### ISSUE TITLE
After upgrading my downloads now get stuck (and a myriad of other issues): how do I start fresh without losing everything?

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#100]
Is there a way I can start fresh without losing the hundreds of accounts I have already backed up? I'm not sure what the issue is, but I think it might be a database issue

**Comment by axcore** [comment]
Firstly, click **Media > Export from database**. In the dialogue window, it's not necessary to select the button **Include lists of videos**. Click the OK button. Let Tartube create the backup file. You now have a backup of the names and URLs for every channel/playlist you added.

Tartube's data folder contains a file called **tartube.db**. Rename it (don't delete it).

Now you can restart Tartube (perhaps having downgraded to an earlier version). Tartube will create a brand new database file.

Click **Media > Import into database > JSON export file**. Import the file you created moments ago.

All the channels/playlists should now be visible in the main window. Click the **Check All** button in the bottom-left corner and wait for it to finish.

Your new database now contains information about all the videos, but it doesn't know that most of those videos have been downloaded already. Click **Operations > Refresh database...** to take care of that.

**Comment by axcore** [comment]
About your myriad other issues, the only big change in v2.1.0 that might affect downloads is the new livestream detection. You could try disabling it. Click **Edit > System preferences... > Operations > Livestreams** and deselect **Detect livestreams announced within this many days**.

**Comment by DankMemeGuy** [comment]
This solved all my problems. Thanks! Not sure what happened in the update process but it was probably just on my end.

**Comment by axcore** [comment]
I reopened the issue as a reminder to myself, to add this question to the FAQ.
