### ISSUE TITLE
How to install tartube using python For Manjaro? and pip3 install does not support for Manjaro and Arch linux?

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#101]
how to Install using PyPI (without root privileges and AUR) for Manjaro

**Comment by candrapersada** [comment]
how to install tartube without AUR

**Comment by axcore** [comment]
Presumably, it is

`pacman -S python-pip`

**Comment by candrapersada** [comment]
but why install failed
Could not find a version that satisfies the requirement gi (from tartube) (from versions: ) No matching distribution found for gi (from tartube)
`pip install tartube`

**Comment by axcore** [comment]
I don't know. I have never used Manjaro.

**Comment by candrapersada** [comment]
but why keep ERROR: Could not find a version that satisfies the requirement gi (from tartube) (from versions: none)
ERROR: No matching distribution found for gi (from tartube)

**Comment by axcore** [comment]
I don't know. I have never used Manjaro.

**Comment by axcore** [comment]
According to [this page](https://pygobject.readthedocs.io/en/latest/getting_started.html#arch-getting-started), you can do this:

`sudo pacman -S python-gobject gtk3`

Or, you can do this:

```
sudo pacman -S python cairo pkgconf gobject-introspection gtk3
pip3 install pycairo
pip3 install PyGObject
```

**Comment by candrapersada** [comment]
why pip3 install PyGObject
correct 'pip3' to 'ypipe' [nyae]?

**Comment by axcore** [comment]
Then, I don't know the answer.

**Comment by candrapersada** [comment]
please find out how to use python for install tartube for manjaro based arch linux

**Comment by axcore** [comment]
It's not possible at the moment. I don't have a fast computer.

**Comment by candrapersada** [comment]
why failed [5.3.5 Manual installation](https://github.com/axcore/tartube#installation).

```
$ python setup.py install  

/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/usr/lib/python3/dist-packages/setuptools/dist.py:397: UserWarning: Normalizing '2.1.020' to '2.1.20'
  normalized_version,
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/test-easy-install-2178.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.6/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.
```

**Comment by axcore** [comment]
Today I tested installing Tartube on Manjaro 20.0.3. These three methods all work:

1. Download and run the source code, using `python3 tartube/tartube`

2. Download from PyPI, using `pip3 install tartube`. PyPI install was broken two days ago, but it's working now.

3. Download and install the AUR package:

```
git clone https://aur.archlinux.org/tartube.git
cd tartube
makepkg -si
```

**Comment by candrapersada** [comment]
how to install pip3 for Manjaro

**Comment by axcore** [comment]
pip3 was already installed on Manjaro, when I installed Manjaro this morning.
