### ISSUE TITLE
feature request: Option to scan for new playlists,then generate playlist folders & playlists for downloads once you specify a folder.

### ISSUE THREAD

**Issue by strunberg** [axcore/tartube#102]
https://www.youtube.com/user/ForgottenWeapons/playlists

That's over 100 playlist for one channel.

**Comment by axcore** [comment]
Unfortunately, it's not possible (as far as I know).

youtube-dl (and therefore Tartube) doesn't know anything about channels and playlists. It sees a webpage with zero, one or multiple videos on it. 

It is you who chooses how Tartube handles this webpage when you click the Add Video, Add Channel or Add Playlist buttons.

(You can test this for yourself by adding a channel with a video link, or vice versa).

**Comment by axcore** [comment]
Tartube v2.3.393 includes a method to extract playlists from a channel (almost) automatically, see [here](https://github.com/axcore/tartube#extracting-playlists-from-a-channel).
