### ISSUE TITLE
how to automatically update tartube without deb again

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#103]
how to automatically update tartube without deb again for ubuntu based?

**Comment by axcore** [comment]
See [5.3.5 Manual installation](https://github.com/axcore/tartube#installation).

If you cannot install using DEB, RPM or PyPI, then just download the source code, and run Tartube without installing anything.

Almost all Ubuntu-based systems already have Python 3, Gtk 3, so you only need to install youtube-dl first.

**Comment by candrapersada** [comment]
the point is how to update versions automatically like ubuntu ppa?

**Comment by axcore** [comment]
That is not possible until someone adds Tartube to the ppa.

**Comment by axcore** [comment]
Closed for inactivity.

**Comment by candrapersada** [comment]
how to auto update tartube from PyPI?

**Comment by axcore** [comment]
https://github.com/axcore/tartube#535-install-using-pypi
