### ISSUE TITLE
Tartube won't start

### ISSUE THREAD

**Issue by Moltkex** [axcore/tartube#108]
Hi. I installed tartube by using the .deb package you provided in Debian buster, however, the app doesn't start and if run from terminal I get this error `Traceback (most recent call last):
  File "/usr/bin/tartube", line 40, in <module>
    import mainapp
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 25, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
`
I really have no idea how to solve that. Looks like some gtk+3 stuff is missing, I tried `sudo apt-get install gtk+3` but this will install a bunch of stuff I prefer not to so just type "n" to cancel.

**Comment by axcore** [comment]
I'm sorry, I have no idea. Compiling Gtk3 by hand is far beyond my level of expertise.

**Comment by Moltkex** [comment]
> I'm sorry, I have no idea. Compiling Gtk3 by hand is far beyond my level of expertise.

Hi. Today I wanted to troubleshoot tartube and see if I could make it work and I didn't need to. I don't know why or how but it worked! I type `tartube` in the terminal to check that error above but instead the app just started! :) So, I guess you can close this. It's fixed.

**Comment by axcore** [comment]
>However, in the Errors/Warning tab there is this Tartube is assuming that Gtk v3.24.5 is broken; some minor cosmetic features are disabled

You can disable the warning by clicking the checkbutton at the bottom of the window, or by updating your system Gtk to at least 3.26 (probably the former option is a lot more convenient)

>EDIT: While the app does start I haven't been able to download anything.

Probably youtube-dl is not installed, or Tartube doesn't know its location - see [here](https://github.com/axcore/tartube#download-did-not-start-error).

The DEB package doesn't list youtube-dl as a dependency because the youtube-dl package is years out of date, cannot easily be updated and interferes with existing youtube-dl installations, leaving both of them unusable.

**Comment by Moltkex** [comment]
`Probably youtube-dl is not installed, or Tartube doesn't know its location - see here.`
This was it. After updating youtube-dl path now downloading work :) Thank you.

**Comment by axcore** [comment]
I'm going to add a warning for DEB/RPM users so everyone knows what to do.

**Comment by Moltkex** [comment]
There's seem to be something wrong with youtube-dl's Buster version cause it kept giving me this error`youtube says: video not available` both form the command line as well as tartube and tried to update but got this `youtube-dl: error: youtube-dl's self-update mechanism is disabled on Debian.
Please update youtube-dl using apt(8).
See https://packages.debian.org/sid/youtube-dl for the latest packaged version.`
but apt kept telling me that the latest youtube-dl's version was installed, so I downloaded the .deb for testing a.k.a Bullseye, installed it, fortunately it gave me no errors and now it works, so Buster's users might want to do that. Just wanted to let you know. I think it's safe to close this now. Thanks so much for your assistance! :+1:

**Comment by candrapersada** [comment]
why The DEB package doesn't list python3-pip as a dependency for youtube-dl from python3?
