### ISSUE TITLE
Icon and Desktop File

### ISSUE THREAD

**Issue by Justinzobel** [axcore/tartube#109]
Neither are installed with `python3 setup.py install`

**Comment by axcore** [comment]
I could not get that working, nor could I find any working examples in other applications, nor did I find any assistance in the documentation or in the usual forums.

At the moment, setup.py only installs icons/desktop files for the DEB/RPM packages.

**Comment by Justinzobel** [comment]
I packages it as it's in the tarball but it could be done in the setup.py I
believe.

**Comment by axcore** [comment]
Yes, in theory it can be done, but how? The documentation is silent.

**Comment by Justinzobel** [comment]
I'm not sure but many other projects have it included. I've only manually
copied the source files to my package directory.

**Comment by axcore** [comment]
Ok, show me some projects that install icons/desktop files from their setup.py, and then I'll just copy what they do.
