### ISSUE TITLE
Channels won't download videos, but other modes will

### ISSUE THREAD

**Issue by profucius** [axcore/tartube#111]
`Tartube v2.1`

Hello, I'm posting with this issue after having tried many things to fix it first. Here is the summary of the issue:

_(clean fresh install and DB, no settings changed)_
I add a youtube channel and set it to download to a folder. I click Check All and it finds the videos, and downloads the thumbnails successfully. I proceed to download videos, starting with just individual ones for testing, by clicking Download and Watch.

### Issue: 
It almost immediately says complete, and does not have a video file downloaded.

I check the channel folder, and it only has the JPG thumbnail files. I also checked the .temp folder, and I see more files such as the xml, etc. But no video files.

### Now, for cross testing, I did this:

_(clean database and settings again, deleted folders)_
I add the youtube channel from earlier, but this time AS a playlist instead. Same process.

**It downloads the videos properly.**

BUT, if I convert that playlist into a channel, after close and reopen Tartube, it will **no longer download the videos** as it was before.

### Further cross testing:

I select individual videos from that channel, and download as temporary videos, and they download properly too.

### Conclusion:

I am unsure what the issue is, as I have started over clean multiple times, and modified nothing in settings, let the application create its own folders, etc. It seems that adding a channel as a Channel makes it so Tartube will not download or save videos at all.

I am willing to do testing or upload logs if you need me to.

**Comment by axcore** [comment]
Can you give me the URL of the channel you're trying to download?

**Comment by profucius** [comment]
This is the main one I am testing on, although I've noticed it with any others:

https://www.youtube.com/channel/UCimiUgDLbi6P17BdaCZpVbg

OS: Windows 10 Pro 1909

**Comment by axcore** [comment]
It's working ok for me. I didn't select any individual videos; just created the channel and then clicked 'Download all'. The videos downloaded without problems.

Make sure youtube-dl is up-to-date (Operations > Update youtube-dl) and probably install FFmpeg, too (Operations > Install FFmpeg). Perhaps you  can show me what you see on the 'Output tab'.

![exurb](https://user-images.githubusercontent.com/37951926/84945729-85f76500-b0df-11ea-85b5-8042600863c7.png)

**Comment by profucius** [comment]
On the newest Youtube-dl 6.16.2020, I cannot seem to reproduce the issue. This can be closed. Thank you.
