### ISSUE TITLE
Thumbnails downloading as both JPG and WEBP

### ISSUE THREAD

**Issue by profucius** [axcore/tartube#113]
> Tartube 2.1
> youtube-dl 2020.06.16.1
> Windows 10

I updated youtube-dl, and proceeded to check/download some videos in a channel. This issue just started occurring.

When running a "check all" on this channel [exurb1a](https://www.youtube.com/channel/UCimiUgDLbi6P17BdaCZpVbg), I am seeing that a few thumbnails download as JPG and then many others download as WEBP format. **Tartube does not seem to be able to read this file format, or have any settings to change the format that thumbnails are downloaded as.**

![image](https://user-images.githubusercontent.com/18254607/84953499-a44e6800-b0c1-11ea-9644-d78c7c10b1d1.png)
-----
![image](https://user-images.githubusercontent.com/18254607/84953576-c5af5400-b0c1-11ea-88ba-98cc3a246cde.png)
-----
-----
To ensure it was not just my configuration, I completely uninstalled and reinstalled Tartube. I re-tested with a [different channel](https://www.youtube.com/channel/UC7IcJI8PUf5Z3zKxnZvTBog).

It happened again, some images are downloading as JPG and some as WEBP. I cannot tell why some are one and the other, but I did try one more thing. I deleted my database file and started fresh one more time. Added the same channel, and it downloaded the exact same JPG and WEBP files for the same videos.

![image](https://user-images.githubusercontent.com/18254607/85139276-2cdc1e00-b212-11ea-90fe-3ded06c45120.png)
-----
![image](https://user-images.githubusercontent.com/18254607/85139401-5c8b2600-b212-11ea-8365-8ced3818957e.png)
-----
### Is anyone else able to reproduce this?

**Comment by axcore** [comment]
Tartube has no control over the file format of the thumbnail: YouTube sends the URL of a thumbnail, and Tartube downloads it. I cannot think of any way to download only .JPG or only .PNG thumbnails.

.WEBP is not one of the image formats that Tartube recognises at the moment. If python/gtk supports .WEBP (I haven't tested it yet), then I can add that functionality.

**Comment by profucius** [comment]
@axcore 
I found with further research that this is a known issue with the newest youtube-dl 2020.6.16

https://www.reddit.com/r/youtubedl/comments/hcin5e/youtubedl_downloading_thumbnails_in_webp_format/

I will close this ticket now.

**Comment by heywolf15** [comment]
[https://github.com/ytdl-org/youtube-dl/issues/21313#issuecomment-499496235](url)

This works for me.
