### ISSUE TITLE
Tartube won't recognize videos in subfolders

### ISSUE THREAD

**Issue by profucius** [axcore/tartube#114]
> Tartube 2.1
> Windows 10

When using Tartube to create channels under subfolders using the General Download Options > Files > Custom, Tartube seems to have an issue recognizing these videos.

### Steps to reproduce:
I am able to add folders in the interface of Tartube, and add channels to these folders, and it works as expected. However, when I add this string to the the Custom filename string:

**%(upload_date)s - %(title)s\\%(upload_date)s - %(title)s.%(ext)s**

and then create a new channel, Check/Download videos, it will create the physical folders under Windows just fine, but then Tartube does not recognize that the videos were downloaded. The "Download & Watch" button does not change to "Player". Again, the videos are there in the subfolders.

However, if I change the above string to remove the subfolder prior to the file name, such as this:

**%(upload_date)s - %(title)s.%(ext)s**

And then re-download that video, it will download it into the channel folder (not in a subfolder obviously) and then Tartube will recognize the video is downloaded and will show "Player" to play the video.

### Conclusion
I would like the ability to subfolder each video inside of a channel, since there are normally about 3-4 files (annotation, subtitle, thumbnail, video) for each video, subfoldering reduces the clutter and keeps things organized.

**Comment by axcore** [comment]
That's a nice idea, but I think it's not possible until youtube-dl itself introduces that feature. Everything in the 'Download options' window is a youtube-dl setting, not a Tartube setting. I
