### ISSUE TITLE
Tartube hangs on checking specific channel

### ISSUE THREAD

**Issue by profucius** [axcore/tartube#115]
> Tartube 2.1
> youtube-dl 2020.06.16.1
> Windows 10

Today I tried to run a check on [this channel](https://www.youtube.com/user/pbsideachannel), and it is hanging on a specific video. I believe it may be the emoji characters in the name. It will not proceed beyond that. It does not throw any errors, it just stays on scanning for hours.

Output log in case it helps:

> youtube-dl --newline -i --hls-prefer-native -o G:/Web/YouTube/Learning/Philosophy/PBS Idea Channel/%(upload_date)s - %(title)s.%(ext)s --write-description --write-info-json --write-annotations --write-thumbnail -f 22 --write-sub --embed-subs --dump-json --download-archive G:/Web/YouTube/Learning/Philosophy/PBS Idea Channel/ytdl-archive.txt --verbose https://www.youtube.com/watch?v=5GNZ48_NJcc
[PBS Idea Channel] <Simulated download of: '20170609 - Comment Responses - ☠ Yarrr! Content ☠'>

-------

I tricked Tartube to skip it by setting the download before date, it proceeded until it hit another video it hung on:

> [PBS Idea Channel] <Simulated download of: '20151223 - ❆ Snow Globes! And A T-Shirt Challenge! ❆ _ Idea Channel _ PBS Digital Studios'>

**Comment by axcore** [comment]
I was able to check the whole channel without any problems, however my machine is running Linux, not MS Windows.

![pbsidea](https://user-images.githubusercontent.com/37951926/85231743-a7af5f80-b3f1-11ea-9c53-6892b60732a3.png)

In theory, there is no reason why emoji characters should cause a problem (Python 3 uses unicode by default), but I don't have a MS Windows installation right now, so I haven't tested that specific situation yet.

**Comment by profucius** [comment]
This ticket can be merged into:

https://github.com/axcore/tartube/issues/106

**Comment by axcore** [comment]
Today I tested the [same channel](https://www.youtube.com/user/pbsideachannel) on Windows 10, Python 3.8, YouTube-dl v2020.6.16.1. I didn't notice any problems. I was able to 'Check' the whole channel without delays. The unicode characters are visible.

The next release will be ready this weekend. I will add quotation marks "..." around all file names; perhaps that will fix your problem.

**Comment by axcore** [comment]
@profucius I believe that I have fixed this error. The fix is in v2.2.046, released today.

**Comment by profucius** [comment]
> 
> 
> @profucius I believe that I have fixed this error. The fix is in v2.2.046, released today.

Is this version posted on Github? Because I am not seeing .046, the last one I see is .007 from 29 days ago.

**Comment by axcore** [comment]
It is only on Github/Pypi at the moment. The installers takes several hours to create, so I don't create new installers every time I tweak a few lines of code.

You can easily download the new code from github, and copy it to **C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube\**, replacing the code that was already there.
