### ISSUE TITLE
Single/Multi instance setting

### ISSUE THREAD

**Issue by profucius** [axcore/tartube#116]
Please add an option in settings to allow only a single instance of Tartube to be running at any given time. Currently, if Tartube is running and minimized to the Windows taskbar, it is not always obvious that it is running. Opening Tartube via the shortcut will open another instance, and it will be unable to access the database file which is locked.

An elegant solution to this would be to have Tartube detect that it is already running, and to then restore the current instance window on-screen. This fulfills the end-user's intention, to see the Tartube window. If the end user wants multiple instances, then a setting in the program options would allow that instead.

**Comment by axcore** [comment]
Unfortunately, it does not seem to be possible.

Long, boring explanation: A Gio.Application registers itself, either as unique or non-unique, when the application itself is created. This happens long before any config files can be read. Once registered, the setting cannot be changed.

I have added a global flag to the Tartube executable (this will be in the next release).

`# Flag set to True if multiple instances of Tartube are allowed; False if
#   only a single instance is allowed
__multiple_instance_flag__ = True`

If you like, you can edit the source code, changing the value to `False` (it must be capitalised). This will prevent multiple instances of Tartube from starting.

At the moment, that's the best I can do.

**Comment by axcore** [comment]
The commented-out code was added in v2.1.051.
