### ISSUE TITLE
Edit channel/playlist url

### ISSUE THREAD

**Issue by mbnoimi** [axcore/tartube#117]
Hi,

I've tens of channels and I want to edit channel/playlist url but ui doesn't accept this behavior. 
May you please enable editing channel/playlist url

Side question:
What's the type of TT database? I suppose it's not SQLite, is it true?

I'm using v2.1.020

**Comment by axcore** [comment]
The Tartube database file is created by the [python pickle module](https://docs.python.org/2/library/pickle.html), so it's not SQLite or anything like that.

**Comment by axcore** [comment]
Changing the URL of channels/playlists was added in v2.1.051.

**Comment by mbnoimi** [comment]
> The Tartube database file is created by the [python pickle module](https://docs.python.org/2/library/pickle.html), so it's not SQLite or anything like that.

I don't know what's the reason of using this module but I find it not a good/safe choice. SQL much better for modifying the options (in my case I want to modify many links) and much safer in case of crashing (my TT database corrupted many time and I'm sure if you used SQL it's nearly impossible to corrupt)

**Comment by mbnoimi** [comment]
> Changing the URL of channels/playlists was added in v2.1.051.

Thanks a lot

**Comment by axcore** [comment]
>I don't know what's the reason of using this module but I find it not a good/safe choice. SQL much better for modifying the options (in my case I want to modify many links) and much safer in case of crashing (my TT database corrupted many time and I'm sure if you used SQL it's nearly impossible to corrupt)

I describe a "Tartube database", but it's not really a database. It's just a collection of data stored as dictionaries/associative arrays. Pickle is the standard python module for loading/saving this kind of data.

About SQL, I have nothing but bad experiences with it. I haven't experienced the TT database corruption you describe. You can create a new Github issue for that, if you like.

**Comment by mbnoimi** [comment]
> You can create a new Github issue for that, if you like.
Unfortunately this issue is frequently occurs the bad thing I couldn't catch how this occurs to be able to create a ticket for it!

**Comment by axcore** [comment]
Go ahead and create a ticket. Until now, it was not worth adding support for SQL. But if Tartube crashes a lot, while saving the database, then that's a good reason to add SQL support.
