### ISSUE TITLE
icons appear missing in classic mode

### ISSUE THREAD

**Issue by easyink** [axcore/tartube#118]
I just installed tartube and on the classic mode tab, a lof ot the buttons don't seem to have icons on them. The buttons themselves actually work, but I have to hover my cursor over them to see what they do. Is there a way to fix this?
[here is a screenshot of what it looks like](https://imgur.com/a/iXTl4a6)

**Comment by axcore** [comment]
Which operating system are you using? How did you install Tartube?

**Comment by easyink** [comment]
I'm using Windows 10 Pro Version 1909. 
I installed Tartube from the sourceforge link on the readme (64-bit).

Now that I think about it, a potential reason was because i installed Tartube on an external hard drive. I'll uninstall and reinstall on a different drive and see if it makes a difference.

**Comment by easyink** [comment]
Alright, I reinstalled on an internal hard drive and it doesn't seem to have fixed the missing icons.

**Comment by axcore** [comment]
I have added an alternate set of icons that will be in this weekend's release.

**Comment by axcore** [comment]
Added in v2.1.051. 

Click **Edit > System preferences... > Windows > Main window > Replace stock icons with custom icons**, then restart Tartube.
