### ISSUE TITLE
Cannot specify Preferred Format Options per channel

### ISSUE THREAD

**Issue by profucius** [axcore/tartube#119]
Many of the channels that I watch, I am satisfied with simple 720p for saving space. I have the Default Download Options set to download "mp4 [720p] <22>" and it works well.

However, there are certain channels that I wish to download the highest quality possible. When I right click this channel, and set specific Download Options for it, I've noticed that when changing the video format under the "List of preferred formats" for only that channel, it will then change that format under the default download options as well.

It seems as though this is a bug where the software is not actually separating video format choice for individual channels. Important note, all other options under the individual download options do actually separate. For example, I can change the file mask for a single channel, and it does not change the file mask for general download options. It seems right now that only the file format is affected.

I've attached a screen cap gif below demonstrating the issue:

![tartube bug](https://user-images.githubusercontent.com/18254607/86377645-93bbf700-bc56-11ea-91f3-2701198dde41.gif)

**Comment by profucius** [comment]
Alternatively, will you please make the software allow us to use command line for formats? I actually prefer using this line to the format list on the Formats tab, it seems to work better when using the youtube-dl command line, and it would technically fix my issue.

`-f 'bestvideo[height=720]+bestaudio'`

When I try using that in a specific channel download options, it ignores it for what is in the Formats tab, even if it is empty.

Example Output Log below, when I erase all formats in the Formats tab, and use the above command line on the General tab under "Extra youtube-dl command line options"

> [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--newline', '-i', '--datebefore', '20200702', '--hls-prefer-native', '-o', 'G:/Web/YouTube/Learning/Personal Dev/August Bradley, Notion/%(upload_date)s - %(title)s.%(ext)s', '--write-description', '--write-info-json', '--write-annotations', '--write-thumbnail', '--write-sub', '--embed-subs', '-f', "'bestvideo[height=1080]+bestaudio'", '--download-archive', 'G:/Web/YouTube/Learning/Personal Dev/August Bradley, Notion/ytdl-archive.txt', '--verbose', 'https://www.youtube.com/channel/UCfqj2oq6LVmR3ybC2nfjqKg']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.2 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: ()
WARNING: video doesn't have subtitles
ERROR: requested format not available
Traceback (most recent call last):
  File "D:/portablez/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "D:/portablez/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "D:/portablez/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1635, in process_video_result
    raise ExtractorError('requested format not available',
youtube_dl.utils.ExtractorError: requested format not available

**Comment by profucius** [comment]
Note: I can work around this using the "Extra youtube-dl command line options" under the General tab for Download Options, only if I have the Formats tab list empty.

Example:

> bestvideo[height=1080]+bestaudio

Does download 1080p videos.

**Comment by axcore** [comment]
Nice catch. Fixed in v2.1.051.
