### ISSUE TITLE
Upload release binaries to github

### ISSUE THREAD

**Issue by djmattyg007** [axcore/tartube#123]
Github releases are far more convenient than Sourceforge releases

**Comment by axcore** [comment]
How do I do that? I can't see any button for adding release binaries (for example, after clicking `Releases > Edit`

**Comment by djmattyg007** [comment]
I believe this was already covered in another issue filed last year by someone else:

https://github.com/axcore/tartube/issues/13

Looks like the up-to-date documentation link is here:

https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

**Comment by axcore** [comment]
Oh, so you can't edit an existing release. Well, that's a shame :)

**Comment by djmattyg007** [comment]
That doesn't seem accurate. When I visit this link for a repo I own, I see an "Edit Release" button in the top-right corner of the page:

https://github.com/djmattyg007/ts3-idle-client-mover/releases/tag/2.0.0

If you go to this page, do you see something similar?

https://github.com/axcore/tartube/releases/tag/v2.1.051

**Comment by axcore** [comment]
Ok, I have done that.
