### ISSUE TITLE
Tartube cannot start because it cannot find its icons folder

### ISSUE THREAD

**Issue by axcore** [axcore/tartube#125]
After installing from source I get the following error:
`Tartube cannot start because it cannot find its icons folder`

**Comment by uali6981** [comment]
I also get this error.
Please help me.

**Comment by axcore** [comment]
In what situation do you get the error? How are you installing Axmud? What operating system are you using?

**Comment by uali6981** [comment]
from source installing
ubuntu 20.04
after installing I got error

**Comment by axcore** [comment]
Try a different install method - install [from PyPI](https://github.com/axcore/tartube#535-install-using-pypi), use the [.DEB package](https://github.com/axcore/tartube#531-install-using-the-deb-package), or [run it without installing it](https://github.com/axcore/tartube#5310-run-without-installing).

**Comment by uali6981** [comment]
.deb package work for me
thanks
