### ISSUE TITLE
Change 'download interval' in scheduling to minutes not hours

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#129]
Currently you can only setup a scheduling at the minimum every hour. It would be nice if this can be done in minutes. Some channels delete videos in less than an hour for whatever reason.

**Comment by axcore** [comment]
Added in v2.1.057 - you can now choose from a selection of units, including minutes and hours. 

The new code can be downloaded from github or pypi. I won't updated the main installers yet because I'm waiting for a youtube-dl fix.
