### ISSUE TITLE
Disable 'download complete' dialog option

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#131]
When having the scheduling set up, the download complete box comes up after every time it runs...this can get quite overwhelming. Would be nice if there was option to disable this from popping up or putting the information elsewhere in the software that the operation completed without making it a dialog

**Comment by axcore** [comment]
Disable the dialogue window:

**Edit > System preferences > Operations > Notifications** 
Select **Show a desktop notification...** or **Don't notify the user...**

**Comment by DankMemeGuy** [comment]
Thanks! I tried looking around for it but I must've gone right past it. Works well, thank you!
