### ISSUE TITLE
Private Playlist

### ISSUE THREAD

**Issue by IgnisQuisVir** [axcore/tartube#132]
I dont know how to download a private playlist. Workaround is to make it public, but the Error Message suggests:
ERROR: This playlist is private, use --username or --netrc to access it.
How can I use that options in tartube?

**Comment by axcore** [comment]
Short answer: Click **Edit > General download options...** (if you're using the Classic Mode tab, click menu icon in the top-right corner and select **Edit classic download options**

In the new window, you can add any youtube-dl options you like, for example:

![username](https://user-images.githubusercontent.com/37951926/87880588-bab25100-c9ea-11ea-98f1-dfec647f87b1.png)

For a list of youtube-dl options, click [here](https://github.com/ytdl-org/youtube-dl/).

Long answer: open the same options window. If the **Show advanced download options button** is visible, click it. Now click the **Advanced** tab, and enter yourusername/password there. 

Longer answer: I don't have a YT channel so I have never tested whether those options actually work or not.

**Comment by IgnisQuisVir** [comment]
Thank you for the very fast reply. I could not get it to work with youtube, but I guess it is either a user error or related to youtube-dl.
