### ISSUE TITLE
Independent download only downloads loose videos

### ISSUE THREAD

**Issue by saeidscorp** [axcore/tartube#134]
Hi,

According to docs, if I understand correctly, it should be possible to "check" a playlist first, possibly remove any unwanted videos from it, then do a "Custom download all" to fetch all. But custom download operation only attempts videos that are not inside a playlist in the database.

The normal download operates on playlists too, but can't hand-pick videos that way.

So, I think there's a documentation/feature mismatch, and I'd rather have the feature than have the docs cleared up :wink:

**Comment by axcore** [comment]
I tested this, and confirmed that it is not working as it should be. For example:

1. Add a playlist
2. Check the playlist (e.g. right-click it, select **Check playlist**)
3. Select **Edit > System preferences... > Operations > Custom > In custom downloads, download each video independently of its channel or playlist**
4. Right-click the playlist and select **Custom download playlist**

...then I see a dialogue window saying **There is nothing to download!** even though the playlist's contents exist in the Tartube database.

A temporary workaround is:

1. Select **Edit > System preferences... > Operations > Custom > In custom downloads, download each video independently of its channel or playlist**
2. Left-click the playlist to select it
3. Left-click one of the videos in the playlist
4. Now press CTRL + A to select all videos in the playlist (at least those that are visible on the current page)
5. Right-click the videos, and select **Custom download videos**


1. Use the main menu: Livestreams >

**Comment by axcore** [comment]
Fixed in v2.1.065. You can now right-click a channel/playlist and perform a custom download.
