### ISSUE TITLE
Feature request: allow opening duplicate videos from tartube itself

### ISSUE THREAD

**Issue by saeidscorp** [axcore/tartube#135]
Setting a shared download destination to avoid redundant downloads is pretty handy, but it'd be way better if, after download, the "Player" button was present on the duplicate video from the secondary playlists (instead of the "Download & watch" button). This way we don't have to manually find the file in file manager to watch it.

Maybe also an indicator in the video description/buttons area showing the duplicate status.

**Comment by saeidscorp** [comment]
It seems that starting an operation resets the downloaded status of previously downloaded videos (and after stopping prematurely, they remain "un-downloaded").

So, maybe the above issue/feature proposal is not applicable and is a result of that. Will test again tonight to verify that.

**Comment by axcore** [comment]
Hi @saeidscorp, I have investigated this using a pair of channels, YouTube and BitChute, on which a single creator posts duplicate videos. I wasn't able to reproduce the conditions you describe:

- On the YouTube videos, I see buttons for Player/YouTube/HookTube/Invidious

- On the BitChute videos, I see buttons for Player/Website

- Downloading one channel or the other did not reset the downloaded status of videos in either channel

If you could give me the URLs of the playlists that are causing you problems, I could test them directly.
