### ISSUE TITLE
Make Tartube download thumbnails in a different subfolder than the videos

### ISSUE THREAD

**Issue by piperun** [axcore/tartube#139]
Windows 10 64bit.
If I disable "Write the video's thumbnail to the same folder" it does not download the thumnails anyhwere, it would be nice if we could have Tartube create a thumnail folder which contains all the thumbnails along side the videos.

**Comment by axcore** [comment]
Unfortunately, thumbnails are downloaded by youtube-dl itself, and there is no option to specify a different folder. You can check the [list of options](https://github.com/ytdl-org/youtube-dl/), if you like.

**Comment by piperun** [comment]
Couldn't you perhaps queue youtube-dl up?
i.e.

* create thumbnail folder & cwd to thumbnail
* queue up 1 instance of youtube-dl to download files into cwd
* when done, change cwd to ".." and make another instance of youtube-dl to only download the videos

I know it's a bit of a hack to work around youtube-dl's limitation, but should still be possible to implement.

**Comment by axcore** [comment]
In v2.2, Tartube can move thumbnails into a /.thumbs folder. It can also move description, metadata and annotation files into a /.data folder.

On MS Windows, these folders should be visible to everyone. On Linux, they are invisible by default. You can usually reveal them by pressing CTRL+H.

The new feature is disabled by default. To enable it, click **Edit > Download options... > Files > Write/move files**, and select the checkboxes.

The new feature only affects new downloads. If you want to move files you've already downloaded, click **Operations > Tidy up files...** and then select **Move thumbnails into own folder** and/or **Move other metadata files into own folder**, then click OK.
