### ISSUE TITLE
'deleted folder'

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#140]
I feel bad for all the tickets I submit, but I use this a lot, so really appreciate bearing with me!

It would be nice if there could be a folder similiar to the 'new videos' 'livestreams' etc that had 'deleted videos' aka videos that the channel has deleted. Would be nice to know if any videos got deleted that I have a copy of in case I need to redistribute the video etc.

**Comment by axcore** [comment]
> I feel bad for all the tickets I submit, but I use this a lot, so really appreciate bearing with me!

Submit as many tickets as you like, it's all good.

> aka videos that the channel has deleted

When you say "the channel has deleted", what exactly do you mean? Do you mean, that the content creator has deleted a video from their channel?

**Comment by axcore** [comment]
Edit: on further reflection, that is obviously what you meant, so no need to reply.

**Comment by axcore** [comment]
Added in v2.1.065. See the instructions [here](https://github.com/axcore/tartube#detecting-missing-videos).
