### ISSUE TITLE
"JSON load failure"

### ISSUE THREAD

**Issue by mel77777** [axcore/tartube#141]
When I try to open Tartube, a dialog box with the following message appears:
"Tartube v2.1.051
Tartube failed to start because:
Failed to load the Tartube config file (JSON load failure)
If you don't know how to resolve this error, please contact the authors here"

I've been able to use Tartube before - it's a very useful program, thank you for developing it!- but now it won't work at all :( 

I am using Linux Mint Cinnamon. Also, I've tried removing Tartube from my system (using Software Manager) and then installing it again, but this won't fix the problem - in fact, it doesn't seem to uninstall!

Any help would be much appreciated. Thank you!!

**Comment by axcore** [comment]
Short fix: delete the config file. When Tartube restarts, it will create a new one. (You may have to change a few settings to their original values).

On Mint, the config file is `/home/YOUR_ACCOUNT/.config/tartube/settings.json`. The .config directory is hidden. To show it, press CTRL+H in the file manager window.

Long fix: Send me a copy of that settings.json file so I can work out why it won't load.

**Comment by mel77777** [comment]
Thank you so much, your short fix worked perfectly, and everything seems alright again! 

I don't need the long fix now, but I'll attach my config file, just in case you'd be interested to know what went wrong (please disregard unless you want to look at it).

Thanks again! 
[settings.json.zip](https://github.com/axcore/tartube/files/4988760/settings.json.zip)

**Comment by axcore** [comment]
The second half of the file is missing for some reason. Probably the system process was interrupted right in the middle of writing the file. Tartube makes backup copies of the database file to protect against exactly this kind of situation, but there are no such protections for the config file.
