### ISSUE TITLE
Downloading pre-existing file

### ISSUE THREAD

**Issue by pkej** [axcore/tartube#142]
I had a directory with files I've downloaded with youtube-dl in the past. When I add the URL to the same file it is accepted by Tartube, as I would have expected. When I right-click on the item in the list and select "Download video" or "Re-download this video" the process is started for downloading the video. 

When I go to the "Output"-tab and to "Thread #1" youtube-dl reports:

[info] Writing video description metadata as JSON to: [json-file]
[YouTube] Downloading thumbnail ...
[YouTube] Writing thumbnail to: [thumbnail]
[download] [file] has already been downloaded 
WARNING: There's no description to write.
WARNING: There are no annotations to write.

When I go to the "Show video->Properties..." right button menu the "Video properties" window shows:

#171 (video with no name)
Listed as: (video with no name)
Contained in [Folder]
Video url: [video url]
File:
Duration:
File size:
Upload time:
Receive time: [now]

and only "video has been downloaded" is ticked in the box.

Expected behaviour:

All the info should be filled in.

**Comment by axcore** [comment]
Hi @pkej, see [this](https://github.com/axcore/tartube#importing-videos-from-other-applications).

**Comment by pkej** [comment]
Thank you. It doesn't quite seem to work for all files, I've had to remove some, and retry, and also I've had frequent crashes while adding large directories. I tried adding just few files around 20, then 50 and it always crash when there are a large number of files. It seems impossible to import a large collection of files.

**Comment by axcore** [comment]
I will test adding large directories on MS Windows and get back to you. In the past I have added folders containing tens of thousands of videos in one go, without problems.

**Comment by axcore** [comment]
I did some testing and eventually I uncovered some rare python errors that could cause a freeze and/or crash. That might explain some of your problems. 

I have uploaded the fixesto github and pypi. If you want to try them, you can download the source code from here, and copy it staight over the existing Tartube files (on MS Windows, they are in `C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube`. (You might need to enable hidden folders first).

**Comment by axcore** [comment]
Several issues with importing files were fixed in v2.2.0. These fixes are now available in all installers.
