### ISSUE TITLE
Export channels in a simple textfile

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#143]
I keep getting the error when trying to save the plain text file of a folder. It doesn't matter what folder I try it in. It says "failed to save the database export file"

**Comment by axcore** [comment]
I tried this on a few systems and I didn't notice any problems.

The file-writing routine is the simplest python code imagineable, so I think it must be an issue with your system:

![filewrite](https://user-images.githubusercontent.com/37951926/89704373-25e8a680-d94b-11ea-8121-dacf2e8c5a64.png)

If you want to hack a workaround, you could write the file to the terminal, then copy-and-paste from there. To do that with v2.1.065, open the ../tartube/tartube/mainapp.py file in a text editor, and line 12561

`outfile.write(line + '\n')
`
to

[print(line)
](url)
...making sure that yuo preserve the indentation.

**Comment by axcore** [comment]
I tested a large database (70000 videos, 300 channels) on MS Windows 10, 64 bit. I was able to save the export file both on C: and on an external hard drive, Z:.

**Comment by DankMemeGuy** [comment]
> I tested a large database (70000 videos, 300 channels) on MS Windows 10, 64 bit. I was able to save the export file both on C: and on an external hard drive, Z:.

Interesting. Does Tartube have a log file? I would actually be interested in what's causing that error before doing the workaround with terminal

**Comment by axcore** [comment]
There is a comprehensive logfile system, but you have to edit the source code to enable it,

In ../tartube/mainapp.py find these lines (near the top)

```
# Debugging flag (calls utils.debug_time at the start of every function)
DEBUG_FUNC_FLAG = False
# ...(but don't call utils.debug_time from the timer functions such as
#   self.script_slow_timer_callback() )
DEBUG_NO_TIMER_FUNC_FLAG = False
```

...and change the values to True

```
# Debugging flag (calls utils.debug_time at the start of every function)
DEBUG_FUNC_FLAG = True
# ...(but don't call utils.debug_time from the timer functions such as
#   self.script_slow_timer_callback() )
DEBUG_NO_TIMER_FUNC_FLAG = True
```

There are similar flags in other files, but you probably don't need to enable them in this case.

**Comment by axcore** [comment]
In v2.2.0, I changed the format of the dialogue window that appears, when this problem occurs. It might give us a better clue of what the problem is.

**Comment by axcore** [comment]
Closed for inactivity.
