### ISSUE TITLE
Microsoft Defender SmartScreen stops running of 2.1.070

### ISSUE THREAD

**Issue by pkej** [axcore/tartube#144]
The 2.1.051 version still starts, but the latest build, 2.1.070 gets blocked by Windows Defender SmartScreen. Unfortunately, I can't access the settings so I can't figure out what it thinks is the problem.

**Comment by axcore** [comment]
Are you using the 64 bit or 32 bit installer? Full or portable?

**Comment by TinaRussell** [comment]
I'm having this (or a similar) problem with the installer for version 2.5.100. I downloaded `install-tartube-2.5.100-64bit.exe` from Sourceforge, and when I run it, I get a message saying "Windows protected your PC" and "Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk." (If I click "More info" it says "App: install-tartube-2.5.100-64bit.exe" and "Publisher: Unknown publisher".) I know this is probably a false positive, but I wanted to make absolutely sure before I bypass the warning. Thanks for any help you can provide. BTW, if I try running `install-tartube-2.5.0-64bit.exe`, which I downloaded sometime last year, I don't get this problem.

**Comment by axcore** [comment]
In this situation, you can try one of the online virus scanners, for example [this one](https://www.virustotal.com/gui/file/42a7e35ad1f848229570990f2f55de9d79efc2db12fe4aefcc08b0dd47222413). It looks like this version of Tartube was only flagged by one of the vendors, which is a normal occurence. Try it yourself and see if you get the same result.
