### ISSUE TITLE
Missing videos folder broken

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#145]
Thanks for adding that feature!

I don't think it's working though. I have videos downloaded, and yet there's about 1,000 videos in that folder, yet every video I manually check does exist on my computer, AND exists still on the channel, so it's not actually missing. 

Maybe something isn't set right in the checking mechanism for what construes a 'missing video'?

**Comment by axcore** [comment]
Hi @DankMemeGuy, I tested several channels this morning, and the Missing Videos feature is working exactly as expected.

The checking mechanism does not look at videos on your hard drive. It only looks at the database. (Tartube assumes that the database is exactly the same as the contents of your hard drive). Are you sure that this is the case?

Can you send me a copy of the database, so I can try to reproduce the problem? (I don't need everything, just one channel or playlist. You could make a copy of the whole data folder, `tartube-data`, then remove everything except one channel/playlist, then send me the database file).

**Comment by DankMemeGuy** [comment]
I removed all the videos from the missing folder before seeing your suggestion and it hasn't reappeared since. I'll do that if it happens again! Thanks!
