### ISSUE TITLE
Adding/Moving to universal package formats

### ISSUE THREAD

**Issue by thomasfinstad** [axcore/tartube#147]
Would you be willing to add universal package formats for your app?

I would be willing to help with the snap packaging, but have no experience with flatpak or appimage.

**Comment by axcore** [comment]
Hi @thomasfinstad, Tartube already has two packages created by other people (AUR and Gentoo). I would be delighted to add more, if you feel like creating a snap package.

**Comment by mbnoimi** [comment]
+1 for Flatpak

**Comment by axcore** [comment]
@mbnoimi I tried creating a flatpak package but failed, perhaps due to the usual lack of documentation.
