### ISSUE TITLE
Downloading a large channel on a schedule

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#148]
I have a very very large channels downloaded with a few thousand videos. I have a schedule setup for 30 mins, but I notice that these few channels take a long time to go through their entire list of videos to check that that I have them.

Is there any way to add a feature that remembers that I have a channel downloaded and to skip checking all the videos past a certain point? One problem I could see is that a channel could unprivate a video from before than I haven't downloaded, so perhaps Tartube can recheck the entire channel every now and then, but generally only check for newer videos. For example, if I download a channel it can remember that, OR if I have the last few videos downloaded already it could skip the rest, etc. Maybe you have other ideas.

**Comment by axcore** [comment]
Have you tried `Edit > System preferences... > Operations > Performance > Time-saving preferences`?

Alternatively, you could create a second database (Edit > System preferences... > Filesystem > Database > Change), and move the channels with thousands of videos there. If two instances of Tartube are running simultaneously, they will automatically choose both databases.

**Comment by DankMemeGuy** [comment]
Ahh wasn't aware that time saving feature existed. I guess my only concern is that if a channel unprivates a video it wouldn't pick it up, so maybe add a feature to check the full channel every X amount of days or whenever.

I'll do that second database though - good idea! thank you!!
