### ISSUE TITLE
Better visual feedback for installation of youtube-dl

### ISSUE THREAD

**Issue by Azzurite** [axcore/tartube#149]
(I installed on Windows, don't know if there are differences)

Currently, when the program is first started, it asks if you want to install youtube-dl, which is necessary for tartube to work. If you choose to do so, that's it. There's nothing that indicates that it's currently installing. The UI is just responsive but you can't do anything. I was wondering if anything was happening, if it failed starting the installation, or what. Then, after a minute, the "finished installation" popup came.

There should be some kind of feedback that the installation of youtube-dl is ongoing as is normal during those kind of operations, like a popup "Installing..." with a spinning circle somewhere or whatever.

**Comment by axcore** [comment]
On Linux, there are two indications of activity: in the Videos tab, the buttons in the bottom-left are replaced by the text "Updating youtube-dl", and the Output tab shows the process output. Do you see either (or both) of them on you MS Windows box?

**Comment by Azzurite** [comment]
It indeed does these things. But as a new user, you won't see these things. I didn't until you pointed it out. 

First, the program already *starts* with the "install youtube-dl" dialog. If you're a new user, you're reading this dialog and pressing "yes" to install because it makes sense. Now the installation starts and now it's basically the first time you're seeing the interface of the program at all. Naturally, you start at the top left, hovering over the buttons or extending the menu buttons at the top, and just see everything disabled. You've never even seen the bottom left buttons before and you don't know that you should be looking there.

Second, the output tab would theoretically be a natural place to look, but again, as a new user to the program you've literally never seen the interface before. You don't even know an output tab exists. The text of the tabs is even a little greyed out so it's even harder to spot if you don't already know where it is, and you naturally read greyed-out things last. This also applies to the button text, which is also greyed out.

So yeah, I see now that there is some feedback, but it was so bad that I couldn't notice it. This is something that should be in your face so you know what's happening, because it's literally the most important thing for the program to even work at that moment.

**Comment by axcore** [comment]
Where do you suggest the feedback should be displayed, if not in corner?

**Comment by Azzurite** [comment]
I was leaving it open to you :) But if you're asking, after you told me where it already is shown, I would **force** the output tab to be active. You can't do anything anyway so it's fine to do this.

**Comment by axcore** [comment]
Yes, that's reasonable.

**Comment by axcore** [comment]
Added in v2.2.0.
