### ISSUE TITLE
Unable to download video. Error (See post)

### ISSUE THREAD

**Issue by brokenzeus** [axcore/tartube#151]
Hello,

I've an error when I try to download a video.

Error:

ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

I have no idea what the problem is. I'm not experienced with any of this stuff. I've been trying to install youtube-dl-gui but I gave up after spending almost a day trying to set it up. It was impossible!

I installed this following the installation instructions, but now i've an error when I try to download the video.

I tried to test youtube-dl but I received the same error.

Any help is greatly appreciated. I'll be happy to provide more information.

Thanks

**Comment by axcore** [comment]
Hi brokenzeus,

Most SSL certificate errors mean that there's a network problem somewhere between your computer and the website. The problems usually fix themselves, after waiting a day or two.

If you get the same error with youtube-dl, then it might be worth reporting the problem on [their issues page](https://github.com/ytdl-org/youtube-dl/issues), for example see [this one](https://github.com/ytdl-org/youtube-dl/issues/26408). The error message you are seeing is definitely generated by youtube-dl, not by Tartube itself.

**Comment by axcore** [comment]
Closed for inactivity.
