### ISSUE TITLE
handling of handling "Actual path to use" for youtube-dl defaults to PyPi path

### ISSUE THREAD

**Issue by doktor5000** [axcore/tartube#152]
When youtube-dl is already preinstalled and present as /usr/bin/youtube-dl (e.g. when being installed via distro packages) then tartube detects that correctly and uses that as the **Default path to youtube-dl executable**, but for **Actual path to use** it still picks **Use PyPI path ~/.local/bin/youtube-dl**

For some context information, this is in a packaged version of tartube where youtube-dl updates are disabled by setting TARTUBE_PKG_STRICT=1 during build, as we package youtube-dl separately and tartube should use the installed system version of youtube-dl. But it still defaults to the PyPi version which is not present.

Not sure if it's this part https://github.com/axcore/tartube/blob/master/tartube/config.py#L8860 or maybe with the definition of self.ytdl_path_pypi, because I'm not too firm with those menu definitions.

screenshot showing the problem:
![Screenshot_20200823_211308](https://user-images.githubusercontent.com/7667040/90986885-9405ae00-e586-11ea-9353-7776c6121270.png)

Due to this, one would need to change **Actual path to use** to /usr/bin/youtube-dl as otherwise all downloads would fail because ~/.local/bin/youtube-dl is not present. There also seems to be no error handling for that case.

**Comment by axcore** [comment]
Actually, the Tartube code is not as sophisticated as you maybe imagine. There is no auto-detection of the youtube-dl at all; Tartube just guesses.

Much earlier in the development, I reasoned that youtube-dl would be available in the local path for nearly all users. Now that I'm a little more clued up, I accept that some kind of auto-detection is necessary.

**Comment by axcore** [comment]
Tartube v2.2.0 auto-detects the location of youtube-dl, FFmpeg and AVConv (when appropriate).

People who install Tartube using the .deb or .rpm packages should be able to use Tartube right away, without needing to set the location of the youtube-dl executable. (This only affects new installations; Tartube doesn't interfere with settings the user has already made.)

Let me know if you have any problems.
