### ISSUE TITLE
Add feature to convert local video files without any other program besides using Tartube

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#153]
I want a local video file converted without any other program other than using tartube with ffmpeg, partly based on [ffmpeg-gui](https://sourceforge.net/projects/ffmpeg-batch/), will it be supported in the future? like youtube-dl-gui

**Comment by axcore** [comment]
Do you want to convert videos, using FFmpeg, after downloading them? For example:

Monday: download a video
Tuesday: don't use Tartube
Wednesday: convert the video using only Tartube

Is that right?

**Comment by candrapersada** [comment]
want to convert videos, using FFmpeg from local file not from download.
Wednesday: convert the video using only Tartube

**Comment by axcore** [comment]
Added in v2.2.0.

Select a video (or videos). Right-click the video(s), and select **Process with FFmpeg...**

A new window opens. It should be easy to understand. For example, if you want to convert an .`mkv` video to an .`avi` video, just add the file extension .`avi`.

Many FFmpeg procedures require a different output filename, so you can specify that, if you want.

**Comment by candrapersada** [comment]
how to video compressor from file explorer for windows not from videos Tartube?
![Video](https://user-images.githubusercontent.com/36833664/94746033-1bc0b280-03a6-11eb-9cf0-aa9ae932236b.PNG)
and I asked for ffmpeg based gui not command-line?
![image](https://user-images.githubusercontent.com/36833664/94745728-7279bc80-03a5-11eb-9456-5539575737e8.png)
![image](https://user-images.githubusercontent.com/36833664/94745747-7dcce800-03a5-11eb-9428-138b8f71281b.png)

**Comment by axcore** [comment]
>how to video compressor from file explorer for windows
I don't know. I never use Windows.

**Comment by candrapersada** [comment]
> I don't know. I never use Windows.

video compressor from directory (folder)

> I don't understand. Which ffmpeg gui?

gui from [FFmpeg Batch AV Converter](https://sourceforge.net/projects/ffmpeg-batch)

**Comment by axcore** [comment]
> video compressor from directory (folder)

Your question is, "How do I XXXXX on Windows?" and my answer is, "I don't know, because I never use Windows"

>FFmpeg gui from FFmpeg Batch AV Converter or FFmpeg wizard from FFmpeg Converter wizard

Yes, that would be a nice feature. Unfortunately drag-and-drop does not work on Windows. (It is a Gtk problem, not a Tartube problem, so there is nothing that I can do).

**Comment by candrapersada** [comment]
> Your question is, "How do I XXXXX on Windows?" and my answer is, "I don't know, because I never use Windows"

video compressor from directory (folder) for file manager Linux Tartube Classic Mode
![image](https://user-images.githubusercontent.com/36833664/94776101-4a14b100-03eb-11eb-9919-19763abaca5a.png)

**Comment by axcore** [comment]
I don't understand, what you want. Can you explain it more clearly?

**Comment by candrapersada** [comment]
add compress video without software others

**Comment by axcore** [comment]
What sort of compression?

**Comment by candrapersada** [comment]
compress video from 500 MB to 50 MB

**Comment by axcore** [comment]
I don't know how to do that.

**Comment by candrapersada** [comment]
you must use [FFmpeg](https://sourceforge.net/projects/ffmpeg-batch) like this picture
![image](https://user-images.githubusercontent.com/36833664/94796956-ac7caa00-0409-11eb-9b85-e051da0c786b.png)
![image](https://user-images.githubusercontent.com/36833664/94796983-b4d4e500-0409-11eb-925c-1a1f0ba073b1.png)
for convert video from 500 MB to 50 MB

**Comment by candrapersada** [comment]
I ask for a gui like this one drawn
![image](https://user-images.githubusercontent.com/36833664/94799359-311cf780-040d-11eb-96c4-0b601f2b1175.png)
![image](https://user-images.githubusercontent.com/36833664/94799459-590c5b00-040d-11eb-90ef-f286154aa547.png)

**Comment by axcore** [comment]
Ok! Now I understand.

**Comment by candrapersada** [comment]
and add convert video for Click the + button to select a directory (folder). All the videos are into this directory like this picture
![image](https://user-images.githubusercontent.com/36833664/94801369-1ef08880-0410-11eb-8a2e-2895aa04fcf5.png)

**Comment by DankMemeGuy** [comment]
@candrapersada have you considered just using [Tdarr](https://github.com/HaveAGitGat/Tdarr)? It's what us with big collections use. Automated and very bulk processing. Plus having a separate system for compression can be good for possible failure point separation. It's also very very robust, and has analytics.

**Comment by axcore** [comment]
I investigated this. I decided that FFmpeg is too complicated. I don't understand most of it. Therefore, I cannot write a GUI.

If someone else wants to write a GUI, they can modify the class `ProcessDialogue` in the `mainwin.py` file. I will be happy to include the modification in a future release.

**Comment by axcore** [comment]
By the way: in v2.2.046, you can drag-and-drop videos from Tartube to another application.

So, if your FFmpeg converter accepts drag and drop, maybe you can use it.

**Comment by axcore** [comment]
In v2.2.173 I added a GUI for FFmpeg. It is very similar to [FFmpeg Command Line Wizard](https://andrekr.github.io/ffmpeg-command-line-wizard/).

Right-click a video, and select **Process with FFmpeg...** 

A new window opens. It is similar to the old window.

![nov3](https://user-images.githubusercontent.com/37951926/99827981-43d0c480-2b52-11eb-959d-21c27ee60215.png)

If you want a GUI like  [FFmpeg Command Line Wizard](https://andrekr.github.io/ffmpeg-command-line-wizard/), then click the button **Show more FFMpeg options**.

![nov4](https://user-images.githubusercontent.com/37951926/99828019-50551d00-2b52-11eb-811a-4cfc71ca87b3.png)

There is a profile manager for FFmpeg options. Click **Edit > System preferences... > Options > FFmpeg options.** 


![nov5](https://user-images.githubusercontent.com/37951926/99828193-8b575080-2b52-11eb-8725-4105a3883d5b.png)

You can create as many profiles as you want. One profile is the 'current' profile. When you right-click a video, you see the 'current' profile.

You can rename profiles, and import/export them.

**Comment by axcore** [comment]
If you are happy with it, then you can close the issue.

**Comment by candrapersada** [comment]
how to add video from file manager?
![gambar](https://user-images.githubusercontent.com/36833664/99854051-ae1b5080-2bb6-11eb-9d91-660fa7b84246.png)
![gambar](https://user-images.githubusercontent.com/36833664/99854254-11a57e00-2bb7-11eb-803e-daf4412d210b.png)

**Comment by candrapersada** [comment]
how to merge audio and video to mp4 use Process with FFmpeg for Classic Mode?
![image](https://user-images.githubusercontent.com/36833664/100058459-e68f8880-2e5b-11eb-9211-daaf51ec5418.png)
from file manager

**Comment by axcore** [comment]
>how to merge audio and video to mp4 use Process with FFmpeg for Classic Mode?

What is the FFmpeg command for that? (I don't know, but maybe you know).

**Comment by axcore** [comment]
>how to add video from file manager?

In v2.2.198 you can drag-and-drop videos from the file manager into the FFmpeg options window. Sorry, but you can only drag-and-drop Tartube's videos (in other words, videos that are visible somewhere in Tartube)

>how to merge audio and video to mp4 use Process with FFmpeg for Classic Mode?

In v2.2.198 there is a new FFmpeg option. If there is a video and an audio file with the same name, they are combined.

I have not been able to test this properly, but the FFmpeg command is the one used here: [https://davidwalsh.name/combine-audio-video](https://davidwalsh.name/combine-audio-video), so it should work.

**Comment by candrapersada** [comment]
why convert video doesn't work for playlists and japanese fonts for Classic Mode for MS windows?
![aaaa](https://user-images.githubusercontent.com/36833664/104788596-2c662e80-57c5-11eb-93f3-10cd45300a59.PNG)

**Comment by axcore** [comment]
>why convert video doesn't work for playlists

The popup menu (right-click a channel or playlist) is already too full, I don't want to add another menu item there.

If you want to process every video in a playlist, you can press CTRL+A to select every video, then right click one video, and select **Process with FFmpeg...**

**Comment by axcore** [comment]
>and japanese fonts for Classic Mode for MS windows?

I know nothing about Windows, so I don't know how to fix this.

It works correctly under Linux.

![japanese](https://user-images.githubusercontent.com/37951926/104809934-14080b00-57e9-11eb-962f-5cafdbae1e4b.png)
