### ISSUE TITLE
Not getting best quality

### ISSUE THREAD

**Issue by Slusho64** [axcore/tartube#155]
I want to download the best quality available for each video in playlists. I tried downloading a playlist with two videos: one available up to 4K and the other 1080p. Both downloaded as 720p mp4s. I changed some settings (not sure what) and then they both downloaded as two webms each: video and audio, this time in the highest resolutions possible although one of them had seemingly too-bright text compared to the video on YouTube. I didn't want separate files for audio and video nor the brightness issue so I tried adding every regular mp4 and webm format option (ones without DASH, 3D, or HDR) in descending order of resolution (and then the numbers inside of the <>). Doing this caused errors that the formats are not available. I also tried installing ffmpeg and setting "If a merge is required..." to mp4 and adding the mp4 option to preferred formats, as well as doing the same with webm, and got the same result of format not available. I do see [youtube-dl](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#format-selection) has a "best" format option not listed in Tartube's formats. How can I have tartube download the best quality available in a single file? And what are the numbers inside <> in Formats, and what are the DASH Video formats? Thanks.

**Comment by axcore** [comment]
First question, have you installed ffmpeg? If you are using MS WIndows, you can install it from tartube's menu: **Operations > Install ffmpeg**.

(ffmpeg is usually required for downloading high-resolution videos like 4K.)

**Comment by Slusho64** [comment]
I did install it before but today I removed all of the preferred formats and now it's working. So the issue was not installing ffmpeg before trying to add preferred formats, which prevent videos from being downloaded. I guess I thought ffmpeg was only needed for transcoding but I guess it's needed for combining files and I didn't realize youtube stored video and audio separately and I don't get why it's needed for high-res videos, so maybe add a sentence saying it's required for high-res? Just a thought. But thanks for pointing me in the right direction.

Also, I don't see thumbnails in the program next to videos even though they're downloaded fine and and can be found in the same folder as the videos. I've looked around for a setting but don't see one. Any ideas?

**Comment by axcore** [comment]
A couple of months ago, YouTube changed their thumbnails to a format no-one uses. Therefore Tartube can't display them.

youtube-dl hasn't been updated for a while. We are all waiting for the next update, which will fix the problem.

**Comment by Slusho64** [comment]
I noticed that many of the thumbnails it downloaded were webp but some were jpegs and it doesn't display those either.

**Comment by gnoejuan** [comment]
I unfortunately don't have the discussion thread at hand, but I came across a claim stating "only new videos are affected by changes." My opinion on `YouTube changed their thumbnails to a format no-one uses` is the change should only affect videos uploaded after the change, assuming there is no A/B testing.

**Comment by axcore** [comment]
youtube-dl recently implemented a 'fix' for the thumbnail problem: [see here](https://github.com/ytdl-org/youtube-dl/issues/25687) and [here](https://github.com/ytdl-org/youtube-dl/pull/25717).

The fix does not appear to work on my system. I have no idea when a better fix might be implemented.

**Comment by axcore** [comment]
The thumbnail problem has been fixed in v2.2.0. Tartube should be able to display all YouTube thumbnails, as long as you have FFmpeg installed. (See the [README](https://github.com/) for help with that.)

Following @Slusho64 's suggestion, Tartube will now prompt the user to install FFmpeg, and there are a few new hints about doing that.

**Comment by xbliss** [comment]
> A couple of months ago, YouTube changed their thumbnails to a format no-one uses. Therefore Tartube can't display them.
> 
> youtube-dl hasn't been updated for a while. We are all waiting for the next update, which will fix the problem.

Was this ever resolved? 

My 1080p videos are downloading at 720p even with ffmpeg installed. 

How & where can I specify - Max Resolution or 1080p? 

I'd prefer MKV or MP4 files.

**Comment by xbliss** [comment]
> I did install it before but today I removed all of the preferred formats and now it's working. So the issue was not installing ffmpeg before trying to add preferred formats, which prevent videos from being downloaded. I guess I thought ffmpeg was only needed for transcoding but I guess it's needed for combining files and I didn't realize youtube stored video and audio separately and I don't get why it's needed for high-res videos, so maybe add a sentence saying it's required for high-res? Just a thought. But thanks for pointing me in the right direction.
> 
> Also, I don't see thumbnails in the program next to videos even though they're downloaded fine and and can be found in the same folder as the videos. I've looked around for a setting but don't see one. Any ideas?

What & how did you fix it besides the FFMPEG install? 

> A couple of months ago, YouTube changed their thumbnails to a format no-one uses. Therefore Tartube can't display them.
> 
> youtube-dl hasn't been updated for a while. We are all waiting for the next update, which will fix the problem.

Was this ever resolved? 

My 1080p videos are downloading at 720p even with ffmpeg installed. 

How & where can I specify - Max Resolution  / 4K /1080p ? 

I'd prefer MKV or MP4 files.

**Comment by axcore** [comment]
>My 1080p videos are downloading at 720p even with ffmpeg installed.
I suggest you open a new issue. Try to download a single 1080p video. Then click the **Output** tab and show me a screenshot of the text
