### ISSUE TITLE
Diversifying from youtube-dl

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#158]
Youtube-dl has been heavily [uncommitted for the past few month](https://github.com/ytdl-org/youtube-dl/graphs/commit-activity)s, and there's been a [new fork ](https://github.com/blackjack4494/youtube-dlc/releases)that's kind-of taken on the reigns. Wondering if it would be possible to perhaps give the option of supporting that instead of the original one?

**Comment by axcore** [comment]
I'm aware of the youtube-dl issues. In the next version I'm planning to let the user switch between the original and any fork they like.

Workload is quite heavy at the moment, so the next release won't be until the end of this month.

**Comment by axcore** [comment]
I'm happy that a fork has been created. I didn't want to do it myself...

**Comment by axcore** [comment]
Added in v2.2.0. You can now use youtube-dlc or any other fork of youtube-dl that is similar to the original.

Click **Edit > System preferences... > youtube-dl**, and type the name of the fork.

**Comment by candrapersada** [comment]
why Click Edit > System preferences cannot be opened on tartube portable v2.2.003

**Comment by axcore** [comment]
Fixed in v2.2.007.
