### ISSUE TITLE
Problem MP3 Quality

### ISSUE THREAD

**Issue by KERNEL59** [axcore/tartube#159]
Hi , 

always   **--audio-quality 5**  :( 

in option "post process"  audio quality = high 

help me please

**Comment by axcore** [comment]
I tested it. For me, **--audio-quality** is working correctly.

![quality](https://user-images.githubusercontent.com/37951926/93170966-1d407880-f720-11ea-997e-7bb0a763b814.png)

If you have a problem, you can add **--audio-quality** in **Edit > General download options... > General**

![quality2](https://user-images.githubusercontent.com/37951926/93171142-6ee90300-f720-11ea-9ed0-7b6dfb86a9de.png)

**Comment by axcore** [comment]
Closed for inactivity.
