### ISSUE TITLE
Column width for 'incoming file'

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#161]
On Windows 10, when I resize the column for the 'incoming file', the file names still show "..." and there is wasted space regardless of how wide I make the column. I tried changing it before an operation, or during, and still that happens.

**Comment by axcore** [comment]
I tested this on Linux and MSWin, and I'm not seeing '...' in the Incoming File column. Are you sure you're using Tartube? ;)

![rodtodd](https://user-images.githubusercontent.com/37951926/94454954-72fa3380-01aa-11eb-8f86-d39f2c0ea371.png)

**Comment by axcore** [comment]
I have changed the formatting in v2.2.0. I hope it's better.
