### ISSUE TITLE
Identify Between Automatic Captions and Manual

### ISSUE THREAD

**Issue by DReaper** [axcore/tartube#162]
I currently have Download the Automatic subtitles file checked on. However, when downloaded, you cannot identify whether if it was a manually added subtitle or an automatic one, as it just adds an .en suffix. Is it possible to add an additional suffix, such as .ac or something to identify automatic ones?

The issue is when manual subtitles are added after the fact and I cannot identify which ones need updating.

**Comment by axcore** [comment]
youtube-dl handles subtitles; Tartube doesn't interfere at all. So you should ask for this feature on the [youtube-dl issue page](https://github.com/ytdl-org/youtube-dl/issues).
