### ISSUE TITLE
Tartube Immediately Says Download Complete, but the Status Column Says Error and No File Has Been Downloaded

### ISSUE THREAD

**Issue by muttleytm** [axcore/tartube#163]
I just updated my OS to Linux Mint 20.  I have been using youtube-dl and the youtube-dl GUI for some time.  I did notice that the GUI hadn't been working so well lately, but that wasn't my reason for updating.  When I went to intall youtube-dl GUI I found it was no longer supported and leaned of tartube.

I have used youtube-dl in the command line on this new install successfully both for downloading a video and to download the audio from a youtube video.  So youtube-dl seems to be working OK.

I located the paths to the youtube-dl, ffmpeg binaries in /usr/bin and set that as the path to use in Edit/System Preferences/youtube-dl.

It looks like AVconv is part of the AV tools package which no longer exists. I seem to read that FFMPEG is the substitute.

I do have FFMPEG installed.  I did read that it is different if it is from the Ubuntu repository or the snap repository and that the snap repository has been blocked.

Here is the output from ffmpeg -version:

ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100

Tartube is all new to me.  I only tried it with one video at a time and used it in Classic Mode to keep things simple and tried downloading the file as both vorbis and mp3 format and I think a video format as well.  

TIA

**Comment by axcore** [comment]
Can you show me what happens in Tartube's Output tab, when you try to downoad a video? Either a screenshot, or copy-and-paste the text here.

**Comment by muttleytm** [comment]
I'm attaching some before and after of what is on several tabs of the
tartube screen.

Looks like maybe a Gtk issue???

**Comment by axcore** [comment]
Your screenshots aren't visible, can you try a different method?

**Comment by muttleytm** [comment]
[image: tartubeStart.png]
Initial Screen Before Download Attempt


[image: TartubeAfterDownload.png]
Screen Right After Download Attempt



[image: tartubeoutputafter.png]
The Output Tab Right After Download Attempt



[image: TartubeErrorsWarnings.png]
The Errors/Warnings Screen After Download Attempt

**Comment by axcore** [comment]
Sorry, they still aren't visible. Github is not very helpful, when trying to upload screenshots.

I suggest uploading them to [imgur.com](https://imgur.com/), then you can just copy-paste the links.

**Comment by muttleytm** [comment]
here is a link to a folder on Google Drive with the pictures:

https://drive.google.com/drive/folders/1MBHwEB9BndwHgRe7GneJTrG62T-THM0M?usp=sharing
<https://mailtrack.io/trace/link/0abca03f94db1abe1262d61d3a8f63b9db56cfec?url=https%3A%2F%2Fdrive.google.com%2Fdrive%2Ffolders%2F1MBHwEB9BndwHgRe7GneJTrG62T-THM0M%3Fusp%3Dsharing&userId=1080085&signature=f04cbc685b10157a>

**Comment by axcore** [comment]
You are using an older version of Tartube, in which the format selector in the Classic Mode tab was broken.

Try [installing v2.1.070](https://sourceforge.net/projects/tartube/), I think that will fix your problem.

**Comment by muttleytm** [comment]
Hi,

Thanks for the reply.   I downloaded the deb file on the link you provided
and installed it. The installer said it was already installed so I chose
reinstall.

When I opened tarbube I went to help install and it said it was this
version.

I tried again in classic mode and it still didn't work and behaved as
before.

I then tried using the new interface. I tried the watch and download
option, it acted the same and immediately said download complete and I
didn't view it either.  I then tried watch on youtube and youtube opened
and it played and I tried the other two viewing options.  One (that I've
never used or heard of) said I'd exceeded my limit. I assume it was because
I need an account and there is a limit and I have no account so my limit
would be zero. The other viewing option just took me to a page that it is
no longer under development or supported.

So it might be more to the issue than just the classic tab or maybe
somehow some version numbers got mixed up or something.

**Comment by muttleytm** [comment]
Oh yeah,

I took some screenshots and put them in the same folder that I previously
sent you.  I did grab the link again and here it is:

https://drive.google.com/drive/folders/1MBHwEB9BndwHgRe7GneJTrG62T-THM0M?usp=sharing
<https://mailtrack.io/trace/link/c34f0f6da2d3a8fabaed7686b9f34f7037666aa9?url=https%3A%2F%2Fdrive.google.com%2Fdrive%2Ffolders%2F1MBHwEB9BndwHgRe7GneJTrG62T-THM0M%3Fusp%3Dsharing&userId=1080085&signature=885389e06e30b291>

I think it is the same link as earlier. It links to the same folder in any
event only this time there are a few more pictures in the folder.

Thanks again,

Tom

**Comment by axcore** [comment]
The version numbers are definitely correct, I have been testing the code this week.

Ok, I can download [that video](https://www.youtube.com/watch?v=8ZqRvlsoPhs&pp=wgIECgIIAQ%3D%3D) as an .ogg file, from the Classic Mode tab, just by using the format selector in that tab.

However, when I compare the text in my Output Tab with yours, I notice that the command is different. Therefore you must have opened the **Download options** window, and changed some things there.

So, let's try this:

1. In the main window, click **Edit > General download options...**
2. In the new window, click the button **Completely reset all download options to their default values**
3. Try downloading the video from the Classic Mode tab again

If that doesn't work, try this:

1. In the Classic Mode tab, click the menu button in the top-right corner (it looks like a machine cog)
2. In the menu, if you can see **Use general download options**, then click it. Otherwise, don't worry about it
3. Try downloading the video from the Classic Mode tab again

**Comment by axcore** [comment]
Oh, another thing: If you download audio from a video directly, it doesn't appear in Tartube's main window. Tartube looks for a video file, and finds that the file doesn't exist. It doesn't look for any audio you might have downloaded.

It's worth checking the destination folder, to see if the audio file has been downloaded anyway.

**Comment by muttleytm** [comment]
I just used my file manager and I tried again and created a specified it as the destination folder. Nothing there.  Also, like I mentioned it the window that says file downloaded immediately pops up as does the word error under status. I know for both command line youtube-dl and the old youtube-dl GUI, it took some time to download and it showed the different stages going on in the process.  So I don't think it is that.

I also tried simply trying to download it as an mp4 file or as an audio mp3 file and everything acted the same.

**Comment by axcore** [comment]
In **Edit > System preferences... > youtube-dl > File paths** there are three possible settings for the youtube-dl path. Have you tried all three?

(The next version of Tartube auto-detects youtube-dl, but your version does not.)

**Comment by muttleytm** [comment]
I didn't see this post.  I tried the things you suggested. Both the first
and the second. Still not working.

I have to do something else right now, but I'm thinking of uninstalling
tartube and if it leaves behind and data or settings folders deleting them
as well and starting over again. Does it create and leave any settings
folders? if so the names, etc?

I'll also just try download using youtube-dl command line. It did work a
couple days ago, but I better make sure it doesn't need updating or
something.

**Comment by muttleytm** [comment]
I set all of them to the location where I found the tartube binary.  I
think it was /usr/bin/tartube.

I've uploaded what I have for the settings to the folder I sent the link to
earlier.

https://drive.google.com/drive/folders/1MBHwEB9BndwHgRe7GneJTrG62T-THM0M?usp=sharing
<https://mailtrack.io/trace/link/b7caab7e79acbfbd2cfa1284721a7d00da872afc?url=https%3A%2F%2Fdrive.google.com%2Fdrive%2Ffolders%2F1MBHwEB9BndwHgRe7GneJTrG62T-THM0M%3Fusp%3Dsharing&userId=1080085&signature=36d36f21bc82e61d>

So, now I better go run my erend and get something to eat.

**Comment by axcore** [comment]
From your latest screenshot, it seems that you selected this

**Use PyPi path (~/.local/bin/youtube-dl)**

Which is great, if you installed youtube-dl via PyPI. If you installed it from your system's Software manager, then the binary will be in **/usr/bin/tartube**, and you have to select

**Use default path (/usr/bin/youtube-dl)**

Besides that, can you download the video using youtube-dl alone? That is to say, open a terminal window, and type

`youtube-dl https://www.youtube.com/watch?v=8ZqRvlsoPhs&pp=wgIECgIIAQ%3D%3D`

You can run a similar test from inside Tartube's window. Add the video, right-click it and select **Downloads > Test system command**. Click the OK button, switch to the Output Tab, and see what happens.

**Comment by axcore** [comment]
If you want to remove data files, it's quite easy.

From Tartube's main window, click **Edit > System preferences... > Filesystem > Device**. At the bottom of the window you can see the location of Tartube's configuration file. 

Now click the **Database** tab, and you can see the folder containing the database.

Stop Tartube, delete or rename those things, restart Tartube, and it should be as good as new.

**Comment by axcore** [comment]
Closed for inactivity.
