### ISSUE TITLE
ModuleNotFoundError: No module named 'gi'

### ISSUE THREAD

**Issue by kerim** [axcore/tartube#165]
Tried the Mac instructions. Numerous errors. It thought I found workarounds for most of them, but on the final stage, when I run "python3 tartube/tartube" I get the error "ModuleNotFoundError: No module named 'gi'" None of the workarounds I found on Google work...

**Comment by axcore** [comment]
That type of error is usually associated with running Tartube under python2, rather than python3. Open a terminal, and see what the response to this command is:

` python --version`

**Comment by axcore** [comment]
Closed for inactivity.

**Comment by Daumianeg** [comment]
Sorry for reopening the thread. I was faced with the same issue and I didnt find anything here that would help me. After looking for info for an hour I found out what was the fix.

Executing this command: python3 -m pip install PyGObject
And then launching Tartube with: python3 tartube/tartube worked

**Comment by axcore** [comment]
@Daumianeg, just to clarify, this is a fix for installing on MacOS, right?

**Comment by Daumianeg** [comment]
> @Daumianeg, just to clarify, this is a fix for installing on MacOS, right?

Yes, with the issue mentioned by the OP

**Comment by axcore** [comment]
Great, I will update the installation instructions :)
