### ISSUE TITLE
I get this dialog box on start up: Font not found, using system substitute: Lucida Console

### ISSUE THREAD

**Issue by richardnassour** [axcore/tartube#166]
Title: mintty
Content: Font not found, using system substitute: Lucida Console

Which font is it looking for?

**Comment by axcore** [comment]
Tartube doesn't use any special font, it just uses whatever the system is using.

On Windows, Tartube is run inside an emulator, that emulator is Mintty. I googled around and could not find a matching error message, so at the moment I don't know what to suggest.

**Comment by richardnassour** [comment]
> 
> 
> Tartube doesn't use any special font, it just uses whatever the system is using.
> 
> On Windows, Tartube is run inside an emulator, that emulator is Mintty. I googled around and could not find a matching error message, so at the moment I don't know what to suggest.

I did have a large amount of preinstalled windows fonts removed, those related to non-latin languages in particular, so there's a chance it's looking for one of those. although i don't get this problem with any other app.
