### ISSUE TITLE
Updated to newest version, now it freezes trying to load the database

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#167]
The software was working great, I closed it, updated then when i reopened it it asked for my database, so I showed it the folder and it gets stuck. That happens every time. I've restarted, reinstalled, nothing seems to work. Any ways of trying to recover that database or seeing what's happenig?

It also can't close. I have to go to task manager and end task. But the software itself can still be minimized, but just not closed.

https://i.imgur.com/EtNIf4q.png

I have ensured I have access to the folder (although nothing changed to make it not work). I even installed the software with admin rights, and the folder opens up fine in Windows Explorer.

**Comment by axcore** [comment]
A backup copy of the previous database should have been saved in ../tartube-data/.backups (unless you disabled it). This directory is hidden on Linux, pressing CTRL+H should reveal it.

For seeing what is going on: Edit > System preferences ... General > Debugging has some options you can enable. This should show a lot of debug messages in a terminal window. (You need to re-enable these options whenever you start Tartube.)

**Comment by DankMemeGuy** [comment]
The database itself is fine, I think. But i literally cannot access anything in the toolbar. Everything is disabled except quit, custom download, tidy up files, all the livestream options, and everything in help.

I also cannot start a new database

**Comment by axcore** [comment]
In the dialogue window, are you selecting the option **I have mounted the drive, please try again**, or a different option?

**Comment by axcore** [comment]
In the dialogue window, are you selecting the option **I have mounted the drive, please try again**, or a different option?

**Comment by DankMemeGuy** [comment]
I've tried every option, I made it work once, but when I restrted my computer the same issue happened again.

I created a new folder and then told it to put the database there. It froze, so i reopened it, then it loaded a new database in that new folder. Then I selected my normal database from the menu and it loaded the database fine. When I restarted my computer the same issue happened. I enabled debugging mode though so maybe that will show something

**Comment by axcore** [comment]
Ok, please test v2.2.013. This is available from git/pypi only. You know what to do: download the code, copy it to `C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube`, replacing the previous folder).

I was able to partially reproduce your problem by editing the config file to specify a completely imaginary data folder, `X:\Youtube`. I reorganised the folder-checking code to resolve that problem.

I am not sure yet what is actually causing your problem. I suspect that Python is getting confused about file paths, because it is running inside a Linux emulator. I have added some debug messages, which should give us the answer.

So, try running Tartube in a terminal window. Run `C:\Users\YOURNAME\AppData\Local\Tartube\msys64\mingw64` ), then type 

> cd tartube
> python3 tartube/tartube

Do not turn on the normal debug messages. Just tell me what the new debug messages say.

**Comment by DankMemeGuy** [comment]
Get this error when doing cd tartube after inputting that in the terminal that comes up when doing C:\Users\YOURNAME\AppData\Local\Tartube\msys64\mingw64
```
Adam@Adam-PC MINGW64 ~
$ cd tartube
-bash: cd: tartube: No such file or directory

Adam@Adam-PC MINGW64 ~
$ python3 tartube/tartube


```

**Comment by DankMemeGuy** [comment]
Running "tartube_64bit.bat" inside C:\Users\Adam\AppData\Local\Tartube\msys64\home\user\tartube seems to not cause the problem, oddly enough.

**Comment by axcore** [comment]
After opening the mingw64 terminal, what happens when you type these commands

pwd
ls

**Comment by DankMemeGuy** [comment]
```
Adam@Adam-PC MINGW64 ~
$ pwd
/home/Adam

Adam@Adam-PC MINGW64 ~
$ ls

```

**Comment by axcore** [comment]
Hmmm, that should not be possible. The home directory for all users should be /home/user.

Try this:

```
cd /home/user/tartube
python3 tartube/tartube
```

**Comment by DankMemeGuy** [comment]
That worked!

**Comment by axcore** [comment]
Hmmm, I'm not sure why it works. Did you use the MS Windows installer, or did you perform a [manual install](https://github.com/axcore/tartube#511-manual-installation---ms-windows)?

**Comment by DankMemeGuy** [comment]
I used the installer originally, but then did the pypi manually install as you had suggested with the latest version

**Comment by axcore** [comment]
Right, that explains the directory structure. I will have to update the README to mention it.
