### ISSUE TITLE
Perform schedule even though previous downloads still happening

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#168]
Not sure if this is even possible, but it would be nice to be able to continue schedules even if previous downloads are still happening. Some videos/channels are bigger than others, so even if I have multiple downloading enabled, one channel might take a few hours to download, but Tartube could continue the schedule and keep checking other channels while still downloading that other one.

**Comment by axcore** [comment]
Added in v2.2.046. You can now create as many scheduled downloads as you like. Each scheduled download can download the whole database, or just some of it. I think I have added all the features you wanted.

There are some basic instructions [here](https://github.com/axcore/tartube#612-scheduled-downloads), but everything should be easy to use.

If you had already created some scheduled downloads, they should still exist.

**Comment by axcore** [comment]
Edit: I forgot to add the request you made [here](https://github.com/axcore/tartube/issues/148), but I will do that this weekend.

**Comment by axcore** [comment]
Added in v2.2.055.
