### ISSUE TITLE
Profile Manager - Create, remove, or switch download options Classic Mode profiles

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#171]
add Profile Manager for Create, remove, or switch download options Classic Mode profiles

**Comment by axcore** [comment]
Added in v2.2.046. 

In the Classic Mode tab, you can now add as many download options as you want.

![classic](https://user-images.githubusercontent.com/37951926/96897148-3c9c9500-1486-11eb-9134-c7d826f0282b.png)

**Comment by candrapersada** [comment]
how to remove create new download options?
![Cuplikan layar dari 2020-10-22 23-27-38](https://user-images.githubusercontent.com/36833664/96903598-3deab380-14c0-11eb-8e7f-6312eeb9296c.png)

**Comment by axcore** [comment]
I forgot that, I will add it soon.

**Comment by candrapersada** [comment]
and add export download options.

**Comment by axcore** [comment]
In v2.2.055, added:

- Import download options from a channel, playlist or folder
- Remove download options from the menu, in the classic mode tab (if you don't need them any more)

**Comment by candrapersada** [comment]
> Import download options from a channel, playlist or folder

what I mean is how do I export settings to other Tartube

**Comment by axcore** [comment]
It's not possible at the moment.

When you make a feature request, you need to add more detail. I can't guess what you want, I am not a psychic :)

**Comment by candrapersada** [comment]
how do I export settings download options like this picture
![1](https://user-images.githubusercontent.com/36833664/97081542-4ca2a900-162d-11eb-8265-16353976da8f.PNG)
![2](https://user-images.githubusercontent.com/36833664/97081547-50cec680-162d-11eb-9769-ef14dc25209a.PNG)

**Comment by axcore** [comment]
It's not possible at the moment, but I can add it.

**Comment by candrapersada** [comment]
why download all don't work from Classic Mode for Tartube v2.2.055?
![Download](https://user-images.githubusercontent.com/36833664/97207158-43136f80-17ec-11eb-88e5-919075e559c5.PNG)

**Comment by axcore** [comment]
>why download all don't work from Classic Mode for Tartube v2.2.055?

Fixed in v2.2.060.

**Comment by candrapersada** [comment]
why the rename download option is not working?
![image](https://user-images.githubusercontent.com/36833664/97937693-f4e50a00-1db1-11eb-810b-e296e05ba322.png)

**Comment by axcore** [comment]
I haven't added that yet. Do you really need it?

**Comment by candrapersada** [comment]
yes

**Comment by axcore** [comment]
In v2.2.173, you can rename download options, and there is a profile manager. You can export and import download options.

**Edit > System preferences... >  Options > Downlaod options**

![nov1](https://user-images.githubusercontent.com/37951926/99827031-09b2f300-2b51-11eb-8bdf-e2bd068735d6.png)

**Comment by candrapersada** [comment]
> You can export and import download options.

add export and import System preferences.

**Comment by axcore** [comment]
>add export and import System preferences.
>and why database change not working for Tartube v2.2.174?

I will investigate the database problem.

For system preferences - you can copy the config file. If you don't know where the config file is, click **Edit > System preferences... > Files > Devices**, and see the box at the bottom of the window.

**Comment by axcore** [comment]
>and why database change not working for Tartube v2.2.174?

Fixed in v2.2.176.

**Comment by candrapersada** [comment]
why Profile Manager not work v2.3.085

**Comment by axcore** [comment]
Which profile manager?

**Comment by candrapersada** [comment]
![image](https://user-images.githubusercontent.com/36833664/104560815-09c6ff00-5679-11eb-8c3d-f3055d8cf2a8.png)

**Comment by axcore** [comment]
Ok, what do you mean, "not work"? What does not work?

**Comment by candrapersada** [comment]
edit Profile Manager

**Comment by axcore** [comment]
Run Tartube in a terminal window, and show me the error message.

**Comment by candrapersada** [comment]
```
Traceback (most recent call last):
  File "/home/candra/.local/lib/python3.8/site-packages/tartube/config.py", line 18084, in on_options_edit_button_clicked
    OptionsEditWin(
  File "/home/candra/.local/lib/python3.8/site-packages/tartube/config.py", line 2725, in __init__
    self.setup()
  File "/home/candra/.local/lib/python3.8/site-packages/tartube/config.py", line 104, in setup
    self.setup_tabs()
  File "/home/candra/.local/lib/python3.8/site-packages/tartube/config.py", line 2850, in setup_tabs
    self.setup_files_tab()
  File "/home/candra/.local/lib/python3.8/site-packages/tartube/config.py", line 3008, in setup_files_tab
    self.setup_files_cookies_tab(inner_notebook)
  File "/home/candra/.local/lib/python3.8/site-packages/tartube/config.py", line 3330, in setup_files_cookies_tab
    entry.set_text(init_path)
TypeError: Argument 1 does not allow None as a value

```

**Comment by axcore** [comment]
I examined the code. I cannot explain why this error occurs, and I don't know how to reproduce it.

**Comment by candrapersada** [comment]
why should it be removed?  and usually never happens in previous versions?

**Comment by axcore** [comment]
>why should it be removed?

Because I don't know the cause of the problem yet.

>and profile data in the previous version cannot be used for the latest version

More details, please.

**Comment by candrapersada** [comment]
> More details, please.

I created two profiles from the previous version but it can't be used anymore for the latest version why does that happen?

**Comment by axcore** [comment]
Same answer: I cannot reproduce your problem, so I don't know how to fix it.

Here is the test I performed. I created the profiles **Test channel** and **Test playlist** with v2.3.042. Then I tested the profiles using v2.3.086. They work without problems.

![profiletest](https://user-images.githubusercontent.com/37951926/104810099-888f7980-57ea-11eb-890c-7e760b5cec38.png)

**Comment by candrapersada** [comment]
have you tried it for v2.2.055, v2.2.060, and v2.3.0?

**Comment by axcore** [comment]
I can do that, but what do you mean "it can't be used anymore"? The **Edit** button, or something else?

**Comment by candrapersada** [comment]
The edit button, and use in classic mode cannot download youtube

**Comment by axcore** [comment]
Ok, I created new databases with v2.2.055, v2.2.060, and v2.3.0. In each database, I created download options. Then I opened the databases in v2.3.088. The edit button and classic mode downloads work normally.

**Comment by candrapersada** [comment]
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/candra/.local/lib/python3.8/site-packages/tartube/downloads.py", line 352, in run
    worker_obj.prepare_download(self.current_item_obj)
  File "/home/candra/.local/lib/python3.8/site-packages/tartube/downloads.py", line 1451, in prepare_download
    self.options_list = self.download_manager_obj.options_parser_obj.parse(
  File "/home/candra/.local/lib/python3.8/site-packages/tartube/options.py", line 1050, in parse
    cookies_path = copy_dict[option_holder_obj.name]
KeyError: 'cookies_path'
```
