### ISSUE TITLE
Add extra ignore error/warnings for:

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#172]
System prefs > Windows > Errors/warnings

- 'unable to extract video data'
- 'this video requires payment to watch'
-

**Comment by axcore** [comment]
I haven't seen 'this video requires payment to watch' before. Is that the exact message? (A link to a video or a screenshot of your errors/warnings tab would be useful.)

**Comment by DankMemeGuy** [comment]
https://i.imgur.com/ifY92hV.png

**Comment by axcore** [comment]
Added in v2.2.046. 

Click **Edit > System preferences... > Windows > Websites** for the payment error. 

(Perhaps you didn't notice the box on this page, where you can intercept any error message you like.)

The 'unable to extract video data'' error is now covered by an existing setting. Click **Edit > System preferences... > Windows > Errors/Warnings**, and click the **'Ignore Unable to download video data...'** box to select it.
