### ISSUE TITLE
[Question] --sleep-interval argument

### ISSUE THREAD

**Issue by mbnoimi** [axcore/tartube#173]
Hi,

Does `--sleep-interval` available in Tatrube GUI?

**Comment by axcore** [comment]
It is not. Do you need it?

**Comment by mbnoimi** [comment]
I prefer to add it

**Comment by axcore** [comment]
The following [workarounds](https://github.com/ytdl-org/youtube-dl/#workarounds) are not used by Tartube. Shall I add all of them?

> --add-header FIELD:VALUE  
> --bidi-workaround   
> --sleep-interval SECONDS 
> --max-sleep-interval SECONDS

**Comment by mbnoimi** [comment]
I only use `--sleep-interval` but I don't see any problem by adding them

**Comment by axcore** [comment]
Added in v2.2.046.

(I only added --sleep-interval and --max-sleep-interval.)

**Comment by mbnoimi** [comment]
Thank you @axcore
