### ISSUE TITLE
Prevent hibernate or sleep during downloads

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#176]
how to Prevent hibernate or sleep during downloads for tartube-portable Windows

**Comment by axcore** [comment]
That's a good idea, but I don't know how. Google does not give any suggestions.

**Comment by candrapersada** [comment]
> That's a good idea, but I don't know how. Google does not give any suggestions.

it should work fine using a batch link like the image below
![1](https://user-images.githubusercontent.com/36833664/99196112-cf49fe80-27bc-11eb-894c-62925d18f608.PNG)
