### ISSUE TITLE
Channels/Playlists not working

### ISSUE THREAD

**Issue by Naugrimohtar** [axcore/tartube#177]
I am a new user to tartube. I have been using youtube-dl via command line for a while but have been annoyed so I am trying tartube as a GUI ;)

I have been able to configure Tartube to work in individual videos but I have **NOT** been unable to have it work on Playlists or Channels.

For example, I am trying to setup the following channel - `https://www.youtube.com/channel/UCsXVk37bltHxD1rDPwtNM8Q`

In order to get the setting I like, I use the following exter commandline options:
`--cookies cookies.txt --format bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best --merge-output-format mp4 --add-metadata --embed-thumbnail`

When I add a channel (or a playlist) and I choose 'Check Channel'. I see the command issues in the output window but it just sits there indefinitely.

![Capture2](https://user-images.githubusercontent.com/28710488/97017410-7b2c6100-1513-11eb-81b5-3e287ca5161d.PNG)

![Capture](https://user-images.githubusercontent.com/28710488/97017381-72d42600-1513-11eb-8ed3-bd1c8f195367.PNG)

**Comment by axcore** [comment]
An inexplicable freeze normally means that there's a python error somewhere. You need to run Tartube from inside a terminal window, so you can see the error. 

The instructions are [here](https://github.com/axcore/tartube#71-tartube-wont-installwont-rundoesnt-work), perhaps you can try doing that.

**Comment by Naugrimohtar** [comment]
Here is what I see when running from 

`$ python3 tartube/tartube
Traceback (most recent call last):
  File "C:\Users\[USER]\AppData\Local\Tartube\msys64\home\user\tartube\tartube/mainwin.py", line 9756, in on_video_index_check
    self.app_obj.download_manager_start('sim', False, [media_data_obj] )
  File "C:\Users\[USER]\AppData\Local\Tartube\msys64\home\user\tartube\tartube/mainapp.py", line 7211, in download_manager_start
    self.download_manager_continue(
  File "C:\Users\[USER]\AppData\Local\Tartube\msys64\home\user\tartube\tartube/mainapp.py", line 7264, in download_manager_continue
    download_list_obj = downloads.DownloadList(
  File "C:\Users\[USER]\AppData\Local\Tartube\msys64\home\user\tartube\tartube/downloads.py", line 1346, in __init__
    if media_data_list and isinstance(media_data_list[0], media.Scheduled):
AttributeError: module 'media' has no attribute 'Scheduled'`

**Comment by axcore** [comment]
I suspect that you have tried to implement the fix suggested [here](https://github.com/axcore/tartube/issues/175), so now you have some files from one version and other files from another version.

This is what you can do to fix it:

- Completely reinstall Tartube, or
- Don't reinstall Tartube, but download the source code from here on Github, and copy it to C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube, replacing all of the code

**Comment by Naugrimohtar** [comment]
I deleted this tartube folders and then completely reinstalled using the Win64 Windows install and have the same issue. Here is the text I see now in the commandline interface

`Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:/Users/USER/AppData/Local/Tartube/msys64/mingw64/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\USER\AppData\Local\Tartube\msys64\home\user\tartube\tartube/downloads.py", line 884, in run
    return_code = self.video_downloader_obj.do_download()
  File "C:\Users\USER\AppData\Local\Tartube\msys64\home\user\tartube\tartube/downloads.py", line 2303, in do_download
    dl_stat_dict = self.extract_stdout_data(stdout)
  File "C:\Users\USER\AppData\Local\Tartube\msys64\home\user\tartube\tartube/downloads.py", line 3846, in extract_stdout_data
    self.confirm_sim_video(json_dict)
  File "C:\Users\USER\AppData\Local\Tartube\msys64\home\user\tartube\tartube/downloads.py", line 2917, in confirm_sim_video
    path, filename, extension = self.extract_filename(full_path)
  File "C:\Users\USER\AppData\Local\Tartube\msys64\home\user\tartube\tartube/downloads.py", line 3555, in extract_filename
    path, fullname = os.path.split(input_data.strip("\""))
AttributeError: 'NoneType' object has no attribute 'strip'`

**Comment by axcore** [comment]
Ok, it looks like youtube-dl is supplying you with a metadata (JSON) file containing garbage data. I can't explain that behaviour, but I have amended the Tartube code to intercept this particular error.

The fix is here on Github so, once again, either wait for the next full release, or download the github code and copy it to  `C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube`, replacing all of the old code

**Comment by Naugrimohtar** [comment]
I have downloaded the latest 'master' of tartube, added my channel `https://www.youtube.com/channel/UCsXVk37bltHxD1rDPwtNM8Q`, chose to 'check channel' and received many errors.

Errors/Warnings tab shows 'Tartube error #303L Missing filename in JSON data'

Output shows 
`ERROR: Error in output template: unsupported format character '%' (0x25) at index 51 (encoding: 'cp1252')
ERROR: Error in output template: unsupported format character '%' (0x25) at index 51 (encoding: 'cp1252')
ERROR: Error in output template: unsupported format character '%' (0x25) at index 51 (encoding: 'cp1252')`

Nothing is in the commandline inferace.

Can you try the channel I linked above to help see if its an issue with me adding this channel (i.e. somehow with this channel' or send me an example channel to try?

![Capture3](https://user-images.githubusercontent.com/28710488/97310756-96f47780-1831-11eb-918b-e2f7a866dad8.PNG)

**Comment by Naugrimohtar** [comment]
I deleted the 'database' folder and started new. That seems to have resolved this issue.

**Comment by axcore** [comment]
Sorry, a little busy right now, but:

If you need to delete the database and start again, you can export a list of channels/playlists/folders (Media > Export from database, Media > import into database), so you don't have to copy all the URLs again

If you have already downloaded files and don't want to download them again, you can manually copy them into the new database folder,  and then do Operations > Refresh database

**Comment by heywolf15** [comment]
@axcore In the menu of Import into database, there's import videos. Is it copy the downloaded videos or move it? 
No need to do this? 

> If you have already downloaded files and don't want to download them again, you can manually copy them into the new database folder, and then do Operations > Refresh database

**Comment by heywolf15** [comment]
Make new database, but still the same result 

> When I add a channel (or a playlist) and I choose 'Check Channel'. I see the command issues in the output window but it just sits there indefinitely.

**Comment by axcore** [comment]
@heywolf15 , see [this issue](https://github.com/axcore/tartube/issues/192#issuecomment-725253038).

**Comment by heywolf15** [comment]
@axcore youtube-dlc new release has fixed it

**Comment by heywolf15** [comment]
> 
> 
> @axcore youtube-dlc new release has fixed it

Nvm it broke again. https://github.com/blackjack4494/yt-dlc/issues/148#issuecomment-725915379

using --rm-cache-dir --no-cache-dir params in your command. This works for me
