### ISSUE TITLE
DMCA issue

### ISSUE THREAD

**Issue by mbnoimi** [axcore/tartube#178]
Both `youtube-dl` and `youtube-dlc` are unavailable. Do you know where can I find their clones?

```
Repository unavailable due to DMCA takedown.
```

**Comment by mbnoimi** [comment]
Please make a fork ASAP because RIAA assholes want to close anything related to `youtube-dl`

**Comment by axcore** [comment]
Source code for official youtube-dl releases can still be downloaded from its website, [https://youtube-dl.org/](https://youtube-dl.org/).

The most recent github code can be downloaded from archive.org, [using this link](https://web.archive.org/web/20201019090822/https://github.com/ytdl-org/youtube-dl/).

[youtube-dl](https://pypi.org/project/youtube_dl/) and [youtube-dlc](https://pypi.org/project/youtube-dlc/) can still be download and installed from PyPI. Tartube installs youtube-dl from PyPI by default, so Tartube users can continue downloading things, at the moment.

My backup Tartube repository is [here](https://gitlab.com/axcore/tartube).

**Comment by axcore** [comment]
About the RIAA takedown generally:

-  youtube-dl is probably dead, and will probably never be updated. Its maintainers are being [sued in Germany](https://www.theregister.com/2020/10/23/riaa_youtube_dl_github/), and that normally means the end of a project

- There will be a lot of forks, but it is too early to say, whose fork will become the most popular

- The RIAA takedown is not about copyright, it is about circumventing DRM. Tartube does not circumvent anything, in fact it does not download videos at all, so the Tartube codebase is probably safe for the moment

**Comment by Yakabuff** [comment]
>Tartube works with a number of command-line downloaders, not just youtube-dl.

 Hello,
How do you configure it so it works with youtube-dlc

**Comment by axcore** [comment]
`Edit > System preferences... > youtube-dl > File paths`

In the box `Use this fork of youtube-dl`, type `youtube-dlc`

In the main window, click `Operations > Update youtube-dl `(it should say `Updated youtube-dlc`, but there is a typo)

[Or, read the instructions](https://github.com/axcore/tartube#625-using-youtube-dl-forks)

**Comment by Yakabuff** [comment]
> [Or, read the instructions](https://github.com/axcore/tartube#625-using-youtube-dl-forks)

why read the instructions when i can get you to spoonfeed me the answer ;)
