### ISSUE TITLE
unable to use download location

### ISSUE THREAD

**Issue by alidan** [axcore/tartube#180]
![python3_2020-10-29_01-50-48](https://user-images.githubusercontent.com/2681758/97535184-3bd59880-1989-11eb-8b2e-3e94940c3f35.png)
Ok, so I had this location as download
I drop files into either music, which downloads/keeps only the audio or video which as name suggests keeps the full video

if I have the program open for a while, It decided to not work right so I have to restart it. 
I tried to shut it down, but it refuses to shut down
so I have to eventually kill the process

then when I tried to load the program i'm greeted with that.
the drive works, its right there, same as always, but this won't load. 
I try to start it over and over again, I try to shut it down but it again wont shut down.

I tried updating, nothing.

Im at a loss as to what to do because it seems the program is broken and I cant get it to work.

**Comment by axcore** [comment]
I have some debug messages in place, for a problem similar to this. Try running Tartube from a terminal, using [these instructions](https://github.com/axcore/tartube#71-tartube-wont-installwont-rundoesnt-work), and tell me what you see.

**Comment by alidan** [comment]
![explorer_2020-10-29_19-49-02](https://user-images.githubusercontent.com/2681758/97647302-e39da580-1a1f-11eb-84b9-2cdfc588413c.png)
ok, this is what happened, tell me if I did something wrong

**Comment by axcore** [comment]
Ok, that rules out any python errors. Perhaps you can try running the newest version of Tartube:

- Enable showing hidden folders on your system (you've already done that, I think)
- Download the Tartube source code from [here on github](https://github.com/axcore/tartube#tartube-won-t-install-won-t-run-doesn-t-work)
- Copy that code to **C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube**, replacing the older code there
- Then run Tartube inside a terminal window again

**Comment by alidan** [comment]
Need a bit more instruction then download the source code, anything beyond downloading the exe or portable is a bit beyond me

**Comment by axcore** [comment]
It's really easy. On [the main page](https://github.com/axcore/tartube) there is a green box called `Code`. Click it, and then click `Download zip`.

You will download a file called tartube-master.zip. If you right-click it, you will probably see an option like `Extract all`. This will create a folder called `tartube-master` at the same location.

Rename the folder from `tartube-master` to `tartube`.

Now open the folder called `C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\`. This location also contains a folder called `tartube`. Drag the renamed folder to this location, which will replace the existing `tartube` folder.

**Comment by alidan** [comment]
ok, this sees me able to get back into the program, 
![explorer_2020-10-31_12-57-38](https://user-images.githubusercontent.com/2681758/97786313-adc00480-1b78-11eb-899a-582374ab9351.png)
this was the error I was getting before that caused me to try to restart the program
I have a feeling if I try to shut down it wont and I will be back at the beginning, so i'm going to leave it here for the moment. 

the program is pointing to its normal download folder on the g:\ drive, the hdd is working...
Ok, something came to me on why it would do that... so I checked the folder and apparently some of the subfolders were read only, I changed everything to read and write, but unlike last time where ytdl was able to test and download the video, its getting errors as well. 

![python3_2020-10-31_13-07-11](https://user-images.githubusercontent.com/2681758/97786501-0643d180-1b7a-11eb-801d-f0385d5e0e66.png)

not sure if this is a ytdl issue or not at this point, because i'm fairly sure it wasn't before but now I cant test if it is.

**Comment by alidan** [comment]
just noticed this 
![mintty_2020-10-31_17-17-45](https://user-images.githubusercontent.com/2681758/97791139-14efb000-1b9d-11eb-8f58-17b0377010d0.png)

**Comment by alidan** [comment]
Ok, the program is not working correctly again, prior step of from source fixed it, and ytdl needed a new version and now that that's out things are downloading, I have another issue so I will make a new thread about that one.

**Comment by axcore** [comment]
The "system cannot find the file specified" error you reported above is fixed in v2.2.098.
