### ISSUE TITLE
Can't type in system preferences

### ISSUE THREAD

**Issue by makeworld-the-better-one** [axcore/tartube#181]
Typing in boxes in the regular window works, but I can't type in any text fields when opening the system preferences. I am on Arch Linux, with Tartube v2.1.070, installed from AUR.

Also the [youtube-dl fork instructions](https://github.com/axcore/tartube#using-youtube-dl-forks) are out of date, the option they list doesn't exist anymore. I assume I just specify a different path? It's also not clear how I can choose whether I want tartube to update its own copy or whether I want it to use the system version, and whether it will try and update to a global/user path, ie affecting executables in the user's path.

**Comment by axcore** [comment]
What happens when you run Tartube from inside a terminal window? Do you see any errors?

Also: [your link](https://github.com/axcore/tartube/issues/181) refers to a more recent version of the code. In v2.1.070 there was no ability to switch to a different fork. Until the AUR package is updated, I suggest [installing Tartube using pip](https://github.com/axcore/tartube#535-install-using-pypi).

**Comment by makeworld-the-better-one** [comment]
> What happens when you run Tartube from inside a terminal window? Do you see any errors?

I ran `tartube`, then typed successfully in a regular text box, then opened system preferences and tried to type unsucessfully.

```
(tartube:31041): Gdk-CRITICAL **: 09:17:08.249: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

However, I should try and update and then report back.

> your link refers to a more recent version of the code. [...]

Ah damn, thought it was the latest version. Thanks.

**Comment by makeworld-the-better-one** [comment]
The AUR pkg has been updated to v2.2.007. I tested and don't have this issue anymore.

I do have a question though. How can I disable updates? I don't want tartube to attempt to update any downloaders on its own.

**Comment by axcore** [comment]
Disable updates for what?Tartube itself? youtube-dl?

**Comment by makeworld-the-better-one** [comment]
youtube-dl(c). I want to be in control of when it updates.

**Comment by axcore** [comment]
youtube-dl(c) does not update, unless you tell it to update.

There is an option to update youtube-dl(c) whenever you check or download a video, but this is disabled by default. To enable it, click **Edit > System preferences... > Operations > Downloads**, and select the box **Automatically update downloader before every download operation**
