### ISSUE TITLE
Won't save storage folder because config file is already in use

### ISSUE THREAD

**Issue by BmoXD** [axcore/tartube#182]
Like the title suggests Tarttube won't start because "`Failed to save the Tartube config file (file already in use)`" I tried running Tartube with administrator rights but that makes it not open at all. I checked for a config file in Tartube's directory but couldn't find one, I'm actually not sure where it is located.
I'm very new to this program, I just now installed it using the installer, not the portable version. Those didn't open at all, I tried both bit versions.

My Python version is 3.8.0 if that means anything

**Comment by axcore** [comment]
You didn't tell me which operating system you are using, so I will guess MS Windows 10

The config file is called `settings.json`. It can be found in `C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube`. This is a hidden folder, so you need to enable hidden folders in your control panel.

When Tartube is not running, you can delete the settings.json file, and then you can start Tartube again.

**Comment by BmoXD** [comment]
I apologize for not specifying my operating system. Tartube randomly started working out of nowhere when I downloaded and launched the portable version a second time. Thank you for commenting a fix, I'm sure this would have helped me with the non-portable version of Tartube :)
