### ISSUE TITLE
ffmpeg failing to install

### ISSUE THREAD

**Issue by alidan** [axcore/tartube#183]
![python3_2020-10-31_23-55-32](https://user-images.githubusercontent.com/2681758/97795554-b98de400-1bd5-11eb-8b64-12b205a281f2.png)
so the thumbnail conversion is something I like alot, however the program can't install ffmpeg, and I can't tell it a different location, though i'm fairly sure I dont have it installed anywhere else, I know several programs I use do use it as a dependency so I was going to try linking it to them, but not able to, possibly dumb idea but I tried. 

any idea how to get it to work through the program?

**Comment by axcore** [comment]
On MS Windows, Tartube, youtube-dl and ffmpeg are all installed into the same folder (`C:\Users\YOURNAME\AppData\Local\Tartube`). 

You could try uninstalling Tartube, then make sure that folder is completely deleted, then reinstall Tartube again.

**Comment by alidan** [comment]
don't really want to do that given other trouble I had, for now ill just wait and see, I can manually convert the files so its not too big an issue.

**Comment by axcore** [comment]
There is a terminal window you can run, `C:\Users\YOURNAME\AppData\Local\Tartube\msys64\mingw64.exe`

In this window, you can uninstall ffmpeg manually using this command:

`pacman -R mingw-w64-x86_64--ffmpeg`

Then you can reinstall it using Tartube's menu, or inside the same terminal window:

`pacman -S mingw-w64-x86_64--ffmpeg`

**Comment by alidan** [comment]
![mintty_2020-11-03_15-55-37](https://user-images.githubusercontent.com/2681758/98044779-0992c380-1ded-11eb-9a70-284668b9549c.png)

Ok, I assume i'm not doing something correctly.

**Comment by axcore** [comment]
I made a typo 

```
pacman -R mingw-w64-x86_64-ffmpeg
pacman -S mingw-w64-x86_64-ffmpeg
```

**Comment by alidan** [comment]
![mintty_2020-11-06_02-30-13](https://user-images.githubusercontent.com/2681758/98343926-293a0f80-1fd8-11eb-99dd-f2c9c1b292ef.png)
![mintty_2020-11-06_02-31-12](https://user-images.githubusercontent.com/2681758/98343931-2b03d300-1fd8-11eb-9913-2bbc714f3c94.png)
![python3_2020-11-06_02-32-01](https://user-images.githubusercontent.com/2681758/98344024-4969ce80-1fd8-11eb-9594-f5cf500c27fc.png)

Not sure if it did anything

**Comment by axcore** [comment]
In that case, you could try uninstalling Tartube (from the windows Start menu). Then completely the delete the folder `C:\Users\YOURNAME\AppData\Local\Tartube\` and everything it contains. Then reinstall Tartube from scratch.

If that doesn't work, then I don't know what to suggest.

**Comment by axcore** [comment]
Closed for inactivity.
