### ISSUE TITLE
Interface is grayed out in python3-tartube_2.2.7-STRICT

### ISSUE THREAD

**Issue by kendoori** [axcore/tartube#184]
I am able to use youtube-dl from the CLI on Pop!_OS 20.04 (Ubuntu derivative). I had an older version of Tartube (1.4 that was not working) so I updated to 2.2.0 then to 2.2.7. Both new versions act the same. Most of the interface is grayed out. I am unable to trigger anything. The classic interface allows me to paste a URL, but it ends up being stuck on waiting.
![Tartube_095](https://user-images.githubusercontent.com/2447420/97898155-76cb2980-1d05-11eb-9dd6-8e3e2cac872e.png)

**Comment by axcore** [comment]
Try running from inside a terminal window, then you can see all the python errors (if any).

**Comment by kendoori** [comment]
What command should I run?

**Comment by axcore** [comment]
Because of network issues I can't test it, but presumably you just type `tartube`

**Comment by kendoori** [comment]
Here's what displays:

`tartube
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 2192, in do_activate
    self.start()
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 2505, in start
    self.load_db()
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 4186, in load_db
    self.update_db(version)
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 4739, in update_db
    container_obj.recalculate_counts()
  File "/usr/lib/python3/dist-packages/tartube/media.py", line 709, in recalculate_counts
    if child_obj.live_mode:
AttributeError: 'Video' object has no attribute 'live_mode'

(tartube:251627): Gdk-CRITICAL **: 10:02:53.744: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
`

**Comment by axcore** [comment]
**Click Edit > System preferences... > Filesystem > DB Errors**
Click the **Check DB** button

**Comment by kendoori** [comment]
There were definitely issues with the database. It seems that the issue had to do with remnants of an older version. I deleted using Synaptic and then hunted all over my drive for anything named tartube and deleted. I then reinstalled and can confirm that it's working.

**Comment by axcore** [comment]
I have spent a lot of time, making sure that databases from earlier versions are compatible with all later versions. There is no guarantee that I have caught everything, though. Glad it's working now.
