### ISSUE TITLE
Update Operation Failed When Updating Youtube-DL / Youtube-DLC

### ISSUE THREAD

**Issue by DReaper** [axcore/tartube#188]
I updated to 2.2.007 and when I try to update youtube-DL or DLC, I get an "Update Operation Failed" error popup.

The output shows this:

Starting update operation, installing/updating youtube-dl
..\..\..\mingw64\bin\python3.exe ..\..\..\mingw64\bin\pip3-script.py install --upgrade youtube-dl
Update did not start
Update operation finished

**Comment by axcore** [comment]
Click Edit > System preferences > youtube-dl > paths, and tell me which settings you have there (take a screenshot of the window if you don't want to do a lot of typing)

**Comment by DReaper** [comment]
![image](https://user-images.githubusercontent.com/7599067/98213974-ddbe2d80-1f13-11eb-9fec-a43ef9ac0e74.png)

No custom path is being used

**Comment by axcore** [comment]
Look at the yellow text in this screenshot. Is it exactly the same as the yellow text you see in your Output tab? 

(I ask, because there are some backslashes missing in the output you posted, but that is probably because github removed them.)

![yellowtext](https://user-images.githubusercontent.com/37951926/98383458-6b009f80-2044-11eb-9225-29ad49a75fcc.png)

**Comment by DReaper** [comment]
Looks the same, this is what I have
![image](https://user-images.githubusercontent.com/7599067/98390573-8c9d5f00-2023-11eb-82e8-c98b861ede71.png)

**Comment by axcore** [comment]
Yes, that looks correct.

I will need to do some more thinking/testing before I can offer another suggestion.

**Comment by DReaper** [comment]
I can try to do a clean uninstall and reinstall, but I assume you might want to see what is causing this before I do that.

**Comment by axcore** [comment]
Don't wait for me, it might be a few days before I can do any more work on this issue.

**Comment by DReaper** [comment]
Can confirm, I did a clean uninstall and reinstall and it was able to download Youtube-DL. Not sure what happened before. I appreciate the support.

**Comment by axcore** [comment]
I checked the code. Any error messages or return codes that are possible to display, are already displayed. The 'Update did not start' message implies "and I don't know why".
