### ISSUE TITLE
should use "tartube" instead of "lib"

### ISSUE THREAD

**Issue by legrostdg** [axcore/tartube#19]
Trying to create a Debian package for tartube, I noticed that modules are installed in `/usr/lib/python3/dist-packages/lib/`, which should be `/usr/lib/python3/dist-packages/tartube/`... Could you rename the `lib` module to `tartube`?

**Comment by axcore** [comment]
The executable has the same name, so renaming `../lib` to `../tartube` is impossible (and the executable cannot be moved inside `../lib`, which is what many python apps do).

What about if I renamed it to` ../tartube-lib` or something like that? Or perhaps you have a better suggestion?

**Comment by legrostdg** [comment]
You can put the executables into a ./bin directory, or rename the executable to tartube-runner.py or something else? The convention seems to have /usr/lib/python3/dist-packages/package-name/

**Comment by axcore** [comment]
The tartube.py executable was originally in the ../lib directory, but I had to move it into the directory above, because nothing worked without that. I don't remember the details now, so I will have to experiment with it again.

**Comment by axcore** [comment]
v1.1.008 renames /lib as /tartube, and moves both executables into that directory. I have no idea what the problem was months ago, but it seems to be working now.
