### ISSUE TITLE
Show video information/name instead of the id in the lists

### ISSUE THREAD

**Issue by elico** [axcore/tartube#190]
Currently when I am changing the filename to only ID TarTube shows the ID as the name of the file.
I am using for the ID but want the details of the Video to show correctly in the GUI.

I believe that many others want this option, to fetch these details from some metadata file or any other way.

**Comment by axcore** [comment]
Hi elico, Tartube already shows the name of the video, not the name of the file.

I tested this today:

1. Click **Edit > General download options > Files**
2. In the box **Format for video file names**, select ID
3. Click **OK** to close the window
4. Download a video
5. Right-click the video, and select **Show video > Properties...**

This is the result. I can see the video name, not the file name (which is `piO6ANanSMoj.mp4` )

![idtest](https://user-images.githubusercontent.com/37951926/98707770-512ec780-2378-11eb-9bc5-5d2f21c0c21d.png)

Which version of Tartube are you using? (Click **Help > About**)

**Comment by axcore** [comment]
Also, you should check that Tartube is downloading the metadata file.

Click **Edit > System preferences... > File > Write/move files**
Make sure **Write videos' metadata to an .info.json file** is selected

**Comment by elico** [comment]
I dont remember the version.
i will try to verify this later this week or sometime next week,... no
promises.

**Comment by axcore** [comment]
Closed for inactivity.
