### ISSUE TITLE
How to reset Tartube settings to default?

### ISSUE THREAD

**Issue by heywolf15** [axcore/tartube#191]
Thanks for taking the time to ask a question! 

### Please read the README
Perhaps your question is answered there

### The authors are not experts in python, security, youtube-dl, FFmpeg, Debian/RPM packaging or Windows programming
You are welcome to ask a Tartube-related question, but you might get a better answer in forums where those kinds of expert can be found

**Comment by axcore** [comment]
Delete the config file. It is called `settings.json`.

If you are using a recent version of Tartube, the location of the config file is visible here:

**Edit > System preferences > Filesystem > Device**

**Comment by heywolf15** [comment]
Thank youuu
