### ISSUE TITLE
how to add track number from Individual video downloads?

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#193]
how to add name the files like 1-{name}, 2-{name}, ... n-{name} in order to be able to watch them in the sequence?
for youtube link batch download
![Youtube Batch2](https://user-images.githubusercontent.com/36833664/98796035-83562d00-243d-11eb-89ce-35d3512ec0ad.png)

**Comment by axcore** [comment]
In the options window, click **File > File Names**, then select **Autonumber + Title'**

![autonum](https://user-images.githubusercontent.com/37951926/98801705-19706000-240a-11eb-9ab8-fcf502eb0cc6.png)

**Comment by candrapersada** [comment]
but `Autonumber` only NA name not number

**Comment by axcore** [comment]
What is NA name?

**Comment by axcore** [comment]
By the way, youtube-dl and youtube-dlc don't work on YouTube playlists. You must wait for an update.

**Comment by candrapersada** [comment]
what I mean is how add track number YouTube link batch not for YouTube playlists

**Comment by axcore** [comment]
youtube-dl cannot do that

**Comment by axcore** [comment]
> but `Autonumber` just give NA name not numbers

I remembered answering this question, but now I can't find the answer.

Anyway: I tested youtube-dl without Tartube, and it also produced files with NA name, not numbers. So it is a youtube-dl issue.
