### ISSUE TITLE
save link URL on Classic Mode

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#194]
how to save link URL to Classic Mode?

**Comment by axcore** [comment]
Do you mean this?

![copypaste3](https://user-images.githubusercontent.com/37951926/98912796-7af20680-24be-11eb-994d-59b684842eeb.png)

**Comment by candrapersada** [comment]
not what I mean is How do I keep the URL link from being lost when the Tartube is closed?
and save link URL for downloads later.

**Comment by axcore** [comment]
Keep them in **top** or **bottom**?

![keepwhere](https://user-images.githubusercontent.com/37951926/98915985-8a734e80-24c2-11eb-9328-ac5febd2e230.png)

**Comment by candrapersada** [comment]
bottom and add Remove all list
![98915985-8a734e80-24c2-11eb-9328-ac5febd2e230](https://user-images.githubusercontent.com/36833664/98917380-df34ba80-24fe-11eb-9732-a8aba3e3291e.png)

**Comment by axcore** [comment]
No, that is not possible.

**Comment by axcore** [comment]
Ok, I can do that.

**Comment by axcore** [comment]
Added in v2.2.173. In the Classic Mode Tab, click the menu button at the top, and select Remember URLs.

![nov2](https://user-images.githubusercontent.com/37951926/99827387-73cb9800-2b51-11eb-9cd4-6c805b6dd895.png)

When you restart Tartube, any URLs that are not downloaded, will still be visible.
