### ISSUE TITLE
DL Membership streams?

### ISSUE THREAD

**Issue by Cheunguy** [axcore/tartube#196]
Sorry if this is a dumb question, but is there a way to log into YouTube in Tartube so it can download Member-only streams?

**Comment by axcore** [comment]
In theory you can, but in practice it often doesn't work.

- Clidk **Edit > Download options...**
- If the **Show advanced download options** button is visible, click it
- Click the **Advanced** tab
- Enter your YouTube name and password
- Click **OK** to close the window
