### ISSUE TITLE
Live stream support via other github project

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#197]
I was looking into https://github.com/mrwnwttk/youtube_stream_capture and it seems possible to record live streams, I was wondering if there would be a way to implement that just for livestreams, but then use yt-dlc for the normal downloads?

Since tartube separtes livestream vs normal videos, I think it could be possible?

**Comment by axcore** [comment]
Ok, I'll look into that.

**Comment by axcore** [comment]
Added in v2.2.198. Tartube now uses Youtube Stream Capture by default. It can be disabled in **Edit > System preferences... > Operations > Livestreams**, there you can deselect **Use Youtube Stream Capture to download broadcasting livestreams**.

**Comment by DankMemeGuy** [comment]
I just want to say how great you are @axcore Your hard work definitely doesn't go unnoticed!

**Comment by axcore** [comment]
In v2.3.0, YTSC is disabled by default. It can be enabled by clicking  **Edit > System preferences... > Operations > Livestreams**, and selecting the box **Use Youtube Stream Capture to download broadcasting livestreams**.

Unfortunately I was not able to get it working on MS Windows, but I haven't given up on that yet.

**Comment by DankMemeGuy** [comment]
I had noticed. At this point I realized that Windows is probably not the best for scraping so I was going to get a VM running with Linux with Tartube inside that. Or do you have "Docker" support by any chance?

**Comment by axcore** [comment]
[Youtube Stream Capture](https://github.com/mrwnwttk/youtube_stream_capture) apparently works on MS Windows, it just doesn't work on MS Windows under MSYS2, which is what Tartube is using. 

Actually, YTSC uses two stages - download video segments, and then merge them - and it's the second stage that I couldn't get working. 

There is no support at the moment for Docke or flatpak or any of the others - I just don't have time to learn them all :)

**Comment by DankMemeGuy** [comment]
Interesting. I wonder if that developer had tried FFMPEG for merging but that didn't work? That seems like it would be the more prefered means of merging videos

**Comment by axcore** [comment]
I tested the latest version of YTSC on a MS Windows box this morning, with the same result. Your idea of using FFmpeg is a good one, though, I will look into it as soon as I have time.
