### ISSUE TITLE
Livestream not being detected

### ISSUE THREAD

**Issue by absintheL** [axcore/tartube#198]
Whenever I enter a channel, livestreams are not detected. 

When entering the link as a video or as a playlist, and try to check it, it just produces the "this event will go live in x hours" error. 

The video remains as it is, looking like a video that hasn't been checked yet.
![tar](https://user-images.githubusercontent.com/74472965/99157787-170e4e80-2707-11eb-850c-f031480ea906.PNG)

The expected behavior is that it shows the stream with a red background. Due to this issue, the D/L at start option is also useless. 

Also, how do you stop a livestream download? For example, if I start downloading a livestream that is live right now, if i press the "stop now" button on the progress tab, the video remains as a .part file. Do I have to process that file with FFMPEG? Or is there a proper way to stop the download?

**Comment by axcore** [comment]
YouTube recently changed how livestreams work, so Tartube v2.2.007 can't detect them. I have already patched the code, though. It can be downloaded from here on Github or PyPI. There will be a full release later this week.

About livestream downloads, I'm not sure about that yet, but keep an eye on the progress on `this issue` which might solve it.

**Comment by axcore** [comment]
Livestream detection has been updated in v2.3.0, and should be working perfectly.
