### ISSUE TITLE
downloading art channel list; other art channels come through too

### ISSUE THREAD

**Issue by linuxgirl22** [axcore/tartube#199]
### What operating system are you using?
Anarchy linux, Mate desktop. 

### What version of Tartube are you using?
2.2.007

### What happens when you run Tartube from a terminal window?
No problems with running TarTube (installed from the AUR), and issue is to do with downloading of videos, not whether TarTube runs okay ... thanks for your work :-) 

Program runs very well, except that I've just noticed that, among the video list from the channel I chose to download (just jpg's list, not the videos), there are other art channel videos. The channel is BoroCG, and there are videos from Marco Bucci's youtube channel, and Sinix Design's channel, also. 

Is there some AI involved at some stage, e.g. on YT's end? With the extra videos also being art videos, ie not at all random, it's a bit creepy and making me wonder. Also, it's a bit difficult to find which are the BoroCG videos, without opening up the text of every video to first check.

**Comment by axcore** [comment]
At the moment, youtube-dl is experiencing problems in handling YouTube channels/playlists. You should make sure you have today's update of youtube-dl. If that doesn't improve things, try switching to youtube-dlc. If that still doesn't work, tell me and I'll investigate further.

**Comment by linuxgirl22** [comment]
Thanks for such a quick response. :-) Yes, using today's youtube-dl update. Will take a look at youtube-dlc, and post back. Thanks for advice.

**Comment by linuxgirl22** [comment]
Just to feed back that switching to youtube-dlc fixed things perfectly! 11 pages for the BoroCG channel, instead of the 27 that had come through before. :-)
