### ISSUE TITLE
Incomplete list of playlist videos shown when checking playlist (not on Youtube)

### ISSUE THREAD

**Issue by patsulee** [axcore/tartube#200]
Using Windows 7 Pro x64
Tartube V. 2.2.007

Hello all,
I am trying to download a playlist from Pornhub but i keep getting the warning about tartube being "unable to extract like/dislike count" and when checking the videos i get only a part returned. For example, i know there are 102 videos in a playlist but when i check the playlist i get 34 shown....

Is there something i am doing wrong?

**Comment by axcore** [comment]
Hi @patsulee, I tested this using youtube-dl and saw the same "unable to extract like/dislike count" warnings. However, youtube-dl did return complete videos. 

Have you installed FFmpeg on your system? (If not, that would explain why .part files are not converted to the full video. On MS Windows, FFmpeg must be installed from the Tartube menu: **Operations > Install FFmpeg**

**Comment by patsulee** [comment]
Hey @axcore, thanks for the reply! 
Yeah, i installed FFmpeg alright. The problem is not that those videos that get downloaded are incomplete. The problem is that from a playlist with 100+ videos, even though my db is empty, only a portion of those get recognized and downloaded. I noticed that it usually finds 36 items, so perhaps it is a paging thing ?!?

**Comment by axcore** [comment]
You can test whether youtube-dl itself is at fault, or not, by clicking **Operations > Test youtube-dl**. Then add the playlist URL, and click OK to download it. Click the **Output** tab to keep on eye on what's happening. You don't get the videos you were expecting, you can report the problem on the [youtube-dl issue page](https://github.com/ytdl-org/youtube-dl/issues/).

**Comment by axcore** [comment]
Closed for inactivity.
