### ISSUE TITLE
Cann't update Youtube DLC

### ISSUE THREAD

**Issue by WandeingLagomorph793** [axcore/tartube#201]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Manjaro Linux Kernel 5.9.8.2

### What version of Tartube are you using?
v2.2.007

I currently have the youtube dlc fork to download videos with, but if I try and update that from within TarTube, then I only get an update failed notification, here's what the output shows.

![Screenshot from 2020-11-22 07-05-29](https://user-images.githubusercontent.com/41207981/99907365-47b73080-2c91-11eb-8284-f13cf929491f.png)

Is there something I need to configure or can Tartube only update normal youtube dl?

**Comment by axcore** [comment]
Sorry, I have no idea what might cause youtube-dl(c) installation errors of this kind.

Google [suggests](https://stackoverflow.com/questions/48269756/pip-install-unicodedecodeerror-utf-8-codec-cant-decode-byte-0xe0-in-positi) that the crash could be bypassed by piping the output away from the terminal. 

You probably need to try installing/updating youtube-dlc in separate terminal window, using the same command:

pip3 install --upgrade --user /usr/local/bin/youtube-dlc

If you still see the error message, then it's nothing to do with Tartube, and can be reported at the [youtube-dlc issue tracker](https://github.com/blackjack4494/yt-dlc/issues).

**Comment by WandeingLagomorph793** [comment]
> Sorry, I have no idea what might cause youtube-dl(c) installation errors of this kind.
> 
> Google [suggests](https://stackoverflow.com/questions/48269756/pip-install-unicodedecodeerror-utf-8-codec-cant-decode-byte-0xe0-in-positi) that the crash could be bypassed by piping the output away from the terminal.
> 
> You probably need to try installing/updating youtube-dlc in separate terminal window, using this command:
> 
> `pip3 install --upgrade --user /usr/local/bin/youtube-dlc`
> 
> If you still see the error message, then it can be reported at the [youtube-dlc issue tracker](https://github.com/blackjack4494/yt-dlc/issues).

Had to reinstall YT-DLC and adjust some settings to allow it to update correctly, so .local/bin/youtube-dlc and pip3 update. No idea why it broke last time and it took a few reinstalls to get it right, but it works now.
