### ISSUE TITLE
separate video file from ytdl-archive.txt Videos Tab

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#202]
how to separate video file from ytdl-archive.txt from folder?

**Comment by axcore** [comment]
You cannot. The archive file must be in the same folder as the videos. If it in a different folder, then youtube-dl can't use it.

If you don't want the archive file, you can disable it.

**Edit > System preferences.. > Operations > Downloads**, and deselect **Allow downloader to create its own archive file...**

If you want to delete all the archive files you already have, click **Operations > Tidy up files...**, select **Delete all archive files**, the click **OK** to start.
