### ISSUE TITLE
Forcing MP3 or AAC Audio format in the output MP4 file?

### ISSUE THREAD

**Issue by elico** [axcore/tartube#203]
Am I doing something wrong?

My current config results in MP4 with Opus audio format.
The result I got was a single MP3 file.
I don't know if it's a bug or an issue.
To force AAC now on the MP4 What I did was add a custom:
`-f mp4`

I wanted to force mp3 or AAC audio format and got into:
Edit -> General Download Options -> Post-Proccess -> Audio Quality of  the Post-Proccessed file -> High
or
Edit -> General Download Options -> Post-Proccess -> Audio format of  the Post-Proccessed file -> mp3

And I made sure the next option is not checked:
Edit -> General Download Options -> Post-Proccess -> Post-process video files to convert to audio-only file

And the result command is:
`youtube-dl --newline -i --hls-prefer-native -o C:/PATH/%(id)s.%(ext)s --write-description --write-info-json --write-annotations --write-thumbnail -f bestvideo[height<=?1080][fps<=?60]+bestaudio/best[height<=?1080] --merge-output-format mp4 -x --audio-format mp3 --audio-quality 0 --embed-thumbnail --add-metadata --fixup detect_or_warn https://www.youtube.com/watch?v=XYZ`
And the output is:
```
[youtube] XYZ: Downloading webpage
[info] Writing video description to: C:/PATH/XYZ.description
[info] Writing video description metadata as JSON to: C:/PATH/XYZ.info.json
[youtube] XYZ: Downloading thumbnail ...
[youtube] XYZ: Writing thumbnail to: C:/PATH/XYZ.jpg
[download] Destination: C:/PATH/XYZ.f134.mp4
[download] 100% of 49.03MiB in 00:24
[download] Destination: C:/PATH/XYZ.f251.webm
[download] 100% of 26.15MiB in 00:12
[ffmpeg] Merging formats into "C:/PATH/XYZ.mp4"
Deleting original file C:/PATH/XYZ.f134.mp4 (pass -k to keep)
Deleting original file C:/PATH/XYZ.f251.webm (pass -k to keep)
[ffmpeg] Destination: C:/PATH/XYZ.mp3
Deleting original file C:/PATH/XYZ.mp4 (pass -k to keep)
[ffmpeg] Adding metadata to 'C:/PATH/XYZ.mp3'
[ffmpeg] Correcting extension to webp and escaping path for thumbnail "C:/PATH/XYZ.jpg"
[ffmpeg] Converting thumbnail "C:/PATH/XYZ.webp" to JPEG
[ffmpeg] Adding thumbnail to "C:/PATH/XYZ.mp3"
WARNING: There are no annotations to write.
```

**Comment by axcore** [comment]
I don't know a lot about video/audio formats. A better place to find out which youtube-dl options produce the results you want would be at [reddit](https://www.reddit.com/r/youtubedl/).

As far as I understood, though, the combination of options you've chosen has this effect: first, the video is downloaded as two separate files (as is normal these days). Then, FFmpeg merges them into a single output file, in MP4 format. Then, FFmpeg strips away the audio from the merged file, creating a new MP3 file. Then, the merged MP4 file is deleted.

**Comment by elico** [comment]
@axcore I know something about audio and video format, just .. something..
the "-x" causes to create a mp3 file instead of somehow merging the mp3 or audio into the mp4 file.
I don't know what option is adding the "-x" to the command.
If you do know this will help to make sure if and how to resolve this specific issue.

**Comment by axcore** [comment]
The -x is added in two places:

**Edit > General download options... > Sound only**, when the **Download each video, extract the sound...** button is selected

**Edit > General download options... > Post-processing**, when the **Post-process video files to convert them to audio-only files** is selected

The second one is only visible if you clicked the **Show advanced download options** button in the **Name** tab

**Comment by elico** [comment]
@axcore It appears that wrongfully when 
 
 **Edit -> General Download Options -> Post-Proccess -> Audio format of the Post-Proccessed file -> mp3**

The `-x`  should only be added when **Post-process video files to convert them to audio-only files** is selected/check to my understanding.

**Comment by axcore** [comment]
You might be right. Here is my problem: the documentation for youtube-dl is completely inadequate, so it is difficult to know which download options should be used together, and which should not.

**Comment by axcore** [comment]
Closed for inactivity.
