### ISSUE TITLE
Where does cookies.txt go

### ISSUE THREAD

**Issue by KJThaDon** [axcore/tartube#204]
Jus beginning to use this over the command line, however running into an issue. I use cookies to download most my files, and am used to placing my cookies.txt into the root folder with youtube-dl. I have placed my cookies.txt in the root folder of Tartube and added the xtra command line options of

`--cookies cookies.txt
`
This is not working as I expected though. I have also tried the full path into the --cookies line, like so.

`--cookies.txt X:\Media\~ Tartube`

I am still getting these validations errors.
`ERROR: This video is only available via cable service provider subscription that is not currently supported. You may want to use --cookies.`

**Comment by axcore** [comment]
It looks like Git has swallowed some characters from the file path, because I am only seeing `X:\Media\~ Tartube`.

If the file path contains spaces, you could try putting it in quotes, "X:\Media\Hello world" (I haven't tested this)

A new release (v2.3.0) is being uploaded now, it should be available in a couple of hours. It uses a `cookies.txt `stored where the videos are downloaded (specifically, in the same folder as the `tartube.db` file). Maybe that will solve yourp roblems.

**Comment by candrapersada** [comment]
Where does --download-archive FILE go?

**Comment by axcore** [comment]
It goes in the same directory, where the videos are downloaded, as long as you have enabled it in **Edit > System preferences... > Operations > Downloads > Allow downloader to create its own acrhive file**

**Comment by candrapersada** [comment]
[Question] How to save video titles or URLs alongside the IDs when using (download archive)?

**Comment by axcore** [comment]
You cannot change the format of the youtube-dl archive file (unless you want to rewrite youtube-dl).

You can export a channel as a JSON file: right-click the channel, and select **Channel actions > Export channel... **. In the new window, select only **Include lists of videos**, then click the **OK** button.

At the moment, Tartube does not produce a text file in the format  you want.

**Comment by candrapersada** [comment]
> --download-archive is not meant as a method to save information, but only to prevent the same videos from being redownloaded.
> If you want to download the titles as well, you can seperately use --get-title like this:
> ```
> # First save titles
> youtube-dlc --get-title --download-archive archivefile URL >> titles.txt
> # Then download
> youtube-dlc --download-archive archivefile URL
> ```

information from [youtube-dlc](https://github.com/blackjack4494/yt-dlc/issues/257#issuecomment-734393032)

**Comment by axcore** [comment]
Let's continue this in a [new issue](https://github.com/axcore/tartube/issues/207).

**Comment by axcore** [comment]
Closed for inactivity.
