### ISSUE TITLE
Software not checking or downloading the full list of video

### ISSUE THREAD

**Issue by Anticancer123** [axcore/tartube#208]
When I hit check or download channel it shows only 30 videos and starts downloading from there sometimes only 60 when there would be hundreds or thousands of videos on that channel.

**Comment by axcore** [comment]
Which website? YouTube?

**Comment by Anticancer123** [comment]
yes

**Comment by axcore** [comment]
YouTube recently made major changes to its code. As a result youtube-dl(c) might not be working with all channels/playlists. The problem you describe sounds like one other youtube-dl(c) users have been complaining about.

You can try switching to a different downloader (**Edit > System preferences... > Downloaders > Forks**. Then, in the main window, click **Operations > Update youtube-dl(c)**.

**Comment by axcore** [comment]
Also, you can check **Edit > System preferences > Operations > Performance**. If the button **Stop checking/downloading a channel/playlist...** button is selected, then try de-selecting it.

**Comment by Anticancer123** [comment]
der (Edit > System preferences... > Downloaders > Forks. 


cant find that also the other options didnt work

**Comment by axcore** [comment]
Are you using Tartube v2.3.0?

**Comment by Anticancer123** [comment]
yes

**Comment by axcore** [comment]
Ok, here are the same steps in pictorial form.

![testa](https://user-images.githubusercontent.com/37951926/101146394-da9d8680-3612-11eb-8614-99bd17df85db.png)
![testb](https://user-images.githubusercontent.com/37951926/101146406-de310d80-3612-11eb-8dfe-3e448fc0961b.png)
![testc](https://user-images.githubusercontent.com/37951926/101146414-dffad100-3612-11eb-80b2-5d32d256ff70.png)

**Comment by Anticancer123** [comment]
First option n/a
![Screenshot (7394)](https://user-images.githubusercontent.com/74401394/101148229-626f9a80-35eb-11eb-8fb3-4d7fc88f62c2.png)

**Comment by Anticancer123** [comment]
can I get a link to the recent one then?
![Screenshot (7394)](https://user-images.githubusercontent.com/74401394/101201164-498bd700-3635-11eb-9ab7-499f89dc509f.png)

**Comment by axcore** [comment]
The most recent Tartube? Download links are always on the main page, for example [here](https://github.com/axcore/tartube#3-downloads) and [here](https://tartube.sourceforge.io/).

**Comment by Anticancer123** [comment]
Ok it seems to be working now.How can I avoid downloading the same files again when updating a channel in the future

**Comment by axcore** [comment]
youtube-dl automatically checks that a file doesn't exist on your hard drive, before trying to download it.

**Comment by Anticancer123** [comment]
error :requested format not available

**Comment by axcore** [comment]
You can select your preferred formats in **Edit > General download options... > Formats > Preferred**. There is also a selector in the **Classic mode** tab.

If you have not selected a format, then it's just a normal youtube-dl(c) error that will be fixed eventually.

**Comment by Anticancer123** [comment]
yeah that didnt work

**Comment by axcore** [comment]
Can you show me a screenshot of the **Output** tab, when you try to download this video? (Specifically, the yellow text at the top)

**Comment by Anticancer123** [comment]
![Screenshot (7463)](https://user-images.githubusercontent.com/74401394/101900965-556c2180-3b7e-11eb-904b-e6a85a847b96.png)
![Screenshot (7464)](https://user-images.githubusercontent.com/74401394/101900992-5dc45c80-3b7e-11eb-9040-a19435dfa09f.png)

**Comment by Anticancer123** [comment]
no yellow line btw

**Comment by axcore** [comment]
You need to scroll the **Output** tab to the top, so you can see the yellow text.

Possibly you need to increase the page size (in the bottom right corner), because at the moment there is only room for 1000 lines (and you have 800 videos)

**Comment by Anticancer123** [comment]
![Screenshot (7470)](https://user-images.githubusercontent.com/74401394/101975807-644de500-3c0d-11eb-8960-641e75ea2f28.png)

**Comment by Anticancer123** [comment]
thats whats happened when trying to downlead vireo individually

**Comment by axcore** [comment]
I tested this using youtube-dl alone, and got the same result:

![ytdl](https://user-images.githubusercontent.com/37951926/101978575-dd6d2c80-3c4d-11eb-999a-dd72b41b1005.png)

So it's a youtube-dl problem which you can report at their [issues page](url).

I did some additional testing. The [video](https://www.youtube.com/watch?v=UKB68n2FnSE) is not available in most of those formats. (You can get a list of the available formats by right-clicking the video and selecting **Fetch > Available formats**).

I did even more testing, because the video is available in format 22, and that is one that you have specified. It looks like youtube-dl is rejecting the download request if you specify certain formats at all. In this case, 22 is valid but 397 is invalid, and the download request is rejected:

![ytdl2](https://user-images.githubusercontent.com/37951926/101978659-83b93200-3c4e-11eb-8f05-9f257fb8ee64.png)

**Comment by Anticancer123** [comment]
isnt this the issue page and what do I do the software

**Comment by axcore** [comment]
Tartube and youtube-dl are separate applications. Tartube is just a graphical front-end for youtube-dl. I can fix Tartube issues, but there is nothing I can do about youtube-dl issues.

youtube-dl will download the video if you only specify the format 22 / mp4 [720p], and remove all of the others (in **Edit > General download options > Formats > Preferred**)

**Comment by Anticancer123** [comment]
so no 1080p vid and above vids available for now? It was available before.

**Comment by axcore** [comment]
According to **Fetch > Available formats**, your [video](https://www.youtube.com/watch?v=UKB68n2FnSE) is not available in 1080p. This is not a youtube-dl issue; the video you want simply doesn't exist.

![noexist](https://user-images.githubusercontent.com/37951926/101983123-bbd16c80-3c70-11eb-95a9-56dbe4ea8acc.png)

**Comment by axcore** [comment]
Also: I tested format 22 (which works) and format 397 (which does not work), but you specified about ten formats, and I didn't test the others.

**Comment by Anticancer123** [comment]
if there is no requested format will it download the vid automatically in the highest quality?

**Comment by axcore** [comment]
Yes, always. And if you select **mp4**, the highest-available quality in mp4 should be downloaded.

![mp4test](https://user-images.githubusercontent.com/37951926/102006376-9c8e1a00-3d18-11eb-8bfe-958b5c57cc9e.png)

**Comment by Anticancer123** [comment]
if I am download a video and shut down muy computer the files the remaning on my computer but are missing from tartube

**Comment by axcore** [comment]
The database cannot be saved when youtube-dl is downloading videos. 

If you need to stop a download, press the **Stop** button (at the top of the window). When the download stops, the database is saved automatically.

**Comment by axcore** [comment]
Closed for inactivity.
