### ISSUE TITLE
export and import System preferences

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#210]
how to move Tartube configuration file loaded from:
![Capture](https://user-images.githubusercontent.com/36833664/101226195-3ffe7f80-36c6-11eb-986f-a29f16ec9700.PNG)
like database preferences?

**Comment by axcore** [comment]
If you move it, how will Tartube find it?

**Comment by candrapersada** [comment]
use change ![Capture](https://user-images.githubusercontent.com/36833664/101237611-d48bd080-370c-11eb-8efb-392cdd5f5d9f.PNG)
![Capture2](https://user-images.githubusercontent.com/36833664/101237617-e40b1980-370c-11eb-9798-f9f23a476b45.PNG)

**Comment by axcore** [comment]
How does Tartube know, where the data folder is, if it doesn't know where the config file is?

**Comment by candrapersada** [comment]
use import and export to load `settings.json`
![Capture2](https://user-images.githubusercontent.com/36833664/101240641-2b9ca000-3723-11eb-977b-0b15dc5ba7b2.PNG)

**Comment by axcore** [comment]
Same question: how does Tartube know, that the config file is in \Users\Candra Persada\Downlaods\Tartube-data?

**Comment by candrapersada** [comment]
I mean add a feature to move the configuration preferences file

**Comment by axcore** [comment]
I understand you, but I think it is not possible.

If we move the `settings.json` file, then Tartube cannot find it.

Tartube looks in two places:

1. The directory containing the source code (where Tartube's **setup.py** file is)
2. The standard location for config files. On my Linux, it is /home/MYNAME/.config/

If the config file is not in (1) and not in (2), then Tartube cannot find it.

**Comment by candrapersada** [comment]
I mean add the [export and import](https://github.com/axcore/tartube/issues/171#issuecomment-731419262) System preferences feature.

**Comment by axcore** [comment]
I think it's not possible. Tartube loads the config file once, when it starts. Tartube could import a config file, but could not load it. And when Tartube closes, it saves a new config file, so the imported config file is destroyed.

**Comment by candrapersada** [comment]
> 2. The standard location for config files. On my Linux, it is /home/MYNAME/.config/
why is settings.json put /home/MYNAME/.config/ not on tartube?

**Comment by axcore** [comment]
Because that is the standard location for config files on Linux.

**Comment by candrapersada** [comment]
> Because that is the standard location for config files on Linux.

why is settings.json put in C:\Users\UserName\AppData\Local\Tartube\msys64\home\user\tartube for windows?

**Comment by axcore** [comment]
I just checked `tartube-portable-64bit.zip` and `tartube-portable-32bit.zip`, the `settings.json` file is in the correct place (in the same folder as `setup.py`).

**Comment by candrapersada** [comment]
Can I move `settings.json` only for tartube-portable?

**Comment by axcore** [comment]
Same answer. If I change the `settings.json` save location, how will Tartube find it?

**Comment by axcore** [comment]
Closed for inactivity.
