### ISSUE TITLE
Wrong file recorded as video file for subtitles / live chat

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#211]
If a video has a subtitle file, that file will be listed instead of the video file.  See this URL to test:
https://www.youtube.com/watch?v=uw8MACDZ3RI

If a video has live chat, that file will be listed instead of the video file.  See this URL to test:
https://www.youtube.com/watch?v=nAbF2bKo2Fs

Thumbnails will also not be displayed for these files even though they are downloaded.

I have it set to keep description / metadata / annotations / thumbnails.

Unfortunately I have quite a few videos with this issue in my DB - is there a way I can somehow edit them to replace it with the proper file?
Christopher F. Rufo - (20200803) - Chaos by the Bay - The Truth About Homelessness in San Francisco - uw8MACDZ3RI - [244+251#480p].en.vtt to .mkv

Mountain Time Media - (20200917) - DENVER IN DECAY _ DOCUMENTARY FILM 4K - nAbF2bKo2Fs - [244+251#480p].live_chat.json to .mkv

On a semi-related note, is there any way to save all the comments for a video when it is downloaded?

### What operating system are you using?
Win 10

### What version of Tartube are you using?
2.3.008

### What happens when you run Tartube from a terminal window?
no error logged in terminal

**Comment by axcore** [comment]
Both of those links download for me, with both youtube-dl and youtube-dlc, without any problems. Having enabled keep description / metadata / annotations / thumbnails, I receive the four files I'm expecting and not any others.

What do you mean, "If a video has a subtitle file, that file will be listed" - listed where?

Can you show me the contents of the **Output** tab, when you try to download one of those videos? (It would be useful to see the command in yellow at the top, and the last few lines at the bottom, when the download has finished.)

**Comment by axcore** [comment]
>On a semi-related note, is there any way to save all the comments for a video when it is downloaded?

Not at the moment. I did not know that youtube-dl(c) could download comments.

**Comment by ceonelson** [comment]
Using latest yt-dlc. It downloads all the files to my drive but tartube won't display it's thumbnail or correct info.
![image](https://user-images.githubusercontent.com/16659133/101259518-b6af7300-36ee-11eb-85c4-d77b910bd972.png)

under video properties it has:
#525 video icon then in the field to the right:
Christopher F. Rufo - (20200803) - Chaos by the Bay - The Truth About Homelessness in San Francisco - uw8MACDZ3RI - [244+251#480p].en
(should be as above without the .en on end)

listed as field is also:
Christopher F. Rufo - (20200803) - Chaos by the Bay - The Truth About Homelessness in San Francisco - uw8MACDZ3RI - [244+251#480p].en
(should be just the video title)

then file is:
PATH/Christopher F. Rufo - (20200803) - Chaos by the Bay - The Truth About Homelessness in San Francisco - uw8MACDZ3RI - [244+251#480p].en.vtt
(should be .mkv instead of .en.vtt)

I don't think they do the comments, was asking if it was possible so I guess not :/

**Comment by ceonelson** [comment]
@axcore any thoughts on this?

All files download to the filesystem just fine, but for whatever reason the one tartube puts in the db is the subtitle or live chat file rather than the actual video file.

Is the db running some sort of standard format that I could install an editor to be able to browse and run SQL against?

**Comment by axcore** [comment]
@ceonelson, I understand the issue, but I need to see the youtube-dl system command used to download these videos, that's the yellow text in the **Output** tab.

>Is the db running some sort of standard format that I could install an editor to be able to browse and run SQL against?
The db file uses the standard Python format for saved data. I don't think it can be edited with SQL.

**Comment by ceonelson** [comment]
Sure! Here's the code:

`youtube-dlc --newline -i --hls-prefer-native -o C:/Temp/_youtube/%(uploader)s - (%(upload_date)s) - %(title)s - %(id)s - [%(format_id)s#%(height)sp].%(ext)s --write-description --write-info-json --write-annotations --write-thumbnail --merge-output-format mkv --write-sub --embed-thumbnail --add-metadata -f bestvideo[ext=webm][height<=?480][fps<=?30]+bestaudio[ext=webm]/bestvideo[height<=?480][fps<=?30]+bestaudio/best --download-archive C:/Temp/_youtube/ytdl-archive.txt --cookies C:/Temp/_youtube/cookies.txt https://www.youtube.com/watch?v=uw8MACDZ3RI`

**Comment by axcore** [comment]
Ok, I got it. youtube-dlc is using the same message to confirm the download of the subtitles files as it does for the video file, therefore one is mistaken for the other.

**Comment by axcore** [comment]
> I don't think they do the comments, was asking if it was possible so I guess not :/

Sorry, I misread your original question: youtube-dl can get the number of comments, but not the comments themselves (and not the live chat), as far as I know.

**Comment by axcore** [comment]
Fixed in v.2.3.015. Tartube will only use the path to a video file if it's actually a valid video (or audio) file. I was able to reproduce your problem, and this fixes it.

This is how to fix your database:

If you only have one or two videos pointing to wrong file, you can change them manually. Right-click each video and select **Show video > Properites**. In the edit window, next to the **File** line, there's a new button you can use to change the file.
 
If there are lot of videos pointing at the wrong file, it would be quicker to delete them from the database. When the dialogue window asks if you want to delete the **files** as well, say no. Then, click the **Check all** button (or check every affected channel/playlist separately). Then click **Operations > Refresh database**, which will mark the videos as having been downloaded.

**Comment by ceonelson** [comment]
Thanks! Manually editing the file works and allows tartube to display the thumbnail in the window now / launch the player with the file, so that helps.

It appears that the other fields aren't updated to reflect what they would be on a valid dl:

under video properties it has:
#525 video icon then in the field to the right:
Christopher F. Rufo - (20200803) - Chaos by the Bay - The Truth About Homelessness in San Francisco - uw8MACDZ3RI - [244+251#480p].en
(should be as above without the .en on end)

listed as field is also:
Christopher F. Rufo - (20200803) - Chaos by the Bay - The Truth About Homelessness in San Francisco - uw8MACDZ3RI - [244+251#480p].en
(should be just the video title: Chaos by the Bay - The Truth About Homelessness in San Francisco)

The file size is also still showing 17k vs the actual video size (in this case 40mb).

2 questions:
1) is there a way to have those fields be updated to the correct values upon changing the video file?
2) can clicking the video file edit button launch the file picker to the current path of the file?

Assuming this error won't happen any more I understand if you don't want to spend time on 1, but if 2 is easy enough I'd appreciate it!

**Comment by axcore** [comment]
>is there a way to have those fields be updated to the correct values upon changing the video file?

I can update the file size, but the video name comes from the download, not from the file. The only way to correct this is to **check** the videos/channels/playlists again, as described above.

>can clicking the video file edit button launch the file picker to the current path of the file?
That would certainly be useful, but it won't be possible until the Gtk team decide to write a better file chooser.

**Comment by axcore** [comment]
In v2.3.020, changing the file will reset the video's duration and file size. I was also able to send the file chooser dialogue directly to the correct directory, after a little jiggery-pokery.
