### ISSUE TITLE
Brand new install of install-tartube-2.3.008-64bit.exe setup fails at "Install FFmpeg"

### ISSUE THREAD

**Issue by PillarOfJoy** [axcore/tartube#212]
Setup process:
1) Install install-tartube-2.3.008-64bit.exe fresh
2) Run application
3) Chose folder
4) Chose "youtube-dlc"
5) Chose "Install and update downloader", then "Next"
6) Click "Install FFmpeg" button and application window closes.

### What operating system are you using?
Windows 10

### What version of Tartube are you using?
install-tartube-2.3.008-64bit.exe

### What happens when you run Tartube from a terminal window?

$ python3 tartube/tartube
**
Gtk:ERROR:../gtk+-3.24.20/gtk/gtktextview.c:4451:gtk_text_view_validate_onscreen: assertion failed: (priv->onscreen_validated)
Bail out! Gtk:ERROR:../gtk+-3.24.20/gtk/gtktextview.c:4451:gtk_text_view_validate_onscreen: assertion failed: (priv->onscreen_validated)

**Comment by axcore** [comment]
Workaround: don't install FFmpeg in the setup window. Install it from the main window instead, **Operations > Install FFmpeg...**

**Comment by axcore** [comment]
Fixed in v2.3.015 (available from PyPI and github only). 

You probably don't need to update Tartube, since downloads from the main window are not affected.
