### ISSUE TITLE
change video quality on youtube in Classic Mode

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#214]
how to change video quality on youtube in Classic Mode?

**Comment by axcore** [comment]
Can you do that in the **download options** window?

**Comment by candrapersada** [comment]
> Can you do that in the download options window?

yes but why is there no video quality change in Classic Mode?

**Comment by axcore** [comment]
Classic Mode is supposed to be a copy of youtube-dl-gui, so I can't add too many new features there. I think the tab is already quite crowded.

**Comment by axcore** [comment]
Closed for inactivity.
