### ISSUE TITLE
Why doesn't there check the Tartube update

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#216]
why is there no menu to check for updates?

**Comment by axcore** [comment]
This is the reason: many users are paranoid. If Tartube sends messages to a website, then paranoid users won't use Tartube at all.

**Comment by candrapersada** [comment]
I mean how to check for updates like this image
![Capture](https://user-images.githubusercontent.com/36833664/101879984-c2a2a580-3bc4-11eb-96db-85d26e385c87.PNG)

**Comment by axcore** [comment]
Also, Tartube is probably finished. I think there will not be new features, just bug fixes sometimes.

**Comment by axcore** [comment]
Added in v2.3.072.
