### ISSUE TITLE
Auxiliary files not deleted upon re-download

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#219]
### What operating system are you using?
Win 10

### What version of Tartube are you using?
2.3.015

I had downloaded a video (my default is @480p) then after watching decided I'd like to save it at 1080p so I applied download options to it, changed the res and then re-download video.  When it was done I noticed it had left the old auxiliary files on disk since my file name stores the resolution which had changed:
![image](https://user-images.githubusercontent.com/16659133/101979707-fe6d5780-3c24-11eb-9615-741ee48f17e2.png)

**Comment by axcore** [comment]
Fixed in v2.3.020. The metadata files should be deleted when you re-download a video (regardless of whether the name has changed, or not.)
