### ISSUE TITLE
Max # of videos?

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#220]
Just curious, what's the max # of videos that the db has been tested with?

Is there any theoretical limit to be aware of?

**Comment by axcore** [comment]
I have one with 60,000 videos (all downloaded), and it does not present any problems, even when running on a slow-ish laptop.

The database file this generates is not very big (a few megabytes). Projecting upwards from that, there is no reason why Tartube shouldn't be able to cope with databases of millions. I don't know how Python handles limits on physical memory, but presumably you would eventually get an 'out of memory' errror.

A channel/playlist/folder is sorted when new videos are added. If you tried to download a channel with hundreds of thousands of videos (these things actually exist on YouTube) then that might conceivably lead to a slowdown. i don't have the disk space or the bandwidth to test that proposition though.

**Comment by DankMemeGuy** [comment]
I'm at 106,144 and it's running like butter.

**Comment by ceonelson** [comment]
Wow that's great to know!  I'm sure others would too, might be helpful to put a blurb in the readme about how awesomely large it can run :)

@DankMemeGuy dang, how much storage are you using?!

**Comment by DankMemeGuy** [comment]
@ceonelson my YouTube folder is sitting at 27.1TB, but I'm in the process of using http://tdarr.io/ to compress the entire archive to H265 to probably cut down the space used by 30-50%.

I don't think you will likely ever run into issues with Tartube. I have 32GB RAM, and a Ryzen 3600, running Windows 10. The only time Tartube isn't running for me is when I'm performing an update/restart. It's been running for me for months. Maybe most of 2020 at this point. Plus, @axcore does an amazing job with any issues in the software! I swear he must be a former Googler with his level of expertise.
