### ISSUE TITLE
gallery-dl integration

### ISSUE THREAD

**Issue by mbnoimi** [axcore/tartube#221]
I suggest adding an integration for [gallery-dl](https://github.com/mikf/gallery-dl) similarly to `youtube-dl`
The commands are very similar and both of them use `pip`

**Comment by axcore** [comment]
I have been thinking about this. There are two possibilites; either create a new client, or modify Tartube to work with gallery-dl. In both cases, it would be weeks of work, and I don't have enough time to do it right now.

We can keep this issue open, though, in case I'm able to find some time.
