### ISSUE TITLE
Bulk adding channels

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#222]
Would be nice to be able to bulk add channels, something like a large input box that allows for a simple one-line format like:

Channel Name, Folder Name, Link

**Comment by axcore** [comment]
What happens if **Channel name** or **Folder name** contains commas?

**Comment by axcore** [comment]
I experimented with storing multiple URLs in a buffer, but it tends to make the process of adding new channels/playlists even more cumbersome than it already is, so I abandoned that idea.

**Comment by DankMemeGuy** [comment]
Mhmm, maybe have a box but then instead of storing it in a buffer, it can behind-the-scenes add each link as if the user had inputted it each time? Could just store the textbox in a hidden textfile in the program files then when its done the adding process empty the textfile

**Comment by axcore** [comment]
That's what I tried. It sounds good in theory, but in practice it's cumbersome.

**Comment by axcore** [comment]
I added some new things in v2.3.203. The updated code is only available from pypi/github at the moment.

First, click **Media > Any many channels/playlists**, and you'll see this dialogue, which is more or less what you requested:

![newdia](https://user-images.githubusercontent.com/37951926/125104567-6f022700-e0d5-11eb-9a8e-415c911c5517.png)

Secondly, in **Edit > Systerm preferences... > Files > URLs** you'll find some stuff for updating the URLs of channels/playlists you've already added. It includes a search-and-replace button.

**Comment by axcore** [comment]
I also added export/import using .CSV in v2.3.233.
