### ISSUE TITLE
is_network_error bug

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#223]
So I had started to dl a channel yesterday and it stopped at some point. Restarted it when I left today, get back and it shows 237/237 status: downloading at the top of the progress window, output tab shows [download] finished downloading playlist but when I switch back to videos tab it shows 67/67 in the treeview (that's where it errored out yesterday) and the progress bar at the bottom is 50%.  I canceled the DL and it refreshes to show 236/236, one video shows (video with no name) and "Can't D/L No Link" but the file itself has a # instead of % in the filename and ends with '.webp" to JPEG' which is weird.

Anyways I went to check terminal and saw the error below twice (looks like relating to auto restart upon network). Haven't tried this in the latest release yet so that part might be fixed already but wanted to also see if you've had any issues where the video URL doesn't get assigned to a DB entry and the last part of [ffmpeg] converting thumbnail output line gets set as the File.

That video is isn't in the archive.txt (along with possibly one other video since channel says 237 but i only have 235 lines there). Should I just delete that video with no link and then download channel again to try and get the missing 2 videos?

In the meantime I'll update to .020 and download another channel and see if I get that error below again.

Thanks!

### What operating system are you using?
Win 10

### What version of Tartube are you using?
2.3.015

### What happens when you run Tartube from a terminal window?
Exception in thread Thread-561:
Traceback (most recent call last):
  File "C:/Users/Z/Documents/___Apps/Tartube/msys64/mingw64/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/downloads.py", line 1042, in run
    self.run_video_downloader(media_data_obj)
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/downloads.py", line 1139, in run_video_downloader
    return_code = self.downloader_obj.do_download()
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/downloads.py", line 2912, in do_download
    and self.is_network_error(stderr):
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/downloads.py", line 4732, in is_network_error
    if re.search(r'unable to download video data'):
TypeError: search() missing 1 required positional argument: 'string'

**Comment by axcore** [comment]
You guys need to give me time to finish my breakfast, before you start posting issues ;)

**Comment by axcore** [comment]
I patched that error, it's just one line in [tartube/downloads.py](https://github.com/axcore/tartube/blob/master/tartube/downloads.py)

**Comment by candrapersada** [comment]
ERROR: unable to download video data: <urlopen error [Errno 101] Network is unreachable>
