### ISSUE TITLE
applied custom download options deleted

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#224]
I have a main folder "politics" with download options applied to it. I added a video underneath that folder, apply download options -> use these options, chose "politics" then edited it to increase the resolution. Video downloaded. I added a new video, went to do the same steps, only "politics" is no longer listed as an option to import from. No longer shows in Sys Pref -> Options -> Download Options. Neither is the video I just downloaded.

Right click on politics folder -> edit download options and now instead of "download options applied to" #5 (politics folder id) it has #827 (the last video id) and the parameters are set to the high resolution of it.

I have "after downloading a video, remove its download options" selected.

To test, I created a custom dl option of 1080p. Applied it to a new video, edited the option (it had that videos id as the option #), then downloaded the video and the new 1080p download option profile was removed upon completion.

Expected behavior: If I select "use these options" it is a template that I want to keep and wouldn't be deleted upon download completion (rather the specific video's options and any changes I made for that video would be deleted).

What happened: imported download options were deleted, not just the video's copy of them.

### What operating system are you using?
Win 10

### What version of Tartube are you using?
2.3.020 latest as of 2020/12/14

### What happens when you run Tartube from a terminal window?
n/a

**Comment by ceonelson** [comment]
I restored an earlier backup so that the folder's download options would be correct. The video I downloaded above was still in there (but Tartube showed it not downloaded or had any DL options applied), so I did properties to point it to the downloaded file and got an error "The replacement video/audio file must be in the same channel, playlist or folder" (which it is).

I tried with another video that Tartube showed as downloaded (the live_chat.json error from before) and got the same message, so it looks like at some point after the initial "point to file" button was added this bug happened.

**Comment by axcore** [comment]
Ok, one step at a time:

>I have a main folder "politics" with download options applied to it. I added a video underneath that folder,

What do you mean, "underneath that folder"? Do you mean you added a video inside the politics folder, like this?

![ymca](https://user-images.githubusercontent.com/37951926/102186389-77311580-3eaa-11eb-9d21-f89f049530c4.png)

**Comment by ceonelson** [comment]
Yeah, actually in a subfolder under politics. Then went to apply a download option to just that newly added video so I could d/l it at a higher quality.

**Comment by axcore** [comment]
Right, so you have a setup like this

![ymca3](https://user-images.githubusercontent.com/37951926/102253581-6b237300-3eff-11eb-9b92-ed6fd6537b9c.png)

...but if you right-click the video, select **Downloads > Apply download options**, then the download options called **politics** should not be visible, because one set of download options can only be applied once in the tree.

Perhaps you have several sets of download options, each one called **politics** (but each with a unique ID number)? To get a list of all download options, click **Edit > System preferences... > Options > Download options**

**Comment by ceonelson** [comment]
yeah that's really weird, if I right click on Politics folder and edit download options it shows the name as Politics and has all the right settings but "download options applied to" says 'these options are not applied to anything" 

No idea when or how that happened but that's probably a separate issue.

Only one politics dl profile (id #5) and I had created a new global option 1080p which is what I had applied to the video.

With your test DB above, have you been able to reproduce the disappearing DL options?
Have "after downloading a video, remove its download options" selected.
1. Sys Pref -> Options -> Download Options, create new profile named vanish
2. apply custom download options to the village people video, choose vanish
3. dl the video and upon completion the vanish profile is gone from sys pref -> DL options, rather than just the village people's copy of it

**Comment by axcore** [comment]
The following behaviour is expected:

- Create a set of download options called 'vanish'
- Apply it to a video
- Download the video
- The 'vanish' options have disappeared from the list

In the **System preferences** window, I will change the text to **After downloading a video, _destroy_ its download options**

**Comment by axcore** [comment]
The other problem I cannot reproduce:

- Create a folder called **politics**
- Right-click the folder, **Downloads > Apply download options**, select **Create new download options**
- In the **Download options** window, check that the correct folder is visible
- Click OK to close the window
- Add a video inside the poltiics folder
- Right-click the video, **Downloads > Apply download options**
- Select **Use the download options**
- The download options called **politics** are not in the list

**Comment by ceonelson** [comment]
> The following behaviour is expected:
> 
> * Create a set of download options called 'vanish'
> * Apply it to a video
> * Download the video
> * The 'vanish' options have disappeared from the list
> 
> In the **System preferences** window, I will change the text to **After downloading a video, _destroy_ its download options**

Is there a way to make an option to save the "base" (template?) download option but delete any tweaks done once it has been applied to the video?  To me it makes more sense that anything created from the download options window is more of a template than a one-off.  

An option like that would enable them to be used as a template without them getting deleted when they're applied to a video, while also not cluttering up the download options with any customizations done to a specific video's download options :)

**Comment by ceonelson** [comment]
> The other problem I cannot reproduce:
> * (On your system, **politics** _was_ in the list)
Politics was only in the list because it had somehow gotten "un-applied" from the folder (even though the politics folder still has the custom download options and settings on it).

I just went to check something and it turns out either I was delusional or DL opts worked differently in earlier versions but I had an "audio only" folder and custom DL opt. Yesterday I create a playlist for a soundcloud library and right click -> dl -> apply dl opts and it let me choose audio only format to apply. 

Now my audio only folder is like the politics one above: still shows the custom dl option icon and has those settings, and when i click edit dl opts it shows "dl opts applied to:" soundcloud playlist above.

Sorta going along with my reply above, I thought there was a way to have the same DL "template" applied to multiple folders at the same time (ie my audio only dl opt would be on the Audio Only folder, the new soundcloud playlist, future podcast playlist, etc) and if that base "audio only" template was modified the folders assigned to use it would all take the new setting.

**Comment by axcore** [comment]
>Is there a way to make an option to save the "base" (template?) download option but delete any tweaks done once it has been applied to the video? 

No, but I can add the ability to clone a set of options, which will achieve the same thing.

Right-click video, **Downloads > Apply download options**, and in the window add a list marked **Clone these download options**.

**Comment by axcore** [comment]
> Now my audio only folder is like the politics one above: still shows the custom dl option icon and has those settings, and when i click edit dl opts it shows "dl opts applied to:" soundcloud playlist above.

I can't reproduce this behaviour. Your choices are: (1) create a new database, and try to reproduce the problem yourself, so that I can follow exactly the same steps as you, or (2) delete all download options in the database, and then create new ones.

>Sorta going along with my reply above, I thought there was a way to have the same DL "template" applied to multiple folders at the same time

This is not possible at the moment. A set of download options can only be applied once in the tree. In this example, a set of download options can be applied to **testme1** or **testme2**, but not both of them.

![testme](https://user-images.githubusercontent.com/37951926/102473764-c2385d80-404f-11eb-93e6-07d3c3162d64.png)

**Comment by axcore** [comment]
It's possible that I found the cause of your original problem, and the one mentioned in https://github.com/axcore/tartube/issues/228. I still can't reproduce it, though, so I can't be sure.

The fixed code is v2.3.035 and can be downloaded from github/pypi now. There will be a full release in a couple of days.

**Comment by axcore** [comment]
Closed for inactivity.

**Comment by xbliss** [comment]
> In the **System preferences** window, I will change the text to **After downloading a video, _destroy_ its download options**

I am having a tiny issues/ bug here - Everytime I go in and UNCHECK this box in Sys Prefs, and go OK. 

I go and check its checked again. 

How / why is this happening? Have not seen this with any other settings.

**Comment by axcore** [comment]
@xbliss It is always better to start a new issue, rather than to regurgitate an old one :)

Your problem is fixed in v2.3.302. You can download it now from github, or wait for a full release some time in the next few days.

**Comment by xbliss** [comment]
> @xbliss It is always better to start a new issue, rather than to regurgitate an old one :)
> 
> Your problem is fixed in v2.3.302. You can download it now from github, or wait for a full release some time in the next few days.

Thanks. I googled that thing first so that I was not troubling you without cause, and this was the only place it showed up. 

Albeit, it was being fixed as I found it. Got the new and much awaited release.
