### ISSUE TITLE
Proxy list

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#226]
I have a handful of proxies I use, it would be nice to be able to have Tartube allow for a textfile for proxies, or multi-line inout. I often get rate-limited with how much I'm downloading. Tartube could just cycle through the proxy list for each video it needs to download in the operation.

Right now Tartube accepts 1 proxy URL, but with a multi-line input (1 proxy per line), it can just cycle through.

**Comment by axcore** [comment]
Done. Do you have a couple of proxies with which I can test the new code?

**Comment by axcore** [comment]
Added in v2.3.035. Click **Edit > System preferences... > Operations > Proxies** for a space where you can add a list of proxies. When checking/downloading videos, Tartube will cycle between them. 

(It is not possible to switch proxies while downloading a channel or playlist, but if you are downloading ten playlists, then you should see the proxy switching.)

If you have specified a proxy in the download options (for example, **Edit > General download options... > Advanced > Network**, then this proxy overrides the new list.

I don't have any proxies for testing, so you will have to do the testing for yourself.

**Comment by DankMemeGuy** [comment]
I believe it's working! Does the error window show proxy errors by any chance? if one proxy stops working for example, would it show something like "[Proxy IP] did not respond - timed out" etc?

**Comment by axcore** [comment]
> Does the error window show proxy errors by any chance? 

Not yet, I don't have any proxies to test so I don't know what messages to intercept.

**Comment by candrapersada** [comment]
how to configure youtebe-dl when using PAC on Tartube?

**Comment by axcore** [comment]
I don't know anything about PAC, and I don't know how to configure youtube-dl for PAC.

**Comment by axcore** [comment]
Closed for inactivity.
