### ISSUE TITLE
checks errors

### ISSUE THREAD

**Issue by urfausto** [axcore/tartube#229]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
7 64 bit

### What version of Tartube are you using?
v2.3.008

these errors happen upon right-click 'check video' and halting download for 'check all videos etc.':
youtube-dlc --newline -i --hls-prefer-native -o C:/Program Files/Tartube/DB/3b/%(title)s.%(ext)s --write-description --write-info-json --write-annotations --write-thumbnail -x --audio-format mp3 --audio-quality 0 --dump-json --download-archive C:/Program Files/Tartube/DB/3b/ytdl-archive.txt --cookies C:/Program Files/Tartube/DB/cookies.txt https://www.youtube.com/watch?v=ZgtTcYRQhd4
[3b] <Simulated download of: 'La quarantena dei Giganti'>
WARNING: unable to extract xsrf token; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.

WARNING: unable to extract xsrf token; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
WARNING: unable to extract xsrf token; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
WARNING: unable to extract xsrf token; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
WARNING: unable to extract xsrf token; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
WARNING: unable to extract xsrf token; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
WARNING: unable to extract xsrf token; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
WARNING: unable to extract xsrf token; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
WARNING: unable to extract xsrf token; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
WARNING: unable to extract xsrf token; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
WARNING: unable to extract xsrf token; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.

**Comment by axcore** [comment]
These warnings are generated by youtube-dl(c). Everyone is seeing the same warnings. Eventually youtube-dl(c) will be fixed, and you won't see the warnings any more.

You can filter out errors and warnings that you don't want. Click **Edit > System preferences... > Windows > Websites**.

![xtoken](https://user-images.githubusercontent.com/37951926/102994694-71c17400-4517-11eb-84b8-7c57b38bf240.png)
