### ISSUE TITLE
settings & db location

### ISSUE THREAD

**Issue by legrostdg** [axcore/tartube#23]
tartube seems to store its settings.json and its tartube.db and tartube_BU.db in my $HOME. It would be nice if it could use $XDG_CONFIG_HOME/tartube/settings.json and $XDG_DATA_HOME/tartube.db

**Comment by axcore** [comment]
The config file is stored $XDG_CONFIG_HOME from v1.1.015.

The tartube.db file needs to stay with its videos. (One reason is that I want to add multiple database files, for users who have several external hard drives).
