### ISSUE TITLE
Liked Videos playlist 

### ISSUE THREAD

**Issue by ERasnier** [axcore/tartube#230]
Is it possible to download videos from the Liked Videos playlist? And would it be possible to unlike the videos that get listed?

I generally use the whole liking feature as a watch later playlist since the original Watch Later playlist has a limit and I found out that so does Liked Videos.

**Comment by axcore** [comment]
Are you talking about "liked" videos on YouTube?

youtube-dl(c) doesn't know anything about liked videos. It just sees a webpage with one or more videos on it, and downloads them all.

Are you talking about a way to "like" videos in Tartube's database?

You can bookmark the videos you want, then right-click the **Bookmarks** folder to download them all. See [here](https://github.com/axcore/tartube#6161-bookmarked-videos).

**Comment by ERasnier** [comment]
> Are you talking about "liked" videos on YouTube?
Yeah pretty much. The general idea is to transfer all "liked" videos into Tartube and have them removed from the Liked Videos list automatically once it's been grabbed. I guess I'll have to find another way of doing this.

Thanks!
