### ISSUE TITLE
autoupdate

### ISSUE THREAD

**Issue by urfausto** [axcore/tartube#234]
well, easily i would request this: get an auto update button inside the application. currently i have to download the package manually, correct?

**Comment by DankMemeGuy** [comment]
If not this, it would be nice to be able to atleast 'check for update' inside the software. It could ping the github's version file and if it's larger than the current one installed then let the user know.

I have to keep checking the github every few days to see if an update happened right now

**Comment by urfausto** [comment]
> I have to keep checking the github every few days to see if an update happened right now

yes, exactly. at least check for update and link to direct download of the new version.

**Comment by urfausto** [comment]
merry christmas anyway! :snowman_with_snow:

**Comment by axcore** [comment]
>well, easily i would request this: get an auto update button inside the application. currently i have to download the package manually, correct?

Technically very difficult, because installation is handled by a packager (like DEB or RPM or PyPI), and those packagers put Tartube's files anywhere they want. An auto-update button would probably fail more often that it would succeed.

>If not this, it would be nice to be able to atleast 'check for update' inside the software. 

My reasoning for not doing this is user paranoia: think how many people don't want anyone to know what they are downloading using Tartube. At the moment, I can tell everyone that Tartube doesn't send any user data anywhere, under any circumstances. If I added a 'check for updates' button, I could no longer say that.

**Comment by DankMemeGuy** [comment]
> My reasoning for not doing this is user paranoia: think how many people don't want anyone to know what they are downloading using Tartube. At the moment, I can tell everyone that Tartube doesn't send any user data anywhere, under any circumstances. If I added a 'check for updates' button, I could no longer say that.

Fair reasoning. What if you made it an option people could enable in the settings, but disabled by default?

**Comment by axcore** [comment]
OK, I can add an experimental **Check for updates** button, and we will see if the number of complaints is  higher than the complaints that the button doesn't exist yet

**Comment by urfausto** [comment]
> Fair reasoning. What if you made it an option people could enable in the settings, but disabled by default?

+1
optional enable feature in the settings with warning about privacy issues.
please with direct link to the download (like qbittorrent for example or similar)

**Comment by candrapersada** [comment]
menu to check for updates? #216

**Comment by axcore** [comment]
In v2.3.072, I added a button to check for Tartube updates.

Click **Help > Check for updates** to use it. Users can see exactly what is being downloaded, and from where, by clicking the **Output** tab. I think this is a reasonable compromise for paranoid users.

As explained above, there is no practical way to introduce an auto-update feature, so I will close this issue now.
