### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#235]
Definitely not a pressing feature, but I think it would be cool to have a statistics tab. To see how many channels per folder, how many channels overall, how many videos overall, maybe graphs/charts for how many daily/monthly/yearly downloads, etc.

I'm not sure what data you store per download but could be neat to see some of the information!

**Comment by axcore** [comment]
>I'm not sure what data you store per download but could be neat to see some of the information!

Statistics for each video, such as the upload and download times, are stored for each video, and visible by right-clicking the video, and selecting **Show video > Properties...**

Tartube doesn't store statistical information like that for channels/playlists, so that would have to be reconstructed, one video at a time.

**Comment by DankMemeGuy** [comment]
Hmm, I'm confused. How is it showing (xxx/xxx) in the name of each channel? Then it shows "All Videos (xxx/xxx)".

If it's showing the totals for those, than can't it just also start to add that up? So if a folder has 2 channels in it each with 100 videos then the folder name would be something like "Folder Name (xxx/200)"

Also when I hover over a channel it says "#X:" so imagine somewhere it's keeping track of how many channels are per folder?

When I say statistics per video, I meant the cumulative, so it could show how many videos were downloaded on a graph.

I think the information is all there just not on one convenient page

**Comment by axcore** [comment]
> Hmm, I'm confused. How is it showing (xxx/xxx) in the name of each channel? Then it shows "All Videos (xxx/xxx)".

All of the data Tartube stores for each video/channel/playlist/folder is visible by right-clicking them, and selecting **Show > XXX properties**.

I can add the feature this feature, I'm just telling you about the statistics that already exist :-)

**Comment by axcore** [comment]
v2.3.072 adds the statistics and graphs you wanted.

Statistics are available to all users. Graphs depend on the [Python module matplotlib](https://matplotlib.org/) library, so you must install that on your system if you want to see graphs. On Linux (etc), use your normal software manager. On 64-bit MS Windows, run the terminal window:

**C:\Users\YOURNAME\AppData\Local\Tartube\msys64\mingw64.exe**

And in it, type the following command:

**pacman -S mingw-w64-x86_64-python-matplotlib**

..then restart Tartube.

Statistics and graphs are visible in several places, for example **Edit > System preferences... > Files > Statistics** and **...Files > History**.

You can also see statistics/graphs for an individual channel, playlist or folder. For example, right-click a channel and select **Show > Channel properties > History**.

**Comment by DankMemeGuy** [comment]
Thank you so much! This is perfect!
