### ISSUE TITLE
Not a Question, just a great review. 

### ISSUE THREAD

**Issue by aaronsql2019** [axcore/tartube#236]
hey

I've been looking for something like this for years. It worked. I've got some concerns that I think I told it to download 600 different videos and I'm only seeing 330. I wish that this product was a TINY bit more detailed in showing how many videos are on a playlist, and helps me to understand what I've got.

I love how you guys asked me which algorithm to use when I first started. But I'm curious what I can do to go back and eval the other options. 

I wish that this would tie all of the updates, the Logs, the Detailed Error Messages, and the Counts of 'What had been scanned' and 'From where' and 'why' and I wish that all that data would go into a SQLITE database so that I could look at it further.

I wish I could help in some regards. But I'm VERY happy that I have found your software, and i'm looking forward to using this for hundreds of different things,. I hate needing to be online to watch videos, I have VERY slow internet at home. I'm hoping that I can put a REVIEW of each of these videos on my website., 

So it would be nice to know a better detailed description, like 'This Video, called 1234.xyz was taken from this URL at this time'. 

Having logging information like that would make that so much cooler.  Most people want to cover their tracks. I just want to be able to refer to the original work.

**Comment by axcore** [comment]
> I wish that this product was a TINY bit more detailed in showing how many videos are on a playlist

**Edit > System preferences.... > Windows > Videos > In the Video Index, show detailed statistics...**

>I love how you guys asked me which algorithm to use when I first started. But I'm curious what I can do to go back and eval the other options.

To create a database somewhere else, **File > Database preferences...**

To change the downloader, **Edit > System preferences... > Downloaders > Forks**

** I wish that all that data would go into a SQLITE database so that I could look at it further.**

The reason for not adding support for SQLITE, is that the data would have to be converted back to python's standard data format, and this would increase the load/save time from a couple of seconds to several minutes. Also, I don't know anything about SQLITE so the development time would include the time needed to read up on that.

In case you didn't know, you can drag and drop from most tabs into an external application (for example, a text editor). To set which information is attached to a drag and drop, **Edit > System preferences... > Windows > Drag**.

>So it would be nice to know a better detailed description, like 'This Video, called 1234.xyz was taken from this URL at this time'.

Right-click the video and select **Show video > Properties...**. If tooltips are enabled (**Edit > System preferences ... > Windows > Main window > Show tooltips for videos, channels playlists and folders**) you can see some of the information by letting your mouse hover over the video.

**Comment by aaronsql2019** [comment]
Thanks so much.

**Comment by aaronsql2019** [comment]
Freelancer (https://www.freelancer.com/)

Aaron has given you $20 USD to try Freelancer!

Freelancer.com gives you access to millions of freelancers from all around the world. Simply answer a few quick questions to post a project, and receive free quotes from freelancers in just a few minutes.

Claim Your $20 → (https://www.freelancer.com/get?id=43407296&source=gge)

* Credit available when you have verified your payment method.

What can you get done on Freelancer?

Graphic Design (https://www.freelancer.com/graphic-designers)
Website Development (https://www.freelancer.com/website-developers)
Translation (https://www.freelancer.com/translators)

Marketing (https://www.freelancer.com/internet-marketing)
Mobile Development (https://www.freelancer.com/mobile-app-development)
Photography (https://www.freelancer.com/local/photography)

© 2020 Freelancer Technology Pty Limited. All Rights Reserved.

Level 37, 225 George Street, Sydney, NSW 2000, Australia

Privacy Policy (https://www.freelancer.com/page.php?p=info%2Fprivacy)  |  Terms and Conditions (https://www.freelancer.com/page.php?p=info%2Fterms)  |  Unsubscribe (https://www.freelancer.com/users/email/subscriptions.php?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkZyZWVsYW5jZXJcXEdBRlxcQ29yZVxcSldUXFxKV1QifQ.eyJpZCI6bnVsbCwic3ViIjoidW5zdWJzY3JpYmUiLCJpYXQiOjE2MDkyMDc1NDR9.Zt_fZEzaFwPkrveef5FeQIBg_cGA7hhIQUS3zp3gDfc)  |  Get Support (https://www.freelancer.com/support)  |  Get Free Credit (https://www.freelancer.com/give?from=email_footer)

Facebook (https://www.facebook.com/fansoffreelancer)

Twitter (https://twitter.com/freelancer)

Instagram (https://www.instagram.com/freelancerofficial)

Download our mobile app (https://bnc.lt/edm-download-freelancer)

(https://bnc.lt/edm-download-freelancer)

**Comment by axcore** [comment]
Mate, I can't accept donations. If I do that, Hollywood will sue me into oblivion :+1:

**Comment by aaronsql2019** [comment]
Join Freelancer Today! | Freelancer

(https://www.freelancer.com/)

Aaron has given you $20 in credit* to spend on our website.

Claim Your $20 Now → (https://www.freelancer.com/get?id=43407296&source=gge)

Freelancer.com gives you access to millions of freelancers, from all around the world.

If there's a task that you've been meaning to complete - whether it be for business or personal means - there's an expert out there who will get it done for you.

But the clock is ticking - you only have 48 hours left before we return the gift!

* Credit available when you have verified your payment method.

© 2021 Freelancer Technology Pty Limited. All Rights Reserved.
Level 37, 225 George Street, Sydney, NSW 2000, Australia

Privacy Policy (https://www.freelancer.com/about/privacy) | Terms and Conditions (https://www.freelancer.com/about/terms) | Unsubscribe (https://www.freelancer.com/emails/unsubscribe.php?s=MkpVaFRSRWNPYnNmWTFWcG95OW0zdF9jWEUzM0NESENCWWNqaE5QeDY3RjF4MENOQWFqb2UzVkNOSmtVc1lFQXRJaUMwMnlGZHZldlBURVclMkZxYW9LalBmJTJGMDN5TUpSWU9RTHp0Z1FGRUc5Q0N6MEdTQnJzR1M0c04lMkY5JTJGeURBZ2k2dkh1eFE2YWZzVTRqcGFIdXVuRHVj) | support@freelancer.com (mailto:support@freelancer.com)

Facebook (https://www.facebook.com/fansoffreelancer) Twitter (https://twitter.com/freelancer) Instagram (https://www.instagram.com/freelancerofficial)

Download our mobile app (https://bnc.lt/edm-download-freelancer)

(https://bnc.lt/edm-download-freelancer)
