### ISSUE TITLE
youtube audio download issues

### ISSUE THREAD

**Issue by learnfromit** [axcore/tartube#237]
Attempting to use this program to download youtube audio. Here are the steps taken:

Edit - > download options -> sound only -> checked the box and mp3 / high.

edit-> download options -> formats - > attempted both m4a and mp4  - > merge post -processing output format: mp4.

Edit - > download options -> post - processing - > post-process video files to convert them to audio only files checked / mp3/ keep original file after processing it is unchecked. 

Ive reinstalled several times, reinstalled FFmpeg , used both youtube dl and dlc. It always spits out 4 files with the main one being a .webm video. 

anything i did wrong?  does it just not work at the moment? heres some outputs and warnings. 

youtube-dlc --newline -i --hls-prefer-native -o C:/Users/glitc/mD/%(title)s.%(ext)s --write-description --write-info-json --write-annotations --write-thumbnail --cookies C:/Users/glitc/mD/cookies.txt https://www.youtube.com/watch?v=fL1pnzQj5j8
[youtube] fL1pnzQj5j8: Downloading webpage
[info] Writing video description to: C:/Users/glitc/mD/Prismo - Solo.description
[info] Writing video description metadata as JSON to: C:/Users/glitc/mD/Prismo - Solo.info.json
[youtube] fL1pnzQj5j8: Downloading thumbnail ...
[youtube] fL1pnzQj5j8: Writing thumbnail to: C:/Users/glitc/mD/Prismo - Solo.webp
[download] Destination: C:/Users/glitc/mD/Prismo - Solo.f303.webm
[download] 100% of 76.33MiB in 00:02
[download] Destination: C:/Users/glitc/mD/Prismo - Solo.f251.webm
[download] 100% of 2.97MiB in 00:00
[ffmpeg] Merging formats into "C:/Users/glitc/mD/Prismo - Solo.webm"
Deleting original file C:/Users/glitc/mD/Prismo - Solo.f251.webm (pass -k to keep)
Deleting original file C:/Users/glitc/mD/Prismo - Solo.f303.webm (pass -k to keep)
WARNING: unable to extract xsrf token; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
WARNING: There are no annotations to write.

**Comment by axcore** [comment]
`youtube-dlc --newline -i --hls-prefer-native -o C:/Users/glitc/mD/%(title)s.%(ext)s --write-description --write-info-json --write-annotations --write-thumbnail --cookies C:/Users/glitc/mD/cookies.txt`

This command does not tell youtube-dl(c) to download audio only. Either you reset the download options accidentally (**Edit > General download options... > Completely reset all download options to their default values**), or the download options you were editing don't apply to the video  (an explanation of how it works is [here](https://github.com/axcore/tartube#6112-other-download-options).)

I have tested both of these methods, and they both work:

Method 1
**Edit > General download options... > Completely reset all download options to their default values**)
Click the **Hide advanced download options** button, if visible
Click the **Sound only** tab
Select the checkbox, and select **mp3** and **high**
Click the **OK** button to save the changes

Method 1
**Edit > General download options... > Completely reset all download options to their default values**)
Click the **Show advanced download options** button, if visible
Click the **post-processing** tab
Select **Post-process video files to convert them to audio-only files**
Click the **OK** button to save the changes

**Comment by learnfromit** [comment]
Ok. So the issue was that I was downloading through the "classic mode" tab. If i do it through the "videos" tab it works.

**Comment by axcore** [comment]
The Classic Mode tab has a separate set of download options (by default). Click the menu button in the top-right corner to show them!
