### ISSUE TITLE
Making tartube accessible to screenreader, adopt inclusive design principle

### ISSUE THREAD

**Issue by kaveinthran** [axcore/tartube#239]
HI,

As a blind user, I find it disappointing that I can't use tartube at all. NO controls are visible to my screenreader and I can't operate the application wiht keyboard at all.

as a blind user, I use screenreader which depend on the application programming structure to convey information to me. I really hope the developer will put an effort to adopt inclusive principle to design the app so that the app will be accessible to all,

You can try using the opensource and free screenreader nvda with Tartube to get the bigger picture,
download nvda here
https://www.nvaccess.org/download/ 
Thanks for taking the time to submit a feature request! 

### Make sure you are using the most recent version of Tartube
Perhaps your feature request has already been implemented. The most recent version can be downloaded from Github

### Please read the README
Perhaps your feature request is already possible

**Comment by axcore** [comment]
I'm sorry to say that popular screenreaders like JAWS and NVDA don't support applications written with GTK. This problem has existed for years, and neither the developers of JAWS, nor NVDA nor GTK have shown any interest in fixing it.
