### ISSUE TITLE
Can't download higher than 720p 30fps

### ISSUE THREAD

**Issue by NightshadeGS** [axcore/tartube#241]
I am trying to simply download an mp4 with audio at 1080p 60fps, but all I can get is 720p 30fps webm without audio. Nothing else works. I have ffmpeg auto installed using the tartube installer tool in addition to youtube-dlc. I have been at it for 3 days and google has been useless. I have had this same exact issue with every single version of youtube-dl including the original. Is it just incapable of doing this?

Windows 10 64-bit

Tartube v2.3.042

**Comment by axcore** [comment]
Are you sure the video is available in 1080p? Right-click the video, select **Fetch > Available formats**, and see the list of formats in the **Output** tab.

**Comment by NightshadeGS** [comment]
> 
> 
> Are you sure the video is available in 1080p? Right-click the video, select **Fetch > Available formats**, and see the list of formats in the **Output** tab.

Yes, I was watching it in 1080p when I decided to download it. This is the video: https://www.youtube.com/watch?v=ohNpf4VnlP8

**Comment by axcore** [comment]
I tested that URL, and it looks like I received the 1080p 60fps video. This is what VLC says about it:

![60fps](https://user-images.githubusercontent.com/37951926/103560173-3a57ad80-4eaf-11eb-9e6e-80b21dba06de.png)

In this test, I used a specified video format, #299. **Edit > General download options... > Formats**

![60fps2](https://user-images.githubusercontent.com/37951926/103560287-712dc380-4eaf-11eb-8b3f-3f1e30236245.png)

Could you test downloading the video with that format? Can you show me a screenshot of the **Output tab**, when you download that video, in case there is something we are missing?

**Comment by axcore** [comment]
Closed for inactivity
