### ISSUE TITLE
Why gi -> pgi?

### ISSUE THREAD

**Issue by ryneeverett** [axcore/tartube#242]
I see the dependency was changed from gi to pgi a while back and I'd like to know what that means.

- It appears that gi is the actively maintained pygobject api while pgi is the legacy api. If I'm understanding that correctly does that mean tartube depends on the legacy api?
- Tartube appears to only import gi and never pgi. Am I missing something?

Thanks.

**Comment by axcore** [comment]
My notes say that gi was changed to pgi in v2.1.042-v2.1.044 (July 2020), because installation from pypi failed under Ubuntu and Linux Mint. Using pgi fixed these problems.

The issues were [108](https://github.com/axcore/tartube/issues/241) and [110](https://github.com/axcore/tartube/issues/241).

**Comment by ryneeverett** [comment]
While it would be nice to have a better understanding of this it does seem like tartube works with modern pygobject so this would seem to be a distribution oddity which isn't too concerning.

**Comment by axcore** [comment]
I haven't tested it recently, but presumably whatever was causing the problem will be fixed eventually, and then I can remove pgi and restore gi.

**Comment by axcore** [comment]
v2.3.110 uses pygobject to replace pgi as a dependency. It seems to be working correctly.
