### ISSUE TITLE
why is there no custom path for youtube-dl(c)

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#243]
why the path to the executable: exists only in the `use local path (youtube-dl(c))` `/usr/local/bin` and `~/local/bin` for [5.3.8 Manual installation without Python pip](https://github.com/axcore/tartube#installation)?

**Comment by axcore** [comment]
As far as I know, youtube-dl(c) must be installed. (You can run Tartube source code, without installing it, but you can't do that with youtube-dl(c) ).

**Comment by candrapersada** [comment]
in `/home/user/Download/youtube-dl`
![image](https://user-images.githubusercontent.com/36833664/103746043-09a08100-5033-11eb-969d-6f177a2c0d0a.png)
![image](https://user-images.githubusercontent.com/36833664/103746633-f6da7c00-5033-11eb-9c58-e48ec1ecd9c4.png)

**Comment by axcore** [comment]
How did you install youtube-dl in ` /home/user/Download/youtube-dl` ?

**Comment by candrapersada** [comment]
didn't install me but downloaded from https://github.com/ytdl-org/youtube-dl/releases/download/2021.01.03/youtube-dl without installing

**Comment by axcore** [comment]
I think that, if you want to install youtube-dl(c) in an unusual location, it is better to add it to your system's PATH.

Then you can use **Path to the executable: Use local path** and **Command for update operations: Update using local youtube-dl path**.

**Comment by candrapersada** [comment]
I mean how to use youtube-dl without installing it like ffmpeg for [5.3.10 Run without installing](https://github.com/axcore/tartube#5310-run-without-installing)
![103753121-39548680-503d-11eb-8ef6-5c653342d864](https://user-images.githubusercontent.com/36833664/103925506-3bf0d200-514a-11eb-9d4c-29c78ffc38e6.png)

**Comment by axcore** [comment]
Tartube gives the path to the FFmpeg executable to youtube-dl(c). That is why there is a **Set** button.

youtube-dl(c) must be installed. That is why there is no **Set** button.

**Comment by candrapersada** [comment]
have you tried `python3 Downloads/youtube-dlc https://www.youtube.com/watch?v=CG8CX5mx2mk` or `python3 /home/user/Downloads/youtube-dlc https://www.youtube.com/watch?v=CG8CX5mx2mk` without installing youtube-dl(c) to system and python3-pip?
![Screenshot from 2021-01-10 23-31-58](https://user-images.githubusercontent.com/36833664/104138919-38737a00-53da-11eb-8d8e-4a2b3867e97b.png)

**Comment by axcore** [comment]
Yes, it doesn't work.

![nowork](https://user-images.githubusercontent.com/37951926/104361810-debe9d00-550a-11eb-9572-e8ba8697df6a.png)

**Comment by candrapersada** [comment]
have you put the [youtube-dic](https://github.com/blackjack4494/yt-dlc/releases/download/2020.11.11-3/youtube-dlc) file to `/home/ra/local/Downloads/Direct/yt-dlc/youtube-dlc`?

**Comment by axcore** [comment]
That file does not exist.

**Comment by candrapersada** [comment]
please try again and add youtube-dic to `/home/ra/Local/Downloads/Direct/yt-dlc/`, like this picture.
![image](https://user-images.githubusercontent.com/36833664/104419825-9acfa480-55ab-11eb-8d04-dd9630389913.png)
![image](https://user-images.githubusercontent.com/36833664/104419844-a4f1a300-55ab-11eb-9eb7-303c49056a24.png)

**Comment by axcore** [comment]
I checked again, the file does not exist
![noexist](https://user-images.githubusercontent.com/37951926/104424523-68a44f80-5577-11eb-93f2-368d9040be17.png)

**Comment by candrapersada** [comment]
then try this
[youtube-dlc.zip](https://github.com/axcore/tartube/files/5807325/youtube-dlc.zip)

**Comment by axcore** [comment]
Where does this file come from?

**Comment by candrapersada** [comment]
From [Releases · blackjack4494_yt-dlc](https://github.com/blackjack4494/yt-dlc/releases/tag/2020.11.11-3
![youtube-dlc](https://user-images.githubusercontent.com/36833664/104443148-9ebdef80-55c8-11eb-819a-808889057fe6.PNG)
)

**Comment by axcore** [comment]
Ok, in that case, I can add a custom path for youtube-dl(c).

**Comment by axcore** [comment]
Added in v2.3.085.

**Comment by candrapersada** [comment]
add a custom path for `settings.json` [#210](https://github.com/axcore/tartube/issues/210#issuecomment-739289070https://github.com/axcore/tartube/issues/210#issuecomment-739289070) and features for downloading youtube-dl(c) for custom path

**Comment by axcore** [comment]
>add a custom path for settings.json

It is impossible. See [#210](https://github.com/axcore/tartube/issues/210#issuecomment-739138728).

>and features for downloading youtube-dl(c) without python3-pip
Why?

**Comment by candrapersada** [comment]
in order to update the youtube-dl(c) without opening the browser or python3-pip by downloading directly from https://yt-dl.org/downloads/latest/youtube-dl

**Comment by axcore** [comment]
>in order to update the youtube-dl(c) without opening the browser or python3-pip

You can already update youtube-dl(c) without opening the browser, and without python3-pip.

![updatetest](https://user-images.githubusercontent.com/37951926/104560608-06625200-563e-11eb-81d0-aaef830b6c9d.png)

>and why is there python3 /home/user/Downloads/youtube-dlcc for youtube-dlc?

I used the command that you used [in this post](https://github.com/axcore/tartube/issues/243#issuecomment-759262370).

**Comment by candrapersada** [comment]
> You can already update youtube-dl(c) without opening the browser, and without python3-pip.

without install python3-pip

> I used the command that you suggested in this post.

![image](https://user-images.githubusercontent.com/36833664/104567006-e4d68a00-5680-11eb-96df-1a2dec4f3f51.png)
![image](https://user-images.githubusercontent.com/36833664/104567184-15b6bf00-5681-11eb-8758-2a52e28823a3.png)
![image](https://user-images.githubusercontent.com/36833664/104567347-439c0380-5681-11eb-8803-34deb11f2814.png)

**Comment by axcore** [comment]
Ok thanks, I have uploaded the fix to github.

**Comment by candrapersada** [comment]
> You can already update youtube-dl(c) without opening the browser, and without python3-pip.

without install python3-pip
![image](https://user-images.githubusercontent.com/36833664/104648204-b9689500-56aa-11eb-9f0e-084f8ef495e0.png)

**Comment by axcore** [comment]
You can select "Update using default youtube-dl path', "Update using local youtube-dl path', "Update using custom youtube-dl path'.

**Comment by candrapersada** [comment]
what I mean is if there is no youtube-dl in  "default youtube-dl path', "local youtube-dl path' can't update
![aaaa](https://user-images.githubusercontent.com/36833664/104697641-a73a3580-5742-11eb-8022-c6d158923018.PNG)

**Comment by axcore** [comment]
Yes, that's right. It is the user's responsibility to install software, not Tartube's responsibility.

**Comment by candrapersada** [comment]
https://github.com/pukkandan/yt-dlp/releases

**Comment by candrapersada** [comment]
if possible, move youtube-dl(c) custom path from File paths to Forks?
![Capture3](https://user-images.githubusercontent.com/36833664/105529255-b3ad2800-5d18-11eb-8fa9-f8e36567f9c6.png)

**Comment by axcore** [comment]
I would like to do that, but there isn't enough space in the **Forks** tab.

**Comment by candrapersada** [comment]
> I would like to do that, but there isn't enough space in the Forks tab.


is it possible to use this?
![105529255-b3ad2800-5d18-11eb-8fa9-f8e36567f9c6](https://user-images.githubusercontent.com/36833664/105700363-59d87800-5f3b-11eb-8f25-2402ec5aa329.png)

**Comment by axcore** [comment]
If I move something from **File paths**, then I have to move everything. There is not enough space in **Forks** to move everything.
