### ISSUE TITLE
[Errno 2] No translation file found for domain: 'base'

### ISSUE THREAD

**Issue by Kamilake** [axcore/tartube#247]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Debian based Raspberry Pi OS (Buster) on Rpi 4(8GB/armhf)

### What version of Tartube are you using?
I can't do that for sure. But at the time of writing it is the latest version.

### What happens when you run Tartube from a terminal window?
Many error messages are only visible in the terminal window. On MS Windows, this is how to do it:

> pi@raspberrypi:~ $ tartube 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 2435, in do_activate
>     self.start()
>   File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 2600, in start
>     new_config_flag = self.load_config()
>   File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 3297, in load_config
>     languages=[self.custom_locale],
>   File "/usr/lib/python3.7/gettext.py", line 539, in translation
>     'No translation file found for domain', domain)
> FileNotFoundError: [Errno 2] No translation file found for domain: 'base'

###If your bug report is "I can't download this video", please provide a link to the video
This will save a lot of time!

Tartube only works fine the first time I install it, and it breaks the second time I run it.
I apologize for the poor writing.
I will give you all the information you need to solve the problem.

**Comment by axcore** [comment]
I have a fix for this. There will be a new release in a day or two.

**Comment by axcore** [comment]
Should be fixed in v2.3.085.

**Comment by Kamilake** [comment]
I have updated the package v2.3.085. and it works very fine! (No need to erase or reset configuration) Thank you
