### ISSUE TITLE
Video download "finishes" almost immediately but no video is there

### ISSUE THREAD

**Issue by onesteelcoder** [axcore/tartube#249]
Log: https://pastebin.com/UAHnP70u

Can provide more info if needed.

**Comment by axcore** [comment]
I uploaded the fix to Github. It's a one-line change to the [tartube/info.py](https://github.com/axcore/tartube/blob/master/tartube/info.py) file.

I think it only affects youtube-dl tests (e.g. right-click a video, and select **Downloads > Test system command**). Ordinary downloads should not have been affected.
