### ISSUE TITLE
Downloading each URL to different directories?

### ISSUE THREAD

**Issue by stillpointx** [axcore/tartube#252]
Is it possible to download each URL to a separate directory like youtube-DLG did?

It says it stores all downloads in one place
![screenshot-2021-01-23-04-41-29](https://user-images.githubusercontent.com/28985314/105574867-49ef4700-5d35-11eb-9a32-4dc65e81362f.png)

**Is it possible to download each URL to a separate directory like youtube-DLG did?**

![jr7qwOW](https://user-images.githubusercontent.com/28985314/105574697-3d1e2380-5d34-11eb-9a43-5966cd169a79.png)

**Comment by axcore** [comment]
Do you want to store three channels in three folders? Tartube already does that, the channels are downloaded to `../tartube-data/pewdiepie`, `../tartube-data/T-Series`, `../tartube-data/MrBeast` and so on.

Do you want to store three channels on three different hard drives? Tartube can only load one database at a time, but you can create three different databases, one on each hard drive. And you can run three copies of Tartube simultaneously. Click **Files > Database preferences...**

Have you clicked the **Classic Mode** tab? It behaves exactly like youtube-dl-gui.

![classicmode](https://user-images.githubusercontent.com/37951926/105671517-c3746a00-5eda-11eb-8de2-087de1920c59.png)

**Comment by stillpointx** [comment]
Thanks!
