### ISSUE TITLE
How to uninstall if tartube is installed from source?

### ISSUE THREAD

**Issue by TrinhMinhVu** [axcore/tartube#253]
It seems like my attempt at installing from source failed, how do I remove everything?

**Comment by axcore** [comment]
What operating system are you using? What installation method are you using? 

If you are using MS Windows, and [this installation method](https://github.com/axcore/tartube#511-manual-installation---ms-windows), then you can just delete the folder C:\msys64\home\YOURNAME\tartube and then you're finished.

**Comment by TrinhMinhVu** [comment]
I am using Linux and the installation method is to download the source and run `python3 setup.py install` as directed.

**Comment by axcore** [comment]
According to google, [this](https://stackoverflow.com/questions/1550226/python-setup-py-uninstall/25209129#25209129) is the correct method.

`python setup.py install --record files.tx
xargs rm -rf < files.txt`

**Comment by TrinhMinhVu** [comment]
Seems to do the trick. Thank you I will remember this method for the future.
