### ISSUE TITLE
Download live stream

### ISSUE THREAD

**Issue by mbnoimi** [axcore/tartube#257]
Tartube downloads livestreams while I don't want it! How can I prevent downloading livestreams?

My current configs
![image](https://user-images.githubusercontent.com/284547/107676739-89f97800-6caa-11eb-8d62-ae4a1d1e82c9.png)

**Comment by axcore** [comment]
Can you describe the circumstances, in which Tartube downloads livestreams?

Specifically: when Tartube downloads the livestream, what do you see in the **Output** tab? Do you see output from youtube-dl, or do you see output from [youtube_stream_capture](https://github.com/mrwnwttk/youtube_stream_capture)?

**Comment by mbnoimi** [comment]
> Can you describe the circumstances, in which Tartube downloads livestreams?

Tartube downloads all the available livestreams. But I captured this livestream particularly today:
**Tartube channel source is:** `https://www.youtube.com/user/aljazeeradoc/videos`


>  what do you see in the Output tab?

![image](https://user-images.githubusercontent.com/284547/108095652-26e45880-7091-11eb-9bf7-61621d3c7d0f.png)

![image](https://user-images.githubusercontent.com/284547/108095982-83477800-7091-11eb-8949-00c1c7355bbf.png)

**Comment by axcore** [comment]
Are you sure that the livestream is still broadcasting? When a livestream finishes, it behaves like an ordinary video, and youtube-dl will download it.

(I apologise for an obvious question, but it is necessary to check all possibilities.)

**Comment by mbnoimi** [comment]
> When a livestream finishes, it behaves like an ordinary video, and youtube-dl will download it.

It's broadcasting 24/7

**Comment by axcore** [comment]
Can you give me the URL of the livestream? I can't find it in the video list for `https://www.youtube.com/user/aljazeeradoc/videos`, probably because there are a billion videos there.

**Comment by mbnoimi** [comment]
![image](https://user-images.githubusercontent.com/284547/108303649-57261700-71b7-11eb-9cf4-6b702c241508.png)
https://www.youtube.com/watch?v=lRjOKEF_Ynw

**Comment by axcore** [comment]
It must be region-blocked, I don't see a livestream there. Never mind, I will try a local channel.

![aljaz](https://user-images.githubusercontent.com/37951926/108333411-d2dc8f80-71c8-11eb-9c79-67342e68f625.png)

**Comment by axcore** [comment]
I have investigated this problem.

The livestream settings (you have deselected them) are used only to detect livestreams (in other words, to decide when a video is a livestream or not). They don't affect youtube-dl's behaviour.

I can't find a way to stop youtube-dl from downloading a livestream. (Normally it does not download livestreams, that are still broadcasting). Perhaps the youtube-dl people will have some better ideas.

**Comment by axcore** [comment]
In yt-dlp, you can prevent livestreams from being downloaded with this option:

`--match-filters !is_live`

You can add that to the **Additional download options** box in **Edit > General downloads options... > Name**.
