### ISSUE TITLE
ffprobe/avprobe and ffmpeg/avconf not found.

### ISSUE THREAD

**Issue by ZonK256** [axcore/tartube#26]
Tartube seems not to find ffmpeg on my computer (hopefully I installed it correctly). Using Windows 7 64 bit and manual installation. 
![obraz](https://user-images.githubusercontent.com/25548445/63525864-b2157a00-c4fe-11e9-8295-9699e68bf82d.png)

**Comment by axcore** [comment]
I don't know yet, how to install ffmpeg so Tartube can find it.

**Comment by axcore** [comment]
@ZonK256 can you please try this:

1. From the Tartube main window, click **Edit > General download options... > General**
2. In the **Extra youtube-dl command line options** box, enter this:

**--ffmpeg-location C:\ffmpeg\bin**

3. Use Tartube to download any video

Does Tartube now find ffmpeg?

**Comment by ZonK256** [comment]
Yup, now converts videos correctly, thanks

**Comment by axcore** [comment]
Great!  I will release v1.2 this weekend. I will add something to the window, so you can set that without knowing how to use `--ffmpeg-location`.
