### ISSUE TITLE
[Question on usage] Can't find how to enable GPU encoding/decoding for post-processing with FFmpeg

### ISSUE THREAD

**Issue by oshura3** [axcore/tartube#264]
Hello there!

Great piece of programming here! I think it's fantastic and it definitely helps to make my life a lot easier. One thing that I was trying to figure out but cannot find documentation for is how to enable hardware encoding/decoding on the FFmpeg options. I do see that it is currently using the flag ```-c:v libx264``` and from searching online, it looks like I could possibly use the flags `-hwaccel auto -c:v h264_amf` to use my computer's AMD GPU in the encoding/post-processing portion of the process. Am I way off base here? Did I just miss a setting somewhere that allows me to enable GPU encoding/decoding? Is there a way that I could manually set all of the flags?

I really hope that this question makes sense; if not, I would be glad to come back here and clarify.

Thank you for all the hard work you have done @axcore!

**Comment by axcore** [comment]
Many apologies; I know almost nothing FFmpeg. I didn't design the FFmpeg interface used in Tartube, I copied it from somewhere else

**Comment by oshura3** [comment]
No worries at all! The fact that FFmpeg is a part of it is awesome to begin with. Do you think that you would be able edit the software to incorporate GPU encoding? If there was an option to change the '-c:v libx264' to '-c:v h264_amf' in the advanced options, as well as the option to add '-hwaccel auto', the whole process would progress much faster. This is just a suggestion for possible future improvements but even if it's not added, the program is pretty awesome.

**Comment by axcore** [comment]
Where do you think the options to change to `-c:v h264_amf` and to add `-hwaccel auto` should be placed in the FFmpeg window? 

For example: I could add an option to switch between `-c:v libx264` and `-c:v h264_amf` at the bottom of the **Settings** tab, and a button to enable `-hwaccel auto` could be placed in the **Optimisations** tab. What do you think?

>or the Nvidia alternative as appropriate of course lol

I don't know what the Nvidia alternative is, if you can specify which `c:v` options should exist, then I can add them.

**Comment by oshura3** [comment]
After looking through the app some, I think it would be a fine choice to have the option to switch between the different `-c:v` types under the settings tap of the FFmpeg options at the bottom with a "Experimental: use at your own risk" warning/caveat listed just in case it doesn't work for some people. I think the `-hwaccel auto` option placed in the settings tab as well should work since the options go hand in hand.

As far as the nvidia options, I am far from an expert on the topic so I'm not 100% sure on which options they should be. Based on some intel I gathered on these various sites ([the main manual page for FFmpeg HWaccel stuff](https://trac.ffmpeg.org/wiki/HWAccelIntro), [the nvidia developers page on hwaccel with their hardware](https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/), and/or [nvidia FFmpeg transcoding guide](https://developer.nvidia.com/blog/nvidia-ffmpeg-transcoding-guide/) it looks like the command could be a few different things and I wouldn't want to steer anyone in the wrong direction. 

I'm still fairly new with using all these FFmpeg options but if I can help any more, trying to get it to work, please let me know. I would love to help troubleshoot the nvidia options but I only have an AMD GPU unfortunately. That said, if you want some help beta-testing the options using an AMD card, I'm your guy. Just let me know!

**Comment by axcore** [comment]
This will be in the next release

![ffmpeg options](https://user-images.githubusercontent.com/37951926/109413668-7c303c00-79a6-11eb-9f26-ab42249d35f9.png)

**Comment by axcore** [comment]
All added in v2.3.110.

**Comment by oshura3** [comment]
This should be great! I'm looking forward to see how it improves things. I would make a suggestion. Do you think that maybe it would be good to add a little "I" information bubble thing next to the HWaccel option that states to turn on the auto option if people going to use the GPU encoding/decoding? Again, I wish I had more expertise with this whole program so I could provide better advice. Hope it helps.

**Comment by axcore** [comment]
I have to assume that anyone who uses these options already knows what they are doing, because I certainly don't :)

**Comment by oshura3** [comment]
lol. That's fair enough. 

sidebar: I just updated to the latest release on Windows and when trying to install/update yt-dlp I'm encountering an error and the update is failing. How would you like me to upload the error logs so we can try to debug what's happening? Open a new issue? Copy the entire error log or just bits of it? I'm still sort of new when it comes to using github

**Comment by axcore** [comment]
I can swap the positions of `GPU encoding` and `Hardware acceleration`.

Or, I can automatically change `Hardware acceleration` to `auto`, when the user changes the value of `GPU encoding`.

But I think I can't do both. That would look weird.

**Comment by oshura3** [comment]
If swapping the positions of `GPU encoding` and `Hardware acceleration` would place the `hwaccel auto` flag before the `-c:v XXX` flag, that that would be good. Also, having hardware acceleration change to auto when the user changes the value of GPU encoding, I think would be great. Honestly, whatever works best for you as a programmer as I'm not a programmer and wouldn't know where to begin or what would work.
