### ISSUE TITLE
For me Tartube is only downloading the first 1 minute of each video. Any ideas why this is happening?

### ISSUE THREAD

**Issue by elmobotix** [axcore/tartube#266]
Thanks for taking the time to ask a question! 

### Please read the README
Perhaps your question is answered there

### The authors are not experts in python, security, youtube-dl, FFmpeg, Debian/RPM packaging or Windows programming
You are welcome to ask a Tartube-related question, but you might get a better answer in forums where those kinds of expert can be found

**Comment by elmobotix** [comment]
Edit: I needed to add my credentails!

**Comment by axcore** [comment]
Try to download a single video

Then click the **Output** tab, and take a screenshot, or copy-and-paste the text, so I can see the youtube-dl command (in yellow).

**Comment by elmobotix** [comment]
Hi

Sorry I fixed it! It wasn’t authenticating my account.

**Comment by axcore** [comment]
Ah, ok :)
