### ISSUE TITLE
files wont merge

### ISSUE THREAD

**Issue by alidan** [axcore/tartube#267]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
win 7 

### What version of Tartube are you using?
2.3.085

### What happens when you run Tartube from a terminal window?
Many error messages are only visible in the terminal window. On MS Windows, this is how to do it:

- First, enable hidden folders on your system
- Then, run the application: 

    C:\Users\YOURNAME\AppData\Local\Tartube\msys64\mingw64.exe

- In this new window, type these commands to start Tartube:

    cd /home/user/tartube

    python3 tartube/tartube

###If your bug report is "I can't download this video", please provide a link to the video
videos download
audio downloads
files wont merge
I cant get ffmpeg to install or work (its possible its there and works, but I wont install)

![python3_2021-02-23_15-03-57](https://user-images.githubusercontent.com/2681758/108907943-5db5f380-75e8-11eb-8bab-07980c8cf3d9.png)
![explorer_2021-02-23_15-04-16](https://user-images.githubusercontent.com/2681758/108907981-6d353c80-75e8-11eb-9602-cfe969c9fdcf.png)

im not sure if its related or not, not sure when this started happening either, I killed the process download when I saw they were not merging,

**Comment by axcore** [comment]
Someone else who reported a similar problem resolved it by completely uninstalling Tartube, then reinstalling it, so you should try that.

Tartube can be uninstalled from the Windows Start menu.

Before re-installing, make sure that the entire installation folder has been deleted. That folder is probably **C:\Users\YOURNAME\AppData\Local\Tartube**. You will probably need to enable hidden folders on your system first.

**Comment by alidan** [comment]
reinstalling fixed it and seemingly got ffmpg to work and also got the files to merge. the other issue where I had ffmpg would not install also got fixed by this. sorry bout not responding to the other one sooner, irl crap put a few things on the backburner at the time.

**Comment by axcore** [comment]
Great, enjoy it!
