### ISSUE TITLE
Cannot change downloader from youtube-dlc to yt-dlp when upgrading from 2.3.085 to 2.3.110 (apologies for the wall of text)

### ISSUE THREAD

**Issue by oshura3** [axcore/tartube#269]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Windows 10

### What version of Tartube are you using?
2.3.110 was the one giving me issues

### What happens when you run Tartube from a terminal window?
When I run the commands usually listed here while using 2.3.085, the program starts right up.  I get the following error (which is not the reason I was opening this bug report in the first place, but may it's related)
`C:/Users/USERNAME/AppData/Local/Tartube/msys64/mingw64/bin/python3.exe: error while loading shared libraries: libpython3.8.dll: cannot open shared object file: No such file or directory`

I updated from version 2.3.085 to 2.3.110 today and while trying to update to the new "yt-dlp" I kept getting the errors listed below. I tried going back to youtube-dl with no luck so I ended up downgrading from 2.3.110 to 2.3.085 to see if I could get everything working like it was before, the results of that will be listed below these results. Again, my apologies for the really long wall of text; if there's a better way to post the logs, please let me know and I will edit this bug report accordingly.

**wall of text redacted**

At this point, I figured I should just go back and leave youtube-dlc as my downloader of choice for now and see if that will still work when upgrading to 2.3.110. When I tried downloading the same exact video I downloaded using 2.3.085, the video download would not work. I tried switching to yt-dlp as the main downloader but got this error:

```
Starting update operation, installing/updating yt-dlp
..\..\..\mingw64\bin\python3.exe ..\..\..\mingw64\bin\pip3-script.py install --upgrade yt-dlp
Child process exited with non-zero code: 3221225781
Update operation finished
```

I closed the application to see if a simple shutdown and restart would help it to work but it would not restart after that. I ended up uninstalling this version and will be going to the 2.3.085 for now until we can figure something out.

**Comment by axcore** [comment]
Confirmed, [pycryptodome](https://pypi.org/project/pycryptodome/) cannot be installed on MSYS2, therefore yt-dlp cannot be installed either.

youtube-dlc is not working any more (on all platforms), therefore you'll have to use youtube-dl.

**Comment by axcore** [comment]
I removed the wall of text so I can pin this issue, and so that other people can see my response.

**Comment by Collin8000** [comment]
I am using tartube v2.3.008, i got the sourcecode from sourceforge and used this site https://tartube.sourceforge.io/ . I followed the steps and installed everything in MINGW64 I installed ffmpeg put it in my path and then installed yt-dlp using pip which installed pycryptodome and it build it with wheel. DO not update it using the tartube yt-dlp update method it just gave me this error: .\..\..\mingw64\bin\python3.exe ..\..\..\mingw64\bin\pip3-script.py install --upgrade yt-dlp Update did not start update finished update error. I pressed next and it did the same thing with ffmpeg it used the .py script i pressed next and it worked. I dont know if it will work for 2.3.110.

**Comment by axcore** [comment]
The work around for this problem is install yt-dlp without its dependencies. Open the following application:

`C:\Users\YOURNAME\AppData\Local\Tartube\msys64\mingw64.exe`

Then install yt-dlp:

`pip3 install --upgrade --no-dependencies yt-dlp`

Repeat this procedure every time you want to update yt-dlp, or until the next Tartube release comes out.

**Comment by axcore** [comment]
In v2.3.185, I added an option to install yt-dlp without dependencies. It is enabled by default on MS Windows. This should fix the problem.

The main installer has not been updated yet, but you can download the source code from github, and then copy it over the old source code, which is usually installed in 

`C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube\`

**Comment by axcore** [comment]
Installation of yt-dlp should work on MS Windows, using Tartube v2.3.306.
