### ISSUE TITLE
Add another Storage bank as a depository

### ISSUE THREAD

**Issue by Anticancer123** [axcore/tartube#272]
Hi,I have 2 storage bank how do I use divide tartube into the two depostories.Do I have to have to install another copy of the program?

**Comment by axcore** [comment]
You only need to install Tartube once. You can add as many databases as you want. 

- Create an empty folder (directory) anywhere on your computer (or on a hard drive), for example, call it `my_other_database`
- Click **File > Database preferences...**
- Click the **Add new database button**
- Select the empty folder you just created
- Tartube asks for confirmation, so click **Yes**
- The folder appears in the list

When you start Tartube, it tries to load the first database in the list. If you have two copies of Tartube running, the first one will load the first database, the second one will load the second database. (It all happens automatically.)

**Comment by candrapersada** [comment]
does it work also with MS Windows?

**Comment by axcore** [comment]
Yes

**Comment by Anticancer123** [comment]
Failed to load

**Comment by axcore** [comment]
What failed to load? In what circumstances?

**Comment by candrapersada** [comment]
is there a way to select tartube for example tartube-data A or tartube-data B when tartube starts?

**Comment by axcore** [comment]
>is there a way to choose a tartube-data storage bank for example tartube-data A or my_other_database B when tartube starts?

Yes, in **File > Database preferences...**, you can add as many database as you like. Tartube loads the first database in the list, that isn't already loaded.

**Comment by axcore** [comment]
Closed for inactivity.
