### ISSUE TITLE
When downloading won't update Speed - ETA - Size

### ISSUE THREAD

**Issue by wes1993** [axcore/tartube#273]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Windows 10

### What version of Tartube are you using?
2.3.110

When i'm downloading a video no update in the table, below one screenshot

![image](https://user-images.githubusercontent.com/52070589/109736233-55e7e780-7bc4-11eb-98b2-6c220a682272.png

I hope you could solve this bug
Best Regards
Stefano

**Comment by axcore** [comment]
Can you tell me the video you are trying to download?

**Comment by wes1993** [comment]
Yes, it's an M3U8 link from here:
https://dplaysouth-vod.akamaized.net/dplaydni/88030/0/hls/8826993004/playlist.m3u8?hdnts=st=1614761726~exp=1614848126~acl=/dplaydni/88030/0/hls/8826993004/*~hmac=e1eca9c9f765ff831c920e60f745676790fc260cb2608abc3c3e748e6f5712c7

I have also another problem with the installer that i have found today,
After i have rebooted my pc the program won't start anymore, now i'm using the portable version.

Best Regards
Stefano

**Comment by axcore** [comment]
>Yes, it's an M3U8 link from here:

Tartube does not support m3u8 links at the moment. The download might work, but it might not.

>After i have rebooted my pc the program won't start anymore, now i'm using the portable version.

The normal and portable versions are exactly the same, except the portable version doesn't add anything to the Windows Start Menu. You could try uninstalling Tartube (from the Windows Start Menu), then reinstalling it.

**Comment by wes1993** [comment]
Thanks a lot for your reply :)
I love this program and your work!! I hope you could add support for m3u8 also :)
Best regards
Stefano
