### ISSUE TITLE
The program doesn't work. A few questions

### ISSUE THREAD

**Issue by AlexLev59** [axcore/tartube#274]
My program does not work at all.

1. She can't even update youtube-dl, error:

Starting update operation, installing/updating youtube-dl
..\..\..\mingw64\bin\python3.exe ..\..\..\mingw64\bin\pip3-script.py install --upgrade youtube-dl
Could not fetch URL https://pypi.org/simple/youtube-dl/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/youtube-dl/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)'))) - skipping
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)'))) - skipping
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)'))': /simple/youtube-dl/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)'))': /simple/youtube-dl/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)'))': /simple/youtube-dl/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)'))': /simple/youtube-dl/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)'))': /simple/youtube-dl/
ERROR: Could not find a version that satisfies the requirement youtube-dl
ERROR: No matching distribution found for youtube-dl
Child process exited with non-zero code: 1
Update operation finished

2. I am not sure that the program is designed to install its own database on the path with spaces, such as "d:\- Downloads\Tartube\".

3. Looked at the contents of the file setup_vars_opencv4.cmd
In it, as I understand it, quotation marks are not used correctly when setting different variables, such as:
SET "PYTHONPATH_OPENCV=%SCRIPT_DIR%\lib".

**Comment by axcore** [comment]
>She can't even update youtube-dl, error:

That is a network error: something is broken between your computer and the python server. The only solution is to wait until the network repaired. 

The download is working fine here. If you think it's a software problem, not a network error, you could try using [Tartube v2.3.085](https://sourceforge.net/projects/tartube/files/v2.3.085/) (which uses different network software).

![networkerror](https://user-images.githubusercontent.com/37951926/109781270-ad577900-7bff-11eb-903d-584a7a685f76.png)

>I am not sure that the program is designed to install its own database on the path with spaces, 

Ok, I will investigate that

>Looked at the contents of the file setup_vars_opencv4.cmd

Where did you find this file? It is not a Tartube file.

**Comment by AlexLev59** [comment]
d:\Portable\Tartube\mingw64\setup_vars_opencv4.cmd

d:\Portable\Tartube\mingw64\bin\python.exe
d:\Portable\Tartube\mingw64\bin\python3.exe
d:\Portable\Tartube\mingw64\bin\python3.8.exe

**Comment by AlexLev59** [comment]
I tried to install turtube-portable-64 bit 2.3.085.zip
And already in the "Install and update downloader" mode, it displays errors.
Although actually 142 files have already been installed and updated.

Access to
https://pypi.org/simple/youtube-dl/
https://pypi.org/simple/pip/
available in the browser.

Starting update operation, installing/updating youtube-dl
..\..\..\mingw64\bin\python3.exe ..\..\..\mingw64\bin\pip3-script.py install
--upgrade youtube-dl
Could not fetch URL https://pypi.org/simple/youtube-dl/: There was a problem
confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443):
Max retries exceeded with url: /simple/youtube-dl/ (Caused by
SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed: self signed certificate in certificate chain
(_ssl.c:1108)'))) - skipping
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming
the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries
exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1,
'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed
certificate in certificate chain (_ssl.c:1108)'))) - skipping
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None,
status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1,
'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed
certificate in certificate chain (_ssl.c:1108)'))': /simple/youtube-dl/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None,
status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1,
'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed
certificate in certificate chain (_ssl.c:1108)'))': /simple/youtube-dl/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None,
status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1,
'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed
certificate in certificate chain (_ssl.c:1108)'))': /simple/youtube-dl/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None,
status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1,
'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed
certificate in certificate chain (_ssl.c:1108)'))': /simple/youtube-dl/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None,
status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1,
'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed
certificate in certificate chain (_ssl.c:1108)'))': /simple/youtube-dl/
ERROR: Could not find a version that satisfies the requirement youtube-dl (from
versions: none)
ERROR: No matching distribution found for youtube-dl
Child process exited with non-zero code: 1
Update operation finished
Update operation failed

**Comment by axcore** [comment]
`setup_vars_opencv4.cmd` is installed by [OpenCV](https://opencv.org/), which is a dependency of FFmpeg.

**Comment by axcore** [comment]
Closed for inactivity. Tartube and FFmpeg have been updated many times since this issue was opened. If you are still having the same problem with the updated code, please open a new issue.
