### ISSUE TITLE
Trying to Install tartube

### ISSUE THREAD

**Issue by rx570gtx1060** [axcore/tartube#275]
I downloaded the rpm package from sourceforge to Install the latest version of tartube.Nevertheless, there is a dependency problem as it requires Python(abi)3.8 and openSUSE Leap only has Python up to version 3.6.

When I was about to install it this came up
> Problem: nothing provides python(abi) = 3.8 needed by tartube-2.3.110-1.noarch
>> Solution 1: do not install tartube-2.3.110-1.noarch
       Solution 2: break tartube-2.3.110-1.noarch by ignoring some of its dependencies

I went along with the install and I was able to install it.However i typed tartube into the terminal to see what the potential problem could be with the GUI but all I got as the error was this:

> Traceback (most recent call last):
  File "/usr/bin/tartube", line 40, in <module>
    import mainapp
ModuleNotFoundError: No module named 'mainapp'

Operating System and tartube Specifications:
> OS:openSUSE Leap 15.2
Tartube version:2.3.110

**Comment by axcore** [comment]
If the RPM doesn't work, you can install using [PyPI](https://github.com/axcore/tartube#535-install-using-pypi), [install from source](https://github.com/axcore/tartube#539-install-from-source), or just download the source code and [run it directly](https://github.com/axcore/tartube#5310-run-without-installing); installation is not actually necessary.

**Comment by rx570gtx1060** [comment]
Ok,thanks for the answer.
