### ISSUE TITLE
Download finishes immediately, doesn't download anything

### ISSUE THREAD

**Issue by IntendedPun** [axcore/tartube#277]
System: Windows 10

Version: v2.3.110

When trying to download through the main app, the status under the progress tab goes from "waiting" to "finished" a couple of seconds after starting, with a pop-up box saying "download operation complete". Nothing is actually downloaded. Downloading through classic mode works, though.

Here's an excerpt from the console during that time:

2021-03-11 21:58:04 app 16210 script_fast_timer_callback
2021-03-11 21:58:04 app 16210 script_fast_timer_callback
2021-03-11 21:58:04 app 16210 script_fast_timer_callback
2021-03-11 21:58:04 app 16210 script_fast_timer_callback
2021-03-11 21:58:05 app 16210 script_fast_timer_callback
2021-03-11 21:58:05 app 7803 download_manager_start
2021-03-11 21:58:05 app 7939 download_manager_continue
2021-03-11 21:58:05 app 7710 get_proxy
2021-03-11 21:58:05 app 16210 script_fast_timer_callback
2021-03-11 21:58:05 app 7631 check_downloader
2021-03-11 21:58:05 app 16210 script_fast_timer_callback
2021-03-11 21:58:05 app 16258 dl_timer_callback
2021-03-11 21:58:05 app 16210 script_fast_timer_callback
2021-03-11 21:58:06 app 16210 script_fast_timer_callback
2021-03-11 21:58:06 app 16258 dl_timer_callback
2021-03-11 21:58:06 app 16210 script_fast_timer_callback
2021-03-11 21:58:06 app 16210 script_fast_timer_callback
2021-03-11 21:58:06 app 16258 dl_timer_callback
2021-03-11 21:58:06 app 16210 script_fast_timer_callback
2021-03-11 21:58:07 app 16210 script_fast_timer_callback
2021-03-11 21:58:07 app 16258 dl_timer_callback
2021-03-11 21:58:07 app 16210 script_fast_timer_callback
2021-03-11 21:58:07 app 8092 download_manager_halt_timer
2021-03-11 21:58:07 app 16210 script_fast_timer_callback
2021-03-11 21:58:08 app 16258 dl_timer_callback
2021-03-11 21:58:08 app 8109 download_manager_finished
2021-03-11 21:58:08 app 4066 save_config
2021-03-11 21:58:08 app 4456 get_config_path
2021-03-11 21:58:08 app 5615 save_db
2021-03-11 21:58:08 app 10480 reset_backup_archive
2021-03-11 21:58:08 app 16210 script_fast_timer_callback
2021-03-11 21:58:08 app 16210 script_fast_timer_callback
2021-03-11 21:58:08 app 16210 script_fast_timer_callback
2021-03-11 21:58:09 app 16210 script_fast_timer_callback
2021-03-11 21:58:09 app 16210 script_fast_timer_callback
2021-03-11 21:58:09 app 16210 script_fast_timer_callback
2021-03-11 21:58:09 app 16210 script_fast_timer_callback

The console started spamming "script_fast_timer_callback" as soon as I enabled debug error logs.

**Comment by axcore** [comment]
Try downloading a video (not in Classic Mode). When it fails, click the **Output** tab and show me the output (including the yellow text at the top).

>The console started spamming "script_fast_timer_callback" as soon as I enabled debug error logs.
It's supposed to do that. You can remove those lines from the error log by selecting the option in **Edit > General preferences... > General > Debugging**

**Comment by IntendedPun** [comment]
youtube-dl --newline -i --hls-prefer-native -o D:/Tartube/Vinesauce/%(title)s.%(ext)s --write-description --write-info-json --write-annotations --cookies D:/Tartube/cookies.txt --write-thumbnail --dump-json --download-archive D:/Tartube/Vinesauce/ytdl-archive.txt https://www.youtube.com/watch?v=k0lO0ADkYf4
[Vinesauce] <Simulated download of: '[Vinesauce] Vinny - Zelda CDi ~ Wand of Gamelon Remastered'>

I take it "simulated download" is the issue?

**Comment by axcore** [comment]
There are two modes - checking videos, and downloading videos. Checking a video fetches information about it (downloads the thumbnail and metadata), but not the video itself. 

In the text you just copied,  `--dump-json` and `Simulated download` both correspond to checking a video.

Presumably you clicked the button to download videos, not just check them. In that case, the most likely cause is that you've disabled downloads for a particular channel/playlist/folder. Have a look at this:

![nopewdiepie](https://user-images.githubusercontent.com/37951926/110857905-5150bc80-82b1-11eb-9457-7d9e751fd87d.png)

Downloads are disabled in the `pewdiepie` channel. You can tell because it is in italics.

 To re-enable downloads for pewdiepie, right-click the channel and deselect **Downloads > Just disable downloading**

**Comment by IntendedPun** [comment]
Aha! I know why it happened too. When adding a channel it asks whether I want to download videos automatically. I assumed this meant that Tartube begins downloading everything as soon as I click OK (or it downloads everything in the future). My thought process was that, at first, check the videos, then download. I don't get why this option disables downloading, though, the wording seems a bit misleading. Thanks for the help and quick replies tho!

[This prompt here.](https://i.imgur.com/97nI3eC.png)

Offtopic for this thread, but as you can see in picture, the cancel button picks up on my location (my copy of Windows is in English) and uses the Finnish translation "peru". This happens everywhere else in app, too. Thought you might wanna know that.

**Comment by axcore** [comment]
Ah, understandable. Can you think of a better wording?

For the translated button, that window is generated by the Gtk graphics library, not by Tartube itself. I'll mark the issue open so I can look into it.

**Comment by IntendedPun** [comment]
I'm not sure I understand the point of the choice. After adding a channel you have the option to "download all" and "check all" at the bottom of the list anyway. Is it maybe to prevent "download all" from downloading that specific channel? If so, perhaps "disable downloading for this channel" would work, as it matches the wording of [these menu options.](https://i.imgur.com/m7vLPXs.png) Same for checking.

Another offtopic: [This is my format for file names](https://i.imgur.com/ytElCBc.png), but despite date information being available, that part of the file name [comes out as "NA".](https://i.imgur.com/2zr6tsq.png) (Also, "open file location in explorer" for finished and currently downloading files would be a good [quality of life menu option here](https://i.imgur.com/jjSvvPH.png).)

Here's the output of that process:

youtube-dl --newline -i --hls-prefer-native -o D:/Tartube/Vinesauce/%(release_date)s-%(title)s --write-description --write-info-json --write-annotations --cookies D:/Tartube/cookies.txt --write-thumbnail --download-archive D:/Tartube/Vinesauce/ytdl-archive.txt https://www.youtube.com/watch?v=k0lO0ADkYf4
[youtube] k0lO0ADkYf4: Downloading webpage
[info] Writing video description to: D:/Tartube/Vinesauce/NA-[Vinesauce] Vinny - Zelda CDi ~ Wand of Gamelon Remastered.description
[info] Writing video description metadata as JSON to: D:/Tartube/Vinesauce/NA-[Vinesauce] Vinny - Zelda CDi ~ Wand of Gamelon Remastered.info.json
[youtube] k0lO0ADkYf4: Downloading thumbnail ...
[youtube] k0lO0ADkYf4: Writing thumbnail to: D:/Tartube/Vinesauce/NA-[Vinesauce] Vinny - Zelda CDi ~ Wand of Gamelon Remastered.webp
[download] Destination: D:/Tartube/Vinesauce/NA-[Vinesauce] Vinny - Zelda CDi ~ Wand of Gamelon Remastered.f303
[download] 100% of 180.44MiB in 00:15
[download] Destination: D:/Tartube/Vinesauce/NA-[Vinesauce] Vinny - Zelda CDi ~ Wand of Gamelon Remastered.f140
[download] 100% of 10.61MiB in 00:00
[ffmpeg] Merging formats into "D:/Tartube/Vinesauce/NA-[Vinesauce] Vinny - Zelda CDi ~ Wand of Gamelon Remastered.mkv"
Deleting original file D:/Tartube/Vinesauce/NA-[Vinesauce] Vinny - Zelda CDi ~ Wand of Gamelon Remastered.f303 (pass -k to keep)
Deleting original file D:/Tartube/Vinesauce/NA-[Vinesauce] Vinny - Zelda CDi ~ Wand of Gamelon Remastered.f140 (pass -k to keep)
WARNING: There are no annotations to write.
WARNING: Requested formats are incompatible for merge and will be merged into mkv.

**Comment by axcore** [comment]
>Is it maybe to prevent "download all" from downloading that specific channel?

Yes, exactly. No-one has an infinite hard drive, not even me, so in my Tartube database I have some channels set to download. Other channels have downloads disabled, because I don't want permanent copies of the videos, but I might want to watch them on YouTube.

**Comment by axcore** [comment]
For your file format problem, I examined the metadata for [https://www.youtube.com/watch?v=k0lO0ADkYf4](https://www.youtube.com/watch?v=k0lO0ADkYf4), and it doesn't contain a `release_date` field, which is why youtube-dl doesn't provide it. 

YouTube videos nearly always provide `upload_date`, though, so you could use that instead.

**Comment by IntendedPun** [comment]
My bad, I assumed release meant upload. Works fine now, thanks.

**Comment by copeland3300** [comment]
@axcore I would say better wording/implementation in the 'add channel' dialogue would be a check box that says `disable downloads (simulate only)` and perhaps an info button to explain the difference.

**Comment by axcore** [comment]
Enable the "enable automatic copy/paste" feature
Go to your web browser, and copy a link to a video
The video's link magically appears in the Tartube dialogue

It's a simple way of transferring links, instead of typing CTRL + C then CTRL + V again and again, you only have to type CTRL + C.

**Comment by axcore** [comment]
Added in v2.3.549.
