### ISSUE TITLE
Win 64 bit installer issue 2.3.110

### ISSUE THREAD

**Issue by swdw973** [axcore/tartube#278]
Win 10 Pro Build 1901 Version 18363.1440 Tartube version 2.3.110
Have downloaded the 64 bit version of the installer multiple times from sourceforge. When running the installer it fails on extracting a large number of files (more than 30 if you keep hitting ignore). Tried running the installer with admin privileges. Same problem.

Tried the 32 bit version and it extracted and installed with no issues. Downloaded and extracted the portable version to a folder with no issues. Problem is particular to the 64 bit version.

Had other issues with the youtube-dl, yt-dlp and ffmpeg updates in both in the portable and installed versions  I'll post separately.

**Comment by axcore** [comment]
I just tested the 64-bit installer on a clean MS Windows box, and it installed without problems. Not sure what to suggest for your situation, I'm not a Windows programmer so I don't know how to diagnose the issue.

The repository from which youtube-dl, yt-dlp and ffmpeg are downloaded has many a bit unreliable recently, in some cases it might only be necessary to wait a few hours.

**Comment by axcore** [comment]
Closed for inactivity. If you have the same issue with the latest release of Tartube, please open a new issue.
