### ISSUE TITLE
video not downloading (docker)

### ISSUE THREAD

**Issue by dot-mike** [axcore/tartube#280]
Hello,
I'm having issues running this as the videos are not downloading. I enabled some debug logs and they are available here: https://gist.github.com/ColdIce1/d6c8cee3902c41427516220dc31b8faf

My Setup is using a docker container based on Ubuntu (see [linuxserver/docker-baseimage-guacgui](https://github.com/linuxserver/docker-baseimage-guacgui)) - while the GUI works fine, the download functionality don't.

I suspect that missing quotes in the output command is the cause of this, can you provide some help here?

**Comment by axcore** [comment]
Tartube supplies the output command to the system, one argument at a time. Therefore quotes are not necessary and, indeed, youtube-dl will not work if you try to use them. (I have tested this thoroughly in response to previous issues).

Make sure youtube-dl is [updated](https://github.com/axcore/tartube#62-updating-the-downloader). 

Make sure the downloader's location is [set correctly](https://github.com/axcore/tartube#63-setting-the-downloaders-location).

Try downloading a single video, and then show me the contents of the **Output** tab (a screenshot or copy-and-paste).

**Comment by ColdIce1** [comment]
@axcore thank you, it was a path issue for Youtube-DL. Issue resolved.
Maybe implement some verification during initial setup?

**Comment by axcore** [comment]
There is already some code that auto-detects the path for youtube-dl, but sometimes it doesn't work, and I don't know why.

**Comment by 8465231** [comment]
Is the docker working? I am looking for a docker version of tartube and ran across this post.

**Comment by axcore** [comment]
See [this thread](https://forums.unraid.net/topic/111797-request-tartube-gui-docker-container/), someone has apparently found out how to run Tartube under Docker, but there is no download link yet. You can pester them for one :)
