### ISSUE TITLE
Add a date to errors/warnings

### ISSUE THREAD

**Issue by MohamedEssabani** [axcore/tartube#281]
Hey there,

I just wanted to suggest adding a date column to the Errors/Warnings tab, for giving some more information about the errors. Knowing only the time is not enough when I have a scheduled job that runs once every day for example.

**Comment by strunberg** [comment]
seems like a neat idea, may be we could toggle it the options as well.

**Comment by axcore** [comment]
Added in v2.3.120. The column now shows both the time and date. You can disable showing the date, if you want.
