### ISSUE TITLE
are you able to split files based on time stamps? 

### ISSUE THREAD

**Issue by alidan** [axcore/tartube#282]
I dont notice this on the main page mentioned when searching split, and I dont see a place that stands out that screams 'right here is what you want' 

for reference, this video is what I want to split, 
https://www.youtube.com/watch?v=OXv-LFZeBU8

while its possible to do, i'm wondering if there is an inprogram way to do it,

**Comment by axcore** [comment]
youtube-dl does not download information about the timestamps, so I would guess the answer is (currently) no.

If you're prepared to type the timestamps manually, then Google suggests some solution, for example [here](https://old.reddit.com/r/youtubedl/comments/b67xh5/downloading_part_of_a_youtube_video/ejv5ye7/) and [here](https://unix.stackexchange.com/questions/230481/how-to-download-portion-of-video-with-youtube-dl-command).

**Comment by alidan** [comment]
ok, I think this would fall into requests now, I dont know what it was but there was something I used to download from youtube a while back that would split files, something I used when I found out about electro swing and people made 'best of this month' videos, I have no idea what it was anymore but it helped quite a bit. 

since there are youtube videos that split large videos up into segments, and in the case of music they would probably love the segments split up, would it be possible to add a function to do that? I know it wouldn't be lossless, but would be very helpful.

**Comment by axcore** [comment]
Are you prepared to type in all the timestamps yourself?

**Comment by alidan** [comment]
should the time stamps be able to be pulled from the description, possibly even named off the descriptions time stamp? from what I have seen, most videos that have time stamps also label what that segment will be called, if it takes a bit of manual set up on the user end, pulling the initial bit from the description in a format like

(time goes here) (any text is now the title of the segment) 
(any line break is a new time stamp)

with the potential output being

(name of the video) - (name of the segment) 
with a potential sequential number in between, probably a user preference. 

if it was just this much in program, I think its entirely doable. but taking it out and running command lines myself, thats a step further then I would want to go, it may be faster then dropping it into a daw, but its not as user accessible and I have never really been comfortable with command line.

**Comment by axcore** [comment]
>should the time stamps be able to be pulled from the description
Yes, that would be workable.

**Comment by pukkandan** [comment]
> > should the time stamps be able to be pulled from the description
> Yes, that would be possible.

youtube-dl already pulls the chapter markers and makes it available in the infojson. It is also added to the media file as chapters if `--add-metadata` is used.

yt-dlp additionally has an option `--split-chapters` to split these chapters into seperate files.

**Comment by axcore** [comment]
@pukkandan, thanks for your suggestion.

I have been working on this feature request, so Tartube can now split videos into sections, based on the timestamps in the video description, or on custom timestamps. I will add your method as well. It might be a few days before the new code is ready for release.

**Comment by axcore** [comment]
>would it create a folder for the single video with the video name and then segment names?
Yes, but that behaviour is disabled by default.

>has the time stamps on the left side and the segment names on the right, will it know what to do in this scenario or would user input be needed?
It extracts timestamps from the description, in both formats (text-timestamp, timestamp-text)

>above you were talking about user input, would we be able to clean up any of these segments ourselves or is it out of our hands?
Yes, you can enter your own timestamps, or edit the timestamps extracted from the description, before splitting the video

>would be able to force a video to be downloaded in segments and input our own segments?
As far as I understand, youtube-dl doesn't download the video in segments, it downloads the whole video then passes it to FFmpeg. But I haven't done that part yet.

**Comment by alidan** [comment]
thank you

**Comment by axcore** [comment]
v2.3.184 adds support for video clips. The updated code is only on github/pypi at the moment.

To download a video clip, just right-click a video and select **Download video clip...**

To extract a video clip from a video you've already downloaded, just right-click a video and select **Create video clip...**

There are various settings available in **Edit > System preferences... > Operations > Clips**. You probably want to auto-extract timestamps when you check/download videos, so you should definitely enable those options.

For more complex stuff, see the new section in the [README](https://github.com/axcore/tartube#626-video-clips).
