### ISSUE TITLE
how to download and update yt-dlp from a custom path MS Windows

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#283]
how to download and update yt-dlp to the latest version of a custom path without `yt-dlp -U`and `pip3` for MS Windows?

**Comment by axcore** [comment]
Tartube does not support yt-dlp on MS Windows at the moment.

**Comment by candrapersada** [comment]
Have you tried using yt-dlp as a custom path like #243 for MS Windows?

**Comment by axcore** [comment]
Closed for inactivity. Tartube has supported yt-dlp on MS Windows for a long time.
