### ISSUE TITLE
why re-downloading makes ytdl-archive lost when resuming manual download in Classic Mode

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#285]
Why does the ytdl-archive always reset when typing the re-download button to continue downloading the YouTube playlist without downloading from scratch again? #218 
and why remember URL not working After downloading 50 videos from 100 youtube playlists to continue the remaining 50 videos?

**Comment by axcore** [comment]
>and why remember URL not working After downloading 50 videos from 100 youtube playlists to continue the remaining 50 videos?

I fixed that as well.

Now, if you **Stop** the download of the channel or playlist, it is remembered.

**Comment by axcore** [comment]
Added in v2.3.549.
