### ISSUE TITLE
Bulk changing channel URLs and/or PSA

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#286]
I had assumed that when adding a channel into Tartube it would just download their videos, but as I found out, this isn't the case. It seems to download everything; public playlists, favorites, etc.

Adding "/videos" at the end of a channel URL seems to restrict it to only download their uploaded videos. However, with hundreds of channels this would be quite a time consuming process to manually change the URLs to each channel already added.

I'm asking for a feature that would allow mass adding "/videos" to existing channels, and/or a notice when adding channels that unless "/video" is in the URL it will download everything from that user. There could also be a button on the add channel pop-up window that lets you easily add "/videos" to the URL.

Having bulk way to edit the existing channels would be easier if you need to change channel names, or properties, folder, etc. I'm imagining just a excel-style row-by-row list of every channel that you can edit then save all on one page. If that makes sense?

I know this might be a large feature request, but I think when tartube matures (as it has over the last year/2), and people start getting big list of channels, it would become cumbersome to manually change if they screw up like what I did.

thank you!

**Comment by axcore** [comment]
All added in v2.3.135.

Click **Edit > System preferences... Files > URLs** to see Excel-style list of channels/playlists. Double-click on each URL to change it.

Alternatively, you can select one or more lines, then apply a change to all of them. Enter a pattern and a substitution, and then click the **Search and replace text in the selected URLs** button.

That method requires some knowledge of regular expressions. Deselect the **Regex** checkbutton and you'll get a normal search-and-replace, e.g. to convert **youtube** to **schmootube**.

In both cases, all matching text is replaced (not just the first instance).

In addition, the **Add channel** box has been updated. If you try to add a channel URL that doesn't end in **/videos**, you'll see a reminder. The reminder is also available in Dutch and Korean.
