### ISSUE TITLE
Error: m3u8 download detected but ffmpeg or avconv could not be found. Please install one.

### ISSUE THREAD

**Issue by gelsas** [axcore/tartube#29]
I am trying to use this software but I always get this error:

Error: m3u8 download detected but ffmpeg or avconv could not be found. Please install one.

In System Preferences I set the Path to the ffmpeg/avconc binary to C:\ffmpeg\bin\ffmpeg.exe
That is where my ffmpeg is.

It still show the same error as before.

Please help

**Comment by axcore** [comment]
Hi gelsas,

This is a youtube-dl error, not a Tartube error. 

I checked the youtube-dl issues page. The most recent answer is at the bottom of this page:

https://github.com/ytdl-org/youtube-dl/issues/2815

Try installing the build. On 64-bit Windows, Tartube installs youtube-dl to

C:\Users\YOURNAME\AppData\Local\Tartube\msys64\mingw64\lib\python3.7\site-packages\youtube-dl

**Comment by axcore** [comment]
v1.3.0 contains a fix for this. Click **Operations > Install FFmpeg** to fetch a compatible version of FFmepg.
