### ISSUE TITLE
Finished downloads not being shown as completed (no check mark)

### ISSUE THREAD

**Issue by jneffekt** [axcore/tartube#290]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Windows 10

### What version of Tartube are you using?
v2.3.110
__________________

As per title. I think it's something to do with Korean symbols (Asian symbols in general I think) not being recognised upon download completion. I've come to this conclusion because the completed filenames on Tartube do not show the symbols at al even though it's fine when browsing the folder

Using this playlist for example: https://www.youtube.com/playlist?list=PLWDz_A_ER636aK1kjRikHsTgzCUfiMtJn

![1](https://user-images.githubusercontent.com/35053683/116408215-b36d7d00-a871-11eb-94fc-d99c1febd504.png)
.

**Comment by jneffekt** [comment]
Uninstalling and reinstalling and/or changing the download path seems to have fixed the issue.

**Comment by jneffekt** [comment]
Issue seems to persist with new videos. Need to delete the file and recheck for it to confirm its existence in folder.

**Comment by axcore** [comment]
I haven't had time to look into this yet, but there's a file-checking operation which might do the job better. Click Operations > Tidy up files, and select "Check that videos do/don't exist" before clicking the OK button to start.

**Comment by jneffekt** [comment]
That method of checking files does not work, I think it is only checking for the broken filename that is only shown in TarTube.

**Comment by axcore** [comment]
Sorry for the delay, real life stuff keeps getting in the way.

It looks like the same issue as [this one](https://github.com/axcore/tartube/issues/251), which is an unresolved youtube-dl issue. Not much I can do about that, I'm afraid.

**Comment by axcore** [comment]
Closed this and several related issues, replacing it with a single issue: https://github.com/axcore/tartube/issues/320
