### ISSUE TITLE
Cannot resize main window

### ISSUE THREAD

**Issue by lsaranto** [axcore/tartube#291]
Tartube 2.3.120
Linux Debian VM

I've been using Tartube fine. Now, suddenly, today Tartube decided to resize its main window bigger than the desktop (1920x1080) is. I can resize the window height, but the width can not be changed (dragged). I also tried editing the settings.json file and putting reasonable values, but when Tartube starts, the window goes to the previous size (too wide). I also tried toggling the save window size setting. And I rebooted the system.

**Comment by axcore** [comment]
The first thing to say is that the size of the window is decided by the system (desktop manager). Applications like Tartube can request a size, and the system can either respect that request or ignore it.

I suggest this workaround, which will trick the system by creating a dialogue window before the main window is created:

1. Find Tartube's configuration file. If you don't know where it is, click Edit > System preferences... > Files > Device, the location is visible at the bottom of the tab
2. Rename the file so Tartube can't start it
3. Start Tartube. Skip through the dialogue window
4. Shut down Tartube
5. Delete the brand new configuration file, and restore the old file's name (**settings.json**)

If that doesn't work, we can look at hacking the code.

**Comment by lsaranto** [comment]
I switched, I think, desktop manager and/or desktop environment. I also did some edits found from google which may or may not had an effect. But now the window is at least behaving properly.

**Comment by axcore** [comment]
Glad you got it cleared up. I added a button to reset the main window to its default size (Edit > System preferences > Windows > Main window), but I don't know if it will work in your particular situation. Anyway, it will be in the next release.

**Comment by axcore** [comment]
Ok, I found a possible explanation for this behaviour: in the **Progress** tab, you can increase the number of simultaneous downloads, which increases the number of pages in the **Output** tab, which causes the window to increase in width (and the width can't be reduced).

I found a fix for this particular problem as well, and it will be in the next release.

**Comment by lsaranto** [comment]
So, you're saying I caused it myself. :) Although, I've had the max number (10) of downloaders for months. For some reason this behaviour only triggered now when I switched Tartube versions. Going back didn't help either. But I guess it was mainly caused by the desktop manager.
