### ISSUE TITLE
Window Position [Question]

### ISSUE THREAD

**Issue by smaragdus** [axcore/tartube#292]
I use [Tartube](https://tartube.sourceforge.io/) with these preferences selected:

- `Remember the size of the main window when shutting down`
- `Also remember the position of main window sliders`

Screen:

![Tartube 2 3 110 - 2021-05-12 - 002](https://user-images.githubusercontent.com/9025757/117893396-fa705f00-b2c2-11eb-89e2-e14b848701d3.png)

The window size appears to be preserved after restart but the window position is not saved, so any time I start [Tartube](https://sourceforge.net/projects/tartube/) I need to use an external tool ([SmartSystemMenu](https://github.com/AlexanderPro/SmartSystemMenu)) to re-position the program window.

Screen:

![Tartube 2 3 110 - 2021-05-12 - 004](https://user-images.githubusercontent.com/9025757/117893611-69e64e80-b2c3-11eb-843f-a2389726ce4b.png)

I am not sure whether the preferences mentioned above are supposed to preserve the position of the main window and the settings windows. Actually any time I restore the program from system tray (I use `Close to the tray, rather than closing the application` option enabled) I have to re-position the program. For me this is a bit annoying. I could not find whether there are such settings in the configuration file (`settings.json`).

I am using the x64 portable edition of [Tartube](https://github.com/axcore/tartube) [version](https://github.com/axcore/tartube/releases) [2.3.110](https://github.com/axcore/tartube/releases/tag/v2.3.110) on Windows 8 x64.

**Comment by axcore** [comment]
The position of Tartube windows depends on the system. The system places windows wherever it wants. This will normally be the centre of the desktop.

Applications like Tartube are not supposed to interfere with window positioning, so the Tartube code doesn't do that. 

Restoring the programme from the system tray is a different problem. Again, the window re-appears in the centre of the desktop because that's where the system puts it. I can experiment with moving the window back to its old position, but there is no guarantee it will work.

**Comment by smaragdus** [comment]
@axcore 

Thanks for the clarification. Actually when I start the program it is never centered on desktop (I do this manually), it usually appears at the top left part of the screen.

I thought that saving program coordinates on desktop in the configuration file would be possible.

Feel free to close this issue, I am not doing it myself because you may have reasons to keep it open.

**Comment by axcore** [comment]
I added some code to remember the window's position when it is closed to the system tray, it will be in the next release.

**Comment by smaragdus** [comment]
@axcore 

> I added some code to remember the window's position when it is closed to the system tray, it will be in the next release.

Thanks

**Comment by axcore** [comment]
Added in v2.3.135.

**Comment by smaragdus** [comment]
@axcore 

Thanks! When the new version is published I will check it.

Regards

**Comment by axcore** [comment]
If you are using Windows, you can just download the code from github, and then copy the files to **C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube\**, overwriting the files that are already there.
