### ISSUE TITLE
Classic mode: Re-download button is disabled when downloading

### ISSUE THREAD

**Issue by lsaranto** [axcore/tartube#293]
When nothing is downloading, I can select one or more downloads from the list and press Re-download, and the downloading starts. But when there is a download already going, the Re-download button is disabled, or at least does nothing. This is annoying because if a download stops because of a connection issue or something, you can't just click the button to continue. You have to copy the URL, remove it from the list and then re-add it.

**Comment by axcore** [comment]
I believe this is already fixed. The fix is already uploaded to github, and will be in the next full release.

I'll leave this thread open until I can check that formally.

**Comment by candrapersada** [comment]
and why does Automatic re-download not work properly for Classic mode?

**Comment by axcore** [comment]
I got your issue confused with another one. YOUR issue is fixed in v2.3.135.

**Comment by axcore** [comment]
>and why does Automatic re-download not work properly for youtube from Classic mode?

Same answer as before: I don't know how to reproduce your problem, so I don't know how to fix it.
