### ISSUE TITLE
The number of simultaneous downloads

### ISSUE THREAD

**Issue by lsaranto** [axcore/tartube#294]
Is there a reason why simultaneous downloads is limited to ten? Also, it doesn't seem to be possible to untick the checkbox. When you do and then go back it's again ticked.

**Comment by axcore** [comment]
>Is there a reason why simultaneous downloads is limited to ten?

The reasons are: (1) Gtk library + threads = crash, and (2) Simultaneous download requests + YouTube = IP ban

I can up the limit, if you like. Perhaps you can tell me what upper limit you'd like to see.

>Also, it doesn't seem to be possible to untick the checkbox. When you do and then go back it's again ticked.

Fixed that a few days ago but I don't think it's uploaded yet.

**Comment by lsaranto** [comment]
Ok, I see. Well, I think 20 would be plenty. Will it be unlimited when the untick works? That's also enough for me. You could mention the reasons somewhere: in the docs or in a tooltip or somewhere. They are valid reasons

Sorry, I forgot to reply sooner.

**Comment by axcore** [comment]
Fixed in v2.3.135.  

I increased the maximum number of simultaneous downloads to 32. I fixed the checkbutton, so if it's not selected, you will have 32 simultaneous downloads.
