### ISSUE TITLE
Is there anyway to download to multiple locations?

### ISSUE THREAD

**Issue by wilhil** [axcore/tartube#296]
Hi,

Just found out about this project and quite like it!

I've been experimenting and can see that I can add new folders, but, when I look at properties, they all are within the working directory of Tartube.

Without messing around with junction folders or "hacks", is there any good way of targeting different folders? 

Thanks

**Comment by axcore** [comment]
Tartube's database, and the videos associated with it, are stored inside one folder. 

You can create as many different databases as you want, even on different physical hard drives, but only one of them can be loaded into memory.

If you want to view multiple databases at the same time, just start multiple copies of Tartube. See [here](https://github.com/axcore/tartube#managing-databases).

**Comment by wilhil** [comment]
Hmm, I saw that, but that means having about 30 DBs just to target different folders across the storage infrastructure... manually switching/checking isn't much better than what I do manually now.

I'll try to experiment with junction folders then in order to redirect... but, please can this be considered for a feature request in the future? ... Just wish this app was around (or I found out about it) many years ago before I started archiving!

Thanks

**Comment by axcore** [comment]
That is not feasible, for about a dozen different reasons.

The chief problem is that no-one on this planet owns a 100% reliable hard drive, so there has to be all sorts of error checking. It's manageable for a single folder, it would be horrendous for thirty different ones.

If you _don't_ need a database, but just want the Classic Mode tab to download into thirty different folders, that would be feasible.

**Comment by wilhil** [comment]
Not saying a hard drive is reliable, but, all I'm asking about is changing the location of folders that are already in tartube..

![image](https://user-images.githubusercontent.com/2283808/120182862-dee3de80-c206-11eb-9a81-b1b0990391e2.png)

Granted I haven't written it, so, if there are a dozen reasons, I fully respect that and won't go on - but, I'm just saying to just change location on folders that are added.

I've just added c:\tmp\tartube as root.

I've now created 5 junction folders to different locations, and, it does appear to work fine, without issue - it just means that I have to persist the junction folders/remap them as I was hoping to make this portable... So, happy to say that I think I can do what I want with Tartube, it just isn't a "nice" way of going about it.

**Comment by formlessdao** [comment]
I am not able to figure out how to set up download location for videos i want to download. You do not mention anywhere how to do this in a clear manner.

**Comment by axcore** [comment]
@formlessdao Who are you asking, me or the other guy?

**Comment by formlessdao** [comment]
> 
> 
> @formlessdao Who are you asking, me or the other guy?

I'm asking you. You do not mention anywhere how to choose download location for videos we wan to download.

**Comment by axcore** [comment]
All videos in the database are stored inside one folder. That folder can be anywhere on your filesystem.

To change the location of the folder, click **Files > Database preferences...**, then click **Add new database**. For more information about databases, read [this](https://github.com/axcore/tartube#620-managing-databases).

I think your question is, _How do I save all Pewdiepie videos to C:\myvideos\pewdipie, but all MrBeast videos to D:\othervideos\mrbeast?_ 

And the answer is, I have not implemented that because of lots of boring technical reasons.

**Comment by formlessdao** [comment]
> 
I have not implemented that because of lots of boring technical reasons.
> 
Well that is the most basic of the basic functionalities needed otherwise we're limited to only one partition.

**Comment by wilhil** [comment]
@formlessdao - at the end of the day @axcore is producing open source software, say your requirement and cross your fingers it gets picked up - or fork and build yourself... but, that's the best you can do! I agree that this would be amazing - but, it looks like it won't be supported either ever, or for a long time.

Read up about junction folders and that's basically what I did.... however (sorry), I'm attempting to use an alternate software now as I had a few more issues.

To give you a head start, basically, setup your default library to somewhere obvious - e.g. c:\tartube

go to a command prompt and navigate to that folder. then type:

mklink (name of folder) (real location of folder)


So from start to finish, say you want to create (using Axcore's example), Pewdiepie to  C:\myvideos\pewdiepie and MrBeast to D:\othervideos\mrbeast you would do as follows:

1. Create a new tartube database at c:\tartube
2. Open tartube and add Pewdiepie and Mrbeast.
3. create the folders c:\myvideos\pewdipie and d:\othervideos\mrbeast
4. close tartube and move any files from c:\tartube to the new location.
5. delete the c:\tartube folders
6. type: 

mklink exact-name-the-old-pewdiepie-folder-was c:\myvideos\pewdipie
mklink exact-name-the-old-mrbeast-folder-was d:\othervideos\mrbeast

7. reopen tartube

and it should be working for you.

I hope this helps.

**Comment by formlessdao** [comment]
> 
> 
> @formlessdao - at the end of the day @axcore is producing open source software, say your requirement and cross your fingers it gets picked up - or fork and build yourself... but, that's the best you can do! I agree that this would be amazing - but, it looks like it won't be supported either ever, or for a long time.
> 
> Read up about junction folders and that's basically what I did.... however (sorry), I'm attempting to use an alternate software now as I had a few more issues.
> 
> To give you a head start, basically, setup your default library to somewhere obvious - e.g. c:\tartube
> 
> go to a command prompt and navigate to that folder. then type:
> 
> mklink (name of folder) (real location of folder)
> 
> So from start to finish, say you want to create (using Axcore's example), Pewdiepie to C:\myvideos\pewdiepie and MrBeast to D:\othervideos\mrbeast you would do as follows:
> 
>     1. Create a new tartube database at c:\tartube
> 
>     2. Open tartube and add Pewdiepie and Mrbeast.
> 
>     3. create the folders c:\myvideos\pewdipie and d:\othervideos\mrbeast
> 
>     4. close tartube and move any files from c:\tartube to the new location.
> 
>     5. delete the c:\tartube folders
> 
>     6. type:
> 
> 
> mklink exact-name-the-old-pewdiepie-folder-was c:\myvideos\pewdipie
> mklink exact-name-the-old-mrbeast-folder-was d:\othervideos\mrbeast
> 
>     1. reopen tartube
> 
> 
> and it should be working for you.
> 
> I hope this helps.

How can I contact you?

**Comment by formlessdao** [comment]
axcore where can i find a confirmation that a file is downloaded successfully and there are no errors?

**Comment by wilhil** [comment]
> How can I contact you?

Just message me here...

**Comment by formlessdao** [comment]
> 
> 
> > How can I contact you?
> 
> Just message me here...

What other software are you testing?

**Comment by wilhil** [comment]
Just Google and research - I don't think it's right to promote other solutions here, especially when the author has tried to help... the other one had some more advanced options that were more suited to what I wanted to do, but, it certainly wasn't a turnkey solution and had similar shortcomings - so, if you aren't able to do the above with junction folders, I'm sorry to say that I think you will have the same problems elsewhere.

**Comment by formlessdao** [comment]
Well that's why i asked you to tell me how i can contact you because i wanted to know what software you tried.

**Comment by axcore** [comment]
I have been experimenting with a possible solution to this problem, and that solution is available in v2.3.233. The update is only available from github/pypi at the moment (there will be a full release later this month).

It's experimental, so perhaps you would like to test it, and tell me if it meets your needs.

To set a fixed location for a channel, outside of Tartube's data folder, right-click it and select **Channel actions > Set download destination...**. In the new window, click **Use an external location**, then click the **Set** button to choose a folder. Click **OK** to apply the changes.

(You can also do that to playlists and folders).

There is also a new option to disable adding videos to Tartube's database, which may interest you. If selected, the **Videos** tab behaves much like the **Classic Mode**: right-click a channel (etc), and select **Downloads > Don't add videos to Tartube's database**.
