### ISSUE TITLE
Missing Icons in Classic Mode

### ISSUE THREAD

**Issue by JeanMerand** [axcore/tartube#297]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Kubuntu 21.04 (DE: KDE Plasma 5)

### What version of Tartube are you using?
v2.3.110

### What happens when you run Tartube from a terminal window?
It launches Tartube

### How was it installed?
I installed this version by using the DEB package.

### What is the issue?
In Classic Mode there are a red square with a "wrong way" sign instead of icons, see screenshot below.

![Screenshot_20210605_113146](https://user-images.githubusercontent.com/85391288/120887203-cce0b200-c5f1-11eb-95e7-156325a524a9.png)

**Comment by axcore** [comment]
Please try [this](https://github.com/axcore/tartube#727-some-icons-not-visible).

**Comment by JeanMerand** [comment]
Hi,
no sorry, that's not better:

![Screenshot_20210606_144518](https://user-images.githubusercontent.com/85391288/120924841-f5da7300-c6d5-11eb-93e2-12381ad11232.png)

**Comment by axcore** [comment]
After changing the setting, have you restarted Tartube? (Sorry for the obvious question)

**Comment by axcore** [comment]
Closed for inactivity.
