### ISSUE TITLE
Cannot sort Classic mode download window columns

### ISSUE THREAD

**Issue by lsaranto** [axcore/tartube#298]
Are the columns in Classic mode bottom window supposed to sort when you click the header? I'd suppose the functionality would be provided by the UI library, but mine does nothing when I click them.

**Comment by axcore** [comment]
No, that hasn't been added. It would not be a trivial task.

**Comment by lsaranto** [comment]
Ok then, no worries. I was afraid it's, again, something that's happening only on my system.
