### ISSUE TITLE
Add simple quality selector

### ISSUE THREAD

**Issue by JJRcop** [axcore/tartube#30]
This project was made in response to [youtube-dlg] being unmaintained as of late. The single showstopper for me installing that program on my father's computer was the lack of a simple quality selection interface, instead listing every available video format (for youtube-dl's --format selection) you had to manually select. And this may only apply to one site that provides that format or may be different per video.

Tartube does the same thing, so I have the same issue.

A simple selector with 360p, 480p, 720p, 1080p, 1440p, 2160p, etc should be added that tells youtube-dl the equivalent of
```sh
youtube-dl --format "bestvideo[height<=selectedformat]+bestaudio/best[height<=selectedformat]"
```
possibly with an audio only option as well to ask for "bestaudio", but not strictly necessary.

This will get youtube-dl to handle the format selection and not force the user to select every relevant possible format if they don't want to download the highest quality video.

I believe this option should not be located under download options and should be directly accessible on right click of a download, or even better, from the main UI.

Thank you for your hard work on this program, it is lovely!

[youtube-dlg]: https://github.com/MrS0m30n3/youtube-dl-gui

**Comment by JJRcop** [comment]
As a side note, the download options are very extensive and are clearly intended for experienced youtube-dl users who have already read the manual. It would be nice to hide most of these under an "advanced options" menu and make the normal options assume the user does not know how youtube-dl works.

**Comment by axcore** [comment]
Hi JJRcop, those are both sensible suggestions.

**Comment by axcore** [comment]
Is there a reason why you want 

`youtube-dl --format "bestvideo[height<=selectedformat]+bestaudio/best[height<=selectedformat]"
`

and not:

youtube-dl --format "bestvideo[height<=?selectedformat]+bestaudio/best[height<=?selectedformat]"

**Comment by JJRcop** [comment]
Nah there's no reason, the other form is better.

**Comment by axcore** [comment]
A simpler options window for Tartube could look like the youtube-dlg options window. Is that what you had in mind?

**Comment by axcore** [comment]
I have implemented all your requests. Regarding the simpler options window, you can judge for yourself whether I have gone too far / not gone far enough, when I'm ready to upload the code in a few days.

**Comment by JJRcop** [comment]
I'd like to apologise for adding the options menu comment here rather than making a separate issue. I did not have any particular style in mind for a simpler options menu, I feel your best judgement will be enough if you keep average computer users in mind.

**Comment by axcore** [comment]
Added in v1.3.0.

There are two ways to set the minimum resolution. There is a selector at the bottom of the Progress Tab (don't forget to select the checkbutton, or it won't be applied). There are also new options in the Download Options window. Both of these have the same effect, so you don't need to set both.

The simpler Download Options window is enabled by default. You can show more advanced options by clicking the big button.
