### ISSUE TITLE
Refuses to download videos, output talks about "simulated download" for every single one

### ISSUE THREAD

**Issue by themaster567** [axcore/tartube#301]
### What operating system are you using?
Arch Linux

### What version of Tartube are you using?
2.3.110

### What happens when you run Tartube from a terminal window?
Zero difference.

It will usually download the thumbnail and description, but it will never download the video. I have both youtube-dl and yt-dlp installed. I'm losing my mind trying to figure this out. After doing some searching, it seems like nobody has ever had this exact problem, so I'm really at a loss. I've already tried reinstalling as well as deleting the config folder entirely, with no change in behavior.

**Comment by glubsy** [comment]
Post your logs please, can't help if you are not helping us help you.

**Comment by themaster567** [comment]
I wanted to, but there's nothing that's going to help you. This is all I get when I run it:
```
/usr/bin/yt-dlp --newline -i --hls-prefer-native -o /home/killbotvii/tartube-data/Metal Gear Solid MOVIES/%(title)s.%(ext)s --write-description --write-info-json --write-annotations --cookies /home/killbotvii/tartube-data/cookies.txt --write-thumbnail -f bestvideo[height<=?1080][fps<=?60]+bestaudio/best[height<=?1080] --dump-json --download-archive /home/killbotvii/tartube-data/Metal Gear Solid MOVIES/ytdl-archive.txt https://www.youtube.com/watch?v=zndcY57Tijo
[Metal Gear Solid MOVIES] <Simulated download of: 'Metal Gear Solid 3 - The Movie [HD] Full Story'>

```

**Comment by axcore** [comment]
![pewdiepie](https://user-images.githubusercontent.com/37951926/121796579-075dd680-cc12-11eb-9594-5d2c7a5cb583.png)

Is the channel/playlist/folder in italics, like this? If so, you can re-enable downloads by right-clicking it, and de-selecting **Downloads > Just disable downloads**

**Comment by themaster567** [comment]
> ![pewdiepie](https://user-images.githubusercontent.com/37951926/121796579-075dd680-cc12-11eb-9594-5d2c7a5cb583.png)
> 
> Is the channel/playlist/folder in _italics_, like this? If so, you can re-enable downloads by right-clicking it, and de-selecting **Downloads > Just disable downloads**

That did it. Thank you very much.
