### ISSUE TITLE
Tartube refuses to finish the installation with a generic popup "Failed to save the Tartube config file (file already in use)"

### ISSUE THREAD

**Issue by Lumios64** [axcore/tartube#302]
### What operating system are you using?
I am using Debian 8 and have both Python 2 and Python 3 installed in different directories. Python 3 is the version 3.5.2. I also have ffmpeg installed.

### What version of Tartube are you using?
I am using the latest version of Tartube freshly downloaded from the website last week. I cannot see the version because I don't have access to the about page of Tartube since I couldn't finish the installation in the first place, but I would assume it is version 2.3.110 since, according to the website, it was last updated in February and I downloaded the program last week.

### What happens when you run Tartube from a terminal window?
Here's the full log:

/usr/lib/python3/dist-packages/matplotlib/backends/backend_gtk3agg.py:18: UserWarning: The Gtk3Agg backend is known to not work on Python 3.x with pycairo. Try installing cairocffi.
  "The Gtk3Agg backend is known to not work on Python 3.x with pycairo. "
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tartube/wizwin.py", line 501, in on_button_next_clicked
    self.apply_changes()
  File "/usr/lib/python3/dist-packages/tartube/wizwin.py", line 679, in apply_changes
    self.app_obj.open_wiz_win_continue()
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 7898, in open_wiz_win_continue
    self.start_continue(True)
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 2772, in start_continue
    self.main_win_obj.setup_win()
  File "/usr/lib/python3/dist-packages/tartube/mainwin.py", line 908, in setup_win
    self.setup_videos_tab()
  File "/usr/lib/python3/dist-packages/tartube/mainwin.py", line 1589, in setup_videos_tab
    self.videos_paned.set_wide_handle(True)
AttributeError: 'HPaned' object has no attribute 'set_wide_handle'

The Traceback showed up at the very moment of the popup error when I try to finish the installation. Everything else about the setup went smoothly and I could tweak what I did want and what I didn't want.
![Screenshot from 2021-06-08 13-47-09](https://user-images.githubusercontent.com/85809526/121806093-be784300-cc4e-11eb-9c9b-ea8986c781e1.png)

###If your bug report is "I can't download this video", please provide a link to the video
-

**Comment by axcore** [comment]
I haven't seen this error before, but you should try this first of all:

`sudo apt-get install python3-cairocffi`

**Comment by Lumios64** [comment]
> 
> 
> I haven't seen this error before, but you should try this first, before reinstalling Tartube:
> 
> `sudo apt-get install python3-cairocffi`

Hello again, so I did as you said and the issue still isn't solved. The traceback is still there with its associated pop-up error message stating that the configuration file couldn't be written. 
The warning from before about cairocffi is gone though. I doubted this was what was causing the problem in the first place.

Here's the log just in case, but it is almost identical to my issue's.
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/tartube/wizwin.py", line 501, in on_button_next_clicked
self.apply_changes()
File "/usr/lib/python3/dist-packages/tartube/wizwin.py", line 679, in apply_changes
self.app_obj.open_wiz_win_continue()
File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 7898, in open_wiz_win_continue
self.start_continue(True)
File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 2772, in start_continue
self.main_win_obj.setup_win()
File "/usr/lib/python3/dist-packages/tartube/mainwin.py", line 908, in setup_win
self.setup_videos_tab()
File "/usr/lib/python3/dist-packages/tartube/mainwin.py", line 1589, in setup_videos_tab
self.videos_paned.set_wide_handle(True)
AttributeError: 'HPaned' object has no attribute 'set_wide_handle'

**Comment by axcore** [comment]
Are  you able to run the source code directly, as described [here](https://github.com/axcore/tartube#5310-run-without-installing), or install from PyPI, as described [here](https://github.com/axcore/tartube#535-install-using-pypi)?

**Comment by Lumios64** [comment]
No chance there either, neither worked, including with root access to assure that it has all write privileges possible on my system.
 
It could likely be a compatibility issue, however. You could try to run the program on a virtual machine with Python 3.5 installed on it or earlier versions like Python 3.4 and 3.3 to see if you encounter an identical problem to mine. Another theory in my mind is that my system defaults to Python 2 instead of Python 3 since both are installed, but I will look into it in the upcoming weeks since I got free time for that due to it being the holiday season. Apologies for the bother.

I am thinking about contributing some code to the project since I have done a little bit of Python at school, though I am slightly more proficient in C.

**Comment by axcore** [comment]
Right, the actual error message is this one:

`AttributeError: 'HPaned' object has no attribute 'set_wide_handle'`

Hpaned is a structure that divides a window into two panes, with a moveable slider. According to the [documentation](https://developer.gnome.org/gtk3/stable/GtkPaned.html#gtk-paned-set-wide-handle), the .set_wide_handle() method was introduced in Gtk v3.16, which suggests that you have an older version of Gtk installed on your system.

Anyway, you can try commenting out that line (number 1589 in the mainwin.py file). That's not the only call to .set_wide_handle(), so you might have to comment out a few lines like that.

**Comment by axcore** [comment]
> Another theory in my mind is that my system defaults to Python 2 instead of Python 3 since both are installed

I think this is unlikely, we get an easily recognisable set of error messages when Tartube is run as Python 2

**Comment by axcore** [comment]
Closed for inactivity. If you have the same issue with the latest release of Tartube, please open a new issue.
