### ISSUE TITLE
Video downloads as WEBM Video File

### ISSUE THREAD

**Issue by ScoobyDoo2021** [axcore/tartube#303]
I download youtube videos and they usually download as MKV files.
Noticed a couple that got saved as WEBM files.
Anyone know why this might be?

Also sometimes, a video will get saved very quickly. Less than 30secs

Rarely but sometimes, a video takes ages to download (even though it's a small, short video - 100mb or so). 
Any reason for this?

**Comment by axcore** [comment]
>Anyone know why this might be?

Not all videos are available for download. You can test this for yourself by right-clicking a video, and selecting **Fetch > Available formats**. The results is visible in the **Output** tab.

>Rarely but sometimes, a video takes ages to download 
Without having some URLs to test I can't say, but videos do not always download in a playable state, so youtube-dl has to process them (for example, it's quite common for the video and audio to arrive separately).

Make sure you have FFmpeg installed.
