### ISSUE TITLE
Authentication with .netrc file

### ISSUE THREAD

**Issue by arjung24** [axcore/tartube#305]
Thanks for taking the time to ask a question! 

### Please read the README
Perhaps your question is answered there

### The authors are not experts in python, security, youtube-dl, FFmpeg, Debian/RPM packaging or Windows programming
You are welcome to ask a Tartube-related question, but you might get a better answer in forums where those kinds of expert can be found

**Comment by arjung24** [comment]
Is it possible to download with authentication like we do in yt-dlp .netrc file:

You may also want to configure automatic credentials storage for extractors that support authentication (by providing login and password with --username and --password) in order not to pass credentials as command line arguments on every yt-dlp execution and prevent tracking plain text passwords in the shell command history. You can achieve this using a .netrc file on a per extractor basis. For that you will need to create a .netrc file in your $HOME and restrict permissions to read/write by only you:

touch $HOME/.netrc
chmod a-rwx,u+rw $HOME/.netrc
After that you can add credentials for an extractor in the following format, where extractor is the name of the extractor in lowercase:

machine <extractor> login <login> password <password>
For example:

machine youtube login myaccount@gmail.com password my_youtube_password
machine twitch login my_twitch_account_name password my_twitch_password
To activate authentication with the .netrc file you should pass --netrc to yt-dlp or place it in the configuration file.

On Windows you may also need to setup the %HOME% environment variable manually. For example:

set HOME=%USERPROFILE%

**Comment by axcore** [comment]
Added in v2.3.223. 

Click **Edit > General download options...**. Click the **Show advanced download options** button if it's visible. Then click **Advanced > netrc**.

For your convenience, the .netrc file can be created, or edited, from this location. The youtube-dl configuration file can also be created/edited from the **Advanced > Configurations** tab, in case that's of any interest to you.
