### ISSUE TITLE
Can't install yt-dlp

### ISSUE THREAD

**Issue by NathanYumekoe** [axcore/tartube#306]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
If using MS Windows, are you using Windows 10, Windows 7, or something else?
Windows 11 Pro and Windows 10 Pro (tried both)

### What version of Tartube are you using?
In Tartube's main window, click Help > About
2.3.110

### What happens when you run Tartube from a terminal window?
Many error messages are only visible in the terminal window. On MS Windows, this is how to do it:

- First, enable hidden folders on your system
- Then, run the application: 

    C:\Users\YOURNAME\AppData\Local\Tartube\msys64\mingw64.exe

- In this new window, type these commands to start Tartube:

    cd /home/user/tartube

    python3 tartube/tartube

The same thing
I am unsure how to find the actual lo, so here is attached what the setup window tells me [log.txt](https://github.com/axcore/tartube/files/6779637/log.txt)

**Comment by axcore** [comment]
That was fixed in v2.3.185.

The main installer has not been updated yet, but you can download the source code from github, and then copy it over the old source code, which is usually installed in

C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube\
