### ISSUE TITLE
Downloads Never "Finish"

### ISSUE THREAD

**Issue by DReaper** [axcore/tartube#308]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
W10

### What version of Tartube are you using?
2.3.110

This is something I noticed for a while, possibly starting with the most recent version. I have a lot of channels I download and update on. Lately, when I run a Download All command, all my downloads under Progress and would either Download, Error, or Warning, but it would always have the popup in the ending stating my task was complete.

However, this is no longer the case, even when there is nothing outstanding under Progress. Stopping the current operation does not work and I have to force close Tartube. It's as if Tartube thinks I am still downloading or processing a file. I fear this could cause errors over time.

**Comment by axcore** [comment]
Sounds like an invisible python error. 

Try running Tartube from inside a terminal window, following [these instructions](https://github.com/axcore/tartube#71-tartube-wont-installwont-rundoesnt-work), then show me what you see in the terminal window.

**Comment by DReaper** [comment]
I get the following error:

Exception in thread Thread-9:
Traceback (most recent call last):
  File "C:/Users/x/AppData/Local/Tartube/msys64/mingw64/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\x\AppData\Local\Tartube\msys64\home\user\tartube\tartube/downloads.py", line 1042, in run
    self.run_video_downloader(media_data_obj)
  File "C:\Users\x\AppData\Local\Tartube\msys64\home\user\tartube\tartube/downloads.py", line 1208, in run_video_downloader
    self.check_rss(media_data_obj)
  File "C:\Users\x\AppData\Local\Tartube\msys64\home\user\tartube\tartube/downloads.py", line 1422, in check_rss
    self.json_fetcher_obj.do_fetch()
  File "C:\Users\x\AppData\Local\Tartube\msys64\home\user\tartube\tartube/downloads.py", line 6196, in do_fetch
    stderr = stderr.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 194: invalid continuation byte

**Comment by axcore** [comment]
Good catch, I haven't seen an error like that before.

You can disable livestreams until I can release a fix. **Edit > System preferences . Operations > Live**, then deselect the button at the top, **Detect livestreams announced within this many days**

**Comment by DReaper** [comment]
Can confirm disabling that setting fixed the issue and I'm getting the popup again. Thank you!

**Comment by axcore** [comment]
It would be quite helpful to know which channel/playlist was causing the error, if you are able to share that.

**Comment by DReaper** [comment]
From the Output threads, this looks to be one of them
https://www.youtube.com/c/ICIGOSTYLEOFFICIAL/videos

**Comment by axcore** [comment]
Should be fixed in v2.3.279. If you don't need livestreams detection, then you don't need to update.
