### ISSUE TITLE
Allowing to copy url from right-click menu

### ISSUE THREAD

**Issue by MohamedEssabani** [axcore/tartube#309]
I tend to add a lot of videos to the default "unsorted" folder. Then when I want to move those to separate folders based on their theme (e.g. History, Funny vids, etc.), it would be really nice to be able to quickly copy the url of a video from the right-click menu. 

Better yet, if it would be possible to move videos from one folder to another (doesnt have to work with playlists or channels), that would be perfect.

**Comment by axcore** [comment]
Added in v2.3.279. Only available on git/pypi at the moment.
