### ISSUE TITLE
"Running setup.py install for websockets: finished with status 'error'", installation of the updater fails

### ISSUE THREAD

**Issue by cloudropis** [axcore/tartube#311]
On **Windows 10**, using the latest **2.3.110 64 bit installer**. Downloading and installing the updater gives me this (full log >>) https://pastebin.com/Zgx8Yb9G

EDIT this was after picking yt-dlp as backend, I gather it's the issue explained in the pinned thread?

**Comment by axcore** [comment]
Possibly. There will be a full release later this week, so you can see if that fixes your problems.

**Comment by axcore** [comment]
Should be fixed in v2.3.306.
