### ISSUE TITLE
FFmpeg's first installation fails, timed out from sourceforge

### ISSUE THREAD

**Issue by cloudropis** [axcore/tartube#312]
### What operating system are you using?
Windows 10

### What version of Tartube are you using?
2.3.110

FFmpeg's installation fails. A bunch of the required files get download, but from a point and onward every attempt of connecting to sourceforge times out.

Full log: https://pastebin.com/cDiS5Hxf

**Comment by axcore** [comment]
As detailed in other issues, FFmpeg installation issues are probably now fixed. If you are still having problems with the latest releases, please open a new issue.
