### ISSUE TITLE
I moved my libary to a diffrent external HDD, how do I change the download location?

### ISSUE THREAD

**Issue by strunberg** [axcore/tartube#313]
![vcxcvcvcxvcvx](https://user-images.githubusercontent.com/6355904/127451121-e56c9a1e-c405-4012-9df8-53eac67130ae.png)

**Comment by axcore** [comment]
Tartube downloads all of its videos into a single folder. You can move this folder to any external HDD.

Click **File > Database preferences...**

Then click the **Add new database** button, and select the folder at its new location

The folder is added to the list. Tartube searches the list from top to bottom, so you should **Forget** the old location, or use the **Move up** and **Move down** buttons.

**Comment by strunberg** [comment]
it created a new DB, can I use a backup DB?

**Comment by axcore** [comment]
What do you mean, a backup DB?

Do you mean, a backup of the database file, **tartube.db**? Tartube automatically makes backups of the database file, you can find them in the .backups folder. (On Linux, press CTRL+H to show hidden folders).

You can change how often Tartube makes backups, click **Edit > System preferences... > Files > Backups **
