### ISSUE TITLE
misc issues relating to versions

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#315]
I was running 2.3.206, then updated to the latest (2.3.279 commit 2478c58).

My downloads were failing and I noticed that the -o parameter was no longer appearing in the console. (turns out that the files were saving in the tartube code dir)

To try and help you debug it and figure which release it happened on I went back to yesterday's release and had the same issue. Then I tried to go back to 2.3.233 and upon launching got error:

![image](https://user-images.githubusercontent.com/16659133/127757587-1448a8dc-117f-4c8a-8165-b5593dea1e9c.png)

So i opened the settings.json file, changed the version string back, then tried to launch and got this:

`Owner@Tiger MINGW64 /home/user/tartube
$ python3.8 tartube/tartube
Traceback (most recent call last):
  File "C:\Users\Owner\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/mainapp.py", line 2822, in do_activate
    self.start()
  File "C:\Users\Owner\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/mainapp.py", line 2987, in start
    new_config_flag = self.load_config()
  File "C:\Users\Owner\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/mainapp.py", line 3907, in load_config
    self.custom_dl_by_video_flag = json_dict['custom_dl_by_video_flag']
KeyError: 'custom_dl_by_video_flag'
`

I opened the config file, added that line, saved, relaunched, eventually had to add all these back in:

` 
    "custom_dl_by_video_flag": false,
    "custom_dl_split_flag": false,
    "custom_dl_divert_mode": false,
    "custom_dl_divert_website": false,
    "custom_dl_delay_flag": false,
    "custom_dl_delay_max": false,
    "custom_dl_delay_min": false,`

Finally could get tartube to launch, but then got this screen:

![image](https://user-images.githubusercontent.com/16659133/127757451-96aa0a38-d91b-4cd6-8057-00c33fab322e.png)

I restored an older db backup and was able to open it but upon trying to edit download options got a python error. 

Restoring the 2.3.206 commit and using the older db I was able to edit download options again, and the download succeeded with the -o option included.

I'm using yt-dlp latest 7/21 release.

So at least in my case, at some point between the 2.3.206 release and now the -o output isn't being passed.

Also, would it be possible to have backups of settings.json saved, whether to the database backup folder or somewhere else? It would be handy to be able to easily go back to the version that corresponds to the database file.

In the meantime I'll try to remember to manually back it up before updating versions.

Thanks again for this awesome program Axcore!

**Comment by axcore** [comment]
The missing --output is fixed in v2.3.286. 

Tartube will refuse to load the configuration file and database file from future versions. You can see for yourself what happens when you try to trick it, but as a consolation prize, Tartube can read files from all previous version (and any failure is a bug that can be corrected).

I will look into automatic backups of the config file.

**Comment by ceonelson** [comment]
Just tested and all is good, thanks for the fix!
