### ISSUE TITLE
Problem with emojis (unicode)? Might be yt-dlp issue

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#318]
So I've noticed that when a video has an emoji in it (might be all unicode characters?) that it doesn't get properly recorded in tartube.

Let's use this video as an example:
https://www.youtube.com/watch?v=LLeAWuRbObQ

Title:
`US Women's Soccer Equal Pay Claims vs Facts. Court says they got paid more than the Men. 😲`

Here's the console output:
`
[Merger] Merging formats into "Nate The Lawyer - (20210328) - US Women's Soccer Equal Pay Claims vs Facts.  Court says they got paid more than the Men.  - LLeAWuRbObQ - [244+251#480p].mkv"
`
Notice no emoji listed in the name.

Here's what tartube shows:
![image](https://user-images.githubusercontent.com/16659133/127929945-d023a7db-2a88-4e68-9e69-9b49f55a8466.png)

Here's the filename in the video properties:
`Nate The Lawyer - (20210328) - US Women's Soccer Equal Pay Claims vs Facts.  Court says they got paid more than the Men.  - LLeAWuRbObQ - [244+251#480p].mkv`

Here's the filename in explorer:
`Nate The Lawyer - (20210328) - US Women's Soccer Equal Pay Claims vs Facts.  Court says they got paid more than the Men. 😲 - LLeAWuRbObQ - [244+251#480p]`

So it is missing that emoji in the console output and tartube video properties, but somehow still getting set on the filesystem...

Any thoughts on how to fix this? Should I post it to yt-dlp instead? Let me know! Thanks Axcore!

**Comment by axcore** [comment]
Closed this and several related issues, replacing it with a single issue: https://github.com/axcore/tartube/issues/320
