### ISSUE TITLE
Downloading from specific time range

### ISSUE THREAD

**Issue by ScoobyDoo2021** [axcore/tartube#322]
Just a questions:

1. 
are we able to control downloading from specific time range? 

2.
Also, when I download a VOD, there are situations where it gets divided into multiple parts due to some parts being age restricted or not.

Am I able to choose which parts I want to download? Instead of downloading all the parts. E.g. suppose there are 6 parts. Can I download just "part 3"?

**Comment by axcore** [comment]
>are we able to control downloading from specific time range?

First install the latest Tartube release, v2.3.306, and make sure FFmpeg is installed on your system.

Then read [this](https://github.com/axcore/tartube#video-clips) and [this](https://github.com/axcore/tartube#video-slices).

The short answer to your question is, right-click the video and select **Special > Download video clip...**

**Comment by axcore** [comment]
>Also, when I download a VOD, there are situations where it gets divided into multiple parts due to some parts being age restricted or not.

I have never used VOD so I don't know anything about it. If you like, you can download a single video, then show me the text in the **Output** tab

**Comment by ScoobyDoo2021** [comment]
With regard to VOD, this is a video from a livestream site like Twitch but it is called Afreecatv.
(When the streamer drinks alcohol or smokes, they must add "age restriction" during the stream)

https://vod.afreecatv.com/PLAYER/STATION/73721270
This link above is a video replay (VOD) of a previous live stream (just using an example)

The video is 39:36 in length (39 minutes 36 seconds)

If I use Tartube, it will download the video into 3 parts:

00:00 - 01:24 the streamer is just talking (part 1 gets downloaded in full)
01:24 - 38:22 the streamer puts "age restriction" to the stream due to smoking. This part (Part 2 in Tartube) does not get downloaded
38.22 - 39:36 the streamer removes the "age restriction" (part 3 gets downloaded in full)

Just wondering if its possible to download part 2, the age restricted part. If not, no issues at all :)

[eg.xlsx](https://github.com/axcore/tartube/files/6943628/eg.xlsx)
![2021-08-06_16h46_12](https://user-images.githubusercontent.com/77477008/128469185-d10eb041-36c8-41dd-8b88-9a3f789f5c58.png)

**Comment by axcore** [comment]
I downloaded the videos and the same thing happened: part 1 and part 3 download, but part 2 does not.

As I understand, you asked two questions:

1. Can I download the age-restricted video, part 2?

Maybe you can. You have to create a cookies file, containing a username/password for the website. [This page](https://www.reddit.com/r/youtubedl/wiki/cookies) explains how to do it

In Tartube, you can specify the location of the cookie file in **Edit > General download options... > Files > Cookies**

2. If there are six parts, can I automatically download only the age-restricted parts?

I can't think of any way. In youtube-dl, there is an option **--abort-on-error** but there is no option **--abort-unless-error**. 

Of course, in Tartube you can check the video first, then right-click only the video you want to download, but I think that was not your question.

**Comment by ScoobyDoo2021** [comment]
> Of course, in Tartube you can check the video first, then right-click only the video you want to download, but I think that was not your question.

Just want to check, are you referring to "Special > Download video clip"?

Or are you referring to something different?
