### ISSUE TITLE
youtube-dl compitbility

### ISSUE THREAD

**Issue by mbnoimi** [axcore/tartube#33]
Hi,

I downloaded a full youtube channel using `youtube-dl` but when I tried to use `Tartube` for continue downloading the new videos it started from the beginning because it doesn't call `youtube-dl` with `--continue` argument.

How can I fix this issue?

* Tartube: v1.3.007
* Linux mint 19.3 xfce

**Comment by mbnoimi** [comment]
BTW, Adding `--continue`as extra argument in download option doesn't affect on the result of the download process (Tartube ignore it completely)

![image](https://user-images.githubusercontent.com/284547/71908275-b88b5200-317e-11ea-9d45-5b267e28c37d.png)

**Comment by axcore** [comment]
I don't quite understand your problem. Let's see if we can clarify it.

I checked the [youtube-dl documentation ](https://github.com/ytdl-org/youtube-dl/). It says that downloads are automatically resumed, if possible. 

The --continue option does not apply to channels. If you download a channel, wait six months, then download the channel again, old videos are not re-downloaded. youtube-dl always checks that the video exists. If it already exists, youtube-dl won't re-download it.

However, if you download a channel (specifying .mkv format), and then download the channel again (specifying .mp4 format), then youtube-dl replaces the .mkv format videos with .mp4 videos.

So, that is the first thing to check: if youtube-dl originally downloaded .mp4 videos, make sure that Tartube is also downloading .mp4 videos.

**Comment by mbnoimi** [comment]
Thanks. I got it.
