### ISSUE TITLE
Downloaded an entire YT page only to find that none of the files had any audio?

### ISSUE THREAD

**Issue by GrandizerGo** [axcore/tartube#333]
Probably some setting set wrong on my end, any help is appreciated.
I also swore that I told it to save the files to a specific folder but it instead dumped them all into the Unsorted Videos folder. :(

**Comment by GrandizerGo** [comment]
It is installed, in fact I had it installed for other Python software I use so was surprised that when this program wanted it installed it acted as if it was not already installed and installed it again.

**Comment by axcore** [comment]
Tartube is running under a virtual environment, so your usual FFmpeg installation won't work. This is the only way to get Gtk libraries working on MS Windows.

Regarding your general problems, you can try giving me the URL of a video that downloads without sound, and then show me the contents on Tartube's Output Tab. But I'm away from my desk for several weeks, so it will be some time before I can do any testing.

**Comment by axcore** [comment]
Closed for inactivity.
