### ISSUE TITLE
[YT-DLP] No Audio in videos and no metadata in videos, works in normal YT-DL

### ISSUE THREAD

**Issue by MavisCelus19201** [axcore/tartube#336]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Manjaro Linux 5.10

### What version of Tartube are you using?
v2.3.345, updated via pip3 install --upgrade

### What happens when you run Tartube from a terminal window?
https://privatebin.rinuploads.org/?c712f760f42a89e2#CLnawi1qYfPDFvF9hVGOdr4AF1aLnwGtrTs0eLPNzjc=

Steps Taken:

Updated Tartube and Youtube DLP, confirming both were on the latest versions (didn't fix it)
Reset download options (didn't work)
Checked the advanced tab of YT-DLP to adjust audio and video settings (Nothing)
Checked if I had YT-DLP installed and that it and FFMPEG were detected (both were detected and worked when I used the Test Downloader)

Test Downloader output
https://privatebin.rinuploads.org/?cf613aad8fba073a#rPKEiytF81GFG8DI7SaXQ6ZRGpJ7qXhGI70sINautAo=

###If your bug report is "I can't download this video", please provide a link to the video
This will save a lot of time!

https://www.youtube.com/watch?v=XjEQ4ocQDV0
This happens with every video I try but here's a test one I've been using.

###Description

Whenever I try downloading videos using the YT-DLP fork on Tartube, videos download but they don't have the descriptions or anything in the metadata, just the url. Not only that but now if I download a video, it has no audio whatsoever, at least as a .mp4 file, the audio only m4a has audio but no metadata.

This also ONLY happens with YT-DLP, normal Youtube-DL itself works as normal, audio and metadata and all. It's only DLP that's giving me issues.

These are my current paremeters though removing some of those didn't do much, even doing it with no parameters at all, which also still ended with no audio.

"--embed-metadata --embed-subs --write-description --sub-langs all"

I uninstalled and reinstalled both Tartube and YT-DLP but that didn't fix it, checking the output tab didn't show anything peculiar, neither did resetting options. The Error window shows this

""shows "#404 unrecognized property name "move_description" "shows "#404 unrecognized property name "move_info" "shows "#404 unrecognized property name "move_annotations" "shows "#404 unrecognized property name "move_thumbnail""

##Screenshots

https://user-images.githubusercontent.com/73338735/131218064-ea0870f3-7863-45a2-b3e4-8761ea706e7d.png

**Comment by axcore** [comment]
I tested the [video](https://www.youtube.com/watch?v=XjEQ4ocQDV0) both in Tartube, and with yt-dlp directly, using the same download options you use in your screenshot.

The results were identical. The video had audio. I did not see embedded metadata or subtitles, but perhaps I'm not using the right media player for that.

Because the results are identical, the lack of audio was presumably a yt-dlp issue that has since been fixed. Apologies that I didn't get to your post earlier, but I had been without internet since last summer.
