### ISSUE TITLE
Keep getting this error

### ISSUE THREAD

**Issue by Shippou5** [axcore/tartube#337]
https://puu.sh/IhygG/d04f125f02.png

Windows 10

v2.3.332

### What happens when you run Tartube from a terminal window?
https://puu.sh/Ihyia/ed4d0542b8.png

https://youtu.be/kzdJkT4kp-A

**Comment by axcore** [comment]
Look in the data folder (where videos are downloaded)

There should be two files there, **tartube.db** and **tartube.db.lock**. Try deleting **tartube.db.lock** (do NOT delete **tartube.db**).

**Comment by axcore** [comment]
You chose the location of the folder when you first ran Tartube.

To see it again, in Tartube's main window click **Files > Database preferences...**, then look in the box marked **Tartube data folder**.

**Comment by axcore** [comment]
Issue closed as the puu.sh links are unreadable. If you're still having the same problem, feel free to re-open the issue.

**Comment by ErikUden** [comment]
I got the error: "Failed to load the Tartube database file"

I tried the following: 

https://www.diskpart.com/windows-7/external-hard-drive-read-only-in-windows-7-0310.html

Essentially, the disk was read-only for some reason. I do not know why this happened to me. Moments before this my external HDD which holds my Tartube data folder was not accessible at all, I did some fix (it had a power issue) and then afterwards it was set to read-only. That was the error Tartube was responding to!

Step 1: Search for "DiskPart" on Windows and click "Run as administrator"
*a command line interface will open with the words "DISKPART>" written as your input*

Step 2: type "`list disk`"
*this will list all the disks your PC has access to, internal and external*

Step 3: Find your disk
*You should check which disk is the one you wish to fix, it is the one that holds the Tartube data folder. You can determine which disk is the one you want through determining factors like storage size or if that doesn't make it you need to go to "Create and format hard disk partitions" in the control panel to see which storage is which.

Step 4: Type `select disk [number]`
*You found out which disk was yours, select it!*

Step 5: Type `attributes disk clear readonly`
*You wish to remove the attribute "readonly" from the disk, typing this will solve all issues*
This should warrant the response: `Disk attributes cleared successfully`

Afterwards, if this was your issue, you should be able to launch Tartube like nothing happened.

Hope this helps!
