### ISSUE TITLE
Tartube is providing me with yet more errors

### ISSUE THREAD

**Issue by Shippou5** [axcore/tartube#338]
https://puu.sh/IhXrU/a1c59f9dc5.png

Windows 10

v2.3.332

### What happens when you run Tartube from a terminal window?
https://puu.sh/IhXud/1f75813876.png

https://youtu.be/_LccdxgKho0

**Comment by Shippou5** [comment]
> The usual reason for the the "download did not start" error is that Tartube can't find youtube-dl or yt-dlp. Try this in the first instance:
> 
> [Tartube FAQ](https://github.com/axcore/tartube#73-download-did-not-start-error)

Tried to modify Tartube's settings as per instructions with no success, do I need to ask the authors for help?

**Comment by Shippou5** [comment]
> Sorry. I amended my initial reply to remove the link to the FAQ, which is not relevant for MS Windows users, but apparently the edit didn't get saved.
> 
> The edit said: please try re-installing youtube-dl or yt-dlp first.
> 
> Failing that, can you please open the window **Edit > System preferences**, then show me a screenshot (or describe) the tabs **Downloaders > Forks** and **Downloaders > File paths**

I would love to re-install them! How do I do that? I do not actually recall ever installing them to begin-with, just downloaded tartube

**Comment by axcore** [comment]
>Download starts but then fails, maybe there is some kind of order-of-operations glitch in the GUI, and that the control for enabling the '-x' setting became glitched.

Download options can be specified in any order, except that if you specify the same option multiple times (**-f avi -f mp4** or something like that), the last one is used.

**Comment by Shippou5** [comment]
> > I would love to re-install them! How do I do that? I do not actually recall ever installing them to begin-with, just downloaded tartube
> 
> **Operations > Update youtube-dl** or **Operations > Update yt-dlp**
> 
> When you first run Tartube, you get prompted to install one of them, which is probably what you did

https://puu.sh/IihZb/583ed944b3.png

**Comment by axcore** [comment]
I am back at my desk, but the puu.sh links are invalid. I will look into it, if you can replace them.

**Comment by axcore** [comment]
Closed for inactivity. Feel free to re-open if you like.
