### ISSUE TITLE
Adding specific formats to download for each video

### ISSUE THREAD

**Issue by stillpointx** [axcore/tartube#339]
Is there a way to select specific formats to download or each individual video like in the old youtube-dlg
I would like to add options like 480p for certain videos.

I'm using Tartube V2.3.345 on Ubuntu 20.04

Example:
![screenshot-2021-10-16-13-04-59](https://user-images.githubusercontent.com/28985314/137596130-89640508-9bba-4512-b927-0b39d38eaa64.png)

**Comment by axcore** [comment]
A resolution selector was added to the Classic Mode tab in v2.3.484.
