### ISSUE TITLE
why does auto-resume download not work when using --concurrent-fragments

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#341]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
If using MS Windows, are you using Windows 10, Windows 7, or something else?
Windows 7
### What version of Tartube are you using?
In Tartube's main window, click Help > About
v2.3.332
### What happens when you run Tartube from a terminal window?
ERROR: unable to download video data: [WinError 2] The system cannot find the file specified: '.part-Frag162.part'

**Comment by candrapersada** [comment]
https://www.youtube.com/playlist?list=PL8gtB5P9cW5U1IdijzJeRZvRTf_UOaiOU

**Comment by axcore** [comment]
Ok thanks.

I have no internet until January, so I can't test anything at the moment.

**Comment by candrapersada** [comment]
> If the video stalls, you can already restart it. I added a maximum number of restarts, so the download will eventually finish. Edit > System preferences > Operations > Downloads
> ![image](https://user-images.githubusercontent.com/36833664/137682191-49e5c8ce-a7dc-4c91-abb6-15ccb623c339.png)
https://github.com/axcore/tartube/issues/174#issuecomment-724836259

but why not working for 
`ERROR: unable to download video data: [WinError 2] The system cannot find the file specified: '.part-Frag162.part'`

**Comment by axcore** [comment]
As I mentioned in another issue, auto-resume has been fixed.
