### ISSUE TITLE
Tartube doesn't let me download video what do I do?

### ISSUE THREAD

**Issue by Shippou5** [axcore/tartube#346]
https://puu.sh/IlzVM/699055edbc.png

Here is the error log

**Comment by Shippou5** [comment]
> Have you installed FFmpeg via Tartube's main menu (**Operations > Insall FFmpeg**) ?

https://puu.sh/IlL9Q/9c304b8651.png

Installation complete

https://puu.sh/IlLaL/30d19683eb.png

Download still getting errors, I tried changing "download in this format" to "convert to this format using FFMPEG", I also tried to update yt-dlp and tried a different downloader

**Comment by axcore** [comment]
Try deleting the whole Tartube installation folder, which by default is **C:\Users\YOURNAME\AppData\Local\Tartube**, then install Tartube, yt-dlp and ffmpeg again.

This might not sound like a viable solution, but for some reason FFmpeg installation is unreliable and sometimes invalidates itself.

**Comment by Shippou5** [comment]
Figured out the issue, if I try to download as mp3 everything bugs out until tartube is closed down
If I try to convert to mp3 before downloading as mp3 everything is a-ok!
