### ISSUE TITLE
MacOS - When I run "python3 tartube/tartube" I get a black "Tartube setup" screen

### ISSUE THREAD

**Issue by ffroze** [axcore/tartube#348]
When trying to install and setup on MacOS (the newest version on a MacBook 16 M1 Pro), and I type "python3 tartube/tartube" it opens up to a thing that said Tartube Setup but it was just a black screen. I have no experience coding or knowing any languages so I have no idea what to do.

**Comment by axcore** [comment]
My apologies, I have never used a Mac so there is little I can do to help.

**Comment by axcore** [comment]
All macOS installation problems have been consolidated into one issue, #393.
