### ISSUE TITLE
Drag & drop support

### ISSUE THREAD

**Issue by mbnoimi** [axcore/tartube#35]
Hi,

I suggest to add support for drag & drop which load `Videos` window and paste the link automatically.

**Comment by axcore** [comment]
Added in v1.3.042, but it doesn't work consistently. I have [asked for help](https://stackoverflow.com/questions/59750800/drag-and-drop-youtube-videos-into-python-gtk-window) with this issue.

**Comment by mbnoimi** [comment]
Unfortunately I'm C++/Qt guy I with to a get help soon.

**Comment by axcore** [comment]
Fully working in v1.3.077, on Linux/BSD.

Gtk applications on MS Windows do not support drag and drop. There is nothing I can do about this.

**Comment by mbnoimi** [comment]
Works like a charm.
Thanks @axcore
