### ISSUE TITLE
"...following videos are duplicates" menu lacks a scroll bar. List Size > Screen Size; Window is taller than screen.

### ISSUE THREAD

**Issue by c6670701** [axcore/tartube#351]
### What operating system are you using?
Windows 10

### What version of Tartube are you using?
2.3.332

### What happens when you run Tartube from a terminal window?
NA

### Problem:
1. I have a list of 30 videos as individual URL's.
2. I copy the list of 30 videos into "Add new video(s)".
3. I have all videos download successfully.
4. I copy the same set of 30 videos into "Add new video(s)".
5. The menu that says "the following videos are duplicates" is longer than my screen. I see no scroll bar on the menu.

Can't access buttons at the end of the message.

Post Note: This is my first GitHub Bug Report. Please forgive any errors.

**Comment by axcore** [comment]
Ok thanks, I'll fix that.

**Comment by trimechee** [comment]
I juste discovered this wonderful marvelous software gem of technology and I wanted to thank you very much for this amazing incredible software !

I will submit it to the videhelp site in sha Allah :)

**Comment by axcore** [comment]
Fixed in v2.3.447.

**Comment by trimechee** [comment]
Thank you !
