### ISSUE TITLE
Replace hooktube with piped links

### ISSUE THREAD

**Issue by iamtherobin** [axcore/tartube#353]
Does hooktube even work anymore? I haven't been able to play a video on it in a long time.

Why not replace the Hooktube link with a Piped link? Piped is a new front end for youtube and I have had better reliability and performance with the piped instance than any invidious instance.

Try the piped instance here:
https://piped.kavin.rocks/

**Comment by axcore** [comment]
>Does hooktube even work anymore? I haven't been able to play a video on it in a long time.

The original HookTube is long dead, but there are many mirrors available. If the mirror you're using stops working, you can switch to a different one. See [here](https://github.com/axcore/tartube#6133-diverting-to-hooktube--invidious) for more details.

>Why not replace the Hooktube link with a Piped link?

That should already be possible, you can redirect the HookTube buttons to any website (as explained in the link above). Try that and see if it works.
