### ISSUE TITLE
Tartube on OS X 10.9 Mavericks in 2021

### ISSUE THREAD

**Issue by spyderrp7** [axcore/tartube#354]
Is it possible to run Tartube on Mac OS X 10.9?

I read the installation guide, but I can't install homebrew.
I tried the command:

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

This command gets the error "Your OS X version is too old."

Which makes sense, since the last version of Homebrew that supports OS X Mavericks is 2.3.0.

At the moment the current version of Homebrew is 3.3.0. How can I install homebrew 2.3.0 which is compatible with OS X 10.9 Mavericks?

**Comment by axcore** [comment]
I have never used a Mac, so there may be little I can do to help you.

**Comment by axcore** [comment]
All macOS installation problems have been consolidated into one issue, #393.
