### ISSUE TITLE
Feature Request: Dark Mode on Windows:

### ISSUE THREAD

**Issue by SaintFenix** [axcore/tartube#355]
Hello,

I'm unsure if the feature already exists on other OS's so I'll limit the scale of the request only to the OS I'm using it on.

However I'd like to request a dark mode for Tartube on Windows. Currently it's the only program I use that doesn't have a dark mode on Windows, and I'm roughly reminded that whenever I open it specifically at night.

I'd very much appreciate anyone giving any consideration to this. 

thank you,

(P.S. was a huge Youtube-dlg guy for awhile, but Tartube is next level, thank everyone who's contributed to it so much! I love it!)

-Fenix

**Comment by axcore** [comment]
I would like to add dark mode on MS Windows, but I don't know how, and my pleas for help have gone unanswered.

**Comment by Rukongai** [comment]
Hey!

I couldn't get the default Adwaita dark mode working, but this works! Find a gtk3 dark theme you like. I used [this Windows 10 dark theme recommended by the GTK Project](https://github.com/B00merang-Project/Windows-10-Dark)

- Download it
- Extract
- grab the contents of the gtk-3.2 folder and copy them to `tartube\mingw64\share\themes\Windows10\gtk-3.0\`
- Create a folder called etc in mingw64 folder
- In there, create a folder called gtk-3.0
- In there, create  a file called settings.ini
- In settings.ini add the following 

`[Settings]
gtk-theme-name=Windows10
`

Replacing Windows10 with whichever theme you found and downloaded.

**Comment by axcore** [comment]
Oh, it needs to be

`[Settings]
gtk-theme-name=win32`

**Comment by axcore** [comment]
Splendid, I can't auto-detect dark-ish themes on the Windows desktop, but in the next release the user will be able to switch between themes, and even add their own ones.

![darktheme](https://user-images.githubusercontent.com/37951926/203600464-17eee76c-b7ed-4aa1-8544-d657657cb3ce.png)

**Comment by SaintFenix** [comment]
Wow, thank you guys so much for the work on this, I still love and use Tartube frequently and seeing this update in my inbox is just the highlight of today.

Thank you!

feel free to close this out. :)

**Comment by axcore** [comment]
Added in v2.6.165.

**Comment by Rukongai** [comment]
Hey sorry - busy recently

Yeah I believe there are ways to set gtk themes on a system level, but this seemed the most straight forward. I am pretty sure GTK can't detect system theme on windows, but I don't know if that limitation is exclusive to version 3 and below, or if all GTK can't.

Also - I spent several hours the other day trying to figure out how to apply the theme to the header bar, but doesn't seem possible as far as I can tell. 

Anyway - super stoked this made it into a build so fast. Happy thanksgiving if that's your thing!

**Comment by axcore** [comment]
I think the theme itself doesn't matter, the contrast between dark and light is what matters.

For anyone who might be interested - if new themes are installed, Tartube can add them to its dialogue window. See the README for more details.
