### ISSUE TITLE
Lots of errors

### ISSUE THREAD

**Issue by francois072** [axcore/tartube#357]
Thanks for taking the time to submit a bug report! Please include the following information:

Manjaro

v2.3.332

I am getting a bunch of errors from Tartube.

`[youtube] vtSA6ep_zTE: Downloading android player API JSON (retry #1)`
`[youtube] vtSA6ep_zTE: Downloading initial data API JSON (retry #2)`
`WARNING: [youtube] Unable to download webpage: <urlopen error _ssl.c:1112: The handshake operation timed out>`
`WARNING: [youtube] <urlopen error _ssl.c:1112: The handshake operation timed out>. Retrying ...`
`WARNING: [youtube] Failed to download MPD manifest: <urlopen error _ssl.c:1112: The handshake operation timed out>`
`WARNING: [youtube] <urlopen error _ssl.c:1112: The handshake operation timed out>. Retrying ...`
`WARNING: [youtube] <urlopen error _ssl.c:1112: The handshake operation timed out>. Retrying ...`
`WARNING: [youtube] <urlopen error _ssl.c:1112: The handshake operation timed out>. Retrying ...`
`WARNING: [youtube] Unable to download API page: <urlopen error _ssl.c:1112: The handshake operation timed out> (caused by URLError(timeout('_ssl.c:1112: The handshake operation timed out')))`
`ERROR: local variable 'contents' referenced before assignment`

I have no idea why I'm getting these errors.

**Comment by axcore** [comment]
From [this thread](https://github.com/ytdl-org/youtube-dl/issues/27793), it seems to be a youtube-dl issue. 

Make sure you are using yt-dlp, not youtube-dl, as the latter hasn't been updated for a while.

**Comment by francois072** [comment]
> From [this thread](https://github.com/ytdl-org/youtube-dl/issues/27793), it seems to be a youtube-dl issue.
> 
> Make sure you are using yt-dlp, not youtube-dl, as the latter hasn't been updated for a while.

I am currently using yt-dlp.
