### ISSUE TITLE
Skip finished live streams

### ISSUE THREAD

**Issue by francois072** [axcore/tartube#358]
How can I skip downloading a live stream that has already finished?

**Comment by axcore** [comment]
I'm not sure that the metadata for each video mentions that the video was a livestream, now finished. I can check that, when I get my internet back in January.

If you're talking about videos that Tartube has already detected as being livestreams, then that would be fairly simple check to perform, but the code doesn't do that at the moment.

**Comment by axcore** [comment]
In v2.3.518, you can use custom downloads to skip livestreams (current and finished), or to download ONLY livestreams (current and finished). 

For example, click **Edit > System preferences... > Operations > Custom**, click a custom download to select it, click the **Edit** button. In the new window, enable the settings in the **Hint** box, then click the **Livestreams** tab.

![Screenshot from 2022-04-05 17-28-16](https://user-images.githubusercontent.com/37951926/161801691-66678320-77b7-41a4-ab0e-e13bd7964810.png)

For more information about custom downloads, see [here](https://github.com/axcore/tartube#custom-downloads).

In the Videos tab, videos that are finished livestreams have a different icon.
