### ISSUE TITLE
Is the same video downloaded when it is auto deleted?

### ISSUE THREAD

**Issue by francois072** [axcore/tartube#359]
I have setup Syncthing to `Send Only` Tartube's downloaded videos to my phone.
Tartube's `Start downloading playlist from index` and `Stop downloading playlist from index` are both set to 1.
Tartube's `Automatically delete downloaded videos after this many days` is set to 3 days.

Now I would like to know if Tartube will download the same video again after all videos have been deleted after 3 days and there is no new upload at the next download operation?

**Comment by axcore** [comment]
youtube-dl will not re-download a video, if it already exists (in the same folder).

If you move the video from its folder, youtube-dl will download it again.

To prevent this, you can tell youtube-dl to remember the videos it has downloaded, so it does not download them again (even if the video has been moved). Edit > System preferences > Operations > Downloads, and select "Allow downloader to create its own archive file"

**Comment by axcore** [comment]
A better way to reduce the number of videos downloaded is in Edit > System preferences > Operations > Performance.

In the "Time-saving settings" section, select the button "Stop downloading a channel/playlist when it starts sending videos you already have". Then add numbers below, I find that 3 is a good number.

**Comment by francois072** [comment]
> Performance

That tab doesn't exist for me.
I'm using yt-dlp.

**Comment by axcore** [comment]
Apologies, I looked it up on an old version of Tartube. In v2.3.351 it's in Edit > System preferences... > Operations > Stop

**Comment by francois072** [comment]
Thank you. I also saw the downloaded video history that makes sure the video isn't downloaded again when auto deleted.
