### ISSUE TITLE
Default videos folder

### ISSUE THREAD

**Issue by mbnoimi** [axcore/tartube#36]
I suggest to set the default folder of the videos depending on the selected folder in `Folders` tree.

Ex. As shown in the screenshot below I expect `Tartube` to set the default folder as `Documentary` instead of `Unsorted Videos` because I already selected `Documentary` from the folders tree (you can make `Unsorted Videos` is the default folder in case the user doesn't select any folder)

![image](https://user-images.githubusercontent.com/284547/71782595-f9536180-2fec-11ea-95a0-70639881b81e.png)

**Comment by axcore** [comment]
Added in v1.3.042

**Comment by mbnoimi** [comment]
Doesn't work fine (it seems folder index is incorrect) see the screencast please:
![Peek 2020-01-21 12-50](https://user-images.githubusercontent.com/284547/72794327-e4153e80-3c4c-11ea-9a17-e088978c56a9.gif)

**Comment by mbnoimi** [comment]
I prefer to open this issue.

**Comment by axcore** [comment]
It's a one line fix, if you want to edit **tartube/mainwin.p**y yourself.

Lines 10544-10548 look like this:

`        self.folder_list.sort()            
        self.folder_list.insert(0, main_win_obj.app_obj.fixed_misc_folder.name)
        self.folder_list.insert(1, main_win_obj.app_obj.fixed_temp_folder.name)
        if folder_obj:
            self.folder_list.insert(0, folder_obj.name)`

Add a single line of code after that. The new line must have exactly 8 space characters at the beginning.

`        self.folder_list.sort()            
        self.folder_list.insert(0, main_win_obj.app_obj.fixed_misc_folder.name)
        self.folder_list.insert(1, main_win_obj.app_obj.fixed_temp_folder.name)
        if folder_obj:
            self.folder_list.insert(0, folder_obj.name)
        self.parent_name = self.folder_list[0]`

**Comment by mbnoimi** [comment]
I did it, it doesn't fix the bug!
May you please post the commit.
![image](https://user-images.githubusercontent.com/284547/72930404-ea024100-3d6c-11ea-8820-4c3929c8375c.png)

**Comment by axcore** [comment]
There are 12 characters at the beginning of the line. There must be exactly 8.

I will commit when I am at my desk, some time tomorrow :)

**Comment by mbnoimi** [comment]
Didn't affect too
![image](https://user-images.githubusercontent.com/284547/72930674-83c9ee00-3d6d-11ea-9631-cc72ecad4516.png)
I prefer get the modifications from you.

**Comment by axcore** [comment]
Added in v1.3.048. I won't close the issue until you confirm it's working.

**Comment by mbnoimi** [comment]
> Added in v1.3.048. I won't close the issue until you confirm it's working.

The bug still occurs

**Comment by axcore** [comment]
>The bug still occurs

I think I have fixed the wrong bug. I just noticed this one:

1. Clean installation of Tartube
2. Create a folder called "test1"
3. Create another folder called "test2". The dialogue window says this folder will be created inside test1, but the new folder is not created there

Is that the problem you are experiencing?

**Comment by axcore** [comment]
Fixed in v1.3.053.

**Comment by mbnoimi** [comment]
Thanks @axcore 
It works fine
