### ISSUE TITLE
Video size limit option not applied

### ISSUE THREAD

**Issue by francois072** [axcore/tartube#363]
Even though the video size limit is set to 300MB a video of 2.8GB will still be downloaded.
I did use custom download options.

**Comment by axcore** [comment]
Give me the URL of the video you tried to downloaded, and a screenshot or copy/paste of the yellow text in the Output Tab

**Comment by francois072** [comment]
/usr/bin/yt-dlp --newline -i --playlist-end 1 --max-filesize 300m --hls-prefer-native --cookies /run/media/francois/Storage/Downloads/Tartube/cookies.txt -f 135+139+mp4 --merge-output-format mp4 --skip-playlist-after-errors 3 --embed-metadata --reject-title LIVE --output /run/media/francois/Storage/Downloads/Tartube/Francois & Zandré/channel_106/%(title)s.%(ext)s --dump-json --download-archive /run/media/francois/Storage/Downloads/Tartube/Francois & Zandré/channel_106/ytdl-archive.txt --ffmpeg-location /usr/bin/ffmpeg https://www.youtube.com/c/GameTheorists

The video being downloaded.
https://www.youtube.com/watch?v=5TVJPh_hrIU

Tartube is set to download the lastest video on the channel, but to skip if the video size is over 300MB.

**Comment by axcore** [comment]
>-f 135+139+mp4 

There's your problem. In **Edit > General download option... > Formats** you have selected format 135, which is 480p and 3.1GB, and format 139, in which this video isn't available. 

Some of youtube-dl's options are contradictory, so you have to be careful not to select too many of them.

**Comment by francois072** [comment]
How do I then prevent videos that are over 300MM's from being downloaded?

**Comment by axcore** [comment]
I suggest removing 135 and 139 from your **List of preferred formats**.

By the way, if you right-click the video and select **Fetch > Available formats**, you can see that this video is not available in less than 300 MB. (Even the audio is 250MB)

**Comment by axcore** [comment]
Understood. Here is the problem: youtube-dl tries to download the best possible video. If you say "Download resolution 480p but don't download more than 300MB", youtube-dl thinks the best possible video is 480p, so it downloads that and it ignores the "don't download more than 300MB" part.

**Comment by francois072** [comment]
Would there be any easy workaround?

**Comment by axcore** [comment]
I don't know. I am actually not any kind of expert on youtube-dl and video formats. You could try [reddit](https://www.reddit.com/r/youtubedl/), because there are a few experts there.

**Comment by francois072** [comment]
I'll try that and see what I find.

**Comment by francois072** [comment]
https://www.reddit.com/r/youtubedl/comments/r7d4qk/comment/hmynlmp/?utm_source=share&utm_medium=web2x&context=3

No idea how to apply this in Tartube.

**Comment by axcore** [comment]
Open **Edit > General download options...**, and in the first tab there's a box **Extra command line options**.

You can add any options you like there, for example **-f bestvideo[height<=480][filesize<=300M]+bestaudio**

**Comment by francois072** [comment]
139 m4a  audio only     |  202.52MiB   48k https |                   mp4a.40.5  48k 22050Hz low, m4a_dash
135 mp4  854x480     30 |  3.10GiB    763k https | avc1.4d401f  763k                        480p, mp4_dash

Would it be possible to combine these two file sizes and skip the download if it exceedes the maximum video size limit instead of relying on the download aborting once 300MB have already been downloaded?

**Comment by axcore** [comment]
Closed for inactivity.
