### ISSUE TITLE
Not start at user while workin by the root

### ISSUE THREAD

**Issue by rimsky57** [axcore/tartube#366]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
uname -ars
Linux rimsky-n5005 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
cat /etc/*rel*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### What version of Tartube are you using?
v2.3.332

### What happens when you run Tartube from a terminal window?
rimskya@rimsky-n5005:~$ tartube
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 2862, in do_activate
    self.start()
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 3033, in start
    new_config_flag = self.load_config()
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 4348, in load_config
    self.data_dir = self.data_dir_alt_list[0]
IndexError: list index out of range

__________

Wheres is data and config files are located? ~/tartube-data already removed
How to purge tartube comletely from the OS?

**Comment by axcore** [comment]
>How to purge tartube comletely from the OS?

How did you install Tartube on your OS? I cannot guess, you have to tell me.

>Wheres is data and config files are located?

The config file is in the normal place for the operating system. I don't have Ubuntu, but on Linux Mint it is /home/NAME/.config/tartube/settings.json.

**Comment by rimsky57** [comment]
> How did you install Tartube on your OS? I cannot guess, you have to tell me.

_dpkg -i python3-tartube.deb_

> The config file is in the normal place for the operating system. I don't have Ubuntu, but on Linux Mint it is /home/NAME/.config/tartube/settings.json.

so simple
_lsof | grep tartube_ 
dont show _~/.config/tartube/settings.json_, but only _~/tartube-data_, so i sured that all settings in  _~/tartube-data_, nothing else
So I delete them - and nothing have changed.
I delete througth dpkg
_dpkg -r  python3-tartube.deb_
and
_dpkg --purge  python3-tartube.deb_
And nothing have changed.

**Comment by axcore** [comment]
Apologies, I don't have a computer until January, so I cannot do any testing.

I suggest that you edit **/usr/lib/python3/dist-packages/tartube/mainapp.py** to insert this at line #3644:

`        print(config_file_path)
`
This line must start with exactly 8 space characters (not tabs).

![insert](https://user-images.githubusercontent.com/37951926/144799485-87653a1f-55cf-49e0-80f4-91488e6e2b9e.png)

**Comment by axcore** [comment]
If you want to fix the bug, you can edit mainapp.py and change line 4348:

`        if self.data_dir_use_first_flag:
`
Change it to this:

`        if self.data_dir_use_first_flag and self.data_dir_alt_list:
`

Again, the line must begin with exactly 8 space characters.

**Comment by axcore** [comment]
Fixed in v2.3.518.
