### ISSUE TITLE
Enable automatic copy/paste on Fedora Linux

### ISSUE THREAD

**Issue by uhhmeeyell** [axcore/tartube#367]
I am unable to automatically apply the links I copy in my clipboard in Fedora Linux to the Add videos window (with Enable automatic copy/paste activated). This feature has worked on other Linux distributions and I would like to know if there is some setting I missed or workaround for this.

**Comment by axcore** [comment]
I'm away from my desk for a couple more months, so it will be some time before I can do any testing.

**Comment by axcore** [comment]
I had a chance to test this today, On Fedora Workstation 35, it seems to be working as expected:

![fedora](https://user-images.githubusercontent.com/37951926/161918860-ee866bb3-cc70-44a5-bc3b-695524254d77.png)

If you are still having the same problem, try running Tartube inside a terminal window, so we can see any error messages that are being produced.

**Comment by uhhmeeyell** [comment]
Thank you for checking axcore. My Add videos does not populate even if the link is stored in the clipboard until I select the Tartube application. I have to switch from browser to tartube back and forth for video links to populate.

**Comment by axcore** [comment]
Run Tartube in a browser window. There might be python errors that we're not seeing.

**Comment by axcore** [comment]
Closed for inactivity.
