### ISSUE TITLE
Already downloaded file prompt

### ISSUE THREAD

**Issue by alidan** [axcore/tartube#368]
Ok this one I think may be simple. the message that pops up if I try to download something that was already downloaded is this
![python3_2022-01-01_10-10-55](https://user-images.githubusercontent.com/2681758/147854838-3d0396c6-497e-4c11-9b52-9e57acbbbd25.png)
This to me look like an error/the program did not get anything from the page submitted, as in if youtube changed something and ytdlp was out of date I would see this message

is there a way to have a seperate message pop up in cases like this that says something like 'it looks like this file was already downloaded' rather than a popup that looks like something should have happened.

and on the topic of already downloaded, I think I asked about something like this in the past, but now I have a use case for it. a while back I mass downloaded a bunch of videos, some of them pulled the high quality video, some of them pulled a 480p at best some are 240p and I think one a few are even lower, so when I eventually redownload them, it would be helpful if if on a 'looks like you already downloaded this' page there was an ability to ignore that and redownload rather than editing a text file to make it forget I downloaded it.

**Comment by axcore** [comment]
>is there a way to have a seperate message pop up in cases like this that says something like 'it looks like this file was already downloaded' rather than a popup that looks like something should have happened.

This popup window is designed for newbies and people who don't understand what a GUI is. Obviously those people never read documentation, so I added this window, because people get confused and upset when nothing happens.

If you are not a clueless newbie, then you should just disable the window using the checkbox.

Your suggestion is not possible, because youtube-dl does not produce separate error/warning messages for individual videos, when downloading a channel/playlist. I asked for that behaviour to be changed and was told to fuck off.

**Comment by axcore** [comment]
>it would be helpful if if on a 'looks like you already downloaded this' page there was an ability to ignore that and redownload rather than editing a text file to make it forget I downloaded it.

I think that if you right-click a video in Tartube's **Videos** tab, and select "Re-download video", the video is re-downloaded even if it appears in youtube-dl's archive file. So it should not be necessary to edit the archive file just to re-download one or two videos.

(I am not at my desk at the moment, let me know if this doesn't actually work.)

**Comment by alidan** [comment]
Ok I thought that error was more your side rather than the script side, given its asking if you updated.

as for the error message itself, kind of need to keep it for the immediate effect of 'something didn't work right' so i'll just treat it as a catch all for now.

**Comment by axcore** [comment]
>Ok I thought that error was more your side rather than the script side, given its asking if you updated.

Sometimes youtube-dl stops working with a website completely, and the only solution is to wait for youtube-dl to be updated.

**Comment by axcore** [comment]
Fixed in v2.3.549. If youtube-dl reports that the video has been downloaded already, or is in the archive file, the dialogue window is not shown.
