### ISSUE TITLE
Some videos don't download (not found/fragment)

### ISSUE THREAD

**Issue by kibbblz** [axcore/tartube#369]
So some videos I get this issue in the output log:

[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 1 of 10) ...

[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 2 of 10) ...

[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 3 of 10) ...

[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 4 of 10) ...

[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 5 of 10) ...

[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 6 of 10) ...

[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 7 of 10) ...

[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 8 of 10) ...

[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 9 of 10) ...

[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 10 of 10) ...

-

I end up with this 100 mb file instead which Im guessing is just the audio. But the other part failed to download, which Im guessing is the video. Is there a way for Tartube to try download in other formats? I used a youtube downloader extension on firefox to download the same video and I could see mp4 or webm. Im guessing Tartube only tried downloading the webm version (I also tried downloading the webm version on Firefox extension but also that failed instantly) so maybe Tartube needs to attempt downloading in the next possible highest quality if webm fails?

**Comment by axcore** [comment]
>Got server HTTP error: HTTP Error 404

Are you using yt-dlp, and not youtube-dl? If you are in fact using yt-dlp, then this is probably a network error.

>Is there a way for Tartube to try download in other formats?

**Edit > General download options... > Formats**. Click a format like **mp4** to select it, then click the **Add format** button. Click **OK** to close the window.

>so maybe Tartube needs to attempt downloading in the next possible highest quality if webm fails?

youtube-dl is doing the downloading, Tartube just provides some useful buttons. If a particular video fails to download, youtube-dl should try to download it again, then next time you download the channel/playlist. Alternatively, in Tartube's main window you can right-click any video with an error icon, and select **Download video**.

**Comment by axcore** [comment]
>Not classic mode, if thats what you meant.

Sorry if I wasn't clear: Classic Mode refers to the Classic Mode tab in the main window. 

>All I know is I really want it to download the highest quality version

Left to its own devices, youtube-dl automatically downloads the highest-quality version.

>This one particular like I mentioned above wouldn't download in Tartube (webm) and I couldn't get it to download the mp4 60fps version.

I can test the link, if you tell me. If you're having problems with a particular video, in Tartube's main window you can right-click the video, then select **Fetch > Available formats**.  Click the **Output** tab to see the results  It is often the case that a video might not be available in the format you're hoping for. Also, there is no guarantee that other downloaders might be converting a low-resolution or low-frame-rate video to a higher resolution of frame rate, and not telling you about it.

>Although the extension I use on Firefox downloads both audio and video then merges them together when done.

For high-resolution videos, YouTube supplies separate audio and video files, so all downloaders have to merge them.

**Comment by kibbblz** [comment]
Thanks for the reply... didn't know about the Fetch option. Also, do you know why some videos are not merging and others are? I had to use mkvtoolnix to merge some of the webm and audio files to get a full mkv video. It doesn't take long at all but I'm wondering why some merge and some don't merge. Thanks again!

**Comment by axcore** [comment]
Again, give me a URL of a video that doesn't work and then I can test that video.

**Comment by axcore** [comment]
In v2.3.393 I adjusted the code so that, after fetching a list of formats, you can click a single button to open the window for changing the media format. That window's layout has been improved to make it clearer which buttons should be clicked.

**Comment by metapea** [comment]
I get this too from time to time, it happen when i download a player list or in a batch.

>Again, give me a URL of a video that doesn't work and then I can test that video.

Most of the errors don't even show the URL if you're downloading it in a batch, maybe show the id (end of the url) of the video when "[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1" is noticed by tartube.

**Comment by axcore** [comment]
>maybe show the id (end of the url) of the video when

youtube-dl error/warning messages often do not contain the URL or video ID. I asked for this to be changed some years ago and was told to fuck off.

**Comment by axcore** [comment]
>youtube-dl error/warning messages often do not contain the URL or video ID. 

This is no longer true, as of v2.3.484.
