### ISSUE TITLE
System tray

### ISSUE THREAD

**Issue by mbnoimi** [axcore/tartube#37]
I suggest to add system tray with an option `Close to tray` instead of direct quit.

**Comment by mbnoimi** [comment]
This feature is vital in case of using scheduled download.
Like this scenario:
I can put Tartube as startup app (which will shown minimized as a tray icon) then it will automatically download videos in background every 2 hours from various channels and playlists.

BTW. Currently I use the same scenario using three apps ([RSS-Bridge](https://github.com/rss-bridge/rss-bridge), [youtube-dl](https://github.com/ytdl-org/youtube-dl) & Cron).
I'll replace these three apps by Tartube but I don't want to see Tartube's window whenever I launch it.

**Comment by axcore** [comment]
Added in v1.3.042
