### ISSUE TITLE
Arch Linux: ModuleNotFoundError: No module named 'mainapp'

### ISSUE THREAD

**Issue by nobicycle** [axcore/tartube#372]
### What operating system are you using?
$ uname -a
Linux tower 5.10.93-1-MANJARO #1 SMP PREEMPT Thu Jan 20 09:46:07 UTC 2022 x86_64 GNU/Linux

$ python -V
Python 3.10.1

### What version of Tartube are you using?
tartube-2.3.332-1 

[user@tower ~]$ python -V
Python 3.10.1

### What happens when you run Tartube from a terminal window?
$ tartube 
Traceback (most recent call last):
  File "/usr/bin/tartube", line 40, in <module>
    import mainapp
ModuleNotFoundError: No module named 'mainapp'

Note: tartube was working in the past. Suspect latest python is incompatible.

**Comment by axcore** [comment]
Thanks for the tip-off. I have no internet at the moment, so it might be some weeks before I can do any testing.

**Comment by axcore** [comment]
Addendum: on most (or all?) Linux systems, you should be able to run Tartube without installing it first: [instructions](https://github.com/axcore/tartube#5310-run-without-installing)

**Comment by nobicycle** [comment]
Thank you
I used the pip method instead of Arch package install.
