### ISSUE TITLE
Bug downloading with yt-dlp release 2022-01-21

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#373]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Win10

### What version of Tartube are you using?
In Tartube's main window, click Help > About
2.3.358

### What happens when you run Tartube from a terminal window?
no errors in terminal

###If your bug report is "I can't download this video", please provide a link to the video
Happens with all/majority of videos, example one is https://www.youtube.com/watch?v=zSR3mng7wBI

I upgraded to yt-dlp 2022-01-21 and unfortunately after spending a couple days downloading a 2000 video channel I noticed that Tartube was no longer getting the video source / description / duration for downloads.

![image](https://user-images.githubusercontent.com/16659133/151628196-bc1afbca-1e44-4411-a171-8ba1eb99865a.png)

I restored a backup dp and reverted to yt-dlp 2021-12-27 and Tartube was getting the information as usual when I redownloaded the video.

**Comment by axcore** [comment]
I have no internet at the moment, so I can't do any testing. However, I have used Tartube v2.3.359 with yt-dlp 2022.01.21 without seeing the issues you describe.

Here are some things you could try:

1. The URL you gave me is a video URl, not a channel URL. Check that the channel you're trying to download is using [this URL](https://www.youtube.com/c/ZeducationTyler/videos) (in the Videos tab, right-click the channel and select Show > Channel properties...)
2. Try checking the channel, before trying to download it (in the Videos tab, right-click the channel and select Check channel)
3. Download the channel as normal. As soon as you notice a video with no source/description/duration, stop the download. Now click the Output tab, and show me the text for that video (you might have to scroll around to find it). It's possible that the new version of yt-dlp is using some text in a different format that Tartube doesn't recognise

**Comment by axcore** [comment]
Closed for inactivity. Feel free to re-open the issue if you're having the same problem with current versions of yt-dlp and Tartube.

**Comment by ceonelson** [comment]
Did a clean install with the latest Tartube and also the 20220408 version of yt-dlp and the error is still happening (also errors with the 20220308.1 version)

I added this channel:
https://www.youtube.com/c/BBQwithFranklin/videos

None of the video info was added to tartube:
![image](https://user-images.githubusercontent.com/16659133/162852142-9de02dd2-db99-44cd-88de-4ba00afb7496.png)


Command and last video output:
python3 D:\Audacity\_youtube\yt-dlp-20220408 --newline -i --hls-prefer-native --write-description --write-info-json --write-annotations --cookies D:/Audacity/_youtube/cookies.txt --write-thumbnail --merge-output-format mkv --write-sub --embed-thumbnail --add-metadata --convert-thumbnails jpg --sub-lang en --output D:/Audacity/_youtube/Cooking/BBQ with Franklin/%(uploader)s - (%(upload_date)s) - %(title)s - %(id)s - [%(format_id)s#%(height)sp].%(ext)s --get-comments --extractor-args youtube:comment_sort=top -f bestvideo[ext=webm][height<=?480][fps<=?30]+bestaudio[ext=webm]/bestvideo[height<=?480][fps<=?30]+bestaudio/best[height<=?480]/best --download-archive D:/Audacity/_youtube/Cooking/BBQ with Franklin/ytdl-archive.txt --windows-filenames https://www.youtube.com/c/BBQwithFranklin/videos

(also, --windows-filenames is being added even though the checkbox isn't set in download options)

[download] Downloading video 37 of 37
[youtube] KQi9m9m9BAA: Downloading webpage
[youtube] KQi9m9m9BAA: Downloading android player API JSON
[youtube] Downloading comment section API JSON
[youtube] Downloading ~22 comments
[youtube] Sorting comments by top comments
[youtube] Downloading comment API JSON page 1 (0/22)
[youtube]     Downloading comment API JSON reply thread 1 (2/22)
[youtube]     Downloading comment API JSON reply thread 2 (18/22)
[youtube] Extracted 21 comments
[info] KQi9m9m9BAA: Downloading 1 format(s): 244+251
[info] Writing video description to: D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121003) - Introducing 'BBQ with Franklin' - KQi9m9m9BAA - [244+251#480p].description
[info] Writing video subtitles to: D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121003) - Introducing 'BBQ with Franklin' - KQi9m9m9BAA - [244+251#480p].en.vtt
[download] Destination: D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121003) - Introducing 'BBQ with Franklin' - KQi9m9m9BAA - [244+251#480p].en.vtt
[download] 1.00KiB at Unknown speed (00:00)
[download] 1.42KiB at 473.43KiB/s (00:00)
[download] 100% of 1.42KiB in 00:00
[info] Downloading video thumbnail 41 ...
WARNING: Unable to download video thumbnail 41: HTTP Error 404: Not Found
[info] Downloading video thumbnail 40 ...
WARNING: Unable to download video thumbnail 40: HTTP Error 404: Not Found
[info] Downloading video thumbnail 39 ...
WARNING: Unable to download video thumbnail 39: HTTP Error 404: Not Found
[info] Downloading video thumbnail 38 ...
WARNING: Unable to download video thumbnail 38: HTTP Error 404: Not Found
[info] Downloading video thumbnail 37 ...
WARNING: Unable to download video thumbnail 37: HTTP Error 404: Not Found
[info] Downloading video thumbnail 36 ...
[info] Writing video thumbnail 36 to: D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121003) - Introducing 'BBQ with Franklin' - KQi9m9m9BAA - [244+251#480p].jpg
[info] Writing video metadata as JSON to: D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121003) - Introducing 'BBQ with Franklin' - KQi9m9m9BAA - [244+251#480p].info.json
WARNING: There are no annotations to write.
[ThumbnailsConvertor] Thumbnail "D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121003) - Introducing 'BBQ with Franklin' - KQi9m9m9BAA - [244+251#480p].jpg" is already in the requested format
[download] Destination: D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121003) - Introducing 'BBQ with Franklin' - KQi9m9m9BAA - [244+251#480p].f244.webm
[download] 100% of 4.56MiB in 00:00
[download] Destination: D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121003) - Introducing 'BBQ with Franklin' - KQi9m9m9BAA - [244+251#480p].f251.webm
[download] 100% of 1.26MiB in 00:00
[Merger] Merging formats into "D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121003) - Introducing 'BBQ with Franklin' - KQi9m9m9BAA - [244+251#480p].mkv"
Deleting original file D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121003) - Introducing 'BBQ with Franklin' - KQi9m9m9BAA - [244+251#480p].f244.webm (pass -k to keep)
Deleting original file D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121003) - Introducing 'BBQ with Franklin' - KQi9m9m9BAA - [244+251#480p].f251.webm (pass -k to keep)
[Metadata] Adding metadata to "D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121003) - Introducing 'BBQ with Franklin' - KQi9m9m9BAA - [244+251#480p].mkv"
[EmbedThumbnail] ffmpeg: Adding thumbnail to "D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121003) - Introducing 'BBQ with Franklin' - KQi9m9m9BAA - [244+251#480p].mkv"
[info] Writing updated playlist metadata as JSON to: D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (NA) - BBQwithFranklin - Videos - UC556b-Cl0Fp02iMc96yoJbg - [NA#NAp].info.json
[download] Finished downloading playlist: BBQwithFranklin - Videos



I restored a backup DB, put yt-dlp back to the 20211227 release and everything worked fine:
![image](https://user-images.githubusercontent.com/16659133/162852301-4f541e1c-2946-48e6-ac45-5b89d07aa4cc.png)

Output:
python3 D:\Audacity\_youtube\yt-dlp_20211227 --newline -i --hls-prefer-native --write-description --write-info-json --write-annotations --cookies D:/Audacity/_youtube/cookies.txt --write-thumbnail --merge-output-format mkv --write-sub --embed-thumbnail --add-metadata --sub-lang en --output D:/Audacity/_youtube/Cooking/BBQ with Franklin/%(uploader)s - (%(upload_date)s) - %(title)s - %(id)s - [%(format_id)s#%(height)sp].%(ext)s --get-comments --extractor-args youtube:comment_sort=top -f bestvideo[ext=webm][height<=?480][fps<=?30]+bestaudio[ext=webm]/bestvideo[height<=?480][fps<=?30]+bestaudio/best[height<=?480]/best --download-archive D:/Audacity/_youtube/Cooking/BBQ with Franklin/ytdl-archive.txt --windows-filenames https://www.youtube.com/c/BBQwithFranklin/videos
[youtube:tab] BBQwithFranklin: Downloading webpage
[download] Downloading playlist: BBQwithFranklin - Videos
[youtube:tab] UC556b-Cl0Fp02iMc96yoJbg page 1: Downloading API JSON
[info] Writing playlist metadata as JSON to: D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (NA) - BBQwithFranklin - Videos - UC556b-Cl0Fp02iMc96yoJbg - [NA#NAp].info.json
[info] Writing playlist description to: D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (NA) - BBQwithFranklin - Videos - UC556b-Cl0Fp02iMc96yoJbg - [NA#NAp].description
[info] Downloading playlist thumbnail 0 ...
[info] Writing playlist thumbnail 0 to: D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (NA) - BBQwithFranklin - Videos - UC556b-Cl0Fp02iMc96yoJbg - [NA#NAp].jpg
[download] Downloading video 1 of 37
[youtube:tab] playlist BBQwithFranklin - Videos: Downloading 37 videos
[youtube] GuJSzWTrjmM: Downloading webpage
[youtube] GuJSzWTrjmM: Downloading android player API JSON
[info] GuJSzWTrjmM: Downloading 1 format(s): 244+251
[youtube] Downloading comment section API JSON
[youtube] Downloading comment API JSON page 1 (0/0)
[youtube] Sorting comments by top comments
[youtube] Extracted 0 comments
[info] Writing video description to: D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20160108) - BBQ with Franklin Outtakes - Patience - GuJSzWTrjmM - [244+251#480p].description
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20160108) - BBQ with Franklin Outtakes - Patience - GuJSzWTrjmM - [244+251#480p].webp
[info] Writing video metadata as JSON to: D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20160108) - BBQ with Franklin Outtakes - Patience - GuJSzWTrjmM - [244+251#480p].info.json
WARNING: There are no annotations to write.
[download] Destination: D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20160108) - BBQ with Franklin Outtakes - Patience - GuJSzWTrjmM - [244+251#480p].f244.webm
[download] 100% of 7.23MiB in 00:01
[download] Destination: D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20160108) - BBQ with Franklin Outtakes - Patience - GuJSzWTrjmM - [244+251#480p].f251.webm
[download] 100% of 2.12MiB in 00:00
[Merger] Merging formats into "D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20160108) - BBQ with Franklin Outtakes - Patience - GuJSzWTrjmM - [244+251#480p].mkv"
Deleting original file D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20160108) - BBQ with Franklin Outtakes - Patience - GuJSzWTrjmM - [244+251#480p].f244.webm (pass -k to keep)
Deleting original file D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20160108) - BBQ with Franklin Outtakes - Patience - GuJSzWTrjmM - [244+251#480p].f251.webm (pass -k to keep)
[Metadata] Adding metadata to "D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20160108) - BBQ with Franklin Outtakes - Patience - GuJSzWTrjmM - [244+251#480p].mkv"
[ThumbnailsConvertor] Converting thumbnail "D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20160108) - BBQ with Franklin Outtakes - Patience - GuJSzWTrjmM - [244+251#480p].webp" to png
[EmbedThumbnail] ffmpeg: Adding thumbnail to "D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20160108) - BBQ with Franklin Outtakes - Patience - GuJSzWTrjmM - [244+251#480p].mkv"
Deleting original file D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20160108) - BBQ with Franklin Outtakes - Patience - GuJSzWTrjmM - [244+251#480p].png (pass -k to keep)

If I check the channel beforehand with the latest yt-dlp, it will be added to tartube and then I can download them successfully after the check completes (but that brought up issue #398 ).

Any thoughts on what to do to be able to use the latest yt-dlp?

**Comment by ceonelson** [comment]
Was just going through a note file in vscode and realized I never posted the details from the original post that shows the error with yt-dlp 20220121:

**Video link / duration / etc not being recorded:
This is with the 2022-01-21 yt-dlp file that didn't work:**
[youtube] Extracted 2024 comments
[info] Writing video description to: D:/Audacity/_youtube/Comedy/Zeducation/Zeducation - (20220127) - TRY NOT TO LAUGH #41 - zSR3mng7wBI - [247+251#720p].description
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: D:/Audacity/_youtube/Comedy/Zeducation/Zeducation - (20220127) - TRY NOT TO LAUGH #41 - zSR3mng7wBI - [247+251#720p].webp
[info] Writing video metadata as JSON to: D:/Audacity/_youtube/Comedy/Zeducation/Zeducation - (20220127) - TRY NOT TO LAUGH #41 - zSR3mng7wBI - [247+251#720p].info.json
[download] Destination: D:/Audacity/_youtube/Comedy/Zeducation/Zeducation - (20220127) - TRY NOT TO LAUGH #41 - zSR3mng7wBI - [247+251#720p].f247.webm
[download] 100% of 129.79MiB in 00:22
[download] Destination: D:/Audacity/_youtube/Comedy/Zeducation/Zeducation - (20220127) - TRY NOT TO LAUGH #41 - zSR3mng7wBI - [247+251#720p].f251.webm
[download] 100% of 20.75MiB in 00:03
[Merger] Merging formats into "D:/Audacity/_youtube/Comedy/Zeducation/Zeducation - (20220127) - TRY NOT TO LAUGH #41 - zSR3mng7wBI - [247+251#720p].mkv"
Deleting original file D:/Audacity/_youtube/Comedy/Zeducation/Zeducation - (20220127) - TRY NOT TO LAUGH #41 - zSR3mng7wBI - [247+251#720p].f247.webm (pass -k to keep)
Deleting original file D:/Audacity/_youtube/Comedy/Zeducation/Zeducation - (20220127) - TRY NOT TO LAUGH #41 - zSR3mng7wBI - [247+251#720p].f251.webm (pass -k to keep)
[Metadata] Adding metadata to "D:/Audacity/_youtube/Comedy/Zeducation/Zeducation - (20220127) - TRY NOT TO LAUGH #41 - zSR3mng7wBI - [247+251#720p].mkv"
[ThumbnailsConvertor] Converting thumbnail "D:/Audacity/_youtube/Comedy/Zeducation/Zeducation - (20220127) - TRY NOT TO LAUGH #41 - zSR3mng7wBI - [247+251#720p].webp" to png
[EmbedThumbnail] ffmpeg: Adding thumbnail to "D:/Audacity/_youtube/Comedy/Zeducation/Zeducation - (20220127) - TRY NOT TO LAUGH #41 - zSR3mng7wBI - [247+251#720p].mkv"
Deleting original file D:/Audacity/_youtube/Comedy/Zeducation/Zeducation - (20220127) - TRY NOT TO LAUGH #41 - zSR3mng7wBI - [247+251#720p].png (pass -k to keep)
[download] Downloading video 3 of 281

**This is with the 2021-12-27 yt-dlp file that worked:**
[youtube] Extracted 2027 comments
[info] Writing video description to: D:/Audacity/_youtube/Comedy/Zeducation/Zeducation - (20220127) - TRY NOT TO LAUGH #41 - zSR3mng7wBI - [247+251#720p].description
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: D:/Audacity/_youtube/Comedy/Zeducation/Zeducation - (20220127) - TRY NOT TO LAUGH #41 - zSR3mng7wBI - [247+251#720p].webp
[info] Writing video metadata as JSON to: D:/Audacity/_youtube/Comedy/Zeducation/Zeducation - (20220127) - TRY NOT TO LAUGH #41 - zSR3mng7wBI - [247+251#720p].info.json
[download] D:/Audacity/_youtube/Comedy/Zeducation/Zeducation - (20220127) - TRY NOT TO LAUGH #41 - zSR3mng7wBI - [247+251#720p].mkv has already been downloaded
[Metadata] Adding metadata to "D:/Audacity/_youtube/Comedy/Zeducation/Zeducation - (20220127) - TRY NOT TO LAUGH #41 - zSR3mng7wBI - [247+251#720p].mkv"
[ThumbnailsConvertor] Converting thumbnail "D:/Audacity/_youtube/Comedy/Zeducation/Zeducation - (20220127) - TRY NOT TO LAUGH #41 - zSR3mng7wBI - [247+251#720p].webp" to png
[EmbedThumbnail] ffmpeg: Adding thumbnail to "D:/Audacity/_youtube/Comedy/Zeducation/Zeducation - (20220127) - TRY NOT TO LAUGH #41 - zSR3mng7wBI - [247+251#720p].mkv"
Deleting original file D:/Audacity/_youtube/Comedy/Zeducation/Zeducation - (20220127) - TRY NOT TO LAUGH #41 - zSR3mng7wBI - [247+251#720p].png (pass -k to keep)
[download] Downloading video 3 of 281

Hopefully that combined with my post from today can help figure out what the issue is :)

**Comment by axcore** [comment]
Should be fixed in v2.3.562.
