### ISSUE TITLE
Use an alternative downloader when fail downloading

### ISSUE THREAD

**Issue by mirusu400** [axcore/tartube#375]
When we failed to download, tartube simply show the `nothing happend` prompt: like #368

How about making an option about setting alternative downloader (such as yt-dl, yt-dlp, and other forks), and trying other downloader when failed to download?

It looks nice when background downloading and batch downloading.

Thanks for your help

**Comment by axcore** [comment]
The `nothing happened` message is usually seen when the downloader is not configured correctly. I think that switching to another downloader won't help, because the other downloader won't be configured correctly either.

Also, the only useable fork at the moment is yt-dlp.
