### ISSUE TITLE
Details information missing at my downloaded video

### ISSUE THREAD

**Issue by shironekoss** [axcore/tartube#377]
this is my first time using this , usually using some kind of cmd with phyton from another source. i found it easy but after check my details on some video i had download 
i just found the details information is missing. is it normal ? just curious 

here is the preview
![is this normal](https://user-images.githubusercontent.com/91777682/152358985-cefa2f80-69df-4d45-a1e0-2d0181b718d8.png)

**Comment by axcore** [comment]
Tartube does not download the video, [youtube-dl ](https://github.com/ytdl-org/youtube-dl)and [yt-dlp](https://github.com/yt-dlp/yt-dlp) download the video. So you should ask your question there.

**Comment by shironekoss** [comment]
thx for the info i will ask there :)
