### ISSUE TITLE
[Feature Request] Download multiple specific/selected channels at once?

### ISSUE THREAD

**Issue by NotErikUden** [axcore/tartube#379]
An option to select multiple channels/playlists/videos and only download those!
I have recently gotten Tartube and created a huge collection of channels and playlists, all of which I would like to download, at some point. However, if I were to just click "download all" it would take ages, possibly months. In that time, some of the more important content may already get deleted by their original uploader. Hence, some videos have a higher priority to me, which I would like to download first. 

At the moment, I can individually download a singular channel by right clicking on it and then selecting "Download channel". 
However, when I select this option and the videos begin being downloaded, all other download options grey out until the download operation completes or I stop the operation. Hence, I believe, I can only download one channel/playlist/video at a time, or all channels/playlists/videos at once (_unless the channels I wish to download are all in one folder_). 

When multiple videos and channels get downloaded, Tartube has no issue handling multiple instances of youtube-dl or yt-dlp at once, so I would assume it could be possible to also only download multiple selected channels, or to start downloads even after a download is already running, hence allowing me to download multiple _selected_ channels / videos / playlists at once!

**So, essentially, what I imagine is:** a selection button next to each channel, playlist, and folder on the main "Videos" tab of Tartube, and a "Download selected" option below the "Download all" button on the main menu, that would only download the selected.

Alternatively, I could also imagine a priority system, in which I could give channels a higher or lower download priority for them to be downloaded first when pressing "Download all".

If there are any questions regarding my idea, or if this idea has already been implemented and I just did not find it, please let me know and I will try to respond asap! 
Thank you for running Tartube! Have a wonderful day!

**Comment by axcore** [comment]
Workaround: create a folder, darg the channels/playlists/video into that folder, then right-click the folder and select **Download folder**.

**Comment by NotErikUden** [comment]
Did do that a while ago! Figured that would be the best option! Thanks!
![image](https://user-images.githubusercontent.com/52011431/152681068-300889d9-813e-43ea-b727-046231e88eac.png)

**Comment by axcore** [comment]
Added in v2.3.549. There's a checkbutton next to each channel/playlist/folder, select one or more of them, and you can check/download just those items.

**Comment by NotErikUden** [comment]
Thank you SO much! What an incredible developer you are! This is a feature I very much needed and will use a lot... Thank you!

**Comment by NotErikUden** [comment]
![image](https://user-images.githubusercontent.com/52011431/163992364-98bbb602-cd6d-4854-9ae5-bf1e84fb01f5.png)
Have just tried it, works like a charm! Exactly as expected and easy to understand! Thanks!!

**Comment by axcore** [comment]
I can't accept donations because, if I do, Hollywood's lawyers will eat me alive.

If your conscience is troubling you, perhaps there is a charity doing good work in your neighbourhood, which would appreciate a couple of bucks.
