### ISSUE TITLE
How to download direct audio

### ISSUE THREAD

**Issue by mbnoimi** [axcore/tartube#38]
Hi,

How can I download the audio directly using Tartube?

Using `youtube-dl` I do it easily by choosing format core 140 (for most youtube videos) but Tartube download the video in all the cases then extract the audio file.

ex.
```
$ youtube-dl -F https://www.youtube.com/watch?v=rG0UXdRKEoc
[youtube] rG0UXdRKEoc: Downloading webpage
[youtube] rG0UXdRKEoc: Downloading video info webpage
[info] Available formats for rG0UXdRKEoc:
format code  extension  resolution note
249          webm       audio only tiny   51k , opus @ 50k (48000Hz), 2.22MiB
250          webm       audio only tiny   67k , opus @ 70k (48000Hz), 2.67MiB
140          m4a        audio only tiny  130k , m4a_dash container, mp4a.40.2@128k (44100Hz), 5.80MiB
251          webm       audio only tiny  132k , opus @160k (48000Hz), 5.04MiB
278          webm       256x144    144p   96k , webm container, vp9, 30fps, video only, 3.87MiB
160          mp4        256x144    144p  113k , avc1.4d400c, 30fps, video only, 3.61MiB
242          webm       426x240    240p  182k , vp9, 30fps, video only, 5.63MiB
133          mp4        426x240    240p  259k , avc1.4d4015, 30fps, video only, 8.09MiB
243          webm       640x360    360p  335k , vp9, 30fps, video only, 10.22MiB
244          webm       854x480    480p  616k , vp9, 30fps, video only, 16.51MiB
134          mp4        640x360    360p  627k , avc1.4d401e, 30fps, video only, 14.87MiB
135          mp4        854x480    480p 1141k , avc1.4d401f, 30fps, video only, 25.70MiB
247          webm       1280x720   720p 1292k , vp9, 30fps, video only, 35.16MiB
136          mp4        1280x720   720p 2201k , avc1.4d401f, 30fps, video only, 49.53MiB
248          webm       1920x1080  1080p 2531k , vp9, 30fps, video only, 82.56MiB
137          mp4        1920x1080  1080p 4607k , avc1.640028, 30fps, video only, 94.88MiB
18           mp4        640x360    360p  468k , avc1.42001E, mp4a.40.2@ 96k (44100Hz), 21.01MiB
22           mp4        1280x720   720p 1233k , avc1.64001F, mp4a.40.2@192k (44100Hz) (best)
```

**Comment by axcore** [comment]
>How can I download the audio directly using Tartube?
First, make sure ffmpeg or avconv is installed. On MS Windows, install FFmpeg from the Tartube menu. On Linux Mint, do this:

sudo apt-get install ffmpeg

Secondly, format code 140 is the equivalent of 'm4a 128k (DASH Audio)'. So make sure the format is selected (Edit > General download options > Formats, then Click 'm4a 128k (DASH Audio)' to select it, then click 'Add format >>>', then click OK to close the window

Third, make sure it is actually possible to download that video. I am in the UK, and I am seeing this error:

![ukerror](https://user-images.githubusercontent.com/37951926/71978151-8f1c0600-3212-11ea-9bba-2affb3024126.png)

**Comment by axcore** [comment]
Thanks for all your suggestions. I have a lot of work, so it will be a few days (but not a few weeks) before I can implement them.

**Comment by mbnoimi** [comment]
> Thanks for all your suggestions. I have a lot of work, so it will be a few days (but not a few weeks) before I can implement them.

Thank a lot @axcore for the great contributions and I wish you best.

Regrading audio downloading I did as you suggested but still get error (below a new video I think it's available in UK)
```
$ youtube-dl -F https://www.youtube.com/watch?v=LiIVkD8UtKA
[youtube] LiIVkD8UtKA: Downloading webpage
[youtube] LiIVkD8UtKA: Downloading video info webpage
[youtube] LiIVkD8UtKA: Downloading MPD manifest
[info] Available formats for LiIVkD8UtKA:
format code  extension  resolution note
139          m4a        audio only DASH audio   50k , m4a_dash container, mp4a.40.5@ 48k (22050Hz)
140          m4a        audio only DASH audio  130k , m4a_dash container, mp4a.40.2@128k (44100Hz)
251          webm       audio only DASH audio  143k , webm_dash container, opus @160k (48000Hz)
278          webm       256x144    DASH video   95k , webm_dash container, vp9, 30fps, video only
160          mp4        256x144    DASH video  108k , mp4_dash container, avc1.4d400b, 30fps, video only
242          webm       426x240    DASH video  220k , webm_dash container, vp9, 30fps, video only
133          mp4        426x240    DASH video  242k , mp4_dash container, avc1.4d400c, 30fps, video only
134          mp4        640x360    DASH video  335k , mp4_dash container, avc1.4d401e, 30fps, video only
243          webm       640x360    DASH video  405k , webm_dash container, vp9, 30fps, video only
244          webm       854x480    DASH video  752k , webm_dash container, vp9, 30fps, video only
135          mp4        854x480    DASH video 1155k , mp4_dash container, avc1.4d4014, 30fps, video only
247          webm       1280x720   DASH video 1505k , webm_dash container, vp9, 30fps, video only
137          mp4        1920x1080  DASH video 2058k , mp4_dash container, avc1.640028, 30fps, video only
136          mp4        1280x720   DASH video 2310k , mp4_dash container, avc1.4d4016, 30fps, video only
248          webm       1920x1080  DASH video 2646k , webm_dash container, vp9, 30fps, video only
18           mp4        640x360    360p  332k , avc1.42001E, mp4a.40.2@ 96k (44100Hz), 11.22MiB (best)
$ 
```
![image](https://user-images.githubusercontent.com/284547/71979640-41fa5d00-322f-11ea-8ac4-08d085af179e.png)

![image](https://user-images.githubusercontent.com/284547/71979670-55a5c380-322f-11ea-9b0c-94c3ac220af9.png)

I tried to use the following configuration (I expect to be more general because format 140 unavailable outside YouTube) but unfortunately I got an error once again :(

![image](https://user-images.githubusercontent.com/284547/71979830-bb924b00-322f-11ea-923b-9b5d0e983bf5.png)

![image](https://user-images.githubusercontent.com/284547/71979860-ccdb5780-322f-11ea-8831-a2c3c664e5c8.png)

**Comment by mbnoimi** [comment]
```
# apt list --installed ffmpeg
Listing... Done
ffmpeg/bionic-updates,bionic-security,now 7:3.4.6-0ubuntu0.18.04.1 amd64 [installed]
N: There is 1 additional version. Please use the '-a' switch to see it
#
```

**Comment by axcore** [comment]
Okay, it seems that youtube-dl demands that one of the formats must be a video format, even if you only want audio. I didn't know about this restriction until you found it.

To download only the audio for [this video](https://www.youtube.com/watch?v=LiIVkD8UtKA), users should follow this procedure:

1. On MS Windows, make sure FFmpeg is installed (Operations > Install FFmpeg). On Linux/BSD, make sure either FFmpeg or avconv is installed (using any method you like)
2. Click Edit > Download general options > Formats
3. Add at least one video format, as well as 0, 1 or 2 audio formats 

![audioformat](https://user-images.githubusercontent.com/37951926/72259350-24027300-3608-11ea-8dba-505cfcd88899.png)

4. Click the Post-processing tab, and make sure Post-process video files to convert them to audio-only files is selected

![audioformat2](https://user-images.githubusercontent.com/37951926/72259503-8a879100-3608-11ea-8fdc-9581c36621c6.png)

5. Tartube now downloads the video, extracts the audio to .m4a, and deletes the original video file

![audioformat3](https://user-images.githubusercontent.com/37951926/72259529-a12de800-3608-11ea-8772-9e6da3f01a63.png)

I will make some changes so other users won't experience this problem:

1. Add a section to the README file, explaining how to download only audio
2. Change the Edit > General download options > Format tab, so that the user can't select an audio format until they have selected a video format

**Comment by axcore** [comment]
Those changes were added in v1.3.042. Feel free to re-open the issue if you have any similar problems.

**Comment by mbnoimi** [comment]
Unfortunately it doesn't work at all see my test for downloading:
https://www.youtube.com/watch?v=LIihyY6spAA

![Peek 2020-01-25 14-47](https://user-images.githubusercontent.com/284547/73120617-c82dd780-3f81-11ea-9d9d-8e134e5a3571.gif)

**Comment by axcore** [comment]
You have the following three formats listed: 

```
m4a
m4a 256k
m4a 128k
```

Recently, you discovered that the first format must be a video format. Since v1.3.042, the user cannot add an audio format before a video format has been added.

This is what you should do:

1. Click **Edit > System preferences... > Formats**
2. Remove all three audio formats
3. Click the **Post-processing** tab
4. Select **Post-process video files to convert them to audio-only files**
5. In the box **Audio format of the post-processed file**, select **m4a**
6. Click the **OK** button at the bottom of the window, to apply your changes

I have tested [your video](https://www.youtube.com/watch?v=LIihyY6spAA), and I can download the sound without problems.

**Comment by mbnoimi** [comment]
Solved
Thank you @axcore

**Comment by gitut2007** [comment]
Hi, 
I think the original idea of the op was to download the audio *directly* [eg code 140], not "Tartube now downloads the video, extracts the audio to .m4a, and deletes the original video file", so even if one has to add one video format besides to audio formats, [by the way why max. only 3?], it should be possible to download the M4a sans wasting dling the video?
Thx.

**Comment by xbliss** [comment]
> You have the following three formats listed:
> 
> ```
> m4a
> m4a 256k
> m4a 128k
> ```
> 
> Recently, you discovered that the first format must be a video format. Since v1.3.042, the user cannot add an audio format before a video format has been added.
> 
> This is what you should do:
> 
> 1. Click **Edit > System preferences... > Formats**
> 2. Remove all three audio formats
> 3. Click the **Post-processing** tab
> 4. Select **Post-process video files to convert them to audio-only files**
> 5. In the box **Audio format of the post-processed file**, select **m4a**
> 6. Click the **OK** button at the bottom of the window, to apply your changes
> 
> I have tested [your video](https://www.youtube.com/watch?v=LIihyY6spAA), and I can download the sound without problems.

Is this the currently recommended way when we want AUDIO only? Is there a way to "templatize" this for regular usage as part of a Download Options template? How can we do that? What steps to follow?

**Comment by axcore** [comment]
Edit > General download options...

If the **Hide advanced download options** button is visible, click it

Now click the **Sound only** tab, and choose your format

Click OK to close the window

That's it

**Comment by axcore** [comment]
The **Sound only** tab appears when you click **Hide advanced options**. It disappears when you click **Show advanced options**.

**Comment by xbliss** [comment]
> The **Sound only** tab appears when you click **Hide advanced options** once.
> 
> It disappears when you click **Show advanced options** once.

Did that - I understand its a toggle between the modes - Its not showing up in either 

- Unless you can point to me where I should be looking for it 

Here's what I see: 

![image](https://user-images.githubusercontent.com/5311222/160624196-90a83a3a-8a88-4b4e-ac14-92aeff9dd149.png)

![image](https://user-images.githubusercontent.com/5311222/160624297-bb915072-728c-4732-b2fb-6389d4b14bef.png)
