### ISSUE TITLE
[Feature Request] Global statistics?

### ISSUE THREAD

**Issue by NotErikUden** [axcore/tartube#381]
I LOVE when I "Stop the current operation" or all my downloads finish and a small window pops up showing me just how many videos I've downloaded. I would enjoy for there to be an option, possibly under the "Help", or "Operations" tab that would just show how many videos from how many channels / playlists, etc. I've downloaded overall. I know the "Videos" tab has the "All Videos" folder, but that takes ages to load, and just displays one number. 
[qBittorrent](https://github.com/qbittorrent/qBittorrent) has a statistics tab where it shows all up and downloads, etc. of course Tartube has no uploads, but it would be neat to see all daily/weekly/monthly/yearly/all time used bandwidth and how many videos that are, possibly what the largest/longest video is, etc. Just some fun database stats to look at!
Largest channel/playlist-size, total hours of watch time for all videos (represented in days, weeks, months, years, etc.)
Stuff like this is quite unnecessary, but does not seem **too** complex to implement? All of these statistics are already stored per video. All it would take for this is for these video statistics to be counted up on a channel to channel basis and then added together per channel for global stats.

But really, only if you find the time! Thanks for making Tartube!

**Comment by axcore** [comment]
**Edit > System preferences > Files > Statistics** has many of the numbers you want.

The neighbouring **History** tab shows the download history you want. Click the **Draw** button to see something. If nothing happens, you may have to install matplotlib: see [here](https://github.com/axcore/tartube#730-graphs-not-visible).

Tartube doesn't know how many hours you have spent watching videos. It does know which videos you have opened using Tartube's buttons and clickable text, but that's it.
