### ISSUE TITLE
The new version can't download youtube videos in flac

### ISSUE THREAD

**Issue by metapea** [axcore/tartube#383]
### What operating system are you using?
 7

### What version of Tartube are you using?
v2.3.367

### What happens when you run Tartube from a terminal window?
After when tartube failed to install mingw-w64-x86_64-docbook, it keep giving me ERROR: requested format not available when trying to download in flac. Downloading in flac for the version 2.3.110 still works, so i know it isn't a video specifically

**Comment by axcore** [comment]
MSYS2's ffmpeg repository has been rebuilt, which should fix your problem.

Remove your Tartube installation, then reinstall it (make sure you're using v2.3.367). 

I will risk closing this issue, but feel free to open a new one if you have similar problems.

**Comment by metapea** [comment]
The error is still there in classic mode

**Comment by axcore** [comment]
Did you delete your previous Tartube installation, and then install v2.3.367, and then install FFmpeg from Tartube's menu, yes?

If so, try to install docbook directly. When it fails, take a screenshot of the error and show me that.

- Enable hidden folders on your system
- Open the mingw64 terminal, the default location is **C:\Users\YOURNAME\AppData\Local\Tartube\msys64\mingw64.exe** (perhaps you installed Tartube to a different location)
- Type **pacman -S mingw-w64-x86_64-docbook**

**Comment by metapea** [comment]
I deleted the whole folder and i still got error for docbook
I type pacman -S mingw-w64-x86_64-docbook in mingw64.exe but i just got "error: target not found: mingw-w64-"

When it comes to the flac problem, i found the problem:
 ![Screenshot_81](https://user-images.githubusercontent.com/35351174/157061611-4e6d9087-cc89-4b35-ad41-b3a3ac84fc7b.png)
and the fix:
![Screenshot_80](https://user-images.githubusercontent.com/35351174/157061485-f307860d-b675-4690-9b10-0aaaa1aaada1.png)
It's works fine "convert to" but the default "download in this format" just gives that error.
I'm asking at this point, is for an auto-"convert to" for files like flac and maybe make it default since the older version seem to just used this. 
Just tell #384 that.

**Comment by axcore** [comment]
![docbook](https://user-images.githubusercontent.com/37951926/157082930-def855a1-8069-40e4-bec7-cb135c4ffa2e.png)

These are the available docbook packages. As you say, **mingw-w64-x86_64-docbook** is not listed. 

So, you should check the FFmpeg installation error, which should mention one of the listed packages instead of  **mingw-w64-x86_64-docbook** itself.

**Comment by axcore** [comment]
>I'm asking at this point, is for an auto-"convert to" for files like flac

Not possible I think, if FFmpeg is not installed on the user's system (or installed incorrectly) then an auto-"convert to" function will not work.

**Comment by metapea** [comment]
>Not possible I think, if FFmpeg is not installed on the user's system (or installed incorrectly) then an auto-"convert to" function will not work.
What i'm saying is, if the gui detects a flac/"download in this format" request on a YouTube link then it will download as flac/"convert to this format using". I'm talking about tartube's gui, not FFmpeg.
using flac/"convert to this format using" is working fine even if docbook is missing so far

>Users expect Tartube to download files that don't exist, and then get disappointed and angry when Tartube can't do it. I'm not sure what can be done to improve the situation.
_It did and ''existed''_ on the older version when classic mode was just using "convert to this format using". Just switch around "convert to this format using" and "download in this format" in the gui while making "convert to this format using" the default as an easy fix

**Comment by metapea** [comment]
>These are the available docbook packages. As you say, mingw-w64-x86_64-docbook is not listed.
I already give out my error in the other thread (#371), it's the same error.
also i tried pacman -S mingw-w64-x86_64-docbook-xsl and pacman -S mingw-w64-x86_64-docbook-xml, it just gives me the same error

**Comment by axcore** [comment]
>What i'm saying is, if the gui detects a flac/"download in this format" request on a YouTube link then it will download as flac/"convert to this format using"

Understood. But there are 1000s of video sites, many of them probably allow direct downloads of FLAC. How does Tartube know that a FLAC file is not available to download?

By the way, FFmpeg will happily try to convert MP4 to MP4, and try to convert FLAC to FLAC, and this will take a long time. That is an unfortunate complication.

>It did and ''existed'' on the older version when classic mode was just using "convert to this format using".

**Comment by axcore** [comment]
I updated the mini-screenshot, it should have the same effect.
![updated](https://user-images.githubusercontent.com/37951926/157612246-b7bfab3d-2a51-43f6-9f20-f43a46c7ffa4.png)

**Comment by metapea** [comment]
> I updated the mini-screenshot, it should have the same effect. ![updated](https://user-images.githubusercontent.com/37951926/157612246-b7bfab3d-2a51-43f6-9f20-f43a46c7ffa4.png)
Looks good
maybe change the "(try converting)" part to bold or a red color, other then that it's fine
I just didn't know converting meant the "Convert to this format" option

**Comment by axcore** [comment]
Looks like this issue is finished. But buzz me if I have forgotten something.
