### ISSUE TITLE
Attempts to download videos give an error status

### ISSUE THREAD

**Issue by crocodisle** [axcore/tartube#384]
### What operating system are you using?
Windows 10

### What version of Tartube are you using?
v2.3.367

### What happens when you run Tartube from a terminal window?
No change in behavior

### If your bug report is "I can't download this video", please provide a link to the video
One of the attempted files:
https://www.youtube.com/watch?v=HK00Hq9lH3A

When attempting to download videos using either the classic mode or "Videos" tab, I get the error status. There's no special output in the error window and the output window only shows the youtube-dl.exe command with its arguments. 

When I attempt "Test youtube-dl" from the Operations menu it does seem to download the file, but using the Classic Mode and Videos tab doesn't work.

I'm not sure if it's related because I read other users were having issues but ffmpeg was throwing errors on install. After navigating away from the ffmpeg installation dialog and then back to it, it seems to install successfully though, and much more quickly, so I'm not sure what that's about either.

**Comment by metapea** [comment]
I've still been getting the same error even i've re-install it

**Comment by axcore** [comment]
Try to download the video, then show me a screenshot of the Output tab, or copy-and-paste the yellow text, so I can make sure I am testing the same setup as you.

**Comment by axcore** [comment]
Closed for inactivity. Feel free to re-open if you're still having the same issue.
