### ISSUE TITLE
Videos are only "checked", not downloaded

### ISSUE THREAD

**Issue by Flavescent** [axcore/tartube#385]
After installing Tartube 2.3.367 on Win10, when I add a video and attempt to download it (either individually via the context menu or through "Download all", Tartube displays "Videos downloaded: 0 - Videos checked: 1". 

So it only checks the video, rather than downloading it. What am I doing wrong?

The video is https://www.youtube.com/watch?v=JIT9aUHbcaI.

The output window yields: 
yt-dlp --newline -i --hls-prefer-native --write-description --write-info-json --write-annotations --cookies D:/Downloads/Tartube/cookies.txt --write-thumbnail -f m4a -x --audio-format m4a --audio-quality 0 --output D:/Downloads/Tartube/Unsorted Videos/%(title)s.%(ext)s --split-chapters --dump-json https://www.youtube.com/watch?v=JIT9aUHbcaI
[Unsorted Videos] <Simulated download of: 'Dark Souls 3 The Fire Fades Edition Soundtrack (Complete)'>

**Comment by axcore** [comment]
In the **Videos** tab, look in the list of channels/playlists/folders. Are any of them in italics or underlined?

If so, you have disabled downloading for those channels/playlists/folders. Right-click the channel/playlist/folder and deselect the options like **Downloads > Just disable downloading**

**Comment by axcore** [comment]
In v2.3.393, channels and playlists for which checking/downloading is disabled are marked with an icon, not with stylised text. This should be a bit clearer.

![pewdiepie](https://user-images.githubusercontent.com/37951926/157296779-80f89dc2-5bfa-47af-b7c6-3d99b4c07544.png)

Edit: the icon is not updated immediately, but I'll fix that.
