### ISSUE TITLE
Why is tartube download so slow?

### ISSUE THREAD

**Issue by eternallblack** [axcore/tartube#386]
My internet speed is over 600mbps yet the application is extremely slow in downloading
![Screenshot (10877)](https://user-images.githubusercontent.com/94350153/156959544-1b5076e3-772c-40ee-94f2-9b65da94a240.png)
.

**Comment by axcore** [comment]
Make sure you are using yt-dlp, not youtube-dl (in Edit > System preferences > Downloaders > Forks).

Otherwise, YouTube is throttling your downloads, 60kb/s is the same speed that everyone is getting; see [this](https://www.reddit.com/r/youtubedl/comments/qfbyal/read_slow_youtube_downloads/).

**Comment by eternallblack** [comment]
Its maxiing at around 550 kibs.

**Comment by axcore** [comment]
You could try custom downloads, so you can download more than one video from the channel at a time: see [here](https://github.com/axcore/tartube#custom-downloads).

But that probably won't change the fact that when YouTube decides to throttle you, there isn't much you can do about it.

**Comment by eternallblack** [comment]
Ok,why is it that other people can download at full speed?

**Comment by axcore** [comment]
>Ok,why is it that other people can download at full speed?

The possible reasons are:

1. You are using an old version of yt-dlp
2. You are using youtube-dl (any version)
3. YouTube is throttling you

And the solutions are:

1. Switch to yt-dlp
2. Update yt-dlp
3. Change your IP address (turning off the router for a few hours works for me, but it might not work for everyone)

If you can't find a solution, you are asking in the wrong place: [yt-dlp](https://github.com/yt-dlp/yt-dlp) is a separate application, and I don't have any control over it.
