### ISSUE TITLE
I cant download playlists

### ISSUE THREAD

**Issue by MajorBro** [axcore/tartube#387]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
If using MS Windows, are you using Windows 10, Windows 7, or something else?

windows

### What version of Tartube are you using?
In Tartube's main window, click Help > About

2.3.332

### What happens when you run Tartube from a terminal window?
Many error messages are only visible in the terminal window. On MS Windows, this is how to do it:

- First, enable hidden folders on your system
- Then, run the application: 

    C:\Users\YOURNAME\AppData\Local\Tartube\msys64\mingw64.exe

- In this new window, type these commands to start Tartube:

    cd /home/user/tartube

    python3 tartube/tartube

nothing changed
edit: while trying to download this message popped up "Gdk-WARNING **: 22:20:10.754: ../gtk+-3.24.25/gdk/win32/gdkselection-win32.c:1925: CloseClipboard failed with code 1418: Thread does not have a clipboard open."

###If your bug report is "I can't download this video", please provide a link to the video
This will save a lot of time
its a playlist
https://www.youtube.com/playlist?list=PLhm0jQccmWFoApN6n1sEhl_lKnZTfJqJG

when i try to download any playlist i get an error message of "Download did not start". I also cant seem to update yt-dlp, every time i try it gives me an error message of "Update operation failed". Normal videos seem to work but just not playlists.

**Comment by axcore** [comment]
Edit > System preferences... > Downloaders > File paths

Check that the settings look like this

![pypi](https://user-images.githubusercontent.com/37951926/158536116-87756c7f-f34f-4e1a-9ac0-f34f46add221.png)

Also check that yt-dlp is really selected in > Downloaders > Forks

Also try updating to Tartube v2.3.367.

**Comment by xbliss** [comment]
Experienced same, Checked above items. Updating and will get back after that.

**Comment by MajorBro** [comment]
> Edit > System preferences... > Downloaders > File paths
> 
> Check that the settings look like this
> 
> ![pypi2](https://user-images.githubusercontent.com/37951926/158536577-8dda5ac0-98cf-43b9-a27a-d085c013cd60.png)
> 
> Also check that yt-dlp is really selected in > Downloaders > Forks
> 
> Also try updating to Tartube v2.3.367.

how do i update

**Comment by axcore** [comment]
>how do i update

How do you update Tartube? Open your Start menu, find the option to uninstall Tartube, then download the new release and install it

**Comment by axcore** [comment]
Closed for inactivity.
