### ISSUE TITLE
Downloaded videos with custom filename lose link to YouTube

### ISSUE THREAD

**Issue by c0wg0d** [axcore/tartube#388]
### What operating system are you using?
Windows 10

### What version of Tartube are you using?
v2.3.367

Under Files->File names I have set a custom value: `%(upload_date)s - %(id)s - %(title)s.%(ext)s`

When downloading videos, sometimes the video will be "lost" inside Tartube.  What I mean by that is the video displays in Tartube, but the title shown is my custom filename, rather than the title of the video, and all the links/options to "Watch on YouTube" are gone/not available.

As an example, I added this playlist to Tartube: https://www.youtube.com/playlist?list=PLAYFVhxsaqDuOh4Ic5mRu5CiZVKCMVv66

All of the videos downloaded successfully when I added the playlist, but as you can see in the following screenshot, the only one that kept a link to the original video is the one titled "Overwatch Animated Short | The Last Bastion" (the 6th video in the screenshot).  All the others show my custom value for the title and all the links to the original video are lost.

How can I relink all these videos and show the titles properly?

![rcyT5fqHqC](https://user-images.githubusercontent.com/10082424/159060864-cd77b203-7960-43ee-bab0-82398926dc65.png)

**Comment by axcore** [comment]
I tested this, using the same playlist and the same output template `%(upload_date)s - %(id)s - %(title)s.%(ext)s`, and it worked:

![159060864-cd77b203-7960-43ee-bab0-82398926dc65](https://user-images.githubusercontent.com/37951926/159112515-a0883ab6-df85-463f-97ba-e0fec72e9e08.png)

Please try downloading the playlist again, and show me what you see in the **Output** tab (the yellow text at the top).

**Comment by c0wg0d** [comment]
It worked correctly when I redownloaded it, but is there any way to fix this issue manually?  This has happened on multiple channels and playlists, and I'd rather not re-download hundreds of videos.

**Comment by axcore** [comment]
>This has happened on multiple channels and playlists, and I'd rather not re-download hundreds of videos.

Great, the next time it happens, take a screenshot of the yellow text in the Output tab.

>but is there any way to fix this issue manually?

You can do **Operations > Tidy up files**, which will add orphaned videos to your database. They won't have the right titles but at least you'll be able to play them.

**Comment by c0wg0d** [comment]
I was able to fix this with the following steps:

- Delete the channel in Tartube (make sure you keep files and only remove the channel from Tartube!)
- Close Tartube
- Rename the channel folder in the Tartube downloads folder
- Open Tartube
- Re-add the channel in Tartube
- Right click on the channel and select "Check channel" - this should show all the videos without thumbnails
- Close Tartube
- Move the .data, .thumbs, and all the video files from the old, renamed channel folder into the new one
- Open Tartube
- Right click on the channel and select "Download channel"
- At this point, it should show that all the downloads were skipped because they have already been downloaded
- Restart Tartube again and it should show all the videos with thumbnails and properly linked both to YouTube and to the downloaded video file
