### ISSUE TITLE
How do you backup everything such as the folder structures & sub-folder structures for a total backup?

### ISSUE THREAD

**Issue by strunberg** [axcore/tartube#391]
I'm pretty OCD with the way I backup channels, and I was wondering if there was a way I could backup everything without spending hours manually recreating the folder structures.

**Comment by axcore** [comment]
**File > Database preferences** will show you the current data folder for Tartube, if you're not sure where it is.

Everything is in the folder - the videos sorted into sub-folders, the database file (tartube.db), backups of the database file, everything. So just make a backup copy of that folder.

**Comment by strunberg** [comment]
So this file structure would remain intact as displayed? This is what I'm concerned about as I've been archiving channels due to censorship.

![bvnbbvnvnbbv](https://user-images.githubusercontent.com/6355904/160257710-61311854-0c6c-4d55-8fbd-13992f318b76.png)

**Comment by strunberg** [comment]
It looks like it transferred all over correctly. Thank you for your help!
