### ISSUE TITLE
Installation on macOS

### ISSUE THREAD

**Issue by axcore** [axcore/tartube#393]
This replaces #246, #287, #348, #354 and others.

The README provides a method for installing Tartube on macOS, but it might not work for everyone.

If you have installed Tartube on macOS, please post on this thread.

If you can't install Tartube on macOS, please post on this thread.

**Comment by m3lab-zzl** [comment]
# Installation steps for Apple Silicon Mac

Basically, the steps in `README.md` file are useful, only some details need modification. I actually ran:

```sh
brew install cairo pkg-config python
pip install pycairo
brew install gobject-introspection gtk+3
pip install requests yt-dlp
brew install adwaita-icon-theme ffmpeg
```

After that, go to the unzipped source code folder and run `python tartube/tartube`.

If you ran into `gi` module not found error, it is probably PYTHONPATH issue, you need to specify the python package directory for homebrew!

```sh
which brew # get its location
# if it is /opt/homebrew/bin/brew
cd /opt/homebrew
find . -name "gi" # find out gi package location
# Add that location to PYTHONPATH variable, for example,
export PYTHONPATH=/opt/homebrew/lib/python3.9/site-packages:$PYTHONPATH
# add it to ~/.zshrc so that everytime launch a zsh shell, it can be added automatically
```

Cheers 🍻

**Comment by system1system2** [comment]
I followed all your instructions @m3lab-zzl, but I still got the gi module not found error. 
I followed your recommendation to `find . -name "gi"` and no result comes out.

**Comment by m3lab-zzl** [comment]
Did you modify the above instructions according to your own case? It would be better if you can post the command and output in your shell so we can check what happened.

"gi" module refers to PyGObject currently, try [this answer](https://stackoverflow.com/questions/44213921/python-3-installing-gi-package-with-pip#:~:text=The%20chosen%20answer,doc%2C%20right%20above).), it may help you.

Cheers.

**Comment by system1system2** [comment]
It works. Thank you!

The installation provided by @m3lab-zzl + the following addition (in case you have the `gi module not found error` error) fixed the tartube installation on my macOS 12.5.1 with M1 Pro:

`pip3 install PyGObject`

**Comment by AvrahamTsaban** [comment]
summary of installation steps (worked for me)
```
brew install cairo pkg-config python
pip3 install pycairo
brew install gobject-introspection gtk+3
pip3 install requests yt-dlp
brew install adwaita-icon-theme ffmpeg
pip3 install PyGObject
python3 {PATH}/tartube/tartube
```
replace {PATH} according to unzipped source code folder, of course

the remaining question: How should I make the program work as an app, without the need of opening terminal (and keeping it open)?

**Comment by axcore** [comment]
I am standing by the update the README as soon as you are all happy with the installation method.

By the way, on the subject of making Tartube work as an app: presumably it should be installed (either with `pip3 install tartube` in any directory, or `python3 setup.py install` inside Tartube's source code directory, the one containing `setup.py`). If the desktop file (../pack/tartube.desktop) is not copied to the correct folder (maybe `/usr/share/applications` ?), then do that manually. The desktop file needs to be edited to add a line, telling MacOS that it's a GUI application.

Regrettably, I googled the step-by-step method for doing that last night, and this morning I can't find it.

**Comment by AvrahamTsaban** [comment]
1. 
Last output lines for python3 setup.py install:
```
installing package data to build/bdist.macosx-12-x86_64/egg
running install_data
creating /tartube
error: could not create '/tartube': Read-only file system
```
What does it mean?

2.
I found no /usr/share/applications on my macos. I do not know how to find equivalent path for mac; another's help is needed.

3.
What line should I add to tartube.desktop?

**Comment by axcore** [comment]
1. Probably you need to give yourself permission to write files in system folders, on Linux the command would be `su python3 setup.py install`

2/3. I don't know the answers

**Comment by AvrahamTsaban** [comment]
You mean sudo (Mac has no su)...
same problem

**Comment by axcore** [comment]
I have update the [README](https://github.com/axcore/tartube) with additional installation instructions. Do let me know if I've bungled it.

**Comment by iitjee** [comment]
Try `brew install pygobject3 gtk+3`

**Comment by Ninja-man07** [comment]
did u check all your spelling and links sometimes depending on your level of involvement it can come down to stupid little mistakes like that!lol i don't know your experience or level of involvement. If you wrote the code yourself chances are you misspelled something. Other than that one of the orders is off in the workflow or not opened go backs while you're workflows and retest everything

**Comment by axcore** [comment]
Closed after I successfully tested installation on an actual Mac.
