### ISSUE TITLE
Add support for .webp thumbnails

### ISSUE THREAD

**Issue by iamtherobin** [axcore/tartube#395]
A lot of youtube thumbnails are coming in as .webp these days. It will only grow in number as time goes on. Right now I enable to option to have ffmpeg convert them so they show up in tartube. However, it would be better if tartube supported displaying the .webp directly since they compress better than jpeg and remove one unnecessary conversion step.

**Comment by axcore** [comment]
Unfortunately the Gtk library does not support displaying .webp images, as far as I know.
