### ISSUE TITLE
Failed to load Tartube database file

### ISSUE THREAD

**Issue by heywolf15** [axcore/tartube#396]
### What operating system are you using?
 Windows 10

### What version of Tartube are you using?
v2.3.484

![Capture](https://user-images.githubusercontent.com/34807171/162328697-5426548d-0a42-4c93-9546-6d77f5fe5eae.PNG)

**Comment by axcore** [comment]
Look in the folder where Tartube is storing videos. There should be a folder called .backups. 

That folder contains previous saves of your database. Try copying the most recent one into the folder above, replacing the broken tartube.db file there.

As for the error itself: I can't explain it. I googled the error message and found several solutions, all of which are already in the Tartube code:

```
        try:
            fh = open(path, 'rb')
            load_dict = pickle.load(fh)
            fh.close()
```

**Comment by heywolf15** [comment]
I actually try that by deleting "BU" in the name, but I got this
![Capture](https://user-images.githubusercontent.com/34807171/162415174-1485cf6d-ec6a-4ac0-b6a9-aca172e19d6c.PNG)

**Comment by axcore** [comment]
Sorry, I don't know how to resolve this error or even how to retrieve your database.

Your only option now is to start a new database. Add the channels and playlists you had before, click the **Check all** button, then click **Operations > Refresh database**, which will mark all the videos as actually downloaded.

**Comment by heywolf15** [comment]
Thank you for help, I think this is happening when my laptop suddenly lose power.

**Comment by axcore** [comment]
If your computer loses power at the moment the database file is being saved, then it will definitely be corrupted and will not be recoverable.

**Comment by heywolf15** [comment]
It's not in the save state, just when is open
