### ISSUE TITLE
Keep getting same Downloads failed error: Nothing happened?

### ISSUE THREAD

**Issue by yaba1** [axcore/tartube#397]
Support inquiry:

 Hello Tartube Downloader support,

Recently recently came across your great Tartube Downloader using on my  (WINDOWS 10 16GB RAM PC).

After reading thru your support & help articles, I am still having trouble, trying to simply add short approx 5 min Youtube videos for download and save to my PC downloads folder as HD 1080 MP4, 1 at a time,I select to trim off of Un-desired parts of video clips, 10 sec off video start, and trim off approx only 30 seconds off the end of each video, tried 1 video per time, but Keep getting same error: [Nothing happened?], 
**I tried updating yt-dlp
**setting downloader file path**tried using FFMPEG - This takes far too long , had to cancel this process
 Tried your website troubleshoot instruction several times as per below: Go to a video website, and find your favourite channel In Tartube's main window, click the Classic Mode tab Copy the link to the channel (URL) into the box at the top of tab Just below that, click the button to select a download destination and a video/audio format Click the Add URLs button, When you're ready, click the Download all button

**If you can please advise back on why Tartube Downloader fails to work on any Youtube videos tried?
 I would love to give all Excellent 5 start online Reviews & Comments for this App, if at least some of these superhot options can be addressed.

Please do advise back. Thanks for your time & help.

**Comment by axcore** [comment]
>tried using FFMPEG - This takes far too long , had to cancel this process

If you want want to remove sections from videos, you must install FFmpeg. 

I know it takes a long time, but you must be patient.

>I select to trim off of Un-desired parts of video clips

Make sure you are using Tartube v2.3.549. There were some bugs in v2.3.484.

**Comment by yaba1** [comment]
Hello,
Thanks for the quick reply.
Yes, I confirmed I have the Tartube v2.3.549 version, but there appears to
be a few bugs in this version as well.
I installed the very large FFMPEG on my PC when installed Tartube, but no
matter what downloader tried in tartube, even changed the video output
folder from
from my PC , to an external thumbdrive, still, all videos fail to download,
No real reason given on the failure, over and over.

I have been using online downloaders for years, most of the even free ones,
allow you simply add URL, then simply downloads multiple videos in less
than 30 seconds,
without much issue.
**Tartube appears to have many advanced options, so was hoping could simply
add URL, then select desired part of online video wanted, then I thought
Tartube could quickly download desired part of video only to HD MP4 format,
so I am not stuck with all the un-desired fluff in video clips.

However Tartube appears to have some un-resolved bugs, and just not as user
friendly, takes over 10 times the space of other working downloaders,
have lost a couple days trying to figure out issues, so will have to move
on for now, hopefully will check back in near future to see if all these
issues have been resolved,
and a bit more user friendly. Thanks for your time.

**Comment by axcore** [comment]
>Yes, I confirmed I have the Tartube v2.3.549 version
That version is six months old, if you try again, make sure you have the latest version.

>I installed the very large FFMPEG on my PC when installed Tartube
>However Tartube... takes over 10 times the space of other working downloaders,
Tartube is Linux software. When you install it on MS Windows, you are installing not just Tartube, but a mini operating system and new graphics libraries. It takes up a lot of space.

> I thought Tartube could quickly download desired part of video only to HD MP4 format, so I am not stuck with all the un-desired fluff in video clips.
yt-dlp cannot do this, unless FFmpeg is installed. If you want, you can try to download a video, and then show me a screenshot of your **Output** tab, so I can try to guess what is going wrong.
