### ISSUE TITLE
Disable downloading comments as global option for checking videos

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#398]
On 2.3.549 with yt-dlp 20220408 trying to diagnose another issue by first checking newly added channel before downloading.

https://www.youtube.com/c/BBQwithFranklin/videos

Channel has 37 videos, but only 24 were "checked" because of timeout downloading comments:
![image](https://user-images.githubusercontent.com/16659133/162846360-92029e61-4cfe-490d-a6f5-fce5424658dc.png)

Command line is:
python3 D:\Audacity\_youtube\yt-dlp-20220408 --newline -i --hls-prefer-native --write-description --write-info-json --write-annotations --cookies D:/Audacity/_youtube/cookies.txt --write-thumbnail --merge-output-format mkv --write-sub --embed-thumbnail --add-metadata --sub-lang en --output D:/Audacity/_youtube/Cooking/BBQ with Franklin/%(uploader)s - (%(upload_date)s) - %(title)s - %(id)s - [%(format_id)s#%(height)sp].%(ext)s **--get-comments** --extractor-args youtube:comment_sort=top -f bestvideo[ext=webm][height<=?480][fps<=?30]+bestaudio[ext=webm]/bestvideo[height<=?480][fps<=?30]+bestaudio/best[height<=?480]/best --dump-json --download-archive D:/Audacity/_youtube/Cooking/BBQ with Franklin/ytdl-archive.txt --windows-filenames https://www.youtube.com/c/BBQwithFranklin/videos
[BBQ with Franklin] <Simulated download of: 'BBQwithFranklin - (20160108) - BBQ with Franklin Outtakes - Patience - GuJSzWTrjmM - [244+251#480p]'>

**Assuming that yt-dlp re-downloads the JSON on an actual download command [which it looks like it does], can you have a global option to strip out the "--get-comments" command from "check" commands to avoid the timeout errors?**

If yt-dlp does not re-download JSON on an actual download command, please provide an option to ignore timeouts on checking videos to make sure all the comments and videos will be checked successfully :)

In looking at the folder I realized that only the thumbnail was being saved, so I set the option to keep description and JSON files on a check and it seems to have removed the timeout, is that correct? If that's the case, is there a way to prevent yt-dlp from redownloading those files on an actual download if they already exist?

So after setting it to save the description and JSON files during the check, I did an actual download and it pulled all the comments all over again:
python3 D:\Audacity\_youtube\yt-dlp-20220408 --newline -i --hls-prefer-native --write-description --write-info-json --write-annotations --cookies D:/Audacity/_youtube/cookies.txt --write-thumbnail --merge-output-format mkv --write-sub --embed-thumbnail --add-metadata --sub-lang en --output D:/Audacity/_youtube/Cooking/BBQ with Franklin/%(uploader)s - (%(upload_date)s) - %(title)s - %(id)s - [%(format_id)s#%(height)sp].%(ext)s --get-comments --extractor-args youtube:comment_sort=top -f bestvideo[ext=webm][height<=?480][fps<=?30]+bestaudio[ext=webm]/bestvideo[height<=?480][fps<=?30]+bestaudio/best[height<=?480]/best --download-archive D:/Audacity/_youtube/Cooking/BBQ with Franklin/ytdl-archive.txt --windows-filenames https://www.youtube.com/watch?v=VmTzdMHu5KU
[youtube] VmTzdMHu5KU: Downloading webpage
[youtube] VmTzdMHu5KU: Downloading android player API JSON
[youtube] Downloading comment section API JSON
[youtube] Downloading comment API JSON page 1 (0/1645)
[youtube] Downloading ~1645 comments
[youtube] Sorting comments by top comments
[youtube]     Downloading comment API JSON reply thread 1 (1/1645)
[youtube]     Downloading comment API JSON reply thread 2 (6/1645)
[youtube]        Downloading comment replies API JSON page 1 (16/1645)
[youtube]     Downloading comment API JSON reply thread 3 (35/1645)
[youtube]        Downloading comment replies API JSON page 1 (43/1645)
[youtube]     Downloading comment API JSON reply thread 4 (50/1645)
[youtube]        Downloading comment replies API JSON page 1 (59/1645)
[youtube]        Downloading comment replies API JSON page 2 (100/1645)
[youtube]     Downloading comment API JSON reply thread 5 (133/1645)
[youtube] Downloading comment API JSON page 2 (141/1645)
[youtube]     Downloading comment API JSON reply thread 1 (160/1645)
[youtube] Downloading comment API JSON page 3 (165/1645)
[youtube]     Downloading comment API JSON reply thread 1 (177/1645)
[youtube]     Downloading comment API JSON reply thread 2 (189/1645)
[youtube]        Downloading comment replies API JSON page 1 (199/1645)
[youtube] Downloading comment API JSON page 4 (211/1645)
[youtube]     Downloading comment API JSON reply thread 1 (224/1645)
[youtube]     Downloading comment API JSON reply thread 2 (231/1645)
[youtube] Downloading comment API JSON page 5 (234/1645)
[youtube]     Downloading comment API JSON reply thread 1 (247/1645)
[youtube] Downloading comment API JSON page 6 (255/1645)
[youtube]     Downloading comment API JSON reply thread 1 (256/1645)
[youtube]     Downloading comment API JSON reply thread 2 (272/1645)
[youtube] Downloading comment API JSON page 7 (279/1645)
[youtube]     Downloading comment API JSON reply thread 1 (280/1645)
[youtube]        Downloading comment replies API JSON page 1 (290/1645)
[youtube]     Downloading comment API JSON reply thread 2 (299/1645)
[youtube]     Downloading comment API JSON reply thread 3 (305/1645)
[youtube]     Downloading comment API JSON reply thread 4 (316/1645)
[youtube]     Downloading comment API JSON reply thread 5 (325/1645)
[youtube] Downloading comment API JSON page 8 (328/1645)
[youtube]     Downloading comment API JSON reply thread 1 (329/1645)
[youtube]     Downloading comment API JSON reply thread 2 (339/1645)
[youtube]     Downloading comment API JSON reply thread 3 (351/1645)
[youtube]     Downloading comment API JSON reply thread 4 (359/1645)
[youtube]     Downloading comment API JSON reply thread 5 (361/1645)
[youtube]     Downloading comment API JSON reply thread 6 (363/1645)
[youtube] Downloading comment API JSON page 9 (367/1645)
[youtube]     Downloading comment API JSON reply thread 1 (368/1645)
[youtube]        Downloading comment replies API JSON page 1 (376/1645)
[youtube]     Downloading comment API JSON reply thread 2 (389/1645)
[youtube]     Downloading comment API JSON reply thread 3 (392/1645)
[youtube]     Downloading comment API JSON reply thread 4 (412/1645)
[youtube]        Downloading comment replies API JSON page 1 (419/1645)
[youtube] Downloading comment API JSON page 10 (436/1645)
[youtube]     Downloading comment API JSON reply thread 1 (440/1645)
[youtube]     Downloading comment API JSON reply thread 2 (444/1645)
[youtube]     Downloading comment API JSON reply thread 3 (451/1645)
[youtube]     Downloading comment API JSON reply thread 4 (454/1645)
[youtube]        Downloading comment replies API JSON page 1 (463/1645)
[youtube]     Downloading comment API JSON reply thread 5 (469/1645)
[youtube] Downloading comment API JSON page 11 (475/1645)
[youtube]     Downloading comment API JSON reply thread 1 (476/1645)
[youtube]     Downloading comment API JSON reply thread 2 (491/1645)
[youtube]     Downloading comment API JSON reply thread 3 (501/1645)
[youtube]     Downloading comment API JSON reply thread 4 (504/1645)
[youtube] Downloading comment API JSON page 12 (508/1645)
[youtube]     Downloading comment API JSON reply thread 1 (509/1645)
[youtube]     Downloading comment API JSON reply thread 2 (524/1645)
[youtube]     Downloading comment API JSON reply thread 3 (532/1645)
[youtube]     Downloading comment API JSON reply thread 4 (534/1645)
[youtube] Downloading comment API JSON page 13 (536/1645)
[youtube]     Downloading comment API JSON reply thread 1 (537/1645)
[youtube]     Downloading comment API JSON reply thread 2 (543/1645)
[youtube]     Downloading comment API JSON reply thread 3 (550/1645)
[youtube]     Downloading comment API JSON reply thread 4 (558/1645)
[youtube] Downloading comment API JSON page 14 (564/1645)
[youtube]     Downloading comment API JSON reply thread 1 (565/1645)
[youtube]     Downloading comment API JSON reply thread 2 (572/1645)
[youtube]     Downloading comment API JSON reply thread 3 (582/1645)
[youtube]     Downloading comment API JSON reply thread 4 (585/1645)
[youtube]     Downloading comment API JSON reply thread 5 (590/1645)
[youtube] Downloading comment API JSON page 15 (592/1645)
[youtube]     Downloading comment API JSON reply thread 1 (593/1645)
[youtube]        Downloading comment replies API JSON page 1 (603/1645)
[youtube]     Downloading comment API JSON reply thread 2 (621/1645)
[youtube] Downloading comment API JSON page 16 (624/1645)
[youtube]     Downloading comment API JSON reply thread 1 (626/1645)
[youtube]     Downloading comment API JSON reply thread 2 (632/1645)
[youtube]     Downloading comment API JSON reply thread 3 (637/1645)
[youtube]     Downloading comment API JSON reply thread 4 (645/1645)
[youtube] Downloading comment API JSON page 17 (650/1645)
[youtube]     Downloading comment API JSON reply thread 1 (665/1645)
[youtube] Downloading comment API JSON page 18 (671/1645)
[youtube]     Downloading comment API JSON reply thread 1 (677/1645)
[youtube] Downloading comment API JSON page 19 (695/1645)
[youtube]     Downloading comment API JSON reply thread 1 (706/1645)
[youtube]     Downloading comment API JSON reply thread 2 (708/1645)
[youtube]     Downloading comment API JSON reply thread 3 (716/1645)
[youtube] Downloading comment API JSON page 20 (719/1645)
[youtube]     Downloading comment API JSON reply thread 1 (725/1645)
[youtube]     Downloading comment API JSON reply thread 2 (731/1645)
[youtube] Downloading comment API JSON page 21 (743/1645)
[youtube]     Downloading comment API JSON reply thread 1 (747/1645)
[youtube]     Downloading comment API JSON reply thread 2 (756/1645)
[youtube]     Downloading comment API JSON reply thread 3 (761/1645)
[youtube]     Downloading comment API JSON reply thread 4 (766/1645)
[youtube] Downloading comment API JSON page 22 (771/1645)
[youtube]     Downloading comment API JSON reply thread 1 (778/1645)
[youtube]     Downloading comment API JSON reply thread 2 (790/1645)
[youtube] Downloading comment API JSON page 23 (800/1645)
[youtube]     Downloading comment API JSON reply thread 1 (803/1645)
[youtube]     Downloading comment API JSON reply thread 2 (807/1645)
[youtube]     Downloading comment API JSON reply thread 3 (813/1645)
[youtube]     Downloading comment API JSON reply thread 4 (817/1645)
[youtube]     Downloading comment API JSON reply thread 5 (820/1645)
[youtube]     Downloading comment API JSON reply thread 6 (822/1645)
[youtube]     Downloading comment API JSON reply thread 7 (824/1645)
[youtube]     Downloading comment API JSON reply thread 8 (828/1645)
[youtube] Downloading comment API JSON page 24 (830/1645)
[youtube]     Downloading comment API JSON reply thread 1 (831/1645)
[youtube]     Downloading comment API JSON reply thread 2 (850/1645)
[youtube] Downloading comment API JSON page 25 (853/1645)
[youtube]     Downloading comment API JSON reply thread 1 (859/1645)
[youtube]     Downloading comment API JSON reply thread 2 (863/1645)
[youtube]     Downloading comment API JSON reply thread 3 (866/1645)
[youtube]     Downloading comment API JSON reply thread 4 (872/1645)
[youtube] Downloading comment API JSON page 26 (878/1645)
[youtube] Downloading comment API JSON page 27 (898/1645)
[youtube]     Downloading comment API JSON reply thread 1 (903/1645)
[youtube]     Downloading comment API JSON reply thread 2 (915/1645)
[youtube] Downloading comment API JSON page 28 (920/1645)
[youtube]     Downloading comment API JSON reply thread 1 (925/1645)
[youtube]     Downloading comment API JSON reply thread 2 (927/1645)
[youtube] Downloading comment API JSON page 29 (942/1645)
[youtube]     Downloading comment API JSON reply thread 1 (946/1645)
[youtube]     Downloading comment API JSON reply thread 2 (955/1645)
[youtube] Downloading comment API JSON page 30 (967/1645)
[youtube]     Downloading comment API JSON reply thread 1 (969/1645)
[youtube]     Downloading comment API JSON reply thread 2 (983/1645)
[youtube] Downloading comment API JSON page 31 (989/1645)
[youtube]     Downloading comment API JSON reply thread 1 (1002/1645)
[youtube]     Downloading comment API JSON reply thread 2 (1015/1645)
[youtube] Downloading comment API JSON page 32 (1016/1645)
[youtube]     Downloading comment API JSON reply thread 1 (1024/1645)
[youtube]     Downloading comment API JSON reply thread 2 (1031/1645)
[youtube]     Downloading comment API JSON reply thread 3 (1035/1645)
[youtube] Downloading comment API JSON page 33 (1038/1645)
[youtube]     Downloading comment API JSON reply thread 1 (1044/1645)
[youtube]     Downloading comment API JSON reply thread 2 (1052/1645)
[youtube]     Downloading comment API JSON reply thread 3 (1057/1645)
[youtube]     Downloading comment API JSON reply thread 4 (1062/1645)
[youtube] Downloading comment API JSON page 34 (1065/1645)
[youtube]     Downloading comment API JSON reply thread 1 (1066/1645)
[youtube]     Downloading comment API JSON reply thread 2 (1075/1645)
[youtube]     Downloading comment API JSON reply thread 3 (1082/1645)
[youtube]     Downloading comment API JSON reply thread 4 (1085/1645)
[youtube]     Downloading comment API JSON reply thread 5 (1088/1645)
[youtube]     Downloading comment API JSON reply thread 6 (1091/1645)
[youtube] Downloading comment API JSON page 35 (1096/1645)
[youtube]     Downloading comment API JSON reply thread 1 (1105/1645)
[youtube] Downloading comment API JSON page 36 (1117/1645)
[youtube]     Downloading comment API JSON reply thread 1 (1129/1645)
[youtube]     Downloading comment API JSON reply thread 2 (1132/1645)
[youtube]     Downloading comment API JSON reply thread 3 (1138/1645)
[youtube]     Downloading comment API JSON reply thread 4 (1143/1645)
[youtube] Downloading comment API JSON page 37 (1146/1645)
[youtube]     Downloading comment API JSON reply thread 1 (1148/1645)
[youtube]     Downloading comment API JSON reply thread 2 (1157/1645)
[youtube]     Downloading comment API JSON reply thread 3 (1166/1645)
[youtube] Downloading comment API JSON page 38 (1171/1645)
[youtube]     Downloading comment API JSON reply thread 1 (1176/1645)
[youtube]     Downloading comment API JSON reply thread 2 (1183/1645)
[youtube] Downloading comment API JSON page 39 (1195/1645)
[youtube]     Downloading comment API JSON reply thread 1 (1207/1645)
[youtube]     Downloading comment API JSON reply thread 2 (1213/1645)
[youtube]     Downloading comment API JSON reply thread 3 (1216/1645)
[youtube] Downloading comment API JSON page 40 (1218/1645)
[youtube]     Downloading comment API JSON reply thread 1 (1219/1645)
[youtube] Downloading comment API JSON page 41 (1239/1645)
[youtube]     Downloading comment API JSON reply thread 1 (1241/1645)
[youtube]     Downloading comment API JSON reply thread 2 (1246/1645)
[youtube]     Downloading comment API JSON reply thread 3 (1251/1645)
[youtube]     Downloading comment API JSON reply thread 4 (1260/1645)
[youtube] Downloading comment API JSON page 42 (1266/1645)
[youtube]     Downloading comment API JSON reply thread 1 (1272/1645)
[youtube]     Downloading comment API JSON reply thread 2 (1277/1645)
[youtube]     Downloading comment API JSON reply thread 3 (1286/1645)
[youtube]     Downloading comment API JSON reply thread 4 (1289/1645)
[youtube] Downloading comment API JSON page 43 (1291/1645)
[youtube]     Downloading comment API JSON reply thread 1 (1305/1645)
[youtube]     Downloading comment API JSON reply thread 2 (1309/1645)
[youtube] Downloading comment API JSON page 44 (1313/1645)
[youtube]     Downloading comment API JSON reply thread 1 (1316/1645)
[youtube]     Downloading comment API JSON reply thread 2 (1321/1645)
[youtube] Downloading comment API JSON page 45 (1342/1645)
[youtube]     Downloading comment API JSON reply thread 1 (1346/1645)
[youtube]     Downloading comment API JSON reply thread 2 (1348/1645)
[youtube]     Downloading comment API JSON reply thread 3 (1357/1645)
[youtube]     Downloading comment API JSON reply thread 4 (1361/1645)
[youtube]     Downloading comment API JSON reply thread 5 (1365/1645)
[youtube] Downloading comment API JSON page 46 (1370/1645)
[youtube]     Downloading comment API JSON reply thread 1 (1389/1645)
[youtube] Downloading comment API JSON page 47 (1391/1645)
[youtube]     Downloading comment API JSON reply thread 1 (1397/1645)
[youtube] Downloading comment API JSON page 48 (1412/1645)
[youtube]     Downloading comment API JSON reply thread 1 (1420/1645)
[youtube]     Downloading comment API JSON reply thread 2 (1422/1645)
[youtube]     Downloading comment API JSON reply thread 3 (1433/1645)
[youtube]     Downloading comment API JSON reply thread 4 (1436/1645)
[youtube]     Downloading comment API JSON reply thread 5 (1438/1645)
[youtube]     Downloading comment API JSON reply thread 6 (1440/1645)
[youtube]     Downloading comment API JSON reply thread 7 (1443/1645)
[youtube] Extracted 1449 comments
[info] VmTzdMHu5KU: Downloading 1 format(s): 244+251
[info] Writing video description to: D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121025) - BBQ with Franklin - The Brisket - VmTzdMHu5KU - [244+251#480p].description
[info] Downloading video thumbnail 41 ...
WARNING: Unable to download video thumbnail 41: HTTP Error 404: Not Found
Deleting existing file D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121025) - BBQ with Franklin - The Brisket - VmTzdMHu5KU - [244+251#480p].jpg
[info] Downloading video thumbnail 40 ...
[info] Writing video thumbnail 40 to: D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121025) - BBQ with Franklin - The Brisket - VmTzdMHu5KU - [244+251#480p].jpg
[info] Writing video metadata as JSON to: D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121025) - BBQ with Franklin - The Brisket - VmTzdMHu5KU - [244+251#480p].info.json
WARNING: There are no annotations to write.
[download] Destination: D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121025) - BBQ with Franklin - The Brisket - VmTzdMHu5KU - [244+251#480p].f244.webm
[download] 100% of 21.90MiB in 00:03
[download] Destination: D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121025) - BBQ with Franklin - The Brisket - VmTzdMHu5KU - [244+251#480p].f251.webm
[download] 100% of 6.99MiB in 00:01
[Merger] Merging formats into "D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121025) - BBQ with Franklin - The Brisket - VmTzdMHu5KU - [244+251#480p].mkv"
Deleting original file D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121025) - BBQ with Franklin - The Brisket - VmTzdMHu5KU - [244+251#480p].f244.webm (pass -k to keep)
Deleting original file D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121025) - BBQ with Franklin - The Brisket - VmTzdMHu5KU - [244+251#480p].f251.webm (pass -k to keep)
[Metadata] Adding metadata to "D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121025) - BBQ with Franklin - The Brisket - VmTzdMHu5KU - [244+251#480p].mkv"
[EmbedThumbnail] ffmpeg: Adding thumbnail to "D:/Audacity/_youtube/Cooking/BBQ with Franklin/BBQwithFranklin - (20121025) - BBQ with Franklin - The Brisket - VmTzdMHu5KU - [244+251#480p].mkv

**Comment by axcore** [comment]
>Assuming that yt-dlp re-downloads the JSON on an actual download command [which it looks like it does], can you have a global option to strip out the "--get-comments" command from "check" commands to avoid the timeout errors?

`--get-comments` does not appear anywhere in the Tartube source code. Perhaps you added it yourself in **Edit > General download options...**, in the **Additional download options** box.

`--get-comments` is an alias for `--write-comments`. which is disabled by default (Edit > System preferences... > Operations > Comments > When checking/downloading videos, store comments in the metadata file)

>Assuming that yt-dlp re-downloads the JSON on an actual download command [which it looks like it does]

Yes, it does.

>In looking at the folder I realized that only the thumbnail was being saved, so I set the option to keep description and JSON files on a check and it seems to have removed the timeout, is that correct?

I don't think so. When at least one video is checked, the process times out if another video is not checked within 60 seconds. The options to keep description/JSON files should not change the behaviour.

>If that's the case, is there a way to prevent yt-dlp from redownloading those files on an actual download if they already exist?

You can try the download option `--no-overwrites'. It is not one of Tartube's download options, so you would have to add it in **Edit > General download options... > Additional download options**.

Ideally, you would want a '--no-metadata-overwrites' option, perhaps you can ask the yt-dlp add it.

**Comment by axcore** [comment]
By the way, the JSON timeout can be disabled in **Edit > System preferences... > Operations > Downloads**. Deselect **When checking videos, apply a 60-second timeout**.

**Comment by axcore** [comment]
I made the following changes:

There are now two separate timeouts, one for checking without comments, one for checking with comments. I increased the default time from 1 minute to 2 minutes. See **Edit > System preferences... > Operations > Downloads**

You can now fetch comments when checking videos, or when downloading videos, or both. See **Edit > System preferences... > Operations > Comments**.

I added the `--no-overwrites` option to the window, see **Edit > General download options... > Files > Filesystem**.

(Modified code to follow.)

**Comment by axcore** [comment]
Added in v2.3.562.
