### ISSUE TITLE
Errors on launch

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#399]
Fresh install of 2.3.549 and get this in terminal upon launching Tartube:

$ python3 tartube/tartube
Traceback (most recent call last):
  File "C:/Users\Owner\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/mainapp.py", line 3056, in do_activate
    self.start()
  File "C:/Users\Owner\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/mainapp.py", line 3290, in start
    self.start_continue(new_config_flag)
  File "C:/Users\Owner\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/mainapp.py", line 3462, in start_continue
    self.load_db()
  File "C:/Users\Owner\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/mainapp.py", line 5814, in load_db
    self.main_win_obj.drag_drop_grid_reset()
  File "C:/Users\Owner\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/mainwin.py", line 12802, in drag_drop_grid_reset
    options_obj = self.app_obj.options_reg_dict[uid]
KeyError: 4
C:/Users/Owner/Documents/___Apps/Tartube/msys64/mingw64/lib/python3.9/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'strikethrough-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
C:/Users/Owner/Documents/___Apps/Tartube/msys64/mingw64/lib/python3.9/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'underline-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
C:/Users/Owner/Documents/___Apps/Tartube/msys64/mingw64/lib/python3.9/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'weight-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
C:/Users/Owner/Documents/___Apps/Tartube/msys64/mingw64/lib/python3.9/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'style-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)

Then on changing viewed folder this will be added to the terminal:
C:/Users/Owner/Documents/___Apps/Tartube/msys64/mingw64/lib/python3.9/site-packages/gi/overrides/Gtk.py:1326: Warning: unable to set property 'strikethrough-set' of type 'gboolean' from value of type 'gchararray'
  Gtk.TreeStore.set(self, treeiter, columns, values)
C:/Users/Owner/Documents/___Apps/Tartube/msys64/mingw64/lib/python3.9/site-packages/gi/overrides/Gtk.py:1326: Warning: unable to set property 'underline-set' of type 'gboolean' from value of type 'gchararray'
  Gtk.TreeStore.set(self, treeiter, columns, values)
C:/Users/Owner/Documents/___Apps/Tartube/msys64/mingw64/lib/python3.9/site-packages/gi/overrides/Gtk.py:1326: Warning: unable to set property 'weight-set' of type 'gboolean' from value of type 'gchararray'
  Gtk.TreeStore.set(self, treeiter, columns, values)
C:/Users/Owner/Documents/___Apps/Tartube/msys64/mingw64/lib/python3.9/site-packages/gi/overrides/Gtk.py:1326: Warning: unable to set property 'style-set' of type 'gboolean' from value of type 'gchararray'
  Gtk.TreeStore.set(self, treeiter, columns, values)

**Comment by axcore** [comment]
Confirmed, the steps to reproduce this error are:

1. Create a channel called "wibble"
2. Apply download options to the channel
3. Add the download options "wibble" in the Drag and Drop tab
4. Remove download options from the channel
5. Restart Tartube

By the way, the `Warning: unable to set property` messages are a bug in Gtk, not related to Tartube or to your bug.

**Comment by axcore** [comment]
Should be fixed in v2.3.562.
