### ISSUE TITLE
60fps

### ISSUE THREAD

**Issue by noahastor** [axcore/tartube#40]
Is there a way to download a video in 60fps?

[youtube-dl displays the 60fps video formats options with -F command so maybe there is a way to work around that.]

**Comment by axcore** [comment]
>Is there a way to download a video in 60fps?

Can you give me the URL of the video you're trying to download?

**Comment by noahastor** [comment]
Sure:

https://www.youtube.com/watch?v=BeFHLad0Zpo

**Comment by axcore** [comment]
Short answer: I can add this in the next release.

Long answer: Specify the extractor code you want directly. youtube-dl -F produces this list of formats:

![codes2](https://user-images.githubusercontent.com/37951926/72441711-0cabbd00-37a3-11ea-8019-2da5b021d7a1.png)

So if you want .mp4 1080p60, use the download option **-f 299**

From the Tartube menu, Edit > General download options... > General, add add it to the box:

![codes3](https://user-images.githubusercontent.com/37951926/72442076-bc812a80-37a3-11ea-9f5b-89e23f5d12cf.png)

In the Formats tab, make sure no formats are in the box on the right-hand side:

![codes4](https://user-images.githubusercontent.com/37951926/72442143-df134380-37a3-11ea-8a8f-9b25af8cae8e.png)

Using these settings, I downloaded a ~750MB video, which seems to be the right one.

**Comment by axcore** [comment]
v1.3.042 adds new formats to Edit > General download options... > Formats > Available video formats.

Feel free to re-open this issue if you have any further problems.

**Comment by noahastor** [comment]
Thank you very much
