### ISSUE TITLE
Low / no disk space issues

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#400]
On running out of disk space Tartube file load/save gets disabled until Tartube is relaunched. 

This needs to not be the case as I manually freed up space but then couldn't save the DB, losing a night's worth of info in Tartube. 

Upon closing and opening tartube, I did a refresh on the directory and all of the videos that downloaded during the process when space ran out did not appear in tartube.

Also, if you dismiss the low space warning (because you're going to free up space right then) it won't warn you again when you get low... and then the above happens again. IE get down to 300mb free, dismiss low space warning, free up 10gb of space, then a few days later run out of space without another low space warning.

Thanks again for all of your awesome work on this Axcore, and just let me know how I can help test!

**Comment by axcore** [comment]
>losing a night's worth of info in Tartube.

The work is not lost. Just **Check** the affected channels/playlists, which will add videos to the database. Then **Refresh** them (for example, right-click a channel and select Channel actions > Refresh channel, or in the main menu, Operations > Refresh database), which will mark the videos as downloaded.

I am working on your other bug reports, so you will get a response today.

**Comment by ceonelson** [comment]
Hmm I did a refresh and they didn't appear but not sure if I checked the channel first. I'll see if I can remember what folder that was on to try it out. Either way being able to manually save the Tartube db once space is freed up (or even save it to a different drive) would be helpful for the future :)

Thanks Axcore! I think #373 is the biggest one as I can't use any of the latest releases and I'm starting to get some errors when downloading because of youtube site changes that break the yt-dlp 20211227 version.

**Comment by axcore** [comment]
>This needs to not be the case as I manually freed up space but then couldn't save the DB, losing a night's worth of info in Tartube.

Yes, you are quite right about that. I have changed the code so that, if saving the database fails, loading/saving in general is not disabled, and the user has a chance to fix a problem like a full hard drive.

**Comment by axcore** [comment]
> Also, if you dismiss the low space warning (because you're going to free up space right then) it won't warn you again when you get low... and then the above happens again. IE get down to 300mb free, dismiss low space warning, free up 10gb of space, then a few days later run out of space without another low space warning.

In **Edit > System preferences > Files > Device** there are two settings: 'warn user' and 'halt downloads'.

The 'warn user' setting is checked only at the _start_ of a download, whereas the 'halt downloads' setting is checked continuously, throughout any download, every 0.5 seconds.

The text in the preferences window is confusing, so I have changed it to clarify the situation.

Did you, by any chance, enable the 'warn user' setting but disable the 'halt downloads' setting?

**Comment by axcore** [comment]
Added in v2.3.562.

**Comment by ceonelson** [comment]
Thanks Axcore! Both were enabled, warn was set to 1000 and halt to 300.
