### ISSUE TITLE
Can't adjust column headers on error screen

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#403]
First off, let me say the new filter panel on the error screen is awesome!

I am trying to get the last few videos to successfully download by using the Paths hack #299 for a channel and there's 4 that didn't finish out of almost 900. On the error tab I went to go extend the video column so I could read the full video name, but it looks like the column widths are locked. Can they be adjustable like they are on the progress tab?

Also, I'm not sure if it is related but here are the most recent messages in the console:

(tartube:13936): Pango-CRITICAL **: 00:13:37.261: pango_layout_get_line_count: assertion 'layout != NULL' failed

(tartube:13936): Gtk-CRITICAL **: 00:13:37.261: gtk_render_layout: assertion 'PANGO_IS_LAYOUT (layout)' failed

Thanks Axcore!

**Comment by axcore** [comment]
Added in v2.3.613.
