### ISSUE TITLE
Download Options Bug

### ISSUE THREAD

**Issue by mbnoimi** [axcore/tartube#405]
Hi,

After upgrading to recent version (2.3.562) some folder no longer able to edit their download option and no longer downloadable (Process tabs show "waiting") and Tartube stop working unless I quit it.

In the attachment an example of my Tartube database.

**Comment by axcore** [comment]
Fixed in v2.3.613. Sorry for the inconvenience.

Your database has incorrect video counts. It is not a serious problem, but you can fix it by clicking **File > Check database integrity** (if you want to).
