### ISSUE TITLE
Autonumber always starts from 001 when downloading from YouTube channel

### ISSUE THREAD

**Issue by soopercow** [axcore/tartube#406]
When using download options as part of filename when downloading from a YouTube channel, the autonumber always resets to 001 for each new session. Works perfectly for playlists.

**Comment by axcore** [comment]
I tested this in a terminal window using this command:

`yt-dlp --output "%(autonumber)s-%(title)s.%(ext)s" --download-archive archive.txt https://www.youtube.com/c/hiddentracktv2/videos`

I saw the same problem as you. It's not a Tartube issue, so you can report it to the [yt-dlp developers](https://github.com/yt-dlp/yt-dlp/issues).

`yt-dlp --output "%(autonumber)s-%(title)s.%(ext)s" --download-archive archive.txt https://www.youtube.com/c/hiddentracktv2/videos`
https://github.com/yt-dlp/yt-dlp/issues

 and saw the same problem, so it's not a Tartube issue.

**Comment by axcore** [comment]
According to yt-dlp devs, this is the correct behaviour. See the link above.

**Comment by pukkandan** [comment]
Is user adding `autonumber` by command? Or is this a GUI option? If the latter, I recommend changing it to `video_autonumber` under the hood. I created that field because the behavior of `autonumber` is not what users generally want
