### ISSUE TITLE
[FEATURE REQUEST] Skip a singular video in the progress page!

### ISSUE THREAD

**Issue by NotErikUden** [axcore/tartube#407]
Some YouTubers make many small videos, but then sometimes do very long streams or unnecessary videos that I do not specifically need to have downloaded, here is an example:
![image](https://user-images.githubusercontent.com/52011431/164488244-87d88cc4-8f71-465f-bf56-6a8d75301c5b.png)

This person usually uploads videos that are a few megabytes large, but here they just uploaded a 10 hour loop of something that the precious space on my hard drive is too good for.

When right clicking a download under the "Progress" tab:
![image](https://user-images.githubusercontent.com/52011431/164488540-d8e16d2b-56e2-430d-8e28-c16a7bd08aa9.png)
It would be nice to have the option to just click "Skip current download" to have the current video skipped and resumed with the next!

Simply a neat feature for people that micro-manage their downloads or happen to see one that is unnecessary!

Love the software, thank you for maintaining it!

**Comment by axcore** [comment]
Not possible, I'm afraid. If we tell yt-dlp to download the URL of a channel, we can't randomly interject new instructions halfway through.

Your workarounds are:

1. Check the channel first, then select all the videos (CTRL + A), then right-click the videos and select Download videos
2. Use a custom download, with the **Download each video independently of its channel or playlist** option selected (see https://github.com/axcore/tartube#6132-independent-downloads)

Both methods will start a new yt-dlp for every video, so you can stop downloading any video you don't like.

**Comment by NotErikUden** [comment]
Yup, sounds like a good solution! Sorry, I had no clue how yt-dlp was used to download the videos, I thought this might be a very minor thing to implement! If it is technically impossible, I will close the thread! So, no worries, thank you for your in-depth answer!
