### ISSUE TITLE
[FEATURE REQUEST] Implement Gallery-DL and Instaloader into Tartube?

### ISSUE THREAD

**Issue by NotErikUden** [axcore/tartube#408]
Okay, this is kind of a lot to ask for, but: It would be nice if I could have one program to manage all my archive content. 

There is Gallery-DL: https://github.com/mikf/gallery-dl 
Which is like YouTube-dl, but made for sites where images or comments are posted. 
There is Instaloader: https://github.com/instaloader/instaloader
Which allows the specific download of Instagram accounts (functionality that Gallery-DL lacks)
There is LofterCrawler: https://github.com/BYJRK/LofterCrawlerV2
Which allows the specific download of Lofter Accounts (functionality that Gallery-DL lacks)

Again, this is just what I would need personally in order to not have to use many programs, it is probably not what the community of Tartube needs, which I understand. 

You can close this request if it is too far fetched, considering Tartube has "Tube" in its name, showing it was always intended for videos.
I'd just like to have a singular, easy-to-use, application through which I can manage all my archival efforts! It would be great if I could just manage everything through one program and have a convenient database like Tartube implements it!

**Comment by axcore** [comment]
I considered this before (see https://github.com/axcore/tartube/issues/221). Considering how complex the Tartube interface has become, I don't think it's a good idea to add even more layers of complexity.

A separate application, re-using Tartube code where convenient, would be a good project for someone. But I don't have the time to do it.

**Comment by NotErikUden** [comment]
Yeah, moderating one repo seems like it is already too much effort. I got it, man. Maybe some day, if I am serious enough about this, I'll do so! But that day will be long in the making. I just like how your software works, at it inherently makes sense to me and I am able to easily use it, even as a "power-user" who has thousands of channels to download and archive.
