### ISSUE TITLE
[FEATURE REQUEST] Scheduled downloads (for specific playlists and channels)?

### ISSUE THREAD

**Issue by ErikUden** [axcore/tartube#409]
Since Tartube now has a feature to download selected channels, I thought it would be neat to have some sort of "Selection profiles" which channels can be added to and deleted from. 

This in itself would also be a good thing to have, as I could just select the selection profiles and the 40 or so most important channels to me would immediately be selected, instead of me having to scroll through the list and select the right ones each time (_sure, the channels stay selected during and after the download, but not after the program was closed or the PC restarts_)

Certain channels are very important to me and their videos are always worth a watch, it would be neat if those specific channels would be downloaded every day (_or attempted to be downloaded and if there are no new videos Tartube recognizes that, like it already does_)

This would be neat and would bring a lot more automation to Tartube! Sure, clicking a button that says "Download selected" or "Check selected" isn't hard, but maybe Tartube could, through this feature, also turn more and more into archivist software that can can run 24/7 on someone's PC to make sure the archive is kept up to date!

Additionally, through the different profiles, certain channels could be downloaded once a day, once a week, once a month, etc., depending on how important the channels and their content is to the user of Tartube. 

Hope this feature matches your idea of what Tartube is supposed to be and it is also easy enough to implement for you! Again, thank you for maintaining it, Tartube is already one of my favorite pieces of software, I am just mentioning tiny features I would wish to have, 99.9% of my needs are already met!

**Comment by Lux-Hue** [comment]
This can already be done.
https://github.com/axcore/tartube#scheduled-downloads

**Comment by axcore** [comment]
@Lux-Hue beat me to it: scheduled downloads will provide some of the things you ask for.

**Comment by NotErikUden** [comment]
Ohh, thank you! Yeah, sorry. I have many channels that I only checked and then specifically downloaded some videos (due to the sheer mass of videos they uploaded, like the BBC and stuff), so an option to just download a particular set of channels/playlists/folders would be awesome! (though, I can see how that is very hard to implement with the current download scheduler already existing)

**Comment by Lux-Hue** [comment]
Forgive me if I'm wrong on this, but I don't think you understood what the help article says. You can create a schedule, and add specific channels/playlists/folders to that schedule. Then only those channels/playlists/folders will be downloaded with that particular schedule. According to your last comment, this is exactly what you're looking for, right?

**Comment by axcore** [comment]
Selection profiles are added in v2.4.021. See [here](https://github.com/axcore/tartube#611-profiles) for details of how they work.
