### ISSUE TITLE
Apostrophe error

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#411]
Win10 / 2.4

If I check a video, the name shows correctly in Tartube:

![image](https://user-images.githubusercontent.com/16659133/164700268-7a13cb05-a2a7-4eee-84ab-c9863cf3d0e2.png)

python3 D:\_YT\yt-dlp-20220408 --newline -i --hls-prefer-native --write-description --write-info-json --write-annotations --cookies D:/_ytt/cookies.txt --write-thumbnail --merge-output-format mkv --write-sub --embed-thumbnail --add-metadata --windows-filenames --convert-thumbnails jpg --sub-lang en --output D:/_ytt/Comedy/%(uploader)s - (%(upload_date)s) - %(title)s - %(id)s - [%(format_id)s#%(height)sp].%(ext)s --get-comments --extractor-args youtube:comment_sort=top -f bestvideo[ext=webm][height<=?480][fps<=?30]+bestaudio[ext=webm]/bestvideo[height<=?480][fps<=?30]+bestaudio/best --dump-json --download-archive D:/_ytt/Comedy/ytdl-archive.txt https://www.youtube.com/watch?v=GVtEzGZP-_s
[Comedy] <Simulated download of: 'Dinesh D'Souza - (20220421) - UNMASKED Dinesh D’Souza Podcast Ep315 - GVtEzGZP-_s - [244+251#480p]'>

But upon downloading it, the apostrophe gets messed up:

![image](https://user-images.githubusercontent.com/16659133/164700661-7f6cbd71-1e8c-4e8e-8898-e80eaf3fe041.png)

python3 D:\_YT\yt-dlp-20220408 --newline -i --hls-prefer-native --write-description --write-info-json --write-annotations --cookies D:/_ytt/cookies.txt --write-thumbnail --merge-output-format mkv --write-sub --embed-thumbnail --add-metadata --windows-filenames --convert-thumbnails jpg --sub-lang en --output D:/_ytt/Comedy/%(uploader)s - (%(upload_date)s) - %(title)s - %(id)s - [%(format_id)s#%(height)sp].%(ext)s --get-comments --extractor-args youtube:comment_sort=top -f bestvideo[ext=webm][height<=?480][fps<=?30]+bestaudio[ext=webm]/bestvideo[height<=?480][fps<=?30]+bestaudio/best --download-archive D:/_ytt/Comedy/ytdl-archive.txt https://www.youtube.com/watch?v=GVtEzGZP-_s
[youtube] GVtEzGZP-_s: Downloading webpage
[youtube] GVtEzGZP-_s: Downloading android player API JSON
[youtube] Downloading comment section API JSON
[youtube] Downloading ~140 comments
[youtube] Sorting comments by top comments
[youtube] Downloading comment API JSON page 1 (0/140)
[youtube]     Downloading comment API JSON reply thread 1 (6/140)
[youtube]     Downloading comment API JSON reply thread 2 (9/140)
[youtube]     Downloading comment API JSON reply thread 3 (15/140)
[youtube]     Downloading comment API JSON reply thread 4 (23/140)
[youtube]        Downloading comment replies API JSON page 1 (33/140)
[youtube] Downloading comment API JSON page 2 (47/140)
[youtube]     Downloading comment API JSON reply thread 1 (49/140)
[youtube]        Downloading comment replies API JSON page 1 (59/140)
[youtube]     Downloading comment API JSON reply thread 2 (79/140)
[youtube]     Downloading comment API JSON reply thread 3 (82/140)
[youtube] Downloading comment API JSON page 3 (96/140)
[youtube]     Downloading comment API JSON reply thread 1 (104/140)
[youtube]     Downloading comment API JSON reply thread 2 (109/140)
[youtube]     Downloading comment API JSON reply thread 3 (111/140)
[youtube]     Downloading comment API JSON reply thread 4 (113/140)
[youtube] Extracted 114 comments
[info] GVtEzGZP-_s: Downloading 1 format(s): 244+251
[info] Writing video description to: D:/_ytt/Comedy/Dinesh D'Souza - (20220421) - UNMASKED Dinesh D’Souza Podcast Ep315 - GVtEzGZP-_s - [244+251#480p].description
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: D:/_ytt/Comedy/Dinesh D'Souza - (20220421) - UNMASKED Dinesh D’Souza Podcast Ep315 - GVtEzGZP-_s - [244+251#480p].webp
[info] Writing video metadata as JSON to: D:/_ytt/Comedy/Dinesh D'Souza - (20220421) - UNMASKED Dinesh D’Souza Podcast Ep315 - GVtEzGZP-_s - [244+251#480p].info.json
WARNING: There are no annotations to write.
[ThumbnailsConvertor] Converting thumbnail "D:/_ytt/Comedy/Dinesh D'Souza - (20220421) - UNMASKED Dinesh D’Souza Podcast Ep315 - GVtEzGZP-_s - [244+251#480p].webp" to jpg
Deleting original file D:/_ytt/Comedy/Dinesh D'Souza - (20220421) - UNMASKED Dinesh D’Souza Podcast Ep315 - GVtEzGZP-_s - [244+251#480p].webp (pass -k to keep)
[download] Destination: D:/_ytt/Comedy/Dinesh D'Souza - (20220421) - UNMASKED Dinesh D’Souza Podcast Ep315 - GVtEzGZP-_s - [244+251#480p].f244.webm
[download] 100% of 125.51MiB in 00:27
[download] Destination: D:/_ytt/Comedy/Dinesh D'Souza - (20220421) - UNMASKED Dinesh D’Souza Podcast Ep315 - GVtEzGZP-_s - [244+251#480p].f251.webm
[download] 100% of 42.52MiB in 00:07
[Merger] Merging formats into "D:/_ytt/Comedy/Dinesh D'Souza - (20220421) - UNMASKED Dinesh D’Souza Podcast Ep315 - GVtEzGZP-_s - [244+251#480p].mkv"
Deleting original file D:/_ytt/Comedy/Dinesh D'Souza - (20220421) - UNMASKED Dinesh D’Souza Podcast Ep315 - GVtEzGZP-_s - [244+251#480p].f244.webm (pass -k to keep)
Deleting original file D:/_ytt/Comedy/Dinesh D'Souza - (20220421) - UNMASKED Dinesh D’Souza Podcast Ep315 - GVtEzGZP-_s - [244+251#480p].f251.webm (pass -k to keep)
[Metadata] Adding metadata to "D:/_ytt/Comedy/Dinesh D'Souza - (20220421) - UNMASKED Dinesh D’Souza Podcast Ep315 - GVtEzGZP-_s - [244+251#480p].mkv"
[EmbedThumbnail] ffmpeg: Adding thumbnail to "D:/_ytt/Comedy/Dinesh D'Souza - (20220421) - UNMASKED Dinesh D’Souza Podcast Ep315 - GVtEzGZP-_s - [244+251#480p].mkv"

Tried both with and without --windows-filenames, same result.

Any ideas? Thanks Axcore!

**Comment by axcore** [comment]
Tartube stores two names for every video: a name matching the video's filename, and a 'nickname' taken from the video's metadata.

Open the video's properties window, the nickname is one in the **Listed as" box. The nickname is also the one visible in your screenshots.

I checked that video's metadata, and it contains a character which is not supposed to be used as an apostrophe ( ’ ). Check it for yourself [here](https://software.hixie.ch/utilities/cgi/unicode-decoder/character-identifier). 

The nickname is just for aesthetics, it doesn't affect Tartube operations or your filesystem. As far as I can tell, the text is being rendered correctly. You can write to the video's author, if you like, and politely suggest that they learn how to use their keyboard.

**Comment by ceonelson** [comment]
Why is it that it shows correctly when checking the video but doesn't once the video is downloaded?

In the JSON for that file, it gets correctly rendered by VSCode as an apostrophe (U+2019):
![image](https://user-images.githubusercontent.com/16659133/166118542-9cc9d2c7-231a-4e7d-b236-413ea95ad673.png)

Also, it looks like it used to render correctly previously in Tartube:
![image](https://user-images.githubusercontent.com/16659133/166118633-b866ce49-7658-489c-b36b-eaaafeb4811f.png)

(on a side note, that check script link reports as broken for the character search):
![image](https://user-images.githubusercontent.com/16659133/166118040-4ba44318-f768-49be-a743-47a8569d1925.png)

**Comment by ceonelson** [comment]
Hmm so I pulled up the JSON for the last one that rendered correctly, and it appears instead of storing the character as ' in the file it stores it as \u2019:
![image](https://user-images.githubusercontent.com/16659133/166118716-920ad084-5823-49b6-ae99-120ea53a75d6.png)

Any idea why that would be happening?

**Comment by ceonelson** [comment]
So I think I've figured out the root cause of this issue, and it's another change from yt-dlp's 20211227 release that seems to have broken things.

I went to my test db and reverted to that release of yt-dlp, and sure enough everything was fine in the name and description:
![image](https://user-images.githubusercontent.com/16659133/166406101-2fcc65c2-85ca-4893-95c8-bb17213b3ab0.png)

So I figured I'd work my way back up to the current yt-dlp release and see where things break, but I didn't have to go far as the January release no longer displayed correctly:
![image](https://user-images.githubusercontent.com/16659133/166406135-ce831661-7245-4a65-85ba-a485a1caef66.png)

I went to yt-dlp and searched through all the issues for unicode and found the culprit:
https://github.com/yt-dlp/yt-dlp/issues/2139

Which inspired this change to the code that, you guessed it, was made live in the January release:
https://github.com/yt-dlp/yt-dlp/commit/45d86abeb4959723860848dea5f47969dfe56c11

Since this is the default behavior of yt-dlp moving forward, is it possible to have tartube read in the description and info.json files as unicode to make it where the characters display correctly?

Thanks Axcore!

**Comment by ceonelson** [comment]
Spent a couple more hours playing around with this tonight and it looks like the issue is that the json/description is being encoded to UTF-8 twice (first by yt-dlp, then by tartube).

(I'm testing on the description file because that was the easiest for me to figure out how to hack a test for)

With latest Tartube and 2022-04-08 yt-dlp, this is how the filename and description is displayed:
![image](https://user-images.githubusercontent.com/16659133/166638521-9f747089-3aa4-4b66-b170-5dc3c24179d0.png)

But if I change [downloads.py#L4529](https://github.com/axcore/tartube/blob/master/tartube/downloads.py#L4529) to not encode as UTF-8, it displays correctly on my system with an encoding detected as cp1252:
![image](https://user-images.githubusercontent.com/16659133/166638719-09c45c5d-6aa8-4ad7-9252-ce940774c008.png)

Or if I leave downloads.py alone, but change [utils.py#L2855](https://github.com/axcore/tartube/blob/master/tartube/utils.py#L2855) to force the system encoding to UTF-8, it will also display correctly (but it breaks the filenames on Windows that way):
![image](https://user-images.githubusercontent.com/16659133/166638879-6644a614-6b07-44db-a700-2db474e6d70e.png)

[an hour later]
Great success! (I hope)
Only changing [files.py lines 86]((https://github.com/axcore/tartube/blob/master/tartube/files.py#L86) and 121 to force reading as UTF-8 seemed to do the trick and fix all the problems!
![image](https://user-images.githubusercontent.com/16659133/166642054-d8f84686-375a-47e5-80ca-ec2656a6322d.png)

Maybe this is the proper fix? Any thoughts on if it will break something else?

I'm going to submit a PR with that change in hopes it will work or be a base for a fix :)

Thanks Axcore!

**Comment by axcore** [comment]
Nice work @ceonelson, I think I would not have solved that without you.
