### ISSUE TITLE
Search filter removed after viewing a video's properties

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#413]
In trying to figure out the ' issue I did a search for Podcast and scrolled down a bit to when the error started occurring.
![image](https://user-images.githubusercontent.com/16659133/166119273-62c4b0c9-96d3-4e89-8f4d-be80bf56fe8f.png)

Then I right clicked on a video, show->properties, looked at some info and closed the popup.

Then the search filter got removed but in the toolbar it showed it was still in search mode.
![image](https://user-images.githubusercontent.com/16659133/166119301-5c8ccd0c-ca2f-41be-b783-9e817846c815.png)

Can the search filter still be kept enabled after viewing a video's properties?

Thanks Axcore!

**Comment by axcore** [comment]
Fixed in v2.4.021.
