### ISSUE TITLE
Moveing to a new windows install

### ISSUE THREAD

**Issue by alidan** [axcore/tartube#415]
Am I able to move settings files and everything there so I don't have to reset everything up, or do I have to re make everything?

**Comment by ceonelson** [comment]
Yes you should just be able to copy the directory you installed Tartube into and also the Tartube data directory to the same spot on the new windows install and it will work :)

If you want to change the location of the Tartube data folder you can just open the database from its new location and it will find everything.

**Comment by axcore** [comment]
Edit > System preferences > Files > Config will tell you where the configuration file is. Everything else is in the Tartube data folder, so as @ceonelson says, that can be moved anywhere.
