### ISSUE TITLE
File name renaming does not work

### ISSUE THREAD

**Issue by Lucetia** [axcore/tartube#417]
I'm not sure if this is a bug or something I am missing so I'm putting it under question at first.

I am trying to have it create videos with the filename "Upload Date - Title of Video.extension".  For some reason, when I change the settings under Files -> FIlenames with the custom option the output is still "Title of video.extension"

Below is a copy of the settings I am using.  Am I missing something somewhere or is it a bug of sorts?

![image](https://user-images.githubusercontent.com/36181235/166940319-c008f2a2-66da-4744-afa0-d866ae898c7c.png)

**Comment by ceonelson** [comment]
Try using %(upload_date)s instead - that's what I use and it works.

**Comment by axcore** [comment]
![zoo1](https://user-images.githubusercontent.com/37951926/166956355-f2020081-520c-49d1-b23e-872157d66c60.png)

In the **Videos** tab, you can see the name of the video, not the name of the video file. 

If  you right-click the video and select **Show video > Properties**, you will see this window, which shows both the name of the video and the name of the video file.

![zoo2](https://user-images.githubusercontent.com/37951926/166957040-e51b4d4d-d3a5-4c9a-af57-188b301ae76e.png)

**Comment by axcore** [comment]
I added a setting to toggle between showing video names and file names. It will be in the next upload, in **Edit > System preferences > Windows > Videos > Show nicknames**

**Comment by Lucetia** [comment]
> > In the **Videos** tab, you can see the name of the video, not the name of the video file.
> 
> If you right-click the video and select **Show video > Properties**, you will see this window, which shows both the name of the video and the name of the video file.
> 
> This video was downloading using `%(upload_date)s-%(title)s.%(ext)s`, so everything appears to be working as expected.

I was originally doing it under classic mode and it wasn't working.  I did add it as a channel under as Videos and that seems to be working now.

My next question is that by default it looks like it does YYYYMMDD.  Is it possible to adjust it to do something like YYYY-MM-DD or swap around the order like MM-DD-YYYY, etc?

Lastly, if all the videos are downloaded in a channel, is there a way to go through and have it recheck all the files and adjust their filename based on any new file naming schemes selected?

**Comment by ceonelson** [comment]
See this issue from yt-dlp where someone provides an awesome script to do what you're asking :D

https://github.com/yt-dlp/yt-dlp/issues/3301

**Comment by axcore** [comment]
>I was originally doing it under classic mode and it wasn't working. I did add it as a channel under as Videos and that seems to be working now.

The Classic Mode tab uses a separate set of download options. Make sure you're trying to edit that set. In other words,. click the menu button in the top-right corner, and select **Edit download options**; don't use the main menu to select **Edit > General download options...**

**Comment by axcore** [comment]
>Is it possible to adjust it to do something like YYYY-MM-DD or swap around the order like MM-DD-YYYY, etc?

Not very easily. youtube-dl gives us a video name, it doesn't provide any clues about which part of the name corresponds to which piece of metadata. What happens, for example, if the name contains [a sequence of digits that are not a date](https://www.youtube.com/watch?v=xa2wn6t-wG8)?

**Comment by axcore** [comment]
The toggling is implemented in v2.4.031. The new code is only available from github/PyPi. If you're using Windows and want to update  your installation, see [here](https://github.com/axcore/tartube#71-tartube-wont-installwont-rundoesnt-work).

I will go ahead and close this issue, but if you want to continue discussion of your follow-up questions, feel free to open a new issue for them.

**Comment by axcore** [comment]
@Lucetia thanks to https://github.com/axcore/tartube/issues/424, I have been able to add dates in the format YYYY-MM-DD (or any format you choose) in v2.4.050.

![custom](https://user-images.githubusercontent.com/37951926/168263712-67a3c1b2-e422-49be-b179-fc4896470b12.png)
