### ISSUE TITLE
Other format options for time in file naming

### ISSUE THREAD

**Issue by viktorrauch** [axcore/tartube#424]
Would be great to have other format options for upload time in the file names like "2022-05-09" or "2022 05 09".

At the moment it seems that only "20220509" is possible. Sadly Plex for example can't handle this.

**Comment by axcore** [comment]
You're right, it would be great. yt-dlp handles file naming, so you can suggest it at their [issues page](https://github.com/yt-dlp/yt-dlp/issues).

**Comment by viktorrauch** [comment]
I just did. Thank you for the hint.

**Comment by axcore** [comment]
If it gets implemented, ping me and I'll update the Tartube code to include the new options.

**Comment by viktorrauch** [comment]
They showed me the solution in the documentation:

Date/time Formatting: Date/time fields can be formatted according to [strftime formatting](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes) by specifying it separated from the field name using a >. Eg: %(duration>%H-%M-%S)s, %(upload_date>%Y-%m-%d)s, %(epoch-3600>%H-%M-%S)s

it's already possible. :)

**Comment by axcore** [comment]
I added custom formats for dates/times in v2.4.050. 

The new code is only uploaded to Github/pypi. If you're using MS Windows, you can update your installation as described [here](https://github.com/axcore/tartube#71-tartube-wont-installwont-rundoesnt-work).
