### ISSUE TITLE
Channel associated playlist display

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#425]
I just tried the steps under https://github.com/axcore/tartube#6172-extracting-playlists-from-a-channel and it generally worked great, but I had a feature request and some questions:

I was hoping that the playlists would be displayed in the tree view like they would be if I had added them manually. Is that possible to do? Ideally could they be displayed as a child of the channel?

If not, is it possible to filter the channel view so it only shows videos in a certain playlist?

Is there a way to only download playlists that they create ie [channel name] playlists, leaving created playlists out?

If a channel adds a new playlist, how do we update the associated playlists tab? Just click on update from metadata file?

Thanks Axcore!

**Comment by axcore** [comment]
>I was hoping that the playlists would be displayed in the tree view like they would be if I had added them manually. Is that possible to do?

In the channel properties window, in the Associated Playlists tab, the **Add all playlists** button was broken. I fixed that in v2.4.050, so channels should appear in the treeview immediately.

>Ideally could they be displayed as a child of the channel?

Channels and playlists cannot have children. But if the channel is inside a folder, then the playlists are created inside the same folder.

>Is there a way to only download playlists that they create ie [channel name] playlists, leaving created playlists out?

Sorry, I don't understand that

>If a channel adds a new playlist, how do we update the associated playlists tab? Just click on update from metadata file?

The **Add all playlists** button won't create duplicate playlists, so when new playlists appear in the **Associated playlists** tab, you can just click that button again.

**Comment by axcore** [comment]
Closed for inactivity
