### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by zeref-dragneel** [axcore/tartube#428]
Can this app be translated into other languages using a web based interface like, say, [Weblate](https://hosted.weblate.org/) or [Crowdin](https://crowdin.com/project)?

**Comment by ceonelson** [comment]
Good thinking Zeref! It looks like they both have free versions for OSS projects, and Weblate at least supports gettext .po files which is what Tartube uses :)

**Comment by axcore** [comment]
A great idea in principle, but I don't have the resources to host a server.

**Comment by ceonelson** [comment]
No need to host a server @axcore , they have a free cloud version for both:

Weblate:
![image](https://user-images.githubusercontent.com/16659133/168880859-267183d4-f38a-4183-9dc2-f65e2d4c4ce5.png)

Crowdin:
![image](https://user-images.githubusercontent.com/16659133/168884097-3c8d29c5-2818-4597-b966-0a91d3922fe8.png)

From a quick glance it seems like Weblate might be the better of the two but either one will integrate with github :)

**Comment by axcore** [comment]
https://hosted.weblate.org/projects/tartube/[](https://hosted.weblate.org/projects/tartube/)

Does the free hosting have a language limit of 4? Well, Tartube already has 4 language translations, so I suspect this won't be very useful.

**Comment by axcore** [comment]
The Weblate hosting request was approved so this issue can be closed.
