### ISSUE TITLE
enable download option

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#430]
So right now I can right click a folder/channel/playlist and tell it to download. Once that starts, if I add an individual video somewhere, I can right click on that new video and tell it to download, and it will be added to the download queue.

However, if a download is in progress, the right click download option is disabled for any folder/channel/playlist in the tree view.

Is that something that can be enabled so I can manually add to the download queue while a download is in progress?

Thanks Axcore!

(The download checkboxes aren't quite the same functionality I'm looking for)

**Comment by axcore** [comment]
Added in v2.4.065. 

During a download, you can now right-click a different channel/playlist/folder and select the **Check** or **Download** menu option. The **Custom download** option was too complex to update, so it's still greyed out.
