### ISSUE TITLE
yt-dlp for Downloading Livestream From The Start

### ISSUE THREAD

**Issue by heywolf15** [axcore/tartube#431]
New update for yt-dlp has fixed my problem when it's still trying to download the stream while it ended private or member only.
Now using  `--live-from-start` it will merge automatically.
Just want an easy way to add the command in general and classic

**Comment by axcore** [comment]
Added in v2.4.065. Click **Edit > General download options**, click the **Show advanced download options** button if it's visible, then click the new **Downloads > Live** tab.
