### ISSUE TITLE
Long playlist name results in videos becoming not visible in grid.

### ISSUE THREAD

**Issue by Lux-Hue** [axcore/tartube#433]
### What operating system are you using?
Linux Mint 20.3, unofficial kernel v5.18

### What version of Tartube are you using?
v2.4.065

When I download videos from a playlist that has a long name, that name is not wrapped to a new line or cut off, resulting in parts of the grid going outside the view in the window (see image below). Since I can scroll up and down, but there is no scrollbar for left and right, I cannot see the information of those videos.
![image](https://user-images.githubusercontent.com/32292209/171217262-7e7cfd35-ae4c-489e-a5c3-02d67c9bff5a.png)

**Comment by axcore** [comment]
Workaround: on the left side of the window, right-click the playlist and select **Playlist actions > Rename playlist**. You can choose any name you like, you don't have to use the original name.

**Comment by axcore** [comment]
Fixed in v2.4.069. The previous code reduce the length of the name if it was longer than 64 characters, but the maximum length was already 64 characters, so the name was never reduced.

Anyway the name is now reduced after 48 characters which should take care of your problem.
