### ISSUE TITLE
Options for selecting a video (specially useful for Instagram)

### ISSUE THREAD

**Issue by pamplinas1** [axcore/tartube#438]
It would be nice to have an option for selecting a video.
For example 
```shell
yt-dlp --playlist-items 2 https://www.instagram.com/p/CeT4T9ruvTv/?utm_source=ig_web_copy_link
```
and this will select only the second video for that publication.

**Comment by axcore** [comment]
Added in v2.4.093. 

Edit > General download options
Click the "Show advanced download options" button if it's visible
Click the tab "Downloads > Playlists"
Edit the box marked "Download playlist range"
