### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by 1024mb** [axcore/tartube#44]
Please, add an option to change the default folder when adding new urls so we can change the default "unsorted folder" to whatever folder we want instead of having to change it every time we add new urls.

Another feature I want to request is to integrate the add new video/channel/playlist window into the main one kinda like youtube-dl-gui where we just had to paste the link and press a button, instead in Tartube we have to press a button out of three, then paste the url/s, pick the right folder (because we can't change the default one) and then click on another button, and is even more steps if trying to download a channel/playlist.

So here comes the last one, please allow us (add an option) to input whatever kind of url into the "add new video" window and download them all in the same unique folder instead of having to download to (and force us to input) the channel/playlist name subfolder.

Thanks.

**Comment by axcore** [comment]
> Please, add an option to change the default folder when adding new urls so we can change the default "unsorted folder" to whatever folder we want
This is already added to v1.3.044, available from git. It's not in the MS Windows installer yet.

> Another feature I want to request is to integrate the add new video/channel/playlist window into the main one kinda like youtube-dl-gui where we just had to paste the link and press a button, instead in Tartube we have to press a button out of three, then paste the url/s, pick the right folder (because we can't change the default one) and then click on another button, and is even more steps if trying to download a channel/playlist.
Not possible*. When Tartube tells youtube-dl to download a weblink like [https://www.youtube.com/watch?v=CS9OO0S5w2k](https://www.youtube.com/watch?v=CS9OO0S5w2k), youtube-dl receives any number of videos between 0 and infinity. There is no way to tell if the weblink is a single video, or a channel containing one video, or a playlist containing one video. youtube-dl does not tell us.

* Unless someone knows how to make it possible.

> So here comes the last one, please allow us (add an option) to input whatever kind of url into the "add new video" window and download them all in the same unique folder instead of having to download to (and force us to input) the channel/playlist name subfolder.
If you want to Tartube to take a list of URLs, download all the videos into a single folder, then forget about the list of URLs, then that's possible.

**Comment by 1024mb** [comment]
> 
> 
> This is already added to v1.3.044, available from github. It's not in the MS Windows installer yet.

I'll have to wait then, thanks for adding this.

> 
> 
> When Tartube tells youtube-dl to download a random weblink like https://www.youtube.com/watch?v=CS9OO0S5w2k, youtube-dl receives any number of videos between 0 and infinity. There is no way to tell if the weblink is a single video, or a channel containing one video, or a playlist containing one video. youtube-dl does not tell us.
> 
> It would be nice to auto-sort the list of weblinks into videos, channels and playlists before we download anything, but it's not possible.
> 

Yeah, got it. I was thinking of this too. If you would go to implement some kind of string detection you would have to add a lot because Tartube (and youtube-dl) doesn't only work with YT but another hundreds of sites and each has different url templates.
Besides that, integrating the add vid/pl/chnl windows into the main one with tabs instead of making them separate windows would be great too so they are always visible.

> 
> If you want to Tartube to take a list of URLs, download all the videos into a single folder, then forget about the list of URLs, then that's possible.

Yes, please, add this. I don't mind downloading everything into a single folder, actually that's what I want, so it would be faster to input urls.

**Comment by axcore** [comment]
> I'll have to wait then, thanks for adding this.
[It](https://sourceforge.net/projects/tartube/files/v1.3.048/) was released yesterday 

>Yes, please, add this. I don't mind downloading everything into a single folder
I finished that today, but it's not released yet.

**Comment by 1024mb** [comment]
Thank you!

**Comment by axcore** [comment]
Added in v1.3.077. See the README for details of how this works.

You can now copy a mixture of URLs into the 'Add new videos' window. 

When downloading, if Tartube is expecting an individual video, but receives a channel or playlist, it automatically converts the video into a channel. This behaviour can be changed, if required. For example, Tartube can just download all the videos into the same location, and then forget about the original URL.

A channel can now be converted to a playlist, and vice-versa.

I think that's everything you wanted, but feel free to re-open the issue if not.

**Comment by 1024mb** [comment]
Hey thanks for all your work, I'm finally testing this properly and I've encountered some "bugs".

- If an entry already exists in the destination folder but is a symlink Tartube doesn't fill the "incoming file" column with the filename, of course if it is a regular file it does fills it.
- If the "Download all" button is pressed (this is in the Classic Mode) Tartube starts to re-download all the entries including the already finished ones.
