### ISSUE TITLE
TarTube will download at very fast speeds for a few videos and then slow down for the next few. Is this a bug or intended?

### ISSUE THREAD

**Issue by beachboys95** [axcore/tartube#440]
I've read that YouTube bans people by IP address for downloading too much off the site. Is the fluctuation in speeds meant to curtail that, or is there something I should be doing to get videos to download always at fast speeds?

For example, if I'm downloading a channel, I'll get one video downloading at 20MiB/s, but then the next 5 videos will download at 200KiB/s.

**Comment by axcore** [comment]
As far as I know, yt-dlp does not do any throttling. You would have to ask [its developers](https://github.com/yt-dlp/yt-dlp/issues) for a definitive answer, though.

If remote throttling is an issue, you can use a custom download to download each individual video separately as described [here](https://github.com/axcore/tartube#6142-independent-downloads).

I have seen some reports of slow download speeds in the last few days, so the same issue is probably affecting everyone.

**Comment by axcore** [comment]
Ultimately the only solution for YouTube throttling is to download less stuff.
