### ISSUE TITLE
How to set remux only to mp4

### ISSUE THREAD

**Issue by rafcon-dev** [axcore/tartube#441]
Hi. Thanks for your work on this. I wanted to embed the subtitles into the video file, but without reencoding it. I thought maybe tartube could simply remux it all in a mp4 container. I tried adding the argument remux_video in the post-processing tab in the "Arguments to pass to post-processor" but had no luck. How should that argument be formated?
Thanks!

**Comment by axcore** [comment]
I'm not sure. I usually suggest asking these kinds of questions in the [Reddit forum](https://www.reddit.com/r/youtubedl/). Show the yt-dlp command that is produced when you try to download the video (it's the yellow text at the top of the main window's Output tab).
