### ISSUE TITLE
[Feature Request] Way to add unlisted videos to the correct channel

### ISSUE THREAD

**Issue by ErikUden** [axcore/tartube#445]
Many YouTube Channels have unlisted videos, either because it's part of their genre, or because the person behind the channel doesn't want the video to appear under the “videos” tab, but accessible through public playlists or links from other videos, etc. 

As far as I'm aware, however, such unlisted videos will not be downloaded by youtube-dl / yt-dlp, hence also not Tartube. 

Channels like Technoblade's, whose livestreams are all unlisted but capable of being found on public playlists, or Kane Pixels' Backrooms series, which links to other secret videos in the description of public videos, are much harder to archive, or the archive is more messy as to archive all videos you'd need one “Kane Pixels” channel inside of Tartube, but then another “Kane Pixels” folder with all the unlisted videos added manually. 

**The feature I'm suggesting:**

Allow the user to manually add videos to channels inside of Tartube. Tartube could check the link, see if it is truly a video uploaded by that channel, and if that is the case (and the video hasn't been downloaded already / is unlisted), then put it on the download queue and actually add it to the channel in the database! 

Maybe the feature could pop up as an option when right-clicking a channel in the drop down menu called “Add unlisted video”. 

This option should then open a text box where you could potentially post many lines of YouTube Video links, all of which would be checked and possibly added if they belong to the channel in question.

I am unaware how easy it is to implement such a feature, as Tartube would essentially have to check the uploader's channel ID of each video pasted in that textbox and then compare that to the channel ID of the channel in question, then repeat that for every link posted. 

Additionally, the API for every platform works differently. Performing this ID check for YouTube may be easy, but yt-dlp supports other platforms like BiliBili, Vidme, etc., all of which also have the option of unlisting a video. 

I personally only need that feature for YouTube, but still, I can see how it would be hard to implement considering all the platforms yt-dl supports. If this feature were to be only implemented for YouTube channels, then every channel from other platforms would need a different drop-down menu when right-clicking etc. which just creates a whole mess. 

**Extra Idea:**

Automatically download unlisted videos accessible through public playlists? 

Maybe add a checkbox in the “Add Channel” pop-up menu that when ticked scrapes the channel's playlists for unlisted videos and downloads those as well (and obviously only unlisted videos uploaded by the channel in question). 

This feature would just make the kind of archiving I do a lot easier! You must judge whether this is truly something needed in Tartube/for the average Tartube user. Thanks for development and support, Tartube is the Nr. 1 most useful software to me!

**Comment by axcore** [comment]
In principle, it is not a problem to write an "Add unlisted video" feature, that inserts a video into a Tartube channel or playlist.

In order to check or download this video, you would have to set up [custom downloads](https://github.com/axcore/tartube#614-custom-downloads) to check/download each individual video separately. Alternatively, you could select the video(s) and right-click to download them.

My question is, is it really necessary to check that the video really belongs to the channel/playlist? That extra step is rather complicated, and does not provide any benefits.

**Comment by ErikUden** [comment]
No, such a feature is not necessary, as any user is very easily capable of verifying whether the video belongs to the channel.

To me, the feature of adding unlisted videos in the first place is important!

**Comment by axcore** [comment]
That important feature is added in v2.4.093. Right-click a channel and select "Channel actions > Insert videos..."

**Comment by ErikUden** [comment]
Thank you! Everything I needed is included. Will close the issue now!
