### ISSUE TITLE
Tartube can't open database file (new build)

### ISSUE THREAD

**Issue by mcrsquared** [axcore/tartube#449]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
If using MS Windows, are you using Windows 10, Windows 7, or something else?

Windows 10

### What version of Tartube are you using?
In Tartube's main window, click Help > About

v2.4.093

### What happens when you run Tartube from a terminal window?

**Does not work, since CMD

Many error messages are only visible in the terminal window. On MS Windows, this is how to do it:

- First, enable hidden folders on your system
- Then, run the application: 

    C:\Users\YOURNAME\AppData\Local\Tartube\msys64\mingw64.exe

** Reason 1: not a valid windows application

- In this new window, type these commands to start Tartube:

    cd /home/user/tartube

    python3 tartube/tartube

###If your bug report is "I can't download this video", please provide a link to the video
This will save a lot of time!

++++++++++++++++++++++++

I updated to the latest version of Tartube, and it now won't download my channel. This is the specific error message:

ython3 youtube-dl --newline -i --datebefore 20180101 --dateafter 20160101 --hls-prefer-native --write-description --write-info-json --write-annotations --cookies S:/Talks Third/cookies.txt --write-thumbnail --output S:/Talks Third/YouTube 2018/%(title)s.%(ext)s --download-archive S:/Talks Third/YouTube 2018/ytdl-archive.txt https://www.youtube.com/c/talksatgoogle
python3: can't open file 'C:\\Users\\Cliff Redeker\\AppData\\Local\\Tartube\\msys64\\home\\user\\tartube\\youtube-dl': [Errno 2] No such file or directory

Thanks for your help. I've tried reinstalling the youtube-dl

**Comment by axcore** [comment]
youtube-dl is probably abandoned, you should be using yt-dlp. Select it in **Edit > System preferences > Downloaders**, then install it by clicking **Operations > Update yt-dlp**

**Comment by mcrsquared** [comment]
Thanks, that seemed to help. (along with a complete uninstall/reinstall).

I wish there was a way to download the videos in "oldest first" order, as
those are the ones most in danger of deletion (for my YT channel of
interest). Right now, I can only do that by opening multiple sessions and
limiting the search by year. I also don't think that Tartube is taking the
most advantage of my gig ethernet downloads.

Cheers,

**Comment by axcore** [comment]
**Edit > General download options**
If the **Show advanced download options** button is visible, click it
Then click the **Downloads > Playlists** tab, and click **Download playlist in reverse order**

(These options will also work on channels)

**Comment by mcrsquared** [comment]
Super helpful. The distinction of playlist == channel was lost on me.
Carrying on!

**Comment by axcore** [comment]
Tartube distinguishes between a channel and a playlist because you clicked the "Add channel" or "Add playlist" button. But yt-dlp treats them the same.
