### ISSUE TITLE
Subtitles > Options: Download Automatic Subtitles file (YouTube only) vs Download Subtitles files for these languages: English?

### ISSUE THREAD

**Issue by xbliss** [axcore/tartube#450]
Subtitles > Options: Download Automatic Subtitles file (YouTube only) vs Download Subtitles files for these languages: English? 

Subtitles > Options: 

B. Download Automatic Subtitles file (YouTube only) 

vs 

D. Download Subtitles files for these languages: English? 

Out of the four options.. I am currently using D - 

Issue is under what scenario / what difference is there between B & D.  

I always want subtitles download.. for English - whether they are added by Creator / YouTuber or auto generated by YouTube engine. 

How/ what ways can this be done? 

Because it seems a bunch of times I am not getting any subtitles/ cc with the video?

**Comment by axcore** [comment]
I experimented with this, but I didn't find the right combination of download options that guarantees "either automatically-generated English subtiles or creator-added subtitles". So you need to ask someone else, perhaps on [Reddit](https://www.reddit.com/r/youtubedl/) or the [yt-dlp developers themselves](https://github.com/yt-dlp/yt-dlp/issues).

For comparison, I thought these download options would do that, but they don't:

`--write-sub --sub-lang en --write-auto-sub`

When you have your answer, you can add them to Edit > General download options... > Name, like this.

![subs](https://user-images.githubusercontent.com/37951926/184190429-669a4700-d152-49ef-9eaf-d5a87528ad6c.png)

**Comment by xbliss** [comment]
Apologies. I was bit occupied to review your response. 

Is there a way to cross post this via GitHub itself for better UI and data sharing versus reddit? 

Would similar thread on their Github not be be faster/ better wrt yt dlp devs? 

Or reddit might be the only/ better option?

**Comment by formlessdao** [comment]
Is there no fix to make subtitles downloading work?
I can't download creator made subtitles. 
I'm not interested in automatic youtube subtitles.

**Comment by axcore** [comment]
>Would similar thread on their Github not be be faster/ better wrt yt dlp devs?

Apologies again, either I did not notice your reply, or I forgot to respond.

yt-dlp's github is very busy, so it best not to pollute their timeline with Tartube questions. If you ask "how do I get subtitles in yt-dlp" and get a reply, you can copy and paste the reply here, then I will see it.

>Is there no fix to make subtitles downloading work?
>I can't download creator made subtitles.

It is pointless to ask me. I don't know everything about yt-dlp.

If you know how to do something with yt-dlp, then I can show you the equivalent settings in Tartube.
