### ISSUE TITLE
Can't download age restricted videos even if logged in

### ISSUE THREAD

**Issue by PawelW2006** [axcore/tartube#452]
### What operating system are you using?
Windows 10

### What version of Tartube are you using?
2.4.093

### What happens when you run Tartube from a terminal window?
Not Applicable, All Relevant Error Messages are shown in GUI

Hello. I came here to report a bug.

== Bug ==
When i try to download any age restricted video i get an error message which says "Sign in to confirm your age, This video may be inappropriate for some users." and when i try to use the "Check Channel" option it shows those videos as (Video with no name) and blatantly refuses to give me the option to download it.

== Things i tried to resolve it ==
I have gone into the advanced settings and put in my login and password, to be sure it's right i even copy pasted them into the youtube login screen in a browser window. However this does literally nothing, it's like the app doesn't even notice they are there.
Just in case it's just a problem with downloading channels and playlists, i've also tried manually putting in random videos from those channels and playlists but it also fails.

== How to Reproduce ==
Just try to download ANY age restricted video from YT, you can put in login details or not, it doesn't make any difference.

**Comment by PawelW2006** [comment]
Update: After digging deeper i've found this error message:

WARNING: [youtube:tab] Login with password is not supported for this website. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl  for how to manually pass cookies.

**Comment by axcore** [comment]
As you say, the usual way to get around this problem is to use cookies (there is another simple guide [here](https://www.reddit.com/r/youtubedl/wiki/cookies/)), but some websites really do forbid logins and I don't know of any workaround for that.
