### ISSUE TITLE
youtube dlp update failed

### ISSUE THREAD

**Issue by anwaruddin2k** [axcore/tartube#455]
manjaro 22 
tartube 2.4

**Comment by axcore** [comment]
Updates are working on pip, which update method are you using?

Edit > System prefereneces > Downloaders > File paths > Command for update operations, or just show me the contents of the Output tab

**Comment by anwaruddin2k** [comment]
![image](https://user-images.githubusercontent.com/53415502/191178757-b9be6ed3-4cb4-4575-8c1c-38b83be92d36.png)

**Comment by axcore** [comment]
In **Edit > System preferences > Downloads > File paths**, for the **Path to the executable**, you have selected **Use custom path**.

Then, instead of selecting the youtube-dl executable, you have selected Tartube's database file.

In the first drop-down box, try selecting **Use PyPI path**.
