### ISSUE TITLE
Will Only Start If Run As Root In Ubuntu 22.04

### ISSUE THREAD

**Issue by RichCat6** [axcore/tartube#457]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Ubuntu MATE 22.04

### What version of Tartube are you using?
2.4.093

### What happens when you run Tartube from a terminal window?
Ran it first under my user, and it displayed this:
Aborted (core dumped)
When I run it under root, it runs no problem.

**Comment by axcore** [comment]
Which installation method did you use?

**Comment by RichCat6** [comment]
> Which installation method did you use?

deb package

**Comment by axcore** [comment]
Ok, I will look into that. In the meantime, you can install using [pip](https://github.com/axcore/tartube#537-install-using-pypi-without-root-privileges), or just [run the source code directly](https://github.com/axcore/tartube#5310-run-without-installing).

**Comment by axcore** [comment]
Closed because Ubuntu 22.04 is 20 months old now. Feel free to open a new issue, if modern Ubuntu and modern Tartube have the same problem.
