### ISSUE TITLE
Import certificate

### ISSUE THREAD

**Issue by AvrahamTsaban** [axcore/tartube#459]
I use a network that is filtered. Web surfing is only available by importing a certificate. Is there any way to import .crt files inside the GUI client?

**Comment by axcore** [comment]
[This issue](https://github.com/yt-dlp/yt-dlp/issues/2882) asks a similar question, for which the answer was:

`--downloader-args "aria2c:--ca-certificate=<PATH-TO-CERTIFICATE>"`

In Tartube, you can add any download option to Edit > General download options > Additional download options

**Comment by AvrahamTsaban** [comment]
Cert problem workarounded, for now.
I'll look into  it when neccessary...
Thank you!

**Comment by AvrahamTsaban** [comment]
[On other YT-DLG fork](https://github.com/oleksis/youtube-dl-gui/), same problem occurs only using yt-dlp, but not using classic yt-dl. Here occurs using both.
