### ISSUE TITLE
Folder contents disappear after switching to another and back

### ISSUE THREAD

**Issue by MikkoMMM** [axcore/tartube#46]
The branch is master and I'm on Arch Linux. I'm running Tartube from the tartube directory under the cloned repository with `python3 tartube`.

There appear to be some glitches for me with Tartube. One of them is that I have a video that I started downloading under Unsorted Videos, but it doesn't show up unless I press Check folder, and then it disappears again when I press another folder button and go back to Unsorted Videos.

**Comment by axcore** [comment]
v1.3.048 fixes a similar issue. Please check whether it improves your problem.

**Comment by MikkoMMM** [comment]
Nope. I went to the "Videos" download screen and it detected the video I wanted to download. I clicked "Don't download anything, just check the videos", left the video to go to Unsorted Videos and pressed OK. It didn't appear in the folder Unsorted Videos at all, until I pressed Check folder for it. Then I switched to another folder and back to Unsorted, and again the video had disappeared. I pressed Download all, and it did download the video and the New videos got its text bolded, but when going there I cannot see any videos. But it does exist on my file system.

**Comment by mbnoimi** [comment]
@MikkoMMM Does [this](https://github.com/axcore/tartube/issues/51) issue similar to yours?

**Comment by MikkoMMM** [comment]
My problem is under the Videos tab, that one is in Progress. And I don't at least remember seeing "(video with no name)".

**Comment by MikkoMMM** [comment]
I think that v1.3.077 fixed the issues about folder contents not showing.
