### ISSUE TITLE
Independent downloads playlist

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#460]
how to use `autonumber` `playlist_id` `playlist_title` `playlist` `playlist_index` `playlist_autonumber` `playlist_uploader` in Independent downloads playlist?

**Comment by axcore** [comment]
What is an "independent downloads playlist"?

You can click **Edit > General download options... >  Files > File names**.

In the box **Format for video file names**, select **Custom**.

The options you want can now be selected. For example, `playlist_id ` is in the dropdown box called **Creator/uploader**. Select it, then click the **Add** button.

![candra1](https://user-images.githubusercontent.com/37951926/195116131-33a5bc13-69c6-4deb-9da1-ad810837d78c.png)

![candra2](https://user-images.githubusercontent.com/37951926/195116165-577a91be-4db5-4b04-94f6-e9376b632fef.png)

**Comment by candrapersada** [comment]
i mean concurrent download

**Comment by candrapersada** [comment]
![image](https://user-images.githubusercontent.com/36833664/195137525-f9c9ee65-f542-4bd6-b669-69c6a2f013a4.png)

**Comment by candrapersada** [comment]
how to use `autonumber` `playlist_id` `playlist_title` `playlist` `playlist_index` `playlist_autonumber` `playlist_uploader`

**Comment by candrapersada** [comment]
but the folder name becomes NA concurrent download

**Comment by axcore** [comment]
NA?

**Comment by candrapersada** [comment]
what I mean is if using Control number of the concurrent downloads then `autonumber` `playlist_id` `playlist_title` `playlist` `playlist_index` `playlist_autonumber` `playlist_uploader` it doesn't work degan cuma tampikan NA

**Comment by axcore** [comment]
I can't reproduce the `NA concurrent download` error.

It is not a Tartube error message, and it is not a yt-dlp error message. (I checked the code for both of them.)

So it is probably a YouTube error message.

Anyway, the answer to your question is: I don't know.
