### ISSUE TITLE
Thumbnails doesn't embed on the video using Tartube: "WARNING: Skipping embedding the thumbnail because the file is missing." But they work in a linux terminal using the same yt-dlp command

### ISSUE THREAD

**Issue by Fijxu** [axcore/tartube#461]
### What operating system are you using?
Linux

### What version of Tartube are you using?
v2.4.093

### What happens when you run Tartube from a terminal window?

It opens 

### Bug

well, the problem I have and hopefully it is easy to fix, is that when I want to download videos with thumbnails inside them, sometimes (the vast majority) always comes out "WARNING: Skipping embedding the thumbnail because the file is missing." and it only happens with TarTube, the . webp file of the thumbnail is shown inside the folder, then the video is downloaded, but then it says that it does not find the thumbnail and does not add it to the video, I tried the same command that TarTube uses and in a console and it adds the thumbnail to the video without problems.

TarTube
![caca](https://ii.zzls.xyz/FTMQGBI.png)

```
yt-dlp --newline -i --hls-prefer-native --cookies /directory/cookies.txt --write-thumbnail --output /directory/%(title)s.%(ext)s -f (best*[ext=mp4][height<=720])+bestaudio[ext=m4a]/best[ext=mp4] --compat-options embed-thumbnail-atomicparsley --download-archive /directory/ytdl-archive.txt https://www.youtube.com/c/MITROXFEAR/videos
```
*Changed my actual real file paths with `directory`*

Console
![pepe](https://ii.zzls.xyz/OEAPLPI.png)

btw, if you need more information, just ask. Ty for this awesome tool :)

**Comment by axcore** [comment]
This is not a solution, but try disabling the .webp conversion in **Edit > System preferences... > Operations > Downloads > Convert .webp thumbnails into .jpg thumbnails...**

**Comment by Fijxu** [comment]
Now it works well, ty, but since i download the videos in VP9 .webm, i need to remux the videos to MKV or MP4 to embed the thumbnail on the video, everything well at that point, but the when yt-dlp is doing the remux, Tartube can't longer identify the video (i think) and it looks like this:

![image](https://ii.zzls.xyz/LZBPITI.png)

**Comment by axcore** [comment]
Please show me the command that works in the console, and also show me a screenshot of the command Tartube is using (the yellow text at the top of the **Output** tab).

**Comment by Fijxu** [comment]
Here is the full log of video download using tartube, the thumbnail is acutally embed in the video without any problems, but tartube doesn't show the thumbnail and "no link" and that things
https://pbin.zzls.xyz/?94d9b4c4946b0d36#EpzZ1odu32ztPc6UY6fqVAA4wcPXrY7rBWBrAsTgHvN7
and i don't need to do it on console (AFAIK) since now the problem it's with TarTube itself trying to identify the thumbnail and the video info. I have take a look to the video propierties in TarTube and in the "File" entry, the video ends in .mkv and not in .mp4 (since i am remuxing it to mp4, using advanced options in the post-processing section of download options). 
Also, i have to enable the file write options > "**Write video's metadata to an .info.json file**" to be able to shot the info of the video like the lenght and the youtube link

+ https://ii.zzls.xyz/KRLCHPI.png

+ https://ii.zzls.xyz/NEFCYGI.png

**Comment by axcore** [comment]
I understand your situation like this:

After disabling **Convert .webp thumbnails into .jpg thumbnails...**, thumbnails are embedded in your videos successfully, but the thumbnails are not visible in Tartube's main window.

If **Convert .webp thumbnails into .jpg thumbnails...** is enabled, thumbnails are visible in Tartube's main window, but are not embedded in the videos.

The .webp images are not visible in Tartube's main window because the Gtk graphics library can't display .webp at all. I will try to find a solution, but my workload is very heavy, you might have to wait a few days. 

In the meantime, you can convert the .webp thumbnails into .jpg thumbnails, **after** the download has finished: click Operations > Tidy up files, in the new window select **Convert .webp thumbnails to .jpg using FFmpeg**, then click *OK** to start the conversion. They should then be visible in Tartube's window.

**Comment by axcore** [comment]
Ok, after thinking about this carefully, I decided that the best course of action was to allow the user to retain the original .webp thumbnail, as well as producing a converted copy that can be used in Tartube's Videos tab. 

The behaviour can be changed in **Edit > System preferences.. > Operations > Downloads**, if necessary.

I think this will solve your problem, but feel free to re-open the issue if it doesn't work.
