### ISSUE TITLE
YT Download into mp3 - Settings

### ISSUE THREAD

**Issue by RiderTwix** [axcore/tartube#462]
Thanks for taking the time to ask a question! 

Hi,

first of all thanks for this very nice tool. :)

However, after two hours of research and try and error I was not able to do the following with Tartube 2.4.077.
I want to download a YT clip and let Tartube convert it directly into  mp3 with 320Kbit/s. 
Under "post-processing" the check box is set, mp3 is selected, audio quality is set to high. There is no way to set the output bitrate to 320KBit/s. 
Anyway, Tartube doesn't even do the convert. It just downloads a webm and stops. 

If I manually right-click on the downloaded  file in classic mode and say "Process with ffmpeg" there is also no way to extract the audio and set the parameters like I want to.

Please tell me if there is a bug or what could be the problem here? Between my ears? ;-)

Cheers
Joe

**Comment by axcore** [comment]
Firstly make sure you have installed FFmpeg.

Secondly, the format options in the Classic Mode tab override any download options you have selected. So remove the override by setting the **Format** box to **Default**.

![default](https://user-images.githubusercontent.com/37951926/198508376-94c8f3f1-8f55-4f58-984c-762d7baecdf1.png)

Thirdly, there is more than one set of download options, so make sure you are using the set that applies to the Classic Mode tab. Click the menu in the top-right corner, and select **Edit Download options**.

If that doesn't work, download a video and show me a screenshot of the **Output** tab, including the yellow text at the top.

**Comment by axcore** [comment]
The high/medium/low setting corresponds to an FFMpeg setting in the range 0 (high) to 10 (low). The "high" setting ought to produce and audio bitrate of 320KBit/s, or better. If not, you can manually specify the bitrate:

`--audio-quality 320k`

![bitrate](https://user-images.githubusercontent.com/37951926/198511751-9fc4675a-d3bd-4647-bd6b-385e40c7d1ea.png)

**Comment by axcore** [comment]
I added 320k to the drop-down box in today's release. The new code is only downloadable from Github or PyPI. If you're on MS Windows, you can update your installation as described [here](https://github.com/axcore/tartube#71-tartube-wont-installwont-rundoesnt-work).

**Comment by RiderTwix** [comment]
Thanks. That worked. I checked the download options as you said and there wasn't any post-processing activated. I activated it and it worked. :-)

But to be honest its a bit confusing where all these different "Download Options" "Download Configuration" "Set Download Option" "Edit Donwload Options". It was absolutly not comprehensible that there are even separate settings for each tab. 

Anyway, thank you for your kind help. :)
Cheers
Joe

**Comment by axcore** [comment]
It used to be the case, that the same set of download options applied to both the **Vides** and **Classic mode** tabs. But people complained about that, too :)

If you want the same set of download options to apply in both tabs, click **Edit > System preferences... > Options**. In the list, click **general** to select it, then click the **Use in Classic Mode tab** button.

**Comment by RiderTwix** [comment]
Yes, I definitely should read the manuals. ;-) But thanks anyway for your quick help. 

Have a nice evening
Joe
