### ISSUE TITLE
TarTube gets stuck on tidying

### ISSUE THREAD

**Issue by OneSteelTank** [axcore/tartube#463]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
If using MS Windows, are you using Windows 10, Windows 7, or something else?

Windows 10

### What version of Tartube are you using?
In Tartube's main window, click Help > About

v2.4.093

### What happens when you run Tartube from a terminal window?
Many error messages are only visible in the terminal window. On MS Windows, this is how to do it:

- First, enable hidden folders on your system
- Then, run the application: 

    C:\Users\YOURNAME\AppData\Local\Tartube\msys64\mingw64.exe

- In this new window, type these commands to start Tartube:

    cd /home/user/tartube

    python3 tartube/tartube

N/A, starts fine

###If your bug report is "I can't download this video", please provide a link to the video
This will save a lot of time!

When I choose a folder, playlist, or channel and select "Tidy files" and then select the things I want it do and press OK, nothing happens and it sits on Tidying indefinitely (I left it for several hours and it was still showing Tidying)

**Comment by axcore** [comment]
There is almost certainly a python error, visible only in the terminal window, that only appears once the tidying starts. So I would like to see that.

If you update your Tartube install using the latest code here on github (as described [here](https://github.com/axcore/tartube#71-tartube-wont-installwont-rundoesnt-work)), the error will be visible in Tartube's window and you won't need to look at the terminal window.

**Comment by OneSteelTank** [comment]
Sorry for the delayed response. I downloaded the Stable release v2.4.093 source code and copied it into the directory and then restarted. The only error I've gotten after restarting is "#107: Failed to remove directory 'E:/Tartube/.temp'"

**Comment by axcore** [comment]
Should be fixed in v2.4.149 (only available from github/pypi at the moment, but it will be in the next full release. Installations on MS Windows can be updated manually, see [here](https://github.com/axcore/tartube#71-tartube-wont-installwont-rundoesnt-work).)
