### ISSUE TITLE
Option to re-use download options without cloning?

### ISSUE THREAD

**Issue by BmoXD** [axcore/tartube#464]
Hello,

First of all, I would like to thank you for creating this excellent tool :)

I have a question regarding download options. Is there a way to reuse the same download option for multiple folders? As far as I know, You can only clone download options, which means each time I want to apply a download option to a folder, I have to create a duplicate, and that adds up to a long dropdown menu of the same download option.

The situation for me is that I have two download options. One is for downloading live streams without the chat, basically --live-from-start and not downloading subtitles. The second one is for downloading only the chat since you can't download the chat and the livestream in the same instance. I have multiple channels from which I download live streams and would like to reuse, not clone, my download options.

**Comment by axcore** [comment]
Added in v2.4.149 (only available from github/pypi at the moment, but it will be in the next full release. Installations on MS Windows can be updated manually, see [here](https://github.com/axcore/tartube#71-tartube-wont-installwont-rundoesnt-work).)

You should be able to shared download options between unrelated folders. It is brand-new code, fresh of the production line, so please report any problems you find.
