### ISSUE TITLE
Fedora 37 cant install by python(abi) = 3.10

### ISSUE THREAD

**Issue by chriztheanvill** [axcore/tartube#465]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Fedora 37 KDE

### What version of Tartube are you using?
tartube-2.4.93-1.noarch

### What happens when you run Tartube from a terminal window?
Cant install

```bash
sudo dnf install ./tartube-2.4.093.rpm
[sudo] password for mypc: 
Last metadata expiration check: 0:51:44 ago on Tue 15 Nov 2022 01:56:36 PM CST.
Error: 
 Problem: conflicting requests
  - nothing provides python(abi) = 3.10 needed by tartube-2.4.93-1.noarch
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by axcore** [comment]
In the meantime, Tartube can still be install [via PyPi](https://github.com/axcore/tartube#535-install-using-pypi), or just [install from source](url), or just run the source code.

**Comment by axcore** [comment]
Today's .rpm release is compiled on Fedora 37, which will probably resolve your issue. If not, feel free to re-open it.

**Comment by jtfen86** [comment]
I'm having this issue. On Nobara Linux 37 (A spin of Fedora 37).

```
[jtfen@JFPC1 Linux Installers]$ sudo dnf install ./tartube-2.4.221-STRICT.rpm
Last metadata expiration check: 2:07:20 ago on Wed 18 Jan 2023 09:29:15 PM PST.
Error: 
 Problem: conflicting requests
  - nothing provides python(abi) = 3.10 needed by tartube-2.4.221-1.noarch
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by axcore** [comment]
Hmmm, I'm not sure how that can be resolved. In case installation fails in the future, there are other installation methods available (see the README).
