### ISSUE TITLE
CWE-77, CWE-624, and CWE-185 in ytdl_path_default

### ISSUE THREAD

**Issue by ivanstepanovftw** [axcore/tartube#466]
Cannot open settings after setting custom yt-dlp path.

### What operating system are you using?
Windows 11

### What version of Tartube are you using?
v2.4.093

### What happens when you run Tartube from a terminal window?
```
C:/Users/i/AppData/Local/Tartube/msys64/mingw64/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'strikethrough-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
C:/Users/i/AppData/Local/Tartube/msys64/mingw64/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'underline-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
C:/Users/i/AppData/Local/Tartube/msys64/mingw64/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'weight-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
C:/Users/i/AppData/Local/Tartube/msys64/mingw64/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'style-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
Traceback (most recent call last):
  File "C:/Users/i/AppData/Local/Tartube/msys64/mingw64/lib/python3.10/sre_parse.py", line 1051, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\P'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users\i\AppData\Local\Tartube\msys64\home\user\tartube\tartube/mainapp.py", line 24225, in on_menu_system_preferences
    config.SystemPrefWin(self)
  File "C:/Users\i\AppData\Local\Tartube\msys64\home\user\tartube\tartube/config.py", line 19265, in __init__
    self.setup()
  File "C:/Users\i\AppData\Local\Tartube\msys64\home\user\tartube\tartube/config.py", line 109, in setup
    self.setup_tabs()
  File "C:/Users\i\AppData\Local\Tartube\msys64\home\user\tartube\tartube/config.py", line 19497, in setup_tabs
    self.setup_downloader_tab()
  File "C:/Users\i\AppData\Local\Tartube\msys64\home\user\tartube\tartube/config.py", line 24697, in setup_downloader_tab
    self.setup_downloader_paths_tab(self.downloader_inner_notebook)
  File "C:/Users\i\AppData\Local\Tartube\msys64\home\user\tartube\tartube/config.py", line 25051, in setup_downloader_paths_tab
    self.update_ytdl_combos()
  File "C:/Users\i\AppData\Local\Tartube\msys64\home\user\tartube\tartube/config.py", line 33183, in update_ytdl_combos
    ytdl_path_default = re.sub(
  File "C:/Users/i/AppData/Local/Tartube/msys64/mingw64/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:/Users/i/AppData/Local/Tartube/msys64/mingw64/lib/python3.10/re.py", line 326, in _subx
    template = _compile_repl(template, pattern)
  File "C:/Users/i/AppData/Local/Tartube/msys64/mingw64/lib/python3.10/re.py", line 317, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "C:/Users/i/AppData/Local/Tartube/msys64/mingw64/lib/python3.10/sre_parse.py", line 1054, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \P at position 2
```

Before all of that, setting of custom yt-dlp was not saved after restarting tartube (because it cannot cancel operation).

Thanks for app, but Tartube is not working. I have installed it from chocolatey.

**Comment by ivanstepanovftw** [comment]
Omg isn't it path escape problem???

**Comment by ivanstepanovftw** [comment]
Please fix this and add button to select youtube-dl path...

**Comment by axcore** [comment]
Please show me the yt-dlp custom path.

**Comment by ivanstepanovftw** [comment]
`C:\ProgramData\chocolatey\bin\yt-dlp.exe`

**Comment by ivanstepanovftw** [comment]
You can test some other path, for example `rm -rf`

**Comment by axcore** [comment]
Short answer:

Tartube does not support MS Windows executables. You must install yt-dlp and FFmpeg from Tartube's main menu.

Long answer:

On MS Windows, Tartube is running inside the MSYS2 environment. MSYS2 does not work well with with MS Windows binaries. The MS Windows version of FFmpeg definitely does not work. The MS Windows version of yt-dlp might work, but probably doesn't, I have not tested it.

I will change the "Use custom path" setting to warn the user, if they set a path that is outside the MSYS2 filesystem (on your computer, that is `C:/Users\i\AppData\Local\Tartube\msys64\`).

On MS Windows, the "Use custom path" setting is not recommended. It _might_ be useful, if you have opened the mingw64 terminal window (C:/Users\i\AppData\Local\Tartube\msys64\mingw64.exe) and installed yt-dlp there. Otherwise, you should avoid it.

**Comment by axcore** [comment]
>When I use "native" yt-dlp downloaded by Tartube, nothing happens

Ok, so let's fix that problem. First reset the downloader in **Edit > System preferences > Downloaders > File paths** so it is using the "native" yt-dlop. Then try downloading [this video](https://www.youtube.com/watch?v=jNQXAC9IVRw). If if it doesn't work, show me the contents of Tartube's Output tab (especially the yellow text at the top).

>BTW why are you using MSYS2 in frontend application?
As far as I know, it is the only way to run Gtk applications in Windows. It requires some compromises, for example we can't run the MS Windows version of FFmpeg, but most things work very well.

**Comment by ivanstepanovftw** [comment]
Under WSL2 I have provided `/usr/bin/yt-dlp` path. Why does it prepends `/home/$(whoami)/.local/bin/`??? Is this kind of trolling?
```
/home/i/.local/bin//usr/bin/yt-dlp --newline -i --hls-prefer-native --write-description --write-info-json --cookies /mnt/c/Users/i/Videos/Tartube/cookies.txt --write-thumbnail --output /mnt/c/Users/i/Videos/Tartube/Unsorted Videos/%(title)s.%(ext)s https://www.youtube.com/watch?v=jNQXAC9IVRw
Download did not start
```

Install steps:
```
sudo apt install python3-gi gobject-introspection gir1.2-gtk-3.0 python3-cairo-dev
sudo apt install ./path/to/tartube.dep
```

**Comment by ivanstepanovftw** [comment]
Started to work under WSL2 after `mkdir -p /home/$(whoami)/.local/bin` and providing `../../../../usr/bin/yt-dlp` path...

**Comment by ivanstepanovftw** [comment]
yt-dlp is fully written in Python and cover needs of video downloader backend, youtube-dl is very legacy. Why do you even need to call it as process? In case if anyone wanted to use #434? Nah, they can't.

Why pygtk have been choosen if it is not production ready, ie it needs whole linux abstraction layer like msys2?

**Comment by axcore** [comment]
>Tartube cannot open settings because of above python exception. I need to reset settings somehow.

The settings file is in Tartube's code folder. In Tartube's main menu, **System > Show Tartube script folder**

>Under WSL2 I have provided /usr/bin/yt-dlp path. Why does it prepends /home/$(whoami)/.local/bin/??? Is this kind of trolling?

I will check the code, and then give you a full answer. But: Tartube assumes that all Windows users are using my installer. If you can find an alternative method of installation, then I will need to make some code changes.

>youtube-dl is very legacy, yt-dlp is fully written in Python and cover needs of video downloader backend. Why do you even need to call them as process? Why not embedding yt-dlp?

There are several reasons, firstly yt-dlp did not exist when Tartube was written. Secondly there have been several forks of youtube-dl and most of them have failed.
Will yt-dlp still exist in six months? I hope so, but I can't be certain about it. Thirdly, if the yt-dlp code is embedded then I must update Tartube every time yt-dlp is updated. That is not a good use of my time, because it doesn't give any benefits to the user.

>Why pygtk have been choosen if it is not production ready, ie it needs whole linux abstraction layer like msys2?

Tartube is using pygobject, not pygtk. As far as I know, pygtk doesn't work at all any more.

**Comment by axcore** [comment]
Sorry for the delay. WSL cannot be installed on my machine, so I cannot test your problem.

In **Edit > System preferences > Downloaders > Forks**, I suspect that you have selected these options:

![badfork](https://user-images.githubusercontent.com/37951926/203312266-5011d194-e522-499b-929a-cf0307761546.png)

Please check that, and change the setting to **Use yt-dlp**. Then, in the tab **File paths**, you can set **Use custom path** and **/usr/bin/yt-dlp**

**Comment by axcore** [comment]
In today's release (v2.4.149, only available from pypi/github) I have changed the code, so it's no longer possible to add /home/i/.local/bin/yt-dlp in the **Use this fork** box. I also marked the **Use custom path** option as "not recommended" on MS Windows.

**Comment by markonop93** [comment]
this is not good. have to install everything 2 times. I hope one day this can use windows installed yt-dlp and other things. but installled for now

**Comment by axcore** [comment]
Closed for inactivity.
