### ISSUE TITLE
"tartube failed to start ip config file locked somehow?

### ISSUE THREAD

**Issue by medicisounds** [axcore/tartube#468]
Was using tartube fine the last couple days. I just tried to open it today and it seems to be an error.

Thanks for taking the time to ask a question! 

### Please read the README
Perhaps your question is answered there

### The authors are not experts in python, security, youtube-dl, FFmpeg, Debian/RPM packaging or Windows programming
You are welcome to ask a Tartube-related question, but you might get a better answer in forums where those kinds of expert can be found

**Comment by axcore** [comment]
Can you describe the error? Can you see any Tartube windows at all?

**Comment by medicisounds** [comment]
so i kept getting that error so i uninstalled but now it wont install FFMPEG. And when i try to download videos it only downloads them in some weird webm extension even though i m trying to convert it to WAV.

**Comment by axcore** [comment]
The software library that supplies FFmpeg appears to be broken today. You'll have to wait a day or two for it to be fixed.

**Comment by axcore** [comment]
I think FFmpeg installation problems are currently resolved, but feel free to re-open this issue if that's not the case.
