### ISSUE TITLE
Translation - questions

### ISSUE THREAD

**Issue by daufinsyd** [axcore/tartube#469]
Hey :)
I installed the app a few days ago and I find it amazing !
I started translating it to french using the weblate I found on this ticket #428, I hope to achieve the translation soon however I don't understand why there is some english strings begining with "_" for example:
` _Watch on Website`
Or even more strange 
`Use _default download options`

I guess _ is certainly the translator symbol in order to tell Gtk to translate it automatically but how should one translate it?

My bet is to get rid of it ?

Thanks !

**Comment by axcore** [comment]
It is the keyboard shortcut. 

For example, in Tartube's menu click File > Save all

Or, press ALT+F, ALT+A

In the string "Save _all", the underline goes before the key to be pressed

My suggestion is that you remove the underline in your translations. And thanks for your contribution!

**Comment by daufinsyd** [comment]
Hi @axcore 
Thank your for your explanation, I just finished translating and reviewing past translations !

`My suggestion is that you remove the underline in your translations, for example "Save _all" becomes "Sauvez tout". (Sorry, I don't speak French.)`
We would say "Tout sauvegarder" since "Sauvez tout" would imply that there is an ongoing disaster :D

There are a few sentences I just don't get the meaning like:

-  Set visible page
-  Patience preset

There were also lots of duplicates entries, but I think you can include the translation :)

**Comment by axcore** [comment]
> Set visible page

It's in the Videos tab, in the toolbar at the bottom:

![visible3](https://user-images.githubusercontent.com/37951926/204782639-4ab4ce63-aae3-44e4-96c9-79bb78b98ce0.png)

>Patience preset

I think it is FFmpeg jargon. Right-click a video, and click Special > Process with FFmpeg. In the new window, click the "Show more FFmpeg options" button, then click the Settings tab.

I think it means "conversion speed" or something like that.

>There were also lots of duplicates entries

The translation generator is supposed to eliminate duplicates, I don't know why they exist. I will look into that.

>but I think you can include the translation :)

Ping me when you're happy with it.

**Comment by daufinsyd** [comment]
Thanks for your explanations.
Sure ! Allow me a few days so that I can review the translation :p

**Comment by daufinsyd** [comment]
Hi @axcore 
I reviewed the translation. You can merge it.

**Comment by axcore** [comment]
Great, it is merged in v2.4.190 (available from pypi/github only), and it will be in the next main release when that happens. In case you want a credit that's not "daufinsyd", speak up now :)

I have been wondering for a long time, whether the task of translating Tartube is too difficult. Specifically, I have been wondering whether I should add annotations so the translator can quickly find the text in Tartube's window.

For example: the string "Other format options", perhaps the translator would like to know that it's in Edit > General download options > Formats > Advanced.

Perhaps you have some thoughts about that.

**Comment by daufinsyd** [comment]
:D can't wait to see it in actions !

> I have been wondering for a long time, whether the task of translating Tartube is too difficult. Specifically, I have been wondering whether I should add annotations so the translator can quickly find the text in Tartube's window.
Well there is a few notes (like what means D/L) but indeed some context or description would be definitely help full (like set visible page).

Definitely !
It's usefull since for example "download settings" can be translated to "paramètres des téléchargements" or "paramètres du téléchargement" depending on the context (are we talking about the settings of some current file being downloaded for example).

When I couldn't chose, I tried to be more exhaustive but it tends to become really verbose (especially in french).

With "Edit > General download options" I know we're not talking about a particular file.

**Comment by axcore** [comment]
> :D can't wait to see it in actions !

If you're using MS Windows, you can just download the source code from here on Github, and copy it into Tartube's installation folder, as described [here](https://github.com/axcore/tartube#71-tartube-wont-installwont-rundoesnt-work).

**Comment by axcore** [comment]
In v2.4.245 I have added hundreds of annotations for translators. With that I will close the issue, thanks again for your hard work!
