### ISSUE TITLE
Better support for my viewing habits

### ISSUE THREAD

**Issue by MikkoMMM** [axcore/tartube#47]
I think this project might be closest that I've yet seen to my own vision for a good video manager. Beyond some glitches I think I'm having (I don't always know how it is supposed to operate, so reporting might be difficult at times), it also seems to have a bit of a learning curve. So some feedback might be unwarranted because I just don't understand something.

Anyway, I see that under advanced download options, there is "Maximum downloads from a playlist". However, this doesn't seem to stop youtube-dl from downloading the entire playlist (on 1.3.007; playlists seem to be wonky for me with master). So that seems to just not work currently if I'm not missing something. I have my videos stored on a USB stick so space is limited so I cannot afford to download potentially hundreds of full-HD videos for each playlist.

For "Format for video file names" I'd request "Autonumber + Title" as a listed option. I didn't manage to get in pretty much any testing with it yet, but I know I've encountered some issues with youtube-dl's built-in autonumbering on my own video manager implementation. I don't know if it handles individual videos sensibly on Tartube, and how it handles the cases where downloading of a playlist is started from anywhere but the beginning. I personally prefer if it will use the index on the playlist as the number it puts in the file name (except the reverse if using reverse playlist mode). However, if I remember correctly, youtube-dl will want to always start from index 1 in its numbering.

And here's something I'm pretty sure Tartube simply cannot at least easily be used for (I suppose maybe messing with the Post-processing tab could allow for this). Splitting up videos into reasonable-length chunks after they've been downloaded. I even have it on a two-tier system on my own video manager implementation: if the video doesn't exceed a minimum length (which I've set to 30 minutes), it will not split the video. However, if it exceeds that length, it will call ffmpeg to split it up into 20 minute parts.

The subtitles tab in settings talks about subtitle files, but what about embedding the subtitles? Couldn't that be offered as an option to choose (or are the options just named misleadingly)? Also, as a non-native English speaker, I also want the subtitles also in my own native language if available. However, Tartube currently only offers easy access to just none, one or all subtitles.

Well, I've been mentioning my own implementation and here it is, even though it's not quite yet suited for use of the general public. https://github.com/MikkoMMM/youtube-library

Short usage instructions would be to change the values in the beginning of download.py to match your preferences, and call download.py with a playlist URL as a parameter. And currently only Linux is "officially" supported; though calling it with --choplength=0 should disable the video splitting functionality that I, as it is now, see as problematic on Windows at least but still, I've not done any testing outside Linux.

**Comment by axcore** [comment]
>Anyway, I see that under advanced download options, there is "Maximum downloads from a playlist". However, this doesn't seem to stop youtube-dl from downloading the entire playlist (on 1.3.007; playlists seem to be wonky for me with master)

If you can give me the URL of a playlist which doesn't behave as expected, I can test it for you.

>However, if I remember correctly, youtube-dl will want to always start from index 1 in its numbering.

Yes, this is a known limitation of youtube-dl. Some users of youtube-dl-gui have also complained about it. I will think about it, maybe there is something that can be done.

>Splitting up videos into reasonable-length chunks after they've been downloaded.

All video processing is handled by FFmpeg or AVConv. Neither Tartube nor youtube-dl do their own video processing.

I'm not sure how it could be done, but you can pass any arguments you like to the post-processor. Click Edit > General download options... > Post-processing > Arguments to pass to postprocessor

In the tab, you must click Post-process video files to convert them to audio-only files, or nothing will happen.

>The subtitles tab in settings talks about subtitle files, but what about embedding the subtitles?

The option for that is on the same tab - **Merge subtitles file with video** . I havent' tested it, so you can test it, and tell me if it works.

>However, Tartube currently only offers easy access to just none, one or all subtitles.

No problem, I can modify the code so  you can add multiply subtitle languages. (In Edit > General download options > Subtitles > Download subtitles file for this language)

**Comment by MikkoMMM** [comment]
> If you can give me the URL of a playlist which doesn't behave as expected, I can test it for you.

Well, I tested it on master, and maybe my confusion was from having pressed Download all multiple times. The option means that it downloads at most that many videos at a time, not that it's the maximum stored.  Though, for me the latter would be the preferable way of operation.

I did notice that it still says "Downloading...", though, but doesn't download any more after the two I set it to. Here's a playlist with fairly small videos I felt was appropriate for testing:
https://www.youtube.com/playlist?list=PLB3A7CCFD7CD5CF09

> Yes, this is a known limitation of youtube-dl. Some users of youtube-dl-gui have also complained about it. I will think about it, maybe there is something that can be done.

What I did myself is not rely on youtube-dl's playlist downloading functionality but implemented my own. I keep my own record of which video is next in line to be downloaded and use it as the number to be put into the file name. Who knows if I was reinventing the wheel, but at least that way I got "full control" of the process. Though, I suppose I could be less careful than you would have to be since I was making it for my own purposes only so I didn't think how it would affect other sites than YouTube.

> The option for that is on the same tab - Merge subtitles file with video . I havent' tested it, so you can test it, and tell me if it works.

Oh, you meant the Post-processing tab. It's kind of in a difficult to find spot, being an advanced setting and not under Subtitles, but at least the option is there, then. I don't feel it's a very urgent thing for me to test.

> All video processing is handled by FFmpeg or AVConv. Neither Tartube nor youtube-dl do their own video processing.

Yes, I thought as much. Here's the command for where the action happens that I use:
`ffmpeg -i "${video}" -c copy -map 0 -segment_time "$chunksize" -f segment -loglevel warning "${basename}_%03d${extension}"`
I'm not sure how those $parameters would have to be modified (except chunksize can be "20:00").

**Comment by MikkoMMM** [comment]
By the way, here's something else that I'm not sure exactly how you might want to implement it, but it's still a fairly subtantial usability feature for me: A very simple way to modify some options on (playlist) downloads. In my implementation it asks on new playlists from which index it will start downloading from and each time it's run it asks for how many videos to download from that playlist. Maybe there could be user-favourite download options which are given easier access to (like in the Add playlist screen and maybe for example double clicking a playlist). That's at least a way to generalize what I had so those quick-access options wouldn't need to show up for everyone, just for people who use them.

**Comment by MikkoMMM** [comment]
Well, in 1.3.077 there's now a popup for downloads being complete that wasn't there before for me, and it does indeed stop after the maximum amount of downloads from a playlist has been reached. The UI for that is still kind of misleading, though:

Under "Progress" the # column has a format like "2/95" even though only one video was being downloaded. Also, the Status column shows "Errror" on a successful download. Also, on the Output tab youtube-dl says stuff like `[download] Downloading video 2 of 95`, even though it's not actually going to download it because of the limit. And on the Errors / Warnings tab it says "Child process exited with non-zero code: 101". So I suppose it's in many ways confusing even though working.

**Comment by axcore** [comment]
@MikkoMMM , I am testing some things, so I don't have full replies for you yet. But:

In the Progress tab, in the top half of the window, lots of statistics are displayed. These statistics are generated by the code I borrowed from youtube-dl-gui. I understand that they might be a little confusing, but re-writing the borrowed code is not something I would enjoy.

"2/95" means that there are 95 videos in the channel/playlist, and that youtube-dl is currently downloading the second most-recent one. If you have downloaded no videos, you will see "2/95". If you have downloaded the other 94 videos, you will still see "2/95".

The Status column shows the most serious problem. If you try successfully download 94 videos, but 1 video generates an error message, then you will see "Error". Sometimes the error is not fatal. A common reason is that youtube-dl tried to convert a file to MP4, failed, and instead saved the original MKV file.

The Output tab just displays the output from youtube-dl. If it's confusing, there is nothing I can do about it :)

You can choose to block many kinds of error message in the Errors/Warnings tab. Unfortunately, the code that handles the "Child process exited with non-zero code" message is broken in v1.3.077. It is fixed now, and you will be able to block it in the next release.

**Comment by axcore** [comment]
v1.4.0 has the following new features:

1. You can tell Tartube to stop a download after some time, after a certain number of videos, or after a certain amount of disk space. Click **Edit > System preferences... > Scheduling > Stop** and choose one or more of the options.
2. I have tested the 'maximum downloads from a playlist' download option, it is working as expected. You can now use it with both channels and playlists.
3. I improved the text for that option, so its purpose is easier to understand.
4. File names in the format 'Autonumber + Title' are now available. Click **Edit > General download options... > Files > File names**  and select one of the format options, for example **Autonumber + Title**
5. I have tested this with a playlist containing 8 videos. I started downloading the videos, starting at video #5. The first video was called '5 - Video name', not '1 - Video name'
6. The 'embed subtitles with video' download option now appears in two different places, to make it easier to find
7. Before v1.4.0, you could only specify one language for subtitles. You can now specify as many languages as you want. Click **Edit > General download options... > Subtitles**, then click **Download subitles file for these languages**, and add the languages you want.

I will close this thread. After testing the new stuff, you can option a new issue, if you have any suggestions or improvements or new feature requests. In general, it's better to create ten new issues, than to open one issue and ask for ten things :)
