### ISSUE TITLE
repeatedly crashing while downloading videos

### ISSUE THREAD

**Issue by Dramatic7335** [axcore/tartube#470]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Kubuntu 22.04.1

### What version of Tartube are you using?
v2.4.165

### What happens when you run Tartube from a terminal window?
the cause of the crash seems to be in this line:

python3: ../../../../src/cairo-surface.c:930: cairo_surface_reference: Assertion `CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&surface->ref_count)' failed.
Aborted (core `dumped)

I saw this issue was mentioned previously however it doesnt seem to have been resolved #217. I was wondering if  any progress has been made when it comes to figuring this out cause tbh Im a noob and using source packages is difficult for me.  but if thats still the best solution its what ill do.

**Comment by axcore** [comment]
Please show me the whole error message, not just the last line.

**Comment by axcore** [comment]
Which installation method did you use? .deb, pypi?

**Comment by axcore** [comment]
Closed for inactivity.
