### ISSUE TITLE
Unable to change "System locale"

### ISSUE THREAD

**Issue by iG8R** [axcore/tartube#471]
Hi.
Windows 10 (21H1, 19043.1415)
Tartube v2.4.165

Can't change the system locale, it's stuck in Russian but I need English.
<details><summary>Screenshot</summary>

![Tartube-System-locale-2022-11-29_040024](https://user-images.githubusercontent.com/11407417/204423415-1249ee78-2fc7-4d85-a992-2c849ed677db.jpg)

</details>

**Comment by axcore** [comment]
The code that handles locales was updated recently. At the moment, Tartube uses your system locale. You can't change the locale in **Edit > System preferences...**

If you need English, then your choices are:

1. Change the system locale on your computer
2. Patch the Tartube code: find the ../tartube/mainapp.py file, find line 3330, and remove it (or comment it out by adding a # at the beginning of the line):

`#        self.apply_locale()`

3. Wait for the next release, I have not finished improving the code yet.

**Comment by iG8R** [comment]
@axcore 
Many thanks)
N.2 worked well.

**Comment by axcore** [comment]
In v2.4.174, you can set any locale from Edit > System preferences...

This version is only available on Github/Pypi. If you want to update your MS Windows installation, see [here](https://github.com/axcore/tartube#71-tartube-wont-installwont-rundoesnt-work).

**Comment by iG8R** [comment]
Thank you. It works:)

Some clarifications:
1. It's 2.4.17**3** version
2. Copying the downloaded source code into Tartube script folder, replacing old files with new ones, didn't work as it turned out `settings.json` from 2.4.165 version doesn't compatible with 2.4.173.
It's necessary to fix correct version number and insert the missing strings to make Tartube to start otherwise `bash.exe` and `conhost.exe` processes are launching but Tartube doesn't start:
   - correct `"script_version": "2.4.165",` to `"script_version": "2.4.173",` in line `#3` 
   - insert `"override_locale": "en_GB",` in line `#7`
   - insert `"match_nickname_flag": true,` in line `#316`

**Comment by axcore** [comment]
Whoops! Just a bit of temporary code I forgot to remove, it's removed now.
