### ISSUE TITLE
Making sorting more correct and both descending and ascending

### ISSUE THREAD

**Issue by iG8R** [axcore/tartube#477]
Windows 10 (21H1, 19043.1415)
Tartube v2.4.173

[https://vk.com/video/playlist/-179915138_55](https://vk.com/video/playlist/-179915138_55)

Please, could you make more correct sorting, e.g. videos have names video-1.mp4, video-2.mp4,... video-10.mp4, video-11.mp4,...,video-19.mp4 and now they are sorted (Sort -> Name) as video-1.mp4 -> video-10.mp4 -> video-11.mp4 ->...-> video-19.mp4 -> video-2.mp4

![Tartube-sorting-2022-12-05_000051](https://user-images.githubusercontent.com/11407417/205518208-7fd3133c-8702-4130-ba10-5168013085c2.jpg)

Also, please, add possibility to sort videos with ascending property not only descending as of now.

**Comment by axcore** [comment]
Added in v2.4.198.

**Comment by iG8R** [comment]
Thank you, it works excellent:)
