### ISSUE TITLE
Video's thumnails location and types oddity

### ISSUE THREAD

**Issue by iG8R** [axcore/tartube#478]
Windows 10 (21H1, 19043.1415)
Tartube v2.4.173

[https://vk.com/video/playlist/-179915138_55](https://vk.com/video/playlist/-179915138_55)

I'm trying to store video's thumbnails in a sub-folder to make main folder clean, but whatever options did I use, the result still the same - messing thumbnails (mixture of .webp and .jpg formats) and their storage itself (existence both of the .thumbs folder and thumbnails in the main folder).
All this happens when checking any playlist multiple times.
PS. I tried to uncheck **Download options -> Files -> Write\Move -> Write the video's thumbnails to the same folder** but in this case thumbnails weren't created at all.

<details><summary>**Screenshots**</summary>

![Tartube-Thumbs-Sys-Oper-Down-2022-12-05_015249](https://user-images.githubusercontent.com/11407417/205524187-7c3d2b00-5cea-432d-a733-e58567b78ccd.jpg)
![Tartube-Thumbs-Down-Files-Write-2022-12-05_015347](https://user-images.githubusercontent.com/11407417/205524192-b658966f-1e63-4c4b-baf9-6ff6c59969f6.jpg)
![Tartube-sorting-2022-12-05_012108](https://user-images.githubusercontent.com/11407417/205524406-3e65f716-64fe-45cd-8467-807601998d47.jpg)
![Tartube-Thumbs-sub-folder-2022-12-05_022739](https://user-images.githubusercontent.com/11407417/205525551-7d3f8ae7-9bc4-4cf6-8327-93e9af44b84d.jpg)

</details>

**Comment by axcore** [comment]
The thumbnails for videos 1-36 are not valid .webp images, so Tartube rejects them.

The valid .webp images are delivered by a different server (e.g. invalid 36 comes from https://i.mycdn.me/getVideoPreview?id=2060310153901&idx=7&type=39&tkn=R2w7R1CvxIImSZLjz0fGy2H9jDM&fn=vid_x, valid 37 comes from https://sun6-22.userapi.com/pM56Ds_ZlmAN_JOeW4DL845qbc8uyFW4UHBtIA/zMVaVSl4Jz8.jpg). So the cause of this problem is probably "VK is broken".

**Comment by iG8R** [comment]
Is it possible to make an option to move all thumbnails, despite valid or not valid, to the .thumbs folder for keep the main folder clean and containing only videos?

**Comment by axcore** [comment]
Yes, in the meantime you can remove unwanted .webp in **Operations > Tidy up files...**

**Comment by iG8R** [comment]
**Operations -> Tidy up files... -> Delete all .webp thumbnails** doesn't work at all, all "not valid" .webp remains where they were. 
Making **Operations -> Tidy up files... -> Convert .webp thumbs to .jpg using FFmpeg** does nothing with these "not valid" .webp also.

**Comment by axcore** [comment]
I will check **Operations -> Tidy up files... -> Delete all .webp thumbnails**, but **Convert .webp thumbs to .jpg using FFmpeg** definitely will not work, because the same code will reject the invalid .webp thumbs.

About the portable version - it is exactly the same, except there is a new .bat file.

**Comment by iG8R** [comment]
@axcore 
Thumbnails are still placed not only in the .thumbs folder.

![Tartube-Thumbs-Video_2022-12-10_173816_edit](https://user-images.githubusercontent.com/11407417/206865299-4e697903-5442-4855-ac9b-dac6496b335b.gif)

**Comment by axcore** [comment]
Go to **Edit > System preferences... > Operations > Downloads**, and disable **...but don't delete the original thumbnails**

This setting is enabled by default, because failure to embed thumbnails in videos is a much worse problem, than a few extra .webp thumbnails that can be removed later.

**Comment by iG8R** [comment]
> Go to **Edit > System preferences... > Operations > Downloads**, and disable **...but don't delete the original thumbnails**

This option has been disabled from the very beginning.
![Tartube-thumbs-deleteOption-2022-12-11_204138](https://user-images.githubusercontent.com/11407417/206922482-22522d25-378a-4446-83ad-eb95bb089632.jpg)

**Comment by axcore** [comment]
Hmmm, I just tested this again, a couple of thumbnails are not moved but most are.

![vk5](https://user-images.githubusercontent.com/37951926/206978321-82130f9e-cad1-495c-8c53-3c11f6629cd9.png)

**Comment by axcore** [comment]
I tested your problem again today.

On Linux, the results are exactly the same as the photo above: all thumbnails are moved, but 1 and 2 still exist. yt-dlp is downloading those two videos twice, for some reason. The thumbnails are not moved, because Tartube code doesn't overwrite an existing file.

![tartube1](https://user-images.githubusercontent.com/37951926/208394174-e5b1e895-2e82-4144-8c06-3ee65adfbbf3.png)

On MS Windows, I see the same results as you: 1-36 still exist. 

I did some more detailed testing, and I discovered that the python function os.rename() creates a new thumbnail.jpg, but does not remove the thumbnail.webp. The same function works perfectly on Linux.

Sorry, but I don't know how this can be fixed.

**Comment by iG8R** [comment]
Why not initially make the option to write thumbnails into the sub-folder (.thumbs folder)? Instead of write them into the main folder and then move to the sub-folder?
I tried the following and all did work perfect:
1. `yt-dlp.exe -i --skip-download --write-thumbnail https://vk.com/video/playlist/-179915138_55 -o "thumbnail:.thumbs\%(title)s.%(ext)s"`
2. `yt-dlp.exe -i --skip-download --write-thumbnail --convert-thumbnails jpg --ppa "ThumbnailsConvertor:-q:v 1" https://vk.com/video/playlist/-179915138_55 -o "thumbnail:.thumbs\%(title)s.%(ext)s"`
3. `yt-dlp.exe -i --skip-download --write-thumbnail --convert-thumbnails webp --ppa "ThumbnailsConvertor:-q:v 1" https://vk.com/video/playlist/-179915138_55 -o "thumbnail:.thumbs\%(title)s.%(ext)s"`

[!(1)](https://user-images.githubusercontent.com/11407417/208856097-b6afe88e-e540-44c9-adb0-0d413b16c936.webm)

[Tartube-Thumbs-Video_2022-12-20_010056_0200-0349.webm](https://user-images.githubusercontent.com/11407417/208856142-ec9612b3-350f-4b2e-9fa7-cae450b02bd2.webm)

[Tartube-Thumbs-Video_2022-12-20_010056_0350-0603.webm](https://user-images.githubusercontent.com/11407417/208856164-4a4a2259-3faf-4693-aaf0-1bf6fde1ba66.webm)

**Comment by iG8R** [comment]
The only thing I don't understand why in your case some thumbnails were downloaded with jpg extension the other ones - with webm though they are jpg.

**Comment by axcore** [comment]
>Why not initially make the option to write thumbnails into the sub-folder 
 
I will look into that

>The only thing I don't understand why in your case some thumbnails were downloaded with jpg extension the other ones

Presumably VK servers are broken, I have not tried to report the problem because these big companies never respond to bug reports. YouTube has been sending broken .webp files for years, and that is also not fixed yet :)

**Comment by iG8R** [comment]
> > Why not initially make the option to write thumbnails into the sub-folder
> 
> I will look into that

Thank you.


> > The only thing I don't understand why in your case some thumbnails were downloaded with jpg extension the other ones
> 
> Presumably VK servers are broken, I have not tried to report the problem because these big companies never respond to bug reports. YouTube has been sending broken .webp files for years, and that is also not fixed yet :)

As you can see in my aforementioned screen videos all thumbnails were downloaded in jpg format not one in webm.
Maybe you used some other arguments to download them instead of the ones I used?

**Comment by axcore** [comment]
>Why not initially make the option to write thumbnails into the sub-folder

Using output templates to move the thumbnail into a sub-folder is not feasible because of some boring technical reasons. I can list the reasons, if you want to read them.
