### ISSUE TITLE
Is there a simultaneous download of videos from different folders and playlists?

### ISSUE THREAD

**Issue by iG8R** [axcore/tartube#479]
Windows 10 (21H1, 19043.1415)
Tartube v2.4.173

I'm trying to download videos from different folder and playlist at the same time. I started from the folder's video, but when I tried to download playlist's videos it didn't start and what I got is the following:

![Tartube-simult-download-2022-12-08_232929](https://user-images.githubusercontent.com/11407417/206572300-bdceeceb-31ef-4cb4-8476-4980472c9e56.jpg)
![Tartube-simult-download-2022-12-08_233001](https://user-images.githubusercontent.com/11407417/206572315-930c6df6-720b-447d-af91-a2b585304bcb.jpg)

**Comment by axcore** [comment]
I can't reproduce this problem, but I'm not sure what you did.

1. Create a custom download call TEST, and enable the **Download each video independently of its channel or playlist** option
2. Create a folder. Add some videos to the folder
3. Create a playlist
4. Right-click the folder, and select **Custom download folder > TEST**
5. The download starts and continues
6. Now right-click the playlist, and select **Download playlist**

Is that what you did, or something different? Please describe the process exactly.

**Comment by axcore** [comment]
Workaround: at the bottom of the window, unselect **Hide rows when they are finished**.

**Comment by axcore** [comment]
I still can't reproduce the problem reliably, although I have also seen it. But in v2.4.221, the error message only appears once for each video. (Much better than appearing 1000000 times for each video.)

**Comment by axcore** [comment]
Closed for inactivity.
