### ISSUE TITLE
Sometimes hanging on quit

### ISSUE THREAD

**Issue by MikkoMMM** [axcore/tartube#48]
I don't know what exactly causes it. When I open up Tartube and immediately use File -> Quit, it closes successfully in an "instant". However, then there are those times when I've been using it for a bit and this is what it manages to get to before freezing, not closing the application:
```
2020-01-23 03:27:33 app 8756 on_menu_quit
2020-01-23 03:27:33 app 1581 stop
2020-01-23 03:27:33 app 1624 stop_continue
2020-01-23 03:27:33 app 2051 save_config
2020-01-23 03:27:33 app 2707 save_db
2020-01-23 03:27:33 app 1231 do_shutdown
```

Ctrl+C then gave:
```
^CException ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt:
```

**Comment by axcore** [comment]
I have tested this problem extensively. As far as I can tell, the only solution is to wait for the Gtk devs to update their buggy code.

Edit > System preferences... > General > Gtk support shows the version of Gtk installed on your system. Anything less than v3.24 causes a number of problems, and the only way to resolve them is to update your system's Gtk to v3.24 or better.

**Comment by MikkoMMM** [comment]
It says I have GTK 3.24.13.

**Comment by mbnoimi** [comment]
@MikkoMMM  I believe this issue related to https://github.com/axcore/tartube/issues/34 because error message is the same.

**Comment by axcore** [comment]
@mbnoimi I think it is not related to [#34](https://github.com/axcore/tartube/issues/34). 

Tartube shuts down using an `os._exit(0)` call, or a `Gtk.Application.quit()` call.

For reasons I don't understand, under certain circumstances, both of these function calls freeze forever. For example, under MS Windows, Tartube will not shut down after updating youtube-dl.

**Comment by axcore** [comment]
I'm not sure what the problem was, but it seems to be fixed in v1.5.015. Feel free to re-open the issue if you notice any similar problems.

**Comment by Jah-On** [comment]
I am also having this issue when in conjunction with pyftpdlib.

**Comment by axcore** [comment]
If you're having problems with the most recent release of Tartube, [this](https://github.com/axcore/tartube/issues/98#issuecomment-634772832) is the most likely cause, so check that first.

**Comment by Jah-On** [comment]
No, I don't have Tartube installed. There have be a FEW times where exited correctly, but its been a 1/30 chance.
