### ISSUE TITLE
Downloading YouTube Clips

### ISSUE THREAD

**Issue by TheInevitableBug** [axcore/tartube#482]
Hi,

Is it possible to download YouTube Clips? For example, when I try to download [this clip from a video](https://www.youtube.com/clip/UgkxBCui4WILm9rfufnJorc7ri471i-A3JJt), I get the following error/s:

![image](https://user-images.githubusercontent.com/98386739/206828398-ccc8c61e-a0a4-4db5-8158-2fc111bbda93.png)

Any help is appreciated!

**Comment by axcore** [comment]
The video clip appears to download sucessfully, but yt-dlp is producing a bunch of error messages. They will probably be fixed when yt-dlp is next updated.

**Comment by axcore** [comment]
https://github.com/yt-dlp/yt-dlp/issues/6354

**Comment by axcore** [comment]
According to yt-dlp developers, the errors are generated by FFmpeg. There isn't much we can do about that, but you can still filter out any messages you don't want, as described above.

**Comment by pukkandan** [comment]
What do you do with `WARNING`s or `[debug]`? If you are whitelisting them automatically, couldn't you add this to it as well?

**Comment by pukkandan** [comment]
FYI: All errors in yt-dlp has a `ERROR: ` prefix. So might be better to just catch that instead of the whitelists

**Comment by axcore** [comment]
>What do you do with WARNINGs or [debug]? If you are whitelisting them automatically, couldn't you add this to it as well?

Tartube handles ERROR/WARNING/debug messages in the same way as the original youtube-dl-gui code: they are ignored, but the messages are available to any user who wants them (for example, in the Errors/Warnings tab). So this is just an annoyance, it doesn't affect core functionality.
