### ISSUE TITLE
Independent downloads by default doesn't work

### ISSUE THREAD

**Issue by iG8R** [axcore/tartube#483]
Windows 10 (21H1, 19043.1415)
Tartube v2.4.190

The title says for itself.
PS. Also there is an issue with the View window that happens from time to time.

[Tartube-MultipleDownloads-and-ViewWindow-issue-Video_2022-12-10_194701.webm](https://user-images.githubusercontent.com/11407417/206882446-d4012834-6c59-4921-82b2-e88a08a5486a.webm)

**Comment by axcore** [comment]
You right-clicked the playlist and selected **Download playlist**, but if you want a custom download, you must select **Custom download channel**.

About the video grid problem: the code to produce a grid of windows is written by me, it isn't included in the Gtk graphics library. Occasionally Tartube doesn't have all the information it needs, so the layout is not correct. But it works most of the time.

You can force the grid to reset by changing the size of the window (for example, maximise then unmaximise it).

**Comment by axcore** [comment]
By the way, in the small windows, the **OK** button and the **Apply** button use exactly the same code. The only difference is that one button closes the window, the other doesn't. So you never need to click **Apply** before **OK**.

**Comment by iG8R** [comment]
> You right-clicked the playlist and selected **Download playlist**, but if you want a custom download, you must select **Custom download channel**.

Maybe my understanding was wrong but from the very beginning Tartube uses 2 standard types of the downloads: general and classic. All their settings by default applied corresponding in the advanced and classic modes. I thought if a user changes their settings it has to be reflected in these modes' download behavior? That's why I created the "1by1" download profile to use it by the Custom donload if I ever needed to download videos one by one like it's initially provided in the Tartube's general profile.



> About the video grid problem: the code to produce a grid of windows is written by me, it isn't included in the Gtk graphics library. Occasionally Tartube doesn't have all the information it needs, so the layout is not correct. But it works most of the time.
> You can force the grid to reset by changing the size of the window (for example, maximise then unmaximise it).

I've tried to resize the window, except maximizing, but to no avail. I'll try it next time when this issue happens again (it does every 5-10 starts and needs some interval of time).


> By the way, in the small windows, the **OK** button and the **Apply** button use exactly the same code. The only difference is that one button closes the window, the other doesn't. So you never need to click **Apply** before clicking **OK**.

This is my long term habit from times when "Apply" implied to apply but not to save into the config file and "OK" implied to save applied options:)

**Comment by iG8R** [comment]
Concerning the video grid issue.

[Tartube-View-partial-issue-Video_2022-12-11_211038.webm](https://user-images.githubusercontent.com/11407417/206924931-81bfd171-0478-44d9-922f-da6d98662180.webm)

**Comment by axcore** [comment]
>Maybe my understanding was wrong but from the very beginning Tartube uses 2 standard types of the downloads: general and classic

Now it is possible to create as many custom downloads as you want. But previously, users could only create two, one for the Videos tab and one for the Classic Mode tab. That's why the custom downloads are named "general" and "classic". I know it's confusing, the problem is on my "to-do" list, but I haven't solved it yet.

The custom download only happens when you select "custom download" in a menu. The "check" and "download" buttons / menu items never start a custom download.

>I've tried to resize the window, except maximizing, but to no avail.

As well as resizing the window, you could try clicking the button "Switch between simple and complex views" button at the top of the window.

Unfortunately I don't see the same problem any more, it is very rare for me. So it is quite difficult to test a solution.

**Comment by iG8R** [comment]
> Now it is possible to create as many custom downloads as you want. But previously, users could only create two, one for the Videos tab and one for the Classic Mode tab. That's why the custom downloads are named "general" and "classic". I know it's confusing, the problem is on my "to-do" list, but I haven't solved it yet.
> 
> The custom download only happens when you select "custom download" in a menu. The "check" and "download" buttons / menu items never start a custom download.

Maybe, it's worth to make the possibility for a user to set whatever download with the settings convenient for them as default? The purpose of any download manager is to download files with settings which are convenient for and meet the user's needs.
Otherwise, it turns out there are 2 buttons in essence with the same functionality only separated because there is no option to use the preferred download as default. And the way the user has to go through to conveniently use the download is long enough (make the "Custom download" button appear, then make the new download, configure it and after these all at the end of the day do not forget to miss the "Custom button" button or use "Custom download" in the context menu), instead of just checking the default box and use the standard download button or the option in the context menu.

**Comment by iG8R** [comment]
> As well as resizing the window, you could try clicking the button "Switch between simple and complex views" button at the top of the window.

Thank you. This approach worked. But why does this issue with the grid appear almost every other time?

**Comment by axcore** [comment]
>Maybe, it's worth to make the possibility for a user to set whatever download with the settings convenient for them as default?

That would be sensible if the user could create only one type of custom download, but the user can create multiple types of custom download. 

>This approach worked. But why does this issue with the grid appear almost every other time?

Because the grid is not a part of the Gtk graphics library, therefore it does not have all the information it needs to create a perfect grid. So, sometimes the grid layout is wrong. I don't see the broken layout very often so it's very difficult to know how the code can be improved.

**Comment by axcore** [comment]
In v2.4.221 I changed the way that custom downloads start, so it is more logical.

In the Videos tab, we used to have two buttons: "Custom download all", and a "+" to choose a custom download.

Now there is only one button. The user is always prompted to choose a custom download, if more than one exists.

**Comment by iG8R** [comment]
> The cause of the problem was this: your channel names are very, very long :)

This is anime/donhua world reality... :)

> Now there is only one button. The user is always prompted to choose a custom download, if more than one exists.

Thank you, I'll try it.

**Comment by axcore** [comment]
I think this issue is finished, but feel free to reopen if necessary.
