### ISSUE TITLE
[Request] CLI argument support 

### ISSUE THREAD

**Issue by iG8R** [axcore/tartube#486]
Hi.
Could you, please, implement the possibility to pass arguments (URL, control arguments for Tartube) from external sources to Tartube via command line, e.g. there is an addon for Firefox called "Open with...", it can pass the URL and whatever arguments a user needs to external applications for opening or for any other actions with it. The process is as follows: the "Open with..." add-on created a link of the following format -` [external app name] [any arguments for this external app] %s`, where `%s` is the page URL or  the URL selected on a page and captured by the add-on.
If Tartube could be able to handle an external call of `"tartube_portable_64bit.bat [URL] [general playlist/channel/video/folder]"` or `"tartube_portable_64bit.bat [URL] [classic]` format, where `general playlist/...` or `classic` are the arguments indicating where passed URL will be processed in Tartube.

**Comment by axcore** [comment]
I have considered adding CLI support many times, but there are many problems:

1. What happens if an instance of Tartube is already running? Two instances of Tartube, running at the same time, cannot load the same database into memory. What happens if the user tries to start ten instances of Tartube using CLI?

2. People will keep asking for more command-line options. So eventually the interface will become extremely complicated, and Tartube's own code will also become much more complicated

3. yt-dlp already has CLI, why not just use that?

**Comment by iG8R** [comment]
>     1. What happens if an instance of Tartube is already running? Two instances of Tartube, running at the same time, cannot load the same database into memory. What happens if the user tries to start ten instances of Tartube using CLI?

Is it possible when already running Tartube intercepts a program call then extracts the arguments and does what those arguments tell it to do?
 
>     2. People will keep asking for more command-line options. So eventually the interface will become extremely complicated, and Tartube's own code will also become much more complicated

Yeah... There is no limit to perfection... :) But people always needs to have in mind that Tartube is a GUI for yt-dlp and only arguments except yt-dlp's itself could be arguments doubling the Tartube functions and nothing else.
Is this too troublesome or/and tedious to match CLI arguments with the existing Tartube functions?

>     3. yt-dlp already has CLI, why not just use that?

The main reason - yt-dlp doesn't give an opportunity for a user dynamically to choose what the destination path to save a file to. With Tartube as the GUI this is way too easy to do it, e.g. in a browser RMB click on a link -> Open with... -> Tartube (where CLI is - `tartube_portable_64bit.bat %s classic` where `%s` is an URL) -> Tartube intercepts it and add passed URL to the "Add URL" textbox, after all this a user begins a work with Tartube. 
And the second reason is that it is convenient to have a database of downloaded videos, the role of which is taken over by Tartube.

**Comment by axcore** [comment]
>Is it possible when already running Tartube intercepts a program call then extracts the arguments and does what those arguments tell it to do?

I researched this, when I was writing code to check that two instances of Tartube are not using the same database. I could not find a way to do it.

Problems #2 and #3 are tricky, but not impossible. But I cannot see a solution for problem #1.

**Comment by iG8R** [comment]
The point of my request was to pass an URL and some commanding arguments from the browser to Tartube to make it more easy to download videos. How it'll be done - it's not so important, some apps use arguments (https://github.com/KurtBestor/Hitomi-Downloader/wiki/Command-Line-Switches), as I described in my request, and I thought it was more easy to implement than how some apps (https://github.com/setvisible/DownZemAll) use special protocols to communicate with the browser.

**Comment by axcore** [comment]
>The point of my request was to pass an URL and some commanding arguments from the browser to Tartube to make it more easy to download videos.

You can drag and drop videos from your browser window into Tartube's window. Unfortunately, drag and drop does not work on MS Windows, but that seems to be a GTK and/or Microsoft problem.

Alternatively, you can enable automatic copy/paste, then in your browser, you can just right-click a video and select "Copy link".
