### ISSUE TITLE
[Request] Button "Switch between views" as a drop-down list of possible views

### ISSUE THREAD

**Issue by iG8R** [axcore/tartube#487]
Hi.
Please, could you make the process of the switching between views less tedious where for now you need to click through almost all possible views to reach the favored one.

**Comment by axcore** [comment]
Yes, I can do that.

**Comment by axcore** [comment]
Added in v2.4.221. In the main menu, clikc **Media > Switch between views**

**Comment by iG8R** [comment]
Thank you so much:)
Is it also possible to make the drop-down list appear when the user clicks the "Switch between simple and complex views" icon on the toolbar?

![image](https://user-images.githubusercontent.com/11407417/211401481-6dcaa7ab-3eda-4b22-8048-a9f35befd312.png)
