### ISSUE TITLE
[Request] More information on the main page during checking and downloading

### ISSUE THREAD

**Issue by iG8R** [axcore/tartube#488]
Hi.
Could you, please, enhance the quality and quantity of the information during checking and downloading process, as for now a user after the start of one of these processes willingly or unwillingly forced to switch to the "Progress" or "Output" tabs to see what's happening after they were began.
E.g. insert thin ribbon-like progress-bar + other info into the downloading video's tile and enhance bottom left progress-bar with the same info + overall progress of the download queue.
![Tartube-progressbar-2022-12-28_203039](https://user-images.githubusercontent.com/11407417/209860524-63f3ebf1-e280-4787-8f45-ffdfe2eb8d31.jpg)

**Comment by iG8R** [comment]
Found how to get download progress data more or less easily:
https://www.reddit.com/r/youtubedl/comments/w5g4yy/print_download_progress_as_json/
Also it would help when it needs to display progress of the download on the Output tab's subtabs.

**Comment by iG8R** [comment]
Some ambiguities in the description of options in the settings.
`Edit `-> `General download options...` -> `Files `-> `Filesystem `-> `Use the server's file modification time` - description says "--no-mtime", but "--no-mtime" on the contrary means '`No use the server's file modification time`'?

**Comment by axcore** [comment]
>and enhance bottom left progress-bar with the same info + overall progress of the download queue.

Absolutely not possible, we do not know the size of each video until yt-dlp starts downloading it, or until the metadata file has been downloaded.

Adding a "thin ribbon-like progress-bar" into each video's tile, as it downloading, would be possible. I can look into that.

**Comment by iG8R** [comment]
> Absolutely not possible, we do not know the size of each video until yt-dlp starts downloading it, or until the metadata file has been downloaded.

What I meant was to see the same information as on the progress tab, without switching to this tab, but in a concise/short form. Because at the moment the information in the bottom left corner is so out of touch with real progress that you have to switch to the Progress tab to see the exact state of things.

 
> Adding a "thin ribbon-like progress-bar" into each video's tile, as it downloading, would be possible. I can look into that.

Is it possible to add also what is displaying in the Progress tab, namely %, Speed, ETA, Size?
 
> Unfortunately only yt-dlp shows progress, FFmpeg does not. So if post-processing takes a long time, the progress bar in each video's tile will not be very useful.

IMHO, any user prefers to see what the program is able to show, and that information that cannot be obtained - it will be enough to show general information, say, "The conversion process is taking place, it may take some time".

**Comment by axcore** [comment]
I just realised, that a video does not appear in the Video tab until it has been downloaded. So adding a progress bar in each video tile will be pointless, because no-one will ever see it.

About adding more information in the bottom-left corner of the Videos tab, I don't know how more information can be added in such a small area.

**Comment by axcore** [comment]
>Some ambiguities in the description of options in the settings.
Thanks, I have fixed that.

**Comment by iG8R** [comment]
> I just realised, that a video does not appear in the Video tab until it has been downloaded. So adding a progress bar in each video tile will be pointless, because no-one will ever see it.

Sorry, but I can't reproduce what did you mean. In my case a tile always appears or could you describe the algorithm how could I replicate what did you mention above.
Any way, even if a tile currently doesn't appear, could you, please, make it show up every time a user downloads corresponding video and, respectively, the info on this tile?

> About adding more information in the bottom-left corner of the Videos tab, I don't know how more information can be added in such a small area.

Maybe it is worth to add info next (below) to each playlist/channel/folder/video that is at the moment being checked or downloaded and in the bottom-left corner add only total info?

For example, currently infos in the bottom-left corner and on the Progress tab doesn't correlate at all except in the bottom-left corner shows how many playlists are in the process now.

![Tartube-Info-Combined-2023-01-08_172244-2](https://user-images.githubusercontent.com/11407417/211205079-fed37433-7230-436c-b62d-5d3dede95f8e.jpg)

**Comment by axcore** [comment]
>Sorry, but I can't reproduce what did you mean. In my case a tile always appears or could you describe the algorithm how could I replicate what did you mention above.

1. Add a new channel
2. Don't check the channel, just download it
3. Videos are not visible in the **Videos** tab until they are downloaded

>Any way, even if a tile currently doesn't appear, could you, please, make it show up every time a user downloads corresponding video

It is impossible. When yt-dlp is downloading a video, it provides incomplete information. Check for yourself the **Output** tab. If every line contained unique information, such as the video ID, then it would be easy. But most lines do not contain that information, so it is impossible.

>Maybe it is worth to add info next (below) to each playlist/channel/folder/video that is at the moment being checked or downloaded

There is not enough space next to the playlist/channel/folder name. The user will have to increase the width of the list. So, on the right side, there will be enough space for only one column of videos.

The information could be added beneath the playlist/channel/folder name, but then the names will be constantly moving up and down, and the user will not be able to click on them.

Also Gtk treeviews are very buggy, and there is a big danger that constantly updating the list of channels/playlists/folders will cause crashes.

**Comment by iG8R** [comment]
>     1. Add a new channel
>     2. Don't check the channel, just download it
>     3. Videos are not visible in the **Videos** tab until they are downloaded

Now I understand. The fact is that I always check before downloading to see what the content of the playlist is.
What is the difference between "checking" (when tiles appear in real-time as the playlist is checked) and "downloading" (when tiles appear as the playlist is downloaded) regarding the display of tiles?

**"Checking"**
```
yt-dlp --newline -i --abort-on-unavailable-fragment --hls-prefer-native --write-description --cookies H:/TarTube(Downloader)/cookies.txt --write-thumbnail --concurrent-fragments 3 --windows-filenames --output H:/TarTube(Downloader)/Становление богом Checking/%(title)s.%(ext)s -vU --dump-json https://vk.com/video/playlist/-179915138_101
[debug] Command-line config: ['--newline', '-i', '--abort-on-unavailable-fragment', '--hls-prefer-native', '--write-description', '--cookies', 'H:/TarTube(Downloader)/cookies.txt', '--write-thumbnail', '--concurrent-fragments', '3', '--windows-filenames', '--output', 'H:/TarTube(Downloader)/Становление богом Checking/%(title)s.%(ext)s', '-vU', '--dump-json', 'https://vk.com/video/playlist/-179915138_101']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.11.11 [8b64402] (pip)
[debug] Python 3.10.8 (CPython AMD64 64bit) - Windows-10-10.0.19043-SP0 (OpenSSL 1.1.1s  1 Nov 2022)
[debug] Optional libraries: Crypto-3.15.0, certifi-2022.09.24, sqlite3-2.6.0
[debug] exe versions: ffmpeg 4.4.3 (setts), ffprobe 4.4.3, rtmpdump 2.4
[debug] Proxy map: ()
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Loaded 1723 extractors
Latest version: 2023.01.06, Current version: 2022.11.11
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2023.01.06/_update_spec
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[debug] [vk:uservideos] Extracting URL: https://vk.com/video/playlist/-179915138_101
[vk:uservideos] -179915138_101: Downloading webpage
[download] Downloading playlist: Становление богом
[vk:uservideos] -179915138: Downloading JSON metadata
[debug] [vk] Extracting URL: http://vk.com/video-179915138_456244773
[download] Downloading video 1 of 11
[vk:uservideos] Playlist Становление богом: Downloading 11 videos of 11
[vk] -179915138_456244773: Downloading JSON metadata
[vk] -179915138_456244773: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] -179915138_456244773: Downloading 1 format(s): hls-4665
[Становление богом Checking] <Simulated download of: 'Становление богом  - 11 серия'>
[debug] [vk] Extracting URL: http://vk.com/video-179915138_456244741
[download] Downloading video 2 of 11
[vk] -179915138_456244741: Downloading JSON metadata
[vk] -179915138_456244741: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] -179915138_456244741: Downloading 1 format(s): hls-4625
[Становление богом Checking] <Simulated download of: 'Становление богом  - 10 серия'>
```


**"Downloading"**
```
yt-dlp --newline -i --abort-on-unavailable-fragment --hls-prefer-native --write-description --cookies H:/TarTube(Downloader)/cookies.txt --write-thumbnail --concurrent-fragments 3 --windows-filenames --output H:/TarTube(Downloader)/Становление богом Downloading/%(title)s.%(ext)s -vU https://vk.com/video/playlist/-179915138_101
[debug] Command-line config: ['--newline', '-i', '--abort-on-unavailable-fragment', '--hls-prefer-native', '--write-description', '--cookies', 'H:/TarTube(Downloader)/cookies.txt', '--write-thumbnail', '--concurrent-fragments', '3', '--windows-filenames', '--output', 'H:/TarTube(Downloader)/Становление богом Downloading/%(title)s.%(ext)s', '-vU', 'https://vk.com/video/playlist/-179915138_101']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.11.11 [8b64402] (pip)
[debug] Python 3.10.8 (CPython AMD64 64bit) - Windows-10-10.0.19043-SP0 (OpenSSL 1.1.1s  1 Nov 2022)
[debug] Optional libraries: Crypto-3.15.0, certifi-2022.09.24, sqlite3-2.6.0
[debug] exe versions: ffmpeg 4.4.3 (setts), ffprobe 4.4.3, rtmpdump 2.4
[debug] Proxy map: ()
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Loaded 1723 extractors
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2023.01.06/_update_spec
Latest version: 2023.01.06, Current version: 2022.11.11
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[debug] [vk:uservideos] Extracting URL: https://vk.com/video/playlist/-179915138_101
[vk:uservideos] -179915138_101: Downloading webpage
[download] Downloading playlist: Становление богом
[vk:uservideos] -179915138: Downloading JSON metadata
WARNING: There's no playlist description to write
[debug] [vk] Extracting URL: http://vk.com/video-179915138_456244773
[download] Downloading video 1 of 11
[vk:uservideos] Playlist Становление богом: Downloading 11 videos of 11
[vk] -179915138_456244773: Downloading JSON metadata
[vk] -179915138_456244773: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] -179915138_456244773: Downloading 1 format(s): hls-4665
WARNING: There's no video description to write
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: H:/TarTube(Downloader)/Становление богом Downloading/Становление богом  - 11 серия.jpg
[debug] Invoking hlsnative downloader on "https://vkvd182.mycdn.me/expires/1673556970207/srcIp/104.28.224.95/pr/40/srcAg/CHROME/ms/185.226.52.187/type/5/sig/W1qbuVhMzPo/ct/8/urls/45.136.22.177/clientType/13/zs/43/id/3598403766928/video/"
[hlsnative] Downloading m3u8 manifest
[debug] File locking is not supported. Proceeding without locking
[download] Destination: H:/TarTube(Downloader)/Становление богом Downloading/Становление богом  - 11 серия.mp4
[hlsnative] Total fragments: 75
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
[download] 100% of  414.26MiB in 00:01:05 at 6.36MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:H:/TarTube(Downloader)/Становление богом Downloading/Становление богом  - 11 серия.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:H:/TarTube(Downloader)/Становление богом Downloading/Становление богом  - 11 серия.mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:H:/TarTube(Downloader)/Становление богом Downloading/Становление богом  - 11 серия.temp.mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "H:/TarTube(Downloader)/Становление богом Downloading/Становление богом  - 11 серия.mp4"
[debug] [vk] Extracting URL: http://vk.com/video-179915138_456244741
[download] Downloading video 2 of 11
[vk] -179915138_456244741: Downloading JSON metadata
[vk] -179915138_456244741: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] -179915138_456244741: Downloading 1 format(s): hls-4625
WARNING: There's no video description to write
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: H:/TarTube(Downloader)/Становление богом Downloading/Становление богом  - 10 серия.jpg
[debug] Invoking hlsnative downloader on "https://vkvd241.mycdn.me/expires/1673557038603/srcIp/104.28.224.95/pr/40/srcAg/CHROME/ms/45.136.20.154/type/5/sig/pK39vpQp9uQ/ct/8/urls/45.136.22.207/clientType/13/zs/43/id/3348895631908/video/"
[hlsnative] Downloading m3u8 manifest
[download] Destination: H:/TarTube(Downloader)/Становление богом Downloading/Становление богом  - 10 серия.mp4
[hlsnative] Total fragments: 70
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
```

![Tartube-Chech-Download-Tiles-2023-01-09_231021](https://user-images.githubusercontent.com/11407417/211409519-7dc990f5-11ca-48c7-afbb-6ca393208664.jpg)

Why not add a command from the checking process, after which the tile appears, to insert real-time information about the downloading process into the tile?
In the aforementioned logs this command is:
`[Становление богом Checking] <Simulated download of: 'Становление богом  - 11 серия'>`

**Comment by iG8R** [comment]
> It is impossible. When yt-dlp is downloading a video, it provides incomplete information. Check for yourself the **Output** tab. If every line contained unique information, such as the video ID, then it would be easy. But most lines do not contain that information, so it is impossible.

Is it possible to use this argument: `--progress-template "%(progress)j"` from https://www.reddit.com/r/youtubedl/comments/w5g4yy/print_download_progress_as_json/ to get all needed information?

**Comment by iG8R** [comment]
> There is not enough space next to the playlist/channel/folder name. The user will have to increase the width of the list. So, on the right side, there will be enough space for only one column of videos.
> The information could be added beneath the playlist/channel/folder name, but then the names will be constantly moving up and down, and the user will not be able to click on them.
> Also Gtk treeviews are very buggy, and there is a big danger that constantly updating the list of channels/playlists/folders will cause crashes.

I meant exactly adding information beneath the name of the playlist/channel/folder name.
Is it possible to adjust the height of the playlist entry from the beginning so that it doesn't bob up and down when adding information at the bottom of this entry?
I realize this is going to be a weird suggestion, but if Gtk treeviews are so buggy, why not consider replacing it with something more stable?

**Comment by axcore** [comment]
>What is the difference between "checking" (when tiles appear in real-time as the playlist is checked) and "downloading" (when tiles appear as the playlist is downloaded) regarding the display of tiles?

When checking, yt-dlp is in simulation mode. Tartube receives exactly one message per video, and the message is easy to capture, so the tile grid is updated automatically. 

In real downloads, Tartube receives dozens or hundreds of messages for each video, and most of them are not easy to capture. That's why we have to wait for the "Video has been downloaded" message before updating the database (and displaying the video in the tile grid).

**Comment by axcore** [comment]
`--progress-template` might be a solution, I will look into it when I have some time.

**Comment by axcore** [comment]
>I realize this is going to be a weird suggestion, but if Gtk treeviews are so buggy, why not consider replacing it with something more stable?

Gtk treeviews are not the problem, the problem is Gtk. We have been waiting for a stable release of Gtk for about 20 years, maybe one will appear tomorrow :)

**Comment by axcore** [comment]
I have added this feature request, and also https://github.com/axcore/tartube/issues/486, to my "to-do" list. I don't have time to implement them both at the moment, but it would be fun to tackle the problems later, when I can find the time to do it.
