### ISSUE TITLE
Why aren't subtitles downloading

### ISSUE THREAD

**Issue by DraconicNEO** [axcore/tartube#489]
Hello I'm wondering why the subtitles don't download when I try to download the video, I have the download all availible subtitles option checked in settings but the subs still don't download with the video. Is there something I'm doing wrong or does subtitle downloading just not work right?

If it helps I'm using classic mode.

(Also I did make sure the video has subtitles and not just automatic ones).

**Comment by axcore** [comment]
Please test this by downloading a single video with subtitles.

Then open Tartube's **Output** tab, and show me a screenshot of the yellow text at the top (or just copy/paste the yellow text here).

**Comment by DraconicNEO** [comment]
> Please test this by downloading a single video with subtitles.
> 
> Then open Tartube's **Output** tab, and show me a screenshot of the yellow text at the top (or just copy/paste the yellow text here).

Okay, here it is
```
/home/draconic/.local/bin/youtube-dl --newline -i --hls-prefer-native --cookies /home/draconic/tartube-data/cookies.txt -f bestvideo[height<=?1080]+bestaudio/best[height<=?1080] --recode-video mp4 --output /home/draconic/Videos/YoutubeDL/%(title)s.%(ext)s --ffmpeg-location /usr/bin/ffmpeg https://www.youtube.com/watch?v=2DGqVbTHX-k
```

**Comment by axcore** [comment]
This yt-dlp command does not contain any references to subtitles, which is why they are not downloaded.

There are different sets of download options are used in different circumstances. For example, click **Edit > General download options** for the download options usedwhen you click the **Download all** button in the **Videos** tab. 

If you are downloading in the Classic Mode tab, then click the menu button in the top-right corner and select **Edit download options**.

When you've located the correct set of download options, you can check whether subtitles have been enabled in them.

If that does not help, click **Edit > System preferences > Options > Download options**, and show me a screenshot of that tab.

**Comment by DraconicNEO** [comment]
> This yt-dlp command does not contain any references to subtitles, which is why they are not downloaded.
> 
> There are different sets of download options are used in different circumstances. For example, click **Edit > General download options** for the download options usedwhen you click the **Download all** button in the **Videos** tab.
> 
> If you are downloading in the Classic Mode tab, then click the menu button in the top-right corner and select **Edit download options**.
> 
> When you've located the correct set of download options, you can check whether subtitles have been enabled in them.
> 
> If that does not help, click **Edit > System preferences > Options > Download options**, and show me a screenshot of that tab.
> 
> There is a gentle introduction to download options in Tartube's [README](https://github.com/axcore/tartube#download-options), the next release will have an inline tutorial as well.

I did enable the download all option though it didn't work, also I'm using youtube-dl not yt-dlp (couldn't get that one to save as mp4 at all). 

Screenshot of download options
![image](https://user-images.githubusercontent.com/44508470/211082661-0ad4f962-ae53-4677-868b-1a9872aa3a54.png)

**Comment by axcore** [comment]
Right, so you are using the Classic Mode tab. In that tab, you have clicked the button in the top-right corner,  and selected **Edit download options**. When the window opens, the box **Name for these download options** is **classic**. In the window's **Subtitles** tab, you have selected **Download all available subtitle files**.

![classic1](https://user-images.githubusercontent.com/37951926/211135081-c0373ab5-6242-4e6b-8663-27170dff74d6.png)

![classic2](https://user-images.githubusercontent.com/37951926/211135086-0d2bd669-408b-440b-b216-ee457a3e86be.png)

If you have followed those steps exactly, then I can't explain why subtitles are not being downloaded.

**Comment by axcore** [comment]
>I did enable the download all option though it didn't work, also I'm using youtube-dl not yt-dlp (couldn't get that one to save as mp4 at all).

youtube-dl has been abandoned for so long that it cannot be recommended for any type of downloads. I can't say why yt-dlp won't save videos as MP4s, but you could try removing the `--ffmpeg-location /usr/bin/ffmpeg` option. (If FFmpeg has been installed there, it really should not be necessary to tell yt-dlp how to find it.)

**Comment by DraconicNEO** [comment]
> > I did enable the download all option though it didn't work, also I'm using youtube-dl not yt-dlp (couldn't get that one to save as mp4 at all).
> 
> youtube-dl has been abandoned for so long that it cannot be recommended for any type of download. I can't say why yt-dlp won't save videos as MP4s, but you could try removing the `--ffmpeg-location /usr/bin/ffmpeg` option. (If FFmpeg has been installed there, it really should not be necessary to tell yt-dlp how to find it.)

I think that worked, it actually finished converting when I removed the ffmpeg path from the settings. Kind of wish there was some kind of indication of conversion process but I guess that can't be helped
