### ISSUE TITLE
AtomicParsley

### ISSUE THREAD

**Issue by Veronna** [axcore/tartube#49]
`ERROR: AtomicParsley was not found. Please install.`

Im on Windows and it looks like AtomicParsley isnt integrated with tartube, so im wondering how/where i can add AtomicParsley to make it working within Windows, so i can at thumbnail for mp4 files.

With Youtube-dl Gui i can just place the exe in the root folder of the programm, but the folder structure of Tarttube is more complicated.

**Comment by axcore** [comment]
Hi Veronna. How did you generate this error?

**Comment by Veronna** [comment]
Basically getting it after a download is done, in the output window, on of the thread tabs.

I guess turning the option "Embed thumbnail in audio file as cover art" or "Write Metadata to the video file" under Post-processing options requires AtomicParsley for it to work, if the downloaded files are of the  .mp4 type.

**Comment by axcore** [comment]
I have tested this. The [pull request](https://github.com/axcore/tartube/pull/42) suggests the AtomicParsley binary can be added directly to 

**C:\\Users\\YOURNAME\\AppData\\Local\\Tartube\\msys64\\mingw64\\bin**

I did the following steps:
1. Added the binary to the folder, as above
2. In Tartube, opened the options window ( Edit > General download options... > General )
3. Clicked the **Show advanced download options** button
4. Clicked the **Post-processing** tab
5. Clicked the following boxes to select them:
Post-process video files to convert them to audio-only files
Keep video file after post-processing it
Embed thumbnail in audio file as cover art
Write metadata to the video file
6. Clicked the OK button to close the window

Then I downloaded some videos. When the AtomicParsley binary is present, I no longer see the error

`ERROR: AtomicParsley was not found. Please install`

If the binary is not present, then I do see the error.

However, it does not seem to work. The audio files do not seem to have the thumbnail embedded in them.

Have you had different results? If it can be made to work, I can add AtomicParsley to the MS Windows installer.

**Comment by Veronna** [comment]
From what i gather so far with testing different fileformats/containers only
mp3/m4a for audio files and
mp4 for video files are probably getting thumbnail embedded.

Which is fine for the most part, i just wish mkv containers would work aswell.

**Comment by ceonelson** [comment]
It embedded the thumbnail for me doing audio-only download into a m4a.  

I didn't install Tartube under users myself but I put the full path in there for the people who weren't sure where it was installed by default (but having the installer auto-add it would definitely be best).

**Comment by axcore** [comment]
Opening a new issue as the [previous one](https://github.com/axcore/tartube/issues/49) seems to have vanished.

I tested Tartube v1.3.077 on Windows 7. 

I installed Tartube. Then I added the AtomicParsley binary to both of these folders

```
C:\Users\MYNAME\AppData\Local\Tartube\msys64\mingw64\bin
C:\Users\MYNAME\AppData\Local\Tartube\msys64\usr\bin
```

I started Tartube, and from its menu, I installed youtube-dl and ffmpeg.

I opened the download options window (Edit > General download options...), and set these options.

![options1](https://user-images.githubusercontent.com/37951926/73210268-cf034880-4141-11ea-8e0d-4241d7f40c3e.png)

Then I downloaded [this obscure music video](https://www.youtube.com/watch?v=CS9OO0S5w2k). The video was downloaded, and a separate .mp3 file was created, but it did not have an embedded thumbnail (as far as I can tell).

**Comment by axcore** [comment]
Oh! The procedure above works for .m4a, but not for .mp3.

I tried setting the audio format to .wav, and received the error message `ERROR: Only mp3 and m4a/mp4 are supported for thumbnail embedding for now.`

I'm not sure why one works and not the other, but in any case, I will include atomicparsley with the next MS Windows installer.

**Comment by axcore** [comment]
The MS windows installer for v1.4.0 now includes AtomicParsley, installed in the right place.
