### ISSUE TITLE
Download Speed, ETA and Size no longer update/show.

### ISSUE THREAD

**Issue by TheMadog24** [axcore/tartube#490]
Information:

> What operating system are you using?

Windows 11

> What version of Tartube are you using?

v2.4.165

> What do you see in the Errors/Warnings tab?

N/A

### Issue:

I'm downloading video from twitch, and this feature used to work/show/update about 1-2 months ago.
It stopped working randomly, not after an update. I have since updated Tartube, but that did not make it start working.

![image](https://user-images.githubusercontent.com/12008758/210604325-4420f112-a5d3-4777-b796-81394b319177.png)
![image](https://user-images.githubusercontent.com/12008758/210604984-14b4d263-fb30-49c7-a81a-cd1b311d555d.png)

I don't remember what version I was on when it stopped working, but I do remember confirming that the tartube version was the same before and after the issue appeared. I'm not sure if it's maybe a twitch issue, or not.

**Comment by axcore** [comment]
I recently fixed a similar issue (perhaps the same issue), but the new code is only uploaded to Github at the moment. The fix will be in the next main release.

If you can't wait that long, it is quite simple to update your installation by downloading the source code from here on Github, and copying into the right folder, replacing the old source code. The process is described [here](https://github.com/axcore/tartube#71-tartube-wont-installwont-rundoesnt-work).

**Comment by TheMadog24** [comment]
> I recently fixed a similar issue (perhaps the same issue), but the new code is only uploaded to Github at the moment. The fix will be in the next main release.

Well, I would like to say that it fixed the issue, they do appear again.

![image](https://user-images.githubusercontent.com/12008758/211178695-9a31d077-6356-47da-ae7d-634d2a29b687.png)

But the Speed and time fluctuate WILDLY, all the way from 1.XXKiB/s to 100.XXMiB/s.
The time as well, anywhere from 24 Seconds to 8 hours. Although, once the download gets to about 40% or so completed, the time become accurate. but, at least I can see the total size and _somewhat_ accurate time.

**Comment by axcore** [comment]
It's the same for everyone, probably yt-dlp has switched from an average speed to an actual second-by-second speed. You see exactly the same swings in a torrent client.

**Comment by TheMadog24** [comment]
Ah, alright, thank you.

**Comment by axcore** [comment]
This was added to the full installer for v2.4.221.
