### ISSUE TITLE
Tartube won't open on Windows 11

### ISSUE THREAD

**Issue by ScathachSkadi** [axcore/tartube#491]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Windows 11

### What version of Tartube are you using?
tartube-with-ffmpeg-2.4.165-64bit.exe

### What do you see in the Errors/Warnings tab?
When I install Tartube for the first time it opens a terminal windows for a brief second and it doesn't launch. Reinstalling has the same issue. This bug was there on the July version, but I decided to give it a go again and it still doesn't work. Trying to launch it from the terminal shows this error:

$ python3 tartube/tartube
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'C:\Users\\uac15\AppData\Local\Tartube\msys64\mingw64\bin\python3.exe'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:/Users/\uac15/AppData/Local/Tartube/msys64/mingw64/bin/python3.exe'
  sys.base_prefix = 'D:/a/msys64/mingw64'
  sys.base_exec_prefix = 'D:/a/msys64/mingw64'
  sys.platlibdir = 'lib'
  sys.executable = 'C:/Users/\uac15/AppData/Local/Tartube/msys64/mingw64/bin/python3.exe'
  sys.prefix = 'D:/a/msys64/mingw64'
  sys.exec_prefix = 'D:/a/msys64/mingw64'
  sys.path = [
    'D:/a/msys64/mingw64/lib/python310.zip',
    'D:/a/msys64/mingw64/lib/python3.10',
    'D:/a/msys64/mingw64/lib/lib-dynload',
    '',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00000774 (most recent call first):
  <no Python frame>

Do I need to install Python3 or something?

**Comment by axcore** [comment]
Sorry, I don't have a Windows 11 installation so I can't test your problem. I don't know how to resolve your issue, although it looks like a conflict between python virtual environments.

>Do I need to install Python3 or something?

The installers tartube-2.4.165-64bit.exe and tartube-with-ffmpeg-2.4.165-64bit.exe both contain a full installation of Python3, but that was done on a Windows 10 box.

If you feel like a challenge, you could _try_ creating your own installer. The installer script can be found _here_, and it includes step-by-step instructions of how to do that.

**Comment by axcore** [comment]
You can try this:

Find the file `C:/Users/\uac15/AppData/Local/Tartube/msys64/home/user/tartube/tartube_mswin.sh` and open it in a suitable text editor

Change this line

GTK_OVERLAY_SCROLLING=0 python tartube/tartube

To this (adding the .exe)

GTK_OVERLAY_SCROLLING=0 python.exe tartube/tartube

**Comment by ScathachSkadi** [comment]
@axcore adding .exe didn't work. I want to try making my own installer... where can I find it?

**Comment by axcore** [comment]
Oops, I tried adding the link above, but it didn't work.

The installer script is [here](https://github.com/axcore/tartube/blob/master/nsis/tartube_install_64bit.nsi). Instructions are in the script itself, just open a text editor.

**Comment by axcore** [comment]
Closed for inactivity.

**Comment by ScathachSkadi** [comment]
It seems like it doesn't work if you have a non-english username for Windows. I redirected it to C: and it works now. %appdata% has a non english directory.

**Comment by ScathachSkadi** [comment]
The app didn't open with the recommended installation directory and it was because my pc didn't have an english username. I redirected the installation directory to the C Drive which doesn't have any non-english directories and it works now. Tested on multiple devices.

**Comment by axcore** [comment]
It could be related to [this unresolved issue](https://github.com/axcore/tartube/issues/320), in which Tartube is unable to read characters in some languages. You could check this for yourself by downloading a video, then looking at the contents of the Output tab; if the path to the downloaded folder is garbled, then that's the problem.
