### ISSUE TITLE
Hardware acceleration possible?

### ISSUE THREAD

**Issue by lordCuppa** [axcore/tartube#492]
Hello!
First, thank you for such a great piece of work, but there is one big thing for me missing.
I was looking up if it is possible to enable `hardware acceleration` and found an older, closed, question from oshura3.
There you showed, wrote: "All added in v2.3.110".
At the moment I'm using the version v2.4.165 and was wondering if you removed the option at all, or if I just haven't found it yet.

Thx in advance.

**Comment by Fijxu** [comment]
It's here.
![](https://i.ayaya.beauty/CEWVhzbn.png)

You need to enable advanced options

![](https://i.ayaya.beauty/oWzWfNGB.png)

**Comment by axcore** [comment]
Thanks @Fijxu for beating me to it :)

To clarify: FFmpeg options are explained [here](https://github.com/axcore/tartube#6262-using-ffmpeg-directly). They are used when FFmpeg processes a video you've already downloaded (for example, when you right-click the video in Tartube's Videos tab, and then select **Special > Process with FFmpeg...**). They are not used when youtube-dl starts its own instance of FFmpeg.

**Comment by lordCuppa** [comment]
Thank you for your fast help.
