### ISSUE TITLE
windows 7

### ISSUE THREAD

**Issue by harryray33** [axcore/tartube#493]
Does Tartube run with Windows 7?

Thanks.

**Comment by harryray33** [comment]
Thanks, I tried the link but the page has been removed.

**Comment by harryray33** [comment]
I've gone back to 2.4.093, none seem to work with Win 7. Something to do with msys2.org, according to error message.

**Comment by axcore** [comment]
This link? I think it's still live, it's just section 17.1 of the README for Tartube.

If you show me the actual error message then I can give you a better idea of what it means.

**Comment by axcore** [comment]
Closed for inactivity.
