### ISSUE TITLE
Desktop file incorrectly uses the Version key

### ISSUE THREAD

**Issue by parona-source** [axcore/tartube#496]
### What operating system are you using?
Gentoo Linux

### What version of Tartube are you using?
2.4.221

This isn't a runtime issue but id count it as a bug as question nor feature request dont match this.   

The desktop file doesn't conform to the freedesktop spec. The Version key isnt supposed to convey the application version but the used spec version.

https://github.com/axcore/tartube/blob/master/pack/tartube.desktop#L3

The key should either be corrected to the spec used (1.5) or it could be easily omitted completely as its not required.

You may find the more information on the spec here:
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys

**Comment by axcore** [comment]
Thanks a lot, I have updated the file to use 1.5. It will be in the next release.
