### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by BlueBull010** [axcore/tartube#497]
Hi there

I have a simple question: do you accept donations somewhere? Most OSS devs have a "donate" button somewhere on their page but I can't seem to find one in your case. I would like to donate a small, token amount to show my gratitude. Tartube is an incredible piece of software, I do not understand why it is not as well-known as other youtube-dl/yt-dlp GUI's that are much, muuuuuch more crude and limited than this piece of awesomeness. I have tried handfuls of other tools, likely all of the most well-known ones, and tartube is by far, by very, very, veeery far the best one, nothing even comes close except the original CLI tools

So, could you provide a method for donations? Simply a paypal would already be okay but I guesstimate that there would be more people that want to donate if there was a button somewhere

Cheers and thanks for all the work you've done, this must have been a crazy amount of work to develop, considering all the options it has

Take care

**Comment by axcore** [comment]
Don't let your conscience trouble you. There is no donation button, Tartube is free for everyone to enjoy :)
