### ISSUE TITLE
Filter Errors/Warnings

### ISSUE THREAD

**Issue by mbnoimi** [axcore/tartube#50]
Hi,

I suggest to add two checkboxes in `Errors/Warnings` for filtering warnings/errors

**Comment by axcore** [comment]
Added in v1.3.077.

**Comment by mbnoimi** [comment]
Thanks @axcore I can see the new checkboxes but they filter nothing!
![Peek 2020-01-26 22-13](https://user-images.githubusercontent.com/284547/73140368-30b3ac00-4089-11ea-9b19-06e67d873684.gif)

**Comment by axcore** [comment]
Fixed in v1.3.086. I had forgotten, that Tartube errors and YouTube errors are handled by different functions.
