### ISSUE TITLE
Download destination is stuck

### ISSUE THREAD

**Issue by mcrsquared2** [axcore/tartube#500]
I realize this is a basic question, but I'm trying to change external hard drives for this project. I must be changing the download destination in the wrong spot, because it says "You only have 0 / 0 GB remaining on your device."

I'm sure the answer is obvious, but what am I missing?

Thanks!

----

Thanks for taking the time to ask a question! 

### Please read the README
Perhaps your question is answered there

### The authors are not experts in python, security, youtube-dl, FFmpeg, Debian/RPM packaging or Windows programming
You are welcome to ask a Tartube-related question, but you might get a better answer in forums where those kinds of expert can be found

**Comment by axcore** [comment]
The available disc space is obtained using Python's standard [shutil](url) library. I can't say why your external drive is reporting zero disk space, but you can try disabling the warnings. Click **Edit > System preferences > Files > Device**, and un-select the buttons **Before checking/downloading videos, warn user if disk space is less than** and **Halt downloads if disk space is less than**

**Comment by axcore** [comment]
Closed for inactivity.
