### ISSUE TITLE
SMG4 Channel downloads on database glitch out, but other Channels dont

### ISSUE THREAD

**Issue by ShieBuns** [axcore/tartube#501]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
If using MS Windows, are you using Windows 10, Windows 7, or something else?

Windows 10

### What version of Tartube are you using?
In Tartube's main window, click Help > About

v2.4.221

### What happens when you run Tartube from a terminal window?
Many error messages are only visible in the terminal window. On MS Windows, this is how to do it:

- First, enable hidden folders on your system
- Then, run the application: 

    C:\Users\YOURNAME\AppData\Local\Tartube\msys64\mingw64.exe

- In this new window, type these commands to start Tartube:

    cd /home/user/tartube

    python3 tartube/tartube

No error when running Tartube to open it, but putting a video from SMG4 into the database makes these warnings -

G:/Disk Virtual Home/Downloads Directory/tartube/mingw64/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'strikethrough-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
G:/Disk Virtual Home/Downloads Directory/tartube/mingw64/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'underline-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
G:/Disk Virtual Home/Downloads Directory/tartube/mingw64/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'weight-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
G:/Disk Virtual Home/Downloads Directory/tartube/mingw64/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'style-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)

###If your bug report is "I can't download this video", please provide a link to the video
This will save a lot of time!

https://www.youtube.com/watch?v=4kCCV1MOpxs
https://www.youtube.com/watch?v=zITYPlNkAAk

it does download the video, but the database doesnt recognize it and displays this

![python3_asuq8xEzb7](https://user-images.githubusercontent.com/123888417/215392207-790af3ad-b027-448b-898d-d2c440794528.png)
![python3_m7IwMqrGQi](https://user-images.githubusercontent.com/123888417/215391976-11c2e940-d9ff-4110-bc4d-252e699b0235.png)
4.png)

videos from other channels (RTGame and PhoenixSC in image) work and display properly

thumbnails also dont show up when downloaded in a channel folder

help would be appreciated thanks 👍

**Comment by axcore** [comment]
I tested both of those videos, using a fresh installation of Tartube, and they both downloaded without problems:

![cleaninstall](https://user-images.githubusercontent.com/37951926/215776816-dcb9ba60-4dd0-4ebc-82e7-54c4891884cc.png)

>thumbnails also dont show up when downloaded in a channel folder

This suggests you have not installed FFmpeg, which would also explain why some videos download but others don't.

Make sure you have installed FFmpeg from Tartube's menu. Also try uninstalling Tartube completely from your system, including removing Tartube's installation folder, then re-install Tartube, yt-dlp and FFmpeg.

**Comment by ShieBuns** [comment]
just to be sure, which one did you install from here?
![image](https://user-images.githubusercontent.com/123888417/215916658-bdd8289e-a2e8-46b1-9bff-7e6a540a533f.png)

is there anything else i need to check to see if tartube has been completely removed?

even after deleting the installation folder of tartube and installing the "install tartube with ffmpeg" instead of "tartube 64 bit portable" this still happens

First Image is installing ffmpeg the menu ( how do i set path instead? )
Second Image is the same video downloaded

![python3_4cftcJxr8K](https://user-images.githubusercontent.com/123888417/215917222-2da75e5d-a6c2-41ae-8823-b40dd53fd0f8.png)
![python3_u9I5YkiZBD](https://user-images.githubusercontent.com/123888417/215917234-ef72e563-5bfa-4af8-b073-fd75d2c5b4f2.png)

**Comment by axcore** [comment]
>just to be sure, which one did you install from here?

There are three packages for MS Windows, they all install an identical set of files. Only the "with FFmpeg" uses different files, but these new files are the same files you would receive if you install FFmpeg from Tartube's menu.

>is there anything else i need to check to see if tartube has been completely removed?

If you are sure that FFmpeg is installed correctly, the next step is to try downloading the video, then show me a screenshot of the Output tab, with the yellow text at the top visible.

**Comment by ShieBuns** [comment]
![image](https://user-images.githubusercontent.com/123888417/216282688-1ad58cf6-d0c0-4f49-9825-98ea6562eae2.png)
