### ISSUE TITLE
channel downloaded, unable to delete

### ISSUE THREAD

**Issue by ilvinc3nt** [axcore/tartube#502]
Unable to remove from left side the channel and all videoes it contains. right click over the channel show me the windows with the delete option, but nothing happens when i click it

Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
I'm using manjaro

### What version of Tartube are you using?
Tartube 2.4.226 (compiled from repository)

### What happens when you run Tartube from a terminal window?
/usr/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'strikethrough-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
/usr/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'underline-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
/usr/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'weight-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
/usr/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'style-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)

(tartube:15265): Gdk-CRITICAL **: 17:27:02.377: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Are you SURE you want to delete files? This procedure cannot be reversed!

###If your bug report is "I can't download this video", please provide a link to the video

**Comment by axcore** [comment]
It is likely that you've enabled debug mode. From Tartube's menu, click **Edit > System preferences > Windows > Dialogues**, and unselect the button marked **Temporarily disable message dialogue windows**.
