### ISSUE TITLE
Does downloading this link work?

### ISSUE THREAD

**Issue by ScoobyDoo2021** [axcore/tartube#503]
Trying to download below video. This is a VOD from a Korean streaming website (like Twitch). The video below is marked as 19+ due to the streamer seen smoking a cigarette.

https://vod.afreecatv.com/player/97566851

In the past, I would save the latest cookies file from the website and be able to download such videos. But today, I tried and it is not working. 
Wondering if it's due to the streaming site circumventing downloading or if I am missing something settings in Tartube?

Tried downloading after reinstalling latest Tartube:
Output:
yt-dlp --newline -i --hls-prefer-native --write-description --write-info-json --cookies C:\Users\AMD\Downloads\Tartube\cookies.txt --write-thumbnail --windows-filenames --output C:/Users/AMD/Downloads/Tartube/Unsorted Videos/%(title)s.%(ext)s https://vod.afreecatv.com/player/97566851
[afreecatv] 97566851: Downloading webpage
[afreecatv] Extracting URL: https://vod.afreecatv.com/player/97566851
ERROR: [afreecatv] 97566851: Unable to extract station; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

(Have updated the yt-dlp before trying)
![2023-02-04_11h13_25](https://user-images.githubusercontent.com/77477008/216733709-1fee5de0-bf6b-4b5b-bae9-8dac3dcb8c1b.png)

**Comment by axcore** [comment]
The video can't be downloaded by yt-dlp, with or without Tartube, so you should try reporting it at the [yt-dlp issue page](https://github.com/yt-dlp/yt-dlp/issues).

There's not much I can do to help you because I don't contribute to the yt-dlp codebase.
