### ISSUE TITLE
Suddenly I'm missing this download information

### ISSUE THREAD

**Issue by WWiWo** [axcore/tartube#504]
Hello
Suddenly I'm missing this download information

![grafik](https://user-images.githubusercontent.com/125090374/218193824-9765d85e-259b-4a5b-9a0a-e8be9488d06c.png)

What settings do I have to make that this problem is solved?

I hope someone can help me.

**Comment by axcore** [comment]
Are you using Tartube v2.4.221? If not, updating Tartube will solve your problem.

**Comment by WWiWo** [comment]
It is the current version 2.4.221

**Comment by WWiWo** [comment]
Actually always worked with older versions. And suddenly this function stopped working.

I have the current one now and it doesn't work there either.

Have Windows 7 as operating system.

**Comment by axcore** [comment]
Fixed in v2.4.232. The fix is only uploaded to Github/Pypi at the moment, if you want to update your Windows installation, see [here](https://github.com/axcore/tartube#71-tartube-wont-installwont-rundoesnt-work).
