### ISSUE TITLE
Tartube cannot start download due to failed database loading.

### ISSUE THREAD

**Issue by wolfspiderzx** [axcore/tartube#505]
When trying to use classic mode I get an error saying "Cannot start the download because Tartube failed to finish loading a database (which seems to be broken)". If I select "check database integrity" I get "Cannot check/fix database after load/save has been disabled". I also cannot access any settings unless I restart the program.

Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Arch Linux with KDE Plasma
### What version of Tartube are you using?
v2.4.093

### What happens when you run Tartube from a terminal window?

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/tartube/mainapp.py", line 3189, in do_activate
    self.start()
  File "/usr/lib/python3.10/site-packages/tartube/mainapp.py", line 3434, in start
    self.start_continue(new_config_flag)
  File "/usr/lib/python3.10/site-packages/tartube/mainapp.py", line 3606, in start_continue
    self.load_db()
  File "/usr/lib/python3.10/site-packages/tartube/mainapp.py", line 6071, in load_db
    self.main_win_obj.drag_drop_grid_reset()
  File "/usr/lib/python3.10/site-packages/tartube/mainwin.py", line 13614, in drag_drop_grid_reset
    options_obj = self.app_obj.options_reg_dict[uid]
KeyError: 3
/usr/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'strikethrough-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
/usr/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'underline-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
/usr/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'weight-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
/usr/lib/python3.10/site-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'style-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)

###If your bug report is "I can't download this video", please provide a link to the video
This will save a lot of time!

**Comment by axcore** [comment]
v2.4.093 is seven months old. Please update to the latest release.
