### ISSUE TITLE
Was working fine before, suddenly not downloading anymore.  How to fix?

### ISSUE THREAD

**Issue by goodstuff626** [axcore/tartube#506]
Always used classic youtube-dl to download using tartube with no problems. Then today I started getting errors on everything I tried to download. Then I tried switching to use yt-dlp to download and still getting errors for everything. The output shows this when trying to download a youtube video in .m4a format -

Usage: yt-dlp [OPTIONS] URL [URL...]
yt-dlp: error: invalid merge output format "m4a" given

What am I doing wrong?

**Comment by axcore** [comment]
yt-dlp is broken for everyone. The authors say it will be updated today, so wait for that update.

**Comment by goodstuff626** [comment]
> yt-dlp is broken for everyone. The authors say it will be updated today, so wait for that update.

I just updated yt-dlp in tartube to version 2023.02.17 but I still get the same error 
message 
"Usage: yt-dlp [OPTIONS] URL [URL...]
yt-dlp: error: invalid merge output format "m4a" given"

Am I doing something wrong? Or does tartube need a new version before it will work again?

**Comment by axcore** [comment]
Try downloading the video. When you see the error, open Tartube's Output tab and take a screenshot (or copy/paste) the yellow text at the top.

**Comment by goodstuff626** [comment]
> 

yt-dlp --newline -i --hls-prefer-native --cookies C:/Users/mike/Desktop/Tartube DLs/cookies.txt -f m4a --merge-output-format m4a --windows-filenames --output C:/Users/mike/Desktop/Tartube DLs/%(title)s.%(ext)s https://www.youtube.com/watch?v=X3QkTtn6O9s

**Comment by axcore** [comment]
You found an ancient bug (so well done).

It's fixed in v2.4.232. The fix is only uploaded to Github/Pypi at the moment, if you want to update your Windows installation, see [here](https://github.com/axcore/tartube#71-tartube-wont-installwont-rundoesnt-work).
