### ISSUE TITLE
No thumbnail generated sometimes. Video download completed however.

### ISSUE THREAD

**Issue by swdw973** [axcore/tartube#508]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Windows 10 latest updates

### What version of Tartube are you using?
v2.4.221

### What happens when you run Tartube from a terminal window?
Still have thumbnail / download issue described below

Details.
I'm having an issue with youtube videos. This is hit or miss, which is making it frustrating to track down.
Tartube completes the download of the video, reports it as download complete, but the thumbnail and title do not show, just the Tartube thumbnail with the DL& watch and website link. 
When I go into the tartube folder, the video is there but no thumbnail. If I try check video,  the "Nothing Happening?" window pops up. I can delete the files through explorer and download it again. Occasionally, this fixes the issue. Most of the time it doesn't.

I was running 2.4.093 previously and did not have this issue. I uninstalled the previous version before installing 2.4.221

**Comment by axcore** [comment]
Some obvious things to try:

- Make sure FFmpeg has been installed correctly. This can be done from the Tartube menu
- Try downloading a channel or playlist (or video). When this problem occurs, take a screenshot of the text in Tartube's Output tab, including the yellow text at the top, and show it to me. (Alternatively just copy-paste the yellow text)

**Comment by JoryAnderson** [comment]
I have my Tartube configured to write description/metadata/thumbs to separate folders, and when the above issue occurs to me I notice that these "housekeeping" processes seem interrupted. The videos that have no problem downloading the thumbnail have no outstanding housekeeping operations, but the ones that don't generate thumbnails will often leave a .description file in the same folder as the video, instead of moving it to a sub-folder.

When I watch my File Explorer while I download, I can see that it created the thumbnail, but it deletes it (it keeps the .description file, but it doesn't move it). Just speculation, but could it be something with the Write/Keep features?

**Comment by axcore** [comment]
Can you give me the URL of a video/channel/playlist which exhibits this behaviour?

**Comment by JoryAnderson** [comment]
Hi @axcore. Here's one channel where this happens a lot. Not all of the videos experience this issue, in particular it seems like this affects videos with (very) special characters in the title or description. 

https://www.youtube.com/@YungCyraxx/videos
(viewer discretion is advised!)

**Comment by JoryAnderson** [comment]
Upon further testing, I also experienced The Beatles song thumbnail **sometimes not** generating, exactly how @swdw973 described, however all other housekeeping tasks completed for the video. This sometimes occurred when I tried "re-downloading" it from the context menu, as well as when I check/download the video after deleting it completely, and verifying all files in each folder are deleted.

![image](https://github.com/axcore/tartube/assets/5385311/a95ba6f2-c2ff-4b1e-b2c5-fc9777fe8d2d)
![image](https://github.com/axcore/tartube/assets/5385311/f0de9231-361b-459b-8928-08d218fd26a6)
![image](https://github.com/axcore/tartube/assets/5385311/72d1fdbb-579f-4d54-b6be-116dd5f13f5b)
![image](https://github.com/axcore/tartube/assets/5385311/63fd6797-ebf0-4293-9193-ec1b96e12405)

**Notice the thumbnail was never fetched/kept/moved**

**Comment by axcore** [comment]
The probable cause of this problem was #320, which is fixed in v2.5.0. 

I will go ahead and close the issue, but feel free to re-open it, if you need ot.
