### ISSUE TITLE
Remember width columns progress tab

### ISSUE THREAD

**Issue by Lux-Hue** [axcore/tartube#509]
Would it be possible to remember the width of the columns in the progress tab between sessions?
In the same way that the window size and slider in the videos tab are remembered.

**Comment by axcore** [comment]
It would be possible, but the columns resize themselves as required, so the sizes you want may not be the sizes you get.

Are there any columns in particular, whose size you want to remember?

**Comment by Lux-Hue** [comment]
That would be the "incoming file" column, that one is always too thin to read all the text.

**Comment by axcore** [comment]
I checked the code, and tested its behaviour. All columns auto-expand, except the Source and Incoming File columns, which have a pre-determined width. This ensures that all columns are visible in the window's default size.

I'll see what I can do about remembering the size of those columns.

**Comment by axcore** [comment]
Done in v2.4.245. The new code is only uploaded to Git/Pypi at the moment, but there will be a full release in the next few days.

It makes no sense to remember the width of most of the columns, but there is a new setting that will remember the columns whose width varies substantially, including `Incoming file`. This setting applies to columns in the Progress and Classic Mode tabs.

**Edit > System preferences... > Windows > Main window > In the Progress/Classic Mode tabs, remember the width of (some) columns**
