### ISSUE TITLE
Goto source

### ISSUE THREAD

**Issue by mbnoimi** [axcore/tartube#51]
Hi,

In `Progress` tab I suggest to add a new menuitem called `Goto source` because sometime when youtube-dl failed to download a video Tartube unable tp show the failed video info.

For example the following video is a private one so Tartube shows nothing in `Progress` tab and I'm unable to know which video failed because I've tens of video sources!
https://www.youtube.com/watch?v=k8Jt3_22SYo&feature=em-uploademail
![image](https://user-images.githubusercontent.com/284547/73120296-19879800-3f7d-11ea-88f2-ff036c260746.png)

**Comment by axcore** [comment]
Added in v1.3.077.

**Comment by mbnoimi** [comment]
> Added in v1.3.077.

I'm unable to see it. I saw two new menuitems (Watch on YouTube and HookTube), 
I'm still unable to determine which folder this video is belong to.

**Comment by axcore** [comment]
I added tooltips in v1.3.086. You can easily see the folder, to which the video belongs.
