### ISSUE TITLE
system tray icon not being removed

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#511]
Latest version, win 10 running from terminal.

When closing tartube, the system tray icon stays around:

![image](https://user-images.githubusercontent.com/16659133/222926463-3ece9f84-de30-4193-aff6-0538d44a42ba.png)

Mousing over them will remove the old icons. I'll test shortly to see if a DB swap causes icons or if it is just closing the program and reopening it from command prompt.

**Comment by ceonelson** [comment]
Doesn't happen on DB switch, only app close and reopen.

**Comment by axcore** [comment]
The code that handles the system tray icon hasn't changed for a long time, so it's possibly (yet another) Gtk bug. I'll check it out; if it's an annoyance, the icon can be disabled completely (Edit > System preferences > Windows > Tray).

**Comment by ceonelson** [comment]
Yes it has been happening for quite a long time (at least a year), just always forgot to post about it until now.

Not a big deal I just hover over them every now and then to get rid of the old ones :)

**Comment by axcore** [comment]
I had the same problem on Linux's Cinnamon desktop until the last (Cinnamon) release, whereupon it magically fixed itself.

**Comment by axcore** [comment]
I spent a few minutes testing Tartube v2.4.260 on Windows 10, but I couldn't reproduce the duplicate icons. On my system, the icon disappears as soon as Tartube shuts down.

Not sure what to suggest, except perhaps replacing MS Windows with a different operating system ;)
