### ISSUE TITLE
Subtitles are not downloading as they used to 

### ISSUE THREAD

**Issue by pcgameman** [axcore/tartube#515]
Hi,

i just updated tartube from version 2.1.0 and subtitles are not downloading. I am using the same settings as shown in my upload. 

Does anyone know how to get tartube downloading subtitles pls?

Thanks in advance
![tartube subtitles option](https://user-images.githubusercontent.com/127336261/223786962-88d338d3-4903-4d31-88d9-b00915d8ad9d.PNG)

**Comment by axcore** [comment]
Please download a video with subtitles, then show me a screenshot of the Output tab with the yellow text at the top visible (or copy and paste that yellow text)

**Comment by pcgameman** [comment]
> Please download a video with subtitles, then show me a screenshot of the Output tab with the yellow text at the top visible (or copy and paste that yellow text)

Hi, this is a video from youtube, https://www.youtube.com/watch?v=TAeieqOOSng,  that I had downloaded with tartube version 2.1.0 and got the mp4 file and subtitles file.

Now i downloaded the same video using version 2.4.260 and no subtitles file was downloaded. 
Here is screenshot of the output tab and I also copied and pasted the text:

yt-dlp --newline -i --hls-prefer-native --cookies C:/tartube data folder/cookies.txt -f mp4 --merge-output-format mp4 --windows-filenames --output F:/1/TARTUBE/%(title)s.%(ext)s --download-archive F:/1/TARTUBE/ytdl-archive.txt https://www.youtube.com/watch?v=TAeieqOOSng
[youtube] Extracting URL: https://www.youtube.com/watch?v=TAeieqOOSng
[youtube] TAeieqOOSng: Downloading webpage
[youtube] TAeieqOOSng: Downloading android player API JSON
[info] TAeieqOOSng: Downloading 1 format(s): 22
[download] Destination: F:/1/TARTUBE/200 Medals Won in an Hour - Raid on Zeebrugge 1918 Documentary.mp4
[download] 100% of   55.83MiB in 00:00:18 at 3.02MiB/s
![Capture](https://user-images.githubusercontent.com/127336261/224496538-10c1c678-e902-4e2d-bdb4-a2b2cf36b013.PNG)

Pls advise what to do to get the subtitles files downloading again. Thanks in advance

**Comment by axcore** [comment]
I tested that video in Tartube v2.1.0, then I updated to the current version of Tartube, using the same config files. Everything behaved as expected (subtitles were downloaded both before and after updating).

I can't explain why you are getting a different result, unless it's the following reason:

There might be two different sets of download options, one used in the Videos tab, one used in the Classic Mode tab. Perhaps you have enabled subtitles in the wrong set of download options.

You can check this for yourself: click Edit > System preferences > Options > Download options. Select one of the sets by clicking on it, then click the Edit button. Check that subtitles are enabled in that set.

On my system, the **general** set applies to downloads in the Videos tab, **classic** applies to downloads in the Classic Mode tab.

![subs](https://user-images.githubusercontent.com/37951926/224543369-6a471426-3298-4f5e-8343-d65636239184.png)

**Comment by pcgameman** [comment]
now worked perfectly! Many thanks for your help!

**Comment by axcore** [comment]
Great! Sorry for the confusion!

**Comment by pcgameman** [comment]
> Great! Sorry for the confusion!

I have one last question pls:
With new videos this works perfectly as you described.
However with videos already downloaded, subtitles are not being downloaded. Is there a way of just downloading subtitles or do I have to re download all videos to get their subtitles pls?

thnaks in advance

**Comment by axcore** [comment]
I'm not sure about that. Have you tried checking the video (right-click it and select Check video)?
