### ISSUE TITLE
Show total download size in download finished dialog box

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#516]
I noticed the new stats at the bottom of the Progress window the other day and enjoyed being able to see the size stats, thanks Axcore!

![image](https://user-images.githubusercontent.com/16659133/224396799-35455d38-1fde-4b8b-b0ca-5c325b26f68a.png)

It's especially helpful as I can check that and if it seems higher than expected go through the whole completed video list to find out why. Last night that helped me find that a few videos had downloaded at 1.4GB each rather than the 250MB they should be!

But if I don't happen to be watching the download near the end, I don't know the total size!

Can we add that info to the finished dialog box, like so?

![image](https://user-images.githubusercontent.com/16659133/224397591-f3cc0a68-ba82-4b14-b080-4341b6e755ae.png)

Am I correct that the size is calculated here?
https://github.com/axcore/tartube/blob/246968c144b89f087990acad195aaafd1a7d6d2e/tartube/mainwin.py#L12609

If so I'll see if I can work on a PR for this next weekend :)

**Comment by axcore** [comment]
I have done it, I will upload the new code today, so don't consume your valuable weekend with a PR.

**Comment by axcore** [comment]
Added in v2.4.269.
