### ISSUE TITLE
System locale not in formats.py causing the System Preferences window to be unable to open

### ISSUE THREAD

**Issue by XhiroYui** [axcore/tartube#518]
### What operating system are you using?
Windows 10

### What version of Tartube are you using?
2.4.260 (Downloaded via sourceforge, portable edition).
Link was just obtained/clicked from the readme.md on this line
> MS Windows (64-bit) installer and [portable edition](https://sourceforge.net/projects/tartube/files/v2.4.260/tartube-2.4.260-64bit-portable.zip/download) from Sourceforge

I also tried "Check for updates" to see if this issue was maybe patched but it said I had the latest build.

### What happens when you run Tartube from a terminal window?
I didn't do this step when reporting the bug as I can kind of guess what's the problem which will be described below.

# Issue Description
First, a snapshot of the issue which makes it pretty self explanatory.

![locale](https://user-images.githubusercontent.com/19362381/226085853-72116f7e-c691-42b1-9e58-a84798e9d247.png)

My system locale is set as "en_MY" which is unrecognized and causes the System Preferences window to not open. 

## Suggested fix

Implement a fallback override on the obtained system locale to en_US if it detects "en" as the first 2 characters to prevent this from happening?

## Fix for users who have the same problem (temp)

For people encountering this problem (if it's not fixed) -> Switch your Locale to en_US (English, United States), restart your pc (not sure if this is required but I restarted before testing and I don't want to double back just to test this), then run tartube again.

**Comment by axcore** [comment]
When you start Tartube, and before you open the preferences window, do you see an error message like this?

![localeerror](https://user-images.githubusercontent.com/37951926/226283826-98d4e81e-c12e-427c-b366-0b9452b19a32.png)

**Comment by XhiroYui** [comment]
Using my laptop, yes I have the error you screenshotted above

![image](https://user-images.githubusercontent.com/19362381/226322470-be8c9500-c3bc-492b-a8b7-6269f7dad985.png)

Potentially more annoying on this computer as it is Windows 11 and there seems to be no proper way to change locale easily.

**Comment by axcore** [comment]
Great, next question: did you manually edit the config file (settings.json) to change the `override_locale` setting?

(I am certain the answer is "no", but I have to check.)

**Comment by XhiroYui** [comment]
No. Both time I just launched via the `tartube_portable_64bit.bat` immediately after installing.

The only notable thing that happened both times is that ffmpeg will fail installing the first time, and after pressing re-install it'll work. 

Most likely unrelated but I'm just bringing it up just in case.

**Comment by axcore** [comment]
Yes, it's unrelated.
