### ISSUE TITLE
Feature request: Clipboard monitoring

### ISSUE THREAD

**Issue by Veronna** [axcore/tartube#52]
If the "Add videos" window would have a clipboard monitoring feature, not just initially on the first time opening the window, but continuous until you stop monitoring,  it would really help to add multiple single videos from different places much faster.

To make it a bit more fancy it could also filter the list for proper links.

**Comment by axcore** [comment]
It might not be obvious, but invalid links are filtered out when the 'Add Videos' window is closed.

**Comment by axcore** [comment]
Added in v1.4.0.
