### ISSUE TITLE
How to rename a video?

### ISSUE THREAD

**Issue by BarbzYHOOL** [axcore/tartube#520]
I don't find how to rename a video at all

**Comment by axcore** [comment]
Rename a video, in what circumstances?

**Comment by axcore** [comment]
You can use output templates to change the name of the downloaded video file

- **Edit > General download options...**
- In the new window, click the tab **Files > File names** 
- In the dropdown box **Format for video file names**, select **Custom**
- In the box **File output template**, type the name of the video
- Click OK to close the window
- Download the video (right-click it, select **Download video**)
- If you try to download another video, it will have the same name; so open the options window again, and undo your changes. (There is a **Reset** button in the bottom corner.)

There are a million different ways to set the output template; see the [yt-dlp documentation ](https://github.com/yt-dlp/yt-dlp#output-template) for a complete list.

**Comment by axcore** [comment]
You asked three separate questions, the solution is different for each question:

>I download a video with typos

Ask the video creator to fix their typos. Or, rename the downloaded video yourself. In Tartube's main window, you can right-click the video, select **Show video > Properties**, then click the + button on the right to select the renamed video file

> or special characters in it 

There is an [unresolved bug](https://github.com/axcore/tartube/issues/320) that prevents Tartube from detecting downloaded Japanese/Korean videos, is that what you mean? In that case, I still don't know how to fix it.

You can use the yt-dlp option `--restrict-filenames` which will remove non-ASCII characters. In Tartube, Edit > General download options... > Files > Filesystem > Restrict filenames to ASCII characters

>or just a way too long name 

In the same tab, add a number to the **Limit filename length** box.

**Comment by BarbzYHOOL** [comment]
> Ask the video creator to fix their typos. Or, rename the downloaded video yourself. In Tartube's main window, you can right-click the video, select Show video > Properties, then click the + button on the right to select the renamed video file

I mean, I just don't like the name of the video because it doesn't describe its content clearly and want to rename it... This method doesn't work, I have to create a file first (a 0 byte file??) then select it, it makes no sense

**Comment by axcore** [comment]
In v2.4.520 I added the ability to download a video using a name you choose yourself.

Right-click a video and select **Special > Download with name...**

![downlaodwithname](https://user-images.githubusercontent.com/37951926/231513105-503f0c6f-9b96-4cc3-8303-8b5ea491564e.png)

You can also edit a video's nickname in its properties window, i.e. **Show video > Properties > General > Listed as**

The changes are only uploaded to Git/pypi at the moment. A full release will be ready in a few days.

**Comment by BarbzYHOOL** [comment]
ok thank you
