### ISSUE TITLE
weirdness with downloading clips/splitting files. 

### ISSUE THREAD

**Issue by alidan** [axcore/tartube#523]
Ok, do for reference this is the youtube video, https://www.youtube.com/watch?v=fYYc_fEL0AA

so I downloaded 2.4.260 with ffmpg and installed I believe over the older version. 

so for the test, I made sure yt-dlp was up to date, and downloaded the video, that worked as expected with the music folder only keeping the audio track and creating a thumbnail not in webp 

so I went to see if it could be processed, a problem in the older version because it would break someone frequently and was currently not working, so I went to process it, and I get to the... forgive me this is greyed out so I can't give exact names at the moment, I went to the tab that should have time stamps for splitting, this one did not have the time stamps for the video so i went to 'use video time stamps' which greyed out the old ones, not sure what they were from anymore. this failed. 

now, take note of the videos formatting of time stamps. so I thought maybe this was the cause. I was going to go and try another video with a more... simple split method, till I saw, and again, its middle of doing this right now so options are greyed out, but a download splits option, I clicked it, it had 33 splits, which corresponds to how many segments there were in the video, and I started that... and its working, but at 3-10 minutes per segment, getting longer and longer as this goes on, I think this will take around 4~ hours to finish. 

im wondering if this is working as intended? 
and also is there a way to process the already downloaded file for segments or did I do something stupid? 

I will update this with some images and exactly what I did after this finishes so I have full access to what the program.

also, unless anything is known broken for other people, I would hold off trying to fix anything, im on win 7 and will be moving oses probably in the next month, anything I have issues with may be fixed by that move alone.

**Comment by alidan** [comment]
I just noticed this, because its still doing what I want it to, just progressively slower, I wasnt thinking there was an error, but every one of them has this. 

![python3_2023-03-22_16-45-54](https://user-images.githubusercontent.com/2681758/227046025-6dcca06c-3288-4be2-a444-dcdb76ebadd3.png)

not sure if its important.

**Comment by axcore** [comment]
>forgive me this is greyed out so I can't give exact names at the moment

Not a problem, just take a screenshot. A picture is worth a thousand words :)

**Comment by axcore** [comment]
>I just noticed this, because its still doing what I want it to, just progressively slower, I wasnt thinking there was an error, but every one of them has this.

I haven't seen this error before. If you can describe exactly what you are doing to produce it, that would be very helpful.

**Comment by alidan** [comment]
ok, first let me give this image, 
![explorer_2023-03-23_19-46-43](https://user-images.githubusercontent.com/2681758/227396189-947ecb5e-22ca-4b87-8438-cb886c98440d.png)
that is it finally done, again, it did what I wanted, just slow. 

so lets start off which the steps, I was testing the new install to see if it would seperate video files, so I downloaded that 1:14:00 video with the music folder that just strips the video out of the auido.

so I have the audio track...

ok at this point I was going to go through the step but its still greyed out, I also noticed there was one new error at the end, 
![python3_2023-03-23_19-50-51](https://user-images.githubusercontent.com/2681758/227396603-64c28bb3-cd27-4c66-8fa7-0c7910f0fcaf.png)


im going to close it and reopen, if I still get the same grey out, I will go over it with a new link...

ok its not greyed out. 

so after downloading it, I right clicked it, and the only thing that made sense was 'process with ffmpeg
![python3_2023-03-23_19-53-33](https://user-images.githubusercontent.com/2681758/227396807-c19ac901-3d59-4e95-a34c-4629675d1b1e.png)

now is where everything was a little confusing for me, clips and slices can honestly be the same thing, but when I saw remove slices from the video, I decided that was for sponsor block, and clips was a more familiar ui from when I was trying to split the doom metal v5 soundtrack

![python3_2023-03-23_19-56-15](https://user-images.githubusercontent.com/2681758/227397150-2a080fd2-e34a-4264-846a-0934d30ea9b8.png)

I think the time stamps there are things I entered a long time ago for another video, so not wanting to do that, I clicked the split videos useing their won time stamps, to which I got this dialouge

![2023-03-23_19-57-10](https://user-images.githubusercontent.com/2681758/227397297-72588023-493b-4463-8100-82febc04986e.png)

so with that not working I decided that this is probably ffmpeg not getting a list of the time stamps, given it was able to get the thumbnail working, or at least had the thumbnail working, it has since dissapeared. the thumbnail IS still there, as a jpeg and a webp
![explorer_2023-03-23_20-00-11](https://user-images.githubusercontent.com/2681758/227397608-1af25806-3fb2-4dd8-bb10-07335f4823dd.png)

so I went to special and remembered the download video clips button and pressed it, 

![python3_2023-03-23_20-01-05](https://user-images.githubusercontent.com/2681758/227397710-ee478acf-5292-439b-9fc9-b9b21514d31d.png)

now I thought this was again a failure, I was going to move on to it just not working again, till I noticed "download all clips (33)"
I know that the manual time stamps were not 33 long, 
I counted the ones on the video and it was 33 segments
so I pressed that button and let it do its thing, I have absolutely no idea what it did, because it keep taking longer and longer for each clip, but it was not taking old song time + new song time...

and that's what I did.

in the interest of seeing if this behavior happens again, I have a short video, 
https://www.youtube.com/watch?v=GDbv6RiWPHs

I have not downloaded it, I will do this again with one I have downloaded to see if there is a change. 

Ok, so far it has stopped, telling me maybe update yt-dlp, there was no update, retrying
and it failed again, trying to just download it now, 

ok downloaded it, once downloaded the thumbnail disappeared again, going to try downloading its clips agian. and it failed... I triend once more useing the above 

Click the button Reset list using video description
Click the OK button to close the window
Right-click the video again, and select Special > Download video clip...
Click the button Download all clips

method, and that also failed, going ot try another video, this one longer

https://www.youtube.com/watch?v=2mxIK8G1gcA

ok, first check video, then special download clips, this one has 35, this one also failed going to try to restart again, trying the short one, it failed, then tried the longer one, it failed, and just to make sure everything is working, I go to download the video, it works, the thumbnail is again now missing in tartube, but 
![explorer_2023-03-23_20-33-18](https://user-images.githubusercontent.com/2681758/227401868-3ae52dec-ce40-4d4a-9b2b-bf4bd36f912a.png)
right there they are both webp and jpeg

you ytdlp is working, ffmpeg is working I believe, its able to see the metadata and get get the time stamps along with what to call them, but it fails to do that from both download and process from 

ok, I noticed another thing, this has not shown itself again
![python3_2023-03-23_20-36-17](https://user-images.githubusercontent.com/2681758/227403941-c8ced935-2a19-46d8-92a8-fffa16eeda83.png)

now, my best guess is, and this is a stupid problem I just noticed I have, every single folder on my computer is apparently read only, but windows doesn't care about that at all. my guess now is that something is either opening itself with lesser permissions than me and its getting stuck there. I also cant turn off the read only status for any folder for some reaoson. 

unless you can think of anything, im going to just say my install of windows hates me and will re try this when I move over to 10

**Comment by axcore** [comment]
You are seeing a couple of Python errors. I think the download process fails to complete because of those errors, which is why some things are unexpectedly greyed out.

Let's start by fixing those errors, and then we can see where things stand.

The new code is only uploaded here on Github. You can download the files into the right folder, replacing the old versions of those files, as described [here](https://github.com/axcore/tartube#71-tartube-wont-installwont-rundoesnt-work).

Alternatively, there should be a full release at the end of the month, so you could wait for that.

**Comment by alidan** [comment]
I am in no real hurry, I can wait till the full release, will try it out and see if anything changes. 

but just to be clear, nothing I was doing is technically wrong, somehow the first download worked though it was tossing errors, and subsequent ones decided to not even limp along?

**Comment by axcore** [comment]
Just to let you know, I have been working to redesign the interface for downloading clips, but it's not quite ready for release yet.

![clips](https://user-images.githubusercontent.com/37951926/230559274-9d379a73-fcdd-4832-993b-d8c9e400bdae.png)

**Comment by alidan** [comment]
Honestly looks perfect, got a question, download new clips using yt-dlp/ffmpeg, whats the difference? 

I am assuming maybe youtube already cuts the videos/audio up now so dlp can just can just download from time stamps, and ffmpeg gets the whole audio and then processes it?

**Comment by axcore** [comment]
yt-dlp has some new options for downloading clips, I am adding compatibility with those options. I don't know how they work internally.

**Comment by axcore** [comment]
I have completed the video clip improvements. The new code is uploaded to Github/Pypi only; to patch a Windows installation, see [here](https://github.com/axcore/tartube#71-tartube-wont-installwont-rundoesnt-work); or you can wait for the main release in a few days.

Both video clips and video slices have been substantially improved. Video clips can now be created in the Classic Mode tab, too. I haven't updated the README yet, but it should be mostly self-explanatory.

**Comment by alidan** [comment]
ok new os install and preliminary testing it

the option to get clips from ytdlp seems to do alot of stuff in the background, and then error out at the end

I currently have this https://www.youtube.com/watch?v=xyJdWemtuCk as the test song going with get from ffmpeg I have no idea how long it is going to take, I did want to try with an already downloaded one but that wasnt a selectable option, I intend to let this one ride till its done than try this one https://www.youtube.com/watch?v=3Taeptxe5Ag after its done by downloading it and then seeing if I get the option to work with what I already have, since this is just working with audio, there is nearly no reason for it to take any real amount of time, take some time yes, but i almost want to say I could re encode a bluray to av1 faster on my cpu than than the copious amount of time the reason I made this post took. 

fingers crossed this either works faster, or that downloading the whole audio and then ffmpeg works.

will update once this is done, have so much crap to get up and working due to the os switch that this is going to be backburner till that's done, which given how fast 8.6 million files are copying, seems like its going to be a week or so
