### ISSUE TITLE
Two questions about FixupM3U8 and custom dates

### ISSUE THREAD

**Issue by George620** [axcore/tartube#525]
I would like to know how you can make a custom date of upload after the video name like this when I download from Twitch: "VIDEONAME 24.3.2023"
I would be happy if upload date is customized to my timezone too.

Another thing is to how to download .ts files without reencoding them to mp4 (without needing to do FixupM3u8 step) and save them just as .ts?

**Comment by axcore** [comment]
Edit > General download options... > Files > File names
In the box **Format for video file names**, select **Custom**
In the box **Date/time/location**, select **Upload date (custom format)**
In the **Time format** box, you should be able to see this:

`%Y-%m-%d`

Change it to this:
`
%d-%m-%Y`

Now click the **Add** button just above it, and then the **OK** button to close the window.

![date](https://user-images.githubusercontent.com/37951926/227446115-71f47b0c-d63d-4142-8c65-0388be60c40f.png)

**Comment by axcore** [comment]
I don't know anything about .ts files. The  [yt-dlp documentation](https://github.com/yt-dlp/yt-dlp) doesn't mention any support for them.

**Comment by George620** [comment]
I tried one program "yt-dlg" that is based on yt-dlp and it downloaded .ts files without reencoding it to .mp4. So it might work here.
And I did it exactly like you said and it did only title, not date at all. Looking at the code, would it be possible to have "." in between if it works?

**Comment by axcore** [comment]
>I tried one program "yt-dlg" that is based on yt-dlp and it downloaded .ts files without reencoding it to .mp4. So it might work here.

yt-dlg will not install on my system, so I can't confirm that.

>And I did it exactly like you said and it did only title, not date at all.

I set up my download options, exactly as described above, then I downloaded [this video](https://www.youtube.com/watch?v=jNQXAC9IVRw). Here is the result:

![result](https://user-images.githubusercontent.com/37951926/227592283-be63b2e2-4850-4654-a12b-f2542fe3ab51.png)

The video is downloaded with both the title and the upload date, as expected. By the way, only the _original_ video name is visible in Tartube's window. If you want to see the _actual_ video filename in Tartube's window, click Edit > System preferences... > Windows > Videos, and un-selected **Show nicknames (not video file names)**

![result2](https://user-images.githubusercontent.com/37951926/227592714-6f748f72-92d1-44f8-9016-a83ee875a408.png)

>Looking at the code, would it be possible to have "." in between if it works?

In the download options window, you can insert any characters you like in the **File output template** box. For example here I am inserting your name.

![result3](https://user-images.githubusercontent.com/37951926/227593107-4f55fafd-e860-47cf-affc-9c81b1c60e3f.png)

**Comment by axcore** [comment]
Closed for inactivity.
