### ISSUE TITLE
Have a problem with the "New Videos" list

### ISSUE THREAD

**Issue by WWiWo** [axcore/tartube#526]
Have a problem with the "New Videos" list 

I can't play many videos from the "New Videos" list with the video player. 

and there is no source to be seen. 

and I can't open a video link in the browser. 

Please help
[]() 
![IMG_20230323_232502_288](https://user-images.githubusercontent.com/125090374/227378508-7a621da4-7b03-4384-8bdf-a121f39d4aad.jpg)

Thanks for taking the time to ask a question! 

### Please read the README
Perhaps your question is answered there

### The authors are not experts in python, security, youtube-dl, FFmpeg, Debian/RPM packaging or Windows programming
You are welcome to ask a Tartube-related question, but you might get a better answer in forums where those kinds of expert can be found

**Comment by axcore** [comment]
Can you give me the URL of the Krebs Heilung video?

**Comment by axcore** [comment]
I downloaded the same channel, but did not see the same problems. The krebs heilung video downloaded correctly.

![krebs](https://user-images.githubusercontent.com/37951926/227761184-c0f8e9b3-7056-4f3f-84ff-9a210f10cae0.png)

Perhaps you can check these things:

1. Check you have installed FFmpeg via Tartube's menu
2. Check the version of Tartube you are using (Help > About)
3. Check the **Errors/Warnings** tab, in particular look out for any errors that contain the word Python

**Comment by axcore** [comment]
Closed for inactivity.
