### ISSUE TITLE
Auto rename

### ISSUE THREAD

**Issue by Mefisst** [axcore/tartube#527]
I have all links without a name, they are called master
several links in a row cannot be downloaded because the file names are the same
how to rename automatically downloaded files so that the download continues?
link format ends with master.m3u8, so the final file name is master.mp4

**Comment by axcore** [comment]
Use file output templates.

Edit > General download options... > Files > File names

In the box **Format for video file names**, select **Title + ID**

A video's ID is unique, even if the title is the same.

**Comment by Mefisst** [comment]
does not work

**Comment by Mefisst** [comment]
2 files are downloaded at the same time, these files have the same name, as soon as one is downloaded, it gives an error

**Comment by Mefisst** [comment]
<a href="https://ibb.co/LZYbr33"><img src="https://i.ibb.co/VqJrxss/1-001.jpg" alt="1-001" border="0"></a>
<a href="https://ibb.co/bPLtLs6"><img src="https://i.ibb.co/t4cRcqH/1-002.jpg" alt="1-002" border="0"></a>

**Comment by axcore** [comment]
Make sure you are using the right download options for the Classic Mode tab. There is a menu button in the top-right corner, open the options window from there.

**Comment by Mefisst** [comment]
I didn't change anything, just updated the plugins. this app is not working well

1. Two files are downloaded at the same time
2. Each of the files has the same name
3. Each file is downloaded in parts
4. Each part has the same name as the first and second file
5. There is a conflict in the names of parts, so no file is loaded.

**Comment by axcore** [comment]
You can tell Tartube to download only one video at a time, in the Progress tab.

![progress](https://user-images.githubusercontent.com/37951926/231472585-09384805-40d3-4abc-953d-f1ee9e634d51.png)

Your other question is: "I set the output template to **Title + ID**, but there is still a name conflict"

I'm not sure why that happens; maybe yt-dlp does not work well with vhcdn.com. If you like, you can give me the URL of both videos, then I can test them.
