### ISSUE TITLE
No alarm sound when livestream starts

### ISSUE THREAD

**Issue by Lux-Hue** [axcore/tartube#529]
linux fedora 37
tartube version 2.4.283

When a livestream is detected, and I turned on the "When a livestream starts, sound an alarm" checkbox, no audio is produced.
When testing with the "test" button manually, the following pops up in the log:
```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/large/.local/bin/tartube", line 158, in handle_uncaught_exception
    raise type(value)
TypeError

Original exception was:
Traceback (most recent call last):
  File "/home/large/.local/lib/python3.11/site-packages/tartube/config.py", line 33802, in on_test_sound_clicked
    self.app_obj.play_sound()
  File "/home/large/.local/lib/python3.11/site-packages/tartube/mainapp.py", line 21581, in play_sound
    os.path.join(self.sound_dir, sound_name),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by axcore** [comment]
Is the playsound module installed on your system? You can check by clicking **Edit > System preferences > General > Modules**

![playsound](https://user-images.githubusercontent.com/37951926/230557855-ceb93b54-b405-4d9a-8349-7462a01c13f7.png)

**Comment by Lux-Hue** [comment]
yeah, it does detect that it is installed
![Screenshot_20230410_205128](https://user-images.githubusercontent.com/32292209/230972383-107b943d-dbb0-4858-af13-d5b71fa75876.png)

**Comment by axcore** [comment]
There is a typo in the installation file (`setup.py`) that moves sound files to the wrong location. Apparently you're the first person in three years to notice :)

I have fixed the typo, and also added more checks to prevent the python error. The fix will be in the next release, which will be ready in a few days.

Workarounds:

- [Fedora 37] Create the directory /usr/share/tartube/sounds. Move all of the .mp3 files from /usr/share/tartube/icons into /usr/share/tartube/sounds
- [All Linux distros] Run Tartube directly from source code, as described [here](https://github.com/axcore/tartube#539-install-from-source)

**Comment by Lux-Hue** [comment]
Yep, the workaround fixed the issue, thanks!

**Comment by Lux-Hue** [comment]
Yep, the workaround fixed the issue, thanks!
