### ISSUE TITLE
Option to Paste playlist link is grayed out

### ISSUE THREAD

**Issue by dlmac** [axcore/tartube#533]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
If using MS Windows, are you using Windows 10, Windows 7, or something else?
Docker

### What version of Tartube are you using?
In Tartube's main window, click Help > About
2.4.221

### Issue

I copy a link from my playlist but "Paste" is grayed out. Does this for all link.

<img width="344" alt="image" src="https://user-images.githubusercontent.com/372043/230747443-a4167789-2622-4256-a8be-5b66dde0af48.png">

**Comment by axcore** [comment]
`Paste` is not greyed out on other platforms, which suggests this is a Docker problem.

![playlist](https://user-images.githubusercontent.com/37951926/231459407-9fb2f0c5-da37-4f2f-a32f-893ee5fee11c.png)

If you tell me how you installed Tartube using Docker, then I can try to replicate your setup.

**Comment by dlmac** [comment]
After some experimentation it would seem there is another Clipboard pane hidden on the left. If I past the link there it then shows up in the "Add Playlist" to paste. Very weird functionality, and still not sure if it is functioning correctly.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/372043/231519640-cbb9f669-5295-4f6e-aa9f-033c92866346.png">

**Comment by axcore** [comment]
The **Enable automatic copy/paste** button monitors the system clipboard, when it's enabled.

**Comment by axcore** [comment]
Closed for inactivity.
