### ISSUE TITLE
Tartube won't start

### ISSUE THREAD

**Issue by vertigo220** [axcore/tartube#534]
### What operating system are you using?
Win10

### What version of Tartube are you using?
2.4.260

Was running, closed it then tried to launch it again a short while later and it flashed on the taskbar then nothing. Tried a few times, same thing. Only thing I can think of is that I tried installing FFmpeg with it, which failed, before closing it, so not sure if that messed something up, though it shouldn't have been able to cause Tartube not to open.

**Comment by axcore** [comment]
If you like, you can run Tartube from the MSYS2 terminal, so that any error messages are visible. Find the Tartube installation folder, then open the msys64 sub-folder, the double-click **mingw64.exe**, then in the terminal window type

```
cd /home/user/tartube
python3 tartube/tartube
```

Alternatively, you can save yourself the trouble and just delete Tartube's installation folder before re-installing it.

**Comment by vertigo220** [comment]
Thanks. I generally prefer to actually figure out what's causing something so it can hopefully be fixed rather than to just "turn it off and back on again." I tried running those commands and nothing happened, just put me back at the prompt, with no output whatsoever. I triple-checked I was in the proper location and the command was typed accurately, including copy/pasting. This was with the %localappdata% (AppData\Local) install. Not sure why, but I have two, one there and one in AppData\Roaming (%appdata%), and issuing those commands in the terminal run from the roaming install did open Tartube, with an error saying "Database file can't be read by this version of Tartube. Because of the error, file load/save has been disabled." It's v2.4.093.

Between the fact the Start Menu shortcut links to the Local install, not the Roaming one, and the Roaming one is empty, i.e. it doesn't have any of my saved stuff in the "Videos" tab, I'm guessing that the Roaming install has just been sitting there, unused, and the Local one is the one I've been using and that broke somehow.

I'll probably just remove both and reinstall just to one, but again, I prefer to actually find out what caused something to break so it can be fixed as opposed to resetting everything and simply hoping it doesn't happen again. Is there anything else I can do to help troubleshoot it?

Finally, after running the Roaming install, I reopened the terminal from the Local one to try the commands once more, and this time when I tried to change directories I got the error that it doesn't exist. So not sure if running the Roaming install "stole" it somehow, if that's even possible.

**Comment by axcore** [comment]
>Not sure why, but I have two, one there and one in AppData\Roaming (%appdata%), and issuing those commands in the terminal run from the roaming install did open Tartube, with an error saying "Database file can't be read by this version of Tartube. Because of the error, file load/save has been disabled." It's v2.4.093.

Tartube can open files created by any older version of Tartube, but it will refuse to open files created by a new version. So v2.4.260 should be able to open v2.4.093, but v2.4.093 will not open v.2.4.260.

If you have two installations on your system, I suggest removing the earlier one. Then you can try the terminal window again; it should be ..\AppData\Local\Tartube\msys64\mingw64.exe or ..\AppData\Roaming\Tartube\msys64\mingw64.exe.

**Comment by axcore** [comment]
If bandwidth is limited, and if you decide to remove all your Tartube installations and start from scratch, then you could wait a few days, as I'm working on the next major release now.

**Comment by vertigo220** [comment]
Removed the old version in Roaming and tried the commands again with the Local version, still blank output.

**Comment by axcore** [comment]
Sorry, I have no explanation for that.

You could try this pair of commands:

cd /home/user/tartube
ls -al

...so we can at least see if the Tartube files actually exist, or not.

**Comment by vertigo220** [comment]
Everything looks right:

```
MINGW64 /home/user/tartube
$ ls -al
total 428
drwxr-xr-x 1 Username None      0 Apr  9 01:16 .
drwxr-xr-x 1 Username None      0 Oct 23 18:49 ..
drwxr-xr-x 1 Username None      0 Oct 23 18:49 .github
-rw-r--r-- 1 Username None    268 Aug 19  2019 .gitignore
-rw-r--r-- 1 Username None   1236 Jan  7 07:27 AUTHORS
-rw-r--r-- 1 Username None 175662 Mar  2 07:30 CHANGES
-rw-r--r-- 1 Username None  26521 Oct 28 06:36 LICENSE
-rw-r--r-- 1 Username None    152 Mar 27  2020 MANIFEST.in
-rw-r--r-- 1 Username None     63 Aug 28  2017 Makefile
-rw-r--r-- 1 Username None 143877 Mar  2 07:24 README.rst
-rw-r--r-- 1 Username None      8 Mar  2 07:25 VERSION
-rw-r--r-- 1 Username None     17 May 28  2019 __init__.py
drwxr-xr-x 1 Username None      0 Oct 23 18:49 docs
drwxr-xr-x 1 Username None      0 Mar  3 23:23 icons
drwxr-xr-x 1 Username None      0 Mar  3 23:23 locale
drwxr-xr-x 1 Username None      0 Oct 23 18:49 nsis
drwxr-xr-x 1 Username None      0 Mar  3 23:23 pack
drwxr-xr-x 1 Username None      0 Oct 23 18:49 screenshots
-rw-r--r-- 1 Username None  13304 Apr  9 01:16 settings.json
-rwxr-xr-x 1 Username None   8309 Mar  2 07:23 setup.py
drwxr-xr-x 1 Username None      0 Oct 23 18:49 sounds
drwxr-xr-x 1 Username None      0 Oct 23 18:59 tartube
-rw-r--r-- 1 Username None    127 Mar  2  2021 tartube_64bit.bat
-rwxr-xr-x 1 Username None    195 Apr 12  2022 tartube_mswin.sh
-rwxr-xr-x 1 Username None     86 Feb 16  2021 tartube_portable.sh
drwxr-xr-x 1 Username None      0 Oct 23 18:49 tests
```


```
MINGW64 /home/user/tartube/tartube
$ ls -al
total 4400
drwxr-xr-x 1 Username None       0 Oct 23 18:59 .
drwxr-xr-x 1 Username None       0 Apr  9 01:16 ..
-rw-r--r-- 1 Username None       0 Apr 21  2019 __init__.py
drwxr-xr-x 1 Username None       0 Mar  3 23:25 __pycache__
-rwxr-xr-x 1 Username None    2584 Jan  7 06:48 classes.py
-rwxr-xr-x 1 Username None 1044422 Mar  1 09:13 config.py
-rwxr-xr-x 1 Username None   16384 Jan  7 06:48 dialogue.py
-rwxr-xr-x 1 Username None  397989 Mar  2 07:20 downloads.py
-rwxr-xr-x 1 Username None   42679 Jan  9 15:26 ffmpeg_tartube.py
-rwxr-xr-x 1 Username None    3902 Jan  7 06:48 files.py
-rwxr-xr-x 1 Username None   43889 Feb 25 15:34 formats.py
-rwxr-xr-x 1 Username None   20282 Feb 19 08:03 info.py
-rwxr-xr-x 1 Username None 1016694 Mar  2 07:31 mainapp.py
-rwxr-xr-x 1 Username None 1235082 Mar  2 06:12 mainwin.py
-rwxr-xr-x 1 Username None  150974 Feb 27 11:56 media.py
-rwxr-xr-x 1 Username None   82025 Feb 19 07:40 options.py
drwxr-xr-x 1 Username None       0 Oct 23 18:49 po
-rwxr-xr-x 1 Username None   33831 Jan  7 06:48 process.py
-rwxr-xr-x 1 Username None   21723 Mar  1 09:13 refresh.py
-rwxr-xr-x 1 Username None    4968 Mar  2 07:22 tartube
-rwxr-xr-x 1 Username None   55304 Mar  1 09:12 tidy.py
-rwxr-xr-x 1 Username None   35239 Jan  7 06:48 updates.py
-rwxr-xr-x 1 Username None  124175 Mar  1 09:12 utils.py
-rwxr-xr-x 1 Username None  111574 Mar  1 09:12 wizwin.py
-rw-r--r-- 1 Username None    5908 Jan  9 15:27 xdg_tartube.py
```

Is it possible the failed FFmpeg install messed it up somehow? If so, is there any way to check that. I'm guessing at this point with everything going on I'm just going to have to reinstall, but was just hoping to maybe be able to figure out the cause while it's broken and can be troubleshot. But I realize that may not be possible.

**Comment by rwperrott** [comment]
OS: Linux Mint MATE 64-bit
Tartube Version: 2.4.230 from normal .deb
```zsh
$ tartube
[1]    808558 IOT instruction (core dumped)  tartube
FAIL
```

**Comment by axcore** [comment]
Edited to say: there are [several different ways](https://github.com/axcore/tartube#53-installation---linuxbsd) to install Tartube on Linux Mint, and you can also just run the source code directly. If the .deb package won't work, try one of the other methods.

**Comment by rwperrott** [comment]
`python3-tartube_2.4.386.deb` started fine on my machine, hopefully it will continue to do so.

**Comment by axcore** [comment]
Closed for inactivity.
