### ISSUE TITLE
How does downloading stream at start work

### ISSUE THREAD

**Issue by Lux-Hue** [axcore/tartube#536]
I understand how I can tell tartube to download a stream when it starts, but does this also work when tartube detects (for the first time) a stream that has already begun? From my testing it seems it won't, but maybe I'm missing something. There's also no notification that a stream has begun in that situation.

**Comment by axcore** [comment]
I could reproduce your problem, so I think you _are_ talking about the setting in **Edit > System preferences... > Operations > Actions**.

There are some situations in which Tartube notices a change in the video's status (was not broadcasting, but is now broadcasting). But that message did not always reach the right place.

I re-designed the code to make sure that doesn't happen any more. All of my tests were successful, but feel free to re-open this issue, if you have any more problems.

Tartube v2.4.358 is only uploaded to Git/pypi at the moment, a full release will be ready in a few days.
