### ISSUE TITLE
ffmpeg front end

### ISSUE THREAD

**Issue by alidan** [axcore/tartube#539]
Ok, after the last update, trying to download clips, and overall just having it takes kind of obscene amounts of time for what its doing (splitting audio only should be near instant) and the relative constant issues I have had with getting clips to download split, I think separating the two processes entirely would be for the best. 

My thoughts on it are this. 

a tab that is just ffmpeg processing, its not even going to try to connect to the internet or intergrate. 
When an option in the videos tab to 'send to ffmpeg' this will send the file over to it, along with metadata in the case of clips
in the ffmpeg processing, some common forms of processing as quick selects, I think stripping video and only keeping the audio would be a common one, or in the redone 'create clips' dialog, an easy way to select clips. 
a few format export/save as options, from lossless to slight compression to actually compressed, I know when splitting audio you can't do it losslessly I believe without stupid amounts of extra space taken up, I accept some amount of compression as a necessary evil, but if I was putting things onto a device with limited space, I would accept even more for smaller file sizes.

I think that getting ffmpeg into the program along with is working offline removes a lot of the potential issues it can run into with just downloads taking forever, failing for reasons you have no idea why, and removes one of the factors in things that can potentially break. 

![python3_kRpe1V89Fq](https://user-images.githubusercontent.com/2681758/232339212-86192a9c-568d-4499-8ad1-d5900c6f044d.png)

I have no idea why it starts to take longer and longer, I mean if they all took that 3-5 minutes, understandable.
Also, through tartube and something android based, I have not been able to get yt-dlp to download clips/sections, so I have 0 idea how that works/is suppose to work

if the front end for ffmpeg more or less allowed for everything currently in the create video clips download area, but you either added the video though right clicking their location in the folders, or outside of program dragged and dropped it in, or navigated to it though a dialogue, I think this would cut a fair amount of problems out, currently needing to go though downloading seems to just cause problem's,

**Comment by axcore** [comment]
In testing, I have seen reasonable speeds for downloading clips and sliced videos, but that doesn't guarantee that every such download will be painless. If you want me to test your specific problem, give me the URL, and the precise video clip settings you selected, and the yellow text in the Output tab.

Regarding your idea for "offline" FFmpeg processing; presumably you've tried (in the Videos tab) right-clicking a video, then selecting **Special > Process with FFmpeg**? This is "offline" and it has access to the video's metadata; does it fulfill your needs?

Regarding "common forms of processing as quick selects", keep in mind that I don't know how FFmpeg works and, in fact, I know very little about video editing generally. All of the FFmpeg stuff in Tartube has been copied from somewhere else, not created by me.

About Tartube on Android: it's apparently possible to run Tartube on Android, but I have never used it and know nothing about it. Same applies to MacOS.
