### ISSUE TITLE
Can't add videos

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#54]
Trying to get into edit -> general download options to include the command string I use for the atomicparsley thread and that window won't open... and neither will add a video, channel, etc.  

Any thoughts on what might be causing this?  My database is also empty somehow and the refresh failed, so basically I can't use the app when it was working fine before I closed it last week :/

It happened originally on 1.3.007 and is still happening after the update to 1.3.077.

On a side note, is there a way for the Windows installer to remember the custom location Tartube was installed in?

Thanks for all your hard working making this!

**Comment by axcore** [comment]
@ceonelson, I just tested Tartube on MS Windows, and was able to open the windows fine.

Firstly, check that there isn't a python error that's ruining everything.

Find the folder C:\Users\YOURNAME\AppData\Local\Tartube\msys64

Double-click the application mingw64.exe to run it

In the new terminal window, type these commands

cd tartube
python3 tartube/tartube

Tartube opens. Try to open the general download options window. Check the terminal window, and see if you can see an error message.

**Comment by axcore** [comment]
>My database is also empty somehow and the refresh failed

Find the folder where Tartube is storing its videos, tartube-data (presumably you know where that is)

There should be at least two files - tartube.db and tartube_BU.db. If the first one is damaged for some reason, the second one should still be ok. Before you do anything else, make a copy of those two files, in case we need them later.

**Comment by axcore** [comment]
>On a side note, is there a way for the Windows installer to remember the custom location Tartube was installed in?

I don't think so. Tartube is designed to be portable, so it doesn't alter the Windows registry or anything like that.

**Comment by ceonelson** [comment]
Making a new data directory and a new db and the app loads the menus, so it looks like both my database and backup got corrupted somehow :/

$ python3 tartube/tartube
Traceback (most recent call last):
  File "\Tartube\msys64\home\user\tartube\tartube\mainapp.py", line 8791, in on_menu_general_options
    config.OptionsEditWin(self, self.general_options_obj, None)
  File "\Tartube\msys64\home\user\tartube\tartube\config.py", line 1857, in __init__
    self.setup()
  File "\Tartube\msys64\home\user\tartube\tartube\config.py", line 89, in setup
    self.setup_tabs()
  File "\Tartube\msys64\home\user\tartube\tartube\config.py", line 1954, in setup_tabs
    self.setup_files_tab()
  File "\Tartube\msys64\home\user\tartube\tartube\config.py", line 2298, in setup_files_tab
    store5.append( [pixbuf, self.app_obj.fixed_misc_folder.name] )
AttributeError: 'NoneType' object has no attribute 'name'

Sadly the only place I had my youtube-dl custom command line was in the tartube config so I'll need to figure out how to recreate that.

What are your thoughts about making the daily backup the default option?  That would have let me at least get my settings back, but I don't know how large the db gets for heavy users.  Or make program options a separate db or ini from the videos (though probably not worth the effort)?

**Comment by axcore** [comment]
>Sadly the only place I had my youtube-dl custom command line was in the tartube config so I'll need to figure out how to recreate that.

The database file is not in some secret file format; it's in a format that is easy for python to read. If you are willing to send it to me, I can probably repair it. 

Email is lestrol123@gmx.com

>What are your thoughts about making the daily backup the default option?
Yes, that might be a good idea.

>but I don't know how large the db gets for heavy users
My database with 30,000 videos is 35MB. Not a terrible burden for a modern computer.

**Comment by ceonelson** [comment]
Thanks so much, just sent them over :)  I'm definitely going to set daily backup from now on.
