### ISSUE TITLE
Is there a way to download thumbnails for existing videos?

### ISSUE THREAD

**Issue by BlueBull010** [axcore/tartube#542]
Hello good people

First let me thank you for the amazing piece of software you have created. It is by very far the most feature-rich and powerful GUI video downloader out there. There isn't even anything comparable anywhere. And then to know it is free.... Well, I would pay money for this program, I like it so much

I have a question: I have a whole bunch of youtube channels and playlists downloaded and for most of them, the option to download thumbnails, to convert them to JPEG and to keep them was enabled. However when I just started using Tartube I didn't know how to do this, so the first channels and playlists I have added at the start don't have thumbnails. It also won't download them (neither during a download nor during a check) even with the right options checked. As those channels constitute multiple Terabytes of downloaded videos, I would really prefer not downloading them again. So, is there a way to make Tartube fetch only the thumbnails for videos that are already in the database and have been downloaded already?

Cheers and with kind regards

Tom

**Comment by axcore** [comment]
There isn't an option to re-download thumbnails for the video.

In this situation, I suggest creating a new database, importing your list of channels/playlists into it, then doing Check all to get the thumbnails, then you can copy the thumbnails into your main database.

- Click **Media > Export/Import > Export from database**
- In the window, make sure **Include lists of videos** is not selected
- ...but make sure the other options are select
- Click the OK button, and save the export (perhaps to your desktop)

- Now click **File > Database preferences**
- Click the **Add new database** button
- Select a new folder (perhaps on your desktop)

- Now click **Media > Export/Import > Import into database**
- Select the export file you created earlier
- Assuming that all of your channels/playlists were imported, you can click the Check all button
- When it's finished, copy all the thumbnails from the new folder into the main folder

**Comment by BlueBull010** [comment]
Awesome, thank you for this workaround. I'll try it out later today but at first glance this indeed seems like it should work. Cheers!
