### ISSUE TITLE
ModuleNotFoundError: No module named 'gi'

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [axcore/tartube#544]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
linux opensuse

### What version of Tartube are you using?
can't launch to see

Installed it using `pip install tartube` and it worked fine.
A few weeks later when I launch it it gives this error:

```
tartube
Traceback (most recent call last):
  File "/home/username/.local/bin/tartube", line 42, in <module>
    import mainapp
  File "/home/username/.local/lib/python3.8/site-packages/tartube/mainapp.py", line 24, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

**Comment by axcore** [comment]
I suggest uninstalling it (with `pip uninstall tartube`), then re-installing it.

If problems persists, there are several other installation methods, including just running the source code directly. Instructions for all of them can be found in the [README](https://github.com/axcore/tartube#53-installation---linuxbsd).

**Comment by axcore** [comment]
Also, the correct installation command uses pip3, not pip.

`pip3 install tartube`

**Comment by GreatBigWhiteWorld** [comment]
> 

I get this new error:
```
note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for pycairo
      Failed to build pycairo
      ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects
      WARNING: There was an error checking the latest version of pip.
      [end of output]

```
Could you build a flatpak version of this app instead?

**Comment by axcore** [comment]
>I get this new error:

Looks like you need to install pycairo's dependencies. [This thread](https://stackoverflow.com/questions/70508775/error-could-not-build-wheels-for-pycairo-which-is-required-to-install-pyprojec) provides some suggestions. Try this one for OpenSUSE:

`sudo zypper install cairo-devel pkg-config python3-devel`

>Could you build a flatpak version of this app instead?

I tried that last year but gave up because of the woeful state of flatpak's documentation.

**Comment by GreatBigWhiteWorld** [comment]
Thanks. Had to install quite some packages to get it to work. To start, needed to install specifically python38-devel.
