### ISSUE TITLE
"Ran out of Input, file load/save has been disabled"

### ISSUE THREAD

**Issue by GibbyShadows** [axcore/tartube#545]
### What operating system are you using?
Windows 10

### What version of Tartube are you using?
v2.4.370

Since yesterday, I've been unable to open Tartube. Even after reinstalling, and then using the version of Tartube with FFMpeg, I get the following error:

> "Failed to load the Tartube database file:
> 
> Ran out of input
> 
> Because of the error, file load/save has been disabled"
> 

I've made sure my external harddrive isn't stuck on read only, there's no db.lock file within said area, and there's no errors, even when run from the terminal. I'm not sure what's happened, and I haven't found anyone else with these kinds of errors online or in the bug reports.

**Comment by spod479** [comment]
The database file (tartube.db) is corrupted. You need to replace it with the most recent backup, which you can find in the .backups folder.

**Comment by GibbyShadows** [comment]
After doing what you said, looks like that was the case! I assumed it was something else because of the way the error was told, I thought it had nothing to do with the database being corrupt. I'll close the issue, and I hope that it'll help other people that might get stuck with the same error!

**Comment by axcore** [comment]
I tweaked the window in v2.4.379, so the user sees a "try replacing the database file with a backup" message.
