### ISSUE TITLE
how to embed subtitles in the video and doesnt require a separate file

### ISSUE THREAD

**Issue by bheeshmpita** [axcore/tartube#546]
_What i am seeking?_
while downloading the video i want to download the subtitles associated with it (in priority order, original > auto generated) and subtitles gets embedded (if embedded means integrated and **_not_** imprinted to the video) into file and doesnt download a separate subtitle file.

_What i tried_

1. 
![ksnip_27052023-104952](https://github.com/axcore/tartube/assets/90836004/24cdeca9-4a40-448c-8315-e4921cb170cc)

2. 
![ksnip_27052023-105112](https://github.com/axcore/tartube/assets/90836004/6b2ae351-ff2d-4a92-ba79-12abbb8626d6)

3.
![ksnip_27052023-105132](https://github.com/axcore/tartube/assets/90836004/bd07572e-1951-4339-8380-aa032a2ed038)

With setting only options in pic1 and 2, i get a separate subtitle file
With all pic 1,2 and 3, i get subtitles embedded as well as separate file

How can i achieve the desired output?

**Comment by axcore** [comment]
>download the subtitles associated with it (in priority order, original > auto generated)

Is that possible using yt-dlp? I don't see anything about it in the [yt-dlp documentation](https://github.com/yt-dlp/yt-dlp).

> subtitles gets embedded and doesnt download a separate subtitle file.

The yt-dlp documentation suggests adding `--compat-options no-live-chat` (see [here](https://github.com/yt-dlp/yt-dlp#differences-in-default-behavior)), but again, I don't know anything about this. If you can find out how to achieve the desired results using yt-dlp, then I can tell you how to translate that into Tartube settings.
