### ISSUE TITLE
Tartube doesn't recognize upcoming livestreams when checking

### ISSUE THREAD

**Issue by WilmoSND** [axcore/tartube#552]
### What operating system are you using?
Windows 10

### What version of Tartube are you using?
v2.4.370

When checking a channel or playlist that contains an upcoming livestream, the output window gives:
` "ERROR: [youtube] <url>: This live event will begin in <time>`
and the livestream is not added in the channel video tab. 

Until recently, the same message appeared only as a warning instead, and the upcoming livestream was added to the videos tab with the normal download options.

**Comment by axcore** [comment]
>However, I seem to be having the same issues with your test channel:

Please show me all of the yellow text at the top of the Output tab, most of which has been cut out in your screenshot.

**Comment by WilmoSND** [comment]
It seems like it's picking up the ongoing live stream, but still won't show the upcoming streams.
I wondered if it might have been an RSS issue, but the upcoming stream info is present in the RSS feed.

![er4](https://github.com/axcore/tartube/assets/134983696/52316ec4-c04c-4e2e-8220-f34dc60d973d)
![e4](https://github.com/axcore/tartube/assets/134983696/168b11f5-1f2d-4fa1-b201-b2ef7d096597)

**Comment by axcore** [comment]
This may yet another occurence of the [unicode bug](https://github.com/axcore/tartube/issues/320). Try disabling non-ASCII characters: **Edit > General download options... > Files > Filesystem > Restrict filenames to ASCII characters**.

**Comment by Grecklock** [comment]
Gave it a shot, still not working unfortunately. Just tried it on Ubuntu as well and upcoming livestreams were detected correctly, so probably an issue with Windows somewhere. 

After disabling non-ASCII characters, it still will detect a currently broadcasting livestream just fine, but doesn't show the upcoming ones.

**Comment by WilmoSND** [comment]
Gave it a shot, still won't work unfortunately. I tried it on Ubuntu as well, and the upcoming livestreams were detected correctly- so probably an issue with Windows somewhere.

After disabling non-ASCII characters, tartube still detects any currently broadcasting livestreams, but doesn't show the upcoming ones.

**Comment by axcore** [comment]
I am closing this issue, because the probably cause (#320) has been fixed in v2.5.0. 

If you experience the same problem, feel free to re-open the issue.
