### ISSUE TITLE
Why Tartube no longer saves livestreams under their names?

### ISSUE THREAD

**Issue by 1chan-level-journalist** [axcore/tartube#553]
For some reason any time I try to download a livestream it gets a name "livestream_1" instead of what it was called. It started doing that after I updated Tartube to the newest version. 
Here's what the window looks like:
![1](https://github.com/axcore/tartube/assets/16210758/d77e73dc-0fd0-4c7b-9eba-4c6d46df252e)

EDIT: After it finished downloading the stream it shows this error:
![2](https://github.com/axcore/tartube/assets/16210758/60ec5e1f-aa7e-4632-a5b9-f33c443397af)

Also, when I try downloading the stream after it already started, it no longer downloads the segments that were streamed before I started downloading the stream. It now only downloads the stream from the moment I started downloading, ignoring the segment I missed.

**Comment by axcore** [comment]
Tartube uses one of three methods to download livestreams; you don't mention which one you have selected. The options are in Edit > System preferences... > Operations > Livestreams.

![livestreams](https://github.com/axcore/tartube/assets/37951926/6b399c99-4a97-431e-b7f9-18243c70cfcc)

The default option is `.m3u manifest`. If that is not working as expected, you can try `streamlink`. Streamlink must first be installed on your system, you can do that from Tartube's menu (Operations > Install streamlink).

Failing that, try downloading a stream and, when it fails, show me the output generated in Tartube's Output tab.

**Comment by 1chan-level-journalist** [comment]
I never changed the option from the default.
It looks like the issue is that there are differences in how older and new versions download livestreams.
For example, here's what the output looks like in version 2.4.165:
![1](https://github.com/axcore/tartube/assets/16210758/da5996cd-0b1a-4e9c-bc66-77e0c5b44eea)
And here's what it looks like in 2.4.370:
![2](https://github.com/axcore/tartube/assets/16210758/164418ad-8cdd-4af7-87f1-058e6296098f)
`.m3u manifest` was selected in both cases.
Is there a way to make it download livestreams how it did in the older versions? Selecting `yt-dlp` makes the download freeze with `Tartube is starting the livestream download (yt-dlp)...` in the output

**Comment by axcore** [comment]
I checked the code for downloading livestreams in versions 2.4.165 and 2.4.370; they appear to be almost identical.

I tested downloading a livestream with both versions, first checking that the `.m3u manifest` option is selected. The output for 2.4.165 does not resemble your screenshot:

![livestest1](https://github.com/axcore/tartube/assets/37951926/9f594f3b-9e8e-4ff4-ad7d-dd5fcee94a56)

Here's the output for 2.4.370, which looks to be almost the same:

![livetest2](https://github.com/axcore/tartube/assets/37951926/bb7edd1b-10b8-4189-9de1-91a5da64547e)

I'm guessing that for your first screenshot, the `yt-dlp (not recommended)` setting was enabled.

**Comment by axcore** [comment]
>For some reason any time I try to download a livestream it gets a name "livestream_1" instead of what it was called

I haven't tested this specific problem yet, as a livestream download typically takes several  hours and I haven't been at my desk for long enough to do it.

>it no longer downloads the segments that were streamed before I started downloading the stream

This is a known issue for downloading livestreams. yt-dlp provides the option `--live-from-start,` but it is marked as "experimental", which is why Tartube doesn't select it automatically. You can try enabling it: **Edit > General download options... > Downloads > Live > Download livestreams from start**

**Comment by axcore** [comment]
Are you sure you are editing the right set of options? Depending on your setup, one set of options may apply to the Videos tab, and a different set may apply to the Classic Mode tab. (That would explain why you are changing settings, but nothing is happening.)

![options](https://github.com/axcore/tartube/assets/37951926/e0129416-67a8-459e-9e0d-069aa9e27c71)

**Comment by axcore** [comment]
Closed for inactivity.
