### ISSUE TITLE
Using "Ignore the last # characters" setting causes TypeError Exception (Slice indices must be integers or None or have an __index__ method)

### ISSUE THREAD

**Issue by BlueBull010** [axcore/tartube#557]
### **What operating system are you using?**
Happens on Windows 10, Windows Server 2022 and in a Tartube docker container (that last one is not supported, I know)

### **What versions are you using?**
Tartube: v2.4.370
Yt-dlp: v2023.03.04 stable
Python: v3.10.10
Ffmpeg: v5.1.2 
Ffprobe: v5.1.2
Windows: Windows 10 Pro v22H2

Hello

After moving to a new server to host Tartube on, I have a few videos in my library that refuse to match with their respective youtube video when I do a check + refresh. 95% of my previously downloaded videos do match without issue. I use the filename format "Title + Quality" and had noticed that for the videos that didn't match, the filename on disk ends in, for example "-1440p" and Tartube shows that the file it wants to create from the same video ends in, again for example "-2160p". This is strange because those youtube videos always have had a 1440p version and still do. I have 1440p  set  as primary download format, it should not try to download the 2160p version if 1440p exists and should just recognize the file I have already downloaded

So, I thought I'd use the function "Ignore the last # characters" to have it ignore the last part of the filename where it says "-1440p" or "-2160p" so it matches those videos correctly. However this leads to the error described in the title and found below, after which the check just keeps running without ever completing and the output tab stops too, so nothing is happening even though the check is shown to be running. If I remove that setting, everything works except for some videos not matching. 

The below is the system command which is executed, below that the full error message and below that is the output on the terminal. I have also attached my (almost empty) database all the way at the end, in case that helps. You should remove the "REMOVETHIS.TXT" at the end as Github blocks .db uploads. I am running Tartube in windows 10 but I have received the exact same error in windows server and in a docker container. I will provide any more information you need, just tell me what you need. Also, could you point me to the location of the log file? Because I can't seem to copy the error message found in Tartube's "Errors/Warnings" tab so at the moment I only have a screenshot, which of course is not ideal

Cheers!

**"Ignore last # characters" setting**
![image](https://github.com/axcore/tartube/assets/61655638/45dde5b4-d70b-45e7-8331-075e5631c4b8)

**Full system command**
`yt-dlp --newline -i --hls-prefer-ffmpeg --write-description --write-info-json --cookies C:/Tartube/SymLink/Youtube Content/cookies.txt --write-thumbnail -f bestvideo[height<=?1440][fps<=?60]+bestaudio/best[height<=?1440] --add-metadata --concurrent-fragments 4 --windows-filenames --write-playlist-metafiles --no-cookies --output C:/Tartube/SymLink/Youtube Content/Car Channel Videos/Remove Before Race/%(title)s-%(height)sp.%(ext)s --download-archive C:/Tartube/SymLink/Youtube Content/Car Channel Videos/Remove Before Race/ytdl-archive.txt --verbose https://www.youtube.com/@RemoveBeforeRace/videos`

**Error message screenshot (will provide text version if you tell me how)**
![image](https://github.com/axcore/tartube/assets/61655638/00a257a7-5e58-4622-bd36-e1ac06b00f00)

**Terminal output**

> yt-dlp --newline -i --hls-prefer-ffmpeg --write-description --write-info-json --cookies C:/Tartube/SymLink/Youtube Content/cookies.txt --write-thumbnail --add-metadata --concurrent-fragments 4 --windows-filenames --write-playlist-metafiles --no-cookies --output C:/Tartube/SymLink/Youtube Content/Car Channel Videos/Remove Before Race/%(title)s-%(height)sp.%(ext)s --dump-json --download-archive C:/Tartube/SymLink/Youtube Content/Car Channel Videos/Remove Before Race/ytdl-archive.txt --verbose https://www.youtube.com/@RemoveBeforeRace/videos
> [debug] Command-line config: ['--newline', '-i', '--hls-prefer-ffmpeg', '--write-description', '--write-info-json', '--cookies', 'C:/Tartube/SymLink/Youtube Content/cookies.txt', '--write-thumbnail', '--add-metadata', '--concurrent-fragments', '4', '--windows-filenames', '--write-playlist-metafiles', '--no-cookies', '--output', 'C:/Tartube/SymLink/Youtube Content/Car Channel Videos/Remove Before Race/%(title)s-%(height)sp.%(ext)s', '--dump-json', '--download-archive', 'C:/Tartube/SymLink/Youtube Content/Car Channel Videos/Remove Before Race/ytdl-archive.txt', '--verbose', 'https://www.youtube.com/@RemoveBeforeRace/videos']
> [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No ANSI), error cp1252 (No ANSI), screen cp1252 (No ANSI)
> [debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
> [debug] Python 3.10.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 3.0.8 7 Feb 2023)
> [debug] Optional libraries: certifi-2022.12.07, no_Cryptodome-None, sqlite3-2.6.0
> [debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
> [debug] Proxy map: ()
> [debug] Loaded 1786 extractors
> [debug] Loading archive file 'C:/Tartube/SymLink/Youtube Content/Car Channel Videos/Remove Before Race/ytdl-archive.txt'
> [youtube:tab] @RemoveBeforeRace/videos: Downloading webpage
> [youtube:tab] Extracting URL: https://www.youtube.com/@RemoveBeforeRace/videos
> [debug] [youtube:tab] Selected tab: 'videos' (videos), Requested tab: 'videos'
> [download] Downloading playlist: Remove Before Race - Videos
> [youtube:tab] UCrujKGZ0YHwxMhN2-OwleRQ page 1: Downloading API JSON
> [youtube:tab] UCrujKGZ0YHwxMhN2-OwleRQ page 2: Downloading API JSON
> [youtube:tab] UCrujKGZ0YHwxMhN2-OwleRQ page 3: Downloading API JSON
> [youtube:tab] UCrujKGZ0YHwxMhN2-OwleRQ page 4: Downloading API JSON
> [youtube:tab] UCrujKGZ0YHwxMhN2-OwleRQ page 5: Downloading API JSON
> [youtube:tab] UCrujKGZ0YHwxMhN2-OwleRQ page 6: Downloading API JSON
> [youtube:tab] UCrujKGZ0YHwxMhN2-OwleRQ page 7: Downloading API JSON
> [youtube:tab] UCrujKGZ0YHwxMhN2-OwleRQ page 8: Downloading API JSON
> [download] Downloading item 1 of 265
> [youtube:tab] Playlist Remove Before Race - Videos: Downloading 265 items of 265
> [youtube] Extracting URL: https://www.youtube.com/watch?v=c8eZTusHZoE
> [youtube] c8eZTusHZoE: Downloading webpage
> [youtube] c8eZTusHZoE: Downloading android player API JSON
> [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
> [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
> [debug] Default format spec: bestvideo*+bestaudio/best
> [info] c8eZTusHZoE: Downloading 1 format(s): 313+251
> [download] Downloading item 2 of 265
> [youtube] Extracting URL: https://www.youtube.com/watch?v=nh0DhrTn7W0
> [youtube] nh0DhrTn7W0: Downloading webpage

**Comment by axcore** [comment]
>Also, could you point me to the location of the log file?

No logfile is written unless you enable that setting, which you can do in Edit > System preferences... > Output > Downloader log.

**Comment by BlueBull010** [comment]
Thank you for your reply. I assume you mean it should be "child_nickname", not "child_nickame"? I'll wait for feedback before I try it out. By the way, I have managed to now also trigger it with the "Ignore the last # characters" setting disabled. Previously, disabling that setting would make the error disappear but after uninstalling, reinstalling and importing channels & playlists plus download settings, it now occurs every time I try to check that channel

**Comment by axcore** [comment]
Yes, `child_nickname`.

**Comment by BlueBull010** [comment]
Still the same error
![image](https://github.com/axcore/tartube/assets/61655638/f7b28bdd-359a-4c64-9ced-6504f9d66cc1)
With that line edited
![image](https://github.com/axcore/tartube/assets/61655638/b2736c93-2410-4d35-a607-d41d7dc52edf)

**Comment by axcore** [comment]
Can you please insert some debug statements into the same function. 

Note that there must be exactly 8 space characters at the beginning of each line (because LOL Python).

```
        print(method)
        print(first)
        print(ignore)
        print(test_name)
```

![lolpython](https://github.com/axcore/tartube/assets/37951926/3e6706c3-0395-408a-a6c8-9ea996415136)

The output will only be visible if you're running Tartube in a terminal window. Not sure how that works in Docker; if you can't work it out, I'll write something more elegant.

**Comment by BlueBull010** [comment]
Alright, so I assume I did something wrong, so I might need a bit of help. This is what I did to open Tartube in a terminal, which I don't think is right. I am running Tartube in windows at the moment by the way. It was installed with the installer that includes ffmpeg but the installer without ffmpeg also had this error
![image](https://github.com/axcore/tartube/assets/61655638/a4214d09-fb62-4e01-8c0b-f0a0ffb119ab)

And this is what I got as output. The reason I think I did something wrong is because I do not see the output of those print statements at first glance. That said, I do work in IT but I'm not a developer (very bad at it actually) so I might be overlooking them 
![image](https://github.com/axcore/tartube/assets/61655638/7d38048c-6099-4457-80ba-53f03ccc7bca)

**Comment by BlueBull010** [comment]
Thank you for the update. However, even after applying it I still have the same issue with the same error. I noticed that it always happens at the same video on that channel and looking at the output of the console, it appears to be this video
https://www.youtube.com/watch?v=sMSadvz2uV4(url)
With title: "Batman’s Mercedes VISION GT!! As Seen in Justice League!"

It happens both when using the naming format "Title + Quality" and the following custom naming format
`[%(upload_date>%Y.%m.%d)s].[%(uploader_id)s][%(title)s][%(height)sp].%(ext)s`

It happens on some other channels too, if you want I can try a bit and see which videos it has the same issue with, as soon as I have some time

Update
![image](https://github.com/axcore/tartube/assets/61655638/f125fe7f-4f24-4f0d-a210-54f5cc469d5f)

This is the console output with the naming format "Title + Quality". Note that the video mentioned in the last line "E-Class “ALL TERRAIN” - Strange but Impressive!!-1080p", is actually still properly checked and seems to be properly added to the database as far as I can see. So, the issue is I think with the video right after it, which I have linked above. At least I think this is the case, unless there is a still a step after adding a video to the database which makes it so that it can be added to the database but on that last step still fail and produce this error. In that case it can potentially also be an issue with the last video in the console output below (link: https://www.youtube.com/watch?v=kg3TIeKDtAE)

> [Remove Before Race] <Simulated download of: 'Unveil： BMW M2 CSL Hommage!! by ROK Studio-1080p'>
> [download] Downloading item 242 of 265
> [youtube] Extracting URL: https://www.youtube.com/watch?v=kg3TIeKDtAE
> [youtube] kg3TIeKDtAE: Downloading webpage
> [youtube] kg3TIeKDtAE: Downloading android player API JSON
> [debug] Loading youtube-nsig.8c7583ff from cache
> WARNING: [youtube] kg3TIeKDtAE: nsig extraction failed: You may experience throttling for some formats
> [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
> [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
> [debug] Default format spec: bestvideo*+bestaudio/best
> [info] kg3TIeKDtAE: Downloading 1 format(s): 303+251
> [Remove Before Race] <Simulated download of: 'E-Class “ALL TERRAIN” - Strange but Impressive!!-1080p'>
> 

And this is the console output with the custom naming format

>  [download] Downloading item 242 of 265
> [youtube] Extracting URL: https://www.youtube.com/watch?v=kg3TIeKDtAE
> [youtube] kg3TIeKDtAE: Downloading webpage
> [youtube] kg3TIeKDtAE: Downloading android player API JSON
> [debug] Loading youtube-nsig.8c7583ff from cache
> WARNING: [youtube] kg3TIeKDtAE: nsig extraction failed: You may experience throttling for some formats
> [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
> [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
> [debug] Default format spec: bestvideo*+bestaudio/best
> [info] kg3TIeKDtAE: Downloading 1 format(s): 303+251
> [Remove Before Race] <Simulated download of: '[2017.11.23].[@RemoveBeforeRace]E-Class “ALL TERRAIN” - Strange but Impressive!![1080p]'>

This is the error message
![image](https://github.com/axcore/tartube/assets/61655638/aef63c6e-4714-4521-9226-27598d07469c)

**Comment by axcore** [comment]
I tested both videos on both Linux and MS Windows, but couldn't reproduce your error. However, in v2.4.392 I have amended the log-writing code to make it a little more robust. You can test it for yourself and tell me whether it resolves the problem.

v2.4.392 is only uploaded to Github/pypi. You can update your MS Windows installation just by downloading the new source code and using it to replace the old source code, as described [here](https://github.com/axcore/tartube#72-update-tartube-on-ms-windows).

If this doesn't solve your problem, feel free to open a new issue so I don't forget to reply to you.

**Comment by BlueBull010** [comment]
Sorry for only now replying, I've been away for a few days. That new version has resolved the issue! I now still do get (yet another) error message but it is not an uncaught exception and it doesn't interrupt the download process like the above errors did. I think this error is normal and doesn't have anything to do with Tartube. Thank you! You are awesome

**Comment by axcore** [comment]
If you feel like posting a screenshot of the new error, feel free. Otherwise, happy downloading :)
