### ISSUE TITLE
Copy function for errors tab

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#559]
Even on the latest version the drag n drop of errors has never worked for me under Windows 10.

Some of the errors I can copy from the python shell, but others like the built in tartube errors don't appear there.

It'd be great to be able to ctrl+c or right click and copy to have the selected items in the errors tab put into the clipboard.

**Comment by axcore** [comment]
Nothing I can do about the drag-and-drop problems on MS Windows, but in v2.4.392 I have added a "copy to clipboard" button which should do what you want.

As usual, the new source code is only uploaded to Github/pypi, you can update your Windows installation as described [here](https://github.com/axcore/tartube#72-update-tartube-on-ms-windows).
