### ISSUE TITLE
Classic Mode one-click download duplicate causes instant crash without error message

### ISSUE THREAD

**Issue by BagronkeN** [axcore/tartube#566]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Windows 10

### What version of Tartube are you using?
2.4.386

Hi,

I've run into this error in multiple versions of Tartube, and thought I should report it since it's still happening after a clean reinstall of the latest version.

Can someone help check if they can replicate this?

How to replicate:

1. In Classic Mode, check "Enable one-click downloads" (via the button on the right)
2. Paste a Youtube link in the URL box
3. It should now automatically start downloading due to the options set in step 1
4. Paste the same Youtube link in the URL box again
5. Tartube will recognize that it's a duplicate and will **_not_** download it, and the link will remain in the URL box
6. Now try to erase the link in the URL box, i.e. select the link text and press backspace or delete. _(Or just activate the URL box and press delete or backspace.)_
7. Tartube crashes without any errors.

Please let me know if you cannot replicate this and if I can add any more info on my end, or if there are any settings that could affect this.

Thanks!

**Comment by axcore** [comment]
Confirmed, I'll put out a fix when I get the chance. In the meantime, try to avoid posting duplicate links ;)

**Comment by axcore** [comment]
Should be fixed in v2.4.407. I don't get the same crashes as you, so let me know if the fix doesn't completely resolve your problem.

The new code is uploaded only to Github/pypi. Windows users can update their installation as described [here](https://github.com/axcore/tartube#72-update-tartube-on-ms-windows).

**Comment by BagronkeN** [comment]
I did a script folder update, and I can confirm that pasting duplicates no longer crashes the client. Awesome work!
