### ISSUE TITLE
malware warning

### ISSUE THREAD

**Issue by gitihobo** [axcore/tartube#570]
Antivirus detected as malware install tartube with ffmpeg 2.4.386-64b

**Comment by axcore** [comment]
Most antivirus software will generate warnings from open-source projects, because most open-source project don't buy digital security certificates. Since you haven't included any useful details, such as the actual text of the warning, I'll go right ahead and close this issue.

**Comment by gitihobo** [comment]
none of the open source projects I download gives me warnings, threat name trojan.generickd.678682735 64bit.exe=>(NSIS o)=. zlib_nsis5755

**Comment by axcore** [comment]
Google says that trojan.generickd normally appears as a compromised PDF. The Tartube installer is about a hundred times larger than a typical PDF file, so I would guess that you are seeing a false positive. In any case, your options are these:

1. Try an earlier version of Tartube, and see if you get the same warning
2. Create your own Tartube installer from scratch, using the instructions provided 
3. Remove Tartube, and switch to a different GUI altogether; there are [several good ones available](https://www.reddit.com/r/youtubedl/wiki/info-guis/)

**Comment by gitihobo** [comment]
I really like tartube so I dont want to replace it but I contacted my antivirus support and Ill have more information soon! thank you

**Comment by gitihobo** [comment]
Antivirus company officially says its safe
