### ISSUE TITLE
README is missing tartube path for MacOS install to run executables by name in terminal

### ISSUE THREAD

**Issue by inkhalistan** [axcore/tartube#571]
To run tartube, ytdl, and ffmpeg on MacOS I entered the following in terminal:

echo "export PATH=\"`python3 -m site --user-base`/bin:\$PATH\"" >> ~/.zprofile

and to run the executables without restarting terminal, I also entered:

source ~/.zprofile

**Comment by axcore** [comment]
I have added that to the [README](https://github.com/axcore/tartube#523-troubleshooting-on-macos). I don't have a Mac so I can't do any testing; let me know if the change is not right.
