### ISSUE TITLE
tidy up problems

### ISSUE THREAD

**Issue by raafal** [axcore/tartube#574]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Ubuntu 22.04.2 LTS

### What version of Tartube are you using?
v2.4.386

###If your bug report is "I can't download this video", please provide a link to the video

all files (video, images, txt) for a given folder/channel reside in one folder

folder/channel actions/tidy up folder/channel

- move into separate folder (thumbs/meta) - operation completes quickly, but no new folders created, no files moved
- delete (thumbs/meta) - operation neither completes nor deletes any files, the app doesn't freeze but but all actions (file/save, check/dl, all folder/channel actions are ghosted), after exiting the app restarts with no error message

**Comment by axcore** [comment]
>move into separate folder (thumbs/meta) - operation completes quickly, but no new folders created, no files moved

Please give me the URL of a channel that doesn't work, so I can test it directly.

>delete (thumbs/meta) - operation neither completes nor deletes any files

You should be able to see an error message in the **Errors/Warnings** tab; please show me that message.
