### ISSUE TITLE
Show system command output format

### ISSUE THREAD

**Issue by mbnoimi** [axcore/tartube#576]
Current version doesn't output a correct system command because it's missing double quotes in many passed arguments as shown below.

May you please fix this issue?

### Command output
- Generated command (wrong)
```
/home/laptop/.local/bin/yt-dlp --newline -i --match-filter !is_live -r 200K -R 99 --hls-prefer-native --no-mtime --cookies /home/laptop/Downloads/youtube-dl/cookies.txt -x --audio-format m4a --audio-quality 0 --embed-thumbnail --fixup detect_or_warn --break-on-existing --write-link --embed-metadata --reject-title CANLI|saat|UZUN|live|radyo --output /home/laptop/Downloads/youtube-dl/downloads/Audio/Apocalyptica/%(title)s.%(ext)s --continue --match-filters !is_live --download-archive /home/laptop/Downloads/youtube-dl/downloads/Audio/Apocalyptica/ytdl-archive.txt https://www.youtube.com/c/apocalyptica/videos
```
- Corrected command
```
/home/laptop/.local/bin/yt-dlp --newline -i -r 200K -R 99 --hls-prefer-native --no-mtime --cookies "/home/laptop/Downloads/youtube-dl/cookies.txt" -x --audio-format m4a --audio-quality 0 --embed-thumbnail --fixup detect_or_warn --break-on-existing --write-link --embed-metadata --reject-title "CANLI|saat|UZUN|live|radyo" --output "/home/laptop/Downloads/youtube-dl/downloads/Audio/Apocalyptica/%(title)s.%(ext)s" --continue --download-archive "/home/laptop/Downloads/youtube-dl/downloads/Audio/Apocalyptica/ytdl-archive.txt" https://www.youtube.com/c/apocalyptica/videos
```

### What operating system are you using?
Linux Mint 21.2

### What version of Tartube are you using?
v2.4.407

**Comment by axcore** [comment]
Tartube does not send the whole command to the system; instead, it passes arguments to the system one at a time.  

Therefore, the quotes are not necessary. In fact, if we add the "missing" quotes, the command will not work at all.

**Comment by axcore** [comment]
>BTW, passing --match-filter !is_live shows this error

I tested it on [this video](https://www.youtube.com/watch?v=jNQXAC9IVRw), but I didn't see the same error. Can you give me a video URL that generates this error?

**Comment by mbnoimi** [comment]
> > BTW, passing --match-filter !is_live shows this error
> 
> I tested it on [this video](https://www.youtube.com/watch?v=jNQXAC9IVRw), but I didn't see the same error. Can you give me a video URL that generates this error?

```
/home/laptop/.local/bin/yt-dlp --newline -i --match-filter !is_live -r 200K -R 99 --hls-prefer-native --no-mtime --cookies /home/laptop/Downloads/youtube-dl/cookies.txt -x --audio-format m4a --audio-quality 0 --embed-thumbnail --fixup detect_or_warn --break-on-existing --write-link --embed-metadata --reject-title CANLI|saat|UZUN|live|radyo --output /home/laptop/Downloads/youtube-dl/downloads/Audio/Apocalyptica/%(title)s.%(ext)s --continue --match-filters !is_live --download-archive /home/laptop/Downloads/youtube-dl/downloads/Audio/Apocalyptica/ytdl-archive.txt https://www.youtube.com/c/apocalyptica/videos
```

**Comment by mbnoimi** [comment]
> Therefore, the "missing" quotes are not necessary. In fact, if we try to add them, yt-dlp will generate an error.

If you copied the generated system command and pasted it into the terminal you'll get many errors related to invalid command format!

**Comment by axcore** [comment]
I downloaded all 300 videos, but I didn't see the same error

![apoca](https://github.com/axcore/tartube/assets/37951926/ee689761-dcef-4c3c-a2eb-c87965dcc072)


>If you copied the generated system command and pasted it into the terminal you'll get many errors related to invalid command format!

I understand that, but if I add artificial quotes to the displayed text, then we are not seeing the actual system command, but an imaginary one.

**Comment by axcore** [comment]
Ok, I did not understand that your --match-filter problem only happens in the terminal window. 

![matchfilter](https://github.com/axcore/tartube/assets/37951926/30cd202c-6efa-4ee4-a76a-8056c81f336b)

I don't know why yt-dlp does that :)

**Comment by axcore** [comment]
About your first question:

Changing the Tartube code, so that it displays "..." in the Output tab, is not a simple task. It is probably a whole day or maybe two days of work.

**Comment by axcore** [comment]
I added quotes in v2.4.412. The updated code is not very sophisticated, but it will do what you want (most of the time).

**Comment by mbnoimi** [comment]
> I added quotes in v2.4.412. The updated code is not very sophisticated, but it will do what you want (most of the time).

Thank you. I'll test it soon
