### ISSUE TITLE
Warnings: "Video with no name" and other - yt-dlp

### ISSUE THREAD

**Issue by marekbujko** [axcore/tartube#579]
Hi. 

### What operating system are you using?
Ubuntu 20.04 LTS

### What version of Tartube are you using?
v2.4.412

### If your bug report is "I can't download this video", please provide a link to the video
I've been getting a warnings for a few days now about yt-dlp after download every video. Yt-dlp version is 2023.7.6.

Video: (video with no name)
WARNING: [youtube] unable to extract initial player response; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U

Video: (video with no name)
WARNING: [youtube] unable to extract yt initial data; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U

Video: (video with no name)
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.

**Comment by marekbujko** [comment]
https://github.com/yt-dlp/yt-dlp/issues/7594

**Comment by axcore** [comment]
Yes, anything marked `please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q=`is a yt-dlp problem. I'm sure it will be fixed quite soon.
