### ISSUE TITLE
Better handling of archive

### ISSUE THREAD

**Issue by tsk-2222** [axcore/tartube#580]
It would be a nice feature to add better handling of the ytdl-archive.txt file.

Tartube/ytdl does a great job of populating the archive.txt file in each download directory however this 'breaks' if you later manually move a video from one directory to another.  It would be great if the archive entry for that video could follow it's video into the new directory.

Additionally, perhaps the tidy function could (re)populate any archive.txt file depending on whether someone wants a single large file or individual archive files in each download directory (or both??)

PS. Thanks for this fine program. I use it a lot.

**Comment by axcore** [comment]
Sorry for the delay, somehow your question didn't get added to my to-do list.

What you ask for is not possible at the moment; lines in the archive file look like this:

`[youtube] VIDEO_ID`

Tartube's database stores the VIDEO_ID component, but not the [youtube] component.

In v2.4.429 I have added a new feature: when a YouTube video is moved to a new folder, the archive file in that folder is updated. It won't work for videos from other websites, only for YouTube videos. 

It isn't exactly what you wanted, but it should be an improvement.

**Comment by tsk-2222** [comment]
It works great but there's a slight bug.

Moving multiple files will populate the archive file as a single line with no cr/lf.

"youtube dQw4w9WgXcQyoutube xm3YgoEiEDc"

**Comment by axcore** [comment]
Whoops! I have uploaded a fix for that (to github only), and tested it. Sorry for the delay.
