### ISSUE TITLE
How to Add a Specific Resolution?

### ISSUE THREAD

**Issue by Jain2098** [axcore/tartube#582]
Sometime video of 480p is little different in like source like 486p. How can I add a 486p resolution and download it.
I get Error in those video: Requested format is not available. Use --list-formats for a list of available formats

**Comment by axcore** [comment]
In the Videos tab, right-click the video and select **Fetch > Available formats**

This will show a list of all available formats, with the format ID on the left.

![formats](https://github.com/axcore/tartube/assets/37951926/054e2f3a-5375-44ce-bf02-5a121860e78f)

If you wanted the last item in the list, number 244, then the yt-dlp command would be

yt-dlp -f 244 URL

In Tartube, you can put the **-f 244** part in the download options window.

![options](https://github.com/axcore/tartube/assets/37951926/50ae6a1c-010f-45b8-a9da-51ef60e416b2)
