### ISSUE TITLE
How do I download and embed a video's description?

### ISSUE THREAD

**Issue by strunberg** [axcore/tartube#583]
How do I download and embed a video's description?

All I get in the description area is the URL link to the video.

`-f bestvideo+bestaudio/best --xattrs 
--add-metadata --write-info-json --write-description --write-annotation --write-thumbnail
--no-check-certificate`

**Comment by axcore** [comment]
The [yt-dlp documentation](https://github.com/yt-dlp/yt-dlp) says that `--add-metadata`only works on mkv files. So, make sure you have selected that format in download options.

If you're asking "how do I add `-add-metadata` in Tartube", then you can add it directly in the download options window, in the **Additional download options** box. 

Also, in the same window, you can click the **Show advanced download options** button if it's visible. Then open the **Post-processing > General** tab, and select **Write metadata to the video file**.

**Comment by axcore** [comment]
Download a suitable video, then show me the yellow text at the top of the **Output** tab.

**Comment by strunberg** [comment]
`yt-dlp --newline -i --playlist-reverse --hls-prefer-native --cookies E:/videos/cookies.txt --write-sub --all-subs --recode-video mp4 --add-metadata --output E:/videos/video games/Video game fav/%(playlist_index)s- %(channel)s-  %(playlist)s- %(title)s.- %(upload_date)s- -f bestvideo+bestaudio/best --xattrs --add-metadata --write-info-json --write-description --write-annotation --write-thumbnail --no-check-certificate --download-archive E:/videos/video games/Video game fav/ytdl-archive.txt https://www.youtube.com/playlist?list=PLuCuz7lAz8pibDECojAvOAoJUwYTnC-qi`

**Comment by strunberg** [comment]
Is there any reason why video description is not being embeded other than the youtube URL link?

**Comment by axcore** [comment]
You need to remove --recode-video mp4 from your download options. When I remove it, metadata is embedded in the video.

![eveonline](https://github.com/axcore/tartube/assets/37951926/6a0dcb22-9885-4baa-b5de-f2fe5d0185d1)

**Comment by strunberg** [comment]
Sorry, but this is what I got still. 



![2023-08-24 11_00_08-Window](https://github.com/axcore/tartube/assets/6355904/1b9eb633-4d8f-4305-86e5-d3ca8e6b2b92)

**Comment by axcore** [comment]
I'm sorry, I don't have any ideas except to remove `--recode-video mp4`. You could try asking the same question at the [yt-dlp issues page](https://github.com/yt-dlp/yt-dlp/issues), since it does appear to be a yt-dlp problem.

**Comment by strunberg** [comment]
Where is the default download location for youtube-dl?

**Comment by strunberg** [comment]
> I'm sorry, I don't have any ideas except to remove `--recode-video mp4`. You could try asking the same question at the [yt-dlp issues page](https://github.com/yt-dlp/yt-dlp/issues), since it does appear to be a yt-dlp problem.

This is a working configuration. The correct description is now embedded.

`--embed-metadata --parse-metadata "description:(?s)(?P<meta_comment>.+)"

-f bestvideo+bestaudio/best --xattrs 
--add-metadata --write-info-json --write-description --write-annotation --write-thumbnail
--no-check-certificate`

**Comment by luk9a** [comment]
With yt-dlp I have always used this way: "--compat-options embed-metadata".
