### ISSUE TITLE
Let you skip videos in a playlist to download later if the file is too big.

### ISSUE THREAD

**Issue by strunberg** [axcore/tartube#584]
I have a 20gb file for a videogame video, I would like to skip it to move onto smaller file sized videos.

**Comment by axcore** [comment]
Here is the quickest way: before downloading the videos, check them (use the **Check all** button in the bottom-left corner of the videos tab).

Then you can select the videos you want to download by pressing CTRL + A. While holding the CTRL key, left-click any videos you **don't** want, which will de-select them.

Then right-click one of the selected videos, and select **Download videos**.

**Comment by axcore** [comment]
>Will tartube override any download format option that I put in 'advanced download options'?

Do you mean, in the Additional download options box? The opposite is the case, the contents of this box overrides everything else. So you could just do this:

![options](https://github.com/axcore/tartube/assets/37951926/c2b00254-dbbf-4346-8b6a-fc4c6b753116)

If you just want to set the maximum filesize (a good idea, I should have responded with it instead:

Edit > General download options...
Click the **Show advanced download options** button if it's visible
Open the **Downloads > Limits** tab
Set **Maximum file size for video downloads**, then click the OK button
