### ISSUE TITLE
bestvideo+bestaudio question

### ISSUE THREAD

**Issue by nnDropZz** [axcore/tartube#59]
Hello, i don't know if this the right place but i got a question.

i use Youtube-DLG and cant seem to get the following parameter to work:

`-f bestvideo[ext=mp4]+bestaudio[ext=m4a] --embed-thumbnail --embed-subs --all-subs`

I got the thumbnail and sub embedded working without the Parameter, but i cant get the  `bestvideo[ext=mp4]+bestaudio[ext=m4a]` part working.

Thanks for the help and great project btw.

**Comment by axcore** [comment]
Hi nnDropZz,

First thing - make sure FFmpeg and AtomicParsley are installed on your system. On Linux/BSD, you can install them using the software manager. On MS Windows, the installer includes AtomicParsley, so just click Operations > Install FFmpeg

Secondly, if parameters don't work as you expect, you can enter them directly. Click Edit > General download options, and add the options you want.

![myoptions](https://user-images.githubusercontent.com/37951926/75138707-c5d6ae80-56e2-11ea-866f-5447a6d09107.png)

When you download videos, you can click the Output tab to see which options were applied. 

If you don't want to download anything, you can right-click a video and select Downloads > Show system command. (Unfortunately this is broken in v1.5.007, but here is the output)

![myoptions2](https://user-images.githubusercontent.com/37951926/75138817-11895800-56e3-11ea-9dc8-f763330c7307.png)

Thirdly, what do you mean "I can't get the ... part working"? What are you expecting, and what do you actually get?

**Comment by axcore** [comment]
Closed for inactivity.
