### ISSUE TITLE
i do not understand how to move files

### ISSUE THREAD

**Issue by Xananax** [axcore/tartube#590]
I am probably misunderstanding how to do this.

I've downloaded several files; however, because I had not decided on a structure yet, many of them ended up in "Unsorted".

I'd like to sort them, but I see no way to move them. Dragging and dropping isn't working, and no right-click action or menu entry seems to do what I need it to do.

The README says I can move files while Tartube is closed, but I'm worried I'll lose the metadata this way. Please advise?

**Comment by Xananax** [comment]
Moving files work. I do not understand why I wasn't able to drag and drop them before. Maybe selecting all files was selecting something broken, or maybe it was a PEBCAK

**Comment by axcore** [comment]
Dragging videos from the Unsorted Videos folder to another folder doesn't seem to be working reliably, so I'll look into that when I have a chance.

**Comment by axcore** [comment]
On my system, Tartube has incorrectly registered a .webm video as a .3gp video. Therefore, when I try to move the non-existent file, nothing happens.

Perhaps you can tell me whether that's your problem, too. Right-click the video, and select **Show video > Properties**, then compare it to the actual file extension.

![filext](https://github.com/axcore/tartube/assets/37951926/0abd5f64-1942-4d62-b4fb-2091d664b785)

**Comment by axcore** [comment]
Closed for inactivity.
