### ISSUE TITLE
Livestream query

### ISSUE THREAD

**Issue by soopercow** [axcore/tartube#591]
Good evening

I've been using Tartube for a while and love it. I recently tried to download a livestream and I need some help. It started downloading as a normal video would but once the hour so I wanted to rewatch later was over I was a bit confused. The Twitch channel is one pretty much 24/7 so I didn't want to record hours of content. I figured I could just telling tartube to stop but this delete the video.

Can you assist for the future please?

**Comment by axcore** [comment]
I don't know the answer to your specific question of Twitch downloads, but have you tried downloading with streamlink?

**Edit > System preferences... > Operations > Livestreams**, then click the **Download using... streamlink** button
