### ISSUE TITLE
Doesn't start - Unable to locate package cairo

### ISSUE THREAD

**Issue by cipricus** [axcore/tartube#592]
Thanks for taking the time to submit a bug report! Please include the following information:

Just installed python3-tartube_2.4.412.deb in Kubuntu23.10, the launcher doesn't work. In terminal:

```
~$ tartube
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 176, in require_foreign
    _gi.require_foreign(namespace, symbol)
ModuleNotFoundError: No module named 'gi._gi_cairo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/_backend_gtk.py", line 22, in <module>
    gi.require_foreign("cairo")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 178, in require_foreign
    raise ImportError(str(e))
ImportError: No module named 'gi._gi_cairo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/tartube", line 42, in <module>
    import mainapp
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 96, in <module>
    import config
  File "/usr/lib/python3/dist-packages/tartube/config.py", line 56, in <module>
    from matplotlib.backends.backend_gtk3agg import FigureCanvasGTK3Agg
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 4, in <module>
    from . import backend_agg, backend_gtk3
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_gtk3.py", line 29, in <module>
    from . import _backend_gtk
  File "/usr/lib/python3/dist-packages/matplotlib/backends/_backend_gtk.py", line 24, in <module>
    raise ImportError("Gtk-based backends require cairo") from e
ImportError: Gtk-based backends require cairo
cip@cip-MacBookAir:~$ sudo apt install cairo
[sudo] password for cip: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package cairo
```

**Comment by axcore** [comment]
It might be a day or two before I have the opportunity to test Kubuntu specifically, in the mean time you can try this:

1. Other methods of installation are available, if the .deb package isn't working. And installation is not actually necessary, you should be able to run the source code directly. (See https://github.com/axcore/tartube for a full description of these methods).

2. The dependency you're missing _might_ be pycairo, so try this:

`pip3 install pycairo`

**Comment by cipricus** [comment]
> `pip3 install pycairo`

Thank you for the quick reply. I have big problems installing pip in k/ubuntu, a swell as pipx, even in virtual environment, and the "portable" use from source also complains about cairo. I'll see what happens.

**Comment by cipricus** [comment]
I will close it myself, not really a bug.

**Comment by cipricus** [comment]
> sudo apt-get install libcairo2-dev

just for reference: the command works in Kubuntu, and it also installs `libbrotli-dev libbz2-dev libfontconfig-dev libfreetype-dev libice-dev libpixman-1-dev libpng-dev libpng-tools libsm-dev libxcb-render0-dev libxcb-shm0-dev libxrender-dev` but that changes nothing, not even after restart.

**Comment by axcore** [comment]
Noted. If it were an Ubuntu-wide problem, then it should be affecting me too, since Tartube is developed on Linux Mint. 

I haven't spent much time playing with python virtual environments, so I have no more suggestions. I would use `pip3 install` rather than `pip install`, but I can no longer remember whether it's just a habit or something I started doing for a reason. 

If you find a solution to get cairo correctly installed, do let me know, so I can think about whether the .deb package needs to be modified.
