### ISSUE TITLE
FFmpeg Options > ProRes convert?

### ISSUE THREAD

**Issue by gordingus** [axcore/tartube#593]
Tartube is such a great tool! Very feature-rich in a way that I haven't found yet. I'm curious if there's a way to tell FFmpeg to convert to ProRes 422 within its options? I see H264, Gif, Video clip,... etc. in the Output section of the Settings tab in the FFmpeg Options window. 

What I'd like is an option to convert to ProRes .mov, which should be possible with FFmpeg [according to this page in their documentation](https://trac.ffmpeg.org/wiki/Encode/VFX).

Alternatively, is there a way to custom edit the system command? Not to add extra using the text box above, but alter the command below? 

I know there are alternate ways to convert to 422. Currently I take Tartube's outputs and run them through Shutter Encoder to get them all into ProRes 422. But I downloaded Tartube to fit the whole pipeline into one solution. And it's so close! The functionality is there, I just don't see the option (maybe I'm missing something though!)

**Comment by axcore** [comment]
>I'm curious if there's a way to tell FFmpeg to convert to ProRes 422 within its options?

**Comment by axcore** [comment]
Hopefully you've noticed that, in Tartube's **Videos** tab, you can select multiple videos, then right-click to open the FFmpeg options window, and the operation you set up will be performed on all the selected videos.

You might also note that yt-dlp also behaves like FFmpeg. If you specify `--something X --something Y,` then `--something X` is ignored - _with a few exceptions_, one of which happens to be `--postprocessor-args`.

**Comment by gordingus** [comment]
Yes, I love the option to batch process through FFmpeg! One thing I've run into after a few videos is that .webm files seem to error when I try processing them. That may be where I poke around in the postproccesor args (unless you know a reason they aren't friendly with ffmpeg)!

**Comment by axcore** [comment]
No idea about that, I'm afraid. Try processing a specified set of videos from a specified URL, so that I can try converting the same set of videos.
