### ISSUE TITLE
how to download video with a particular format '-f 22'

### ISSUE THREAD

**Issue by bheeshmpita** [axcore/tartube#595]
I genarally need to download the videos at 720p so when i select the resolution to 720p in tartube classic mode section it downloads the video at 720p with separate audio and then merges them.
But for this use case i think downloading directly with format id -f 22 will be helpful that would save time and system resources.
How can i achieve this?

**Comment by axcore** [comment]
In the Classic Mode tab, set the **Format** to **Default**.

Then, click the menu button in the top-right corner, and select **Edit download options...**

In the new window, click the **Formats** tab. Scroll down the list until you find the line containing **22**, which in this case is **mp4 [720p] <22>**. Click the **Add format** button and then click **OK** to close the window.

**Comment by bheeshmpita** [comment]
i followed the above steps but it still downloads the other way and i did confirm that format -f 22 was available for that particular video.

**Comment by bheeshmpita** [comment]
@axcore for downloading live youtube videos (after they have completed) the format is different and generally dont works (-f 22). Can you help me how to add next entry in the preferred format list for such scenarios with the restriction that the video has h.264 codec and resolution =< 720p

**Comment by axcore** [comment]
Sorry, I don't know the answer to that exact question. The codec can be selected like this:

-S "codec:h264"

So click **Edit > General download options...** , and type it in the **Additional download options** box.

![example](https://github.com/axcore/tartube/assets/37951926/80c54c78-a286-4045-b721-5c0044c37cf7)
