### ISSUE TITLE
doesn't install on fedora 39

### ISSUE THREAD

**Issue by i300220** [axcore/tartube#596]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Fedora 39

### What version of Tartube are you using?
tartube-2.4.386.rpm

Get this error installing with the newly released Fedora 39.  Installed OK with Fedora 38.  But the upgrade process removed Tartube, for incompatibility.

sudo dnf install Downloads/tartube-2.4.386.rpm
[sudo] password for ********: 
Last metadata expiration check: 0:04:08 ago on Tue 07 Nov 2023 12:25:49 PM.
Error: 
 Problem: conflicting requests
  - nothing provides python(abi) = 3.11 needed by tartube-2.4.386-1.noarch from @commandline
(try to add '--skip-broken' to skip uninstallable packages)

**Comment by axcore** [comment]
Step 1 - try the current release (2.4.412) rather than an older one.

**Comment by anaob** [comment]
Just to confirm the repos .rpm download does not install on recently upgraded Fedora 39 (which installs python 3.12).

Last metadata expiration check: 0:00:06 ago on Thu 09 Nov 2023 11:01:10 GMT.
Error: 
 Problem: conflicting requests
  - nothing provides python(abi) = 3.11 needed by tartube-2.4.412-1.noarch from @commandline
(try to add '--skip-broken' to skip uninstallable packages)

An earlier release of tartube is still installed however but now gives

Traceback (most recent call last):
  File "/home/******/.local/bin/tartube", line 42, in <module>
    import mainapp
ModuleNotFoundError: No module named 'mainapp'

Happy to help diagnose

**Comment by i300220** [comment]
So, sorry, but I'm out of the equation for at least 3 months for testing.

I downgraded to Fedora 38.  Don't plan to re-upgrade for 3 months.

There was the possibility to downgrading python to 3.11 on 39 or reinstall from 38, but when I wanted to use Kodi, which I do on a daily basis, it crashed repeteadly.  Kodi too relies heavily on python, and I had the latest Kodi from the fc39 repo.  

That was too much for me.  Besides I haven't seen any significant improvement in Fedora 39 with Cinnamon over 38, only bugs.  

Even the dreaded Timeshift was unable to bring back the system to a bootable state; never was, as a matter of fact, each and every time I performed a restore operation.  It stated that there was some perms/ownership errors but was way to dumb to tell me which one for I can manually fix my system. What this piece of garbage named Timescript does outside of Mint is beyond my comprehension.  Logs aren't humanly interpretable.

I wish you best.  Tartube is the best application for yt-dlp on Linux.  Can't tell on Windows, I'm still with Windows 7 and plan never to upgrade in this life or any future one.  Done with Windows, forever.  Hence this fresh install of Fedora 38 which is only 20 days old.

**Comment by i300220** [comment]
Hi again,

I installed Fedora 39 on a USB key to make some tests.

I managed to copy files from /usr/lib/python3.11/site-packages/tartube to /usr/lib/python3.12/site-packages/tartube and edited those giving warnings.  Now one can run tartube on a python 3.12 equiped computer.  Not thouroughly tested, but it downloaded what I wanted.  All you need is this /usr/lib/python3.12/site-packages/tartube directory and the files within.

In the attachment, you'll find the diff file for the current stable release, plus extra warnings that I haven't been able yet to get a solution.

[tartube-py-3.12.tar.gz](https://github.com/axcore/tartube/files/13357643/tartube-py-3.12.tar.gz)

Best!

**Comment by axcore** [comment]
Fixed in v2.4.429.
