### ISSUE TITLE
Already Downloaded?

### ISSUE THREAD

**Issue by ShawnTexas** [axcore/tartube#597]
I've been using Tartube for years now and I'm wondering when will we get an update that allows duplicate videos? A lot of youtube channels and other websites have videos with the same name and no matter what I try I can't use the program to bulk download which is annoying.Most programs just add a (1) next to a video with the same title.Anyway it's the best program out there so good job to the creators!!

**Comment by axcore** [comment]
yt-dlp handles this situation with file output templates, see [Tartube documentation](https://github.com/axcore/tartube#712-duplicate-video-names) and [yt-dlp documentation](https://github.com/yt-dlp/yt-dlp#output-template).

tl;dr: in Tartube's main menu, select Edit > General download options... > Files. In the dropdown box select Title + ID, then click OK to close the window.

**Comment by ShawnTexas** [comment]
Thanks for the quick reply but it doesn't work.It only downloads 1 file and it says that the file was already downloaded.Are you using other custom settings?

**Comment by axcore** [comment]
Try the download, then show me a screenshot of the Output tab, with the yellow text visible at the top.

**Comment by ShawnTexas** [comment]
I'll try to get  a screenshot when I get back in town.The duplicate download problem has been an issue for ever with no resolution.It's not a big deal to me but it's annoying when downloading a playlist or using bulk download.

[https://www.reddit.com/r/youtubedl/comments/gdepwn/how_to_download_videos_with_the_same_name_without/](url)
[https://www.reddit.com/r/youtubedl/comments/wsq973/issues_with_songs_that_have_the_same_name/](url)
[https://www.reddit.com/r/youtubedl/comments/gdepwn/how_to_download_videos_with_the_same_name_without/](url)

**Comment by axcore** [comment]
If you can't get a screenshot, then just copy-paste the yellow text.

**Comment by axcore** [comment]
Closed for inactivity.
