### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by i300220** [axcore/tartube#599]
Do not install tartube-2.4.429.rpm on systems with Python 3.11. It won't install anyways. In short, if you don't have python 3.12 on your system, skip this one.

dnf install /home/******/Downloads/tartube-2.4.429.rpm
Last metadata expiration check: 0:11:38 ago on Tue 21 Nov 2023 03:27:53 AM.
Error:
Problem: conflicting requests

nothing provides python(abi) = 3.12 needed by tartube-2.4.429-1.noarch from @commandline
System is Fedora 38, yes I rolled back from F39. I use F39 only for compatibility tests for Kodi.
Second system is Debian 12.2 (with Python 3.11 too)

**Comment by axcore** [comment]
Any RPM package requires a specific version of Python, no?

Forgive me, I don't use Fedora so I'm not up to date with these things.

**Comment by i300220** [comment]
Hi,

Looks like this with Fedora, unlike Debian where dependency could be the libpython3 >= 3.7 package.  So if there is no incompatibility between python versions, your tartube could very well install on Debian 12 (Python3.11), 11 (Python 3.9) and 10 (Python3.7) , even Debian unstable (still python 3.11).

There is no libpython3 package in Fedora.  Therefore you need to build a different tartube for each release of Fedora.
Fedora 38 is shipped with Python 3.11 and Fedora 39 with Python 3.12.  One can always install python 3.11 in addition to 3.12 on Fedora 39 but would only get the base.  A lot of libraries could be missing and not available.

Dependencies
4000+ packages depend on Python 3 and ~3900 packages need rebuilding when Python is upgraded. See scope section.

(From
https://fedoraproject.org/wiki/Changes/Python3.11#Dependencies
https://fedoraproject.org/wiki/Changes/Python3.12#Dependencies
)

Hope that helps!
