### ISSUE TITLE
Tartube could download .m4a separately, but doesn't

### ISSUE THREAD

**Issue by axcore** [axcore/tartube#60]
Following on from [here](https://github.com/axcore/tartube/issues/38#issuecomment-592211864) and [here](https://github.com/MrS0m30n3/youtube-dl-gui/issues/430#issuecomment-592219930)

Many audio formats cannot be downloaded separately from their videos, but .m4a can, so Tartube should do that.

**Comment by axcore** [comment]
@gitut2007, 

>It should be possible to download the M4a sans wasting dling the video?
It is not possible to download the audio, without downloading the video, in most formats. But it sems to be possible for .m4a.

>[by the way why max. only 3?]
Most design decisions are explained by "that is how youtube-dl-gui does it". If you actually need more than three, open a new issue for that, and I will look into it :)

**Comment by gitut2007** [comment]
-Youtube: usually 'offers' various Audio-only files not only M4a, usually *also Ogg*. 
If wanted Mp3, this is the one that has to ve transcoded from one of the others. 

-Bitchute /others: Idk if they offer only 'integrated' videos and if so, if it could be possible to pre-analyze/demux the file and download only the audio part...

Thx.

**Comment by axcore** [comment]
Yes, I noticed that m4a is easily downloadable from YouTube as a separate file, but are you sure about .ogg? I have been doing some testing, I haven't seen .ogg at all.

About pre-analysis: definitely not possible. I think that even youtube-dl could not do that.

By the way, in case you didn't know, you can right-click a video, and click Fetch > Available formats; that will tell you if the video website offers separate audio files, or not.

**Comment by gitut2007** [comment]
As seen in https://github.com/axcore/tartube/issues/38#issue-546684684 with youtube-dl -R , there are 4 audio-only options, the 3 Webm happen to be Opus, i don't have an example here but sometimes Ogg is in Youtube's, idk if as such or under Webm name. 
In this case anyway, the best quality audio is code 251: opus @160kbps.
Code 140 [m4a] would be chosed by ppl with ipods, but Opus and Ogg are better imho.
I think the codes are always the same for each type.

Idk if it's enough to simply change the extension from Webm to Opus or Ogg, or if some little change to the file has to be done with FFmpeg.

Thx.

**Comment by axcore** [comment]
v2.0.0 removes the restriction. Click Edit > General download options... > Formats. You can now add video formats, audio formats, or a mixture of both. 

I have tested adding .m4a and .webm (audio only, code 140). I can download the audio file without downloading the whole video, as expected.

(If you add both video and audio formats, Tartube now changes the order of the list, so that video comes before audio. This happens when you click the 'OK' button to close the window. It prevents problems with youtube-dl.)
