### ISSUE TITLE
How to download different audio file on a YouTube video?

### ISSUE THREAD

**Issue by notmodfrplays** [axcore/tartube#602]
Hi, I just started using tartube, and I ran into an issue. I do video translation and subtitling, and could not find out if there was a way to change audio files. Being able to have different languages is pretty important for me. If anyone could help me that would be appreciated. THX

**Comment by axcore** [comment]
The answer seems to be [here](https://github.com/yt-dlp/yt-dlp/issues/3540#issuecomment-1107682146).

For Tartube, click **Edit > General download options...**, and in the **Additional download options** box, add this:

`--audio-multistreams -f bestvideo+mergeall[vcodec=none]
`
![options1](https://github.com/axcore/tartube/assets/37951926/e3e43445-e0cd-46ea-8b95-e416b0717f6b)

**Comment by notmodfrplays** [comment]
Thank you, this helps so much

**Comment by notmodfrplays** [comment]
Actually, coming back to it now, upon adding this to the additional download options, I now find nothing changing to the downloads of my videos. I read the thread that was attached, and I still do not understand. If there is help you can provide, I would be grateful.

**Comment by axcore** [comment]
Download one video, then take a screenshot of Tartube's Output tab, including the yellow text at the top.

**Comment by notmodfrplays** [comment]
yt-dlp --newline -i --hls-prefer-native --cookies C:/Users/*/Downloads/TARTUBE/cookies.txt --windows-filenames --output C:/Users/*/Videos/TARTUBE/%(title)s.%(ext)s https://www.youtube.com/watch?v=mImFz8mkaHo&t=1221s&ab_channel=GLITCH
[youtube] Extracting URL: https://www.youtube.com/watch?v=mImFz8mkaHo&t=1221s&ab_channel=GLITCH
[youtube] mImFz8mkaHo: Downloading webpage
[youtube] mImFz8mkaHo: Downloading ios player API JSON
[youtube] mImFz8mkaHo: Downloading android player API JSON
[youtube] mImFz8mkaHo: Downloading m3u8 information
[info] mImFz8mkaHo: Downloading 1 format(s): 271+251-12
[download] Destination: C:/Users/*/Videos/TARTUBE/MURDER DRONES - Episode 1： PILOT.f271.webm
[download] 100% of  712.39MiB in 00:00:09 at 72.25MiB/s
[download] Destination: C:/Users/*/Videos/TARTUBE/MURDER DRONES - Episode 1： PILOT.f251-12.webm
[download] 100% of   25.11MiB in 00:00:00 at 44.74MiB/s
[Merger] Merging formats into "C:/Users/*/Videos/TARTUBE/MURDER DRONES - Episode 1： PILOT.webm"
Deleting original file C:/Users/*/Videos/TARTUBE/MURDER DRONES - Episode 1： PILOT.f251-12.webm (pass -k to keep)
Deleting original file C:/Users/*/Videos/TARTUBE/MURDER DRONES - Episode 1： PILOT.f271.webm (pass -k to keep)

**Comment by axcore** [comment]
You have not added the extra download options

`--audio-multistreams -f bestvideo+mergeall[vcodec=none] `

(If you had added them, they would be visible in the first line of the **Output** tab.)

If you are downloading videos from the **Videos** tab, click **Edit > General download options...** and add the options to the box, as described above.

If you are downloading videos from the **Classic mode** tab, click the menu button in the top-right corner, select **Edit download options...**, and add the options to the same box.
