### ISSUE TITLE
Library Not Updating Correctly

### ISSUE THREAD

**Issue by awadrummer** [axcore/tartube#604]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Windows 11

### What version of Tartube are you using?
v2.4.429

I started to download a channel's videos, but then realized after about 7 videos in that it wasn't downloading  the auto generated subtitles. I halted the process applied the settings to download said subtitles and attempted again. It still didn't download the auto subtitles. So I deleted the files from the drive using TarTube then I went to re-download them. Now no matter how many times I refresh the channel or check the channel the deleted videos no longer show up in the video list.

**Comment by axcore** [comment]
Regarding the inability to re-download the video: see this section on [yt-dlp archive files](https://github.com/axcore/tartube#79-download-all-button-takes-too-long).  If the video has been added to the archive file, then yt-dlp thinks it has already been downloaded, and won't try to download it again.

Try opening the channel's folder, and then delete (or temporarily rename) the archive file, **ytdl-archive.txt**.

Regarding the failure to download subtitles, if that's still a problem then select a single video whose subtitles can't be downloaded. Try downloading them, then show me a screenshot of your Output tab, including the yellow text at the top.

**Comment by axcore** [comment]
Closed for inactivity.
