### ISSUE TITLE
Error when downloading video using custom file name format

### ISSUE THREAD

**Issue by EdwardChanCH** [axcore/tartube#608]
OS: 
Windows 11 Home

Tartube: 
v2.4.386

Video: (or any YouTube video)
https://www.youtube.com/watch?v=v_FmcHuUK0s

Description:
This bug occurred when I edited (applied) the filename format (in Classic Mode's settings menu) from "Title + ID" to "Custom: Video + URL". This error did not occur when using either the "Title" or "Title + ID" options. I need to use the "Custom" option as I only want video titles with URLs appended (just like using the yt-dlp CLI) but without the other .info files being generated. I tried updating yt-dlp (as suggested by the error pop-up) but nothing changed. 

<img width="628" alt="image_1" src="https://github.com/axcore/tartube/assets/97891482/a56fecd6-45ff-4bcf-a89d-5038d8472607">
<img width="1188" alt="image_2" src="https://github.com/axcore/tartube/assets/97891482/2499ad2e-a043-4082-9e3f-e1211522cbad">
<img width="767" alt="image_3" src="https://github.com/axcore/tartube/assets/97891482/01f4465e-2a5c-4124-994c-5c3d62ab6a81">

To recreate this error, go to Classic Mode --> Edit download options... --> Files --> change "Title" to "Custom" --> in the options, change "Video ID" to "Video URL" and then click "Add". The file output template should become "%(title)s-%(url)s.%(ext)s". Click "Apply" and "Ok". Then try downloading any video/ playlist using Classic Mode. 

Thanks for reading.

**Comment by axcore** [comment]
Please copy and paste all of the yellow text at the top of the Output tab, some of which is not visible in your screenshot.

**Comment by EdwardChanCH** [comment]
> Please copy and paste all of the yellow text at the top of the Output tab, some of which is not visible in your screenshot.

yt-dlp --newline -i --hls-prefer-native --write-description --write-info-json --cookies C:/Users/XXX/Documents/#TarTube/cookies.txt --write-thumbnail --windows-filenames --output C:/Users/XXX/%(title)s-%(url)s.%(ext)s https://www.youtube.com/watch?v=v_FmcHuUK0s

**Comment by axcore** [comment]
On my Linux system, I get different results, using exactly the same download options:

`/home/ra/.local/bin/yt-dlp --newline -i --hls-prefer-native --write-description --write-info-json --cookies /home/ra/tartube-data/cookies.txt --write-thumbnail --output "/home/ra/tartube-data/Unsorted Videos/%(title)s-%(url)s.%(ext)s" --windows-filenames https://www.youtube.com/watch?v=v_FmcHuUK0s`

In your screenshot, yt-dlp is inserting a very long (and incorrect) URL; on my system, yt-dlp inserts `NA` for the URL:

`[info] Writing video description to: /home/ra/tartube-data/Unsorted Videos/Huge explosion as Ukraine strikes Russian warship ｜ BBC News-NA.description`

Both results seem to be incorrect, so I suggest reporting the problem on the [yt-dlp issues page](https://github.com/yt-dlp/yt-dlp/issues). (It is apparently not a Tartube problem.)
