### ISSUE TITLE
Why won't Tartube install ffmpeg for me?

### ISSUE THREAD

**Issue by Wonpil-Myoui** [axcore/tartube#609]
I have a windows 11 and this is my first time downloading something like Tartube. I've wanted to download 4k youtube videos but everytime I try to install ffmpeg through Tartube it just says:

Starting update operation, installing FFmpeg
pacman -S mingw-w64-x86_64-ffmpeg --noconfirm

I've waited for 10 minutes to see if it will do something, but I guess this is an error?

**Comment by axcore** [comment]
Try the [Tartube installer, that already includes FFmpeg](https://sourceforge.net/projects/tartube/files/v2.4.429/install-tartube-with-ffmpeg-2.4.429-64bit.exe/download).

**Comment by Wonpil-Myoui** [comment]
> Try the [Tartube installer, that already includes FFmpeg](https://sourceforge.net/projects/tartube/files/v2.4.429/install-tartube-with-ffmpeg-2.4.429-64bit.exe/download).

Hi, I already installed this version, however when opening tartube for the first time, the Install ffmpeg shows up again with the same -noconfirm error.

**Comment by axcore** [comment]
With that version, ffmpeg is already installed. You can ignore the request to install ffmpeg.

**Comment by Wonpil-Myoui** [comment]
> With that version, ffmpeg is already installed. You can ignore the request to install ffmpeg.

Thank you! Everything works perfectly now
