### ISSUE TITLE
Video Sorting is not always triggered

### ISSUE THREAD

**Issue by tsk-2222** [axcore/tartube#611]
### What version of Tartube are you using? v2.4.429

Reverse sort does not trigger properly.
To Reproduce:
When starting from a normal sort; Clicking reverse sort does nothing and clicking the 'resort videos' icon does nothing.  You can then trigger the sorting function by right clicking on any video, click show video, click properties, click OK. At that point the sort function will be triggered to reverse sort the videos. BTW, leaving the folder and returning to the folder will also cause the sort order to be wrong.

When you are in reverse sort order then clicking the 'undo reverse sort' icon will work properly.

Additionally, non alphabet characters are being included in the sort. For instance the text "Watch This" will be sorted first when in alphabetical order.

**Comment by axcore** [comment]
>Reverse sort does not trigger properly
I have fixed his problem, but...

>Additionally, non alphabet characters are being included in the sort.
I can't reproduce it; non-alphabetic characters should not affect the sort. Please give me the URL of a channel or playlist, which demonstrates this behaviur.

**Comment by tsk-2222** [comment]
Here's a video that starts with quotes:
https://www.youtube.com/watch?v=D090T2MSxKY
When sorted by name, the video title: **"I Will Always Love You" Linda Ronstadt** will be sorted before all other videos because the ascii for the quote character in the title comes before the ascii for any letter or number.

Perhaps the sort should be by uppercase letters and numbers only and exclude other characters.

**Comment by axcore** [comment]
>Additionally, non alphabet characters are being included in the sort. 

I fixed this in v2.5.003. The new code is uploaded only to github/pypi; Windows users can update their installation as [described here](https://github.com/axcore/tartube#72-update-tartube-on-ms-windows).
