### ISSUE TITLE
Submitting `tartube` as a package to the Windows Package Manager Community Repository

### ISSUE THREAD

**Issue by ghost** [axcore/tartube#612]
I think it'd be great to see `tartube` added to the [Windows Package Manager Community Repository](https://github.com/microsoft/winget-pkgs). With `winget` now available by default on both Windows 11 and the newest release of Windows 10, this would bring a bunch of perks for `tartube` users:

- Having `tartube` in the Windows Package Manager makes it simpler for everyone to discover and use.
- Installing `tartube` becomes a breeze using `winget install tartube` for anyone who is already running the latest version of Windows, no third-party package managers required.
- Users get hassle-free updates for the latest `tartube` version so long as the manifest is updated with each new version.
- Being part of the official Windows Package Manager adds credibility, assuring users of `tartube`'s reliability.

Would love your consideration on this. Adding `tartube` to the Windows Package Manager feels like a win-win both for your project and for the Windows community.

Thanks for your time and effort. Cheers!

_LE:_ In case this helps sway your decision, a number of related projects are already available on `winget`, as per the following image. There might be some that I have missed with my particular query, though.
![winget-related-projects](https://github.com/axcore/tartube/assets/124451350/64868190-4104-40b0-9325-4e5d1fd2b880)

**Comment by axcore** [comment]
`winget` can't be installed on my system, so at the moment there is nothing I can do.

If anyone wants to [submit a package](https://github.com/microsoft/winget-pkgs), they are very welcome to do so (see for example the [chocolatey package](https://community.chocolatey.org/packages/tartube) is not controlled by me).
