### ISSUE TITLE
can't uncheck filter yt-dlp options

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#614]
Using latest build from github on win10 launching through ming, I'm trying to figure out how to fix the unicode filename issue that one of the recent yt-dlp releases has caused.

I use the "other forks" option to use different releases of yt-dlp to find which release broke things.

![image](https://github.com/axcore/tartube/assets/16659133/8558c93a-8cbb-428b-86c3-21a6a0b6fa5b)

I unchecked "When using other downloaders, filter out yt-dlp download options" and then tried to set the "--windows-filenames" option and when doing test downloads didn't see that option outputted in the command line. 

Going back into the downloader screen I realized that checkmark was ticked again.

If I set the fork to yt-dlp, then the --windows-filenames showed up in the command line as expected.

Thanks Axcore!

**Comment by axcore** [comment]
Fixed in v2.5.007. Apparently, the button did not work, because I forgot to add the code ;)
