### ISSUE TITLE
Forcing specific audio download

### ISSUE THREAD

**Issue by KJThaDon** [axcore/tartube#617]
Downloading a video that has 2 audio options, it seems to be grabbing the second one by default. The second one "English - Audio Description" is the one it's grabbing by default, but I want the first one.

Example video: https://tubitv.com/movies/100005007/cinnamon

**Comment by axcore** [comment]
Sorry, Tubi is not available in Europe so I can't test your video. If you want specific advice for that video, try asking on [Reddit](https://www.reddit.com/r/youtubedl/).

In general, you specify the audio track you want by specifying a video format, as described [here](https://github.com/yt-dlp/yt-dlp#format-selection), [here](https://github.com/yt-dlp/yt-dlp/issues/3540) and [here](https://www.reddit.com/r/youtubedl/comments/114624f/how_to_choose_audio_language_for_youtube_video/?rdt=59142).

When you have set up your format selection, add it to Tartube's download options (in the Videos tab, **Edit > General download options...**, in the Classic Mode tab, click the menu button in the top-right corner and select **Edit download options...**).

For example, to download all audio tracks, you would add this:

`--audio-multistreams -f bestvideo+mergeall[vcodec=none]`

![tartube_format](https://github.com/axcore/tartube/assets/37951926/37081ba0-57a6-4f5d-849f-532bb7f9047f)

Or, to download just the English tracK;

`-f bv+ba[language=english]`

**Comment by axcore** [comment]
Closed for inactivity.
