### ISSUE TITLE
Downloading a playlist of 40 videos, stops around 8 or 10 videos in

### ISSUE THREAD

**Issue by ringkun** [axcore/tartube#618]
I have a video playlist with 40 videos, I tried to download it with Tartube with the default settings, only removing the metadata files. It stops prematurely, additionally it doesn't download in the order of the playlist. What should I be doing to download an entire playlist.

**Comment by axcore** [comment]
I can only help you, if you give me the URL of the playlist.

**Comment by ringkun** [comment]
https://www.youtube.com/playlist?list=PLluk5zDVDZJZCIZu71XrKfMFqz0KzXNU5
Here you go

**Comment by axcore** [comment]
You saw my answer on reddit, yes?
