### ISSUE TITLE
Gentoo Packaging

### ISSUE THREAD

**Issue by xgqt** [axcore/tartube#62]
I have created a ebuild for your program, available in src_prepare-overlay repo 

tree link: https://gitlab.com/src_prepare/src_prepare-overlay/-/tree/master/media-video%2Ftartube

We would appreciate it a lot if you added this to the tartube readme.
Thanks for great software.

**Comment by axcore** [comment]
@xgqt, I haven't used Gentoo ebuilds so I don't know what to add (i.e. I don't know how to say "If you want to install Tartube on Gentoo, do this..."

If you want to write the text yourself, I will add it to the README

**Comment by xgqt** [comment]
> @xgqt, I haven't used Gentoo ebuilds so I don't know what to add (i.e. I don't know how to say "If you want to install Tartube on Gentoo, do this..."
> 
> If you want to write the text yourself, I will add it to the README

I propose
"""
3 Downloads
...
- `Gentoo ebuild (avalible in src_prepare-overlay) <https://gitlab.com/src_prepare/src_prepare-overlay>` __ from Gitlab
...
"""

**Comment by axcore** [comment]
Done!

**Comment by xgqt** [comment]
> Done!

Thanks for cooperation! Keep the quality code goin'.
