### ISSUE TITLE
Clear previously downloaded links when using the `Clear downloaded` button

### ISSUE THREAD

**Issue by parasiteoflife** [axcore/tartube#621]
I'm using yt-dlp with the archive option.

When there is a url that has been already downloaded and is logged in the archive file Tartube also marks them as "Finished" but they are not removed when using the `Clear downloaded` button, please add this function.

**Comment by axcore** [comment]
Fixed in v2.5.015. 

The new code is uploaded only to github/pypi. You can update a Windows installation, as described here: https://tartube.sourceforge.io/#update-tartube-on-ms-windows
