### ISSUE TITLE
I trying to download all videos from a channel that has more than 1000 videos.

### ISSUE THREAD

**Issue by OmverYo** [axcore/tartube#622]
The channel that I am following is on Dailymotion and the link is provided here below.
https://www.dailymotion.com/MBCEntertainment

Using "Add a new channel function" with the link above enables it to check the channel and download the videos from the channel.
It checks videos fom the channel and it only detects 1000 videos at maximum while the actual dailymotion channel has 98000 videos.
Is there a way to check and download more than 1000 videos?
I have checked README.rst but it does not seem to have the solution for my question.

**Comment by axcore** [comment]
According to this thread, yt-dlp cannot download more than 1000 videos from a Daily Motion channel.

https://www.reddit.com/r/youtubedl/comments/10ksxa8/ytdlp_downloading_from_playlists_with_more_than/?rdt=61932

I don't know about any workarounds.
