### ISSUE TITLE
Unexpected redownloading of existing channel videos

### ISSUE THREAD

**Issue by a0ivanov** [axcore/tartube#623]
### What operating system are you using?
MS Windows 11

### What version of Tartube are you using?
v2.5.007

Hello!

Issue happens on subsequent attempt to download checked channel videos with "Download marked items" button, for ex.
Bug has been introduced at 9f8863a1444b329eed6f7b9c8f2eac2e4491dd4a.
Reason is in [inversed flag](https://github.com/axcore/tartube/commit/9f8863a1444b329eed6f7b9c8f2eac2e4491dd4a#diff-ad7d465aebc82654ac3fcbae9f15473e3bdb9a7fa6095b19f694ca8bd49eaf2eR11971) that supposed to disable blocking of archive file usage.

Please take a look.

**Comment by axcore** [comment]
Thanks, the problem was exactly as you described. It's fixed in v2.5.015.
