### ISSUE TITLE
Disable Modal Dialogs When You Move a Video

### ISSUE THREAD

**Issue by MarkNixon** [axcore/tartube#624]
This program is INCREDIBLE; it's literally changed my life for the better! More people should know about it. Thank you so much. 

But the confirmation modals that pop-up when you try to move a video to a different folder are seriously time-consuming and irritating (I'm sorry to say it!). i.e. "Are You Sure You Want to Move This Video?"… every single time… Plus, you’re also switched to the destination directory, which doesn’t seem desirable.

I've just looked at the source code and even though I don't know Python it doesn't seem like it would be difficult to disable the dialog or be able to disable in settings, at least. I might have a go at it myself. But this one issue is a huge problem, IMHO, for your otherwise amazing app. Reorganizing videos should be quick, just like in any file manager: drag, drop, file moves and you stay in your current location.

Thank you!

**Comment by axcore** [comment]
Workaround: from the main menu, click **Edit > System preferences... > Windows > Dialogues**, and enable **Temporarily disable message dialogue windows**.

**Comment by axcore** [comment]
Added in v2.5.015. 

You can now disable both the prompts, and switching to the destination folder. You can do that both in the dialogue window, and in **Edit > System preferences... > Windows > Dialogues**.  Let me know if you have any problems with it.

The new code is uploaded only to github and pypi. You can update a Windows installation as described here: https://tartube.sourceforge.io/#update-tartube-on-ms-windows

**Comment by MarkNixon** [comment]
Thank you so much! Just updated and checked and it works great. This is a big relief/time-saver for me. Your fast response is hugely appreciated. Does Tartube take donations?

**Comment by axcore** [comment]
I don't take donations, but the authors of yt-dlp do.
