### ISSUE TITLE
ffprobe not found. Please install or provide the path 

### ISSUE THREAD

**Issue by SakethKanchi** [axcore/tartube#625]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Windows 11

### What version of Tartube are you using?
v 2.5.0

### If your bug report is "I can't download this video", please provide a link to the video
![image](https://github.com/axcore/tartube/assets/70198692/da5e8097-5029-4d56-b0bb-9830445eeea8)

video link: https://www.youtube.com/watch?v=XKHEtdqhLK8

**Comment by axcore** [comment]
Have you installed FFmpeg using the Tartube setup window, or from the main menu?

**Comment by SakethKanchi** [comment]
> Have you installed FFmpeg using the Tartube setup window, or from the main menu?

Using Tartube setup

**Comment by SakethKanchi** [comment]
> Are you sure that FFmpeg was installed correctly, without errors? Try installing it again from the Tartube menu, then show me the last few lines of output (in the Output tab).

![image](https://github.com/axcore/tartube/assets/70198692/76fb2c1e-0e39-4943-996f-f85c81e1e61a)
Keep getting this error if i try to reinstall ffmpeg
