### ISSUE TITLE
Download Vimeo password protected private video?

### ISSUE THREAD

**Issue by brightjoey** [axcore/tartube#627]
Pretty straight forward question. I'm trying to download a vimeo video that has a password and it's private. I think it would work if I input some command into the cmd line in the classic yt-dlp setup, but not sure if Tartube can also solve this?

Here's the video I'm trying to download.
https://vimeo.com/932233436
password: 1234-1234

No idea how to get it to run.
![python3_geZGNkdYyj](https://github.com/axcore/tartube/assets/34862568/32c6348a-73c2-46f6-932f-b03151a59eda)

**Comment by BlueBull010** [comment]
A bit late of a reply, but to download passworded Vimeo videos, edit your download options and in the first screen (the tab called "name") you see a large text field to put extra download options in, see below screenshot. Inside that text field add the following but without the quotes and replace <password> with the video password: "--video-password <password>". This will download it. Took me a while to figure this out and in my research I found this github question so I thought I'd answer it now that I know how to do it ;-)

![image](https://github.com/axcore/tartube/assets/61655638/22522f0f-5c93-4e87-ab3c-1bcef548ec5e)

**Comment by axcore** [comment]
I added a section to the Tartube README, explaining how to do this. Thank you @BlueBull010 for your response.

**Comment by PMENARI** [comment]
I am still not able to download video, even after providing password

**Comment by luk9a** [comment]
You have also to tell the format you want to download, like this if you want the lower resolution:

--video-password 1234-1234 -f hls-fastly_skyfire-263

ID                                    EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-fastly_skyfire-audio-high-English mp4 audio only     │                  m3u8  │ audio only        unknown    [en] English
hls-fastly_skyfire-263                mp4 426x240     25 │ ~147.26MiB  263k m3u8  │ avc1.640015  263k video only
hls-fastly_skyfire-314                mp4 640x360     25 │ ~175.82MiB  314k m3u8  │ avc1.64001E  314k video only
hls-fastly_skyfire-410                mp4 960x540     25 │ ~229.57MiB  410k m3u8  │ avc1.64001F  410k video only
hls-fastly_skyfire-525                mp4 1280x720    25 │ ~293.96MiB  525k m3u8  │ avc1.640020  525k video only
hls-fastly_skyfire-824                mp4 1920x1080   25 │ ~461.38MiB  824k m3u8  │ avc1.64002A  824k video only
hls-fastly_skyfire-1070               mp4 2560x1440   25 │ ~599.12MiB 1070k m3u8  │ avc1.640033 1070k video only

**Comment by PMENARI** [comment]
Ohh thats great, thanks 🙏

**Comment by paddyb2** [comment]
Hi, I have the same issue. I've put the PW and format in, but I just get an immediate error?

**Comment by axcore** [comment]
The [reddit forum](https://www.reddit.com/r/youtubedl/) is a good place to ask site-specific questions like this.
