### ISSUE TITLE
Docker image and docker-compose.yml

### ISSUE THREAD

**Issue by bonelifer** [axcore/tartube#628]
Would be nice to have a Docker image and docker-compose.yml file.

**Comment by axcore** [comment]
There are dozens of packaging systems now and I simply don't have the time to learn them all (or indeed, any of them). If anyone with the right skills wants to create a new packager, I would be happy to add it to the [semi-official list](https://tartube.sourceforge.io/#downloads). I would also be happy to add a docker-compose.yml file to the source code, if someone succeeds in creating one. (Looks like [some limited progress](https://forums.unraid.net/topic/111797-request-tartube-gui-docker-container/) was made a couple of years ago.)
