### ISSUE TITLE
Watching a video via YouTube link

### ISSUE THREAD

**Issue by PowerPress** [axcore/tartube#63]
If I click the YouTube link to watch the video it will play in tartube or open a browser to play it?

**Comment by axcore** [comment]
![tartubeliniks](https://user-images.githubusercontent.com/37951926/75973039-70fa1b80-5ecc-11ea-8e91-522aa0bc61c7.png)

If the video has been downloaded, click **Player** to watch the video in Windows Media Player, or VLC, or whatever media player is installed on your computer

If the video has not been downloaded, click **Download & watch**. After downloading the video, Windows Media Player/VLC/whatever will automatically start, and you can watch the video

In all cases, you can click **YouTube**, **HookTube** or **Invidious**. They all open your web browser, so you can watch the video on one of those websites.

**Comment by axcore** [comment]
Closed for inactivity.
