### ISSUE TITLE
What to do with "Nothing happened?" on a single channel (40ish others work fine)

### ISSUE THREAD

**Issue by djarumlights** [axcore/tartube#630]
Hello there! 

First and foremost, thank you for this excellent video archival program! Most reliable I've used yet. 

I'm running into an issue with a single channel. It has previously scraped the channel without issue and downloaded some but not all of the content. In trying to snag the ones that were missed, I am now getting "Nothing happened?" when checking and attempting to download. Yt-dlp and FFMpeg were all installed per the tutorial for a Windows system, and I've got zero issues with 40ish other channels. 

There are no errors or warnings (all options checked to make sure I didn't miss anything), and it looks like nothing is happening in the output log. I did the "Test yt-dlp" function using a single video from the channel, and it pulled without issue. Should I delete and re-add the channel as a whole maybe? Inconvenient, but doable under the current circumstances. 

The below text is from my output tab. This is all it spits out. No responses or additional data to be seen. 

`python3 -X utf8 ..\..\..\mingw64\bin\yt-dlp.exe --newline -i --hls-prefer-native --write-description --write-info-json --cookies "Q:/YT Subscriptions/cookies.txt" --write-thumbnail --recode-video mp4 --windows-filenames --output "Q:/YT Subscriptions/PoisonPavel/%(title)s.%(ext)s" --dump-json --download-archive "Q:/YT Subscriptions/PoisonPavel/ytdl-archive.txt" https://www.youtube.com/@karaokeligapoisonpavel9592`

**Comment by axcore** [comment]
In YouTube, click the **Videos** tab to get a link that's much more likely to work, namely https://www.youtube.com/@karaokeligapoisonpavel9592/videos

**Comment by djarumlights** [comment]
Hm. It still doesn't like that for some reason. a nothing on check, and attempting to download a video that at least by appearances hasn't been downloaded, it states "already recorded in archive" in the output. 

I seem to have downloaded 241 of the 247 videos present (I could understand the remainder of those being region-blocked for whatever reason, so I'm not sweating those). It's just odd that it won't even check the channel. Hm. 

I can revisit it again when the channel has posted new content and see if it functions correctly. Since this is a relatively isolated case, I understand if you want to go ahead and close this out.

**Comment by axcore** [comment]
Sorry for the delay, I have been away from my desk.

>it states "already recorded in archive" in the output.

yt-dlp is creating an archive file, so it doesn't try to download the same file twice. If it's preventing a download, then you should simply delete (or temporarily rename) the archive file, **ytdl-archive.txt** which is usually in the same folder as the video.

To prevent yt-dlp from creating an archive file at all, in Tartube's menu click **Edit > System preferences...** . In the new window, click the **Show advanced preferences** button if it's visible, then click the **Operations > Archive** tab. Deselect **Allow downloader to create its own archive file**, then click OK to close the window.

**Comment by axcore** [comment]
Closed for inactivity.
