### ISSUE TITLE
Unable to set custom-path for yt-dlp

### ISSUE THREAD

**Issue by zensubz** [axcore/tartube#633]
I am unable to set a custom-path for yt-dlp. Screenshot is attached below, I try typing the path for the standalone yt-dlp executable, but nothing happens.

![tartube_ytdlp_path](https://github.com/axcore/tartube/assets/5127872/2999f8ca-120f-4ce7-b7ad-42c72fd14e81)

I am on a CentOS 7.x, and compile tartube from source. Tartube version is 2.5.015 (commit 5d2ccfe).

Please provide a fix for this, thanks in advance.

**Comment by axcore** [comment]
Fixed in v2.5.021.

The new code is uploaded only to Pypi and Github, I haven't updated the installers yet.
