### ISSUE TITLE
Comments Not Downloading

### ISSUE THREAD

**Issue by Toylance** [axcore/tartube#634]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
POPOS

### What version of Tartube are you using?
v2.5.0

### If your bug report is "I can't download this video", please provide a link to the video
N/A

---

As recently as one and a half months ago, Tartube lost the ability to download any comments for any and all YouTube videos. Regular download functions work just fine, but otherwise Tartube fails to download comments as requested, as seen here as an example. 

[download] Downloading item 5 of 16
[youtube] Extracting URL: https://www.youtube.com/watch?v=my4eKvoiEZQ
[youtube] my4eKvoiEZQ: Downloading webpage
[youtube] my4eKvoiEZQ: Downloading ios player API JSON
[youtube] my4eKvoiEZQ: Downloading android player API JSON
[youtube] my4eKvoiEZQ: Downloading m3u8 information
[youtube] Downloading comment section API JSON
[youtube] Downloading ~856 comments
[youtube] Sorting comments by newest first
[youtube] Downloading comment API JSON page 1 (0/~856)
[youtube] Downloading comment API JSON page 2 (0/~856)
[youtube] Downloading comment API JSON page 3 (0/~856)
[youtube] Downloading comment API JSON page 4 (0/~856)
[youtube] Downloading comment API JSON page 5 (0/~856)
[youtube] Downloading comment API JSON page 6 (0/~856)
[youtube] Downloading comment API JSON page 7 (0/~856)
[youtube] Downloading comment API JSON page 8 (0/~856)
[youtube] Downloading comment API JSON page 9 (0/~856)
[youtube] Downloading comment API JSON page 10 (0/~856)
[youtube] Downloading comment API JSON page 11 (0/~856)
[youtube] Downloading comment API JSON page 12 (0/~856)
[youtube] Downloading comment API JSON page 13 (0/~856)
[youtube] Downloading comment API JSON page 14 (0/~856)
[youtube] Downloading comment API JSON page 15 (0/~856)
[youtube] Downloading comment API JSON page 16 (0/~856)
[youtube] Downloading comment API JSON page 17 (0/~856)
[youtube] Downloading comment API JSON page 18 (0/~856)
[youtube] Downloading comment API JSON page 19 (0/~856)
[youtube] Downloading comment API JSON page 20 (0/~856)
[youtube] Downloading comment API JSON page 21 (0/~856)
[youtube] Downloading comment API JSON page 22 (0/~856)
[youtube] Downloading comment API JSON page 23 (0/~856)
[youtube] Extracted 0 comments

-

If I had to guess, I suspect it may actually be some API change on Youtube's end, but I can't confirm either way. If there's currently no solution pending as of right now, it would be nice to know if my suspicions are correct or not. I can elaborate and provide screenshots upon request.

**Comment by presageroutlook** [comment]
Tartube not working suddenly. Using Linux Mint.  Have tried everything

**Comment by axcore** [comment]
@Toylance I tried downloading subtitles using just yt-dlp, and it doesn't work. So it seems to be a [yt-dlp issue](https://github.com/yt-dlp/yt-dlp/issues).

```
$ yt-dlp --write-subs --sub-langs all https://www.youtube.com/watch?v=my4eKvoiEZQ
[youtube] Extracting URL: https://www.youtube.com/watch?v=my4eKvoiEZQ
[youtube] my4eKvoiEZQ: Downloading webpage
[youtube] my4eKvoiEZQ: Downloading ios player API JSON
[youtube] my4eKvoiEZQ: Downloading m3u8 information
[info] my4eKvoiEZQ: Downloading 1 format(s): 302+251
[info] There are no subtitles for the requested languages
[download] Shedinja is Scary as F＊＊＊ - Halloween Special! [my4eKvoiEZQ].webm has already been downloaded

$ yt-dlp --version
2024.05.27
```

By the way, it's helpful if you include the yellow text at the top of Tartube's output tab, so I can reproduce your download exactly.

**Comment by axcore** [comment]
@presageroutlook Tartube seems to be working as normal today on my Linux Mint system. If you feel like submitting an actual bug report, then I'll see what I can do to assist you.
