### ISSUE TITLE
Plex integration?

### ISSUE THREAD

**Issue by secretlycarl** [axcore/tartube#637]
Hi, thanks for making this tool.

I'm trying to get the videos DL'd from tartube to look nice in Plex. Right now it shows the file path as the show/channel title. 

![Screenshot 2024-06-30 170038](https://github.com/axcore/tartube/assets/45924139/d050dff7-419f-4192-b8de-8bf02ad5a13f)
![Screenshot 2024-06-30 170045](https://github.com/axcore/tartube/assets/45924139/41159e6e-51d1-4440-a0cd-8bb05aa73a49)

Is there a setting I missed? Or maybe something with the scanners in plex that would help? thanks!

edit: i was able to fix the titles by just editing them on plex. any fix for thumbnails?

**Comment by axcore** [comment]
Sorry, I have never used Plex and I don't know how to configure it.
