### ISSUE TITLE
Errors on unraid, cannot download

### ISSUE THREAD

**Issue by PrzemekSkw** [axcore/tartube#638]
Hello,
I install Tartube on uraid CA. There's docker container as VNC:

![image](https://github.com/axcore/tartube/assets/25219988/2e6303c6-b6ab-42d6-94ea-bcd5173b4979)
![image](https://github.com/axcore/tartube/assets/25219988/e129cc9c-5f29-4020-8dd3-90d4dcf2d525)

When I choose random youtube video I get errors like that:
![image](https://github.com/axcore/tartube/assets/25219988/a657fa57-c914-4ad9-a1ed-4c8fd460cd60)

when I click `Update youtube-dl`:
![image](https://github.com/axcore/tartube/assets/25219988/ac6a1178-3f4a-4bcb-aeb9-9c71b5fb5d60)

![image](https://github.com/axcore/tartube/assets/25219988/56dd64a6-46cc-42ca-923c-56975c0d013f)

How can I fix that?

Regards.

**Comment by axcore** [comment]
Sorry, I'm not familiar with docker/unraid and I didn't create the installation you're using, so I don't know how to get it working.
