### ISSUE TITLE
I am an idiot and am wondering about some idiot proofing/help

### ISSUE THREAD

**Issue by alidan** [axcore/tartube#64]
ok, I tested youtube dl, that worked
I'm able to get something to download, great
it is either the lowest quality garbage, or I can't get anything to download. 

I have no idea what i'm doing wrong. 
What I want are 2 settings/2 simple ways to download

1) I want to download best video/audio
2) I want best audio only

A Lot of what I save are either very podcasty, or is music, and I want the best quality with no bs, I don't want to convert if I don't have to, I just want the download to be simple, file size be damned, best video and audio with no conversion. I can't for the life of me figure out what i'm doing wrong for this to not be happening. I can't find a setting that isn't trying to convert the end product... 

Like I said, I may be a complete idiot, and i'm missing something obvious, but if im not, would it be possible to just have a simple (best audio/video) and (best audio only) option that is a single button press?

**Comment by axcore** [comment]
alidan,

youtube-dl automatically downloads the best quality video and audio, unless you specify a different setting. You don't have to do anything. Just click download.

Not all videos are available in high definition. If a video was uploaded to YouTube 10 years ago, it will never be available in 1440p. Tartube can show you the available video formats. Right-click a video and select **Fetch > Available formats**, then click the **Output** tab to see the results.

About downloading audio only - it's not a simple setting because of the complexities of storing and downloading videos on the web. In most cases, you need to install Ffmpeg or AVconv as well as Tartube. If you are using MS Windows, you can click **Operations > Install FFmpeg** to do that. The rest really is a one-click operation. Click **Edit > General download options... > Sound only > Download each video, extract the sound...**. Then set the audio quality to **High**.

For more details about downloading audio, [see this](https://github.com/axcore/tartube#converting-to-audio).

If you want help with a particular video, give me the link, and I will check that it downloads correctly.

**Comment by alidan** [comment]
Ok, it seems like things are downloading now, when I wrote this the only thing that would happen was nothing would download at all, outside of a screenshot or meta, but now the program is downloading the video. also before I was getting a 9mb 360p video or a 1mb 360p but even worse quality video, now i'm getting 1080p60, however as a test I tried 4k60 and it still only grabbed 1080p60...

Ok, I realized that I still had a 'custom' setting that I thought could be applied to a folder only, turns out it was program wide... ok, so I removed that setting and it still did the same thing, ok maybe restarting is required. for me I need to start the program twice as the first try the program won't fully load and it get stuck with minimal/no function, and the second time it loads. and it turns out the the setting stuck through shutdown and restart... so I tried again and it now downloads best quality.

Honestly im happy that this works but its one of those things where I did nothing and it fixed itself

as for downloading audio, that section only details converting it, If possible I want the audio to not be messed with at all, and as far as I'm aware youtube has had separate video and audio streams for a very long time now, and even if that isn't the case, a conversion is not necessary, just a demux would work
Ok, in trying to download a video and see if I can demux it, the program would continue downloading and converting to flac, when I finally got this to stop, the program is returning to how it was in the beginning, and not downloading anything but this time, even meta data is no longer downloading. 

so to test youtube dl still works, as the program is not sending me any errors, so I took that file and I decided to demux it, now the ones from the program where giveing me mp4's mkv's and webm's I know mp4 and mkv are demuxable, the file it spat out was "adts audio" but everything i'm using is giving me no problems with it

now in the program, I took one of the songs I like, and decided flac was the best of those options because at least that way the audio wouldn't be messed with, the resulting flac came out to be 40mb... 12mb more then the one that had 1080p60 video... even going through a stereo mix into audacity and saving it as flac at the highest quality uses less space then that. 

so I have to ask because I thought this was how it worked and I was clearly wrong before. 

is there a way to set folder specific download settings rather then global? I don't want to have to go into global settings and mess around just to go from an audio only setting to a get me the best audio/video you can setting.

Now if I remember how youtube-dl works, it can get a single stream
![python3_2020-03-19_02-03-33](https://user-images.githubusercontent.com/2681758/77040466-f928f800-6985-11ea-93e1-b2f158a64a51.png)
as it clearly sees audio only formats, also, note this 
![python3_2020-03-19_02-05-01](https://user-images.githubusercontent.com/2681758/77040511-0f36b880-6986-11ea-9c16-65620cfc691a.png)

I think that was the problem before, and yes... it was
![python3_2020-03-19_02-06-13](https://user-images.githubusercontent.com/2681758/77040585-3bead000-6986-11ea-9caf-22798582776a.png)
that explains why I was getting such a low resolution video, it was choosing what was 'best' its just that the best it thought was a video/audio combination file rather then the best quality streams. 

is there a way to download only the best quality audio stream without conversion? 

and also it appears that my program is completely broken at the moment and not getting any files at all, youtube-dl is working correctly, and I believe ffmpeg is also installed and working, if getting an audio only though stupidly large flac was anything to go by.

**Comment by axcore** [comment]
>If possible I want the audio to not be messed with at all, and as far as I'm aware youtube has had separate video and audio streams for a very long time now

There are four ways to download audio only:

1. Click Edit > General download options.. Click the Hide advanced download options button if it is visible. Then click the Sound only tab. Select the checkbox, and choose the audio format and quality.

2. Click Edit > General download options... Click the Show advanced download options button if it is visible. Then click the Post-process tab. Select the checkbox Post-process video files to convert them to audio-only files, and choose the audio format and quality

3. Click Edit > General download options... > Formats. On the left side is a list of video/audio formats. Click one of them to select it (for example, m4a) and then click the Add format button.

4. Click Edit > General download options... In the large box marked Extra youtube-dl command line options, add any options you like. (There is a list of them [here](https://github.com/ytdl-org/youtube-dl/)).

**Comment by axcore** [comment]
> and even if that isn't the case, a conversion is not necessary, just a demux would work

Tartube does not perform any video conversion/post-processing/demuxing at all. 

Tartube is just a GUI. You click buttons to select the options you want, and then those options are passed to youtube-dl. If the video is post-processed, that is handled by youtube-dl. Tartube does not interfere with the post-processing.

**Comment by axcore** [comment]
> is there a way to set folder specific download settings rather then global?

Yes. Download options can be applied to a folder (and everything in it), applied to a channel (and everything in it), applied to a playlist (and everything in it), or applied to a single video. [Section 6.11](https://github.com/axcore/tartube#general-download-options) and [Section 6.12](https://github.com/axcore/tartube#other-download-options) explain how it works.

To apply download options to a folder, you would right-click it, and select Downloads > Apply download options... ; until you do that, the general download options apply (Edit > General download options...)

**Comment by axcore** [comment]
> is there a way to download only the best quality audio stream without conversion?

I don't know the answer to this question. Perhaps you could ask the youtube-dl experts (I am not an expert). 

If they give you some youtube-dl options, then you can add those options in Edit > General download options... > General > Extra youtube-dl command line options.

**Comment by axcore** [comment]
>and also it appears that my program is completely broken at the moment and not getting any files at all

It is difficult to explain why you are experiencing so many problems. You should probably reset all download options to their default values, and then start again (Edit > General download options... > General > Completely reset all download options to their default values). 

You should also make sure that youtube-dl itself is the most recent version (Operations > Update youtube-dl).

**Comment by alidan** [comment]
Ok, I got a chance to go back in and try this again.
Now I have 2 folders, videos and music, what they get should be obvious
music has the command -x im not 100% sure, but this seems to only get the best audio given how fast it downloaded one that would have been a 100mb download 

so everything is set up in a way that should work, but there is a problem. 

these are my 6 videos I have used to test
https://www.youtube.com/watch?v=VtYry8xaZLY&t=241s
https://www.youtube.com/watch?v=ZW5W-MEvr5w
https://www.youtube.com/watch?v=vespLm2TzFQ&t=173s
https://www.youtube.com/watch?v=B2jBj_ZWSh0&t=184s
https://www.youtube.com/watch?v=WechI-sjrdQ
https://www.youtube.com/watch?v=-JHZsahHhI0&t=267s

the numbers at the end doesn't seem to cause issue, however 
https://www.youtube.com/watch?v=ZW5W-MEvr5w (✧Nightcore - Sexy Naughty Bitchy Me (lyrics)) 
refuses to download, I tried it in the video area and it will download there, one of the frustrating things in this regard is the program is not telling me that anything is wrong, and it tells me it was completed successfully, when that's clearly not the case. 
looking at available formats, every single format is something that I downloaded with the other files, i'm honestly at a loss as to what the issue is. 

-------------

Just found out what the issue was, and this is a bit annoying, In the folder there is a "ytdl-archive" txt file, and inside it has the links of things already downloaded, ok, that's good and all, but apparently in me setting this up, it didn't download anything at some point, wrote in there that it was already downloaded and every subsequent try it decided to do nothing. 

Personally, I think it should be on people themselves to make sure they aren't getting dups or if they want to enable something to help, they enable it themselves. would it be possible to bypass this and if the same file is in the folder with the same name it gets a (X) at the end? 

I think this was causing most of my problems where I could get the file but then anything I tried doing after that would no longer work... a fun problem

--------------

outside of this, I think it would be a good idea to have a presetup music and video folder

**Comment by axcore** [comment]
@alidan, the ytdl-archive.txt file serves a very important purpose: downloading a channel or playlist is much, MUCH quicker when the file exists.

I think I will continue using the archive file (by default) in most folders, but I will remove it from 'Unsorted Videos'. That folder never receives channels or playlists, so it makes no sense to use ytdl-archive.txt there.

You can disable ytdl-archive.txt altogether: Edit > System preferences... > youtube-dl, then deselect 'Allow youtube-dl to create is own archive file...'

>Personally, I think it should be on people themselves to make sure they aren't getting dups or if they want to enable something to help, they enable it themselves. would it be possible to bypass this and if the same file is in the folder with the same name it gets a (X) at the end?

Unfortunately, youtube-dl provides very little information to Tartube. Tartube does the best it can, using the limited information it receives. 

>outside of this, I think it would be a good idea to have a presetup music and video folder

I think the list of folders on the left side of the main window is already too full.

**Comment by alidan** [comment]
With ytdl-archive.txt, would it be possible to separate its use from how videos are imported? Its use in a channel or a playlist is far more understandable then one off videos form places. If this isn't, would it be possible to have a dialogue pop up telling you one or more files you wanted to download were on an already downloaded list? I use an extension called 'copy all url's' due to many different mass download programs, I found it easier to just make a chrome window with everything I wanted and copy that way. I don't know how often a case like me would come up, but a popup telling me why something is not working the way I assumed it would would be helpful. 

as for the side being cluttered... i'm on a 4k monitor with no scaling, making the window 1080p size or even 720p size does not result in anything anything hiding/looking cluttered. But i'm also clearing out folders after a download is done to import more, for me this was just easier to check small batches of files rather than a large 100~ link download, I know better what was downloaded and when something doesn't do what I expect, i'm able to find out why.  i'll probably trust the program with more files now that its working and I know what was wrong. I'm assuming that channel and playlist downloads add folders (I have had no use for them yet so I don't know.) and if that's the case I can understand where clutter comes from, and if that's the case its it possible to implement a collapsible folder tree?

**Comment by axcore** [comment]
>With ytdl-archive.txt, would it be possible to separate its use from how videos are imported? Its use in a channel or a playlist is far more understandable then one off videos form places.

This is done and will be in the next release.

>it possible to implement a collapsible folder tree?

It should be possible to collapse the tree by clicking the arrow, just to the left of the folder icon. Is that what you meant?

![collapse2](https://user-images.githubusercontent.com/37951926/77625411-6f57cc80-6f3b-11ea-9856-c47b1202bed2.png)

**Comment by axcore** [comment]
Closed for inactivity.
