### ISSUE TITLE
Mac how to use an external drive as storage?

### ISSUE THREAD

**Issue by rattailgamer** [axcore/tartube#641]
I have a mac mini with only 120gb so I was hoping to change the storage to a bigger external drive. On my windows PC External Drives show up to add as database, but on Mac I can only interact with the main drive. Is there a way to make it work or would it maybe be for you possible too add?

Backstory if interested:
Unfortunately the problems with recording full livestreams at top quality still isn't working with yt-dlp on windows and is failing every time, otherwise I would have just switched to some old windows laptop for auto download. But bc of that I'm unfortunately stuck with the Mac, as the main Streamer I use this for puts some streams behind a paywall right after they end. 
So right now I have to make copy to my main PC every couple days to clear the space up again and I would like if I could just let it run and only copy when I am either looking for a specific stream or every couple weeks to then sort it on my main PC and delete unneeded streams.

**Comment by axcore** [comment]
I don't use a mac so I don't know anything about the intricacies of external drives. 

Users have reported that external drives are sometimes troublesome. The file selection window (in File > Database preferences...) is pure Gtk code, if it's not detecting an external drive then there may be nothing I can do about it.

A general solution is to run Tartube on whichever drive you're downloading files; this seems to prevent a lot of problems. It should [be possible to run Tartube's source code directly](https://github.com/axcore/tartube?tab=readme-ov-file#5310-run-without-installing), without installing it, so you could keep a copy on every external drive you use.
