### ISSUE TITLE
How to add custom format for Twitch Audio_Only (or other formats in the future)

### ISSUE THREAD

**Issue by EpiKnightz** [axcore/tartube#644]
When I try to fetch a list of available formats for twitch vod here is an example list:

```
[twitch:vod] <sth sth>: Downloading storyboard metadata JSON
------------------------------------------------------------------------------------------------
1080p60    mp4   1920x1080   60 | ~  4.03GiB 4299k m3u8  | avc1.64002A mp4a.40.2      Source
160p       mp4   284x160     30 | ~277.94MiB  289k m3u8  | avc1.4D000C mp4a.40.2
360p       mp4   640x360     30 | ~681.69MiB  709k m3u8  | avc1.4D001E mp4a.40.2
480p       mp4   852x480     30 | ~  1.30GiB 1383k m3u8  | avc1.4D001F mp4a.40.2
720p60     mp4   1280x720    60 | ~  3.16GiB 3362k m3u8  | avc1.4D0020 mp4a.40.2
Audio_Only mp4   audio only     | ~141.95MiB  148k m3u8  | audio only  mp4a.40.2 148k
ID         EXT   RESOLUTION FPS |   FILESIZE   TBR PROTO | VCODEC      ACODEC     ABR MORE INFO
[info] Available formats for v<sth sth>:
sb0        mhtml 220x124      0 |                  mhtml | images                     storyboard
sb1        mhtml 110x62       0 |                  mhtml | images                     storyboard
Info operation finished
```

But in Download option I can't find how to add a custom format (specifically, "Audio_Only") to the list of preferred formats, I even tried typing the extractor code manually but the app just showed "Unrecognized extractor code" error and prevented me from trying it.

**Comment by axcore** [comment]
Use -f FORMAT, where FORMAT is anything on in the column on the left. For example, -f Audio_Only, -f 1080p60, -f 160p.

Click Edit > General download options, and in the **Additional download options** box, add any options you like.

![aduioonly8](https://github.com/user-attachments/assets/2f64c42a-dbf6-4df9-aad9-4606f727f94e)
