### ISSUE TITLE
"Install FFMPEG" button does nothing

### ISSUE THREAD

**Issue by sergiohzph** [axcore/tartube#646]
I'm stuck here because it doesn't install FFMPEG when I press the button.

![image](https://github.com/user-attachments/assets/ee7dc23d-88b7-46d0-9cca-f5c1885f47f6)

### What operating system are you using?
Manjaro

### What version of Tartube are you using?
![image](https://github.com/user-attachments/assets/877f77ee-a729-4170-aa4c-69f9944cf528)

**Comment by axcore** [comment]
The "install ffmpeg" page should not be visible, it's a mistake. Please ignore it.

You can install FFmpeg in Manjaro's software manager, or you can open a terminal window and type:

sudo pacman -S ffmpeg

**Comment by axcore** [comment]
The extra page is removed in v2.5.040, which should resolve this ticket.
