### ISSUE TITLE
Tartube error: "cookies.txt does not look like a Netscape format cookies file"

### ISSUE THREAD

**Issue by Max475-star** [axcore/tartube#648]
I keep getting an error that says "cookies.txt does not look like a Netscape format cookies file" and I am unable to download any videos.

Windows 10 system
Tartube 2.5.0
yt-dlp: 2024.8.6 (latest)
FFmpeg: latest update

I have also included a screenshot of my Error/Warnings screen
![Capture](https://github.com/user-attachments/assets/78b53dbb-cfa1-4401-b530-6c1991fc4ff8)

**Comment by axcore** [comment]
That is a yt-dlp error message, so you should ask for advice on that page.

At a rough guess I'd say your cookies file has been corrupted. You could try deleting it, and then either [create a new one](https://github.com/axcore/tartube?tab=readme-ov-file#719-youtube-namepassword-not-accepted), or use the download options **--cookies-from-browser** (**Edit > General download options**, click the **Show advanced download options** button if it's visible, open the **Files > Cookies** tab, then find the **Browser** dropdown box and select your web browser)

**Comment by Max475-star** [comment]
Sorry for using the wrong page. Your advice worked, however, so thank you!

**Comment by axcore** [comment]
Great!
