### ISSUE TITLE
I can't download this video

### ISSUE THREAD

**Issue by saiwong123** [axcore/tartube#649]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Windows 10  22H2

### What version of Tartube are you using?
v2.5.0

### If your bug report is "I can't download this video", please provide a link to the video
youtube] Extracting URL: https://www.youtube.com/watch?v=LudgxrHrsGo
[youtube] LudgxrHrsGo: Downloading webpage
WARNING: [youtube] Webpage contains broken formats (poToken experiment detected). Ignoring initial player response
[youtube] LudgxrHrsGo: Downloading ios player API JSON
[youtube] LudgxrHrsGo: Downloading web player API JSON
WARNING: [youtube] API returned broken formats (poToken experiment detected). Retrying (1/3)...
[youtube] LudgxrHrsGo: Downloading web player API JSON
WARNING: [youtube] API returned broken formats (poToken experiment detected). Retrying (2/3)...
[youtube] LudgxrHrsGo: Downloading web player API JSON
WARNING: [youtube] API returned broken formats (poToken experiment detected). Retrying (3/3)...
[youtube] LudgxrHrsGo: Downloading web player API JSON
WARNING: [youtube] API returned broken formats (poToken experiment detected). Giving up after 3 retries
ERROR: [youtube] LudgxrHrsGo: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
[download] Downloading item 1330 of 1684
[youtube] Extracting URL: https://www.youtube.com/watch?v=d5m0YwO0yrE
[youtube] d5m0YwO0yrE: Downloading webpage
WARNING: [youtube] Webpage contains broken formats (poToken experiment detected). Ignoring initial player response
[youtube] d5m0YwO0yrE: Downloading ios player API JSON
[youtube] d5m0YwO0yrE: Downloading web player API JSON
WARNING: [youtube] API returned broken formats (poToken experiment detected). Retrying (1/3)...
[youtube] d5m0YwO0yrE: Downloading web player API JSON
WARNING: [youtube] API returned broken formats (poToken experiment detected). Retrying (2/3)...
[youtube] d5m0YwO0yrE: Downloading web player API JSON
WARNING: [youtube] API returned broken formats (poToken experiment detected). Retrying (3/3)...
[youtube] d5m0YwO0yrE: Downloading web player API JSON
WARNING: [youtube] API returned broken formats (poToken experiment detected). Giving up after 3 retries
ERROR: [youtube] d5m0YwO0yrE: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

**Comment by axcore** [comment]
>ERROR: [youtube] LudgxrHrsGo: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

YouTube is blocking  your IP address. Possible solutions include (1) changing your IP address, (2) wait a few days then try again, (3) log in to YouTube, (4) use a proxy. 

For some more discussions about this problem, see [this thread](https://github.com/yt-dlp/yt-dlp/issues/10128).
