### ISSUE TITLE
add peertube support

### ISSUE THREAD

**Issue by DontUseGithub** [axcore/tartube#65]
joinpeertube.org

**Comment by axcore** [comment]
Requests for new sites need to go on the [youtube-dl page](https://github.com/ytdl-org/youtube-dl/).

**Comment by DontUseGithub** [comment]
they support PeerTube https://ytdl-org.github.io/youtube-dl/supportedsites.html so tartube should too, that's great, sorry for opening this issue

**Comment by axcore** [comment]
No problem!
