### ISSUE TITLE
Do you have the guide as a PDF?

### ISSUE THREAD

**Issue by WonderWoman1977** [axcore/tartube#650]
Hello,

FYI - I checked the Read-Me and it is the actual source of my question.  Do you have the guide available as a PDF or Word file?

Thank you.

Sincerely,

WonderWoman1977

**Comment by axcore** [comment]
Here it is:

[TARTUBE README.pdf](https://github.com/user-attachments/files/16796288/TARTUBE.README.pdf)

Alternative link:

https://www.dropbox.com/scl/fi/2sgyfmyf37cecmv40u3p0/TARTUBE-README.pdf?rlkey=z7sh1qp5l8ohncx8sudwhz0jd&st=u627yno2&dl=0

**Comment by WonderWoman1977** [comment]
Thank you so much for this!  You’re the greatest!
