### ISSUE TITLE
Missing row in progress list

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#651]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
If using MS Windows, are you using Windows 10, Windows 7, or something else?
Win10

### What version of Tartube are you using?
I've confirmed the error in these versions:
2.5.021
2.5.028

I right clicked on a folder and downloaded it, that worked fine showing the channels in the top half of the Progress window.
While the original channels were in downloading, I right clicked on another folder and downloaded it.

Instead of adding those new channels to the top of the Progress window, this error came up:
#222 Missing row in progress list

![image](https://github.com/user-attachments/assets/017e49d6-7a5e-4f74-b183-bb6b77ed7f14)

The actual video downloads completed fine, and showed the videos in the new videos bottom panel.

This error wasn't in previous versions, but I'm not sure if it started in 2.5.021 or an earlier one.

Thanks Axcore!

**Comment by ceonelson** [comment]
I just found out that if I add only a single channel to the download queue, that channel with show in the Progress window.

But if I add a folder to the download queue, it will error and not show any of the channels under it in the Progress window.

**Comment by axcore** [comment]
Fixed in v2.5.040. Apologies for the inconvenience.

**Comment by ceonelson** [comment]
Just got a chance to confirm it works, thank you Axcore!
