### ISSUE TITLE
Loading Error???

### ISSUE THREAD

**Issue by Xoanon88** [axcore/tartube#653]
I am unsure if this is a Tartube "bug" or not but I thought I would start here.

I am using Windows 10 and have tried the Portable, EXE & EXE w/ ffmpeg version 2.5.040 and all of them give me the same error attached when I attempt to start using TT after installation or unpacking.

I have removed and updated to the latest version of Python and know nothing else to do.  

Can you shed some light as to what is causing this error?

Thank you!

![Error](https://github.com/user-attachments/assets/2e904f5f-10ce-43f7-bf87-62c3fc17dcef)

**Comment by axcore** [comment]
As a temporary workaround, you could try loading the most recent database backup; it should be in the .**backups** folder.

**Comment by Xoanon88** [comment]
I don't quite undersand what's going on with it.  I had to uninstall a version from Sourceforge because my AV said it had a Virus.  Ever since then, everytime I try to run either the Portable version or install the EXEs, I get the error message above.  It's like it won't even create a tartube.db file so I don't know if there's a backup file to even pull from as I don't even see the tartube.db file and I don't see a backups directory either.  Sorry, I don't mean to sound dense.  Thanks for the response!

**Comment by Xoanon88** [comment]
Sorry, I accidentally marked this as closed.  Duh me!

**Comment by Xoanon88** [comment]
OMG, I am so stupid.  This was a complete non-issue.  My apologies for wasting your time.  Everything's working fine now.  Keep up the good work and again, apologies for taking up your time!
