### ISSUE TITLE
If the video ID or URL is different and the video title is the same

### ISSUE THREAD

**Issue by Repetria** [axcore/tartube#658]
Please add the ability to put a separator like (1) next to the video name to prevent videos from being overwritten if they have different video IDs or URLs and the same video title.

I'm downloading videos with different URLs but the same title, and the addition of this feature is a huge help for people like me.

**Comment by axcore** [comment]
>If the video ID or URL is different and the video title is the same

This is a common problem. Use [output templates](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#output-template) to solve it.

In Tartube, click Edit > General download options... > Files > File names. In the drop-down box in the top-left corner, select Title + ID. Click OK to close the window and apply the changes.

![titleid](https://github.com/user-attachments/assets/f2901c70-8f18-4920-893d-2ad9e9fed4d9)

**Comment by Repetria** [comment]
네 저는 해당 옵션을 발견했고 제가 무식한 질문을 한 것 같아 이 문제를 닫았습니다. 해결로 표시를 바꾸겠습니다! 답변 감사합니다.

**Comment by Repetria** [comment]
Yes I found that option and closed this question because I was asking an ignorant question, thanks for the answer!

**Comment by axcore** [comment]
Tartube is complicated, there are no ignorant questions :)
