### ISSUE TITLE
only error/warning downloader

### ISSUE THREAD

**Issue by Repetria** [axcore/tartube#660]
Can you please create an error/warning folder so that I can only download videos with errors or warnings?
This would be a great time saver.

**Comment by axcore** [comment]
Have you tried filtering out downloaded videos? That should give you the same list of videos as the one you want, more or less.

In the Videos tab, in the bottom-right corner click the **Show more settings** tab. Then, on the bottom row, uncheck all the boxes except **Show undownloaded**.

![show](https://github.com/user-attachments/assets/0b2f4db5-f4b4-4b72-bbad-bcfba005c627)

You can select all of those videos by pressing CTRL+A, then right-click them and select **Download videos**.

**Comment by Repetria** [comment]
Hi, thank you for the solution. I was not aware of that, so thanks for the answer!
