### ISSUE TITLE
About Cairo bug in Debian and derivatives

### ISSUE THREAD

**Issue by luk9a** [axcore/tartube#663]
I'm using Debian 12, and after installed Calibre and dozens of python dependencies, I started to have the Cairo bug mentioned in (https://github.com/axcore/tartube/issues/592).

I made all the troubleshooting with the challenging "Externally Managed Environment Error when using Pip" with no success.

For what I understood, the library Matplotlib cannot see Cairo and displays the error "Gtk-based backends require cairo", which appears to be fixed in version 3.9.1 (https://github.com/matplotlib/matplotlib/pull/28451), but my system has the version 3.6.3.

After installing python3-gi-cairo solves the problem offering Python 3 Cairo bindings for the GObject library.

Thank you

**Comment by axcore** [comment]
I'm not able to reproduce this error on any of my machines, but perhaps we can find a workaround anyway. 

For example, what happens on an affected system if you edit ../tartube/config.py, replacing this:

```
# Import matplotlib stuff
if mainapp.HAVE_MATPLOTLIB_FLAG:
    from matplotlib.backends.backend_gtk3agg import FigureCanvasGTK3Agg
    from matplotlib.figure import Figure
    from matplotlib.ticker import MaxNLocator
```

with this?

```
# Import matplotlib stuff
if mainapp.HAVE_MATPLOTLIB_FLAG:
    try:
        from matplotlib.backends.backend_gtk3agg import FigureCanvasGTK3Agg
        from matplotlib.figure import Figure
        from matplotlib.ticker import MaxNLocator
    except:
        pass

```

**Comment by luk9a** [comment]
Removed python3-gi-cairo, Matplotlib couldn't see Cairo again.

Applied try and except for Matplotlib in /usr/lib/python3/dist-packages/tartube/config.py, Tartube opens and download videos normally.

Thank you for this great frontend!

**Comment by axcore** [comment]
Great, I added the check to today's release (git/pypi) only; there will be a full release in a few days.
