### ISSUE TITLE
Fails to update/download youtubedl

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#67]
Starting update operation, installing/updating youtube-dl
..\..\..\..\mingw64\bin\python3.exe ..\..\..\..\mingw64\bin\pip3-script.py install --upgrade youtube-dl
Collecting youtube-dl
  Could not fetch URL https://pypi.org/simple/youtube-dl/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/youtube-dl/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/youtube-dl/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/youtube-dl/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/youtube-dl/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/youtube-dl/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/youtube-dl/
  ERROR: Could not find a version that satisfies the requirement youtube-dl (from versions: none)
ERROR: No matching distribution found for youtube-dl
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Child process exited with non-zero code: 1
Update operation finished

**Comment by DankMemeGuy** [comment]
I solved that problem by downloading: https://slproweb.com/products/Win32OpenSSL.html

but now i get the following error when downloading:
https://i.imgur.com/e4qVgPb.png

**Comment by axcore** [comment]
99.9% of SSLcertificate errors are network problems. Try again in a day or two.

Downloading random executables from the internet is probably not going to help.

**Comment by DankMemeGuy** [comment]
For future people looking into this: https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error

This seems to be a problem that goes past this program.

**Comment by DankMemeGuy** [comment]
I found out I can include youtube dl options in the "general download options" under Edit. In case anyone in the future sees this problem

**Comment by axcore** [comment]
It can also be set in **Edit > General download options... > Advanced > Workaround > Suppress HTTPS certificate validation**
