### ISSUE TITLE
[Question] Privacy Policy

### ISSUE THREAD

**Issue by Looodon** [axcore/tartube#675]
Hey!

I'm very excited to try out Tartube and I was wondering what the privacy policy is. I know that there's contact between the Tartube/yt-dlp user and Youtube (which collects data as per Youtube's privacy policy), I am instead asking if Tartube itself collects any data or shares any data with third parties

Thank you!

**Comment by axcore** [comment]
Tartube does not collect any data and does not share anything with third parties.

The only time that Tartube connects to the internet is when you click Help > Check for updates; everything else is handled directly by yt-dlp and the other downloaders.
