### ISSUE TITLE
Authentification help

### ISSUE THREAD

**Issue by AplhaSlayer1964** [axcore/tartube#68]
So I added my username and password but still get errors saying I can't log in. I do not have two-factor enabled on this account.

**Comment by axcore** [comment]
1. In the Tartube main window, find a video that hasn't been downloaded yet
2. Right-click the video, and select Downloads > Test system command
3. In the dialogue window, enter `-u yourname -p yourpassword`

![password1](https://user-images.githubusercontent.com/37951926/77732418-b0fc7c00-6ffc-11ea-91dd-95668a6def15.png)

4. Click the OK button to start the test download
5. In the main window, click the Output tab to see the results
6. If the test finishes with a `WARNING: Unable to log in: HTTP Error 400: Bad Request` error, then it's a youtube-dl issue that can be reported [here](https://github.com/ytdl-org/youtube-dl/issues)

You could so the same test from the command line, by typing `youtube-dl -u yourname -p yourpassword <URL>`

**Comment by AplhaSlayer1964** [comment]
yep, I am getting the WARNING: Unable to log in: HTTP Error 400: Bad Request. I'll go look and see if others have found a solution. The funny thing is I switch from jdownloader2 because it didn't allow logins. rip

**Comment by AplhaSlayer1964** [comment]
Found this worked as a solution to youtube login at least. Hope it can help someone https://github.com/ytdl-org/youtube-dl/issues/21313#issuecomment-499496235

**Comment by axcore** [comment]
Splendid, I will add the same information to the Tartube FAQ.

**Comment by AplhaSlayer1964** [comment]
Oh, I forgot to mention you will still get WARNING: Unable to log in: HTTP Error 400: Bad Request but it will still login and it will download anything that required a login. Tested with a private playlist and a user-defined age-restricted video.

**Comment by axcore** [comment]
Yes, I get the same thing: videos download and I get a warning.

**Comment by Wr15** [comment]
Is there any firefox version of the cookies app that works with youtube dl?

**Comment by kingssword9** [comment]
so how do you add this to tartube with the cookies option? Im not sure how i will add this on tartube windows.

**Comment by axcore** [comment]
Edit > General download options > Files > Cookies

If you let your mouse hover over the box near the top, you can see which download option is being set
