### ISSUE TITLE
Download folder different than where the database is

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#69]
I want the program stored on my C drive (it defaults to appdata). However, i want all the folders it saves in to be on my external hdd. Right now it looks like the database file has to be in the same folder as the videos? can this be separated somehow?

My external drive is a virtual google drive file stream so I think that's causing it problems but only due to the database being saved there. If i could have the database on C, but the videos on external I think it would work.

**Comment by axcore** [comment]
>Right now it looks like the database file has to be in the same folder as the videos? can this be separated somehow?

No, it's not possible. Tartube writes a number of files to the same folder as the videos. If it can't write its database file, then it won't be able to write any of the other files. 

If that's the case, there is no advantage to using Tartube over something simpler like [youtube-dl-gui](https://mrs0m30n3.github.io/youtube-dl-gui/), so you might as well use that.

**Comment by axcore** [comment]
Does this problem occur 100% of the time, or just some of the time?

If just some of the time, we could create a _backup_ copy of the database file on a different hard drive, in case the original copy can't be saved.

**Comment by DankMemeGuy** [comment]
I realized that when I closed the software it had an icon open in my traybar (i have a lot of things running) so I didn't notice the icon since it was still downloading. So when I opened a new instance it caused the problem.

Long story short: it works fine having the files on my Google Drive mount.

**Comment by axcore** [comment]
You can disable that behaviour, if you want. **Edit > System preferences... > Windows > System tray**, and deselect **Close to the tray, rather than closing the application**.
