### ISSUE TITLE
Unsightly terminal window

### ISSUE THREAD

**Issue by beefeater7** [axcore/tartube#7]
Sorry to be anal, but please hide the background machinery.
![terminal window](https://user-images.githubusercontent.com/10468970/60341217-4f3fb080-999d-11e9-8dd7-1e13f7cdc79a.PNG)

**Comment by axcore** [comment]
The terminal window is temporary, while I investigate crash reports I've been receiving. I appreciate it is annoying, and will definitely be removed as soon as possible.

**Comment by axcore** [comment]
The window is removed in v0.7.0
