### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#70]
Where would I find the logfile? It keeps crashing and I can't seem to recreate the problem. It seems random, but happens often

**Comment by axcore** [comment]
Which operating system are you using?

**Comment by DankMemeGuy** [comment]
I'll try that out!


It's Windows 10 Pro.

**Comment by DankMemeGuy** [comment]
I tried that out and still crashes!

**Comment by axcore** [comment]
Logfiles can only be enabled by editing the source code. If you have five minutes and nothing better to do, this is how to do it:

1. First find where Tartube is installed. On MS Windows, it is C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube\tartube

2. (This is a hidden folder. You must enable hidden folders on your system).

3. Open the file mainapp.py in a text editor. Change line 78 from this:

DEBUG_FUNC_FLAG = False

To this:

DEBUG_FUNC_FLAG = True

Change line 81 from this:

DEBUG_NO_TIMER_FUNC_FLAG = False

to this:

DEBUG_NO_TIMER_FUNC_FLAG = True

4. Open the file mainwin.py in a text editor. Change line 56 from this:

DEBUG_FUNC_FLAG = False

to this:

DEBUG_FUNC_FLAG = True

Change line 60 from this:

DEBUG_NO_TIMER_FUNC_FLAG = False

to this:

DEBUG_NO_TIMER_FUNC_FLAG = True

5. Open the file downloads.py in a text editor. Change line 55 from this:

DEBUG_FUNC_FLAG = False

to this:

DEBUG_FUNC_FLAG = True

6. Now run the programme C:\Users\YOURNAME\AppData\Local\Tartube\msys64\mingw64.exe

7. In the terminal window, type these commands. Make sure you use a forward slash:

cd tartube
python3 tartube/tartube

8. Tartube runs, and you can see the logfile in the terminal window. When Tartube crashes, take a screenshot of the terminal window.

**Comment by heywolf15** [comment]
This command `cd tartube` give me, 
-bash: cd: tartube: No such file or directory

**Comment by axcore** [comment]
Thanks to [boogiepop](https://github.com/axcore/tartube/issues/79) I discovered that it's the wrong command. Use this instead:

```
cd /home/user/tartube
python3 tartube/tartube

```

**Comment by axcore** [comment]
I have made a few stability improvements today. This might help you with your problem, when the next release is ready.

**Comment by axcore** [comment]
These stability fixes are in today's release, v2.1.0.

**Comment by heywolf15** [comment]
Still likely to crash when checking a channel
