### ISSUE TITLE
Tartube cannot write to this folder after restart.

### ISSUE THREAD

**Issue by AplhaSlayer1964** [axcore/tartube#71]
I restarted my PC and when it turned back on and I launch Tartube I get "The Tartube data folder is set to D:\YouTube ...but Tartube cannot write to this folder" Yes the drive is mounted I tested moving files and running a program off of it and everything else works. Also when I select any of the options Tartube locks up can't even quit it out and I have to use task manager to kill the task.

**Comment by axcore** [comment]
Sounds like a python crash. Run Tartube from a terminal window so we can see the error message.

In the terminal window, type these commands. Make sure you use a forward slash:

```
cd tartube
python3 tartube/tartube
```

![tartubeterm](https://user-images.githubusercontent.com/37951926/77890314-32574700-7267-11ea-9ffc-95d0879be240.png)

Tartube runs, and you can see the logfile in the terminal window. When Tartube crashes, take a screenshot of the terminal window.

**Comment by AplhaSlayer1964** [comment]
I get 
"-bash: cd: tartube: No such file or directory"
when I try to cd tartube

**Comment by AplhaSlayer1964** [comment]
I feel like somehow the files got corrupted because I can create a data folder on the drive but the error only occurs in that folder. I ended up just moving the downloaded files to a new folder and setting that as the data folder. Had to re-add every channel sadly.

**Comment by AplhaSlayer1964** [comment]
Just had it scan all my added channels and it crashed and is back to giving me the same error. :/ rip

**Comment by AplhaSlayer1964** [comment]
I'm just gonna close the thread because I believe it somehow just messed up when quitting out one and it messed up the files it creates in the data folder. Completely deleted the old data folder and it is working fine again.
