### ISSUE TITLE
Tartube is assuming the Gtk v3 is broken

### ISSUE THREAD

**Issue by ale5000-git** [axcore/tartube#72]
When running it on Xubuntu, I get in terminal:
`(tartube:15693): Gdk-CRITICAL **: 01:28:05.538: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed`

And inside the app:
`#140: Tartube is assuming the Gtk v3 is broken; some (minor) features are disabled`

The app seems to work correctly but I wonder what is the problem.

**Comment by axcore** [comment]
Hi @ale5000-git,

The Gtk graphics library on most Linux distros is buggy and prone to issuing error messages and crashing.

The first error is generated when Tartube adds an icon to the system tray. I don't know how to make it go away, but it's harmless.

The second warning is generated by Tartube, if the version of Gtk installed on your system is one of the buggy ones. To prevent crashes, some features are then disabled (for example, the list of channels/playlists/folders isn't updated during a download). The disabled features are purely cosmetic; functionality is not changed at all.

To disable the second warning, click Edit > System Preferences... > Windows > Errors/Warnings > Deselect 'Show Tartube warning messages'

To enable the cosmetic features, click Edit > System preferences... > General > Modules > Deselect 'Assume that Gtk is broken, and disable some features'

**Comment by ale5000-git** [comment]
I'm using Xubuntu 20.04 beta, could it be a false positive?

Is it possible to see what part exactly is detected as broken?

**Comment by axcore** [comment]
There is nothing that can be done until Gtk is fixed, and until those fixes are added to the distributions. That may take some months or years.

**Comment by ale5000-git** [comment]
Do you have a link that explain in detail the problems with references to the sources?

**Comment by axcore** [comment]
No. Fixing bugs in python and Gtk is way beyond my pay grade.

All the crash problems are marked in the Tartube source code, for anyone who cares to look. The workarounds are in `tartube/mainapp.py` and especially in` tartube/mainwin.py`, and can be found by searching for gtk_emulate_broken_flag.

The `gdk_window_thaw_toplevel_updates` error is not marked in the Tartube source code. Tartube creates a [Gtk.StatusIcon](https://developer.gnome.org/gtk3/stable/GtkStatusIcon.html). (In yesterday's release, the code is in `tartube/mainwin.py`, the `StatusIcon` class, lines 13428-13748). At some fraction of a second later, that icon becomes visible in the user's system tray, and the system generates the error.
