### ISSUE TITLE
First time user, need some orientation

### ISSUE THREAD

**Issue by KirbyFan102** [axcore/tartube#73]
First off, how do I download a video? I tried doing it, but it didn't work.
Second, is it possible to embed the thumbnail of the video (and/or the metadata) in the downloaded file? I know youtube-dlg had an option for that.
Third, how to I download region-locked videos?

**Comment by axcore** [comment]
Hi @KirbyFan102,

1. Can you be a bit more specific when you say "I tried doing it, but it didn't work" ?

Probably youtube-dl is not installed on your system. [See this](https://github.com/axcore/tartube#check-youtube-dl-is-updated) to fix that.

2. Yes, but it doesn't work for every video format, and the thumbnail is only embedded in an audio file. (This is a limitation of youtube-dl).

First make sure that ffmpeg is installed on your system. [Read this](https://github.com/axcore/tartube#setting-the-location-of-ffmpeg-avconv).

Then click **Edit > General download options...** 

In the new window, click the **Show advanced download options** button

Then click the **Post-process** tab, and select **Embed thumbnail in audio file as cover art** and/or **Write metadata to the video file**

3. Subscribe to a [VPN](https://en.wikipedia.org/wiki/Virtual_private_network). youtube-dl does offer some bypasses for region-locked videos, but it doesn't work most of the time. (YouTube will probably just ignore the setting.)

Click **Edit > General download options...**

In the new window, click the **Show advanced download options** button

Then click **Advanced > Geo-restriction**, and enter a country code in the box. There is a list of country codes [here](https://www.iso.org/obp/ui/#search).

**Comment by KirbyFan102** [comment]
First off, thanks for the very informative reply. I want to point that I did install youtube-dl, using the command pip install --upgrade youtube-dl. Was I wrong to do that?

Also, one other thing. Because I sort my videos by artist, I would like to change the download directory on a case-by-case basis. How should I go about doing so? It's easy enough on Youtube-dlg, where you just select the folder on the drop-down menu before adding your video, but I'm having difficulty finding a similar option in tartube.

**Comment by axcore** [comment]
>I want to point that I did install youtube-dl, using the command pip install --upgrade youtube-dl. Was I wrong to do that?

On MS Windows ONLY, there are some restrictions. Tartube is running in a virtual environment, so youtube-dl must be installed in the same virtual environment. 

So that users didn't get themselves tied in knots, I implemented a simple installation method: click Operations > Update youtube-dl. 

You _could_ install youtube-dl from the command line, using `pip install --upgrade youtube-dl`. This must be done by running the msys terminal application,`C:\Users\YOURNAME\AppData\Local\Tartube\msys64\mingw64.exe`, and typing the command there.

This restriction does not apply to any other operating system.

If you are sure youtube-dl is installed, it may be that Tartube is looking for it in the wrong location. Try [reading this](https://github.com/axcore/tartube#setting-youtube-dl-s-location).

**Comment by axcore** [comment]
> Also, one other thing. Because I sort my videos by artist, I would like to change the download directory on a case-by-case basis. How should I go about doing so?

![ymca2](https://user-images.githubusercontent.com/37951926/79037867-a7623f00-7bcc-11ea-864e-b063f2fbbfbd.png)

Individual videos are downloaded to `Unsorted Videos` by default, but you can choose a different folder in the Add videos window. (Is that what you meant?)

There is also a download option; for example, click **Edit > General download options... > Files > Filesystem** and set the option marked **Download all videos into this folder**.

**Comment by KirbyFan102** [comment]
I was able to sucessfully install youtube-dl with your instructions. Thank you.

As for the other thing... when I try to add a new video, the only options are unsorted videos or temporary videos. I don't understand why I can't easily select another folder when downloading. I have to use add folder to select them, which is impractical with the amount of folders I have. Not to mention the need to make new ones as I download more content.
This program seems to be constructed with the assumption that the user should only download into the tartube folder, which is highly inconvenient for new users who don't want to mess with their old folder structure or the locations of their videos. I have hundreds of gigabytes of videos on my hard drive, all carefully separated by artist, playlist and more. Why should I abandon all that just so I can use this program?

**Comment by KirbyFan102** [comment]
Again, if I could just select a different folder upon starting every new download, this would be much simpler. Youtube-dlg has that, why not here? Why is it so much more complicated?

**Comment by axcore** [comment]
Closed for inactivity. I think the last post was addressed in v2.1, when the Classic Mode tab was added. Feel free to re-open the issue if not.
