### ISSUE TITLE
Having issues, unable to debug.

### ISSUE THREAD

**Issue by strunberg** [axcore/tartube#74]
https://i.imgur.com/HctApgG.png

That's what python says.

Why I'm trying to debug.

https://i.imgur.com/LrDRx5o.png

This was after I accidentally opened up two instances  of the program. I closed both copies and now everything is greyed out as seen in the picture.

This happened to me after the program decided to shut itself off and I tried to reboot it.

**Comment by axcore** [comment]
Go into the folder into which Tartube downloads videos. There should be a file there called tartube.db.lock. Delete that file, and you're good to go.

The lock file prevents a second copy of Tartube overwriting files that the first copy is still using. If the first copy doesn't shut down cleanly (for some reason), the lock file doesn't get removed.

**Comment by strunberg** [comment]
> 
> 
> Go into the folder into which Tartube downloads videos. There should be a file there called tartube.db.lock. Delete that file, and you're good to go.
> 
> The lock file prevents a second copy of Tartube overwriting files that the first copy is still using. If the first copy doesn't shut down cleanly (for some reason), the lock file doesn't get removed.


I deleted everything, ran CC cleaner.

When I was simulating a channel download tartube crashed on me.

Now it says there's a 2nd instance of tar tube running the database.

I clicked not.

Restarted the program like it said to do so, now the program doesn't have the channel that I was archiving/downloading.

**Comment by axcore** [comment]
Ok, several problems here:

1. CC cleaner - this is not necessary. The Tartube installer doesn't make any changes to the Windows Registry or anything like that. If you want to uninstall it, from the Start menu, click Tartube > Uninstall Tartube. If you don't trust the installer and want to do it yourself, just delete the folder where Tartube is installed (C:\Users\YOURNAME\AppData\Local\Tartube.

2. Tartube crashes - if you add lots of channels and/or playlists, save the database before you start downloading things. Then, if Tartube crashes, you won't lose anything.

3. Everything is purged from the Tartube database - Tartube makes a backup of the previous database file, before saving a new copy. If the database gets corrupted for any reason, you can just revert to the backup. The backups are stored in the same folder as the videos - in a sub-folder called .backups

To change how often Tartube backs up the database file, in the Tartube window click Edit > System preferences... > Filesystem > Backups, and choose one of the options.

4. Tartube has forgotten the channels you were downloading - you can export a list of channels/playlist. From the Tartube window, click Media > Export from database. 

You can export a plain text file (easily readable by humans) or a JSON file (which isn't). Both types of backup can easily be re-imported at a later date (click Media > Import into database)

5. The folder and thumbnails still exist - if you were downloading the pewdiepie channel, then add the channel again (with the same name). 

Then right-click the channel, and select Check channel. Tartube repopulates the database (this will only take a few seconds/minutes).

Then right-click the channel again, and select Channel actions > Refresh channel. Tartube will look for all the videos your already have, and try to match them with its database. (This will only take a few seconds/minutes).

Alternatively, just create a channel with the same name, and download it again. youtube-dl won't download a video that already exists on your filesystem, so you won't waste much time.

**Comment by strunberg** [comment]
Alright. Thanks. BTW FFMPEG works now when it didn't on a previous verison.
