### ISSUE TITLE
Geo-restrictions clarification

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#75]
Just wanted some clarification on these settings.

- for the "use this proxy to verify ip address" what is that meant to be? What do you mean by verify IP address?
- When bypass via fake X-Frowarded-For HTTP is checked, do anything else have to be set for geo-restriction bypass to work?
- Bypass restriction with country code; what does this mean? If i put the country code for the US, would I need to set anything else? would all traffic show as the US?

**Comment by axcore** [comment]
I don't know the answers to any of these questions. These are not Tartube settings, they are [youtube-dl](https://github.com/ytdl-org/youtube-dl/) settings. Tartube doesn't do anything with them; it just passes them to youtube-dl.

This is what the youtube-dl documentation says:

`--geo-verification-proxy URL     Use this proxy to verify the IP address for
                                 some geo-restricted sites. The default
                                 proxy specified by --proxy (or none, if the
                                 option is not present) is used for the
                                 actual downloading.
--geo-bypass                     Bypass geographic restriction via faking
                                 X-Forwarded-For HTTP header
--no-geo-bypass                  Do not bypass geographic restriction via
                                 faking X-Forwarded-For HTTP header
--geo-bypass-country CODE        Force bypass geographic restriction with
                                 explicitly provided two-letter ISO 3166-2
                                 country code
--geo-bypass-ip-block IP_BLOCK   Force bypass geographic restriction with
                                 explicitly provided IP block in CIDR
                                 notation`

**Comment by axcore** [comment]
Closed for inactivity.
