### ISSUE TITLE
gnome software thinks its proprietary

### ISSUE THREAD

**Issue by philipzae** [axcore/tartube#76]
![preview](https://imgur.com/N11ox4K.png)

**Comment by axcore** [comment]
Oh dear, I think the installer is misconfigured.

By the way, Tartube is 100% open-source software :)

**Comment by philipzae** [comment]
Yes i checked and had seen the GNU license, which was why i filed the report. ;D

**Comment by axcore** [comment]
I'm not sure what the problem was, but it seems to be fixed as of v2.1.0.

![freenow](https://user-images.githubusercontent.com/37951926/81270823-33884a80-9043-11ea-99b6-199f6bfa4e81.png)
