### ISSUE TITLE
Would like UI similar to how it looked before the fork

### ISSUE THREAD

**Issue by philipzae** [axcore/tartube#77]
![preview](https://raw.githubusercontent.com/MrS0m30n3/youtube-dl-gui/gh-pages/images/ydlg_ui.gif)

**Comment by axcore** [comment]
This is finished, and will be in the next release.

![example20](https://user-images.githubusercontent.com/37951926/80008201-52250800-84bf-11ea-823c-28df35a1bf3c.png)

**Comment by philipzae** [comment]
Nice. Thanks.

**Comment by axcore** [comment]
Added in v2.1.0.

**Comment by candrapersada** [comment]
why not found download options only for Classic Mode? not for general download options?

**Comment by axcore** [comment]
Yes, that's a good idea

**Comment by candrapersada** [comment]
But why can the settings be wrong for Classic Mode?

**Comment by axcore** [comment]
What do you mean, wrong?

**Comment by candrapersada** [comment]
general download options wrong for Classic Mode
![image](https://user-images.githubusercontent.com/36833664/81381530-15037b80-9137-11ea-8d8a-ce2619de49fa.png)
![asasasa](https://user-images.githubusercontent.com/36833664/81381641-39f7ee80-9137-11ea-85e4-21db0f3ac460.PNG)

**Comment by axcore** [comment]
I'm very sorry, I still don't understand you.

**Comment by candrapersada** [comment]
why no download options apply and edit download options Classic Mode
![aaaaaa](https://user-images.githubusercontent.com/36833664/81428154-127c4280-9186-11ea-8ac5-951da80b519c.PNG)
![asaaaa (1) 70](https://user-images.githubusercontent.com/36833664/81428076-ed87cf80-9185-11ea-8c97-c7bc3844b482.png)

**Comment by axcore** [comment]
Ok, understood

I can change that behaviour in the next release.

**Comment by candrapersada** [comment]
Add a new Profile and Switch between profiles download options

**Comment by candrapersada** [comment]
move it preferred format
![image](https://user-images.githubusercontent.com/36833664/82298609-93d1a180-99de-11ea-9a89-7ca9570a9b70.png)
and merge is required after post-processing, output to this format
![image](https://user-images.githubusercontent.com/36833664/82298825-e01ce180-99de-11ea-9fd5-0462cc7f2ac6.png)
to only for Classic Mode
![aaaaaaaaaaa](https://user-images.githubusercontent.com/36833664/82299254-7bae5200-99df-11ea-9a99-3a24a60a45f9.PNG)

**Comment by candrapersada** [comment]
why is there a file .description, .info.json, and jpg for Classic Mode?

**Comment by axcore** [comment]
Yes, that is a good idea.

I changed the code; they are all disabled by default in the Classic Mode. (The new code will be in the next release.)

![archive](https://user-images.githubusercontent.com/37951926/83527210-65c08700-a4df-11ea-8663-1ef60d88ccaf.png)

**Comment by candrapersada** [comment]
please change download options for Classic Mode

**Comment by axcore** [comment]
Change them, how?

**Comment by candrapersada** [comment]
change filesystem overrides for download options Classic Mode
![82298609-93d1a180-99de-11ea-9a89-7ca9570a9b70](https://user-images.githubusercontent.com/36833664/83631853-641ebe00-a5c8-11ea-9f41-69f34399a247.png)

**Comment by axcore** [comment]
Added in v2.1.051.

**Comment by candrapersada** [comment]
Would like UI similar with FFmpeg GUI

**Comment by candrapersada** [comment]
how to save link URL to Classic Mode?
