### ISSUE TITLE
when downloading entire channels tartube doesn't create folders for play lists, and then sticks the respective files in the playlist folders.

### ISSUE THREAD

**Issue by strunberg** [axcore/tartube#80]
https://www.youtube.com/user/ForgottenWeapons/playlists

https://www.youtube.com/user/Drachinifel/playlists

It would also be nice for instance if tartube would download all of the videos to the central folder, then create shortcuts to the video files in the playlists that tartube detects the videos in.

Meaning the dinosaur hunting guns video play list would have short cuts to those videos from the main folder. 

The reason being is that there are a lot of cross-overs such as videos on forgotten turn of the century semi-auto Italian pistols that would be in the Italy folder, but same videos would also be in the Semi-auto pistol folder.

That way a video program could load up those shortcuts from the Italian folder so you won't have to have copies of videos which drive up the storage needs immensely. 

I'm trying to archive channels before 2020 elections, I've counted 16 channels that I plan to archive.

**Comment by axcore** [comment]
Impossible. youtube-dl (and therefore Tartube) doesn't know anything about channels or playlists. It just sees a webpage with one or more videos on it. 

If you want to download a whole channel, and sort its videos into playlists, [this is how to do it](https://github.com/axcore/tartube#combining-one-channel-and-many-playlists).

**Comment by axcore** [comment]
Closed for inactivity.
