### ISSUE TITLE
what software did you use to create the graphical interface?

### ISSUE THREAD

**Issue by strunberg** [axcore/tartube#81]
I got some ideas for expanding the features of you program, never programed before so I want to give programing a shot.

**Comment by axcore** [comment]
Tartube is written in Python 3. There are a million tutorials available online. Make sure you find one for Python 3, not the older Python 2.

The graphical library is Gtk 3. There is a tutorial for that [here](https://python-gtk-3-tutorial.readthedocs.io/en/latest/). The tutorial may be confusing for absolute beginners.

Gtk is a Linux library, so hopefully you already have Linux already installed on your computer (perhaps on a virtual hard drive, for example using [VirtualBox](https://www.virtualbox.org/).

If you want to install Python 3 / Gtk 3 on MS Windows, then you can [use the same method that I used](https://github.com/axcore/tartube/blob/master/nsis/tartube_install_64bit.nsi).

**Comment by strunberg** [comment]
What icon did you use to add the black navigation arrow for folders that have a playlist in them?

I know which is the yellow folder icon.

**Comment by axcore** [comment]
![blackarrow](https://user-images.githubusercontent.com/37951926/82289606-10dc2700-999d-11ea-9805-8d7b657a59f1.png)

This arrow?

The list of channels/playlists/folders on the left side of the main window is just a Gtk.Treeview, created in a call to mainwin.video_index_reset().

The Gtk.Treeview contains a Gtk.TreeModel (actually a Gtk.TreeModelSort), which contains the data to be displayed.

A new row is added to the Gtk.TreeModel in a call to mainwin.video_index_setup_row(). 

Let's say you want to create a playlist inside a folder. First we call Gtk.TreeModel.append() for the folder. This call returns a pointer (which specifies the folder's position in the list). Then we call Gtk.TreeModel.append() for the playlist, using the pointer as an argument. This places the playlist inside the folder.

**Comment by strunberg** [comment]
Very cool. Thanks. I just upgraded to a 9900k from my i5-750, sorry that it
took a while for me to get back to you.

**Comment by axcore** [comment]
Closed for inactivity.
