### ISSUE TITLE
Can't download multiple video with the same name

### ISSUE THREAD

**Issue by heywolf15** [axcore/tartube#83]
I'm just checking the channel, but there's a multiple video with the same title and can only recognize one of them. But all the video can be seen on the output

**Comment by axcore** [comment]
Can you tell me which channel you are downloading?

**Comment by heywolf15** [comment]
No sorry, but I try other channel with the only different is the title using emoji in the end.
Still can't pick up all.

The ytb-dl can recognize it but Tartube can't?

**Comment by axcore** [comment]
Ok, as I understand, you are trying to download a channel, and all the videos have the same name. Therefore Tartube only recognises one video.

Try this:

**Edit > General download options... > Files > File names**

In the box **Format for video file names**, select **Title + ID**

Click OK to close the window, and try checking the channel again

**Comment by heywolf15** [comment]
OK I didn't know that, I'm gonna use that for now. Thank you
But the channel just gone lol

**Comment by axcore** [comment]
Closed for inactivity.
