### ISSUE TITLE
No download speed.

### ISSUE THREAD

**Issue by LEADERS22** [axcore/tartube#84]
It used to work fine but yesterday it started messing up it kept going down from the usual 1mb/s to less than 10kb/s. i tried uninstalling then reinstalling but still nothing.

**Comment by axcore** [comment]
Click Operations > Test youtube-dl

Enter the URL for any video. For example you can use [the one I use for testing](https://www.youtube.com/watch?v=0RfIn-LrZ3w).

Click the OK button and an (invisible) download will start. Click the Output tab to see the results. You should see a lot of lines like this

`[download]  44.4% of ~113.78MiB at  1.82MiB/s ETA 00:38`

Are you getting 1mb/s download speeds, or 10kb/s?

**Comment by LEADERS22** [comment]
The problem seems to have fixed it self but if it to happen again i'll take a screenshot of it.

**Comment by LEADERS22** [comment]
Their  it goes again but this time it keeps jumping between 500 and 10 kb/s. btw its a twitch link and don't mind the version i downgraded to see if it will fix the issue.
![2](https://user-images.githubusercontent.com/51100531/80527899-65d7df00-8995-11ea-8d9c-f0b18851a978.png)
![1](https://user-images.githubusercontent.com/51100531/80527905-68d2cf80-8995-11ea-9b3a-64b160adf20a.png)

**Comment by axcore** [comment]
I tried downloading the same video, using v2.0, and I experienced normal download speeds.

![ingrid1](https://user-images.githubusercontent.com/37951926/80566297-926a1600-89ea-11ea-8b37-514a3ef14014.png)

Tartube does not download anything; youtube-dl does that. Changing the Tartube version doesn't matter, because you probably have the most recent version of youtube-dl.

**Comment by LEADERS22** [comment]
The problem is that it starts downloading at normal speed then all of a sudden after some time it jumps down to 10kb/s. I'll try reinstalling youtube-dl to see if it'll fix it.

**Comment by axcore** [comment]
Are you using MS Windows? Tartube installs youtube-dl inside a virtual environment, so it has to be uninstalled/reinstalled inside that environment.

The cleanest way to do it is to uninstall Tartube, which deletes the folder containing all youtube-dl stuff (`C:\Users\YOURNAME\AppData\Local\Tartube\`)

**Comment by axcore** [comment]
Closed for inactivity.
