### ISSUE TITLE
tartube portable?

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#85]
tartube portable support for Windows?

**Comment by axcore** [comment]
Tartube is already 100% portable on MS Windows. You can install it anywhere you want.

**Comment by candrapersada** [comment]
how to portable without install?

**Comment by axcore** [comment]
You have two choices:

1. Read [section 5.1.1](https://github.com/axcore/tartube#installation).

This section says, "install MSYS2 at **C:\msys64,**", but you can install it anywhere, for example **D:\MyStuff\Internet\Special\Whatever\msys64**

2. Use the Tartube installer. Let it install Tartube at the default location, which is

**C:\Users\YOURNAME\AppData\Local\Tartube**

When the installer is finished, you can move that folder anywhere, for example to **D:\MyStuff\Internet\Special\Whatever\Tartube**.

The installer doesn't add anything to the Windows registry.

To start Tartube, execute the file **C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube\tartube_64bit**. On a 32-bit computer, it is *C:\Users\YOURNAME\AppData\Local\Tartube\msys32\home\user\tartube\tartube_32bit**.

**Comment by candrapersada** [comment]
I ask for a link download tartube without setup. use folder zip, rar, or 7zip.

**Comment by axcore** [comment]
That doesn't exist at the moment.

**Comment by candrapersada** [comment]
add folder portable for be in future

**Comment by axcore** [comment]
>add folder portable for be in future

Why? Creating a release takes a long time. I don't want to spend hours doing something, unless there is a good reason.

**Comment by djmattyg007** [comment]
There's a lot of value in being able to have portable applications. The two most prominent reasons are:

1. Able to install on a USB drive and use on any computer
2. Keeps your system installation cleaner by having less system files lying around

Check out https://portableapps.com (not that you have to follow that standard or specifically get it uploaded there)

**Comment by axcore** [comment]
@djmattyg007, the MS Windows installer can already do both of those things.

**Comment by candrapersada** [comment]
is there an MSYS2 alternatives portable?
and update tartube from
`..\..\..\mingw64\bin\python3.exe ..\..\..\msys64\home\user\tartube\pip3-script.py install --upgrade tartube`

**Comment by axcore** [comment]
There are only two ways of installing Tartube on MS Windows:

1. Use the installer
2. Installl Tartube manually, see [here](https://github.com/axcore/tartube#511-manual-installation---ms-windows)

**Comment by axcore** [comment]
v2.1.051 has both the normal and installer, and a portable edition.

**Comment by candrapersada** [comment]
how to update version Tartube without change folder portable and without downloading manually source code from Sourceforge or GitHub?

**Comment by axcore** [comment]
It cannot be done at the moment.

**Comment by candrapersada** [comment]
how to get the icon for tartube portable?

**Comment by axcore** [comment]
The Tartube icons are in ..\tartube\msys64\home\user\tartube\icons\win

**Comment by candrapersada** [comment]
but icon files not found or not working
![a](https://user-images.githubusercontent.com/36833664/86527904-83618180-becd-11ea-84b8-7a951efb9dff.PNG)
![b](https://user-images.githubusercontent.com/36833664/86527916-9b390580-becd-11ea-9677-11037eb61672.PNG)

**Comment by axcore** [comment]
Do you mean, the Tartube icon is not installed on your system? 

That is what I expect. In the portable edition, nothing is installed on the computer. Download the code and extract it. That creates a folder called `tartube`. That folder can be copied anywhere, and Tartube will still run.

**Comment by candrapersada** [comment]
[tartube_icon.zip](https://github.com/axcore/tartube/files/4874733/tartube_icon.zip)

**Comment by candrapersada** [comment]
why can't update Tartube without using Download the Tartube source code from Sourceforge and Extract it into the folder C:\msys64\home\YOURNAME, creating a folder called C:\msys64\home\YOURNAME\tartube.
by using update pip3 with In the MINGW64 terminal, type:
`pip3 install --upgrade tartube` or `..\..\..\mingw64\bin\python3.exe ..\..\..\mingw64\bin\pip3-script.py install --upgrade tartube`?

**Comment by axcore** [comment]
If you have already installed Tartube on MS Windows, you can update it.

Just copy the new source code to C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube\

**Comment by candrapersada** [comment]
but why can't update Tartube without copy the new source code to C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube\
and why can't use In the MINGW64 terminal, type:
`pip3 install --upgrade tartube` or `..\..\..\mingw64\bin\python3.exe ..\..\..\mingw64\bin\pip3-script.py install --upgrade tartube`?

**Comment by axcore** [comment]
Because it takes 3-4 hours to create the installers for MS Windows, Debian and RPM.

Yesterday I uploaded new code to Git, so people can test it. Later I will create new installers.

**Comment by candrapersada** [comment]
why the Tartube icon is broken and how to change the theme to dark for MS Windows?

**Comment by axcore** [comment]
>why the Tartube icon is broken

I don't know, you should ask that question to Bill Gates.

There is a second set of icons, if the first set doesn't work: see [here](https://github.com/axcore/tartube#726-some-icons-not-visible).

>how to change the theme to dark for MS Windows?

That is a good question, I will try to find out.

**Comment by candrapersada** [comment]
[5.1 Installation - MS Windows](https://github.com/axcore/tartube#51-installation---ms-windows) why has to Extract it into the folder C:\msys64\home\YOURNAME\tartube, instead of to C:\msys64\home\user\tartube, to run tartube.bat
![aaaa](https://user-images.githubusercontent.com/36833664/105023829-07501500-5a7e-11eb-8cc1-7a0a430685f6.PNG)

**Comment by axcore** [comment]
`user` is the account name on my MS Windows computer. When I install [MSYS2](https://www.msys2.org/) on that computer, it creates a folder called C:\msys64\home\user.

The installer copies that folder to your computer. That's why Tartube is installed to `C:\Users\YOURNAME\AppData\Local\Tartube\**msys64\home\user**\`. 

Therefore the `tartube.bat` expects a folder called `user`, not a folder called `YOURNAME`.

The instructions at [5.1.1](https://github.com/axcore/tartube#511-manual-installation---ms-windows) show how to install Tartube manually. A person who can do that, can definitely create their own .bat file, or edit my one, so I think there is no problem here.

**Comment by candrapersada** [comment]
> The instructions at 5.1.1 show how to install Tartube manually. A person who can do that, can definitely create their own .bat file, or edit my one, so I think there is no problem here.

but still there is a problem updating tartube Source code from GitHub

**Comment by axcore** [comment]
Why is it a problem? Anyone who can install MSYS2 and Tartube manually, also knows how to use Github.

**Comment by candrapersada** [comment]
the problem is for every updating tartube must replace tartube_mswin.sh and tartube.bat continuously

**Comment by axcore** [comment]
I don't understand. Why do you need to replace tartube_mswin.sh and tartube.bat? Those files are not updated, the old files are the same as the new files.

**Comment by candrapersada** [comment]
what I mean is how to lock the home directory name so that it does not change automatically for msys2 portable?

**Comment by axcore** [comment]
Same answer. Tartube is a Linux application. If a user wants to install it on MS Windows, and the user doesn't want to use the official installer, then it is the user's responsibility to worry about folder names.

**Comment by candrapersada** [comment]
Have you ever tried using `pip3 install --upgrade tartube` and `tartube` in MINGW64 terminal?

**Comment by axcore** [comment]
If you used one of the 'official' installers for MS Windows, `pip3 install --upgrade tartube` will not work.

If you want to install Tartube manually, then of course you can use pip3.

As I said already, I won't add auto-updates to Tartube.

**Comment by candrapersada** [comment]
is it true that `pip3 install tartube` doesn't work for the latest msys2?

**Comment by axcore** [comment]
pip3 installs files in several locations, so you can't use it to replace the Tartube source code. All the Windows installers use Tartube source code.
