### ISSUE TITLE
how to auto-resume downloads?

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#86]
how to allows the user to auto resume downloads that have failed or auto-resume downloads?

**Comment by axcore** [comment]
What do you mean, failed? What error message are you seeing?

**Comment by candrapersada** [comment]
download error

**Comment by axcore** [comment]
What is the **exact** download error? Can you show me a screenshot of it?

**Comment by candrapersada** [comment]
how to auto-resume downloads?

**Comment by axcore** [comment]
I don't know, because I don't know what the error is.

If you can show me the exact error, then I can find the solution.

**Comment by axcore** [comment]
Closed for inactivity.
