### ISSUE TITLE
why video and audio merge not working? --merge-output-format mp4 tartube

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#87]
why video and audio merge not working for youtube playlist?
and how to change files the queue from 1 download files at the some time to 3 or 4 download files at the some time for youtube playlist?

**Comment by axcore** [comment]
>why video and audio merge not working for youtube playlist?

Have you [installed FFmpeg?](https://github.com/axcore/tartube#setting-the-location-of-ffmpeg-avconv)

>and how to change files the queue from 1 download files at the some time to 3 or 4 download files at the some time for youtube playlist?

In the main window, right-click the playlist, and select **Check playlist**

When Tartube has finished checking, select all of the videos in the playlist (for example, press CTRL + A)

Then right-click the videos, and select **Download videos**

**Comment by candrapersada** [comment]
yes installed FFmpeg

**Comment by axcore** [comment]
Can you give me the link of the playlist, that won't merge?

**Comment by candrapersada** [comment]
https://www.youtube.com/playlist?list=PLN5V6aiYlgnvVxc9_QcD_3BVSbeRw5vr4

**Comment by axcore** [comment]
>why video and audio merge not working for youtube playlist?

Short answer: I don't know. It works generally. It doesn't work for your playlist.

Long answer: I tested the playlist. I used a new installation of Tartube (all settings are default settings)

Then I clicked **Edit > General download options...**. Then I clicked the button **Show advanced download options**.  Then I clicked the **Formats** tab.

In the box **If a merge is required after post-processing, output to this format**, I selected **.webm**.

I tested this video [https://www.youtube.com/watch?v=Pzn625sD1aM](https://www.youtube.com/watch?v=Pzn625sD1aM)

The merge did not work, I saw this error:

![candra1](https://user-images.githubusercontent.com/37951926/81209697-c6d06a00-8fc8-11ea-9cf4-ad1745ae6dab.png)

I also tried .mp4 instead of .webm, but that also did not work

I don't know how to fix this problem. Tartube does not communicate with FFmpeg directly; youtube-dl does that.

**Comment by candrapersada** [comment]
then how video and audio merge?

**Comment by axcore** [comment]
I don't know.

**Comment by candrapersada** [comment]
alternative other for video and audio merge?

**Comment by axcore** [comment]
>and why merge video and audio work well for youtube-dl-gui old?

For the [same video](https://www.youtube.com/watch?v=Pzn625sD1aM), I compared the youtube-dl command generated by youtube-dl-gui:

`youtube-dl --newline -i -o xxxxx --ignore-config --hls-prefer-native "https://www.youtube.com/watch?v=Pzn625sD1aM"`

...with the youtube-dl command generated by Tartube:

`youtube-dl --newline -i --hls-prefer-native -o xxxxx --write-description --write-info-json --write-annotations --write-thumbnail --merge-output-format mp4 --download-archive xxxxx/ytdl-archive.txt https://www.youtube.com/watch?v=Pzn625sD1aM`

The main difference is this option:

--merge-output-format mp4

This option is added by clicking **Edit > General download options... > Formats > Advances**, and by selecting **mp4** in the box **If a merge is required after post-processing, output to this format**

![tartubemp4](https://user-images.githubusercontent.com/37951926/81274021-a72c5680-9047-11ea-94d3-44ab64a54d7b.png)

I added this option in youtube-dl-gui, but youtube-dl-gui ignored it.

![ytdlgui1](https://user-images.githubusercontent.com/37951926/81273662-1f464c80-9047-11ea-8ed1-b0b540aa219f.png)

So, I tried the same command in a terminal window:

`youtube-dl --newline -i -o xxxxx --ignore-config --hls-prefer-native --merge-output-format mp4 "https://www.youtube.com/watch?v=Pzn625sD1aM"`

This was the result:

![ytdlfail](https://user-images.githubusercontent.com/37951926/81274968-eb6c2680-9048-11ea-9bb8-1ae5a338d82d.png)

![ytdlfail2](https://user-images.githubusercontent.com/37951926/81275006-fd4dc980-9048-11ea-97f5-32e4a4bb844b.png)

So now, you can ask for help on the [youtube-dl page](https://github.com/ytdl-org/youtube-dl). Your question is: why does this work?

`youtube-dl --newline -i -o xxxxx --ignore-config --hls-prefer-native "https://www.youtube.com/watch?v=Pzn625sD1aM"`

And why doesn't this work?

`youtube-dl --newline -i -o xxxxx --ignore-config --hls-prefer-native --merge-output-format mp4 "https://www.youtube.com/watch?v=Pzn625sD1aM"`

**Comment by candrapersada** [comment]
try using `-f worstvideo+worstaudio`
 `youtube-dl --newline -i -o xxxxx --ignore-config --hls-prefer-native --merge-output-format mp4 -f worstvideo+worstaudio "https://www.youtube.com/watch?v=Pzn625sD1aM"`

**Comment by candrapersada** [comment]
but why `--merge-output-format mp4 -f worstvideo+worstaudio` not working for youtube-dl playlist from tartube?

**Comment by axcore** [comment]
I don't know.. I am not an FFmpeg expert.

**Comment by candrapersada** [comment]
but I tried the same command in a terminal window and option in youtube-dl-gui:
why does this work?

`youtube-dl --newline -i -o xxxxx --ignore-config --hls-prefer-native --merge-output-format mp4 -f worstvideo+worstaudio "https://www.youtube.com/playlist?list=PLxPvdC7PyzOx0ZVKHeAk0dgd1n3FiUrIw"`
![image](https://user-images.githubusercontent.com/36833664/81649697-ee0cb880-945a-11ea-97df-71e7162942af.png)

I tried the same in a tartube:
why doesn't this work?

`youtube-dl --newline -i --max-downloads 2 --hls-prefer-native -o C:/Users/ASUS/Youtube/Movie/as/%(playlist_index)s-%(title)s --write-description --write-info-json --write-annotations --write-thumbnail --merge-output-format mp4 -f worstvideo+worstaudio --download-archive C:/Users/ASUS/Youtube/Movie/as/ytdl-archive.txt https://www.youtube.com/playlist?list=PLxPvdC7PyzOx0ZVKHeAk0dgd1n3FiUrIw`
![image](https://user-images.githubusercontent.com/36833664/81649141-0a5c2580-945a-11ea-8faf-23d02594d762.png)

**Comment by axcore** [comment]
>I tried the same in a tartube:
>why doesn't this work?

`youtube-dl --newline -i --max-downloads 2 --hls-prefer-native -o C:/Users/ASUS/Youtube/Movie/as/%(playlist_index)s-%(title)s --write-description --write-info-json --write-annotations --write-thumbnail --merge-output-format mp4 -f worstvideo+worstaudio --download-archive C:/Users/ASUS/Youtube/Movie/as/ytdl-archive.txt https://www.youtube.com/playlist?list=PLxPvdC7PyzOx0ZVKHeAk0dgd1n3FiUrIw`

I tried exactly the same command in Tartube and in a terminal window. The results were identical.

**Comment by candrapersada** [comment]
but why doesn't this work `--merge-output-format mp4 -f worstvideo+worstaudio`?
in Tartube and in a terminal window

`youtube-dl --newline -i --max-downloads 2 --hls-prefer-native -o C:/Users/ASUS/Youtube/Movie/as/%(playlist_index)s-%(title)s --write-description --write-info-json --write-annotations --write-thumbnail --merge-output-format mp4 -f worstvideo+worstaudio --download-archive C:/Users/ASUS/Youtube/Movie/as/ytdl-archive.txt https://www.youtube.com/playlist?list=PLxPvdC7PyzOx0ZVKHeAk0dgd1n3FiUrIw`
and how to fix it?

**Comment by axcore** [comment]
I don't know.

**Comment by candrapersada** [comment]
but I tried the same `youtube-dl --merge-output-format mp4 -f worstvideo+worstaudio` option in youtube-dl-gui:
why does this work?
![image](https://user-images.githubusercontent.com/36833664/81778243-a64e6580-951c-11ea-8997-126b347b9950.png)

**Comment by axcore** [comment]
I don't know.

**Comment by candrapersada** [comment]
`--merge-output-format mp4` alternative for change format video?

**Comment by axcore** [comment]
@candrapersada, if you want mp4 videos, try this:

Click **Edit > General download options... > Formats > Preferred**

Add mp4 as a preferred format:

![mpr1](https://user-images.githubusercontent.com/37951926/82137184-a5178400-980d-11ea-90e8-1fd261a91e50.png)

Click the **Advanced tab**, and select mp4 at the bottom.

![mp42](https://user-images.githubusercontent.com/37951926/82137193-beb8cb80-980d-11ea-9d77-a6ee5c19703d.png)

**Comment by candrapersada** [comment]
why use dual Preferred and Advanced for merge video and audio?
![image](https://user-images.githubusercontent.com/36833664/82138682-897f9e00-984c-11ea-9f47-1a0af742af99.png)
`-f mp4`
![image](https://user-images.githubusercontent.com/36833664/82138737-e9764480-984c-11ea-9a6e-39fff2a22d7d.png)
`--merge-output-format mp4`

**Comment by axcore** [comment]
>why separate option and should use Preferred and Advanced for merge video and audio?

Good question. You can ask the youtube-dl authors, if you want an answer.

**Comment by candrapersada** [comment]
why should use show advanced download options for 
Format
![image](https://user-images.githubusercontent.com/36833664/82294721-c8425f00-99d8-11ea-9180-8f1b7e5f9cd7.png)
![image](https://user-images.githubusercontent.com/36833664/82294789-e3ad6a00-99d8-11ea-94dc-8682c8b8724f.png)
and merge?

**Comment by axcore** [comment]
Tartube v2.1.016 has these changes:

1. **If a merge is required after post-processing, output to this format** has been moved to the previous tab, as you suggested
2. If the user selects **mp4** in **If a merge is required after post-processing, output to this format**, Tartube shows a warning: mp4 must also be added to **List of preferred formats**
3. The FAQ is updated to explain the problem and the solution
4. In the Classic Mode tab, the buttons have been replaced by a popup menu
5. In the new popup menu, you can apply download options (only for downloads in this tab)
6. In the Classic Mode tab, if you select a format like **mp4**, Tartube uses both `-f mp4` and `--merge-output-format mp4`

I can't create new installers at the moment. If you want, you can download the Tartube source code from git, replacing the previous Tartube code on your computer.

**Comment by candrapersada** [comment]
why merge video error
![VirtualBox_KDE Neon User VirtualBox_02_06_2020_05_24_36 2](https://user-images.githubusercontent.com/36833664/83461571-4439ae00-a493-11ea-97f4-f74257a85da2.png)

**Comment by axcore** [comment]
I don't know. Here is the [youtube-dl](https://github.com/ytdl-org/youtube-dl/issues) page; you can ask them why youtube-dl doesn't merge videos correctly.

**Comment by candrapersada** [comment]
but why error
`youtube-dl --newline -i --hls-prefer-native -o /home/candra/Unduhan/%(title)s.%(ext)s --write-description --write-info-json --write-annotations --write-thumbnail -f mp4 --merge-output-format mp4 -f worstvideo+worstaudio --download-archive /home/candra/Unduhan/ytdl-archive.txt https://youtu.be/7ADjVgMGjiM`
```
WARNING: There are no annotations to write.
ERROR:   Stream #1:0 -> #0:1 (copy)
```

**Comment by axcore** [comment]
Closed for inactivity.

**Comment by candrapersada** [comment]
why Tartube v2.2.098 Classic mp4 not working?

**Comment by axcore** [comment]
v2.2.098 works for me. What error messages do you see?

![mp4test](https://user-images.githubusercontent.com/37951926/98564141-e744ee00-22a3-11eb-861c-3c7a7131fc34.png)

**Comment by candrapersada** [comment]
ERROR:   Stream 1:0 -> #0:1 (copy)
![image](https://user-images.githubusercontent.com/36833664/98566177-0ca41d00-22e1-11eb-92f6-0e2281bb618d.png)

**Comment by axcore** [comment]
`youtube-dlc --newline -i --hls-prefer-native -o /media/candra/TOSHIBA/Game/ソードアート・オンライン アリシゼーション リコリス SAOAL SAO リコリス　アリリコ　ストーリーまとめ/%(playlist_title)s/%(playlist_index)s - %(title)s.%(ext)s -f mp4 --merge-output-format mp4 -f 278+249 https://youtu.be/HlqsOk87cWQ `

The -f option occurs twice. First `-f mp4`, then `-f 278+249`. How do you do that? I can't reproduce it.

**Comment by candrapersada** [comment]
i use
![image](https://user-images.githubusercontent.com/36833664/98574718-db304f00-22ea-11eb-878f-3c24335cb32c.png)
and `-f mp4 --merge-output-format mp4` for merge video and audio

**Comment by axcore** [comment]
Yes, but that should be impossible.

Can you show me these screenshots:
1. The classic mode tab
2. In the **Download options** window, the **Formats > Preferred** tab

**Comment by axcore** [comment]
Or maybe you are doing this?

![mp4question](https://user-images.githubusercontent.com/37951926/98575795-88867100-22b1-11eb-9f49-4509a15a64ca.png)

**Comment by candrapersada** [comment]
I use 
![IMG_20201110_003708](https://user-images.githubusercontent.com/36833664/98576604-5c88e100-22ed-11eb-806b-fbd023cb60c4.jpg)

**Comment by axcore** [comment]
Ok,

1. In Classic Mode tab, add the video URl
2. Select MP4
3. Click the ADD URLs button

4. In the Classic Mode tab, click the menu button, then select **Edit download options**
5. In the Formats tab, add #278 and #249 

![test1](https://user-images.githubusercontent.com/37951926/98577240-90471500-22b3-11eb-9de9-6059f86cc546.png)

6. In the Output tab, I see this command

`/home/ra/.local/bin/youtube-dl --newline -i --hls-prefer-native -o /home/ra/%(title)s.%(ext)s --write-description --write-info-json --write-annotations --write-thumbnail -f mp4 --merge-output-format mp4 https://www.youtube.com/watch?v=HlqsOk87cWQ&feature=youtu.be`

It is not the same as your command, and I don't understand why.

**Comment by candrapersada** [comment]
![image](https://user-images.githubusercontent.com/36833664/98598133-97e6d800-230c-11eb-99f4-93dfc3fb0934.png)
![image](https://user-images.githubusercontent.com/36833664/98598529-31ae8500-230d-11eb-9366-8c07ef068112.png)

**Comment by axcore** [comment]
You cannot use `--merge-output-format mp4` and `-f 278+249` together. youtube-dl does not allow it.

You could do `-f 278+249+mp4`, that will probably work.

**Comment by candrapersada** [comment]
> 6. In the Classic Mode tab, if you select a format like mp4, Tartube uses both `-f mp4` and `--merge-output-format mp4`

how to remove `-f mp4` from Classic Mode tab?

**Comment by axcore** [comment]
Don't select **mp4** in the Classic Mode tab, select it in the **Download options** window.

![test1](https://user-images.githubusercontent.com/37951926/98666522-119ab800-2345-11eb-8cdc-1f1a4c9dc1b0.png)

![test2](https://user-images.githubusercontent.com/37951926/98666526-12334e80-2345-11eb-87d4-b718f68aae2f.png)

**Comment by candrapersada** [comment]
but still an error
```
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "/home/candra/.local/lib/python3.8/site-packages/youtube_dlc/YoutubeDL.py", line 2150, in post_process
    files_to_delete, info = pp.run(info)
  File "/home/candra/.local/lib/python3.8/site-packages/youtube_dlc/postprocessor/ffmpeg.py", line 551, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/home/candra/.local/lib/python3.8/site-packages/youtube_dlc/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dlc.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)
```

**Comment by axcore** [comment]
>what else for ubuntu

I don't know

**Comment by candrapersada** [comment]
added feature to download directly to the latest version of FFmpeg / AVConv for Linux based on Ubuntu LTS.
for fix video converter
```
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "/home/candra/.local/lib/python3.8/site-packages/youtube_dlc/YoutubeDL.py", line 2150, in post_process
    files_to_delete, info = pp.run(info)
  File "/home/candra/.local/lib/python3.8/site-packages/youtube_dlc/postprocessor/ffmpeg.py", line 551, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/home/candra/.local/lib/python3.8/site-packages/youtube_dlc/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dlc.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)
```

**Comment by axcore** [comment]
Tartube downloads FFmpeg only on MS Windows. On Linux, users must download it separately.

**Comment by candrapersada** [comment]
I hope that someday tartube can download FFmpeg files from the menu without downloading separately so it's easy to update FFmpeg from ubuntu lts.
thanks.

**Comment by axcore** [comment]
>I hope that someday tartube can download FFmpeg files from the operations without downloading separately so it's easy to update FFmpeg from ubuntu lts.

It is not possible. I cannot write code that works on every distribution. There are 99999 methods, it's too many. I don't even understand most of them.

For youtube-dl, it is simple. There are two methods, they are easy, and they work on all operating systems.
