### ISSUE TITLE
It only downloads the youtube thumbnails instead of the videos

### ISSUE THREAD

**Issue by OrpheusXx** [axcore/tartube#89]
Tried to download a whole youtube channel, but it only downloads the thumbnails of videos, not sure why this is happening, anyone could help me with this?

Edit: I think i found out why, maybe it's a feature i overlooked heh:

I added a new channel to download, but didn't select the auto download option, and later i couldn't get the videos to be downloaded for some reason, only the thumbnails.

Selecting Auto Download videos downloaded the videos fine.

How can i disable creating jpg thumbnails of videos?

**Comment by axcore** [comment]
>Tried to download a whole youtube channel, but it only downloads the thumbnails of videos, not sure why this is happening, anyone could help me with this?

![addchannel](https://user-images.githubusercontent.com/37951926/81419038-8518fe00-9145-11ea-88be-aba25ac6101c.png)

Make sure the default option is selected: **I want to download videos from this channel automatically**.

You can change this setting after adding the channel/playlist, if you want. RIght-click the channel/playlist and toggle **Downloads > Just disable downloading**

>How can i disable creating jpg thumbnails of videos?

**Edit > General download options... > Files > Keep files**

Unselect the two boxes marked **Keep the thumbnail file after Tartube shuts down**

If you do that, the video's thumbnail won't be visible in the list of Videos (you'll just see a generic icon instead).

If you want to delete the thumbnails you already have, click **Operations > Tidy up files...**

**Comment by OrpheusXx** [comment]
> If you do that, the video's thumbnail won't be visible in the list of Videos (you'll just see a generic icon instead).

Yea, i noticed the thumbnails disappeared from the program also after i deleted them manually, so it's actually good to have them for a while.


>  If you want to delete the thumbnails you already have, click Operations > Tidy up files...

Good to know i can also delete them automatically.

Thanks for helping me out!
Great program!
