### ISSUE TITLE
Cannot set ffmpeg in settings

### ISSUE THREAD

**Issue by kyle5482** [axcore/tartube#90]
I am trying to download audio into Mp3 but no matter what options I select I get an error that either tells me "the format is not available" or "ffprobe/avprobe and ffmpeg/avconv not found. Please install one."

I was unable to install ffmpeg via the operations button, but i was able to grab a build and successfully download it as confirmed in the command prompt. I also tested youtube-dl and confirmed that is not the issue, so i'm assuming that Tartube is not recognizing that i have ffmpeg downloaded. Under the system preferences "youtube-dl" tab I am not able to select any of the options under "post processing preferences", they are all grayed out. I am running on Windows 10, any suggestions? 

![System Preferences](https://user-images.githubusercontent.com/65136370/81511087-ceec1a80-92e4-11ea-8144-1a2717b1b68b.PNG)
![Error-Warnings](https://user-images.githubusercontent.com/65136370/81511089-d0b5de00-92e4-11ea-953a-e5cb32691e46.PNG)

**Comment by axcore** [comment]
>I was unable to install ffmpeg via the operations button, but i was able to grab a build and successfully download it as confirmed in the command prompt.

Which command prompt, the MS Windows one? Forget it. [Msys2](https://www.msys2.org/) is a virtual Linux environment that can't run MS Windows software.

If **Operations > Install FFmpeg** doesn't work, you could try installing it from the  [Msys2](https://www.msys2.org/) command prompt. I'm not at my desk right now, but I think it's **C:\Users\YOURNAME\AppData\Local\Tartube\msys64\mingw64.exe**.

>Under the system preferences "youtube-dl" tab I am not able to select any of the options under "post processing preferences", they are all grayed out

Yes, this is to stop Windows 10 users from ripping out their hair, trying to install FFmpeg using a method that will never work.

**Comment by axcore** [comment]
From the screenshot, it looks like you are trying to download a livestream that's still broadcasting. Be aware that I wasn't able to get that working either. I had to assume that it was a temporary problem with youtube-dl, and implemented the feature anyway.

**Comment by kyle5482** [comment]
Hello, thanks for the response. I know ffmpeg is already downloaded and working (outside of tartube), does the method you mention correct it in Tartube at all? Since yesterday I've been selecting "test youtube dl" to get the video then typing "ffmpeg -i "(Video name).mp4" "(Video name).mp3" to convert it since Tartube won't while I await a fix. I wasn't doing a live stream, just a regular video, not even a playlist.

**Comment by axcore** [comment]
Can you please give me the link of video that produces these two errors. 

Can you also be specific about the download options you have selected (in the window **Edit > General download options...** Exactly which options did you select, and on which tabs? 

If you don't want to list all the changes in the window because you have made a lot of changes, you can right-click a video and select **Downloads > Show system command**, and give me a screenshot of that.

**Comment by candrapersada** [comment]
why doesn't this work: merge audio and video
 `--merge-output-format mp4 -f worstvideo+worstaudio`
in Tartube?

**Comment by TylerTheHumanCompiler** [comment]
I have the same issue on arch linux. I set the path to /usr/bin/ffmpeg but tartube just gives me an error that the location doesn't exist.
I tried both the ffmpeg package and compiling it from source, but neither is recognized/found. Surprisingly youtube-dl works fine. I use version ffmpeg-2:4.2.3-2

**Comment by axcore** [comment]
> I have the same issue on arch linux.

MS Windows and Arch are completely different, so if you're having problems getting FFmpeg to run, it would be better to open a new issue.

Meanwhile you can try this:

- Click Edit > System preferences... > youtube-dl
- Set the ffmpeg location to /usr/bin/ffmpeg, or whatever
- In the main window's Videos tab, right-click any video and select Downloads > Show system command', then give me a screenshot of the new dialogue window

-

**Comment by axcore** [comment]
@kyle5482 @TylerTheHumanCompiler, I have a fix for this problem on all operating systems. You are both right; setting the ffmpeg location in Tartube settings does not work at the moment.

**Comment by axcore** [comment]
The fix was added in v2.1.051.

**Comment by TylerTheHumanCompiler** [comment]
After installing from source I get the following error:
`Tartube cannot start because it cannot find its icons folder`

**Comment by axcore** [comment]
@TylerTheHumanCompiler, it's better to create a new issue for a different problem.

I created a [new issue](https://github.com/axcore/tartube/issues/125). Can you please tell me, what you by "installing from source" - do you mean [this exact method](https://github.com/axcore/tartube#538-install-from-source)? Which operating system are you using?
