### ISSUE TITLE
Installation of FFmpeg fails

### ISSUE THREAD

**Issue by TheDukexx99** [axcore/tartube#95]
On Windows 10 64bit. When I click install FFmpeg goes for a moment then just gives an error of installation failed
![Annotation 2020-05-22 134014](https://user-images.githubusercontent.com/65782973/82694737-caebc100-9c31-11ea-99ba-a9bb11911575.jpg)

**Comment by axcore** [comment]
Try installing FFmpeg from the command line, so we can see what the error message is

First turn on hidden folders for your system (type 'hidden folders' in the main search bar)

Then run the terminal window. I'm not at my desk right now, but I think it is **C:\Users\YOURNAME\AppData\Local\Tartube\msys64\mingw64.exe**

Type this command to install ffmpeg:

`pacman -S mingw-w64-x86_64-ffmpeg`

Take a screenshot of the error message and/or copy it here.

**Comment by TheDukexx99** [comment]
`$ pacman -S mingw-w64-x86_64-ffmpeg
error: duplicated database entry 'bash'
error: duplicated database entry 'brotli'
error: duplicated database entry 'bsdcpio'
error: duplicated database entry 'bsdtar'
error: duplicated database entry 'bzip2'
error: duplicated database entry 'coreutils'
error: duplicated database entry 'curl'
error: duplicated database entry 'dtc'
error: duplicated database entry 'file'
error: duplicated database entry 'filesystem'
error: duplicated database entry 'gawk'
error: duplicated database entry 'gcc-libs'
error: duplicated database entry 'glib2'
error: duplicated database entry 'gmp'
error: duplicated database entry 'gnupg'
error: duplicated database entry 'icu'
error: duplicated database entry 'info'
error: duplicated database entry 'libarchive'
error: duplicated database entry 'libbz2'
error: duplicated database entry 'libcurl'
error: duplicated database entry 'libedit'
error: duplicated database entry 'libffi'
error: duplicated database entry 'libgnutls'
error: duplicated database entry 'libgpg-error'
error: duplicated database entry 'libgpgme'
error: duplicated database entry 'libidn2'
error: duplicated database entry 'liblzma'
error: duplicated database entry 'libnghttp2'
error: duplicated database entry 'libopenssl'
error: duplicated database entry 'libp11-kit'
error: duplicated database entry 'libpcre'
error: duplicated database entry 'libpcre16'
error: duplicated database entry 'libpcre32'
error: duplicated database entry 'libpcrecpp'
error: duplicated database entry 'libpcreposix'
error: duplicated database entry 'libreadline'
error: duplicated database entry 'libsqlite'
error: duplicated database entry 'libtasn1'
error: duplicated database entry 'libutil-linux'
error: duplicated database entry 'libxml2'
error: duplicated database entry 'libxslt'
error: duplicated database entry 'libzstd'
error: duplicated database entry 'mingw-w64-x86_64-adwaita-icon-theme'
error: duplicated database entry 'mingw-w64-x86_64-atk'
error: duplicated database entry 'mingw-w64-x86_64-cantarell-fonts'
error: duplicated database entry 'mingw-w64-x86_64-fribidi'
error: duplicated database entry 'mingw-w64-x86_64-gcc-libs'
error: duplicated database entry 'mingw-w64-x86_64-glib2'
error: duplicated database entry 'mingw-w64-x86_64-gmp'
error: duplicated database entry 'mingw-w64-x86_64-gobject-introspection-runtime'
error: duplicated database entry 'mingw-w64-x86_64-graphite2'
error: duplicated database entry 'mingw-w64-x86_64-gsettings-desktop-schemas'
error: duplicated database entry 'mingw-w64-x86_64-gtk3'
error: duplicated database entry 'mingw-w64-x86_64-harfbuzz'
error: duplicated database entry 'mingw-w64-x86_64-libffi'
error: duplicated database entry 'mingw-w64-x86_64-libjpeg-turbo'
error: duplicated database entry 'mingw-w64-x86_64-librsvg'
error: duplicated database entry 'mingw-w64-x86_64-libtasn1'
error: duplicated database entry 'mingw-w64-x86_64-libwinpthread-git'
error: duplicated database entry 'mingw-w64-x86_64-libxml2'
error: duplicated database entry 'mingw-w64-x86_64-ncurses'
error: duplicated database entry 'mingw-w64-x86_64-openssl'
error: duplicated database entry 'mingw-w64-x86_64-p11-kit'
error: duplicated database entry 'mingw-w64-x86_64-pcre'
error: duplicated database entry 'mingw-w64-x86_64-pixman'
error: duplicated database entry 'mingw-w64-x86_64-readline'
error: duplicated database entry 'mingw-w64-x86_64-sqlite3'
error: duplicated database entry 'mingw-w64-x86_64-tcl'
error: duplicated database entry 'mingw-w64-x86_64-tk'
error: duplicated database entry 'mingw-w64-x86_64-xz'
error: duplicated database entry 'mintty'
error: duplicated database entry 'ncurses'
error: duplicated database entry 'openssl'
error: duplicated database entry 'p11-kit'
error: duplicated database entry 'pacman'
error: duplicated database entry 'pacman-mirrors'
error: duplicated database entry 'pcre'
error: duplicated database entry 'sed'
error: duplicated database entry 'tzcode'
error: duplicated database entry 'util-linux'
error: duplicated database entry 'xz'
warning: mingw-w64-x86_64-ffmpeg-4.2.2-4 is up to date -- reinstalling
resolving dependencies...

looking for conflicting packages...

Packages (1) mingw-w64-x86_64-ffmpeg-4.2.2-4

Total Installed Size:  30.56 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                     [#####################] 100%
(1/1) checking package integrity                   [#####################] 100%
(1/1) loading package files                        [#####################] 100%
(1/1) checking for file conflicts                  [#####################] 100%
(1/1) checking available disk space                [#####################] 100%
:: Processing package changes...
(1/1) reinstalling mingw-w64-x86_64-ffmpeg         [#####################] 100%
`

**Comment by axcore** [comment]
At a guess, I would say FFmpeg was correctly installed the first time, but Tartube (for some reason) didn't realise it

We can try uninstalling the package, then reinstalling it:

```
pacman -Rcns ffmpeg
pacman -S mingw-w64-x86_64-ffmpeg
```

(I haven't tested this; if the first command doesn't work, try this)

```
pacman -Rcns mingw-w64-x86_64-ffmpeg
pacman -S mingw-w64-x86_64-ffmpeg
```

**Comment by TheDukexx99** [comment]
Sorry I thought it worked at first but it seems to not see ffmpeg

MINGW64 ~
$ pacman -Rcns ffmpeg
error: duplicated database entry 'bash'
error: duplicated database entry 'brotli'
error: duplicated database entry 'bsdcpio'
error: duplicated database entry 'bsdtar'
error: duplicated database entry 'bzip2'
error: duplicated database entry 'coreutils'
error: duplicated database entry 'curl'
error: duplicated database entry 'dtc'
error: duplicated database entry 'file'
error: duplicated database entry 'filesystem'
error: duplicated database entry 'gawk'
error: duplicated database entry 'gcc-libs'
error: duplicated database entry 'glib2'
error: duplicated database entry 'gmp'
error: duplicated database entry 'gnupg'
error: duplicated database entry 'icu'
error: duplicated database entry 'info'
error: duplicated database entry 'libarchive'
error: duplicated database entry 'libbz2'
error: duplicated database entry 'libcurl'
error: duplicated database entry 'libedit'
error: duplicated database entry 'libffi'
error: duplicated database entry 'libgnutls'
error: duplicated database entry 'libgpg-error'
error: duplicated database entry 'libgpgme'
error: duplicated database entry 'libidn2'
error: duplicated database entry 'liblzma'
error: duplicated database entry 'libnghttp2'
error: duplicated database entry 'libopenssl'
error: duplicated database entry 'libp11-kit'
error: duplicated database entry 'libpcre'
error: duplicated database entry 'libpcre16'
error: duplicated database entry 'libpcre32'
error: duplicated database entry 'libpcrecpp'
error: duplicated database entry 'libpcreposix'
error: duplicated database entry 'libreadline'
error: duplicated database entry 'libsqlite'
error: duplicated database entry 'libtasn1'
error: duplicated database entry 'libutil-linux'
error: duplicated database entry 'libxml2'
error: duplicated database entry 'libxslt'
error: duplicated database entry 'libzstd'
error: duplicated database entry 'mingw-w64-x86_64-adwaita-icon-theme'
error: duplicated database entry 'mingw-w64-x86_64-atk'
error: duplicated database entry 'mingw-w64-x86_64-cantarell-fonts'
error: duplicated database entry 'mingw-w64-x86_64-fribidi'
error: duplicated database entry 'mingw-w64-x86_64-gcc-libs'
error: duplicated database entry 'mingw-w64-x86_64-glib2'
error: duplicated database entry 'mingw-w64-x86_64-gmp'
error: duplicated database entry 'mingw-w64-x86_64-gobject-introspection-runtime'
error: duplicated database entry 'mingw-w64-x86_64-graphite2'
error: duplicated database entry 'mingw-w64-x86_64-gsettings-desktop-schemas'
error: duplicated database entry 'mingw-w64-x86_64-gtk3'
error: duplicated database entry 'mingw-w64-x86_64-harfbuzz'
error: duplicated database entry 'mingw-w64-x86_64-libffi'
error: duplicated database entry 'mingw-w64-x86_64-libjpeg-turbo'
error: duplicated database entry 'mingw-w64-x86_64-librsvg'
error: duplicated database entry 'mingw-w64-x86_64-libtasn1'
error: duplicated database entry 'mingw-w64-x86_64-libwinpthread-git'
error: duplicated database entry 'mingw-w64-x86_64-libxml2'
error: duplicated database entry 'mingw-w64-x86_64-ncurses'
error: duplicated database entry 'mingw-w64-x86_64-openssl'
error: duplicated database entry 'mingw-w64-x86_64-p11-kit'
error: duplicated database entry 'mingw-w64-x86_64-pcre'
error: duplicated database entry 'mingw-w64-x86_64-pixman'
error: duplicated database entry 'mingw-w64-x86_64-readline'
error: duplicated database entry 'mingw-w64-x86_64-sqlite3'
error: duplicated database entry 'mingw-w64-x86_64-tcl'
error: duplicated database entry 'mingw-w64-x86_64-tk'
error: duplicated database entry 'mingw-w64-x86_64-xz'
error: duplicated database entry 'mintty'
error: duplicated database entry 'ncurses'
error: duplicated database entry 'openssl'
error: duplicated database entry 'p11-kit'
error: duplicated database entry 'pacman'
error: duplicated database entry 'pacman-mirrors'
error: duplicated database entry 'pcre'
error: duplicated database entry 'sed'
error: duplicated database entry 'tzcode'
error: duplicated database entry 'util-linux'
error: duplicated database entry 'xz'
error: target not found: ffmpeg

MINGW64 ~
$ pacman -S mingw-w64-x86_64-ffmpeg
error: duplicated database entry 'bash'
error: duplicated database entry 'brotli'
error: duplicated database entry 'bsdcpio'
error: duplicated database entry 'bsdtar'
error: duplicated database entry 'bzip2'
error: duplicated database entry 'coreutils'
error: duplicated database entry 'curl'
error: duplicated database entry 'dtc'
error: duplicated database entry 'file'
error: duplicated database entry 'filesystem'
error: duplicated database entry 'gawk'
error: duplicated database entry 'gcc-libs'
error: duplicated database entry 'glib2'
error: duplicated database entry 'gmp'
error: duplicated database entry 'gnupg'
error: duplicated database entry 'icu'
error: duplicated database entry 'info'
error: duplicated database entry 'libarchive'
error: duplicated database entry 'libbz2'
error: duplicated database entry 'libcurl'
error: duplicated database entry 'libedit'
error: duplicated database entry 'libffi'
error: duplicated database entry 'libgnutls'
error: duplicated database entry 'libgpg-error'
error: duplicated database entry 'libgpgme'
error: duplicated database entry 'libidn2'
error: duplicated database entry 'liblzma'
error: duplicated database entry 'libnghttp2'
error: duplicated database entry 'libopenssl'
error: duplicated database entry 'libp11-kit'
error: duplicated database entry 'libpcre'
error: duplicated database entry 'libpcre16'
error: duplicated database entry 'libpcre32'
error: duplicated database entry 'libpcrecpp'
error: duplicated database entry 'libpcreposix'
error: duplicated database entry 'libreadline'
error: duplicated database entry 'libsqlite'
error: duplicated database entry 'libtasn1'
error: duplicated database entry 'libutil-linux'
error: duplicated database entry 'libxml2'
error: duplicated database entry 'libxslt'
error: duplicated database entry 'libzstd'
error: duplicated database entry 'mingw-w64-x86_64-adwaita-icon-theme'
error: duplicated database entry 'mingw-w64-x86_64-atk'
error: duplicated database entry 'mingw-w64-x86_64-cantarell-fonts'
error: duplicated database entry 'mingw-w64-x86_64-fribidi'
error: duplicated database entry 'mingw-w64-x86_64-gcc-libs'
error: duplicated database entry 'mingw-w64-x86_64-glib2'
error: duplicated database entry 'mingw-w64-x86_64-gmp'
error: duplicated database entry 'mingw-w64-x86_64-gobject-introspection-runtime'
error: duplicated database entry 'mingw-w64-x86_64-graphite2'
error: duplicated database entry 'mingw-w64-x86_64-gsettings-desktop-schemas'
error: duplicated database entry 'mingw-w64-x86_64-gtk3'
error: duplicated database entry 'mingw-w64-x86_64-harfbuzz'
error: duplicated database entry 'mingw-w64-x86_64-libffi'
error: duplicated database entry 'mingw-w64-x86_64-libjpeg-turbo'
error: duplicated database entry 'mingw-w64-x86_64-librsvg'
error: duplicated database entry 'mingw-w64-x86_64-libtasn1'
error: duplicated database entry 'mingw-w64-x86_64-libwinpthread-git'
error: duplicated database entry 'mingw-w64-x86_64-libxml2'
error: duplicated database entry 'mingw-w64-x86_64-ncurses'
error: duplicated database entry 'mingw-w64-x86_64-openssl'
error: duplicated database entry 'mingw-w64-x86_64-p11-kit'
error: duplicated database entry 'mingw-w64-x86_64-pcre'
error: duplicated database entry 'mingw-w64-x86_64-pixman'
error: duplicated database entry 'mingw-w64-x86_64-readline'
error: duplicated database entry 'mingw-w64-x86_64-sqlite3'
error: duplicated database entry 'mingw-w64-x86_64-tcl'
error: duplicated database entry 'mingw-w64-x86_64-tk'
error: duplicated database entry 'mingw-w64-x86_64-xz'
error: duplicated database entry 'mintty'
error: duplicated database entry 'ncurses'
error: duplicated database entry 'openssl'
error: duplicated database entry 'p11-kit'
error: duplicated database entry 'pacman'
error: duplicated database entry 'pacman-mirrors'
error: duplicated database entry 'pcre'
error: duplicated database entry 'sed'
error: duplicated database entry 'tzcode'
error: duplicated database entry 'util-linux'
error: duplicated database entry 'xz'
warning: mingw-w64-x86_64-ffmpeg-4.2.2-4 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-ffmpeg-4.2.2-4

Total Installed Size:  30.56 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                     [#####################] 100%
(1/1) checking package integrity                   [#####################] 100%
(1/1) loading package files                        [#####################] 100%
(1/1) checking for file conflicts                  [#####################] 100%
(1/1) checking available disk space                [#####################] 100%
:: Processing package changes...
(1/1) reinstalling mingw-w64-x86_64-ffmpeg         [#####################] 100%

MINGW64 ~
$ pacman -Rcns mingw-w64-x86_64-ffmpeg
error: duplicated database entry 'bash'
error: duplicated database entry 'brotli'
error: duplicated database entry 'bsdcpio'
error: duplicated database entry 'bsdtar'
error: duplicated database entry 'bzip2'
error: duplicated database entry 'coreutils'
error: duplicated database entry 'curl'
error: duplicated database entry 'dtc'
error: duplicated database entry 'file'
error: duplicated database entry 'filesystem'
error: duplicated database entry 'gawk'
error: duplicated database entry 'gcc-libs'
error: duplicated database entry 'glib2'
error: duplicated database entry 'gmp'
error: duplicated database entry 'gnupg'
error: duplicated database entry 'icu'
error: duplicated database entry 'info'
error: duplicated database entry 'libarchive'
error: duplicated database entry 'libbz2'
error: duplicated database entry 'libcurl'
error: duplicated database entry 'libedit'
error: duplicated database entry 'libffi'
error: duplicated database entry 'libgnutls'
error: duplicated database entry 'libgpg-error'
error: duplicated database entry 'libgpgme'
error: duplicated database entry 'libidn2'
error: duplicated database entry 'liblzma'
error: duplicated database entry 'libnghttp2'
error: duplicated database entry 'libopenssl'
error: duplicated database entry 'libp11-kit'
error: duplicated database entry 'libpcre'
error: duplicated database entry 'libpcre16'
error: duplicated database entry 'libpcre32'
error: duplicated database entry 'libpcrecpp'
error: duplicated database entry 'libpcreposix'
error: duplicated database entry 'libreadline'
error: duplicated database entry 'libsqlite'
error: duplicated database entry 'libtasn1'
error: duplicated database entry 'libutil-linux'
error: duplicated database entry 'libxml2'
error: duplicated database entry 'libxslt'
error: duplicated database entry 'libzstd'
error: duplicated database entry 'mingw-w64-x86_64-adwaita-icon-theme'
error: duplicated database entry 'mingw-w64-x86_64-atk'
error: duplicated database entry 'mingw-w64-x86_64-cantarell-fonts'
error: duplicated database entry 'mingw-w64-x86_64-fribidi'
error: duplicated database entry 'mingw-w64-x86_64-gcc-libs'
error: duplicated database entry 'mingw-w64-x86_64-glib2'
error: duplicated database entry 'mingw-w64-x86_64-gmp'
error: duplicated database entry 'mingw-w64-x86_64-gobject-introspection-runtime'
error: duplicated database entry 'mingw-w64-x86_64-graphite2'
error: duplicated database entry 'mingw-w64-x86_64-gsettings-desktop-schemas'
error: duplicated database entry 'mingw-w64-x86_64-gtk3'
error: duplicated database entry 'mingw-w64-x86_64-harfbuzz'
error: duplicated database entry 'mingw-w64-x86_64-libffi'
error: duplicated database entry 'mingw-w64-x86_64-libjpeg-turbo'
error: duplicated database entry 'mingw-w64-x86_64-librsvg'
error: duplicated database entry 'mingw-w64-x86_64-libtasn1'
error: duplicated database entry 'mingw-w64-x86_64-libwinpthread-git'
error: duplicated database entry 'mingw-w64-x86_64-libxml2'
error: duplicated database entry 'mingw-w64-x86_64-ncurses'
error: duplicated database entry 'mingw-w64-x86_64-openssl'
error: duplicated database entry 'mingw-w64-x86_64-p11-kit'
error: duplicated database entry 'mingw-w64-x86_64-pcre'
error: duplicated database entry 'mingw-w64-x86_64-pixman'
error: duplicated database entry 'mingw-w64-x86_64-readline'
error: duplicated database entry 'mingw-w64-x86_64-sqlite3'
error: duplicated database entry 'mingw-w64-x86_64-tcl'
error: duplicated database entry 'mingw-w64-x86_64-tk'
error: duplicated database entry 'mingw-w64-x86_64-xz'
error: duplicated database entry 'mintty'
error: duplicated database entry 'ncurses'
error: duplicated database entry 'openssl'
error: duplicated database entry 'p11-kit'
error: duplicated database entry 'pacman'
error: duplicated database entry 'pacman-mirrors'
error: duplicated database entry 'pcre'
error: duplicated database entry 'sed'
error: duplicated database entry 'tzcode'
error: duplicated database entry 'util-linux'
error: duplicated database entry 'xz'
checking dependencies...
warning: dependency cycle detected:
warning: mingw-w64-x86_64-ffms2 will be removed after its mingw-w64-x86_64-ffmpeg dependency

Packages (37) mingw-w64-x86_64-SDL2-2.0.12-4  mingw-w64-x86_64-celt-0.11.3-4
              mingw-w64-x86_64-ffms2-2.23.1-1  mingw-w64-x86_64-giflib-5.2.1-1
              mingw-w64-x86_64-gnutls-3.6.13-1  mingw-w64-x86_64-gsm-1.0.19-1
              mingw-w64-x86_64-l-smash-2.14.5-1  mingw-w64-x86_64-lame-3.100-1
              mingw-w64-x86_64-lcms2-2.9-1  mingw-w64-x86_64-libass-0.14.0-1
              mingw-w64-x86_64-libbluray-1.2.0-1
              mingw-w64-x86_64-libcaca-0.99.beta19-5
              mingw-w64-x86_64-libidn2-2.3.0-1  mingw-w64-x86_64-libmfx-1.25-1
              mingw-w64-x86_64-libmodplug-0.8.9.0-1
              mingw-w64-x86_64-libogg-1.3.4-3
              mingw-w64-x86_64-libtheora-1.1.1-4
              mingw-w64-x86_64-libunistring-0.9.10-1
              mingw-w64-x86_64-libvorbis-1.3.6-1
              mingw-w64-x86_64-libvpx-1.8.2-1  mingw-w64-x86_64-libwebp-1.1.0-1
              mingw-w64-x86_64-nettle-3.5.1-1  mingw-w64-x86_64-openal-1.20.1-1
              mingw-w64-x86_64-opencore-amr-0.1.5-1
              mingw-w64-x86_64-openjpeg2-2.3.1-1  mingw-w64-x86_64-opus-1.3.1-1
              mingw-w64-x86_64-rtmpdump-git-r514.c5f04a5-1
              mingw-w64-x86_64-speex-1.2.0-1  mingw-w64-x86_64-speexdsp-1.2.0-1
              mingw-w64-x86_64-srt-1.4.1-1
              mingw-w64-x86_64-vulkan-headers-1.2.139-1
              mingw-w64-x86_64-vulkan-loader-1.2.137-1
              mingw-w64-x86_64-wavpack-5.2.0-1
              mingw-w64-x86_64-x264-git-r2991.1771b556-1
              mingw-w64-x86_64-x265-3.3-1  mingw-w64-x86_64-xvidcore-1.3.7-1
              mingw-w64-x86_64-ffmpeg-4.2.2-4

Total Removed Size:  168.83 MiB

:: Do you want to remove these packages? [Y/n] y
:: Processing package changes...
( 1/37) removing mingw-w64-x86_64-ffmpeg           [#####################] 100%
( 2/37) removing mingw-w64-x86_64-xvidcore         [#####################] 100%
( 3/37) removing mingw-w64-x86_64-x265             [#####################] 100%
( 4/37) removing mingw-w64-x86_64-wavpack          [#####################] 100%
( 5/37) removing mingw-w64-x86_64-srt              [#####################] 100%
( 6/37) removing mingw-w64-x86_64-speex            [#####################] 100%
( 7/37) removing mingw-w64-x86_64-speexdsp         [#####################] 100%
( 8/37) removing mingw-w64-x86_64-rtmpdump-git     [#####################] 100%
( 9/37) removing mingw-w64-x86_64-opus             [#####################] 100%
(10/37) removing mingw-w64-x86_64-openjpeg2        [#####################] 100%
(11/37) removing mingw-w64-x86_64-lcms2            [#####################] 100%
(12/37) removing mingw-w64-x86_64-opencore-amr     [#####################] 100%
(13/37) removing mingw-w64-x86_64-openal           [#####################] 100%
(14/37) removing mingw-w64-x86_64-libwebp          [#####################] 100%
(15/37) removing mingw-w64-x86_64-giflib           [#####################] 100%
(16/37) removing mingw-w64-x86_64-libvpx           [#####################] 100%
(17/37) removing mingw-w64-x86_64-libtheora        [#####################] 100%
(18/37) removing mingw-w64-x86_64-libvorbis        [#####################] 100%
(19/37) removing mingw-w64-x86_64-libmodplug       [#####################] 100%
(20/37) removing mingw-w64-x86_64-libmfx           [#####################] 100%
(21/37) removing mingw-w64-x86_64-libcaca          [#####################] 100%
(22/37) removing mingw-w64-x86_64-libbluray        [#####################] 100%
(23/37) removing mingw-w64-x86_64-libass           [#####################] 100%
(24/37) removing mingw-w64-x86_64-lame             [#####################] 100%
(25/37) removing mingw-w64-x86_64-gsm              [#####################] 100%
(26/37) removing mingw-w64-x86_64-gnutls           [#####################] 100%
(27/37) removing mingw-w64-x86_64-nettle           [#####################] 100%
(28/37) removing mingw-w64-x86_64-libidn2          [#####################] 100%
(29/37) removing mingw-w64-x86_64-libunistring     [#####################] 100%
(30/37) removing mingw-w64-x86_64-celt             [#####################] 100%
(31/37) removing mingw-w64-x86_64-libogg           [#####################] 100%
(32/37) removing mingw-w64-x86_64-SDL2             [#####################] 100%
(33/37) removing mingw-w64-x86_64-vulkan-loader    [#####################] 100%
(34/37) removing mingw-w64-x86_64-vulkan-headers   [#####################] 100%
(35/37) removing mingw-w64-x86_64-x264-git         [#####################] 100%
(36/37) removing mingw-w64-x86_64-l-smash          [#####################] 100%
(37/37) removing mingw-w64-x86_64-ffms2            [#####################] 100%

MINGW64 ~
$ pacman -S mingw-w64-x86_64-ffmpeg
error: duplicated database entry 'bash'
error: duplicated database entry 'brotli'
error: duplicated database entry 'bsdcpio'
error: duplicated database entry 'bsdtar'
error: duplicated database entry 'bzip2'
error: duplicated database entry 'coreutils'
error: duplicated database entry 'curl'
error: duplicated database entry 'dtc'
error: duplicated database entry 'file'
error: duplicated database entry 'filesystem'
error: duplicated database entry 'gawk'
error: duplicated database entry 'gcc-libs'
error: duplicated database entry 'glib2'
error: duplicated database entry 'gmp'
error: duplicated database entry 'gnupg'
error: duplicated database entry 'icu'
error: duplicated database entry 'info'
error: duplicated database entry 'libarchive'
error: duplicated database entry 'libbz2'
error: duplicated database entry 'libcurl'
error: duplicated database entry 'libedit'
error: duplicated database entry 'libffi'
error: duplicated database entry 'libgnutls'
error: duplicated database entry 'libgpg-error'
error: duplicated database entry 'libgpgme'
error: duplicated database entry 'libidn2'
error: duplicated database entry 'liblzma'
error: duplicated database entry 'libnghttp2'
error: duplicated database entry 'libopenssl'
error: duplicated database entry 'libp11-kit'
error: duplicated database entry 'libpcre'
error: duplicated database entry 'libpcre16'
error: duplicated database entry 'libpcre32'
error: duplicated database entry 'libpcrecpp'
error: duplicated database entry 'libpcreposix'
error: duplicated database entry 'libreadline'
error: duplicated database entry 'libsqlite'
error: duplicated database entry 'libtasn1'
error: duplicated database entry 'libutil-linux'
error: duplicated database entry 'libxml2'
error: duplicated database entry 'libxslt'
error: duplicated database entry 'libzstd'
error: duplicated database entry 'mingw-w64-x86_64-adwaita-icon-theme'
error: duplicated database entry 'mingw-w64-x86_64-atk'
error: duplicated database entry 'mingw-w64-x86_64-cantarell-fonts'
error: duplicated database entry 'mingw-w64-x86_64-fribidi'
error: duplicated database entry 'mingw-w64-x86_64-gcc-libs'
error: duplicated database entry 'mingw-w64-x86_64-glib2'
error: duplicated database entry 'mingw-w64-x86_64-gmp'
error: duplicated database entry 'mingw-w64-x86_64-gobject-introspection-runtime'
error: duplicated database entry 'mingw-w64-x86_64-graphite2'
error: duplicated database entry 'mingw-w64-x86_64-gsettings-desktop-schemas'
error: duplicated database entry 'mingw-w64-x86_64-gtk3'
error: duplicated database entry 'mingw-w64-x86_64-harfbuzz'
error: duplicated database entry 'mingw-w64-x86_64-libffi'
error: duplicated database entry 'mingw-w64-x86_64-libjpeg-turbo'
error: duplicated database entry 'mingw-w64-x86_64-librsvg'
error: duplicated database entry 'mingw-w64-x86_64-libtasn1'
error: duplicated database entry 'mingw-w64-x86_64-libwinpthread-git'
error: duplicated database entry 'mingw-w64-x86_64-libxml2'
error: duplicated database entry 'mingw-w64-x86_64-ncurses'
error: duplicated database entry 'mingw-w64-x86_64-openssl'
error: duplicated database entry 'mingw-w64-x86_64-p11-kit'
error: duplicated database entry 'mingw-w64-x86_64-pcre'
error: duplicated database entry 'mingw-w64-x86_64-pixman'
error: duplicated database entry 'mingw-w64-x86_64-readline'
error: duplicated database entry 'mingw-w64-x86_64-sqlite3'
error: duplicated database entry 'mingw-w64-x86_64-tcl'
error: duplicated database entry 'mingw-w64-x86_64-tk'
error: duplicated database entry 'mingw-w64-x86_64-xz'
error: duplicated database entry 'mintty'
error: duplicated database entry 'ncurses'
error: duplicated database entry 'openssl'
error: duplicated database entry 'p11-kit'
error: duplicated database entry 'pacman'
error: duplicated database entry 'pacman-mirrors'
error: duplicated database entry 'pcre'
error: duplicated database entry 'sed'
error: duplicated database entry 'tzcode'
error: duplicated database entry 'util-linux'
error: duplicated database entry 'xz'
resolving dependencies...
looking for conflicting packages...
warning: dependency cycle detected:
warning: mingw-w64-x86_64-ffms2 will be installed before its mingw-w64-x86_64-ffmpeg dependency

Packages (37) mingw-w64-x86_64-SDL2-2.0.12-4  mingw-w64-x86_64-celt-0.11.3-4
              mingw-w64-x86_64-ffms2-2.23.1-1  mingw-w64-x86_64-giflib-5.2.1-1
              mingw-w64-x86_64-gnutls-3.6.13-1  mingw-w64-x86_64-gsm-1.0.19-1
              mingw-w64-x86_64-l-smash-2.14.5-1  mingw-w64-x86_64-lame-3.100-1
              mingw-w64-x86_64-lcms2-2.9-1  mingw-w64-x86_64-libass-0.14.0-1
              mingw-w64-x86_64-libbluray-1.2.0-1
              mingw-w64-x86_64-libcaca-0.99.beta19-5
              mingw-w64-x86_64-libidn2-2.3.0-1  mingw-w64-x86_64-libmfx-1.25-1
              mingw-w64-x86_64-libmodplug-0.8.9.0-1
              mingw-w64-x86_64-libogg-1.3.4-3
              mingw-w64-x86_64-libtheora-1.1.1-4
              mingw-w64-x86_64-libunistring-0.9.10-1
              mingw-w64-x86_64-libvorbis-1.3.6-1
              mingw-w64-x86_64-libvpx-1.8.2-1  mingw-w64-x86_64-libwebp-1.1.0-1
              mingw-w64-x86_64-nettle-3.5.1-1  mingw-w64-x86_64-openal-1.20.1-1
              mingw-w64-x86_64-opencore-amr-0.1.5-1
              mingw-w64-x86_64-openjpeg2-2.3.1-1  mingw-w64-x86_64-opus-1.3.1-1
              mingw-w64-x86_64-rtmpdump-git-r514.c5f04a5-1
              mingw-w64-x86_64-speex-1.2.0-1  mingw-w64-x86_64-speexdsp-1.2.0-1
              mingw-w64-x86_64-srt-1.4.1-1
              mingw-w64-x86_64-vulkan-headers-1.2.139-1
              mingw-w64-x86_64-vulkan-loader-1.2.137-1
              mingw-w64-x86_64-wavpack-5.2.0-1
              mingw-w64-x86_64-x264-git-r2991.1771b556-1
              mingw-w64-x86_64-x265-3.3-1  mingw-w64-x86_64-xvidcore-1.3.7-1
              mingw-w64-x86_64-ffmpeg-4.2.2-4

Total Installed Size:  168.83 MiB

:: Proceed with installation? [Y/n] y
(37/37) checking keys in keyring                   [#####################] 100%
(37/37) checking package integrity                 [#####################] 100%
(37/37) loading package files                      [#####################] 100%
(37/37) checking for file conflicts                [#####################] 100%
(37/37) checking available disk space              [#####################] 100%
:: Processing package changes...
( 1/37) installing mingw-w64-x86_64-libogg         [#####################] 100%
( 2/37) installing mingw-w64-x86_64-celt           [#####################] 100%
( 3/37) installing mingw-w64-x86_64-libunistring   [#####################] 100%
( 4/37) installing mingw-w64-x86_64-libidn2        [#####################] 100%
( 5/37) installing mingw-w64-x86_64-nettle         [#####################] 100%
( 6/37) installing mingw-w64-x86_64-gnutls         [#####################] 100%
( 7/37) installing mingw-w64-x86_64-gsm            [#####################] 100%
( 8/37) installing mingw-w64-x86_64-lame           [#####################] 100%
( 9/37) installing mingw-w64-x86_64-libass         [#####################] 100%
(10/37) installing mingw-w64-x86_64-libbluray      [#####################] 100%
(11/37) installing mingw-w64-x86_64-libcaca        [#####################] 100%
(12/37) installing mingw-w64-x86_64-libmfx         [#####################] 100%
(13/37) installing mingw-w64-x86_64-libmodplug     [#####################] 100%
(14/37) installing mingw-w64-x86_64-libvorbis      [#####################] 100%
(15/37) installing mingw-w64-x86_64-libtheora      [#####################] 100%
(16/37) installing mingw-w64-x86_64-libvpx         [#####################] 100%
(17/37) installing mingw-w64-x86_64-giflib         [#####################] 100%
(18/37) installing mingw-w64-x86_64-libwebp        [#####################] 100%
(19/37) installing mingw-w64-x86_64-openal         [#####################] 100%
(20/37) installing mingw-w64-x86_64-opencore-amr   [#####################] 100%
(21/37) installing mingw-w64-x86_64-lcms2          [#####################] 100%
(22/37) installing mingw-w64-x86_64-openjpeg2      [#####################] 100%
(23/37) installing mingw-w64-x86_64-opus           [#####################] 100%
(24/37) installing mingw-w64-x86_64-rtmpdump-git   [#####################] 100%
(25/37) installing mingw-w64-x86_64-vulkan-headers [#####################] 100%
(26/37) installing mingw-w64-x86_64-vulkan-loader  [#####################] 100%
(27/37) installing mingw-w64-x86_64-SDL2           [#####################] 100%
(28/37) installing mingw-w64-x86_64-speexdsp       [#####################] 100%
(29/37) installing mingw-w64-x86_64-speex          [#####################] 100%
(30/37) installing mingw-w64-x86_64-srt            [#####################] 100%
(31/37) installing mingw-w64-x86_64-wavpack        [#####################] 100%
(32/37) installing mingw-w64-x86_64-l-smash        [#####################] 100%
(33/37) installing mingw-w64-x86_64-ffms2          [#####################] 100%
(34/37) installing mingw-w64-x86_64-x264-git       [#####################] 100%
(35/37) installing mingw-w64-x86_64-x265           [#####################] 100%
(36/37) installing mingw-w64-x86_64-xvidcore       [#####################] 100%
(37/37) installing mingw-w64-x86_64-ffmpeg         [#####################] 100%

MINGW64 ~
$

**Comment by axcore** [comment]
I suggest completely uninstalling Tartube, and deleting the following folder (which contains both Tartube and FFmpeg):

`C:\Users\YOURNAME\AppData\Local\Tartube
`
...before reinstalling from scratch.

**Comment by TheDukexx99** [comment]
Was able to install in tartube after complete reinstall
Thanks
