### ISSUE TITLE
how to import database to Classic Mode, for use Click the + button to select a directory (folder). 

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#96]
how to import database Video to Classic Mode without re-download, use
Click the + button to select a directory (folder). All the videos are downloaded into this directory
![82298609-93d1a180-99de-11ea-9a89-7ca9570a9b70](https://user-images.githubusercontent.com/36833664/82719293-5e290300-9cd3-11ea-8973-c33ca51a6c76.png)

**Comment by axcore** [comment]
I don't understand you very well. Can you explain in more detail?

**Comment by candrapersada** [comment]
save video youtube use Click the + button to select a directory (folder). All the videos are downloaded into this directory
![82298609-93d1a180-99de-11ea-9a89-7ca9570a9b70](https://user-images.githubusercontent.com/36833664/82722753-9b04f200-9cf3-11ea-8665-047a906e9a1c.png)
from database

**Comment by axcore** [comment]
So:

1. In the Classic Mode Tab, you select a new destination (e.g. C:\myvideos )
2. In the Videos Tab, you add some channels, e.g. pewdiepie and T-Series
3. You want to download pewdiepie and T-Series into C:\myvideos

Is that right?

**Comment by candrapersada** [comment]
yes

**Comment by axcore** [comment]
[See this](https://github.com/axcore/tartube#download-all-videos-to-a-single-folder)

Click Edit > General download options... > Files > Filesystem
Select Download all videos into this folder
Select any folder you want

![unsorted](https://user-images.githubusercontent.com/37951926/82724137-d25fa880-9ccb-11ea-8eab-664566edc589.png)

**Comment by axcore** [comment]
It's not possible to save videos anywhere on the computer (for example, save pewdiepie to C:\myvideos\pewdiepie, save T-Series to D:\stuff\stuff\videos\tseries)

If would be possible, but only if I completely redesign Tartube.

**Comment by candrapersada** [comment]
if so is there a way how to move links video from Videos Tab to Classic Mode Tab with one click?

**Comment by axcore** [comment]
Yes, I added it in v2.1.016. (This version can only be downloaded from Github.)

To copy a video link from the Videos Tab to the Classic Mode Tab:

Right-click the video
Select **Add to Classic Mode Tab**

To copy a channel link from the Videos Tab to the Classic Mode Tab:

Right-click the channel
Select **Channel actions > Add to Classic Mode tab**

**Comment by axcore** [comment]
Closed for inactivity.
