### ISSUE TITLE
Missing folder

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#97]
I updated from 2.0.16 to 2.1.0. For some reason a folder is now missing. The folder still exists on my PC in the same location as other folders that are still shown on Tartube. I tried just re-adding a folder with the same name in Tartube but an error comes up saying the folder already exists. Any way to solve this?

**Comment by axcore** [comment]
Try **Edit > System preferences... > Filesytstem > DB Errors > Check DB**

**Comment by axcore** [comment]
v2.2.0 fixes an inconsistency in the database, that sounds a lot like this problem.
