### ISSUE TITLE
Error when downloading

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#99]
This comes up for various users, however the screenshot is just from 1 account, that happened all at once (12:46:33)

https://i.imgur.com/G2R9Byu.png

**Comment by axcore** [comment]
This appears to be a [youtube-dl](https://github.com/ytdl-org/youtube-dl/). I don't see any Tartube code in the traceback at all.

If you've enabled YouTube authentication, you could try disabling it. In Tartube's main window, click **Edit > General download options**. Click the **Show advanced download options** button if it's visible. Then click the **Advanced > Authentication tab**, and reset all the options in that tab.
